"""MongoDB Database Administrator Certification"""

CERTIFICATION = {
    "name": "MongoDB Database Administrator",
    "description": "MongoDB NoSQL database administration, sharding, and replica sets management",
    "slug": "mongodb-database-administrator",
    "level": "Professional",
    "duration": 15,
    "questions_count": 5,
    "category_slug": "database",
    "is_active": True,
}

QUESTIONS = [{"text": "What is a replica set in MongoDB?",
              "explanation": "A replica set is a group of MongoDB processes that maintain the same data set, providing redundancy and high availability. It consists of one primary node and multiple secondary nodes.",
              "reference": "https://docs.mongodb.com/manual/replication/",
              "points": 1,
              "answers": [{"text": "A group of MongoDB processes maintaining the same data for high availability",
                           "is_correct": True,
                           },
                          {"text": "A collection of similar documents",
                           "is_correct": False},
                          {"text": "A backup storage mechanism",
                           "is_correct": False},
                          {"text": "A query optimization technique",
                           "is_correct": False},
                          ],
              },
             {"text": "What is sharding in MongoDB?",
              "explanation": "Sharding is MongoDB's approach to horizontal scaling, distributing data across multiple machines (shards) to handle large datasets and high throughput operations.",
              "reference": "https://docs.mongodb.com/manual/sharding/",
              "points": 1,
              "answers": [{"text": "Horizontal scaling by distributing data across multiple machines",
                           "is_correct": True,
                           },
                          {"text": "Vertical scaling by adding more CPU and RAM",
                           "is_correct": False,
                           },
                          {"text": "Creating indexes on collections",
                           "is_correct": False},
                          {"text": "Compressing database files",
                           "is_correct": False},
                          ],
              },
             {"text": "Which MongoDB command shows database statistics?",
              "explanation": "The db.stats() command provides statistics about the database including size, number of collections, indexes, and storage information.",
              "reference": "https://docs.mongodb.com/manual/reference/method/db.stats/",
              "points": 1,
              "answers": [{"text": "db.stats()",
                           "is_correct": True},
                          {"text": "show stats",
                           "is_correct": False},
                          {"text": "db.info()",
                           "is_correct": False},
                          {"text": "db.status()",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of MongoDB's oplog?",
              "explanation": "The oplog (operations log) is a special capped collection that keeps a rolling record of all operations that modify data in a database, used for replication and change streams.",
              "reference": "https://docs.mongodb.com/manual/core/replica-set-oplog/",
              "points": 1,
              "answers": [{"text": "Records all data modification operations for replication",
                           "is_correct": True,
                           },
                          {"text": "Stores user authentication data",
                           "is_correct": False},
                          {"text": "Contains database configuration settings",
                           "is_correct": False},
                          {"text": "Logs query performance metrics",
                           "is_correct": False},
                          ],
              },
             {"text": "Which MongoDB storage engine is the default?",
              "explanation": "WiredTiger is MongoDB's default storage engine, providing document-level concurrency control, compression, and encryption at rest capabilities.",
              "reference": "https://docs.mongodb.com/manual/core/wiredtiger/",
              "points": 1,
              "answers": [{"text": "WiredTiger",
                           "is_correct": True},
                          {"text": "MMAPv1",
                           "is_correct": False},
                          {"text": "InMemory",
                           "is_correct": False},
                          {"text": "RocksDB",
                           "is_correct": False},
                          ],
              },
             ]
