"""Cisco Certified Internetwork Expert (CCIE) Certification"""

CERTIFICATION = {
    "name": "Cisco Certified Internetwork Expert (CCIE)",
    "description": "Expert-level networking knowledge and advanced troubleshooting skills",
    "slug": "cisco-ccie",
    "level": "Expert",
    "duration": 15,
    "questions_count": 5,
    "category_slug": "networking",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which OSPF LSA type is used to describe networks within an area?",
        "explanation": "LSA Type 2 (Network LSA) is generated by the Designated Router (DR) and describes the networks within an area, listing all routers connected to that network.",
        "reference": "https://www.cisco.com/c/en/us/support/docs/ip/open-shortest-path-first-ospf/7039-1.html",
        "points": 1,
        "answers": [
            {"text": "Type 1 (Router LSA)", "is_correct": False},
            {"text": "Type 2 (Network LSA)", "is_correct": True},
            {"text": "Type 3 (Summary LSA)", "is_correct": False},
            {"text": "Type 5 (External LSA)", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of BGP path attributes in route selection?",
        "explanation": "BGP path attributes are used to influence the BGP best path selection algorithm. Attributes like LOCAL_PREF, AS_PATH, and MED help determine the preferred route to a destination.",
        "reference": "https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/13753-25.html",
        "points": 1,
        "answers": [
            {"text": "Encrypt routing updates", "is_correct": False},
            {"text": "Influence route selection", "is_correct": True},
            {"text": "Compress routing tables", "is_correct": False},
            {"text": "Authenticate peers", "is_correct": False},
        ],
    },
    {
        "text": "In MPLS networks, what is the function of the Label Distribution Protocol (LDP)?",
        "explanation": "LDP is used to distribute labels between MPLS routers, enabling the creation of Label Switched Paths (LSPs) for efficient packet forwarding.",
        "reference": "https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/mp_ldp/configuration/xe-3s/mp-ldp-xe-3s-book.html",
        "points": 1,
        "answers": [
            {"text": "Route advertisement", "is_correct": False},
            {"text": "Label distribution", "is_correct": True},
            {"text": "Traffic engineering", "is_correct": False},
            {"text": "Quality of Service", "is_correct": False},
        ],
    },
    {
        "text": "What is the default administrative distance for EIGRP internal routes?",
        "explanation": "EIGRP internal routes have an administrative distance of 90, making them more preferred than OSPF (110) but less preferred than directly connected (0) and static routes (1).",
        "reference": "https://www.cisco.com/c/en/us/support/docs/ip/enhanced-interior-gateway-routing-protocol-eigrp/8651-21.html",
        "points": 1,
        "answers": [
            {"text": "90", "is_correct": True},
            {"text": "100", "is_correct": False},
            {"text": "110", "is_correct": False},
            {"text": "120", "is_correct": False},
        ],
    },
    {
        "text": "Which QoS mechanism is used to prevent network congestion by dropping packets before queues become full?",
        "explanation": "Random Early Detection (RED) and Weighted Random Early Detection (WRED) are congestion avoidance mechanisms that drop packets probabilistically before queues become full.",
        "reference": "https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/qos_conav/configuration/15-mt/qos-conav-15-mt-book.html",
        "points": 1,
        "answers": [
            {"text": "Traffic Shaping", "is_correct": False},
            {"text": "WRED (Weighted Random Early Detection)", "is_correct": True},
            {"text": "Priority Queuing", "is_correct": False},
            {"text": "Traffic Policing", "is_correct": False},
        ],
    },
]
