"""Docker Certified Associate Certification"""

CERTIFICATION = {
    "name": "Docker Certified Associate",
    "description": "Docker containerization and orchestration expertise",
    "slug": "docker-certified-associate",
    "level": "Associate",
    "duration": 15,
    "questions_count": 5,
    "category_slug": "devops",
    "is_active": True,
}

QUESTIONS = [{"text": "What is the difference between a Docker image and a Docker container?",
              "explanation": "A Docker image is a read-only template used to create containers, while a Docker container is a running instance of an image. Images are immutable, containers are mutable and can be started, stopped, and deleted.",
              "reference": "https://docs.docker.com/get-started/overview/",
              "points": 1,
              "answers": [{"text": "Images and containers are the same thing",
                           "is_correct": False},
                          {"text": "Image is a template, container is a running instance",
                           "is_correct": True,
                           },
                          {"text": "Images are faster than containers",
                           "is_correct": False},
                          {"text": "Containers are stored, images are running",
                           "is_correct": False},
                          ],
              },
             {"text": "Which Dockerfile instruction is used to copy files from the host to the image?",
              "explanation": "The COPY instruction copies files or directories from the build context (host) into the Docker image. ADD can also copy files but has additional features like URL support and tar extraction.",
              "reference": "https://docs.docker.com/engine/reference/builder/#copy",
              "points": 1,
              "answers": [{"text": "MOVE",
                           "is_correct": False},
                          {"text": "COPY",
                           "is_correct": True},
                          {"text": "TRANSFER",
                           "is_correct": False},
                          {"text": "IMPORT",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Docker Compose used for?",
              "explanation": "Docker Compose is a tool for defining and running multi-container Docker applications. It uses a YAML file to configure application services and can start all services with a single command.",
              "reference": "https://docs.docker.com/compose/",
              "points": 1,
              "answers": [{"text": "Building single container applications",
                           "is_correct": False},
                          {"text": "Defining and running multi-container applications",
                           "is_correct": True,
                           },
                          {"text": "Monitoring container performance",
                           "is_correct": False},
                          {"text": "Managing Docker registry",
                           "is_correct": False},
                          ],
              },
             {"text": "Which command is used to build a Docker image from a Dockerfile?",
              "explanation": "The 'docker build' command is used to build Docker images from a Dockerfile. It takes the build context and follows the instructions in the Dockerfile to create a new image.",
              "reference": "https://docs.docker.com/engine/reference/commandline/build/",
              "points": 1,
              "answers": [{"text": "docker create",
                           "is_correct": False},
                          {"text": "docker build",
                           "is_correct": True},
                          {"text": "docker make",
                           "is_correct": False},
                          {"text": "docker compile",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a Docker volume used for?",
              "explanation": "Docker volumes are used to persist data generated and used by Docker containers. Volumes exist outside the container lifecycle and can be shared between containers.",
              "reference": "https://docs.docker.com/storage/volumes/",
              "points": 1,
              "answers": [{"text": "To increase container performance",
                           "is_correct": False},
                          {"text": "To persist and share data between containers",
                           "is_correct": True,
                           },
                          {"text": "To network containers together",
                           "is_correct": False},
                          {"text": "To monitor container logs",
                           "is_correct": False},
                          ],
              },
             ]
