"""Ansible Automation Platform Specialist Certification"""

CERTIFICATION = {
    "name": "Red Hat Certified Specialist in Ansible Automation",
    "description": "Ansible automation, configuration management, and orchestration expertise",
    "slug": "ansible-automation-specialist",
    "level": "Specialist",
    "duration": 15,
    "questions_count": 5,
    "category_slug": "devops",
    "is_active": True,
}

QUESTIONS = [{"text": "What is an Ansible playbook?",
              "explanation": "An Ansible playbook is a YAML file that contains a series of procedures (plays) that should be executed on remote hosts. Playbooks are the basis for configuration management and deployment.",
              "reference": "https://docs.ansible.com/ansible/latest/user_guide/playbooks.html",
              "points": 1,
              "answers": [{"text": "A YAML file containing automation procedures for remote hosts",
                           "is_correct": True,
                           },
                          {"text": "A GUI for managing Ansible",
                           "is_correct": False},
                          {"text": "A database of server configurations",
                           "is_correct": False},
                          {"text": "A monitoring dashboard",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the Ansible inventory?",
              "explanation": "The Ansible inventory is a file or collection of files that defines the hosts and groups of hosts that Ansible will manage. It can be static (INI or YAML files) or dynamic (scripts or plugins).",
              "reference": "https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html",
              "points": 1,
              "answers": [{"text": "A file defining hosts and groups that Ansible manages",
                           "is_correct": True,
                           },
                          {"text": "A list of available Ansible modules",
                           "is_correct": False},
                          {"text": "A backup of server configurations",
                           "is_correct": False},
                          {"text": "A performance monitoring tool",
                           "is_correct": False},
                          ],
              },
             {"text": "What is an Ansible role?",
              "explanation": "An Ansible role is a way to organize playbooks and related files in a standardized directory structure. Roles make it easier to reuse and share automation content.",
              "reference": "https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html",
              "points": 1,
              "answers": [{"text": "A standardized way to organize and reuse playbooks",
                           "is_correct": True,
                           },
                          {"text": "A user permission level",
                           "is_correct": False},
                          {"text": "A server function assignment",
                           "is_correct": False},
                          {"text": "A backup strategy",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between Ansible's 'copy' and 'template' modules?",
              "explanation": "The 'copy' module transfers files as-is from the local machine to remote hosts, while the 'template' module processes Jinja2 templates and variables before copying the rendered content to remote hosts.",
              "reference": "https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html",
              "points": 1,
              "answers": [{"text": "Copy transfers files as-is; template processes Jinja2 templates first",
                           "is_correct": True,
                           },
                          {"text": "Copy is faster than template",
                           "is_correct": False},
                          {"text": "Template is deprecated",
                           "is_correct": False},
                          {"text": "They do exactly the same thing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Ansible Vault?",
              "explanation": "Ansible Vault is a feature that allows you to encrypt sensitive data such as passwords, keys, and other secrets within Ansible files, keeping them secure while still allowing automation to function.",
              "reference": "https://docs.ansible.com/ansible/latest/user_guide/vault.html",
              "points": 1,
              "answers": [{"text": "A feature for encrypting sensitive data in Ansible files",
                           "is_correct": True,
                           },
                          {"text": "A backup storage system",
                           "is_correct": False},
                          {"text": "A performance optimization tool",
                           "is_correct": False},
                          {"text": "A GUI for Ansible management",
                           "is_correct": False},
                          ],
              },
             ]
