"""Certified Ethical Hacker (CEH) Certification"""

CERTIFICATION = {
    "name": "Certified Ethical Hacker (CEH)",
    "description": "Ethical hacking and penetration testing",
    "slug": "certified-ethical-hacker-ceh",
    "level": "Professional",
    "duration": 333,
    "questions_count": 111,
    "category_slug": "cybersecurity",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is the first phase of ethical hacking?",
        "explanation": "Reconnaissance (or Information Gathering) is the first phase where hackers gather information about the target system.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Scanning", "is_correct": False},
            {"text": "Reconnaissance", "is_correct": True},
            {"text": "Enumeration", "is_correct": False},
            {"text": "System Hacking", "is_correct": False},
        ],
    },
    {
        "text": "Which type of reconnaissance involves directly interacting with the target system?",
        "explanation": "Active reconnaissance involves direct interaction with the target system, which can be detected by intrusion detection systems.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Passive reconnaissance", "is_correct": False},
            {"text": "Active reconnaissance", "is_correct": True},
            {"text": "Indirect reconnaissance", "is_correct": False},
            {"text": "Social reconnaissance", "is_correct": False},
        ],
    },
    {
        "text": "What tool is commonly used for DNS enumeration?",
        "explanation": "Nslookup is a network administration command-line tool for querying the Domain Name System (DNS).",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Nmap", "is_correct": False},
            {"text": "Wireshark", "is_correct": False},
            {"text": "Nslookup", "is_correct": True},
            {"text": "Netcat", "is_correct": False},
        ],
    },
    {
        "text": "Which search engine is specifically designed for finding Internet-connected devices?",
        "explanation": "Shodan is a search engine that lets users find specific types of computers connected to the Internet using a variety of filters.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Google", "is_correct": False},
            {"text": "Bing", "is_correct": False},
            {"text": "Shodan", "is_correct": True},
            {"text": "DuckDuckGo", "is_correct": False},
        ],
    },
    {
        "text": "What information can be gathered using WHOIS queries?",
        "explanation": "WHOIS queries provide domain registration information including registrant details, name servers, and registration dates.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Open ports only", "is_correct": False},
            {"text": "Domain registration information", "is_correct": True},
            {"text": "Operating system version", "is_correct": False},
            {"text": "Network topology", "is_correct": False},
        ],
    },
    {
        "text": "Which Google dorking operator is used to find specific file types?",
        "explanation": "The 'filetype:' operator in Google dorking is used to search for specific file types like PDF, DOC, XLS, etc.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "site:", "is_correct": False},
            {"text": "filetype:", "is_correct": True},
            {"text": "inurl:", "is_correct": False},
            {"text": "intitle:", "is_correct": False},
        ],
    },
    {
        "text": "What is footprinting in the context of ethical hacking?",
        "explanation": "Footprinting is the process of collecting information about a target network and its environment through passive and active reconnaissance.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Exploiting vulnerabilities", "is_correct": False},
            {"text": "Collecting target information", "is_correct": True},
            {"text": "Installing backdoors", "is_correct": False},
            {"text": "Covering attack traces", "is_correct": False},
        ],
    },
    {
        "text": "Which protocol is commonly used for email footprinting?",
        "explanation": "SMTP (Simple Mail Transfer Protocol) is commonly used for email footprinting to gather information about email servers and users.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "HTTP", "is_correct": False},
            {"text": "FTP", "is_correct": False},
            {"text": "SMTP", "is_correct": True},
            {"text": "SNMP", "is_correct": False},
        ],
    },
    {
        "text": "What type of information can be gathered from social networking sites during reconnaissance?",
        "explanation": "Social networking sites can provide personal information, relationships, interests, locations, and potential social engineering vectors.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Network topology only", "is_correct": False},
            {"text": "Personal and professional information", "is_correct": True},
            {"text": "System vulnerabilities only", "is_correct": False},
            {"text": "Encryption keys", "is_correct": False},
        ],
    },
    {
        "text": "Which tool can be used for competitive intelligence gathering?",
        "explanation": "Maltego is a powerful tool for competitive intelligence gathering and link analysis that helps visualize relationships between entities.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Nmap", "is_correct": False},
            {"text": "Maltego", "is_correct": True},
            {"text": "Metasploit", "is_correct": False},
            {"text": "Burp Suite", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of banner grabbing in reconnaissance?",
        "explanation": "Banner grabbing is used to identify services, applications, and their versions running on target systems by capturing service banners.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "To exploit vulnerabilities", "is_correct": False},
            {"text": "To identify services and versions", "is_correct": True},
            {"text": "To install malware", "is_correct": False},
            {"text": "To cover tracks", "is_correct": False},
        ],
    },
    {
        "text": "Which Nmap scan type is considered stealthy and doesn't complete the TCP handshake?",
        "explanation": "SYN scan (half-open scan) sends SYN packets but doesn't complete the three-way handshake, making it stealthier than connect scans.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "TCP Connect scan", "is_correct": False},
            {"text": "SYN scan", "is_correct": True},
            {"text": "UDP scan", "is_correct": False},
            {"text": "FIN scan", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary purpose of port scanning?",
        "explanation": "Port scanning is used to discover which ports are open on a target system and what services are running on those ports.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "To exploit vulnerabilities", "is_correct": False},
            {"text": "To discover open ports and services", "is_correct": True},
            {"text": "To install backdoors", "is_correct": False},
            {"text": "To steal data", "is_correct": False},
        ],
    },
    {
        "text": "Which enumeration technique is used to gather information about NetBIOS shares?",
        "explanation": "NetBIOS enumeration uses commands like 'net view' and tools like enum4linux to discover shared resources on Windows systems.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "SNMP enumeration", "is_correct": False},
            {"text": "NetBIOS enumeration", "is_correct": True},
            {"text": "LDAP enumeration", "is_correct": False},
            {"text": "DNS enumeration", "is_correct": False},
        ],
    },
    {
        "text": "What does a ping sweep accomplish in network scanning?",
        "explanation": "A ping sweep sends ICMP echo requests to multiple IP addresses to identify which hosts are alive and responding on the network.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Identifies live hosts", "is_correct": True},
            {"text": "Exploits vulnerabilities", "is_correct": False},
            {"text": "Steals passwords", "is_correct": False},
            {"text": "Installs malware", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for SNMP enumeration?",
        "explanation": "SNMPwalk is a command-line tool that uses SNMP GETNEXT requests to query a network entity for a tree of information.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Nmap", "is_correct": False},
            {"text": "SNMPwalk", "is_correct": True},
            {"text": "Wireshark", "is_correct": False},
            {"text": "Burp Suite", "is_correct": False},
        ],
    },
    {
        "text": "What is OS fingerprinting?",
        "explanation": "OS fingerprinting is the process of determining the operating system running on a remote target system by analyzing network traffic patterns.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Identifying the operating system", "is_correct": True},
            {"text": "Stealing user credentials", "is_correct": False},
            {"text": "Installing backdoors", "is_correct": False},
            {"text": "Encrypting data", "is_correct": False},
        ],
    },
    {
        "text": "Which Nmap option is used for aggressive scanning?",
        "explanation": "The -A option in Nmap enables aggressive scanning, which includes OS detection, version detection, script scanning, and traceroute.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "-sS", "is_correct": False},
            {"text": "-sT", "is_correct": False},
            {"text": "-A", "is_correct": True},
            {"text": "-sU", "is_correct": False},
        ],
    },
    {
        "text": "What information can LDAP enumeration reveal?",
        "explanation": "LDAP enumeration can reveal user accounts, group memberships, organizational units, and directory structure information.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Network topology only", "is_correct": False},
            {"text": "User accounts and directory information", "is_correct": True},
            {"text": "Encryption keys only", "is_correct": False},
            {"text": "Hardware specifications", "is_correct": False},
        ],
    },
    {
        "text": "Which scanning technique sends packets with no flags set?",
        "explanation": "Null scan sends TCP packets with no flags set. If the port is closed, the target should respond with RST packet.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "SYN scan", "is_correct": False},
            {"text": "FIN scan", "is_correct": False},
            {"text": "Null scan", "is_correct": True},
            {"text": "Xmas scan", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of vulnerability scanning?",
        "explanation": "Vulnerability scanning identifies security weaknesses, misconfigurations, and known vulnerabilities in systems and applications.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "To identify security vulnerabilities", "is_correct": True},
            {"text": "To steal sensitive data", "is_correct": False},
            {"text": "To install malware", "is_correct": False},
            {"text": "To crash systems", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary goal of the gaining access phase in ethical hacking?",
        "explanation": "The gaining access phase focuses on exploiting vulnerabilities to gain unauthorized access to target systems.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Gathering information", "is_correct": False},
            {"text": "Exploiting vulnerabilities", "is_correct": True},
            {"text": "Covering tracks", "is_correct": False},
            {"text": "Maintaining access", "is_correct": False},
        ],
    },
    {
        "text": "Which technique involves guessing passwords using a list of common passwords?",
        "explanation": "Dictionary attack uses a predefined list of common passwords to attempt unauthorized access to user accounts.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Brute force attack", "is_correct": False},
            {"text": "Dictionary attack", "is_correct": True},
            {"text": "Rainbow table attack", "is_correct": False},
            {"text": "Hybrid attack", "is_correct": False},
        ],
    },
    {
        "text": "What is privilege escalation?",
        "explanation": "Privilege escalation is the act of exploiting a bug or vulnerability to gain elevated access to resources that are normally restricted.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Gaining higher-level permissions", "is_correct": True},
            {"text": "Stealing user credentials", "is_correct": False},
            {"text": "Installing antivirus software", "is_correct": False},
            {"text": "Encrypting files", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for password cracking?",
        "explanation": "John the Ripper is a popular password cracking tool that supports various password hash formats and attack methods.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Nmap", "is_correct": False},
            {"text": "Wireshark", "is_correct": False},
            {"text": "John the Ripper", "is_correct": True},
            {"text": "Burp Suite", "is_correct": False},
        ],
    },
    {
        "text": "What is a buffer overflow attack?",
        "explanation": "Buffer overflow occurs when more data is written to a buffer than it can hold, potentially allowing attackers to execute malicious code.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Overwriting memory boundaries", "is_correct": True},
            {"text": "Stealing network traffic", "is_correct": False},
            {"text": "Blocking network access", "is_correct": False},
            {"text": "Encrypting system files", "is_correct": False},
        ],
    },
    {
        "text": "Which Windows utility can be used to view and modify the registry?",
        "explanation": "Regedit is the Windows Registry Editor that allows users to view and modify the Windows registry database.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "cmd.exe", "is_correct": False},
            {"text": "regedit.exe", "is_correct": True},
            {"text": "notepad.exe", "is_correct": False},
            {"text": "explorer.exe", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of a keylogger?",
        "explanation": "A keylogger records keystrokes made by a user, often used maliciously to capture passwords and sensitive information.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "To record keystrokes", "is_correct": True},
            {"text": "To block network traffic", "is_correct": False},
            {"text": "To encrypt files", "is_correct": False},
            {"text": "To scan for vulnerabilities", "is_correct": False},
        ],
    },
    {
        "text": "Which attack technique exploits the way applications handle user input?",
        "explanation": "Input validation attacks exploit insufficient input validation in applications, including SQL injection, XSS, and command injection.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Input validation attacks", "is_correct": True},
            {"text": "Man-in-the-middle attacks", "is_correct": False},
            {"text": "Denial of service attacks", "is_correct": False},
            {"text": "Social engineering attacks", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between local and remote exploits?",
        "explanation": "Local exploits require access to the target system, while remote exploits can be executed over a network without local access.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Local requires system access, remote works over network",
                "is_correct": True,
            },
            {"text": "Local is faster than remote", "is_correct": False},
            {"text": "Local is more dangerous than remote", "is_correct": False},
            {"text": "No difference between them", "is_correct": False},
        ],
    },
    {
        "text": "Which technique involves hiding executable code within seemingly harmless files?",
        "explanation": "Steganography is the practice of concealing malicious code or data within other non-suspicious files or media.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Encryption", "is_correct": False},
            {"text": "Steganography", "is_correct": True},
            {"text": "Compression", "is_correct": False},
            {"text": "Hashing", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of maintaining access in ethical hacking?",
        "explanation": "Maintaining access ensures that attackers can return to compromised systems without having to re-exploit vulnerabilities.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "To ensure persistent access to compromised systems",
                "is_correct": True,
            },
            {"text": "To gather initial information", "is_correct": False},
            {"text": "To scan for vulnerabilities", "is_correct": False},
            {"text": "To document findings", "is_correct": False},
        ],
    },
    {
        "text": "Which type of malware provides remote access to a compromised system?",
        "explanation": "A Remote Access Trojan (RAT) allows attackers to remotely control a compromised system as if they were sitting at it.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Virus", "is_correct": False},
            {"text": "Remote Access Trojan (RAT)", "is_correct": True},
            {"text": "Worm", "is_correct": False},
            {"text": "Adware", "is_correct": False},
        ],
    },
    {
        "text": "What is a rootkit?",
        "explanation": "A rootkit is malicious software designed to remain hidden on a computer while maintaining persistent access to the system.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "A network scanning tool", "is_correct": False},
            {"text": "Hidden malware that maintains system access", "is_correct": True},
            {"text": "A password cracking utility", "is_correct": False},
            {"text": "A vulnerability scanner", "is_correct": False},
        ],
    },
    {
        "text": "Which technique involves removing evidence of an attack from system logs?",
        "explanation": "Log manipulation involves altering or deleting system logs to hide traces of unauthorized activities and attacks.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Privilege escalation", "is_correct": False},
            {"text": "Log manipulation", "is_correct": True},
            {"text": "Buffer overflow", "is_correct": False},
            {"text": "Social engineering", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of a backdoor?",
        "explanation": "A backdoor provides an alternative method of accessing a system, often bypassing normal authentication mechanisms.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "To provide alternative system access", "is_correct": True},
            {"text": "To scan for vulnerabilities", "is_correct": False},
            {"text": "To encrypt communications", "is_correct": False},
            {"text": "To monitor network traffic", "is_correct": False},
        ],
    },
    {
        "text": "Which Windows command can be used to clear event logs?",
        "explanation": "The 'wevtutil' command in Windows can be used to clear event logs, helping attackers cover their tracks.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "netstat", "is_correct": False},
            {"text": "wevtutil", "is_correct": True},
            {"text": "ipconfig", "is_correct": False},
            {"text": "tasklist", "is_correct": False},
        ],
    },
    {
        "text": "What is timestomping?",
        "explanation": "Timestomping is the technique of modifying file timestamps to hide when files were created, modified, or accessed.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Modifying file timestamps", "is_correct": True},
            {"text": "Encrypting file contents", "is_correct": False},
            {"text": "Compressing files", "is_correct": False},
            {"text": "Creating file backups", "is_correct": False},
        ],
    },
    {
        "text": "Which technique helps establish persistent access through scheduled tasks?",
        "explanation": "Task scheduling allows attackers to execute malicious code at specific times or events, maintaining persistent access.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Task scheduling", "is_correct": True},
            {"text": "Port forwarding", "is_correct": False},
            {"text": "DNS tunneling", "is_correct": False},
            {"text": "ARP spoofing", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary goal of the covering tracks phase?",
        "explanation": "Covering tracks aims to hide evidence of the attack and maintain stealth to avoid detection by security systems.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "To hide evidence of the attack", "is_correct": True},
            {"text": "To gain initial access", "is_correct": False},
            {"text": "To escalate privileges", "is_correct": False},
            {"text": "To gather information", "is_correct": False},
        ],
    },
    {
        "text": "Which technique involves hiding files and processes from system administrators?",
        "explanation": "Stealth techniques include hiding files, processes, and network connections to avoid detection by system monitoring tools.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Stealth techniques", "is_correct": True},
            {"text": "Encryption methods", "is_correct": False},
            {"text": "Authentication bypass", "is_correct": False},
            {"text": "Network routing", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary difference between a virus and a worm?",
        "explanation": "A virus requires a host file to replicate, while a worm can self-replicate and spread across networks without a host file.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Virus needs a host file, worm self-replicates",
                "is_correct": True,
            },
            {"text": "Virus is faster than worm", "is_correct": False},
            {"text": "Virus is more dangerous than worm", "is_correct": False},
            {"text": "No difference between them", "is_correct": False},
        ],
    },
    {
        "text": "Which type of malware appears to be legitimate software but contains malicious code?",
        "explanation": "A Trojan horse appears to be legitimate software but contains hidden malicious functionality that executes when the program runs.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Virus", "is_correct": False},
            {"text": "Worm", "is_correct": False},
            {"text": "Trojan horse", "is_correct": True},
            {"text": "Rootkit", "is_correct": False},
        ],
    },
    {
        "text": "What is ransomware?",
        "explanation": "Ransomware is malicious software that encrypts a victim's files and demands payment for the decryption key.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Software that displays advertisements", "is_correct": False},
            {"text": "Malware that encrypts files for ransom", "is_correct": True},
            {"text": "Software that monitors keystrokes", "is_correct": False},
            {"text": "Software that steals passwords", "is_correct": False},
        ],
    },
    {
        "text": "Which vulnerability assessment approach involves testing without prior knowledge of the system?",
        "explanation": "Black box testing involves testing a system without any prior knowledge of its internal structure or implementation.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "White box testing", "is_correct": False},
            {"text": "Black box testing", "is_correct": True},
            {"text": "Gray box testing", "is_correct": False},
            {"text": "Clear box testing", "is_correct": False},
        ],
    },
    {
        "text": "What is a zero-day vulnerability?",
        "explanation": "A zero-day vulnerability is a security flaw that is unknown to security vendors and has no available patch or fix.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "A vulnerability with no available patch", "is_correct": True},
            {"text": "A vulnerability found on day zero", "is_correct": False},
            {"text": "A vulnerability that causes system crash", "is_correct": False},
            {"text": "A vulnerability in web applications only", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for automated vulnerability scanning?",
        "explanation": "Nessus is a popular automated vulnerability scanner that identifies security vulnerabilities in networks and systems.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Metasploit", "is_correct": False},
            {"text": "Nessus", "is_correct": True},
            {"text": "Wireshark", "is_correct": False},
            {"text": "John the Ripper", "is_correct": False},
        ],
    },
    {
        "text": "What is spyware?",
        "explanation": "Spyware is malicious software that secretly gathers information about a user's activities without their knowledge or consent.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Software that blocks network access", "is_correct": False},
            {
                "text": "Software that secretly gathers user information",
                "is_correct": True,
            },
            {"text": "Software that encrypts files", "is_correct": False},
            {"text": "Software that displays error messages", "is_correct": False},
        ],
    },
    {
        "text": "Which technique involves analyzing malware in a controlled environment?",
        "explanation": "Malware sandboxing involves executing malware in an isolated, controlled environment to analyze its behavior safely.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Static analysis", "is_correct": False},
            {"text": "Sandboxing", "is_correct": True},
            {"text": "Code review", "is_correct": False},
            {"text": "Penetration testing", "is_correct": False},
        ],
    },
    {
        "text": "What is a botnet?",
        "explanation": "A botnet is a network of compromised computers (bots) that can be remotely controlled by cybercriminals for malicious activities.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "A network of compromised computers", "is_correct": True},
            {"text": "A type of firewall", "is_correct": False},
            {"text": "A vulnerability scanner", "is_correct": False},
            {"text": "An encryption algorithm", "is_correct": False},
        ],
    },
    {
        "text": "Which vulnerability category includes improper input validation?",
        "explanation": "Input validation vulnerabilities include SQL injection, XSS, and command injection, all related to improper handling of user input.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Authentication vulnerabilities", "is_correct": False},
            {"text": "Input validation vulnerabilities", "is_correct": True},
            {"text": "Cryptographic vulnerabilities", "is_correct": False},
            {"text": "Configuration vulnerabilities", "is_correct": False},
        ],
    },
    {
        "text": "What is social engineering in cybersecurity?",
        "explanation": "Social engineering is the psychological manipulation of people to divulge confidential information or perform actions that compromise security.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Psychological manipulation for security breach",
                "is_correct": True,
            },
            {"text": "Technical vulnerability exploitation", "is_correct": False},
            {"text": "Network traffic analysis", "is_correct": False},
            {"text": "System configuration hardening", "is_correct": False},
        ],
    },
    {
        "text": "Which social engineering technique involves creating a fabricated scenario to engage victims?",
        "explanation": "Pretexting involves creating a fabricated scenario or False identity to engage with victims and extract information.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Phishing", "is_correct": False},
            {"text": "Pretexting", "is_correct": True},
            {"text": "Baiting", "is_correct": False},
            {"text": "Tailgating", "is_correct": False},
        ],
    },
    {
        "text": "What is phishing?",
        "explanation": "Phishing is a social engineering attack that uses fraudulent emails or websites to trick users into revealing sensitive information.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Physical intrusion into buildings", "is_correct": False},
            {"text": "Fraudulent emails to steal information", "is_correct": True},
            {"text": "Network traffic interception", "is_correct": False},
            {"text": "System vulnerability scanning", "is_correct": False},
        ],
    },
    {
        "text": "What is session hijacking?",
        "explanation": "Session hijacking involves taking control of a user's web session by stealing or predicting session tokens or cookies.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Taking control of user's web session", "is_correct": True},
            {"text": "Blocking network connections", "is_correct": False},
            {"text": "Encrypting session data", "is_correct": False},
            {"text": "Creating new user sessions", "is_correct": False},
        ],
    },
    {
        "text": "Which technique involves following authorized personnel into restricted areas?",
        "explanation": "Tailgating (or piggybacking) involves following authorized personnel through access-controlled doors or areas without authorization.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Shoulder surfing", "is_correct": False},
            {"text": "Tailgating", "is_correct": True},
            {"text": "Dumpster diving", "is_correct": False},
            {"text": "Eavesdropping", "is_correct": False},
        ],
    },
    {
        "text": "What is spear phishing?",
        "explanation": "Spear phishing is a targeted phishing attack directed at specific individuals or organizations, often using personalized information.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Mass email phishing campaign", "is_correct": False},
            {"text": "Targeted phishing attack", "is_correct": True},
            {"text": "Phone-based social engineering", "is_correct": False},
            {"text": "Physical security breach", "is_correct": False},
        ],
    },
    {
        "text": "Which attack intercepts communication between two parties?",
        "explanation": "Man-in-the-middle (MITM) attacks intercept and potentially alter communications between two parties without their knowledge.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Denial of service", "is_correct": False},
            {"text": "Man-in-the-middle", "is_correct": True},
            {"text": "Buffer overflow", "is_correct": False},
            {"text": "SQL injection", "is_correct": False},
        ],
    },
    {
        "text": "What is vishing?",
        "explanation": "Vishing (voice phishing) is a social engineering attack that uses phone calls to trick victims into revealing sensitive information.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Email-based phishing", "is_correct": False},
            {"text": "Voice-based phishing", "is_correct": True},
            {"text": "SMS-based phishing", "is_correct": False},
            {"text": "Website-based phishing", "is_correct": False},
        ],
    },
    {
        "text": "Which technique involves observing someone enter passwords or PINs?",
        "explanation": "Shoulder surfing involves watching someone enter confidential information like passwords, PINs, or credit card numbers.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Shoulder surfing", "is_correct": True},
            {"text": "Dumpster diving", "is_correct": False},
            {"text": "Tailgating", "is_correct": False},
            {"text": "Pretexting", "is_correct": False},
        ],
    },
    {
        "text": "What is session fixation?",
        "explanation": "Session fixation is an attack where an attacker fixes a user's session ID before the user logs in, then hijacks the session.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Fixing user's session ID before login", "is_correct": True},
            {"text": "Repairing broken sessions", "is_correct": False},
            {"text": "Creating permanent sessions", "is_correct": False},
            {"text": "Encrypting session data", "is_correct": False},
        ],
    },
    {
        "text": "What is a Denial of Service (DoS) attack?",
        "explanation": "A DoS attack aims to make a machine or network resource unavailable to its intended users by overwhelming it with traffic or requests.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Making resources unavailable to users", "is_correct": True},
            {"text": "Stealing user credentials", "is_correct": False},
            {"text": "Installing malware", "is_correct": False},
            {"text": "Encrypting user files", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between DoS and DDoS attacks?",
        "explanation": "DoS attacks come from a single source, while DDoS (Distributed Denial of Service) attacks come from multiple sources simultaneously.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "DoS from single source, DDoS from multiple sources",
                "is_correct": True,
            },
            {"text": "DoS is faster than DDoS", "is_correct": False},
            {"text": "DoS is more dangerous than DDoS", "is_correct": False},
            {"text": "No difference between them", "is_correct": False},
        ],
    },
    {
        "text": "What is SQL injection?",
        "explanation": "SQL injection is a web security vulnerability that allows attackers to interfere with database queries by inserting malicious SQL code.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Injecting malicious SQL code into applications",
                "is_correct": True,
            },
            {"text": "Installing database software", "is_correct": False},
            {"text": "Backing up database files", "is_correct": False},
            {"text": "Optimizing database performance", "is_correct": False},
        ],
    },
    {
        "text": "Which type of DoS attack exploits the TCP three-way handshake?",
        "explanation": "SYN flood attacks exploit the TCP handshake by sending many SYN requests but never completing the handshake, exhausting server resources.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Ping flood", "is_correct": False},
            {"text": "SYN flood", "is_correct": True},
            {"text": "UDP flood", "is_correct": False},
            {"text": "ICMP flood", "is_correct": False},
        ],
    },
    {
        "text": "What is a blind SQL injection?",
        "explanation": "Blind SQL injection occurs when an application is vulnerable to SQL injection but doesn't display database errors or data to the attacker.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "SQL injection without visible database output",
                "is_correct": True,
            },
            {"text": "SQL injection using encryption", "is_correct": False},
            {"text": "SQL injection through images", "is_correct": False},
            {"text": "SQL injection using audio files", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for SQL injection testing?",
        "explanation": "SQLmap is an automated tool for detecting and exploiting SQL injection vulnerabilities in web applications.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Nmap", "is_correct": False},
            {"text": "SQLmap", "is_correct": True},
            {"text": "Wireshark", "is_correct": False},
            {"text": "Metasploit", "is_correct": False},
        ],
    },
    {
        "text": "What is a Smurf attack?",
        "explanation": "A Smurf attack is a DDoS attack that uses ICMP ping requests with spoofed source addresses to amplify traffic to a victim.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "ICMP-based DDoS attack", "is_correct": True},
            {"text": "TCP-based attack", "is_correct": False},
            {"text": "UDP-based attack", "is_correct": False},
            {"text": "HTTP-based attack", "is_correct": False},
        ],
    },
    {
        "text": "Which SQL injection technique uses time delays to extract information?",
        "explanation": "Time-based SQL injection uses database time delay functions to infer information from the database based on response times.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Union-based injection", "is_correct": False},
            {"text": "Time-based injection", "is_correct": True},
            {"text": "Boolean-based injection", "is_correct": False},
            {"text": "Error-based injection", "is_correct": False},
        ],
    },
    {
        "text": "What is application layer DDoS?",
        "explanation": "Application layer DDoS attacks target specific application services by overwhelming them with seemingly legitimate requests.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Attacks targeting application services", "is_correct": True},
            {"text": "Attacks targeting network infrastructure", "is_correct": False},
            {"text": "Attacks targeting operating systems", "is_correct": False},
            {"text": "Attacks targeting hardware", "is_correct": False},
        ],
    },
    {
        "text": "Which defense mechanism can help prevent SQL injection attacks?",
        "explanation": "Parameterized queries (prepared statements) separate SQL code from data, preventing malicious SQL code injection.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Firewall rules", "is_correct": False},
            {"text": "Parameterized queries", "is_correct": True},
            {"text": "Antivirus software", "is_correct": False},
            {"text": "Network segmentation", "is_correct": False},
        ],
    },
    {
        "text": "What is Cross-Site Scripting (XSS)?",
        "explanation": "XSS is a web vulnerability that allows attackers to inject malicious scripts into web pages viewed by other users.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Injecting malicious scripts into web pages", "is_correct": True},
            {"text": "Crossing network boundaries", "is_correct": False},
            {"text": "Stealing session cookies only", "is_correct": False},
            {"text": "Blocking website access", "is_correct": False},
        ],
    },
    {
        "text": "Which wireless security protocol is considered most secure?",
        "explanation": "WPA3 is the latest and most secure wireless security protocol, providing stronger encryption and security features than WPA2.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "WEP", "is_correct": False},
            {"text": "WPA", "is_correct": False},
            {"text": "WPA2", "is_correct": False},
            {"text": "WPA3", "is_correct": True},
        ],
    },
    {
        "text": "What is Cross-Site Request Forgery (CSRF)?",
        "explanation": "CSRF tricks users into executing unwanted actions on websites where they're authenticated by exploiting their trust relationship.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Tricking users into executing unwanted actions",
                "is_correct": True,
            },
            {"text": "Stealing user passwords", "is_correct": False},
            {"text": "Blocking website requests", "is_correct": False},
            {"text": "Encrypting web traffic", "is_correct": False},
        ],
    },
    {
        "text": "What is a rogue access point?",
        "explanation": "A rogue access point is an unauthorized wireless access point installed on a network, potentially allowing attackers network access.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Unauthorized wireless access point", "is_correct": True},
            {"text": "Legitimate wireless router", "is_correct": False},
            {"text": "Firewall device", "is_correct": False},
            {"text": "Network switch", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for web application security testing?",
        "explanation": "Burp Suite is a popular web application security testing platform used for finding security vulnerabilities.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Nmap", "is_correct": False},
            {"text": "Burp Suite", "is_correct": True},
            {"text": "Wireshark", "is_correct": False},
            {"text": "Aircrack-ng", "is_correct": False},
        ],
    },
    {
        "text": "What is WEP cracking?",
        "explanation": "WEP cracking involves exploiting weaknesses in the WEP encryption protocol to recover the wireless network key.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Breaking WEP encryption to get network key", "is_correct": True},
            {"text": "Fixing WEP configuration errors", "is_correct": False},
            {"text": "Installing WEP on networks", "is_correct": False},
            {"text": "Upgrading WEP to WPA", "is_correct": False},
        ],
    },
    {
        "text": "What is directory traversal attack?",
        "explanation": "Directory traversal allows attackers to access files and directories outside the web root folder by manipulating file paths.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Accessing files outside web root directory", "is_correct": True},
            {"text": "Creating new directories", "is_correct": False},
            {"text": "Deleting website directories", "is_correct": False},
            {"text": "Organizing website files", "is_correct": False},
        ],
    },
    {
        "text": "Which attack targets wireless networks by capturing handshake packets?",
        "explanation": "WPA/WPA2 handshake capture attacks involve capturing the 4-way handshake to later crack the wireless password offline.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Deauthentication attack", "is_correct": False},
            {"text": "Handshake capture attack", "is_correct": True},
            {"text": "Evil twin attack", "is_correct": False},
            {"text": "Beacon flood attack", "is_correct": False},
        ],
    },
    {
        "text": "What is command injection?",
        "explanation": "Command injection allows attackers to execute arbitrary operating system commands on the host system through vulnerable applications.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Executing OS commands through vulnerable apps",
                "is_correct": True,
            },
            {"text": "Installing command-line tools", "is_correct": False},
            {"text": "Running database commands", "is_correct": False},
            {"text": "Configuring system commands", "is_correct": False},
        ],
    },
    {
        "text": "What is an evil twin attack?",
        "explanation": "An evil twin attack involves creating a rogue access point with the same name as a legitimate one to intercept user traffic.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Creating fake access point with legitimate name",
                "is_correct": True,
            },
            {"text": "Cloning network devices", "is_correct": False},
            {"text": "Duplicating user accounts", "is_correct": False},
            {"text": "Creating identical websites", "is_correct": False},
        ],
    },
    {
        "text": "What is mobile device jailbreaking/rooting?",
        "explanation": "Jailbreaking (iOS) or rooting (Android) removes manufacturer restrictions to gain administrative access to the mobile operating system.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Gaining administrative access to mobile OS", "is_correct": True},
            {"text": "Installing security patches", "is_correct": False},
            {"text": "Backing up mobile data", "is_correct": False},
            {"text": "Updating mobile apps", "is_correct": False},
        ],
    },
    {
        "text": "Which attack vector is common in IoT devices?",
        "explanation": "Default credentials are a major vulnerability in IoT devices, as many users never change the default username and password.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Buffer overflows only", "is_correct": False},
            {"text": "Default credentials", "is_correct": True},
            {"text": "SQL injection only", "is_correct": False},
            {"text": "Cross-site scripting only", "is_correct": False},
        ],
    },
    {
        "text": "What is a mobile app sandbox?",
        "explanation": "A mobile app sandbox is a security mechanism that isolates applications from each other and the operating system to prevent unauthorized access.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Isolated environment for app execution", "is_correct": True},
            {"text": "App development environment", "is_correct": False},
            {"text": "App testing framework", "is_correct": False},
            {"text": "App store marketplace", "is_correct": False},
        ],
    },
    {
        "text": "Which protocol is commonly vulnerable in IoT communications?",
        "explanation": "MQTT is a lightweight messaging protocol often used in IoT but can be vulnerable if not properly secured with authentication and encryption.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "HTTP", "is_correct": False},
            {"text": "MQTT", "is_correct": True},
            {"text": "FTP", "is_correct": False},
            {"text": "SMTP", "is_correct": False},
        ],
    },
    {
        "text": "What is mobile application repackaging?",
        "explanation": "Mobile app repackaging involves modifying legitimate apps to include malicious code and redistributing them through unofficial channels.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Adding malicious code to legitimate apps", "is_correct": True},
            {"text": "Optimizing app performance", "is_correct": False},
            {"text": "Updating app user interface", "is_correct": False},
            {"text": "Fixing app bugs", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for IoT device discovery?",
        "explanation": "Shodan is a search engine that can discover Internet-connected IoT devices by scanning for specific services and ports.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Nmap", "is_correct": False},
            {"text": "Shodan", "is_correct": True},
            {"text": "Burp Suite", "is_correct": False},
            {"text": "Metasploit", "is_correct": False},
        ],
    },
    {
        "text": "What is SMS phishing (smishing)?",
        "explanation": "Smishing is a form of phishing that uses SMS text messages to trick users into revealing sensitive information or installing malware.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Phishing through SMS text messages", "is_correct": True},
            {"text": "Sending legitimate SMS notifications", "is_correct": False},
            {"text": "SMS encryption method", "is_correct": False},
            {"text": "SMS backup service", "is_correct": False},
        ],
    },
    {
        "text": "Which vulnerability is common in IoT firmware?",
        "explanation": "Hard-coded credentials in IoT firmware represent a critical vulnerability that provides attackers with persistent access to devices.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Hard-coded credentials", "is_correct": True},
            {"text": "Strong encryption", "is_correct": False},
            {"text": "Regular updates", "is_correct": False},
            {"text": "Secure boot process", "is_correct": False},
        ],
    },
    {
        "text": "What is mobile device management (MDM) bypass?",
        "explanation": "MDM bypass involves circumventing mobile device management policies and restrictions to gain unauthorized access to device functions.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Circumventing device management policies", "is_correct": True},
            {"text": "Installing MDM software", "is_correct": False},
            {"text": "Configuring MDM settings", "is_correct": False},
            {"text": "Updating MDM policies", "is_correct": False},
        ],
    },
    {
        "text": "What is a botnet in the context of IoT?",
        "explanation": "An IoT botnet consists of compromised IoT devices that can be remotely controlled to perform malicious activities like DDoS attacks.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Network of compromised IoT devices", "is_correct": True},
            {"text": "IoT device management system", "is_correct": False},
            {"text": "IoT security framework", "is_correct": False},
            {"text": "IoT communication protocol", "is_correct": False},
        ],
    },
    {
        "text": "What is cloud misconfiguration?",
        "explanation": "Cloud misconfiguration refers to incorrect or inadequate security settings in cloud services that can lead to data breaches and unauthorized access.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Incorrect security settings in cloud services",
                "is_correct": True,
            },
            {"text": "Optimal cloud performance tuning", "is_correct": False},
            {"text": "Cloud service installation", "is_correct": False},
            {"text": "Cloud cost optimization", "is_correct": False},
        ],
    },
    {
        "text": "Which encryption algorithm is considered symmetric?",
        "explanation": "AES (Advanced Encryption Standard) is a symmetric encryption algorithm that uses the same key for both encryption and decryption.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "RSA", "is_correct": False},
            {"text": "AES", "is_correct": True},
            {"text": "ECC", "is_correct": False},
            {"text": "Diffie-Hellman", "is_correct": False},
        ],
    },
    {
        "text": "What is container escape in cloud security?",
        "explanation": "Container escape is when an attacker breaks out of a container to gain access to the host operating system or other containers.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Breaking out of container to access host", "is_correct": True},
            {"text": "Moving containers between hosts", "is_correct": False},
            {"text": "Backing up container data", "is_correct": False},
            {"text": "Optimizing container performance", "is_correct": False},
        ],
    },
    {
        "text": "Which hash function is considered cryptographically secure?",
        "explanation": "SHA-256 (part of SHA-2 family) is considered cryptographically secure and widely used for digital signatures and certificates.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "MD5", "is_correct": False},
            {"text": "SHA-1", "is_correct": False},
            {"text": "SHA-256", "is_correct": True},
            {"text": "CRC32", "is_correct": False},
        ],
    },
    {
        "text": "What is a privilege escalation attack in cloud environments?",
        "explanation": "Cloud privilege escalation involves exploiting misconfigurations or vulnerabilities to gain higher-level permissions than initially granted.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Gaining higher-level cloud permissions", "is_correct": True},
            {"text": "Reducing cloud access permissions", "is_correct": False},
            {"text": "Creating new cloud accounts", "is_correct": False},
            {"text": "Deleting cloud resources", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between symmetric and asymmetric encryption?",
        "explanation": "Symmetric encryption uses the same key for encryption and decryption, while asymmetric uses different keys (public/private key pairs).",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Symmetric uses same key, asymmetric uses different keys",
                "is_correct": True,
            },
            {"text": "Symmetric is faster than asymmetric", "is_correct": False},
            {"text": "Symmetric is more secure than asymmetric", "is_correct": False},
            {"text": "No difference between them", "is_correct": False},
        ],
    },
    {
        "text": "What is cloud storage data exposure?",
        "explanation": "Cloud storage data exposure occurs when sensitive data stored in cloud services becomes publicly accessible due to misconfiguration.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Sensitive data becoming publicly accessible", "is_correct": True},
            {"text": "Data backup procedures", "is_correct": False},
            {"text": "Data compression techniques", "is_correct": False},
            {"text": "Data migration processes", "is_correct": False},
        ],
    },
    {
        "text": "Which attack targets public key infrastructure (PKI)?",
        "explanation": "Certificate authority compromise attacks target PKI by compromising certificate authorities to issue fraudulent certificates.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Man-in-the-middle", "is_correct": False},
            {"text": "Certificate authority compromise", "is_correct": True},
            {"text": "Buffer overflow", "is_correct": False},
            {"text": "SQL injection", "is_correct": False},
        ],
    },
    {
        "text": "What is serverless security in cloud computing?",
        "explanation": "Serverless security involves protecting Function-as-a-Service (FaaS) applications from vulnerabilities like code injection and insecure dependencies.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Security for Function-as-a-Service applications",
                "is_correct": True,
            },
            {"text": "Removing servers from cloud", "is_correct": False},
            {"text": "Installing security software on servers", "is_correct": False},
            {"text": "Managing physical server security", "is_correct": False},
        ],
    },
    {
        "text": "What is a rainbow table attack?",
        "explanation": "Rainbow table attacks use precomputed tables of hash values and their corresponding plaintext to quickly crack hashed passwords.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Using precomputed hash tables to crack passwords",
                "is_correct": True,
            },
            {"text": "Creating colorful data visualizations", "is_correct": False},
            {"text": "Organizing database tables", "is_correct": False},
            {"text": "Generating random passwords", "is_correct": False},
        ],
    },
    {
        "text": "What is the first step in incident response?",
        "explanation": "Preparation is the first phase of incident response, involving establishing policies, procedures, and resources before an incident occurs.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Detection", "is_correct": False},
            {"text": "Preparation", "is_correct": True},
            {"text": "Containment", "is_correct": False},
            {"text": "Recovery", "is_correct": False},
        ],
    },
    {
        "text": "What is digital forensics?",
        "explanation": "Digital forensics is the process of identifying, preserving, analyzing, and presenting digital evidence in a legally admissible manner.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Process of analyzing digital evidence", "is_correct": True},
            {"text": "Creating digital backups", "is_correct": False},
            {"text": "Installing security software", "is_correct": False},
            {"text": "Configuring network devices", "is_correct": False},
        ],
    },
    {
        "text": "Which principle ensures digital evidence integrity?",
        "explanation": "Chain of custody maintains the integrity of digital evidence by documenting who handled the evidence, when, and how.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Data compression", "is_correct": False},
            {"text": "Chain of custody", "is_correct": True},
            {"text": "Data encryption", "is_correct": False},
            {"text": "Data backup", "is_correct": False},
        ],
    },
    {
        "text": "What is volatile data in digital forensics?",
        "explanation": "Volatile data is information stored in RAM or other temporary storage that is lost when the system is powered off or rebooted.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Data lost when system powers off", "is_correct": True},
            {"text": "Permanently stored data", "is_correct": False},
            {"text": "Encrypted data", "is_correct": False},
            {"text": "Compressed data", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for disk imaging in forensics?",
        "explanation": "dd is a command-line utility commonly used in digital forensics to create bit-by-bit copies of storage devices.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Wireshark", "is_correct": False},
            {"text": "dd", "is_correct": True},
            {"text": "Nmap", "is_correct": False},
            {"text": "Burp Suite", "is_correct": False},
        ],
    },
    {
        "text": "What is the containment phase in incident response?",
        "explanation": "Containment involves limiting the scope and impact of a security incident to prevent further damage to systems and data.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Limiting incident scope and impact", "is_correct": True},
            {"text": "Identifying the incident", "is_correct": False},
            {"text": "Recovering from the incident", "is_correct": False},
            {"text": "Documenting the incident", "is_correct": False},
        ],
    },
    {
        "text": "What is steganography analysis in digital forensics?",
        "explanation": "Steganography analysis involves detecting and extracting hidden data that may be concealed within image, audio, or video files.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Detecting hidden data in files", "is_correct": True},
            {"text": "Analyzing file compression", "is_correct": False},
            {"text": "Checking file permissions", "is_correct": False},
            {"text": "Examining file creation dates", "is_correct": False},
        ],
    },
    {
        "text": "Which hash algorithm is commonly used to verify evidence integrity?",
        "explanation": "MD5 and SHA-1/SHA-256 are commonly used hash algorithms to create digital fingerprints that verify evidence hasn't been altered.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "AES", "is_correct": False},
            {"text": "MD5", "is_correct": True},
            {"text": "RSA", "is_correct": False},
            {"text": "DES", "is_correct": False},
        ],
    },
    {
        "text": "What is network forensics?",
        "explanation": "Network forensics involves capturing, recording, and analyzing network traffic to investigate security incidents and cybercrimes.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {
                "text": "Analyzing network traffic for investigations",
                "is_correct": True,
            },
            {"text": "Configuring network devices", "is_correct": False},
            {"text": "Installing network security tools", "is_correct": False},
            {"text": "Optimizing network performance", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of incident documentation?",
        "explanation": "Incident documentation provides a detailed record of the incident for legal proceedings, lessons learned, and improving future response efforts.",
        "reference": "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        "points": 1,
        "answers": [
            {"text": "Record for legal and improvement purposes", "is_correct": True},
            {"text": "Creating system backups", "is_correct": False},
            {"text": "Installing security patches", "is_correct": False},
            {"text": "Configuring firewalls", "is_correct": False},
        ],
    },
]
