"""CISCP (Certified Information Systems Cybersecurity Professional) Certification"""

CERTIFICATION = {
    "name": "CISCP - Certified Information Systems Cybersecurity Professional",
    "description": "Advanced cybersecurity expertise covering risk management, security architecture, and incident response",
    "slug": "ciscp-cybersecurity-professional",
    "level": "Professional",
    "duration": 288,
    "questions_count": 96,
    "category_slug": "cybersecurity",
    "is_active": True,
}

QUESTIONS = [{"text": "What is the primary purpose of a Security Operations Center (SOC)?",
              "explanation": "A Security Operations Center (SOC) is a centralized unit that deals with security issues on an organizational and technical level. It monitors, prevents, detects, investigates, and responds to cyber threats.",
              "reference": "https://www.sans.org/white-papers/39825/",
              "points": 1,
              "answers": [{"text": "Monitor and respond to security incidents 24/7",
                           "is_correct": True,
                           },
                          {"text": "Develop software applications",
                           "is_correct": False},
                          {"text": "Manage network infrastructure",
                           "is_correct": False},
                          {"text": "Handle customer support",
                           "is_correct": False},
                          ],
              },
             {"text": "Which framework is commonly used for incident response?",
              "explanation": "The NIST Cybersecurity Framework provides a policy framework of computer security guidance for how private sector organizations can assess and improve their ability to prevent, detect, and respond to cyber attacks.",
              "reference": "https://www.nist.gov/cyberframework",
              "points": 1,
              "answers": [{"text": "NIST Cybersecurity Framework",
                           "is_correct": True},
                          {"text": "ITIL Framework",
                           "is_correct": False},
                          {"text": "Agile Framework",
                           "is_correct": False},
                          {"text": "DevOps Framework",
                           "is_correct": False},
                          ],
              },
             {"text": "What is threat intelligence?",
              "explanation": "Threat intelligence is evidence-based knowledge, including context, mechanisms, indicators, implications and actionable advice, about an existing or emerging menace or hazard to assets that can be used to inform decisions regarding the subject's response to that menace or hazard.",
              "reference": "https://www.sans.org/reading-room/whitepapers/analyst/defining-cyber-threat-intelligence-36240",
              "points": 1,
              "answers": [{"text": "Data about potential security threats and attackers",
                           "is_correct": True,
                           },
                          {"text": "Software for monitoring networks",
                           "is_correct": False},
                          {"text": "Hardware security modules",
                           "is_correct": False},
                          {"text": "Encryption algorithms",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of analysis examines malware in a controlled environment?",
              "explanation": "Dynamic analysis involves executing malware in a controlled environment (sandbox) to observe its behavior, while static analysis examines the code without executing it.",
              "reference": "https://www.sans.org/reading-room/whitepapers/malicious/paper/2136",
              "points": 1,
              "answers": [{"text": "Dynamic analysis",
                           "is_correct": True},
                          {"text": "Static analysis",
                           "is_correct": False},
                          {"text": "Behavioral analysis",
                           "is_correct": False},
                          {"text": "Forensic analysis",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of a honeypot in cybersecurity?",
              "explanation": "A honeypot is a security mechanism set to detect, deflect, or counteract attempts at unauthorized use of information systems. It appears to be a legitimate system but is actually isolated and monitored.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/deployment-analysis-honeypots-detection-internal-threats-1690",
              "points": 1,
              "answers": [{"text": "Attract and monitor attackers",
                           "is_correct": True},
                          {"text": "Store encrypted data",
                           "is_correct": False},
                          {"text": "Backup system files",
                           "is_correct": False},
                          {"text": "Manage user access",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of risk assessment in cybersecurity?",
              "explanation": "Risk assessment aims to identify, analyze, and evaluate potential threats and vulnerabilities to determine the likelihood and impact of security incidents, enabling informed decision-making about risk mitigation strategies.",
              "reference": "https://www.nist.gov/publications/guide-conducting-risk-assessments",
              "points": 1,
              "answers": [{"text": "Identify and evaluate potential security threats and vulnerabilities",
                           "is_correct": True,
                           },
                          {"text": "Implement security controls",
                           "is_correct": False},
                          {"text": "Train security personnel",
                           "is_correct": False},
                          {"text": "Purchase security software",
                           "is_correct": False},
                          ],
              },
             {"text": "Which encryption standard is currently recommended for sensitive data protection?",
              "explanation": "AES (Advanced Encryption Standard) with 256-bit keys is currently the gold standard for encrypting sensitive data, approved by the NSA for protecting classified information.",
              "reference": "https://www.nist.gov/publications/advanced-encryption-standard-aes",
              "points": 1,
              "answers": [{"text": "AES-256",
                           "is_correct": True},
                          {"text": "DES",
                           "is_correct": False},
                          {"text": "MD5",
                           "is_correct": False},
                          {"text": "SHA-1",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of penetration testing?",
              "explanation": "Penetration testing simulates real-world attacks to identify vulnerabilities and security weaknesses in systems, networks, and applications before malicious actors can exploit them.",
              "reference": "https://www.sans.org/reading-room/whitepapers/testing/penetration-testing-methodology-33901",
              "points": 1,
              "answers": [{"text": "Simulate attacks to identify vulnerabilities",
                           "is_correct": True,
                           },
                          {"text": "Install security software",
                           "is_correct": False},
                          {"text": "Train employees",
                           "is_correct": False},
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          ],
              },
             {"text": "Which principle is fundamental to zero-trust security architecture?",
              "explanation": "Zero-trust architecture operates on the principle of 'never trust, always verify,' requiring authentication and authorization for every user and device attempting to access resources, regardless of their location.",
              "reference": "https://www.nist.gov/publications/zero-trust-architecture",
              "points": 1,
              "answers": [{"text": "Never trust, always verify",
                           "is_correct": True},
                          {"text": "Trust but verify",
                           "is_correct": False},
                          {"text": "Default allow policy",
                           "is_correct": False},
                          {"text": "Perimeter-based security",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary characteristic of an Advanced Persistent Threat (APT)?",
              "explanation": "APTs are sophisticated, long-term cyberattacks where attackers establish and maintain unauthorized access to networks for extended periods, often months or years, to steal sensitive data or monitor activities.",
              "reference": "https://www.sans.org/reading-room/whitepapers/analyst/advanced-persistent-threats-apt-37432",
              "points": 1,
              "answers": [{"text": "Long-term, sophisticated attacks with sustained access",
                           "is_correct": True,
                           },
                          {"text": "Quick hit-and-run attacks",
                           "is_correct": False},
                          {"text": "Automated vulnerability scans",
                           "is_correct": False},
                          {"text": "Social engineering campaigns",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security control is most effective against phishing attacks?",
              "explanation": "Security awareness training is the most effective control against phishing attacks because it educates users to recognize and respond appropriately to phishing attempts, addressing the human element that attackers target.",
              "reference": "https://www.sans.org/reading-room/whitepapers/awareness/effective-security-awareness-programs-36747",
              "points": 1,
              "answers": [{"text": "Security awareness training",
                           "is_correct": True},
                          {"text": "Firewall configuration",
                           "is_correct": False},
                          {"text": "Antivirus software",
                           "is_correct": False},
                          {"text": "Network segmentation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of Security Information and Event Management (SIEM)?",
              "explanation": "SIEM systems collect, aggregate, and analyze security-related data from multiple sources in real-time to detect, investigate, and respond to security threats and incidents.",
              "reference": "https://www.sans.org/reading-room/whitepapers/logging/siem-101-guide-security-information-event-management-36240",
              "points": 1,
              "answers": [{"text": "Aggregate and analyze security events for threat detection",
                           "is_correct": True,
                           },
                          {"text": "Backup data automatically",
                           "is_correct": False},
                          {"text": "Manage user passwords",
                           "is_correct": False},
                          {"text": "Control network access",
                           "is_correct": False},
                          ],
              },
             {"text": "Which framework provides guidance for cybersecurity risk management?",
              "explanation": "The NIST Cybersecurity Framework provides a policy framework of computer security guidance for organizations to assess and improve their ability to prevent, detect, and respond to cyber attacks.",
              "reference": "https://www.nist.gov/cyberframework",
              "points": 1,
              "answers": [{"text": "NIST Cybersecurity Framework",
                           "is_correct": True},
                          {"text": "ITIL Framework",
                           "is_correct": False},
                          {"text": "Agile Framework",
                           "is_correct": False},
                          {"text": "PMBOK Framework",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of digital forensics in cybersecurity?",
              "explanation": "Digital forensics involves the systematic examination and analysis of digital evidence to understand what happened during a security incident, who was responsible, and how the incident occurred.",
              "reference": "https://www.sans.org/reading-room/whitepapers/forensics/digital-forensics-incident-response-33264",
              "points": 1,
              "answers": [{"text": "Analyze digital evidence to understand security incidents",
                           "is_correct": True,
                           },
                          {"text": "Prevent future attacks",
                           "is_correct": False},
                          {"text": "Install security updates",
                           "is_correct": False},
                          {"text": "Monitor network performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which access control model is based on security clearances and classifications?",
              "explanation": "Mandatory Access Control (MAC) uses security clearances for users and classifications for data/resources, with access decisions made by the system based on these predefined security levels.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/access-control-fundamentals-486",
              "points": 1,
              "answers": [{"text": "Mandatory Access Control (MAC)",
                           "is_correct": True},
                          {"text": "Discretionary Access Control (DAC)",
                           "is_correct": False},
                          {"text": "Role-Based Access Control (RBAC)",
                           "is_correct": False},
                          {"text": "Attribute-Based Access Control (ABAC)",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of business continuity planning in cybersecurity?",
              "explanation": "Business continuity planning ensures that critical business operations can continue or be quickly resumed following a cybersecurity incident or other disruptive event.",
              "reference": "https://www.sans.org/reading-room/whitepapers/recovery/business-continuity-planning-security-incidents-34642",
              "points": 1,
              "answers": [{"text": "Ensure business operations continue during and after incidents",
                           "is_correct": True,
                           },
                          {"text": "Prevent all security incidents",
                           "is_correct": False},
                          {"text": "Reduce operational costs",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of vulnerability assessment provides the most comprehensive security evaluation?",
              "explanation": "Authenticated vulnerability scans provide the most comprehensive evaluation because they use valid credentials to access systems internally, revealing vulnerabilities that external scans might miss.",
              "reference": "https://www.sans.org/reading-room/whitepapers/testing/vulnerability-assessments-35969",
              "points": 1,
              "answers": [{"text": "Authenticated vulnerability scan",
                           "is_correct": True},
                          {"text": "Unauthenticated external scan",
                           "is_correct": False},
                          {"text": "Network discovery scan",
                           "is_correct": False},
                          {"text": "Port scan",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of security orchestration, automation, and response (SOAR)?",
              "explanation": "SOAR platforms automate security operations tasks, orchestrate security tools, and enable rapid response to incidents by executing predefined workflows and playbooks.",
              "reference": "https://www.sans.org/reading-room/whitepapers/analyst/security-orchestration-automation-response-soar-36467",
              "points": 1,
              "answers": [{"text": "Automate security operations and incident response",
                           "is_correct": True,
                           },
                          {"text": "Replace security analysts",
                           "is_correct": False},
                          {"text": "Monitor network bandwidth",
                           "is_correct": False},
                          {"text": "Manage user accounts",
                           "is_correct": False},
                          ],
              },
             {"text": "Which principle is essential for secure software development lifecycle (SDLC)?",
              "explanation": "Security by design ensures that security considerations are integrated throughout the entire software development lifecycle, from initial planning through deployment and maintenance.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/secure-software-development-lifecycle-36968",
              "points": 1,
              "answers": [{"text": "Security by design",
                           "is_correct": True},
                          {"text": "Security through obscurity",
                           "is_correct": False},
                          {"text": "Security as an afterthought",
                           "is_correct": False},
                          {"text": "Security by compliance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of network segmentation in cybersecurity?",
              "explanation": "Network segmentation divides a network into smaller, isolated segments to limit the spread of security threats and reduce the attack surface by controlling traffic flow between network zones.",
              "reference": "https://www.sans.org/reading-room/whitepapers/firewalls/network-segmentation-security-34692",
              "points": 1,
              "answers": [{"text": "Limit threat spread and reduce attack surface",
                           "is_correct": True,
                           },
                          {"text": "Improve network performance",
                           "is_correct": False},
                          {"text": "Reduce hardware costs",
                           "is_correct": False},
                          {"text": "Simplify network management",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of malware is designed to remain hidden while providing unauthorized access?",
              "explanation": "A rootkit is malicious software designed to maintain persistent access to a computer while hiding its presence from the operating system and security software.",
              "reference": "https://www.sans.org/reading-room/whitepapers/malicious/rootkit-detection-removal-34692",
              "points": 1,
              "answers": [{"text": "Rootkit",
                           "is_correct": True},
                          {"text": "Virus",
                           "is_correct": False},
                          {"text": "Worm",
                           "is_correct": False},
                          {"text": "Trojan",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary function of a Security Access Control Matrix?",
              "explanation": "A Security Access Control Matrix defines and documents the access rights and permissions that users, groups, or roles have to specific resources and operations within a system.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/access-control-models-34240",
              "points": 1,
              "answers": [{"text": "Define access rights and permissions for resources",
                           "is_correct": True,
                           },
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Encrypt sensitive data",
                           "is_correct": False},
                          {"text": "Backup user files",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security principle requires that users should only have the minimum access necessary to perform their job functions?",
              "explanation": "The Principle of Least Privilege states that users should be granted only the minimum levels of access needed to perform their job functions, reducing the potential impact of compromised accounts.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/principle-least-privilege-34692",
              "points": 1,
              "answers": [{"text": "Principle of Least Privilege",
                           "is_correct": True},
                          {"text": "Defense in Depth",
                           "is_correct": False},
                          {"text": "Separation of Duties",
                           "is_correct": False},
                          {"text": "Need to Know",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of a Certificate Authority (CA) in PKI?",
              "explanation": "A Certificate Authority (CA) is a trusted entity that issues, manages, and revokes digital certificates in a Public Key Infrastructure (PKI), providing verification of identity and enabling secure communications.",
              "reference": "https://www.sans.org/reading-room/whitepapers/PKI/public-key-infrastructure-34692",
              "points": 1,
              "answers": [{"text": "Issue and manage digital certificates",
                           "is_correct": True},
                          {"text": "Generate encryption keys",
                           "is_correct": False},
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Store user passwords",
                           "is_correct": False},
                          ],
              },
             {"text": "Which attack technique involves overwhelming a system with traffic to make it unavailable?",
              "explanation": "A Denial of Service (DoS) attack attempts to make a system, service, or network unavailable by overwhelming it with traffic or requests, preventing legitimate users from accessing it.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/denial-service-attacks-34692",
              "points": 1,
              "answers": [{"text": "Denial of Service (DoS)",
                           "is_correct": True},
                          {"text": "Man-in-the-Middle",
                           "is_correct": False},
                          {"text": "SQL Injection",
                           "is_correct": False},
                          {"text": "Cross-Site Scripting",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of data classification in information security?",
              "explanation": "Data classification categorizes information based on its sensitivity and criticality to determine appropriate security controls, handling procedures, and protection levels.",
              "reference": "https://www.sans.org/reading-room/whitepapers/policy/data-classification-34692",
              "points": 1,
              "answers": [{"text": "Determine appropriate security controls for different data types",
                           "is_correct": True,
                           },
                          {"text": "Reduce storage costs",
                           "is_correct": False},
                          {"text": "Improve data retrieval speed",
                           "is_correct": False},
                          {"text": "Organize files alphabetically",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security model is based on the concept of information flow control?",
              "explanation": "The Bell-LaPadula model is a security model that focuses on confidentiality through information flow control, using the 'no read up, no write down' principle to prevent unauthorized information disclosure.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/security-models-34692",
              "points": 1,
              "answers": [{"text": "Bell-LaPadula model",
                           "is_correct": True},
                          {"text": "Biba model",
                           "is_correct": False},
                          {"text": "Clark-Wilson model",
                           "is_correct": False},
                          {"text": "Chinese Wall model",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of security awareness training?",
              "explanation": "Security awareness training educates employees about cybersecurity threats, safe computing practices, and organizational security policies to reduce human-related security risks.",
              "reference": "https://www.sans.org/reading-room/whitepapers/awareness/security-awareness-training-34692",
              "points": 1,
              "answers": [{"text": "Educate employees about cybersecurity threats and safe practices",
                           "is_correct": True,
                           },
                          {"text": "Install security software",
                           "is_correct": False},
                          {"text": "Configure firewalls",
                           "is_correct": False},
                          {"text": "Monitor network logs",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of backup strategy provides the fastest recovery time?",
              "explanation": "A hot backup (or hot site) provides the fastest recovery time because it maintains real-time or near real-time copies of data and systems that can be immediately activated in case of a disaster.",
              "reference": "https://www.sans.org/reading-room/whitepapers/recovery/backup-strategies-34692",
              "points": 1,
              "answers": [{"text": "Hot backup",
                           "is_correct": True},
                          {"text": "Cold backup",
                           "is_correct": False},
                          {"text": "Warm backup",
                           "is_correct": False},
                          {"text": "Incremental backup",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary function of an Intrusion Detection System (IDS)?",
              "explanation": "An Intrusion Detection System (IDS) monitors network traffic and system activities to detect and alert on suspicious activities that may indicate security threats or attacks.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/intrusion-detection-systems-34692",
              "points": 1,
              "answers": [{"text": "Monitor and detect suspicious network activities",
                           "is_correct": True,
                           },
                          {"text": "Block malicious traffic",
                           "is_correct": False},
                          {"text": "Encrypt network communications",
                           "is_correct": False},
                          {"text": "Manage user accounts",
                           "is_correct": False},
                          ],
              },
             {"text": "Which cryptographic technique provides both confidentiality and authentication?",
              "explanation": "Digital signatures provide authentication and non-repudiation, while encryption provides confidentiality. Using both techniques together provides comprehensive protection.",
              "reference": "https://www.sans.org/reading-room/whitepapers/PKI/cryptography-fundamentals-34692",
              "points": 1,
              "answers": [{"text": "Digital signatures with encryption",
                           "is_correct": True},
                          {"text": "Hash functions only",
                           "is_correct": False},
                          {"text": "Symmetric encryption only",
                           "is_correct": False},
                          {"text": "Public key encryption only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of a security baseline?",
              "explanation": "A security baseline establishes the minimum security configuration requirements and standards that systems must meet to ensure consistent and adequate security across an organization.",
              "reference": "https://www.sans.org/reading-room/whitepapers/standards/security-baselines-34692",
              "points": 1,
              "answers": [{"text": "Establish minimum security configuration standards",
                           "is_correct": True,
                           },
                          {"text": "Monitor system performance",
                           "is_correct": False},
                          {"text": "Create user accounts",
                           "is_correct": False},
                          {"text": "Install software updates",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security principle ensures that critical tasks require multiple people to complete?",
              "explanation": "Separation of Duties (SoD) requires that critical tasks be divided among multiple people to prevent fraud, errors, and unauthorized actions by ensuring no single person has complete control over critical processes.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/separation-duties-34692",
              "points": 1,
              "answers": [{"text": "Separation of Duties",
                           "is_correct": True},
                          {"text": "Least Privilege",
                           "is_correct": False},
                          {"text": "Defense in Depth",
                           "is_correct": False},
                          {"text": "Need to Know",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of vulnerability management?",
              "explanation": "Vulnerability management is the systematic process of identifying, evaluating, prioritizing, and remediating security vulnerabilities in systems and applications to reduce organizational risk.",
              "reference": "https://www.sans.org/reading-room/whitepapers/testing/vulnerability-management-34692",
              "points": 1,
              "answers": [{"text": "Systematically identify and remediate security vulnerabilities",
                           "is_correct": True,
                           },
                          {"text": "Install antivirus software",
                           "is_correct": False},
                          {"text": "Monitor network bandwidth",
                           "is_correct": False},
                          {"text": "Manage user passwords",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of security control is designed to deter potential attackers?",
              "explanation": "Deterrent controls are designed to discourage potential attackers from attempting to breach security by making them aware of the consequences or difficulty of their actions.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/security-controls-34692",
              "points": 1,
              "answers": [{"text": "Deterrent controls",
                           "is_correct": True},
                          {"text": "Detective controls",
                           "is_correct": False},
                          {"text": "Corrective controls",
                           "is_correct": False},
                          {"text": "Compensating controls",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of security metrics and KPIs?",
              "explanation": "Security metrics and Key Performance Indicators (KPIs) measure the effectiveness of security controls and programs, providing quantitative data to support decision-making and demonstrate security posture.",
              "reference": "https://www.sans.org/reading-room/whitepapers/metrics/security-metrics-34692",
              "points": 1,
              "answers": [{"text": "Measure security program effectiveness and support decision-making",
                           "is_correct": True,
                           },
                          {"text": "Install security patches",
                           "is_correct": False},
                          {"text": "Configure firewall rules",
                           "is_correct": False},
                          {"text": "Train security personnel",
                           "is_correct": False},
                          ],
              },
             {"text": "Which attack technique exploits the trust relationship between websites and users' browsers?",
              "explanation": "Cross-Site Request Forgery (CSRF) attacks exploit the trust that a website has in a user's browser by tricking the browser into executing unwanted actions on behalf of the user.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/cross-site-request-forgery-34692",
              "points": 1,
              "answers": [{"text": "Cross-Site Request Forgery (CSRF)",
                           "is_correct": True},
                          {"text": "SQL Injection",
                           "is_correct": False},
                          {"text": "Buffer Overflow",
                           "is_correct": False},
                          {"text": "Directory Traversal",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of implementing multi-factor authentication (MFA)?",
              "explanation": "Multi-factor authentication significantly strengthens security by requiring multiple forms of verification, making it much more difficult for attackers to gain unauthorized access even if they compromise one authentication factor.",
              "reference": "https://www.sans.org/reading-room/whitepapers/authentication/multi-factor-authentication-34692",
              "points": 1,
              "answers": [{"text": "Significantly strengthen authentication security",
                           "is_correct": True,
                           },
                          {"text": "Reduce login time",
                           "is_correct": False},
                          {"text": "Eliminate password requirements",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of encryption at rest?",
              "explanation": "Encryption at rest protects stored data from unauthorized access by encrypting it while it's stored on disk, databases, or other storage media, ensuring confidentiality even if physical storage is compromised.",
              "reference": "https://www.sans.org/reading-room/whitepapers/encryption/encryption-rest-34692",
              "points": 1,
              "answers": [{"text": "Protect stored data from unauthorized access",
                           "is_correct": True,
                           },
                          {"text": "Improve database performance",
                           "is_correct": False},
                          {"text": "Reduce storage space",
                           "is_correct": False},
                          {"text": "Speed up data retrieval",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of social engineering attack targets high-profile individuals?",
              "explanation": "Whaling is a type of phishing attack that specifically targets high-profile individuals such as CEOs, CFOs, or other senior executives, often using personalized and sophisticated techniques.",
              "reference": "https://www.sans.org/reading-room/whitepapers/social/social-engineering-34692",
              "points": 1,
              "answers": [{"text": "Whaling",
                           "is_correct": True},
                          {"text": "Spear phishing",
                           "is_correct": False},
                          {"text": "Vishing",
                           "is_correct": False},
                          {"text": "Smishing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of a Web Application Firewall (WAF)?",
              "explanation": "A Web Application Firewall (WAF) protects web applications by filtering, monitoring, and blocking HTTP traffic between web applications and the internet, specifically defending against application-layer attacks.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/web-application-firewalls-34692",
              "points": 1,
              "answers": [{"text": "Protect web applications from application-layer attacks",
                           "is_correct": True,
                           },
                          {"text": "Improve website loading speed",
                           "is_correct": False},
                          {"text": "Manage SSL certificates",
                           "is_correct": False},
                          {"text": "Optimize database queries",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security principle states that defense mechanisms should not depend on the secrecy of their design?",
              "explanation": "Kerckhoffs's principle states that a cryptosystem should be secure even if everything about the system, except the key, is public knowledge. This principle extends to all security mechanisms.",
              "reference": "https://www.sans.org/reading-room/whitepapers/standards/security-principles-34692",
              "points": 1,
              "answers": [{"text": "Kerckhoffs's principle",
                           "is_correct": True},
                          {"text": "Defense in depth",
                           "is_correct": False},
                          {"text": "Least privilege",
                           "is_correct": False},
                          {"text": "Fail-safe defaults",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary characteristic of a distributed denial-of-service (DDoS) attack?",
              "explanation": "A DDoS attack uses multiple compromised systems (botnet) to flood a target with traffic, making it much more difficult to defend against than a single-source DoS attack.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/distributed-denial-service-attacks-34692",
              "points": 1,
              "answers": [{"text": "Uses multiple compromised systems to flood the target",
                           "is_correct": True,
                           },
                          {"text": "Targets only web applications",
                           "is_correct": False},
                          {"text": "Only affects network infrastructure",
                           "is_correct": False},
                          {"text": "Requires physical access to systems",
                           "is_correct": False},
                          ],
              },
             {"text": "Which framework is specifically designed for managing information security?",
              "explanation": "ISO 27001 is an international standard that provides requirements for establishing, implementing, maintaining, and continually improving an information security management system (ISMS).",
              "reference": "https://www.sans.org/reading-room/whitepapers/standards/iso-27001-34692",
              "points": 1,
              "answers": [{"text": "ISO 27001",
                           "is_correct": True},
                          {"text": "ITIL",
                           "is_correct": False},
                          {"text": "COBIT",
                           "is_correct": False},
                          {"text": "PMBOK",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of endpoint detection and response (EDR)?",
              "explanation": "EDR solutions continuously monitor and collect activity data from endpoints (computers, mobile devices, servers) to detect and respond to cyber threats in real-time.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/endpoint-detection-response-34692",
              "points": 1,
              "answers": [{"text": "Monitor and respond to threats on endpoint devices",
                           "is_correct": True,
                           },
                          {"text": "Manage software updates",
                           "is_correct": False},
                          {"text": "Control network access",
                           "is_correct": False},
                          {"text": "Backup endpoint data",
                           "is_correct": False},
                          ],
              },
             {"text": "Which attack technique involves injecting malicious code into SQL queries?",
              "explanation": "SQL injection attacks involve inserting malicious SQL code into application queries, allowing attackers to view, modify, or delete database information.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/sql-injection-34692",
              "points": 1,
              "answers": [{"text": "SQL injection",
                           "is_correct": True},
                          {"text": "Cross-site scripting",
                           "is_correct": False},
                          {"text": "Buffer overflow",
                           "is_correct": False},
                          {"text": "Command injection",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of security information sharing?",
              "explanation": "Security information sharing enables organizations to share threat intelligence, indicators of compromise, and security best practices to improve collective defense against cyber threats.",
              "reference": "https://www.sans.org/reading-room/whitepapers/analyst/threat-intelligence-sharing-34692",
              "points": 1,
              "answers": [{"text": "Improve collective defense through shared threat intelligence",
                           "is_correct": True,
                           },
                          {"text": "Reduce security costs",
                           "is_correct": False},
                          {"text": "Comply with regulations",
                           "is_correct": False},
                          {"text": "Simplify security management",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of encryption uses the same key for both encryption and decryption?",
              "explanation": "Symmetric encryption uses the same key for both encryption and decryption operations, making it faster than asymmetric encryption but requiring secure key distribution.",
              "reference": "https://www.sans.org/reading-room/whitepapers/encryption/symmetric-encryption-34692",
              "points": 1,
              "answers": [{"text": "Symmetric encryption",
                           "is_correct": True},
                          {"text": "Asymmetric encryption",
                           "is_correct": False},
                          {"text": "Hash functions",
                           "is_correct": False},
                          {"text": "Digital signatures",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of security architecture?",
              "explanation": "Security architecture provides a structured approach for designing and implementing security controls and mechanisms to protect an organization's assets and ensure security requirements are met.",
              "reference": "https://www.sans.org/reading-room/whitepapers/architecture/security-architecture-34692",
              "points": 1,
              "answers": [{"text": "Design and implement comprehensive security controls",
                           "is_correct": True,
                           },
                          {"text": "Reduce operational costs",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          {"text": "Simplify user interfaces",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security control type is designed to reduce the impact of security incidents?",
              "explanation": "Corrective controls are implemented to reduce the impact of security incidents and restore normal operations after an incident occurs.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/security-control-types-34692",
              "points": 1,
              "answers": [{"text": "Corrective controls",
                           "is_correct": True},
                          {"text": "Preventive controls",
                           "is_correct": False},
                          {"text": "Detective controls",
                           "is_correct": False},
                          {"text": "Deterrent controls",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of a security token in authentication?",
              "explanation": "Security tokens provide an additional authentication factor by generating time-sensitive codes or storing cryptographic keys, enhancing security beyond traditional username/password combinations.",
              "reference": "https://www.sans.org/reading-room/whitepapers/authentication/security-tokens-34692",
              "points": 1,
              "answers": [{"text": "Provide additional authentication factor beyond passwords",
                           "is_correct": True,
                           },
                          {"text": "Store user preferences",
                           "is_correct": False},
                          {"text": "Encrypt network traffic",
                           "is_correct": False},
                          {"text": "Monitor user activities",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of malware encrypts files and demands payment for decryption?",
              "explanation": "Ransomware is malicious software that encrypts a victim's files and demands payment (usually in cryptocurrency) in exchange for the decryption key.",
              "reference": "https://www.sans.org/reading-room/whitepapers/malicious/ransomware-34692",
              "points": 1,
              "answers": [{"text": "Ransomware",
                           "is_correct": True},
                          {"text": "Spyware",
                           "is_correct": False},
                          {"text": "Adware",
                           "is_correct": False},
                          {"text": "Keylogger",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of secure coding practices?",
              "explanation": "Secure coding practices aim to prevent security vulnerabilities from being introduced during software development by following established security guidelines and best practices.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/secure-coding-practices-34692",
              "points": 1,
              "answers": [{"text": "Prevent security vulnerabilities during development",
                           "is_correct": True,
                           },
                          {"text": "Improve code performance",
                           "is_correct": False},
                          {"text": "Reduce development time",
                           "is_correct": False},
                          {"text": "Simplify code maintenance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security assessment method involves reviewing source code for vulnerabilities?",
              "explanation": "Static Application Security Testing (SAST) analyzes source code without executing it to identify potential security vulnerabilities and coding errors.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/static-analysis-34692",
              "points": 1,
              "answers": [{"text": "Static Application Security Testing (SAST)",
                           "is_correct": True},
                          {"text": "Dynamic Application Security Testing (DAST)",
                           "is_correct": False,
                           },
                          {"text": "Interactive Application Security Testing (IAST)",
                           "is_correct": False,
                           },
                          {"text": "Penetration testing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of incident containment?",
              "explanation": "Incident containment aims to limit the scope and impact of a security incident by preventing it from spreading to other systems or causing additional damage.",
              "reference": "https://www.sans.org/reading-room/whitepapers/incident/incident-response-34692",
              "points": 1,
              "answers": [{"text": "Limit the scope and impact of the security incident",
                           "is_correct": True,
                           },
                          {"text": "Identify the root cause",
                           "is_correct": False},
                          {"text": "Restore normal operations",
                           "is_correct": False},
                          {"text": "Document lessons learned",
                           "is_correct": False},
                          ],
              },
             {"text": "Which protocol provides secure communication over the internet?",
              "explanation": "Transport Layer Security (TLS) is a cryptographic protocol that provides secure communication over a computer network, commonly used for web browsing (HTTPS).",
              "reference": "https://www.sans.org/reading-room/whitepapers/protocols/transport-layer-security-34692",
              "points": 1,
              "answers": [{"text": "Transport Layer Security (TLS)",
                           "is_correct": True},
                          {"text": "File Transfer Protocol (FTP)",
                           "is_correct": False},
                          {"text": "Simple Mail Transfer Protocol (SMTP)",
                           "is_correct": False},
                          {"text": "Hypertext Transfer Protocol (HTTP)",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of a security policy?",
              "explanation": "A security policy establishes the rules, guidelines, and procedures that govern how an organization protects its information assets and ensures consistent security practices.",
              "reference": "https://www.sans.org/reading-room/whitepapers/policy/security-policies-34692",
              "points": 1,
              "answers": [{"text": "Establish rules and guidelines for protecting information assets",
                           "is_correct": True,
                           },
                          {"text": "Configure security software",
                           "is_correct": False},
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Train security personnel",
                           "is_correct": False},
                          ],
              },
             {"text": "Which attack technique involves manipulating people to divulge confidential information?",
              "explanation": "Social engineering attacks exploit human psychology and trust to manipulate people into revealing confidential information or performing actions that compromise security.",
              "reference": "https://www.sans.org/reading-room/whitepapers/social/social-engineering-attacks-34692",
              "points": 1,
              "answers": [{"text": "Social engineering",
                           "is_correct": True},
                          {"text": "Password cracking",
                           "is_correct": False},
                          {"text": "Network scanning",
                           "is_correct": False},
                          {"text": "Vulnerability exploitation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of network access control (NAC)?",
              "explanation": "Network Access Control (NAC) systems control access to network resources by authenticating and authorizing devices and users before granting network access.",
              "reference": "https://www.sans.org/reading-room/whitepapers/networkaccess/network-access-control-34692",
              "points": 1,
              "answers": [{"text": "Control and manage access to network resources",
                           "is_correct": True,
                           },
                          {"text": "Monitor network performance",
                           "is_correct": False},
                          {"text": "Encrypt network traffic",
                           "is_correct": False},
                          {"text": "Backup network configurations",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of backup contains only the changes made since the last full backup?",
              "explanation": "A differential backup contains all changes made since the last full backup, providing a middle ground between full backups and incremental backups in terms of storage space and restore time.",
              "reference": "https://www.sans.org/reading-room/whitepapers/recovery/backup-types-34692",
              "points": 1,
              "answers": [{"text": "Differential backup",
                           "is_correct": True},
                          {"text": "Incremental backup",
                           "is_correct": False},
                          {"text": "Full backup",
                           "is_correct": False},
                          {"text": "Mirror backup",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of security governance?",
              "explanation": "Security governance ensures that security strategies align with business objectives and that appropriate oversight, accountability, and risk management processes are in place.",
              "reference": "https://www.sans.org/reading-room/whitepapers/governance/security-governance-34692",
              "points": 1,
              "answers": [{"text": "Align security strategies with business objectives",
                           "is_correct": True,
                           },
                          {"text": "Install security software",
                           "is_correct": False},
                          {"text": "Configure firewalls",
                           "is_correct": False},
                          {"text": "Train security staff",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security mechanism provides non-repudiation?",
              "explanation": "Digital signatures provide non-repudiation by ensuring that the sender cannot deny having sent a message, as the signature is created using the sender's private key.",
              "reference": "https://www.sans.org/reading-room/whitepapers/PKI/digital-signatures-34692",
              "points": 1,
              "answers": [{"text": "Digital signatures",
                           "is_correct": True},
                          {"text": "Symmetric encryption",
                           "is_correct": False},
                          {"text": "Hash functions",
                           "is_correct": False},
                          {"text": "Access control lists",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of security monitoring?",
              "explanation": "Security monitoring involves continuously observing and analyzing system activities, network traffic, and security events to detect, investigate, and respond to potential threats and incidents.",
              "reference": "https://www.sans.org/reading-room/whitepapers/monitoring/security-monitoring-34692",
              "points": 1,
              "answers": [{"text": "Continuously detect and respond to security threats",
                           "is_correct": True,
                           },
                          {"text": "Improve system performance",
                           "is_correct": False},
                          {"text": "Reduce operational costs",
                           "is_correct": False},
                          {"text": "Manage user accounts",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of firewall operates at the application layer?",
              "explanation": "Application layer firewalls (also called proxy firewalls or application gateways) operate at Layer 7 of the OSI model and can inspect and filter traffic based on application-specific protocols and content.",
              "reference": "https://www.sans.org/reading-room/whitepapers/firewalls/firewall-types-34692",
              "points": 1,
              "answers": [{"text": "Application layer firewall",
                           "is_correct": True},
                          {"text": "Packet filtering firewall",
                           "is_correct": False},
                          {"text": "Stateful inspection firewall",
                           "is_correct": False},
                          {"text": "Circuit-level gateway",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of data loss prevention (DLP)?",
              "explanation": "Data Loss Prevention (DLP) systems monitor, detect, and prevent unauthorized transmission or disclosure of sensitive data, whether in use, in motion, or at rest.",
              "reference": "https://www.sans.org/reading-room/whitepapers/dlp/data-loss-prevention-34692",
              "points": 1,
              "answers": [{"text": "Prevent unauthorized disclosure of sensitive data",
                           "is_correct": True,
                           },
                          {"text": "Improve data processing speed",
                           "is_correct": False},
                          {"text": "Reduce storage costs",
                           "is_correct": False},
                          {"text": "Optimize database performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security principle requires that systems should fail to a secure state?",
              "explanation": "Fail-safe defaults ensure that when a system fails or encounters an error, it defaults to a secure state that denies access rather than allowing it, maintaining security even during failures.",
              "reference": "https://www.sans.org/reading-room/whitepapers/standards/fail-safe-defaults-34692",
              "points": 1,
              "answers": [{"text": "Fail-safe defaults",
                           "is_correct": True},
                          {"text": "Defense in depth",
                           "is_correct": False},
                          {"text": "Least privilege",
                           "is_correct": False},
                          {"text": "Complete mediation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of threat modeling?",
              "explanation": "Threat modeling is a structured approach to identify, assess, and prioritize potential threats to a system or application, enabling proactive security measures to be implemented.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/threat-modeling-34692",
              "points": 1,
              "answers": [{"text": "Identify and assess potential threats to systems",
                           "is_correct": True,
                           },
                          {"text": "Install security patches",
                           "is_correct": False},
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Train security personnel",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of attack involves intercepting and potentially altering communications between two parties?",
              "explanation": "A Man-in-the-Middle (MITM) attack occurs when an attacker secretly intercepts and potentially alters communications between two parties who believe they are directly communicating with each other.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/man-middle-attacks-34692",
              "points": 1,
              "answers": [{"text": "Man-in-the-Middle (MITM)",
                           "is_correct": True},
                          {"text": "Replay attack",
                           "is_correct": False},
                          {"text": "Brute force attack",
                           "is_correct": False},
                          {"text": "Dictionary attack",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of a Virtual Private Network (VPN)?",
              "explanation": "A VPN creates a secure, encrypted tunnel over a public network (typically the internet) to provide remote users with secure access to private network resources.",
              "reference": "https://www.sans.org/reading-room/whitepapers/networkaccess/virtual-private-networks-34692",
              "points": 1,
              "answers": [{"text": "Provide secure remote access to private networks",
                           "is_correct": True,
                           },
                          {"text": "Improve internet speed",
                           "is_correct": False},
                          {"text": "Block malicious websites",
                           "is_correct": False},
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security assessment technique involves testing without prior knowledge of the system?",
              "explanation": "Black box testing is performed without any prior knowledge of the system's internal structure, design, or implementation, simulating how an external attacker would approach the system.",
              "reference": "https://www.sans.org/reading-room/whitepapers/testing/penetration-testing-methodologies-34692",
              "points": 1,
              "answers": [{"text": "Black box testing",
                           "is_correct": True},
                          {"text": "White box testing",
                           "is_correct": False},
                          {"text": "Gray box testing",
                           "is_correct": False},
                          {"text": "Clear box testing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary function of a Hardware Security Module (HSM)?",
              "explanation": "HSMs are dedicated, tamper-resistant hardware devices designed to securely generate, store, and manage cryptographic keys and perform cryptographic operations.",
              "reference": "https://www.sans.org/reading-room/whitepapers/PKI/hardware-security-modules-34692",
              "points": 1,
              "answers": [{"text": "Securely generate, store, and manage cryptographic keys",
                           "is_correct": True,
                           },
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Backup system data",
                           "is_correct": False},
                          {"text": "Manage user accounts",
                           "is_correct": False},
                          ],
              },
             {"text": "Which principle requires that all access requests should be authenticated and authorized?",
              "explanation": "Complete mediation ensures that every access request to a protected resource is checked for authorization, with no exceptions or bypasses allowed.",
              "reference": "https://www.sans.org/reading-room/whitepapers/standards/security-principles-34692",
              "points": 1,
              "answers": [{"text": "Complete mediation",
                           "is_correct": True},
                          {"text": "Least privilege",
                           "is_correct": False},
                          {"text": "Defense in depth",
                           "is_correct": False},
                          {"text": "Separation of duties",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of sandboxing in cybersecurity?",
              "explanation": "Sandboxing creates an isolated environment where potentially malicious code can be executed safely without affecting the host system, allowing for analysis and testing.",
              "reference": "https://www.sans.org/reading-room/whitepapers/malicious/sandboxing-techniques-34692",
              "points": 1,
              "answers": [{"text": "Isolate and safely execute potentially malicious code",
                           "is_correct": True,
                           },
                          {"text": "Improve system performance",
                           "is_correct": False},
                          {"text": "Backup important files",
                           "is_correct": False},
                          {"text": "Manage user permissions",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of cryptographic attack exploits mathematical relationships in encryption algorithms?",
              "explanation": "Cryptanalysis involves analyzing cryptographic systems to find weaknesses or mathematical relationships that can be exploited to break the encryption without knowing the key.",
              "reference": "https://www.sans.org/reading-room/whitepapers/encryption/cryptanalysis-techniques-34692",
              "points": 1,
              "answers": [{"text": "Cryptanalysis",
                           "is_correct": True},
                          {"text": "Brute force attack",
                           "is_correct": False},
                          {"text": "Social engineering",
                           "is_correct": False},
                          {"text": "Physical attack",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of incident eradication?",
              "explanation": "Incident eradication involves removing the threat from the affected systems and eliminating any remaining traces of the attack to prevent reoccurrence.",
              "reference": "https://www.sans.org/reading-room/whitepapers/incident/incident-response-lifecycle-34692",
              "points": 1,
              "answers": [{"text": "Remove the threat and eliminate traces of the attack",
                           "is_correct": True,
                           },
                          {"text": "Document the incident",
                           "is_correct": False},
                          {"text": "Notify stakeholders",
                           "is_correct": False},
                          {"text": "Assess the damage",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security control provides real-time protection against network-based attacks?",
              "explanation": "An Intrusion Prevention System (IPS) actively monitors network traffic in real-time and can automatically block or prevent detected attacks from reaching their targets.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/intrusion-prevention-systems-34692",
              "points": 1,
              "answers": [{"text": "Intrusion Prevention System (IPS)",
                           "is_correct": True},
                          {"text": "Antivirus software",
                           "is_correct": False},
                          {"text": "Access control list",
                           "is_correct": False},
                          {"text": "Audit log",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of key escrow in cryptography?",
              "explanation": "Key escrow involves storing encryption keys with a trusted third party to ensure that encrypted data can be recovered if the original keys are lost or in legal situations requiring access.",
              "reference": "https://www.sans.org/reading-room/whitepapers/PKI/key-escrow-management-34692",
              "points": 1,
              "answers": [{"text": "Store encryption keys with trusted third parties for recovery",
                           "is_correct": True,
                           },
                          {"text": "Generate new encryption keys",
                           "is_correct": False},
                          {"text": "Distribute keys to users",
                           "is_correct": False},
                          {"text": "Validate key authenticity",
                           "is_correct": False},
                          ],
              },
             {"text": "Which attack technique involves flooding a network with broadcast traffic?",
              "explanation": "A broadcast storm attack floods a network segment with broadcast traffic, consuming network bandwidth and potentially causing network performance degradation or outages.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/network-attacks-34692",
              "points": 1,
              "answers": [{"text": "Broadcast storm",
                           "is_correct": True},
                          {"text": "ARP poisoning",
                           "is_correct": False},
                          {"text": "DNS spoofing",
                           "is_correct": False},
                          {"text": "VLAN hopping",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary function of a Security Assertion Markup Language (SAML)?",
              "explanation": "SAML is an XML-based standard for exchanging authentication and authorization data between parties, particularly for single sign-on (SSO) implementations.",
              "reference": "https://www.sans.org/reading-room/whitepapers/authentication/saml-security-34692",
              "points": 1,
              "answers": [{"text": "Exchange authentication and authorization data for SSO",
                           "is_correct": True,
                           },
                          {"text": "Encrypt network communications",
                           "is_correct": False},
                          {"text": "Monitor system logs",
                           "is_correct": False},
                          {"text": "Manage user profiles",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of malware is designed to steal sensitive information from infected systems?",
              "explanation": "Spyware is malicious software designed to secretly monitor user activities and steal sensitive information such as passwords, credit card numbers, and personal data.",
              "reference": "https://www.sans.org/reading-room/whitepapers/malicious/spyware-detection-removal-34692",
              "points": 1,
              "answers": [{"text": "Spyware",
                           "is_correct": True},
                          {"text": "Worm",
                           "is_correct": False},
                          {"text": "Logic bomb",
                           "is_correct": False},
                          {"text": "Boot sector virus",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of security configuration management?",
              "explanation": "Security configuration management ensures that systems are configured according to security standards and that these configurations are maintained consistently across the organization.",
              "reference": "https://www.sans.org/reading-room/whitepapers/standards/security-configuration-management-34692",
              "points": 1,
              "answers": [{"text": "Maintain consistent and secure system configurations",
                           "is_correct": True,
                           },
                          {"text": "Monitor network performance",
                           "is_correct": False},
                          {"text": "Backup system data",
                           "is_correct": False},
                          {"text": "Train security personnel",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security model focuses on data integrity rather than confidentiality?",
              "explanation": "The Biba model is a security model that focuses on data integrity by preventing unauthorized modification of data, using 'no write up, no read down' principles.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/security-models-integrity-34692",
              "points": 1,
              "answers": [{"text": "Biba model",
                           "is_correct": True},
                          {"text": "Bell-LaPadula model",
                           "is_correct": False},
                          {"text": "Clark-Wilson model",
                           "is_correct": False},
                          {"text": "Chinese Wall model",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of security incident recovery?",
              "explanation": "Security incident recovery involves restoring affected systems and services to normal operation while ensuring that the vulnerability that allowed the incident has been addressed.",
              "reference": "https://www.sans.org/reading-room/whitepapers/incident/incident-recovery-34692",
              "points": 1,
              "answers": [{"text": "Restore systems to normal operation and address vulnerabilities",
                           "is_correct": True,
                           },
                          {"text": "Identify the attacker",
                           "is_correct": False},
                          {"text": "Calculate financial losses",
                           "is_correct": False},
                          {"text": "Update security policies",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique is used to hide the existence of data within other data?",
              "explanation": "Steganography is the practice of concealing information within other non-secret data or physical objects, hiding the very existence of the secret information.",
              "reference": "https://www.sans.org/reading-room/whitepapers/steganography/steganography-techniques-34692",
              "points": 1,
              "answers": [{"text": "Steganography",
                           "is_correct": True},
                          {"text": "Cryptography",
                           "is_correct": False},
                          {"text": "Hashing",
                           "is_correct": False},
                          {"text": "Compression",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of a demilitarized zone (DMZ) in network security?",
              "explanation": "A DMZ is a network segment that sits between the internal network and external networks (like the internet), providing a buffer zone for publicly accessible services while protecting the internal network.",
              "reference": "https://www.sans.org/reading-room/whitepapers/firewalls/dmz-network-security-34692",
              "points": 1,
              "answers": [{"text": "Provide a buffer zone between internal and external networks",
                           "is_correct": True,
                           },
                          {"text": "Improve network performance",
                           "is_correct": False},
                          {"text": "Reduce hardware costs",
                           "is_correct": False},
                          {"text": "Simplify network management",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of access control makes access decisions based on attributes of the user, resource, and environment?",
              "explanation": "Attribute-Based Access Control (ABAC) makes access decisions by evaluating attributes associated with the user, resource, action, and environment context.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/attribute-based-access-control-34692",
              "points": 1,
              "answers": [{"text": "Attribute-Based Access Control (ABAC)",
                           "is_correct": True},
                          {"text": "Role-Based Access Control (RBAC)",
                           "is_correct": False},
                          {"text": "Mandatory Access Control (MAC)",
                           "is_correct": False},
                          {"text": "Discretionary Access Control (DAC)",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary function of a Security Token Service (STS)?",
              "explanation": "A Security Token Service issues, validates, and manages security tokens used for authentication and authorization in distributed systems and federated identity scenarios.",
              "reference": "https://www.sans.org/reading-room/whitepapers/authentication/security-token-service-34692",
              "points": 1,
              "answers": [{"text": "Issue and manage security tokens for authentication",
                           "is_correct": True,
                           },
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Encrypt data at rest",
                           "is_correct": False},
                          {"text": "Manage user passwords",
                           "is_correct": False},
                          ],
              },
             {"text": "Which attack technique involves exploiting buffer overflows to execute malicious code?",
              "explanation": "Buffer overflow attacks exploit programming errors where data exceeds the allocated buffer space, potentially allowing attackers to overwrite memory and execute arbitrary code.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/buffer-overflow-attacks-34692",
              "points": 1,
              "answers": [{"text": "Buffer overflow attack",
                           "is_correct": True},
                          {"text": "Format string attack",
                           "is_correct": False},
                          {"text": "Race condition attack",
                           "is_correct": False},
                          {"text": "Integer overflow attack",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of security awareness metrics?",
              "explanation": "Security awareness metrics measure the effectiveness of security training programs and help identify areas where additional education or reinforcement is needed.",
              "reference": "https://www.sans.org/reading-room/whitepapers/awareness/security-awareness-metrics-34692",
              "points": 1,
              "answers": [{"text": "Measure effectiveness of security training programs",
                           "is_correct": True,
                           },
                          {"text": "Monitor network performance",
                           "is_correct": False},
                          {"text": "Track system uptime",
                           "is_correct": False},
                          {"text": "Measure encryption strength",
                           "is_correct": False},
                          ],
              },
             {"text": "Which protocol is commonly used for secure file transfer over networks?",
              "explanation": "Secure File Transfer Protocol (SFTP) and SSH File Transfer Protocol provide secure file transfer capabilities over networks using encryption and authentication.",
              "reference": "https://www.sans.org/reading-room/whitepapers/protocols/secure-file-transfer-34692",
              "points": 1,
              "answers": [{"text": "SFTP (Secure File Transfer Protocol)",
                           "is_correct": True},
                          {"text": "FTP (File Transfer Protocol)",
                           "is_correct": False},
                          {"text": "TFTP (Trivial File Transfer Protocol)",
                           "is_correct": False},
                          {"text": "HTTP (Hypertext Transfer Protocol)",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of security testing in software development?",
              "explanation": "Security testing aims to identify vulnerabilities, weaknesses, and security flaws in applications before they are deployed to production environments.",
              "reference": "https://www.sans.org/reading-room/whitepapers/application/security-testing-software-34692",
              "points": 1,
              "answers": [{"text": "Identify vulnerabilities and security flaws before deployment",
                           "is_correct": True,
                           },
                          {"text": "Improve application performance",
                           "is_correct": False},
                          {"text": "Reduce development costs",
                           "is_correct": False},
                          {"text": "Simplify user interfaces",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of authentication relies on something the user knows, has, and is?",
              "explanation": "Three-factor authentication combines something you know (password), something you have (token), and something you are (biometric) for maximum security.",
              "reference": "https://www.sans.org/reading-room/whitepapers/authentication/multi-factor-authentication-types-34692",
              "points": 1,
              "answers": [{"text": "Three-factor authentication",
                           "is_correct": True},
                          {"text": "Two-factor authentication",
                           "is_correct": False},
                          {"text": "Single sign-on",
                           "is_correct": False},
                          {"text": "Mutual authentication",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of security log analysis?",
              "explanation": "Security log analysis involves examining log files to detect security incidents, identify patterns of suspicious activity, and support forensic investigations.",
              "reference": "https://www.sans.org/reading-room/whitepapers/logging/security-log-analysis-34692",
              "points": 1,
              "answers": [{"text": "Detect security incidents and identify suspicious activity patterns",
                           "is_correct": True,
                           },
                          {"text": "Improve system performance",
                           "is_correct": False},
                          {"text": "Reduce storage costs",
                           "is_correct": False},
                          {"text": "Simplify system administration",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security control type is designed to detect security violations after they occur?",
              "explanation": "Detective controls are implemented to identify and alert on security violations, policy breaches, or unauthorized activities after they have occurred.",
              "reference": "https://www.sans.org/reading-room/whitepapers/basics/security-control-types-detective-34692",
              "points": 1,
              "answers": [{"text": "Detective controls",
                           "is_correct": True},
                          {"text": "Preventive controls",
                           "is_correct": False},
                          {"text": "Corrective controls",
                           "is_correct": False},
                          {"text": "Compensating controls",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary function of a Certificate Revocation List (CRL)?",
              "explanation": "A Certificate Revocation List (CRL) is a list of digital certificates that have been revoked before their expiration date and should no longer be trusted.",
              "reference": "https://www.sans.org/reading-room/whitepapers/PKI/certificate-revocation-lists-34692",
              "points": 1,
              "answers": [{"text": "List certificates that have been revoked and should not be trusted",
                           "is_correct": True,
                           },
                          {"text": "Store valid certificates",
                           "is_correct": False},
                          {"text": "Generate new certificates",
                           "is_correct": False},
                          {"text": "Encrypt certificate data",
                           "is_correct": False},
                          ],
              },
             {"text": "Which attack technique involves sending malformed packets to crash or disrupt systems?",
              "explanation": "A malformed packet attack sends packets with invalid or unexpected data that can cause systems to crash, hang, or behave unexpectedly due to poor input validation.",
              "reference": "https://www.sans.org/reading-room/whitepapers/detection/malformed-packet-attacks-34692",
              "points": 1,
              "answers": [{"text": "Malformed packet attack",
                           "is_correct": True},
                          {"text": "Packet sniffing",
                           "is_correct": False},
                          {"text": "Packet replay",
                           "is_correct": False},
                          {"text": "Packet fragmentation",
                           "is_correct": False},
                          ],
              },
             ]
