"""GCFA (GIAC Certified Forensic Analyst) Certification"""

CERTIFICATION = {
    "name": "GCFA - GIAC Certified Forensic Analyst",
    "description": "Digital forensics skills for investigating computer incidents and crimes",
    "slug": "giac-gcfa",
    "level": "Advanced",
    "duration": 15,
    "questions_count": 5,
    "category_slug": "cybersecurity",
    "is_active": True,
}

QUESTIONS = [{"text": "What is the chain of custody in digital forensics?",
              "explanation": "Chain of custody is a legal concept that describes the chronological documentation showing the seizure, custody, control, transfer, analysis, and disposition of evidence.",
              "reference": "https://www.sans.org/reading-room/whitepapers/legal/legal-issues-conducting-computer-forensics-34852",
              "points": 1,
              "answers": [{"text": "Documentation of evidence handling from collection to court",
                           "is_correct": True,
                           },
                          {"text": "A forensic software tool",
                           "is_correct": False},
                          {"text": "A type of encryption",
                           "is_correct": False},
                          {"text": "A network security protocol",
                           "is_correct": False},
                          ],
              },
             {"text": "Which file system is commonly found on Windows systems?",
              "explanation": "NTFS (New Technology File System) is the primary file system used by modern Windows operating systems, providing features like file-level security, compression, and encryption.",
              "reference": "https://docs.microsoft.com/en-us/windows/desktop/fileio/file-systems",
              "points": 1,
              "answers": [{"text": "NTFS",
                           "is_correct": True},
                          {"text": "EXT4",
                           "is_correct": False},
                          {"text": "HFS+",
                           "is_correct": False},
                          {"text": "ZFS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is slack space in digital forensics?",
              "explanation": "Slack space is the unused space in a disk cluster. When a file doesn't completely fill a cluster, the remaining space becomes slack space, which may contain remnants of previously deleted files.",
              "reference": "https://www.sans.org/reading-room/whitepapers/forensics/understanding-slack-space-34521",
              "points": 1,
              "answers": [{"text": "Unused space in disk clusters that may contain old data",
                           "is_correct": True,
                           },
                          {"text": "Free memory in RAM",
                           "is_correct": False},
                          {"text": "Bandwidth not being used",
                           "is_correct": False},
                          {"text": "Empty registry entries",
                           "is_correct": False},
                          ],
              },
             {"text": "Which forensic technique can recover deleted files?",
              "explanation": "File carving is a forensic technique that recovers files without relying on file system metadata by searching for file headers and footers in raw data.",
              "reference": "https://www.sans.org/reading-room/whitepapers/forensics/file-carving-digital-forensics-35622",
              "points": 1,
              "answers": [{"text": "File carving",
                           "is_correct": True},
                          {"text": "Password cracking",
                           "is_correct": False},
                          {"text": "Network scanning",
                           "is_correct": False},
                          {"text": "Vulnerability assessment",
                           "is_correct": False},
                          ],
              },
             {"text": "What is volatile memory analysis used for?",
              "explanation": "Volatile memory (RAM) analysis can reveal running processes, network connections, encryption keys, and other information that exists only in memory and would be lost when the system is powered off.",
              "reference": "https://www.sans.org/reading-room/whitepapers/forensics/extracting-windows-volatile-memory-analyzing-advanced-malware-36192",
              "points": 1,
              "answers": [{"text": "Analyzing data in RAM that disappears when power is lost",
                           "is_correct": True,
                           },
                          {"text": "Examining hard drive contents",
                           "is_correct": False},
                          {"text": "Reviewing system logs",
                           "is_correct": False},
                          {"text": "Monitoring network traffic",
                           "is_correct": False},
                          ],
              },
             ]
