"""CompTIA Linux+ Certification"""

CERTIFICATION = {
    "name": "CompTIA Linux+",
    "description": "Linux system administration and troubleshooting skills",
    "slug": "comptia-linux-plus",
    "level": "Professional",
    "duration": 243,
    "questions_count": 81,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which command is used to change file permissions in Linux?",
        "explanation": "The chmod command is used to change file and directory permissions in Linux systems.",
        "reference": "https://man7.org/linux/man-pages/man1/chmod.1.html",
        "points": 1,
        "answers": [
            {"text": "chown", "is_correct": False},
            {"text": "chmod", "is_correct": True},
            {"text": "chgrp", "is_correct": False},
            {"text": "umask", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'ps aux' command display?",
        "explanation": "The 'ps aux' command shows detailed information about all running processes including user, CPU usage, memory usage, and command.",
        "reference": "https://man7.org/linux/man-pages/man1/ps.1.html",
        "points": 1,
        "answers": [
            {"text": "Network connections", "is_correct": False},
            {"text": "File system usage", "is_correct": False},
            {"text": "Running processes", "is_correct": True},
            {"text": "System logs", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains user account information in Linux?",
        "explanation": "/etc/passwd contains user account information including username, UID, GID, home directory, and shell.",
        "reference": "https://man7.org/linux/man-pages/man5/passwd.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/passwd", "is_correct": True},
            {"text": "/etc/shadow", "is_correct": False},
            {"text": "/etc/group", "is_correct": False},
            {"text": "/etc/hosts", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'grep' command?",
        "explanation": "The grep command searches for patterns in text files and displays matching lines.",
        "reference": "https://man7.org/linux/man-pages/man1/grep.1.html",
        "points": 1,
        "answers": [
            {"text": "Copy files", "is_correct": False},
            {"text": "Search text patterns", "is_correct": True},
            {"text": "Compress files", "is_correct": False},
            {"text": "Edit files", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create a new directory?",
        "explanation": "The mkdir command creates new directories in the Linux file system.",
        "reference": "https://man7.org/linux/man-pages/man1/mkdir.1.html",
        "points": 1,
        "answers": [
            {"text": "makedir", "is_correct": False},
            {"text": "mkdir", "is_correct": True},
            {"text": "createdir", "is_correct": False},
            {"text": "newdir", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'df' command show?",
        "explanation": "The df command displays disk space usage for mounted file systems.",
        "reference": "https://man7.org/linux/man-pages/man1/df.1.html",
        "points": 1,
        "answers": [
            {"text": "Running processes", "is_correct": False},
            {"text": "Disk space usage", "is_correct": True},
            {"text": "Network connections", "is_correct": False},
            {"text": "System memory", "is_correct": False},
        ],
    },
    {
        "text": "Which file system is commonly used as the default in modern Linux distributions?",
        "explanation": "ext4 is the most commonly used default file system in modern Linux distributions, offering journaling and better performance.",
        "reference": "https://ext4.wiki.kernel.org/index.php/Main_Page",
        "points": 1,
        "answers": [
            {"text": "ext2", "is_correct": False},
            {"text": "ext3", "is_correct": False},
            {"text": "ext4", "is_correct": True},
            {"text": "ntfs", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'sudo' command?",
        "explanation": "The sudo command allows users to execute commands with elevated privileges, typically as root.",
        "reference": "https://man7.org/linux/man-pages/man8/sudo.8.html",
        "points": 1,
        "answers": [
            {"text": "Switch users", "is_correct": False},
            {"text": "Execute commands with elevated privileges", "is_correct": True},
            {"text": "Schedule tasks", "is_correct": False},
            {"text": "Mount file systems", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display the manual page for a command?",
        "explanation": "The man command displays the manual pages for commands, providing detailed documentation.",
        "reference": "https://man7.org/linux/man-pages/man1/man.1.html",
        "points": 1,
        "answers": [
            {"text": "help", "is_correct": False},
            {"text": "man", "is_correct": True},
            {"text": "info", "is_correct": False},
            {"text": "doc", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'ls -la' command display?",
        "explanation": "The 'ls -la' command lists all files including hidden ones (-a) in long format (-l) showing permissions, ownership, size, and timestamps.",
        "reference": "https://man7.org/linux/man-pages/man1/ls.1.html",
        "points": 1,
        "answers": [
            {"text": "Only directories", "is_correct": False},
            {
                "text": "All files in long format including hidden files",
                "is_correct": True,
            },
            {"text": "Only executable files", "is_correct": False},
            {"text": "File content", "is_correct": False},
        ],
    },
    {
        "text": "Which service management system is used by most modern Linux distributions?",
        "explanation": "systemd is the service management system used by most modern Linux distributions, replacing older init systems.",
        "reference": "https://systemd.io/",
        "points": 1,
        "answers": [
            {"text": "SysV init", "is_correct": False},
            {"text": "systemd", "is_correct": True},
            {"text": "Upstart", "is_correct": False},
            {"text": "OpenRC", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /etc/fstab file?",
        "explanation": "/etc/fstab contains information about file systems and their mount points, used during system boot.",
        "reference": "https://man7.org/linux/man-pages/man5/fstab.5.html",
        "points": 1,
        "answers": [
            {"text": "User account information", "is_correct": False},
            {"text": "File system mount information", "is_correct": True},
            {"text": "Network configuration", "is_correct": False},
            {"text": "System logs", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to find files in Linux?",
        "explanation": "The find command is used to search for files and directories based on various criteria.",
        "reference": "https://man7.org/linux/man-pages/man1/find.1.html",
        "points": 1,
        "answers": [
            {"text": "search", "is_correct": False},
            {"text": "locate", "is_correct": False},
            {"text": "find", "is_correct": True},
            {"text": "grep", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'top' command display?",
        "explanation": "The top command displays real-time information about running processes and system resource usage.",
        "reference": "https://man7.org/linux/man-pages/man1/top.1.html",
        "points": 1,
        "answers": [
            {"text": "File permissions", "is_correct": False},
            {"text": "Real-time process information", "is_correct": True},
            {"text": "Network statistics", "is_correct": False},
            {"text": "Disk usage", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to copy files in Linux?",
        "explanation": "The cp command is used to copy files and directories in Linux.",
        "reference": "https://man7.org/linux/man-pages/man1/cp.1.html",
        "points": 1,
        "answers": [
            {"text": "copy", "is_correct": False},
            {"text": "cp", "is_correct": True},
            {"text": "mv", "is_correct": False},
            {"text": "ln", "is_correct": False},
        ],
    },
    {
        "text": "What is the default shell in most Linux distributions?",
        "explanation": "Bash (Bourne Again Shell) is the default shell in most Linux distributions.",
        "reference": "https://www.gnu.org/software/bash/",
        "points": 1,
        "answers": [
            {"text": "csh", "is_correct": False},
            {"text": "bash", "is_correct": True},
            {"text": "zsh", "is_correct": False},
            {"text": "fish", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change file ownership?",
        "explanation": "The chown command changes the ownership of files and directories.",
        "reference": "https://man7.org/linux/man-pages/man1/chown.1.html",
        "points": 1,
        "answers": [
            {"text": "chmod", "is_correct": False},
            {"text": "chown", "is_correct": True},
            {"text": "chgrp", "is_correct": False},
            {"text": "usermod", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'cat' command do?",
        "explanation": "The cat command concatenates and displays the content of files.",
        "reference": "https://man7.org/linux/man-pages/man1/cat.1.html",
        "points": 1,
        "answers": [
            {"text": "Create files", "is_correct": False},
            {"text": "Display file content", "is_correct": True},
            {"text": "Delete files", "is_correct": False},
            {"text": "Edit files", "is_correct": False},
        ],
    },
    {
        "text": "Which directory contains system log files?",
        "explanation": "/var/log is the standard directory for system log files in Linux.",
        "reference": "https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html",
        "points": 1,
        "answers": [
            {"text": "/etc/log", "is_correct": False},
            {"text": "/var/log", "is_correct": True},
            {"text": "/usr/log", "is_correct": False},
            {"text": "/tmp/log", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'tar' command?",
        "explanation": "The tar command is used to create, extract, and manipulate archive files.",
        "reference": "https://man7.org/linux/man-pages/man1/tar.1.html",
        "points": 1,
        "answers": [
            {"text": "Text processing", "is_correct": False},
            {"text": "Archive files", "is_correct": True},
            {"text": "Network testing", "is_correct": False},
            {"text": "Process management", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display network interface information?",
        "explanation": "The ifconfig command (or ip command on newer systems) displays network interface configuration.",
        "reference": "https://man7.org/linux/man-pages/man8/ifconfig.8.html",
        "points": 1,
        "answers": [
            {"text": "netstat", "is_correct": False},
            {"text": "ifconfig", "is_correct": True},
            {"text": "ping", "is_correct": False},
            {"text": "route", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'kill' command do?",
        "explanation": "The kill command sends signals to processes, typically to terminate them.",
        "reference": "https://man7.org/linux/man-pages/man1/kill.1.html",
        "points": 1,
        "answers": [
            {"text": "Delete files", "is_correct": False},
            {"text": "Terminate processes", "is_correct": True},
            {"text": "Stop services", "is_correct": False},
            {"text": "Shutdown system", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains DNS server information?",
        "explanation": "/etc/resolv.conf contains DNS server configuration information.",
        "reference": "https://man7.org/linux/man-pages/man5/resolv.conf.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/hosts", "is_correct": False},
            {"text": "/etc/resolv.conf", "is_correct": True},
            {"text": "/etc/network", "is_correct": False},
            {"text": "/etc/dns.conf", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'cron' service?",
        "explanation": "The cron service is used to schedule and execute tasks automatically at specified times.",
        "reference": "https://man7.org/linux/man-pages/man8/cron.8.html",
        "points": 1,
        "answers": [
            {"text": "File synchronization", "is_correct": False},
            {"text": "Task scheduling", "is_correct": True},
            {"text": "User authentication", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to mount a file system?",
        "explanation": "The mount command is used to attach file systems to the directory tree.",
        "reference": "https://man7.org/linux/man-pages/man8/mount.8.html",
        "points": 1,
        "answers": [
            {"text": "attach", "is_correct": False},
            {"text": "mount", "is_correct": True},
            {"text": "connect", "is_correct": False},
            {"text": "link", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'du' command show?",
        "explanation": "The du command displays disk usage by directories and files.",
        "reference": "https://man7.org/linux/man-pages/man1/du.1.html",
        "points": 1,
        "answers": [
            {"text": "System uptime", "is_correct": False},
            {"text": "Disk usage", "is_correct": True},
            {"text": "User activity", "is_correct": False},
            {"text": "Process duration", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change the current directory?",
        "explanation": "The cd command changes the current working directory.",
        "reference": "https://www.gnu.org/software/bash/manual/bash.html#Bourne-Shell-Builtins",
        "points": 1,
        "answers": [
            {"text": "chdir", "is_correct": False},
            {"text": "cd", "is_correct": True},
            {"text": "goto", "is_correct": False},
            {"text": "move", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /etc/shadow file?",
        "explanation": "/etc/shadow contains encrypted passwords and password aging information for user accounts.",
        "reference": "https://man7.org/linux/man-pages/man5/shadow.5.html",
        "points": 1,
        "answers": [
            {"text": "User account information", "is_correct": False},
            {"text": "Encrypted passwords", "is_correct": True},
            {"text": "Group information", "is_correct": False},
            {"text": "System configuration", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display the last few lines of a file?",
        "explanation": "The tail command displays the last few lines of a file, useful for monitoring log files.",
        "reference": "https://man7.org/linux/man-pages/man1/tail.1.html",
        "points": 1,
        "answers": [
            {"text": "head", "is_correct": False},
            {"text": "tail", "is_correct": True},
            {"text": "end", "is_correct": False},
            {"text": "last", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'w' command display?",
        "explanation": "The w command shows who is logged on and what they are doing.",
        "reference": "https://man7.org/linux/man-pages/man1/w.1.html",
        "points": 1,
        "answers": [
            {"text": "System load", "is_correct": False},
            {"text": "Logged-in users and their activities", "is_correct": True},
            {"text": "Network connections", "is_correct": False},
            {"text": "File permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create a symbolic link?",
        "explanation": "The ln -s command creates symbolic (soft) links to files or directories.",
        "reference": "https://man7.org/linux/man-pages/man1/ln.1.html",
        "points": 1,
        "answers": [
            {"text": "link", "is_correct": False},
            {"text": "ln -s", "is_correct": True},
            {"text": "symlink", "is_correct": False},
            {"text": "mklink", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'history' command?",
        "explanation": "The history command displays the command history of the current shell session.",
        "reference": "https://www.gnu.org/software/bash/manual/bash.html#History-Builtins",
        "points": 1,
        "answers": [
            {"text": "Show file history", "is_correct": False},
            {"text": "Display command history", "is_correct": True},
            {"text": "Show system events", "is_correct": False},
            {"text": "Display login history", "is_correct": False},
        ],
    },
    {
        "text": "Which runlevel represents single-user mode in traditional SysV init?",
        "explanation": "Runlevel 1 represents single-user mode, used for system maintenance and recovery.",
        "reference": "https://man7.org/linux/man-pages/man8/init.8.html",
        "points": 1,
        "answers": [
            {"text": "0", "is_correct": False},
            {"text": "1", "is_correct": True},
            {"text": "2", "is_correct": False},
            {"text": "3", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'which' command do?",
        "explanation": "The which command locates and displays the path of executable commands.",
        "reference": "https://man7.org/linux/man-pages/man1/which.1.html",
        "points": 1,
        "answers": [
            {"text": "Find files", "is_correct": False},
            {"text": "Locate executable commands", "is_correct": True},
            {"text": "Show file type", "is_correct": False},
            {"text": "Display permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display system memory usage?",
        "explanation": "The free command displays system memory usage including RAM and swap space.",
        "reference": "https://man7.org/linux/man-pages/man1/free.1.html",
        "points": 1,
        "answers": [
            {"text": "mem", "is_correct": False},
            {"text": "free", "is_correct": True},
            {"text": "memory", "is_correct": False},
            {"text": "ram", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /proc directory?",
        "explanation": "/proc is a virtual file system that provides information about running processes and system status.",
        "reference": "https://man7.org/linux/man-pages/man5/proc.5.html",
        "points": 1,
        "answers": [
            {"text": "Store process executables", "is_correct": False},
            {"text": "Virtual file system for process information", "is_correct": True},
            {"text": "Process logs", "is_correct": False},
            {"text": "Process configuration", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to compress files using gzip?",
        "explanation": "The gzip command compresses files using the gzip compression algorithm.",
        "reference": "https://man7.org/linux/man-pages/man1/gzip.1.html",
        "points": 1,
        "answers": [
            {"text": "compress", "is_correct": False},
            {"text": "gzip", "is_correct": True},
            {"text": "zip", "is_correct": False},
            {"text": "pack", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'uname -a' command display?",
        "explanation": "The 'uname -a' command displays all system information including kernel name, version, and architecture.",
        "reference": "https://man7.org/linux/man-pages/man1/uname.1.html",
        "points": 1,
        "answers": [
            {"text": "User information", "is_correct": False},
            {"text": "System information", "is_correct": True},
            {"text": "Network configuration", "is_correct": False},
            {"text": "Process list", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to search for text within files?",
        "explanation": "The grep command searches for patterns within files and displays matching lines.",
        "reference": "https://man7.org/linux/man-pages/man1/grep.1.html",
        "points": 1,
        "answers": [
            {"text": "find", "is_correct": False},
            {"text": "grep", "is_correct": True},
            {"text": "search", "is_correct": False},
            {"text": "locate", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'umask' command?",
        "explanation": "The umask command sets the default file permissions for newly created files and directories.",
        "reference": "https://man7.org/linux/man-pages/man2/umask.2.html",
        "points": 1,
        "answers": [
            {"text": "Mount file systems", "is_correct": False},
            {"text": "Set default file permissions", "is_correct": True},
            {"text": "Unmount file systems", "is_correct": False},
            {"text": "Create user masks", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains group information in Linux?",
        "explanation": "/etc/group contains group account information including group names, GIDs, and member lists.",
        "reference": "https://man7.org/linux/man-pages/man5/group.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/passwd", "is_correct": False},
            {"text": "/etc/group", "is_correct": True},
            {"text": "/etc/shadow", "is_correct": False},
            {"text": "/etc/users", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'whoami' command display?",
        "explanation": "The whoami command displays the username of the current user.",
        "reference": "https://man7.org/linux/man-pages/man1/whoami.1.html",
        "points": 1,
        "answers": [
            {"text": "System hostname", "is_correct": False},
            {"text": "Current username", "is_correct": True},
            {"text": "User ID", "is_correct": False},
            {"text": "Group membership", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display the first few lines of a file?",
        "explanation": "The head command displays the first few lines of a file (default is 10 lines).",
        "reference": "https://man7.org/linux/man-pages/man1/head.1.html",
        "points": 1,
        "answers": [
            {"text": "top", "is_correct": False},
            {"text": "head", "is_correct": True},
            {"text": "first", "is_correct": False},
            {"text": "begin", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'passwd' command?",
        "explanation": "The passwd command is used to change user passwords.",
        "reference": "https://man7.org/linux/man-pages/man1/passwd.1.html",
        "points": 1,
        "answers": [
            {"text": "View password file", "is_correct": False},
            {"text": "Change user passwords", "is_correct": True},
            {"text": "Create user accounts", "is_correct": False},
            {"text": "Lock user accounts", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display active network connections?",
        "explanation": "The netstat command displays active network connections, routing tables, and network statistics.",
        "reference": "https://man7.org/linux/man-pages/man8/netstat.8.html",
        "points": 1,
        "answers": [
            {"text": "ifconfig", "is_correct": False},
            {"text": "netstat", "is_correct": True},
            {"text": "ping", "is_correct": False},
            {"text": "route", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'jobs' command display?",
        "explanation": "The jobs command displays active jobs (background and suspended processes) in the current shell.",
        "reference": "https://www.gnu.org/software/bash/manual/bash.html#Job-Control-Builtins",
        "points": 1,
        "answers": [
            {"text": "System processes", "is_correct": False},
            {"text": "Active shell jobs", "is_correct": True},
            {"text": "Scheduled tasks", "is_correct": False},
            {"text": "User sessions", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to sort lines in a file?",
        "explanation": "The sort command arranges lines of text in alphabetical, numerical, or other specified order.",
        "reference": "https://man7.org/linux/man-pages/man1/sort.1.html",
        "points": 1,
        "answers": [
            {"text": "order", "is_correct": False},
            {"text": "sort", "is_correct": True},
            {"text": "arrange", "is_correct": False},
            {"text": "organize", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'crontab' command?",
        "explanation": "The crontab command is used to create, edit, and manage user-specific cron jobs.",
        "reference": "https://man7.org/linux/man-pages/man1/crontab.1.html",
        "points": 1,
        "answers": [
            {"text": "View system time", "is_correct": False},
            {"text": "Manage scheduled tasks", "is_correct": True},
            {"text": "Configure network", "is_correct": False},
            {"text": "Monitor processes", "is_correct": False},
        ],
    },
    {
        "text": "Which signal does 'kill -9' send to a process?",
        "explanation": "Signal 9 (SIGKILL) is an unconditional kill signal that immediately terminates a process.",
        "reference": "https://man7.org/linux/man-pages/man7/signal.7.html",
        "points": 1,
        "answers": [
            {"text": "SIGTERM", "is_correct": False},
            {"text": "SIGKILL", "is_correct": True},
            {"text": "SIGHUP", "is_correct": False},
            {"text": "SIGINT", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'lsof' command display?",
        "explanation": "The lsof command lists open files and the processes that opened them.",
        "reference": "https://man7.org/linux/man-pages/man8/lsof.8.html",
        "points": 1,
        "answers": [
            {"text": "System logs", "is_correct": False},
            {"text": "Open files and processes", "is_correct": True},
            {"text": "File system structure", "is_correct": False},
            {"text": "Library files", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change group ownership of files?",
        "explanation": "The chgrp command changes the group ownership of files and directories.",
        "reference": "https://man7.org/linux/man-pages/man1/chgrp.1.html",
        "points": 1,
        "answers": [
            {"text": "chown", "is_correct": False},
            {"text": "chgrp", "is_correct": True},
            {"text": "chmod", "is_correct": False},
            {"text": "groupmod", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /boot directory?",
        "explanation": "The /boot directory contains boot loader files, kernel images, and initial RAM disk images needed for system startup.",
        "reference": "https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s05.html",
        "points": 1,
        "answers": [
            {"text": "User home directories", "is_correct": False},
            {"text": "Boot loader and kernel files", "is_correct": True},
            {"text": "System configuration", "is_correct": False},
            {"text": "Temporary files", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display disk partitions?",
        "explanation": "The fdisk -l command lists all disk partitions on the system.",
        "reference": "https://man7.org/linux/man-pages/man8/fdisk.8.html",
        "points": 1,
        "answers": [
            {"text": "partitions", "is_correct": False},
            {"text": "fdisk -l", "is_correct": True},
            {"text": "lsblk", "is_correct": False},
            {"text": "diskutil", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'id' command display?",
        "explanation": "The id command displays user and group IDs for the current user or specified user.",
        "reference": "https://man7.org/linux/man-pages/man1/id.1.html",
        "points": 1,
        "answers": [
            {"text": "Process IDs", "is_correct": False},
            {"text": "User and group IDs", "is_correct": True},
            {"text": "System identification", "is_correct": False},
            {"text": "Network interfaces", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains the system hostname?",
        "explanation": "/etc/hostname contains the system's hostname configuration.",
        "reference": "https://man7.org/linux/man-pages/man5/hostname.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/hosts", "is_correct": False},
            {"text": "/etc/hostname", "is_correct": True},
            {"text": "/etc/sysconfig/network", "is_correct": False},
            {"text": "/etc/network/interfaces", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'alias' command?",
        "explanation": "The alias command creates shortcuts for longer commands, allowing users to define custom command abbreviations.",
        "reference": "https://www.gnu.org/software/bash/manual/bash.html#Aliases",
        "points": 1,
        "answers": [
            {"text": "Change file names", "is_correct": False},
            {"text": "Create command shortcuts", "is_correct": True},
            {"text": "Link files", "is_correct": False},
            {"text": "Rename users", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display system uptime?",
        "explanation": "The uptime command shows how long the system has been running and system load averages.",
        "reference": "https://man7.org/linux/man-pages/man1/uptime.1.html",
        "points": 1,
        "answers": [
            {"text": "runtime", "is_correct": False},
            {"text": "uptime", "is_correct": True},
            {"text": "systemtime", "is_correct": False},
            {"text": "boottime", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'awk' command do?",
        "explanation": "The awk command is a pattern scanning and processing language, useful for text processing and data extraction.",
        "reference": "https://man7.org/linux/man-pages/man1/awk.1p.html",
        "points": 1,
        "answers": [
            {"text": "Archive files", "is_correct": False},
            {"text": "Pattern scanning and text processing", "is_correct": True},
            {"text": "Network testing", "is_correct": False},
            {"text": "Audio processing", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display file type information?",
        "explanation": "The file command determines and displays the type of a file based on its content.",
        "reference": "https://man7.org/linux/man-pages/man1/file.1.html",
        "points": 1,
        "answers": [
            {"text": "type", "is_correct": False},
            {"text": "file", "is_correct": True},
            {"text": "info", "is_correct": False},
            {"text": "stat", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'screen' command?",
        "explanation": "The screen command creates virtual terminal sessions that can be detached and reattached, useful for long-running processes.",
        "reference": "https://man7.org/linux/man-pages/man1/screen.1.html",
        "points": 1,
        "answers": [
            {"text": "Display management", "is_correct": False},
            {"text": "Virtual terminal sessions", "is_correct": True},
            {"text": "Screen capture", "is_correct": False},
            {"text": "System monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change user password aging information?",
        "explanation": "The chage command is used to change user password expiry information and aging policies.",
        "reference": "https://man7.org/linux/man-pages/man1/chage.1.html",
        "points": 1,
        "answers": [
            {"text": "passwd", "is_correct": False},
            {"text": "chage", "is_correct": True},
            {"text": "usermod", "is_correct": False},
            {"text": "pwdage", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'dmesg' command display?",
        "explanation": "The dmesg command displays kernel ring buffer messages, including boot messages and hardware detection information.",
        "reference": "https://man7.org/linux/man-pages/man1/dmesg.1.html",
        "points": 1,
        "answers": [
            {"text": "Disk messages", "is_correct": False},
            {"text": "Kernel ring buffer messages", "is_correct": True},
            {"text": "Debug messages", "is_correct": False},
            {"text": "Daemon messages", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create user accounts?",
        "explanation": "The useradd command creates new user accounts on the system.",
        "reference": "https://man7.org/linux/man-pages/man8/useradd.8.html",
        "points": 1,
        "answers": [
            {"text": "adduser", "is_correct": False},
            {"text": "useradd", "is_correct": True},
            {"text": "newuser", "is_correct": False},
            {"text": "createuser", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'rsync' command?",
        "explanation": "The rsync command synchronizes files and directories between local and remote systems efficiently.",
        "reference": "https://man7.org/linux/man-pages/man1/rsync.1.html",
        "points": 1,
        "answers": [
            {"text": "Remove files", "is_correct": False},
            {"text": "Synchronize files and directories", "is_correct": True},
            {"text": "Restart services", "is_correct": False},
            {"text": "Reset system", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains kernel boot parameters?",
        "explanation": "/proc/cmdline contains the kernel command line parameters used during boot.",
        "reference": "https://man7.org/linux/man-pages/man5/proc.5.html",
        "points": 1,
        "answers": [
            {"text": "/boot/grub/grub.conf", "is_correct": False},
            {"text": "/proc/cmdline", "is_correct": True},
            {"text": "/etc/default/grub", "is_correct": False},
            {"text": "/boot/config", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'watch' command do?",
        "explanation": "The watch command repeatedly executes a command and displays its output, useful for monitoring changes.",
        "reference": "https://man7.org/linux/man-pages/man1/watch.1.html",
        "points": 1,
        "answers": [
            {"text": "Monitor file changes", "is_correct": False},
            {
                "text": "Repeatedly execute and display command output",
                "is_correct": True,
            },
            {"text": "Watch system processes", "is_correct": False},
            {"text": "Time command execution", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to delete user accounts?",
        "explanation": "The userdel command removes user accounts from the system.",
        "reference": "https://man7.org/linux/man-pages/man8/userdel.8.html",
        "points": 1,
        "answers": [
            {"text": "deluser", "is_correct": False},
            {"text": "userdel", "is_correct": True},
            {"text": "removeuser", "is_correct": False},
            {"text": "userrem", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'nohup' command?",
        "explanation": "The nohup command runs commands immune to hangups, allowing processes to continue after logout.",
        "reference": "https://man7.org/linux/man-pages/man1/nohup.1.html",
        "points": 1,
        "answers": [
            {"text": "Prevent process termination on logout", "is_correct": True},
            {"text": "No hardware updates", "is_correct": False},
            {"text": "Disable help messages", "is_correct": False},
            {"text": "No user permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays information about CPU architecture?",
        "explanation": "The lscpu command displays detailed information about the CPU architecture and features.",
        "reference": "https://man7.org/linux/man-pages/man1/lscpu.1.html",
        "points": 1,
        "answers": [
            {"text": "cpuinfo", "is_correct": False},
            {"text": "lscpu", "is_correct": True},
            {"text": "cpustat", "is_correct": False},
            {"text": "archinfo", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'cut' command do?",
        "explanation": "The cut command extracts specific columns or fields from text files or command output.",
        "reference": "https://man7.org/linux/man-pages/man1/cut.1.html",
        "points": 1,
        "answers": [
            {"text": "Delete files", "is_correct": False},
            {"text": "Extract columns or fields from text", "is_correct": True},
            {"text": "Truncate files", "is_correct": False},
            {"text": "Split files", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display PCI devices?",
        "explanation": "The lspci command lists all PCI devices connected to the system.",
        "reference": "https://man7.org/linux/man-pages/man8/lspci.8.html",
        "points": 1,
        "answers": [
            {"text": "pcilist", "is_correct": False},
            {"text": "lspci", "is_correct": True},
            {"text": "pciinfo", "is_correct": False},
            {"text": "showpci", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'xargs' command?",
        "explanation": "The xargs command builds and executes command lines from standard input, useful for processing lists of files.",
        "reference": "https://man7.org/linux/man-pages/man1/xargs.1.html",
        "points": 1,
        "answers": [
            {"text": "Extract archives", "is_correct": False},
            {"text": "Build and execute command lines from input", "is_correct": True},
            {"text": "Execute X11 programs", "is_correct": False},
            {"text": "Transfer files", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains system-wide environment variables?",
        "explanation": "/etc/environment contains system-wide environment variable definitions.",
        "reference": "https://help.ubuntu.com/community/EnvironmentVariables",
        "points": 1,
        "answers": [
            {"text": "/etc/profile", "is_correct": False},
            {"text": "/etc/environment", "is_correct": True},
            {"text": "/etc/bashrc", "is_correct": False},
            {"text": "/etc/exports", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'stat' command display?",
        "explanation": "The stat command displays detailed file or file system status information including permissions, timestamps, and inode data.",
        "reference": "https://man7.org/linux/man-pages/man1/stat.1.html",
        "points": 1,
        "answers": [
            {"text": "System statistics", "is_correct": False},
            {"text": "Detailed file status information", "is_correct": True},
            {"text": "Process statistics", "is_correct": False},
            {"text": "Network statistics", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to modify user account properties?",
        "explanation": "The usermod command modifies existing user account properties such as home directory, shell, or group membership.",
        "reference": "https://man7.org/linux/man-pages/man8/usermod.8.html",
        "points": 1,
        "answers": [
            {"text": "moduser", "is_correct": False},
            {"text": "usermod", "is_correct": True},
            {"text": "chuser", "is_correct": False},
            {"text": "edituser", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'su' command?",
        "explanation": "The su command switches to another user account, commonly used to become root or another user.",
        "reference": "https://man7.org/linux/man-pages/man1/su.1.html",
        "points": 1,
        "answers": [
            {"text": "System update", "is_correct": False},
            {"text": "Switch user", "is_correct": True},
            {"text": "System utilities", "is_correct": False},
            {"text": "Show users", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays USB devices connected to the system?",
        "explanation": "The lsusb command lists all USB devices connected to the system.",
        "reference": "https://man7.org/linux/man-pages/man8/lsusb.8.html",
        "points": 1,
        "answers": [
            {"text": "usblist", "is_correct": False},
            {"text": "lsusb", "is_correct": True},
            {"text": "usbinfo", "is_correct": False},
            {"text": "showusb", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'tr' command do?",
        "explanation": "The tr command translates or deletes characters from standard input, useful for text transformation.",
        "reference": "https://man7.org/linux/man-pages/man1/tr.1.html",
        "points": 1,
        "answers": [
            {"text": "Transfer files", "is_correct": False},
            {"text": "Translate or delete characters", "is_correct": True},
            {"text": "Trace processes", "is_correct": False},
            {"text": "Tree structure", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display or modify network interface configuration?",
        "explanation": "The ip command is the modern tool for displaying and configuring network interfaces, replacing ifconfig.",
        "reference": "https://man7.org/linux/man-pages/man8/ip.8.html",
        "points": 1,
        "answers": [
            {"text": "ifconfig", "is_correct": False},
            {"text": "ip", "is_correct": True},
            {"text": "netconfig", "is_correct": False},
            {"text": "network", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'systemctl' command?",
        "explanation": "The systemctl command controls systemd services and units, used to start, stop, enable, and manage services.",
        "reference": "https://man7.org/linux/man-pages/man1/systemctl.1.html",
        "points": 1,
        "answers": [
            {"text": "System control panel", "is_correct": False},
            {"text": "Control systemd services", "is_correct": True},
            {"text": "System configuration", "is_correct": False},
            {"text": "System catalog", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains the message of the day displayed at login?",
        "explanation": "/etc/motd contains the message of the day that is displayed to users when they log in.",
        "reference": "https://man7.org/linux/man-pages/man5/motd.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/issue", "is_correct": False},
            {"text": "/etc/motd", "is_correct": True},
            {"text": "/etc/banner", "is_correct": False},
            {"text": "/etc/welcome", "is_correct": False},
        ],
    },
]
