"""Linux Foundation Certified Engineer (LFCE)"""

CERTIFICATION = {
    "name": "Linux Foundation Certified Engineer (LFCE)",
    "description": "Advanced Linux engineering and enterprise system administration",
    "slug": "lfce",
    "level": "Expert",
    "duration": 159,
    "questions_count": 53,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which tool is commonly used for configuration management and automation in Linux environments?",
        "explanation": "Ansible is a popular configuration management tool that uses YAML playbooks to automate system configuration and deployment tasks.",
        "reference": "https://training.linuxfoundation.org/certification/linux-foundation-certified-engineer-lfce/",
        "points": 1,
        "answers": [
            {"text": "Ansible", "is_correct": True},
            {"text": "grep", "is_correct": False},
            {"text": "vim", "is_correct": False},
            {"text": "cron", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary purpose of HAProxy in Linux infrastructure?",
        "explanation": "HAProxy is a high-performance load balancer and proxy server used for distributing incoming requests across multiple backend servers.",
        "reference": "https://www.haproxy.org/download/1.8/doc/configuration.txt",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "Load balancing and proxying", "is_correct": True},
            {"text": "File system encryption", "is_correct": False},
            {"text": "User authentication", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create and manage Linux containers with Docker?",
        "explanation": "The docker command-line interface is used to create, manage, and interact with Docker containers and images.",
        "reference": "https://docs.docker.com/engine/reference/commandline/docker/",
        "points": 1,
        "answers": [
            {"text": "container", "is_correct": False},
            {"text": "docker", "is_correct": True},
            {"text": "lxc", "is_correct": False},
            {"text": "podman", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Kubernetes in container orchestration?",
        "explanation": "Kubernetes is a container orchestration platform that automates deployment, scaling, and management of containerized applications.",
        "reference": "https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/",
        "points": 1,
        "answers": [
            {"text": "Web server hosting", "is_correct": False},
            {"text": "Container orchestration and management", "is_correct": True},
            {"text": "Database administration", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which monitoring solution is commonly used for metrics collection in Linux systems?",
        "explanation": "Prometheus is a popular open-source monitoring and alerting system designed for reliability and scalability in dynamic environments.",
        "reference": "https://prometheus.io/docs/introduction/overview/",
        "points": 1,
        "answers": [
            {"text": "Apache", "is_correct": False},
            {"text": "Prometheus", "is_correct": True},
            {"text": "MySQL", "is_correct": False},
            {"text": "Redis", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to configure and manage systemd services?",
        "explanation": "systemctl is the primary command for controlling systemd services, enabling, disabling, starting, stopping, and checking service status.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemctl.html",
        "points": 1,
        "answers": [
            {"text": "service", "is_correct": False},
            {"text": "systemctl", "is_correct": True},
            {"text": "chkconfig", "is_correct": False},
            {"text": "init", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of LVM (Logical Volume Manager) in Linux?",
        "explanation": "LVM provides flexible disk space management by abstracting physical storage into logical volumes that can be easily resized and managed.",
        "reference": "https://tldp.org/HOWTO/LVM-HOWTO/",
        "points": 1,
        "answers": [
            {"text": "Network configuration", "is_correct": False},
            {"text": "Process management", "is_correct": False},
            {"text": "Logical volume management", "is_correct": True},
            {"text": "User authentication", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for creating and managing RAID arrays in Linux?",
        "explanation": "mdadm is the primary tool for managing software RAID arrays in Linux, allowing creation, monitoring, and maintenance of RAID devices.",
        "reference": "https://raid.wiki.kernel.org/index.php/A_guide_to_mdadm",
        "points": 1,
        "answers": [
            {"text": "fdisk", "is_correct": False},
            {"text": "mdadm", "is_correct": True},
            {"text": "parted", "is_correct": False},
            {"text": "lsblk", "is_correct": False},
        ],
    },
    {
        "text": "What is the default configuration file for the Apache HTTP server?",
        "explanation": "The main Apache configuration file is typically located at /etc/apache2/apache2.conf on Debian-based systems or /etc/httpd/conf/httpd.conf on Red Hat-based systems.",
        "reference": "https://httpd.apache.org/docs/2.4/configuring.html",
        "points": 1,
        "answers": [
            {"text": "/etc/apache2/apache2.conf", "is_correct": True},
            {"text": "/etc/nginx/nginx.conf", "is_correct": False},
            {"text": "/etc/httpd/httpd.conf", "is_correct": False},
            {"text": "/var/www/html/index.html", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to configure network interfaces persistently in RHEL/CentOS 8+?",
        "explanation": "nmcli (NetworkManager command line interface) is the primary tool for configuring network connections in modern RHEL/CentOS systems.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/getting-started-with-networkmanager_configuring-and-managing-networking",
        "points": 1,
        "answers": [
            {"text": "ifconfig", "is_correct": False},
            {"text": "nmcli", "is_correct": True},
            {"text": "ip", "is_correct": False},
            {"text": "netstat", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of SELinux in enterprise Linux systems?",
        "explanation": "SELinux (Security-Enhanced Linux) provides mandatory access control security policies to enhance system security beyond traditional discretionary access controls.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/index",
        "points": 1,
        "answers": [
            {"text": "Network monitoring", "is_correct": False},
            {"text": "Mandatory access control security", "is_correct": True},
            {"text": "Package management", "is_correct": False},
            {"text": "File system encryption", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to manage firewall rules in RHEL/CentOS 8+?",
        "explanation": "firewall-cmd is the command-line interface for firewalld, the dynamic firewall management tool in modern RHEL/CentOS systems.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/using-and-configuring-firewalls_securing-networks",
        "points": 1,
        "answers": [
            {"text": "iptables", "is_correct": False},
            {"text": "ufw", "is_correct": False},
            {"text": "firewall-cmd", "is_correct": True},
            {"text": "netfilter", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary configuration file for SSH daemon?",
        "explanation": "The SSH daemon configuration file is located at /etc/ssh/sshd_config and contains server-side SSH configuration options.",
        "reference": "https://man.openbsd.org/sshd_config",
        "points": 1,
        "answers": [
            {"text": "/etc/ssh/ssh_config", "is_correct": False},
            {"text": "/etc/ssh/sshd_config", "is_correct": True},
            {"text": "/home/.ssh/config", "is_correct": False},
            {"text": "/etc/sshd.conf", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for log analysis and centralized logging?",
        "explanation": "ELK Stack (Elasticsearch, Logstash, Kibana) or rsyslog are commonly used for centralized logging and log analysis in enterprise environments.",
        "reference": "https://www.elastic.co/what-is/elk-stack",
        "points": 1,
        "answers": [
            {"text": "tail", "is_correct": False},
            {"text": "ELK Stack", "is_correct": True},
            {"text": "grep", "is_correct": False},
            {"text": "less", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Nagios in Linux infrastructure monitoring?",
        "explanation": "Nagios is a comprehensive monitoring system that monitors hosts, services, and network devices, providing alerting and reporting capabilities.",
        "reference": "https://www.nagios.org/about/",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "Infrastructure monitoring and alerting", "is_correct": True},
            {"text": "Web development", "is_correct": False},
            {"text": "File backup", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create encrypted file systems with LUKS?",
        "explanation": "cryptsetup is used to create, manage, and access encrypted block devices using LUKS (Linux Unified Key Setup).",
        "reference": "https://gitlab.com/cryptsetup/cryptsetup/-/wikis/DMCrypt",
        "points": 1,
        "answers": [
            {"text": "encrypt", "is_correct": False},
            {"text": "cryptsetup", "is_correct": True},
            {"text": "luks", "is_correct": False},
            {"text": "openssl", "is_correct": False},
        ],
    },
    {
        "text": "What is the default port for HTTPS traffic?",
        "explanation": "HTTPS (HTTP over SSL/TLS) uses port 443 by default for secure web traffic.",
        "reference": "https://tools.ietf.org/html/rfc2818",
        "points": 1,
        "answers": [
            {"text": "80", "is_correct": False},
            {"text": "443", "is_correct": True},
            {"text": "8080", "is_correct": False},
            {"text": "22", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for backup and synchronization in Linux?",
        "explanation": "rsync is a versatile tool for efficient file transfer and synchronization, commonly used for backups and mirroring data.",
        "reference": "https://rsync.samba.org/documentation.html",
        "points": 1,
        "answers": [
            {"text": "cp", "is_correct": False},
            {"text": "rsync", "is_correct": True},
            {"text": "scp", "is_correct": False},
            {"text": "mv", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Terraform in infrastructure management?",
        "explanation": "Terraform is an Infrastructure as Code tool that allows you to define and provision infrastructure resources using declarative configuration files.",
        "reference": "https://www.terraform.io/docs/index.html",
        "points": 1,
        "answers": [
            {"text": "Container orchestration", "is_correct": False},
            {"text": "Infrastructure as Code", "is_correct": True},
            {"text": "Database management", "is_correct": False},
            {"text": "Web server hosting", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to manage Git repositories from the command line?",
        "explanation": "git is the command-line interface for the Git version control system, used for managing source code repositories.",
        "reference": "https://git-scm.com/docs",
        "points": 1,
        "answers": [
            {"text": "svn", "is_correct": False},
            {"text": "git", "is_correct": True},
            {"text": "cvs", "is_correct": False},
            {"text": "mercurial", "is_correct": False},
        ],
    },
    {
        "text": "What is the default configuration directory for Nginx?",
        "explanation": "Nginx configuration files are typically stored in /etc/nginx/ directory, with the main configuration file being nginx.conf.",
        "reference": "https://nginx.org/en/docs/beginners_guide.html",
        "points": 1,
        "answers": [
            {"text": "/etc/apache2/", "is_correct": False},
            {"text": "/etc/nginx/", "is_correct": True},
            {"text": "/var/www/", "is_correct": False},
            {"text": "/usr/share/nginx/", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for managing MySQL/MariaDB databases from the command line?",
        "explanation": "mysql is the command-line client for connecting to and managing MySQL/MariaDB database servers.",
        "reference": "https://dev.mysql.com/doc/refman/8.0/en/mysql.html",
        "points": 1,
        "answers": [
            {"text": "psql", "is_correct": False},
            {"text": "mysql", "is_correct": True},
            {"text": "sqlite3", "is_correct": False},
            {"text": "mongo", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Jenkins in DevOps workflows?",
        "explanation": "Jenkins is an automation server that facilitates Continuous Integration and Continuous Deployment (CI/CD) pipelines.",
        "reference": "https://www.jenkins.io/doc/",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "CI/CD automation", "is_correct": True},
            {"text": "Network monitoring", "is_correct": False},
            {"text": "File encryption", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to manage PostgreSQL databases?",
        "explanation": "psql is the interactive terminal for PostgreSQL, allowing database administration and query execution.",
        "reference": "https://www.postgresql.org/docs/current/app-psql.html",
        "points": 1,
        "answers": [
            {"text": "mysql", "is_correct": False},
            {"text": "psql", "is_correct": True},
            {"text": "sqlite3", "is_correct": False},
            {"text": "mongo", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Redis in application architecture?",
        "explanation": "Redis is an in-memory data structure store used as a database, cache, and message broker for high-performance applications.",
        "reference": "https://redis.io/documentation",
        "points": 1,
        "answers": [
            {"text": "Web server", "is_correct": False},
            {"text": "In-memory data store and cache", "is_correct": True},
            {"text": "Operating system", "is_correct": False},
            {"text": "Text editor", "is_correct": False},
        ],
    },
    {
        "text": "Which protocol is commonly used for secure file transfer?",
        "explanation": "SFTP (SSH File Transfer Protocol) provides secure file transfer capabilities over an encrypted SSH connection.",
        "reference": "https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02",
        "points": 1,
        "answers": [
            {"text": "FTP", "is_correct": False},
            {"text": "SFTP", "is_correct": True},
            {"text": "HTTP", "is_correct": False},
            {"text": "Telnet", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of crontab in Linux systems?",
        "explanation": "crontab is used to schedule and automate recurring tasks (cron jobs) in Linux systems.",
        "reference": "https://man7.org/linux/man-pages/man5/crontab.5.html",
        "points": 1,
        "answers": [
            {"text": "Network configuration", "is_correct": False},
            {"text": "Task scheduling and automation", "is_correct": True},
            {"text": "User management", "is_correct": False},
            {"text": "File compression", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to monitor system performance in real-time?",
        "explanation": "top displays running processes and system resource usage in real-time, showing CPU, memory, and process information.",
        "reference": "https://man7.org/linux/man-pages/man1/top.1.html",
        "points": 1,
        "answers": [
            {"text": "ps", "is_correct": False},
            {"text": "top", "is_correct": True},
            {"text": "ls", "is_correct": False},
            {"text": "df", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of tmux in Linux environments?",
        "explanation": "tmux is a terminal multiplexer that allows multiple terminal sessions to be accessed simultaneously from a single screen.",
        "reference": "https://github.com/tmux/tmux/wiki",
        "points": 1,
        "answers": [
            {"text": "Text editing", "is_correct": False},
            {"text": "Terminal multiplexing", "is_correct": True},
            {"text": "File compression", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for network packet analysis?",
        "explanation": "Wireshark is a comprehensive network protocol analyzer that captures and displays network packets for troubleshooting and analysis.",
        "reference": "https://www.wireshark.org/docs/",
        "points": 1,
        "answers": [
            {"text": "netstat", "is_correct": False},
            {"text": "Wireshark", "is_correct": True},
            {"text": "ping", "is_correct": False},
            {"text": "traceroute", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Zabbix in infrastructure monitoring?",
        "explanation": "Zabbix is an enterprise-class monitoring solution for networks, servers, applications, and services.",
        "reference": "https://www.zabbix.com/documentation/current/",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "Infrastructure monitoring", "is_correct": True},
            {"text": "Web development", "is_correct": False},
            {"text": "File backup", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to manage disk partitions in Linux?",
        "explanation": "fdisk is a command-line utility for managing disk partitions, allowing creation, deletion, and modification of partition tables.",
        "reference": "https://man7.org/linux/man-pages/man8/fdisk.8.html",
        "points": 1,
        "answers": [
            {"text": "mount", "is_correct": False},
            {"text": "fdisk", "is_correct": True},
            {"text": "df", "is_correct": False},
            {"text": "du", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Grafana in monitoring solutions?",
        "explanation": "Grafana is a data visualization and monitoring platform that creates dashboards and graphs from various data sources.",
        "reference": "https://grafana.com/docs/",
        "points": 1,
        "answers": [
            {"text": "Database storage", "is_correct": False},
            {"text": "Data visualization and dashboards", "is_correct": True},
            {"text": "Web hosting", "is_correct": False},
            {"text": "File encryption", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for configuration management with Python?",
        "explanation": "SaltStack (Salt) is a Python-based configuration management and remote execution tool for infrastructure automation.",
        "reference": "https://docs.saltproject.io/en/latest/",
        "points": 1,
        "answers": [
            {"text": "Chef", "is_correct": False},
            {"text": "SaltStack", "is_correct": True},
            {"text": "Puppet", "is_correct": False},
            {"text": "Terraform", "is_correct": False},
        ],
    },
    {
        "text": "What is the default port for SSH connections?",
        "explanation": "SSH (Secure Shell) uses port 22 by default for secure remote access and command execution.",
        "reference": "https://tools.ietf.org/html/rfc4251",
        "points": 1,
        "answers": [
            {"text": "21", "is_correct": False},
            {"text": "22", "is_correct": True},
            {"text": "23", "is_correct": False},
            {"text": "80", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to check network connectivity?",
        "explanation": "ping sends ICMP echo request packets to test network connectivity and measure round-trip time to a destination.",
        "reference": "https://man7.org/linux/man-pages/man8/ping.8.html",
        "points": 1,
        "answers": [
            {"text": "telnet", "is_correct": False},
            {"text": "ping", "is_correct": True},
            {"text": "ssh", "is_correct": False},
            {"text": "curl", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Elasticsearch in the ELK stack?",
        "explanation": "Elasticsearch is a distributed search and analytics engine that stores, searches, and analyzes large volumes of data in real-time.",
        "reference": "https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-intro.html",
        "points": 1,
        "answers": [
            {"text": "Log shipping", "is_correct": False},
            {"text": "Search and analytics engine", "is_correct": True},
            {"text": "Data visualization", "is_correct": False},
            {"text": "Web server", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for container image management with Kubernetes?",
        "explanation": "kubectl is the command-line tool for interacting with Kubernetes clusters and managing containerized applications.",
        "reference": "https://kubernetes.io/docs/reference/kubectl/",
        "points": 1,
        "answers": [
            {"text": "docker", "is_correct": False},
            {"text": "kubectl", "is_correct": True},
            {"text": "podman", "is_correct": False},
            {"text": "containerd", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Consul in service discovery?",
        "explanation": "Consul provides service discovery, health checking, and distributed key-value storage for microservices architectures.",
        "reference": "https://www.consul.io/docs",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "Service discovery and health checking", "is_correct": True},
            {"text": "Web development", "is_correct": False},
            {"text": "File backup", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to manage system logs with journalctl?",
        "explanation": "journalctl is used to query and display logs from the systemd journal, providing centralized log management.",
        "reference": "https://www.freedesktop.org/software/systemd/man/journalctl.html",
        "points": 1,
        "answers": [
            {"text": "tail", "is_correct": False},
            {"text": "journalctl", "is_correct": True},
            {"text": "syslog", "is_correct": False},
            {"text": "dmesg", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Vault in security management?",
        "explanation": "HashiCorp Vault securely stores and manages secrets, passwords, certificates, and encryption keys.",
        "reference": "https://www.vaultproject.io/docs",
        "points": 1,
        "answers": [
            {"text": "Database storage", "is_correct": False},
            {"text": "Secret and key management", "is_correct": True},
            {"text": "Web hosting", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for infrastructure provisioning with code?",
        "explanation": "Terraform allows infrastructure to be defined, provisioned, and managed using declarative configuration files (Infrastructure as Code).",
        "reference": "https://www.terraform.io/docs/index.html",
        "points": 1,
        "answers": [
            {"text": "Ansible", "is_correct": False},
            {"text": "Terraform", "is_correct": True},
            {"text": "Chef", "is_correct": False},
            {"text": "Puppet", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Istio in microservices architecture?",
        "explanation": "Istio is a service mesh that provides traffic management, security, and observability for microservices communications.",
        "reference": "https://istio.io/latest/docs/",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "Service mesh for microservices", "is_correct": True},
            {"text": "Web development", "is_correct": False},
            {"text": "File storage", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to manage user accounts and groups?",
        "explanation": "useradd, usermod, userdel are commands for user management, while groupadd, groupmod, groupdel manage groups.",
        "reference": "https://man7.org/linux/man-pages/man8/useradd.8.html",
        "points": 1,
        "answers": [
            {"text": "passwd", "is_correct": False},
            {"text": "useradd", "is_correct": True},
            {"text": "su", "is_correct": False},
            {"text": "sudo", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Helm in Kubernetes deployments?",
        "explanation": "Helm is a package manager for Kubernetes that simplifies deployment and management of applications using charts.",
        "reference": "https://helm.sh/docs/",
        "points": 1,
        "answers": [
            {"text": "Container runtime", "is_correct": False},
            {"text": "Kubernetes package manager", "is_correct": True},
            {"text": "Database management", "is_correct": False},
            {"text": "Network configuration", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for automated testing in CI/CD pipelines?",
        "explanation": "pytest, JUnit, and other testing frameworks are integrated into CI/CD pipelines for automated testing of applications.",
        "reference": "https://docs.pytest.org/en/stable/",
        "points": 1,
        "answers": [
            {"text": "Git", "is_correct": False},
            {"text": "pytest", "is_correct": True},
            {"text": "Docker", "is_correct": False},
            {"text": "Ansible", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of FluentD in log management?",
        "explanation": "FluentD is an open-source data collector that unifies log collection and consumption for better data processing and analysis.",
        "reference": "https://docs.fluentd.org/",
        "points": 1,
        "answers": [
            {"text": "Database storage", "is_correct": False},
            {"text": "Log collection and forwarding", "is_correct": True},
            {"text": "Web hosting", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to manage file permissions in Linux?",
        "explanation": "chmod (change mode) is used to modify file and directory permissions in Linux systems.",
        "reference": "https://man7.org/linux/man-pages/man1/chmod.1.html",
        "points": 1,
        "answers": [
            {"text": "chown", "is_correct": False},
            {"text": "chmod", "is_correct": True},
            {"text": "chgrp", "is_correct": False},
            {"text": "umask", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Envoy Proxy in modern architectures?",
        "explanation": "Envoy is a high-performance proxy designed for cloud-native applications, providing load balancing, observability, and security features.",
        "reference": "https://www.envoyproxy.io/docs/",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "High-performance proxy and load balancer", "is_correct": True},
            {"text": "Web development", "is_correct": False},
            {"text": "File storage", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is commonly used for secrets management in Kubernetes?",
        "explanation": "Kubernetes Secrets and external tools like Vault, Sealed Secrets, or External Secrets Operator are used for managing sensitive data.",
        "reference": "https://kubernetes.io/docs/concepts/configuration/secret/",
        "points": 1,
        "answers": [
            {"text": "ConfigMap", "is_correct": False},
            {"text": "Kubernetes Secrets", "is_correct": True},
            {"text": "Deployment", "is_correct": False},
            {"text": "Service", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of NGINX Ingress Controller in Kubernetes?",
        "explanation": "NGINX Ingress Controller manages external access to services in a Kubernetes cluster, providing HTTP and HTTPS routing.",
        "reference": "https://kubernetes.github.io/ingress-nginx/",
        "points": 1,
        "answers": [
            {"text": "Pod management", "is_correct": False},
            {"text": "External traffic routing", "is_correct": True},
            {"text": "Storage management", "is_correct": False},
            {"text": "Network policies", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create and manage virtual environments in Python?",
        "explanation": "python -m venv creates virtual environments for Python projects, allowing isolated package installations.",
        "reference": "https://docs.python.org/3/library/venv.html",
        "points": 1,
        "answers": [
            {"text": "pip", "is_correct": False},
            {"text": "python -m venv", "is_correct": True},
            {"text": "conda", "is_correct": False},
            {"text": "virtualenv", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Traefik in container orchestration?",
        "explanation": "Traefik is a modern reverse proxy and load balancer that automatically discovers services and configures itself dynamically.",
        "reference": "https://doc.traefik.io/traefik/",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "Dynamic reverse proxy and load balancer", "is_correct": True},
            {"text": "Container runtime", "is_correct": False},
            {"text": "Image registry", "is_correct": False},
        ],
    },
]
