"""Linux Foundation Certified System Administrator (LFCS)"""

CERTIFICATION = {
    "name": "Linux Foundation Certified System Administrator (LFCS)",
    "description": "Performance-based Linux system administration certification",
    "slug": "lfcs",
    "level": "Professional",
    "duration": 162,
    "questions_count": 54,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which command is used to create a logical volume in LVM?",
        "explanation": "The lvcreate command is used to create logical volumes within a volume group in Linux Logical Volume Management (LVM).",
        "reference": "https://training.linuxfoundation.org/certification/linux-foundation-certified-sysadmin-lfcs/",
        "points": 1,
        "answers": [
            {"text": "lvextend", "is_correct": False},
            {"text": "lvcreate", "is_correct": True},
            {"text": "vgcreate", "is_correct": False},
            {"text": "pvcreate", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary purpose of the /etc/fstab file?",
        "explanation": "/etc/fstab contains information about filesystems and their mount points, used for automatic mounting at boot time.",
        "reference": "https://man7.org/linux/man-pages/man5/fstab.5.html",
        "points": 1,
        "answers": [
            {"text": "Store user passwords", "is_correct": False},
            {"text": "Configure filesystem mounts", "is_correct": True},
            {"text": "Define network interfaces", "is_correct": False},
            {"text": "Manage system services", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays real-time process information?",
        "explanation": "The top command displays real-time information about running processes, including CPU and memory usage.",
        "reference": "https://man7.org/linux/man-pages/man1/top.1.html",
        "points": 1,
        "answers": [
            {"text": "ps", "is_correct": False},
            {"text": "top", "is_correct": True},
            {"text": "pstree", "is_correct": False},
            {"text": "jobs", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to change file permissions using symbolic notation?",
        "explanation": "The chmod command can use symbolic notation (like chmod u+x file) to change file permissions for user, group, and others.",
        "reference": "https://man7.org/linux/man-pages/man1/chmod.1.html",
        "points": 1,
        "answers": [
            {"text": "chown", "is_correct": False},
            {"text": "chmod", "is_correct": True},
            {"text": "chgrp", "is_correct": False},
            {"text": "umask", "is_correct": False},
        ],
    },
    {
        "text": "Which systemctl command enables a service to start automatically at boot?",
        "explanation": "The 'systemctl enable' command creates symbolic links to enable a service to start automatically during the boot process.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemctl.html",
        "points": 1,
        "answers": [
            {"text": "systemctl start", "is_correct": False},
            {"text": "systemctl enable", "is_correct": True},
            {"text": "systemctl activate", "is_correct": False},
            {"text": "systemctl boot", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the crontab command?",
        "explanation": "The crontab command is used to view, edit, and manage user cron jobs for scheduling tasks to run automatically.",
        "reference": "https://man7.org/linux/man-pages/man1/crontab.1.html",
        "points": 1,
        "answers": [
            {"text": "Manage system processes", "is_correct": False},
            {"text": "Schedule automated tasks", "is_correct": True},
            {"text": "Monitor system logs", "is_correct": False},
            {"text": "Configure network settings", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to view disk usage by directory?",
        "explanation": "The du (disk usage) command displays the amount of disk space used by directories and files.",
        "reference": "https://man7.org/linux/man-pages/man1/du.1.html",
        "points": 1,
        "answers": [
            {"text": "df", "is_correct": False},
            {"text": "du", "is_correct": True},
            {"text": "ls", "is_correct": False},
            {"text": "free", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /etc/passwd file?",
        "explanation": "The /etc/passwd file contains user account information including usernames, UIDs, GIDs, home directories, and default shells.",
        "reference": "https://man7.org/linux/man-pages/man5/passwd.5.html",
        "points": 1,
        "answers": [
            {"text": "Store user passwords", "is_correct": False},
            {"text": "Store user account information", "is_correct": True},
            {"text": "Configure system services", "is_correct": False},
            {"text": "Define network settings", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display running processes?",
        "explanation": "The ps command displays information about currently running processes on the system.",
        "reference": "https://man7.org/linux/man-pages/man1/ps.1.html",
        "points": 1,
        "answers": [
            {"text": "top", "is_correct": False},
            {"text": "ps", "is_correct": True},
            {"text": "jobs", "is_correct": False},
            {"text": "who", "is_correct": False},
        ],
    },
    {
        "text": "What command creates a new user account?",
        "explanation": "The useradd command is used to create new user accounts on Linux systems.",
        "reference": "https://man7.org/linux/man-pages/man8/useradd.8.html",
        "points": 1,
        "answers": [
            {"text": "adduser", "is_correct": False},
            {"text": "useradd", "is_correct": True},
            {"text": "newuser", "is_correct": False},
            {"text": "mkuser", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains system-wide environment variables?",
        "explanation": "The /etc/environment file contains system-wide environment variables that are set for all users.",
        "reference": "https://help.ubuntu.com/community/EnvironmentVariables",
        "points": 1,
        "answers": [
            {"text": "/etc/profile", "is_correct": False},
            {"text": "/etc/environment", "is_correct": True},
            {"text": "/etc/bashrc", "is_correct": False},
            {"text": "/home/.bashrc", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to mount a filesystem?",
        "explanation": "The mount command is used to attach filesystems to the directory tree at specified mount points.",
        "reference": "https://man7.org/linux/man-pages/man8/mount.8.html",
        "points": 1,
        "answers": [
            {"text": "attach", "is_correct": False},
            {"text": "mount", "is_correct": True},
            {"text": "link", "is_correct": False},
            {"text": "connect", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays available disk space?",
        "explanation": "The df (disk free) command shows the amount of available disk space on mounted filesystems.",
        "reference": "https://man7.org/linux/man-pages/man1/df.1.html",
        "points": 1,
        "answers": [
            {"text": "du", "is_correct": False},
            {"text": "df", "is_correct": True},
            {"text": "free", "is_correct": False},
            {"text": "space", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the grep command?",
        "explanation": "The grep command searches for patterns in text files and displays lines that match the specified pattern.",
        "reference": "https://man7.org/linux/man-pages/man1/grep.1.html",
        "points": 1,
        "answers": [
            {"text": "Copy files", "is_correct": False},
            {"text": "Search text patterns", "is_correct": True},
            {"text": "Change permissions", "is_correct": False},
            {"text": "List directories", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change file ownership?",
        "explanation": "The chown command changes the owner and group ownership of files and directories.",
        "reference": "https://man7.org/linux/man-pages/man1/chown.1.html",
        "points": 1,
        "answers": [
            {"text": "chmod", "is_correct": False},
            {"text": "chown", "is_correct": True},
            {"text": "chgrp", "is_correct": False},
            {"text": "own", "is_correct": False},
        ],
    },
    {
        "text": "What command displays memory usage information?",
        "explanation": "The free command displays information about system memory usage including total, used, and available memory.",
        "reference": "https://man7.org/linux/man-pages/man1/free.1.html",
        "points": 1,
        "answers": [
            {"text": "mem", "is_correct": False},
            {"text": "free", "is_correct": True},
            {"text": "memory", "is_correct": False},
            {"text": "ram", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains network interface configuration in Red Hat systems?",
        "explanation": "In Red Hat-based systems, network interface configurations are stored in files under /etc/sysconfig/network-scripts/.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-configuring_network_interfaces",
        "points": 1,
        "answers": [
            {"text": "/etc/network/interfaces", "is_correct": False},
            {"text": "/etc/sysconfig/network-scripts/ifcfg-*", "is_correct": True},
            {"text": "/etc/netplan/", "is_correct": False},
            {"text": "/etc/networking/", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to view system log files?",
        "explanation": "The journalctl command is used to view logs from the systemd journal, while traditional log files can be viewed with less, tail, or cat.",
        "reference": "https://www.freedesktop.org/software/systemd/man/journalctl.html",
        "points": 1,
        "answers": [
            {"text": "logview", "is_correct": False},
            {"text": "journalctl", "is_correct": True},
            {"text": "syslog", "is_correct": False},
            {"text": "viewlog", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates a compressed archive?",
        "explanation": "The tar command with the -z option creates gzipped compressed archives, commonly used for backup and file distribution.",
        "reference": "https://man7.org/linux/man-pages/man1/tar.1.html",
        "points": 1,
        "answers": [
            {"text": "zip", "is_correct": False},
            {"text": "tar -czf", "is_correct": True},
            {"text": "compress", "is_correct": False},
            {"text": "archive", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the sudo command?",
        "explanation": "The sudo command allows users to execute commands with the privileges of another user, typically root, for administrative tasks.",
        "reference": "https://man7.org/linux/man-pages/man8/sudo.8.html",
        "points": 1,
        "answers": [
            {"text": "Switch user identity", "is_correct": False},
            {"text": "Execute commands as another user", "is_correct": True},
            {"text": "Change passwords", "is_correct": False},
            {"text": "List users", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to find files by name?",
        "explanation": "The find command searches for files and directories based on various criteria including name, size, permissions, and modification time.",
        "reference": "https://man7.org/linux/man-pages/man1/find.1.html",
        "points": 1,
        "answers": [
            {"text": "locate", "is_correct": False},
            {"text": "find", "is_correct": True},
            {"text": "search", "is_correct": False},
            {"text": "which", "is_correct": False},
        ],
    },
    {
        "text": "What command displays network connections and listening ports?",
        "explanation": "The netstat command displays network connections, routing tables, and network statistics including listening ports.",
        "reference": "https://man7.org/linux/man-pages/man8/netstat.8.html",
        "points": 1,
        "answers": [
            {"text": "network", "is_correct": False},
            {"text": "netstat", "is_correct": True},
            {"text": "ifconfig", "is_correct": False},
            {"text": "ping", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains DNS server configuration?",
        "explanation": "The /etc/resolv.conf file contains DNS resolver configuration including nameserver entries for domain name resolution.",
        "reference": "https://man7.org/linux/man-pages/man5/resolv.conf.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/hosts", "is_correct": False},
            {"text": "/etc/resolv.conf", "is_correct": True},
            {"text": "/etc/dns.conf", "is_correct": False},
            {"text": "/etc/nameserver", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to kill a process by PID?",
        "explanation": "The kill command terminates processes by sending signals to them, typically using the process ID (PID).",
        "reference": "https://man7.org/linux/man-pages/man1/kill.1.html",
        "points": 1,
        "answers": [
            {"text": "stop", "is_correct": False},
            {"text": "kill", "is_correct": True},
            {"text": "terminate", "is_correct": False},
            {"text": "end", "is_correct": False},
        ],
    },
    {
        "text": "Which command copies files and directories?",
        "explanation": "The cp command copies files and directories from one location to another, with options for recursive copying and preserving attributes.",
        "reference": "https://man7.org/linux/man-pages/man1/cp.1.html",
        "points": 1,
        "answers": [
            {"text": "copy", "is_correct": False},
            {"text": "cp", "is_correct": True},
            {"text": "mv", "is_correct": False},
            {"text": "duplicate", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /var/log directory?",
        "explanation": "The /var/log directory contains system log files that record system events, errors, and other important information for troubleshooting.",
        "reference": "https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html",
        "points": 1,
        "answers": [
            {"text": "Store user data", "is_correct": False},
            {"text": "Store system log files", "is_correct": True},
            {"text": "Store configuration files", "is_correct": False},
            {"text": "Store temporary files", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to view the end of a file?",
        "explanation": "The tail command displays the last few lines of a file, useful for monitoring log files and recent changes.",
        "reference": "https://man7.org/linux/man-pages/man1/tail.1.html",
        "points": 1,
        "answers": [
            {"text": "head", "is_correct": False},
            {"text": "tail", "is_correct": True},
            {"text": "end", "is_correct": False},
            {"text": "last", "is_correct": False},
        ],
    },
    {
        "text": "What command creates a symbolic link?",
        "explanation": "The ln command with the -s option creates symbolic links (symlinks) that point to other files or directories.",
        "reference": "https://man7.org/linux/man-pages/man1/ln.1.html",
        "points": 1,
        "answers": [
            {"text": "link", "is_correct": False},
            {"text": "ln -s", "is_correct": True},
            {"text": "symlink", "is_correct": False},
            {"text": "mklink", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays currently logged-in users?",
        "explanation": "The who command shows information about users currently logged into the system.",
        "reference": "https://man7.org/linux/man-pages/man1/who.1.html",
        "points": 1,
        "answers": [
            {"text": "users", "is_correct": False},
            {"text": "who", "is_correct": True},
            {"text": "logged", "is_correct": False},
            {"text": "active", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /etc/hosts file?",
        "explanation": "The /etc/hosts file contains static hostname-to-IP address mappings used for local name resolution before DNS queries.",
        "reference": "https://man7.org/linux/man-pages/man5/hosts.5.html",
        "points": 1,
        "answers": [
            {"text": "Store user passwords", "is_correct": False},
            {"text": "Map hostnames to IP addresses", "is_correct": True},
            {"text": "Configure network interfaces", "is_correct": False},
            {"text": "Define system services", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change user password?",
        "explanation": "The passwd command is used to change user passwords, including the current user's password or other users' passwords (with appropriate privileges).",
        "reference": "https://man7.org/linux/man-pages/man1/passwd.1.html",
        "points": 1,
        "answers": [
            {"text": "password", "is_correct": False},
            {"text": "passwd", "is_correct": True},
            {"text": "chpasswd", "is_correct": False},
            {"text": "setpass", "is_correct": False},
        ],
    },
    {
        "text": "What command displays system uptime and load average?",
        "explanation": "The uptime command shows how long the system has been running and the current load average.",
        "reference": "https://man7.org/linux/man-pages/man1/uptime.1.html",
        "points": 1,
        "answers": [
            {"text": "load", "is_correct": False},
            {"text": "uptime", "is_correct": True},
            {"text": "runtime", "is_correct": False},
            {"text": "system", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to view and edit cron jobs?",
        "explanation": "The crontab -e command opens the user's cron table for editing, allowing scheduling of automated tasks.",
        "reference": "https://man7.org/linux/man-pages/man1/crontab.1.html",
        "points": 1,
        "answers": [
            {"text": "cron -e", "is_correct": False},
            {"text": "crontab -e", "is_correct": True},
            {"text": "cronjob -e", "is_correct": False},
            {"text": "schedule -e", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /tmp directory?",
        "explanation": "The /tmp directory is used for storing temporary files that are typically deleted upon system reboot.",
        "reference": "https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s18.html",
        "points": 1,
        "answers": [
            {"text": "Store user home directories", "is_correct": False},
            {"text": "Store temporary files", "is_correct": True},
            {"text": "Store system configuration", "is_correct": False},
            {"text": "Store log files", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to compress files with gzip?",
        "explanation": "The gzip command compresses files using the gzip compression algorithm, creating .gz files.",
        "reference": "https://man7.org/linux/man-pages/man1/gzip.1.html",
        "points": 1,
        "answers": [
            {"text": "compress", "is_correct": False},
            {"text": "gzip", "is_correct": True},
            {"text": "zip", "is_correct": False},
            {"text": "tar", "is_correct": False},
        ],
    },
    {
        "text": "What command displays the current working directory?",
        "explanation": "The pwd (print working directory) command displays the full path of the current directory.",
        "reference": "https://man7.org/linux/man-pages/man1/pwd.1.html",
        "points": 1,
        "answers": [
            {"text": "dir", "is_correct": False},
            {"text": "pwd", "is_correct": True},
            {"text": "cwd", "is_correct": False},
            {"text": "path", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains group information?",
        "explanation": "The /etc/group file contains group account information including group names, GIDs, and group members.",
        "reference": "https://man7.org/linux/man-pages/man5/group.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/passwd", "is_correct": False},
            {"text": "/etc/group", "is_correct": True},
            {"text": "/etc/shadow", "is_correct": False},
            {"text": "/etc/users", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to change to a directory?",
        "explanation": "The cd (change directory) command is used to navigate between directories in the filesystem.",
        "reference": "https://man7.org/linux/man-pages/man1/cd.1p.html",
        "points": 1,
        "answers": [
            {"text": "goto", "is_correct": False},
            {"text": "cd", "is_correct": True},
            {"text": "chdir", "is_correct": False},
            {"text": "move", "is_correct": False},
        ],
    },
    {
        "text": "Which command shows system hardware information?",
        "explanation": "The lshw command displays detailed hardware information about the system including CPU, memory, and devices.",
        "reference": "https://linux.die.net/man/1/lshw",
        "points": 1,
        "answers": [
            {"text": "hardware", "is_correct": False},
            {"text": "lshw", "is_correct": True},
            {"text": "hwinfo", "is_correct": False},
            {"text": "sysinfo", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the su command?",
        "explanation": "The su (substitute user) command is used to switch to another user account, typically to gain root privileges.",
        "reference": "https://man7.org/linux/man-pages/man1/su.1.html",
        "points": 1,
        "answers": [
            {"text": "Show users", "is_correct": False},
            {"text": "Switch user", "is_correct": True},
            {"text": "System update", "is_correct": False},
            {"text": "Super user", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays file and directory listing?",
        "explanation": "The ls command lists files and directories in the current or specified directory with various formatting options.",
        "reference": "https://man7.org/linux/man-pages/man1/ls.1.html",
        "points": 1,
        "answers": [
            {"text": "list", "is_correct": False},
            {"text": "ls", "is_correct": True},
            {"text": "dir", "is_correct": False},
            {"text": "show", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to remove files?",
        "explanation": "The rm command removes (deletes) files and directories from the filesystem.",
        "reference": "https://man7.org/linux/man-pages/man1/rm.1.html",
        "points": 1,
        "answers": [
            {"text": "delete", "is_correct": False},
            {"text": "rm", "is_correct": True},
            {"text": "remove", "is_correct": False},
            {"text": "del", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates a directory?",
        "explanation": "The mkdir (make directory) command creates new directories in the filesystem.",
        "reference": "https://man7.org/linux/man-pages/man1/mkdir.1.html",
        "points": 1,
        "answers": [
            {"text": "makedir", "is_correct": False},
            {"text": "mkdir", "is_correct": True},
            {"text": "createdir", "is_correct": False},
            {"text": "newdir", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the history command?",
        "explanation": "The history command displays a list of previously executed commands from the command history.",
        "reference": "https://man7.org/linux/man-pages/man3/history.3.html",
        "points": 1,
        "answers": [
            {"text": "Show system history", "is_correct": False},
            {"text": "Show command history", "is_correct": True},
            {"text": "Show login history", "is_correct": False},
            {"text": "Show file history", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays the first few lines of a file?",
        "explanation": "The head command displays the first few lines (default 10) of a file, useful for previewing file contents.",
        "reference": "https://man7.org/linux/man-pages/man1/head.1.html",
        "points": 1,
        "answers": [
            {"text": "top", "is_correct": False},
            {"text": "head", "is_correct": True},
            {"text": "first", "is_correct": False},
            {"text": "begin", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to move or rename files?",
        "explanation": "The mv (move) command is used to move files to different locations or rename files and directories.",
        "reference": "https://man7.org/linux/man-pages/man1/mv.1.html",
        "points": 1,
        "answers": [
            {"text": "move", "is_correct": False},
            {"text": "mv", "is_correct": True},
            {"text": "rename", "is_correct": False},
            {"text": "rn", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays file content page by page?",
        "explanation": "The less command displays file content one page at a time, allowing forward and backward navigation through the file.",
        "reference": "https://man7.org/linux/man-pages/man1/less.1.html",
        "points": 1,
        "answers": [
            {"text": "more", "is_correct": False},
            {"text": "less", "is_correct": True},
            {"text": "page", "is_correct": False},
            {"text": "view", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the which command?",
        "explanation": "The which command locates the path of executable programs in the system PATH.",
        "reference": "https://man7.org/linux/man-pages/man1/which.1.html",
        "points": 1,
        "answers": [
            {"text": "Find files", "is_correct": False},
            {"text": "Locate executable path", "is_correct": True},
            {"text": "Show file type", "is_correct": False},
            {"text": "Display file info", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays system kernel information?",
        "explanation": "The uname command displays system information including kernel name, version, and architecture.",
        "reference": "https://man7.org/linux/man-pages/man1/uname.1.html",
        "points": 1,
        "answers": [
            {"text": "kernel", "is_correct": False},
            {"text": "uname", "is_correct": True},
            {"text": "sysinfo", "is_correct": False},
            {"text": "version", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to display file contents?",
        "explanation": "The cat command displays the entire contents of one or more files to the terminal.",
        "reference": "https://man7.org/linux/man-pages/man1/cat.1.html",
        "points": 1,
        "answers": [
            {"text": "show", "is_correct": False},
            {"text": "cat", "is_correct": True},
            {"text": "display", "is_correct": False},
            {"text": "print", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to check filesystem integrity?",
        "explanation": "The fsck (filesystem check) command checks and repairs filesystem inconsistencies and errors.",
        "reference": "https://man7.org/linux/man-pages/man8/fsck.8.html",
        "points": 1,
        "answers": [
            {"text": "checkfs", "is_correct": False},
            {"text": "fsck", "is_correct": True},
            {"text": "scandisk", "is_correct": False},
            {"text": "verify", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the alias command?",
        "explanation": "The alias command creates shortcuts for longer commands, allowing users to define custom command abbreviations.",
        "reference": "https://man7.org/linux/man-pages/man1/alias.1p.html",
        "points": 1,
        "answers": [
            {"text": "Create user accounts", "is_correct": False},
            {"text": "Create command shortcuts", "is_correct": True},
            {"text": "Link files", "is_correct": False},
            {"text": "Rename commands", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays currently running services?",
        "explanation": "The systemctl list-units command displays currently running systemd services and their status.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemctl.html",
        "points": 1,
        "answers": [
            {"text": "service --status-all", "is_correct": False},
            {"text": "systemctl list-units", "is_correct": True},
            {"text": "ps aux", "is_correct": False},
            {"text": "jobs", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to synchronize files between locations?",
        "explanation": "The rsync command efficiently synchronizes files and directories between different locations, local or remote.",
        "reference": "https://man7.org/linux/man-pages/man1/rsync.1.html",
        "points": 1,
        "answers": [
            {"text": "sync", "is_correct": False},
            {"text": "rsync", "is_correct": True},
            {"text": "copy", "is_correct": False},
            {"text": "mirror", "is_correct": False},
        ],
    },
]
