"""Linux Professional Institute Certification Level 2 (LPIC-2)"""

CERTIFICATION = {
    "name": "Linux Professional Institute Certification Level 2 (LPIC-2)",
    "description": "Advanced Linux professional skills and knowledge",
    "slug": "lpic-2",
    "level": "Professional",
    "duration": 159,
    "questions_count": 53,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which command is used to configure kernel modules to load automatically at boot time?",
        "explanation": "The /etc/modules-load.d/ directory contains configuration files that specify kernel modules to load at boot time. Files should have .conf extension.",
        "reference": "https://www.lpi.org/our-certifications/lpic-2-overview",
        "points": 1,
        "answers": [
            {"text": "modprobe", "is_correct": False},
            {"text": "insmod", "is_correct": False},
            {"text": "/etc/modules-load.d/*.conf", "is_correct": True},
            {"text": "/etc/modprobe.conf", "is_correct": False},
        ],
    },
    {
        "text": "What is the default log level for the Linux kernel?",
        "explanation": "The default kernel log level is 4 (KERN_WARNING), which means messages with priority 4 and lower (higher priority) are displayed on the console.",
        "reference": "https://www.kernel.org/doc/html/latest/core-api/printk-basics.html",
        "points": 1,
        "answers": [
            {"text": "0", "is_correct": False},
            {"text": "4", "is_correct": True},
            {"text": "7", "is_correct": False},
            {"text": "1", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains the system's current kernel parameters?",
        "explanation": "/proc/cmdline contains the kernel command line parameters that were passed to the kernel at boot time.",
        "reference": "https://www.kernel.org/doc/Documentation/filesystems/proc.txt",
        "points": 1,
        "answers": [
            {"text": "/proc/version", "is_correct": False},
            {"text": "/proc/cmdline", "is_correct": True},
            {"text": "/proc/cpuinfo", "is_correct": False},
            {"text": "/proc/meminfo", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to display and configure network interface parameters?",
        "explanation": "The ip command is the modern replacement for ifconfig and is used to display and configure network interfaces, routing, and tunnels.",
        "reference": "https://man7.org/linux/man-pages/man8/ip.8.html",
        "points": 1,
        "answers": [
            {"text": "ifconfig", "is_correct": False},
            {"text": "ip", "is_correct": True},
            {"text": "netstat", "is_correct": False},
            {"text": "route", "is_correct": False},
        ],
    },
    {
        "text": "Which directory contains systemd unit files for system services?",
        "explanation": "/lib/systemd/system/ contains the default systemd unit files installed by packages, while /etc/systemd/system/ contains local customizations.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemd.unit.html",
        "points": 1,
        "answers": [
            {"text": "/etc/systemd/", "is_correct": False},
            {"text": "/lib/systemd/system/", "is_correct": True},
            {"text": "/usr/systemd/", "is_correct": False},
            {"text": "/var/systemd/", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to compile a new kernel from source?",
        "explanation": "The make command is used to compile the Linux kernel from source code after configuration with make menuconfig or similar tools.",
        "reference": "https://www.kernel.org/doc/html/latest/admin-guide/README.html",
        "points": 1,
        "answers": [
            {"text": "gcc", "is_correct": False},
            {"text": "make", "is_correct": True},
            {"text": "compile", "is_correct": False},
            {"text": "build", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the initramfs in Linux boot process?",
        "explanation": "initramfs is an initial RAM filesystem that contains essential drivers and tools needed to mount the real root filesystem during boot.",
        "reference": "https://www.kernel.org/doc/html/latest/admin-guide/initrd.html",
        "points": 1,
        "answers": [
            {"text": "Initial bootloader", "is_correct": False},
            {"text": "Initial RAM filesystem", "is_correct": True},
            {"text": "Initial kernel", "is_correct": False},
            {"text": "Initial memory test", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates an initramfs image?",
        "explanation": "mkinitramfs (Debian/Ubuntu) or dracut (Red Hat/CentOS) commands are used to create initramfs images containing necessary drivers and tools.",
        "reference": "https://man7.org/linux/man-pages/man8/mkinitramfs.8.html",
        "points": 1,
        "answers": [
            {"text": "mkimage", "is_correct": False},
            {"text": "mkinitramfs", "is_correct": True},
            {"text": "initfs", "is_correct": False},
            {"text": "ramfs", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of GRUB2 configuration file?",
        "explanation": "The GRUB2 configuration file (/boot/grub/grub.cfg) contains boot menu entries and kernel parameters for system startup.",
        "reference": "https://www.gnu.org/software/grub/manual/grub/grub.html",
        "points": 1,
        "answers": [
            {"text": "Kernel compilation", "is_correct": False},
            {"text": "Boot menu and kernel parameters", "is_correct": True},
            {"text": "System services", "is_correct": False},
            {"text": "Network configuration", "is_correct": False},
        ],
    },
    {
        "text": "Which command updates GRUB2 configuration?",
        "explanation": "update-grub (Debian/Ubuntu) or grub2-mkconfig (Red Hat/CentOS) commands regenerate the GRUB configuration file.",
        "reference": "https://man7.org/linux/man-pages/man8/update-grub.8.html",
        "points": 1,
        "answers": [
            {"text": "grub-install", "is_correct": False},
            {"text": "update-grub", "is_correct": True},
            {"text": "grub-config", "is_correct": False},
            {"text": "grub-update", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of systemd targets?",
        "explanation": "Systemd targets group units together and define system states, similar to runlevels in traditional init systems.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemd.target.html",
        "points": 1,
        "answers": [
            {"text": "Service dependencies", "is_correct": False},
            {"text": "System state grouping", "is_correct": True},
            {"text": "File targets", "is_correct": False},
            {"text": "Network targets", "is_correct": False},
        ],
    },
    {
        "text": "Which command shows the current systemd target?",
        "explanation": "systemctl get-default shows the default target, while systemctl list-units --type=target shows active targets.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemctl.html",
        "points": 1,
        "answers": [
            {"text": "systemctl status", "is_correct": False},
            {"text": "systemctl get-default", "is_correct": True},
            {"text": "systemctl show", "is_correct": False},
            {"text": "systemctl target", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of rsyslog configuration?",
        "explanation": "rsyslog configuration defines how system logs are collected, filtered, and forwarded to various destinations.",
        "reference": "https://www.rsyslog.com/doc/v8-stable/configuration/index.html",
        "points": 1,
        "answers": [
            {"text": "System monitoring", "is_correct": False},
            {"text": "Log collection and forwarding", "is_correct": True},
            {"text": "System backup", "is_correct": False},
            {"text": "Remote access", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains rsyslog configuration?",
        "explanation": "The main rsyslog configuration file is /etc/rsyslog.conf, with additional configuration in /etc/rsyslog.d/.",
        "reference": "https://man7.org/linux/man-pages/man5/rsyslog.conf.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/syslog.conf", "is_correct": False},
            {"text": "/etc/rsyslog.conf", "is_correct": True},
            {"text": "/etc/logging.conf", "is_correct": False},
            {"text": "/var/log/rsyslog.conf", "is_correct": False},
        ],
    },
    {
        "text": "What is log rotation and which tool manages it?",
        "explanation": "Log rotation manages log file sizes by archiving and compressing old logs. The logrotate tool handles this process.",
        "reference": "https://man7.org/linux/man-pages/man8/logrotate.8.html",
        "points": 1,
        "answers": [
            {"text": "Log compression with gzip", "is_correct": False},
            {"text": "Log archiving with logrotate", "is_correct": True},
            {"text": "Log deletion with cron", "is_correct": False},
            {"text": "Log backup with tar", "is_correct": False},
        ],
    },
    {
        "text": "Which command configures network interfaces persistently in systemd-networkd?",
        "explanation": "systemd-networkd uses configuration files in /etc/systemd/network/ with .network extension for persistent network configuration.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemd-networkd.html",
        "points": 1,
        "answers": [
            {"text": "networkctl", "is_correct": False},
            {"text": "/etc/systemd/network/*.network", "is_correct": True},
            {"text": "netplan", "is_correct": False},
            {"text": "ifupdown", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of NetworkManager?",
        "explanation": "NetworkManager provides dynamic network configuration and management, especially useful for laptops and mobile devices.",
        "reference": "https://networkmanager.dev/docs/",
        "points": 1,
        "answers": [
            {"text": "Static network configuration", "is_correct": False},
            {"text": "Dynamic network management", "is_correct": True},
            {"text": "Network monitoring", "is_correct": False},
            {"text": "Network security", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages NetworkManager connections?",
        "explanation": "nmcli (NetworkManager command line interface) is used to configure and manage NetworkManager connections.",
        "reference": "https://man7.org/linux/man-pages/man1/nmcli.1.html",
        "points": 1,
        "answers": [
            {"text": "netctl", "is_correct": False},
            {"text": "nmcli", "is_correct": True},
            {"text": "nmtui", "is_correct": False},
            {"text": "netconfig", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of iptables in Linux?",
        "explanation": "iptables is a user-space utility for configuring the Linux kernel firewall implemented within the Netfilter framework.",
        "reference": "https://man7.org/linux/man-pages/man8/iptables.8.html",
        "points": 1,
        "answers": [
            {"text": "Network routing", "is_correct": False},
            {"text": "Firewall configuration", "is_correct": True},
            {"text": "Network monitoring", "is_correct": False},
            {"text": "Network optimization", "is_correct": False},
        ],
    },
    {
        "text": "Which chain in iptables handles incoming packets?",
        "explanation": "The INPUT chain in iptables handles packets destined for the local system.",
        "reference": "https://man7.org/linux/man-pages/man8/iptables.8.html",
        "points": 1,
        "answers": [
            {"text": "FORWARD", "is_correct": False},
            {"text": "INPUT", "is_correct": True},
            {"text": "OUTPUT", "is_correct": False},
            {"text": "PREROUTING", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of NAT in iptables?",
        "explanation": "NAT (Network Address Translation) in iptables translates private IP addresses to public IP addresses for internet access.",
        "reference": "https://netfilter.org/documentation/HOWTO/NAT-HOWTO.html",
        "points": 1,
        "answers": [
            {"text": "Network monitoring", "is_correct": False},
            {"text": "Address translation", "is_correct": True},
            {"text": "Network routing", "is_correct": False},
            {"text": "Access control", "is_correct": False},
        ],
    },
    {
        "text": "Which command saves iptables rules permanently?",
        "explanation": "iptables-save outputs current rules, which can be redirected to a file or used with iptables-persistent for permanent storage.",
        "reference": "https://man7.org/linux/man-pages/man8/iptables-save.8.html",
        "points": 1,
        "answers": [
            {"text": "iptables-persist", "is_correct": False},
            {"text": "iptables-save", "is_correct": True},
            {"text": "iptables-store", "is_correct": False},
            {"text": "iptables-backup", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Apache Virtual Hosts?",
        "explanation": "Apache Virtual Hosts allow multiple websites to be hosted on a single server using different domain names or IP addresses.",
        "reference": "https://httpd.apache.org/docs/2.4/vhosts/",
        "points": 1,
        "answers": [
            {"text": "Server clustering", "is_correct": False},
            {"text": "Multiple websites on one server", "is_correct": True},
            {"text": "Load balancing", "is_correct": False},
            {"text": "SSL encryption", "is_correct": False},
        ],
    },
    {
        "text": "Which Apache module enables SSL/TLS support?",
        "explanation": "The mod_ssl module provides SSL/TLS encryption capabilities for Apache HTTP Server.",
        "reference": "https://httpd.apache.org/docs/2.4/mod/mod_ssl.html",
        "points": 1,
        "answers": [
            {"text": "mod_https", "is_correct": False},
            {"text": "mod_ssl", "is_correct": True},
            {"text": "mod_tls", "is_correct": False},
            {"text": "mod_secure", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Apache .htaccess files?",
        "explanation": ".htaccess files provide directory-level configuration for Apache, allowing per-directory customization of server behavior.",
        "reference": "https://httpd.apache.org/docs/2.4/howto/htaccess.html",
        "points": 1,
        "answers": [
            {"text": "User authentication only", "is_correct": False},
            {"text": "Directory-level configuration", "is_correct": True},
            {"text": "Global server settings", "is_correct": False},
            {"text": "Log file configuration", "is_correct": False},
        ],
    },
    {
        "text": "Which Nginx directive defines server blocks?",
        "explanation": "The server directive in Nginx defines server blocks (virtual hosts) for handling different domains or configurations.",
        "reference": "https://nginx.org/en/docs/http/ngx_http_core_module.html#server",
        "points": 1,
        "answers": [
            {"text": "location", "is_correct": False},
            {"text": "server", "is_correct": True},
            {"text": "upstream", "is_correct": False},
            {"text": "proxy", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Nginx upstream directive?",
        "explanation": "The upstream directive in Nginx defines a group of backend servers for load balancing and proxy configurations.",
        "reference": "https://nginx.org/en/docs/http/ngx_http_upstream_module.html",
        "points": 1,
        "answers": [
            {"text": "SSL configuration", "is_correct": False},
            {"text": "Backend server grouping", "is_correct": True},
            {"text": "URL rewriting", "is_correct": False},
            {"text": "Access control", "is_correct": False},
        ],
    },
    {
        "text": "Which command tests Nginx configuration syntax?",
        "explanation": "nginx -t tests the Nginx configuration syntax without starting the server, useful for validating changes.",
        "reference": "https://nginx.org/en/docs/switches.html",
        "points": 1,
        "answers": [
            {"text": "nginx -test", "is_correct": False},
            {"text": "nginx -t", "is_correct": True},
            {"text": "nginx -check", "is_correct": False},
            {"text": "nginx -validate", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Squid proxy server?",
        "explanation": "Squid is a caching proxy server that improves web performance by caching frequently requested content and providing access control.",
        "reference": "http://www.squid-cache.org/Doc/",
        "points": 1,
        "answers": [
            {"text": "Web development", "is_correct": False},
            {"text": "Caching proxy and access control", "is_correct": True},
            {"text": "Database proxy", "is_correct": False},
            {"text": "Mail proxy", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains Squid configuration?",
        "explanation": "The main Squid configuration file is /etc/squid/squid.conf (or /etc/squid3/squid.conf on some systems).",
        "reference": "http://www.squid-cache.org/Doc/config/",
        "points": 1,
        "answers": [
            {"text": "/etc/squid.conf", "is_correct": False},
            {"text": "/etc/squid/squid.conf", "is_correct": True},
            {"text": "/etc/proxy.conf", "is_correct": False},
            {"text": "/var/squid/config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of DNS BIND server?",
        "explanation": "BIND (Berkeley Internet Name Domain) is a DNS server that translates domain names to IP addresses and vice versa.",
        "reference": "https://bind9.readthedocs.io/",
        "points": 1,
        "answers": [
            {"text": "Web hosting", "is_correct": False},
            {"text": "Domain name resolution", "is_correct": True},
            {"text": "Mail routing", "is_correct": False},
            {"text": "File sharing", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains BIND main configuration?",
        "explanation": "The main BIND configuration file is /etc/bind/named.conf (or /etc/named.conf on some systems).",
        "reference": "https://bind9.readthedocs.io/en/latest/reference.html#configuration-file",
        "points": 1,
        "answers": [
            {"text": "/etc/dns.conf", "is_correct": False},
            {"text": "/etc/bind/named.conf", "is_correct": True},
            {"text": "/etc/bind.conf", "is_correct": False},
            {"text": "/var/bind/config", "is_correct": False},
        ],
    },
    {
        "text": "What is a DNS zone file?",
        "explanation": "A DNS zone file contains DNS records that define the mapping between domain names and IP addresses for a specific domain.",
        "reference": "https://bind9.readthedocs.io/en/latest/chapter3.html#zone-file",
        "points": 1,
        "answers": [
            {"text": "Server configuration", "is_correct": False},
            {"text": "Domain DNS records", "is_correct": True},
            {"text": "Network routing", "is_correct": False},
            {"text": "Access control", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of NFS (Network File System)?",
        "explanation": "NFS allows sharing of filesystems over a network, enabling remote access to files as if they were local.",
        "reference": "https://man7.org/linux/man-pages/man5/nfs.5.html",
        "points": 1,
        "answers": [
            {"text": "Network monitoring", "is_correct": False},
            {"text": "Network file sharing", "is_correct": True},
            {"text": "Network security", "is_correct": False},
            {"text": "Network backup", "is_correct": False},
        ],
    },
    {
        "text": "Which file configures NFS exports?",
        "explanation": "The /etc/exports file defines which directories are shared via NFS and their access permissions.",
        "reference": "https://man7.org/linux/man-pages/man5/exports.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/nfs.conf", "is_correct": False},
            {"text": "/etc/exports", "is_correct": True},
            {"text": "/etc/nfs/exports", "is_correct": False},
            {"text": "/var/nfs/exports", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Samba server?",
        "explanation": "Samba provides file and printer sharing services for Windows clients using SMB/CIFS protocols.",
        "reference": "https://www.samba.org/samba/docs/",
        "points": 1,
        "answers": [
            {"text": "Linux file sharing", "is_correct": False},
            {"text": "Windows file/printer sharing", "is_correct": True},
            {"text": "Database sharing", "is_correct": False},
            {"text": "Web sharing", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains Samba configuration?",
        "explanation": "The main Samba configuration file is /etc/samba/smb.conf, which defines shares and server settings.",
        "reference": "https://man7.org/linux/man-pages/man5/smb.conf.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/samba.conf", "is_correct": False},
            {"text": "/etc/samba/smb.conf", "is_correct": True},
            {"text": "/etc/smb.conf", "is_correct": False},
            {"text": "/var/samba/config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of OpenSSH server?",
        "explanation": "OpenSSH server (sshd) provides secure remote access and file transfer capabilities using encrypted connections.",
        "reference": "https://man7.org/linux/man-pages/man8/sshd.8.html",
        "points": 1,
        "answers": [
            {"text": "Web access", "is_correct": False},
            {"text": "Secure remote access", "is_correct": True},
            {"text": "File compression", "is_correct": False},
            {"text": "Mail delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which file configures SSH server settings?",
        "explanation": "The SSH server configuration file is /etc/ssh/sshd_config, which defines server behavior and security settings.",
        "reference": "https://man7.org/linux/man-pages/man5/sshd_config.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/ssh/ssh_config", "is_correct": False},
            {"text": "/etc/ssh/sshd_config", "is_correct": True},
            {"text": "/etc/sshd.conf", "is_correct": False},
            {"text": "/var/ssh/config", "is_correct": False},
        ],
    },
    {
        "text": "What is SSH key-based authentication?",
        "explanation": "SSH key-based authentication uses public-private key pairs for authentication, providing better security than password-based authentication.",
        "reference": "https://man7.org/linux/man-pages/man1/ssh-keygen.1.html",
        "points": 1,
        "answers": [
            {"text": "Password encryption", "is_correct": False},
            {"text": "Public-private key authentication", "is_correct": True},
            {"text": "Certificate authentication", "is_correct": False},
            {"text": "Token authentication", "is_correct": False},
        ],
    },
    {
        "text": "Which command generates SSH key pairs?",
        "explanation": "ssh-keygen command generates SSH public-private key pairs for authentication purposes.",
        "reference": "https://man7.org/linux/man-pages/man1/ssh-keygen.1.html",
        "points": 1,
        "answers": [
            {"text": "ssh-key", "is_correct": False},
            {"text": "ssh-keygen", "is_correct": True},
            {"text": "genkey", "is_correct": False},
            {"text": "ssh-create", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Postfix mail server?",
        "explanation": "Postfix is a mail transfer agent (MTA) that routes and delivers email messages between mail servers and users.",
        "reference": "http://www.postfix.org/documentation.html",
        "points": 1,
        "answers": [
            {"text": "Web mail interface", "is_correct": False},
            {"text": "Mail transfer and delivery", "is_correct": True},
            {"text": "Mail storage", "is_correct": False},
            {"text": "Mail encryption", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains Postfix main configuration?",
        "explanation": "The main Postfix configuration file is /etc/postfix/main.cf, which defines server settings and behavior.",
        "reference": "http://www.postfix.org/postconf.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/postfix.conf", "is_correct": False},
            {"text": "/etc/postfix/main.cf", "is_correct": True},
            {"text": "/etc/mail/postfix.conf", "is_correct": False},
            {"text": "/var/postfix/config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of mail aliases in Postfix?",
        "explanation": "Mail aliases redirect email from one address to another, allowing mail forwarding and distribution lists.",
        "reference": "http://www.postfix.org/aliases.5.html",
        "points": 1,
        "answers": [
            {"text": "Mail encryption", "is_correct": False},
            {"text": "Mail forwarding and redirection", "is_correct": True},
            {"text": "Mail authentication", "is_correct": False},
            {"text": "Mail compression", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages the Postfix mail queue?",
        "explanation": "postqueue command displays and manages the Postfix mail queue, showing pending and deferred messages.",
        "reference": "http://www.postfix.org/postqueue.1.html",
        "points": 1,
        "answers": [
            {"text": "mailq", "is_correct": False},
            {"text": "postqueue", "is_correct": True},
            {"text": "queuemgr", "is_correct": False},
            {"text": "mailqueue", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of systemd timers?",
        "explanation": "Systemd timers provide scheduling functionality similar to cron, but with better integration with systemd services.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemd.timer.html",
        "points": 1,
        "answers": [
            {"text": "Time synchronization", "is_correct": False},
            {"text": "Task scheduling", "is_correct": True},
            {"text": "Time display", "is_correct": False},
            {"text": "Timeout management", "is_correct": False},
        ],
    },
    {
        "text": "Which command lists active systemd timers?",
        "explanation": "systemctl list-timers displays all active systemd timers with their next run times and associated services.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemctl.html",
        "points": 1,
        "answers": [
            {"text": "systemctl timers", "is_correct": False},
            {"text": "systemctl list-timers", "is_correct": True},
            {"text": "systemctl show-timers", "is_correct": False},
            {"text": "timerctl list", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of systemd-resolved?",
        "explanation": "systemd-resolved provides DNS resolution services for local applications, including caching and DNSSEC validation.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemd-resolved.html",
        "points": 1,
        "answers": [
            {"text": "System recovery", "is_correct": False},
            {"text": "DNS resolution and caching", "is_correct": True},
            {"text": "Service resolution", "is_correct": False},
            {"text": "Resource resolution", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages systemd-resolved configuration?",
        "explanation": "resolvectl command manages systemd-resolved configuration and provides DNS resolution information.",
        "reference": "https://www.freedesktop.org/software/systemd/man/resolvectl.html",
        "points": 1,
        "answers": [
            {"text": "resolve", "is_correct": False},
            {"text": "resolvectl", "is_correct": True},
            {"text": "resolv", "is_correct": False},
            {"text": "dnsctl", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Linux containers (LXC)?",
        "explanation": "LXC provides operating-system-level virtualization allowing multiple isolated Linux systems to run on a single host.",
        "reference": "https://linuxcontainers.org/lxc/",
        "points": 1,
        "answers": [
            {"text": "Hardware virtualization", "is_correct": False},
            {"text": "OS-level virtualization", "is_correct": True},
            {"text": "Network virtualization", "is_correct": False},
            {"text": "Storage virtualization", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates LXC containers?",
        "explanation": "lxc-create command creates new LXC containers with specified templates and configurations.",
        "reference": "https://man7.org/linux/man-pages/man1/lxc-create.1.html",
        "points": 1,
        "answers": [
            {"text": "lxc-new", "is_correct": False},
            {"text": "lxc-create", "is_correct": True},
            {"text": "lxc-make", "is_correct": False},
            {"text": "lxc-build", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of systemd user services?",
        "explanation": "Systemd user services allow individual users to manage their own services without requiring root privileges.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemd.html#User%20Manager",
        "points": 1,
        "answers": [
            {"text": "System administration", "is_correct": False},
            {"text": "User-specific service management", "is_correct": True},
            {"text": "User authentication", "is_correct": False},
            {"text": "User file management", "is_correct": False},
        ],
    },
    {
        "text": "Which directory contains systemd user service files?",
        "explanation": "User systemd service files are located in ~/.config/systemd/user/ for individual users or /usr/lib/systemd/user/ for system-wide user services.",
        "reference": "https://www.freedesktop.org/software/systemd/man/systemd.unit.html",
        "points": 1,
        "answers": [
            {"text": "~/.systemd/user/", "is_correct": False},
            {"text": "~/.config/systemd/user/", "is_correct": True},
            {"text": "~/systemd/", "is_correct": False},
            {"text": "~/.local/systemd/", "is_correct": False},
        ],
    },
]
