"""Linux Professional Institute Certification Level 3 (LPIC-3)"""

CERTIFICATION = {
    "name": "Linux Professional Institute Certification Level 3 (LPIC-3)",
    "description": "Senior level Linux professional and enterprise-level skills",
    "slug": "lpic-3",
    "level": "Expert",
    "duration": 156,
    "questions_count": 52,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which tool is primarily used for advanced LDAP directory management?",
        "explanation": "OpenLDAP's slapd is the primary LDAP directory server, and ldapmodify, ldapsearch, and other ldap* tools are used for advanced directory management.",
        "reference": "https://www.lpi.org/our-certifications/lpic-3-overview",
        "points": 1,
        "answers": [
            {"text": "Active Directory", "is_correct": False},
            {"text": "OpenLDAP (slapd)", "is_correct": True},
            {"text": "NIS", "is_correct": False},
            {"text": "Kerberos", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary configuration file for Samba server?",
        "explanation": "The main Samba configuration file is /etc/samba/smb.conf, which contains global settings and share definitions.",
        "reference": "https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/samba/smb.conf", "is_correct": True},
            {"text": "/etc/smb.conf", "is_correct": False},
            {"text": "/etc/samba/samba.conf", "is_correct": False},
            {"text": "/usr/local/samba/smb.conf", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to test Samba configuration syntax?",
        "explanation": "The testparm command is used to check the syntax of the Samba configuration file and display the configuration parameters.",
        "reference": "https://www.samba.org/samba/docs/current/man-html/testparm.1.html",
        "points": 1,
        "answers": [
            {"text": "smbstatus", "is_correct": False},
            {"text": "testparm", "is_correct": True},
            {"text": "smbclient", "is_correct": False},
            {"text": "nmblookup", "is_correct": False},
        ],
    },
    {
        "text": "What protocol does NFS version 4 use for security by default?",
        "explanation": "NFSv4 uses Kerberos for authentication and security by default, providing strong security mechanisms for network file systems.",
        "reference": "https://tools.ietf.org/rfc/rfc7530.txt",
        "points": 1,
        "answers": [
            {"text": "SSL/TLS", "is_correct": False},
            {"text": "Kerberos", "is_correct": True},
            {"text": "LDAP", "is_correct": False},
            {"text": "SSH", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains the NFS export configuration?",
        "explanation": "/etc/exports contains the configuration for NFS exports, specifying which directories are shared and with what permissions.",
        "reference": "https://man7.org/linux/man-pages/man5/exports.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/fstab", "is_correct": False},
            {"text": "/etc/exports", "is_correct": True},
            {"text": "/etc/nfs.conf", "is_correct": False},
            {"text": "/etc/nfs/exports", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of LDAP schema in OpenLDAP?",
        "explanation": "LDAP schema defines the structure and rules for data stored in the directory, including object classes and attribute types.",
        "reference": "https://www.openldap.org/doc/admin24/schema.html",
        "points": 1,
        "answers": [
            {"text": "User authentication", "is_correct": False},
            {"text": "Data structure definition", "is_correct": True},
            {"text": "Network configuration", "is_correct": False},
            {"text": "Access control", "is_correct": False},
        ],
    },
    {
        "text": "Which OpenLDAP command is used to add entries to the directory?",
        "explanation": "ldapadd command is used to add new entries to an LDAP directory from LDIF (LDAP Data Interchange Format) files.",
        "reference": "https://man7.org/linux/man-pages/man1/ldapadd.1.html",
        "points": 1,
        "answers": [
            {"text": "ldapmodify", "is_correct": False},
            {"text": "ldapadd", "is_correct": True},
            {"text": "ldapsearch", "is_correct": False},
            {"text": "ldapdelete", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of LDAP Access Control Lists (ACLs)?",
        "explanation": "LDAP ACLs control access permissions to directory entries and attributes, defining who can read, write, or modify specific data.",
        "reference": "https://www.openldap.org/doc/admin24/access-control.html",
        "points": 1,
        "answers": [
            {"text": "Data encryption", "is_correct": False},
            {"text": "Access permission control", "is_correct": True},
            {"text": "Schema validation", "is_correct": False},
            {"text": "Replication settings", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains OpenLDAP server configuration?",
        "explanation": "slapd.conf is the traditional configuration file for OpenLDAP server, though newer versions use cn=config (dynamic configuration).",
        "reference": "https://man7.org/linux/man-pages/man5/slapd.conf.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/ldap.conf", "is_correct": False},
            {"text": "/etc/openldap/slapd.conf", "is_correct": True},
            {"text": "/etc/slapd/config", "is_correct": False},
            {"text": "/var/ldap/slapd.conf", "is_correct": False},
        ],
    },
    {
        "text": "What is LDAP replication and why is it important?",
        "explanation": "LDAP replication synchronizes directory data across multiple servers for redundancy, load distribution, and high availability.",
        "reference": "https://www.openldap.org/doc/admin24/replication.html",
        "points": 1,
        "answers": [
            {"text": "Data backup only", "is_correct": False},
            {"text": "Data synchronization for redundancy", "is_correct": True},
            {"text": "Schema validation", "is_correct": False},
            {"text": "User authentication", "is_correct": False},
        ],
    },
    {
        "text": "Which Samba tool is used to join a Linux system to an Active Directory domain?",
        "explanation": "net ads join command is used to join a Linux system running Samba to an Active Directory domain.",
        "reference": "https://www.samba.org/samba/docs/current/man-html/net.8.html",
        "points": 1,
        "answers": [
            {"text": "smbclient", "is_correct": False},
            {"text": "net ads join", "is_correct": True},
            {"text": "wbinfo", "is_correct": False},
            {"text": "pdbedit", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Winbind in Samba?",
        "explanation": "Winbind allows Linux systems to authenticate users against Windows domains and resolve Windows user/group information.",
        "reference": "https://www.samba.org/samba/docs/current/man-html/winbindd.8.html",
        "points": 1,
        "answers": [
            {"text": "File sharing only", "is_correct": False},
            {"text": "Windows domain authentication", "is_correct": True},
            {"text": "Print serving", "is_correct": False},
            {"text": "Network browsing", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages Samba user database?",
        "explanation": "pdbedit command is used to manage the Samba user database, including adding, modifying, and deleting user accounts.",
        "reference": "https://www.samba.org/samba/docs/current/man-html/pdbedit.8.html",
        "points": 1,
        "answers": [
            {"text": "smbpasswd", "is_correct": False},
            {"text": "pdbedit", "is_correct": True},
            {"text": "useradd", "is_correct": False},
            {"text": "smbclient", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Samba's SWAT tool?",
        "explanation": "SWAT (Samba Web Administration Tool) provides a web-based interface for configuring and managing Samba servers.",
        "reference": "https://www.samba.org/samba/docs/current/man-html/swat.8.html",
        "points": 1,
        "answers": [
            {"text": "Command-line management", "is_correct": False},
            {"text": "Web-based administration", "is_correct": True},
            {"text": "File transfer", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which NFS service handles file locking?",
        "explanation": "rpc.lockd (or lockd) service handles file locking for NFS, ensuring file integrity in multi-client environments.",
        "reference": "https://man7.org/linux/man-pages/man8/rpc.lockd.8.html",
        "points": 1,
        "answers": [
            {"text": "nfsd", "is_correct": False},
            {"text": "rpc.lockd", "is_correct": True},
            {"text": "rpc.mountd", "is_correct": False},
            {"text": "portmap", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of rpc.mountd in NFS?",
        "explanation": "rpc.mountd handles mount requests from NFS clients and manages the mount protocol for NFS filesystems.",
        "reference": "https://man7.org/linux/man-pages/man8/rpc.mountd.8.html",
        "points": 1,
        "answers": [
            {"text": "File serving", "is_correct": False},
            {"text": "Mount request handling", "is_correct": True},
            {"text": "User authentication", "is_correct": False},
            {"text": "File locking", "is_correct": False},
        ],
    },
    {
        "text": "Which command exports NFS shares without restarting the service?",
        "explanation": "exportfs command can export or unexport NFS shares dynamically without restarting the NFS service.",
        "reference": "https://man7.org/linux/man-pages/man8/exportfs.8.html",
        "points": 1,
        "answers": [
            {"text": "nfsstat", "is_correct": False},
            {"text": "exportfs", "is_correct": True},
            {"text": "showmount", "is_correct": False},
            {"text": "mount", "is_correct": False},
        ],
    },
    {
        "text": "What is NFS4 referrals feature?",
        "explanation": "NFSv4 referrals allow servers to redirect clients to other servers for specific portions of the namespace, enabling distributed filesystems.",
        "reference": "https://tools.ietf.org/rfc/rfc7530.txt",
        "points": 1,
        "answers": [
            {"text": "User redirection", "is_correct": False},
            {"text": "Namespace redirection to other servers", "is_correct": True},
            {"text": "Error handling", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which protocol provides secure authentication for NFS?",
        "explanation": "Kerberos provides secure authentication for NFS, especially in NFSv4 implementations, offering strong security mechanisms.",
        "reference": "https://tools.ietf.org/rfc/rfc7530.txt",
        "points": 1,
        "answers": [
            {"text": "LDAP", "is_correct": False},
            {"text": "Kerberos", "is_correct": True},
            {"text": "SSL/TLS", "is_correct": False},
            {"text": "SSH", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Apache mod_rewrite?",
        "explanation": "mod_rewrite provides URL rewriting capabilities for Apache, allowing dynamic URL manipulation based on rules and conditions.",
        "reference": "https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html",
        "points": 1,
        "answers": [
            {"text": "SSL encryption", "is_correct": False},
            {"text": "URL rewriting and redirection", "is_correct": True},
            {"text": "User authentication", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which Apache module provides reverse proxy functionality?",
        "explanation": "mod_proxy module enables Apache to function as a reverse proxy server, forwarding requests to backend servers.",
        "reference": "https://httpd.apache.org/docs/2.4/mod/mod_proxy.html",
        "points": 1,
        "answers": [
            {"text": "mod_rewrite", "is_correct": False},
            {"text": "mod_proxy", "is_correct": True},
            {"text": "mod_ssl", "is_correct": False},
            {"text": "mod_cache", "is_correct": False},
        ],
    },
    {
        "text": "What is Apache mod_security used for?",
        "explanation": "mod_security is a web application firewall (WAF) module that provides protection against web application attacks and vulnerabilities.",
        "reference": "https://github.com/SpiderLabs/ModSecurity/wiki",
        "points": 1,
        "answers": [
            {"text": "SSL termination", "is_correct": False},
            {"text": "Web application firewall", "is_correct": True},
            {"text": "Load balancing", "is_correct": False},
            {"text": "Content compression", "is_correct": False},
        ],
    },
    {
        "text": "Which command tests Apache configuration syntax?",
        "explanation": "apache2ctl configtest (or httpd -t) tests Apache configuration syntax without starting the server.",
        "reference": "https://httpd.apache.org/docs/2.4/programs/httpd.html",
        "points": 1,
        "answers": [
            {"text": "apache2 -test", "is_correct": False},
            {"text": "apache2ctl configtest", "is_correct": True},
            {"text": "httpd -check", "is_correct": False},
            {"text": "apachectl -verify", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Apache LogFormat directive?",
        "explanation": "LogFormat directive defines custom log formats for Apache access logs, specifying which information to log and how to format it.",
        "reference": "https://httpd.apache.org/docs/2.4/mod/mod_log_config.html#logformat",
        "points": 1,
        "answers": [
            {"text": "Error handling", "is_correct": False},
            {"text": "Custom log format definition", "is_correct": True},
            {"text": "Log rotation", "is_correct": False},
            {"text": "Log compression", "is_correct": False},
        ],
    },
    {
        "text": "Which Nginx module handles load balancing?",
        "explanation": "ngx_http_upstream_module provides load balancing functionality in Nginx, distributing requests among backend servers.",
        "reference": "https://nginx.org/en/docs/http/ngx_http_upstream_module.html",
        "points": 1,
        "answers": [
            {"text": "ngx_http_proxy_module", "is_correct": False},
            {"text": "ngx_http_upstream_module", "is_correct": True},
            {"text": "ngx_http_rewrite_module", "is_correct": False},
            {"text": "ngx_http_ssl_module", "is_correct": False},
        ],
    },
    {
        "text": "What is Nginx FastCGI used for?",
        "explanation": "FastCGI in Nginx is used to interface with backend application servers, particularly for PHP and other dynamic content generation.",
        "reference": "https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html",
        "points": 1,
        "answers": [
            {"text": "Static file serving", "is_correct": False},
            {"text": "Dynamic content generation interface", "is_correct": True},
            {"text": "SSL termination", "is_correct": False},
            {"text": "Caching", "is_correct": False},
        ],
    },
    {
        "text": "Which Nginx directive enables gzip compression?",
        "explanation": "The gzip directive in Nginx enables gzip compression for responses, reducing bandwidth usage and improving performance.",
        "reference": "https://nginx.org/en/docs/http/ngx_http_gzip_module.html",
        "points": 1,
        "answers": [
            {"text": "compress", "is_correct": False},
            {"text": "gzip", "is_correct": True},
            {"text": "deflate", "is_correct": False},
            {"text": "zip", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Nginx rate limiting?",
        "explanation": "Nginx rate limiting controls the rate of requests from clients, providing protection against DDoS attacks and resource abuse.",
        "reference": "https://nginx.org/en/docs/http/ngx_http_limit_req_module.html",
        "points": 1,
        "answers": [
            {"text": "Load balancing", "is_correct": False},
            {"text": "Request rate control and DDoS protection", "is_correct": True},
            {"text": "Caching", "is_correct": False},
            {"text": "SSL termination", "is_correct": False},
        ],
    },
    {
        "text": "Which command reloads Nginx configuration without downtime?",
        "explanation": "nginx -s reload gracefully reloads Nginx configuration without dropping existing connections or causing downtime.",
        "reference": "https://nginx.org/en/docs/control.html",
        "points": 1,
        "answers": [
            {"text": "nginx -restart", "is_correct": False},
            {"text": "nginx -s reload", "is_correct": True},
            {"text": "nginx -refresh", "is_correct": False},
            {"text": "nginx -update", "is_correct": False},
        ],
    },
    {
        "text": "What is Squid's cache hierarchy feature?",
        "explanation": "Squid cache hierarchy allows multiple proxy servers to work together, sharing cached content and improving overall cache efficiency.",
        "reference": "http://www.squid-cache.org/Doc/config/cache_peer/",
        "points": 1,
        "answers": [
            {"text": "User hierarchy", "is_correct": False},
            {"text": "Multi-proxy cache sharing", "is_correct": True},
            {"text": "File system hierarchy", "is_correct": False},
            {"text": "Network hierarchy", "is_correct": False},
        ],
    },
    {
        "text": "Which Squid directive defines access control rules?",
        "explanation": "acl (Access Control List) directive in Squid defines rules for controlling client access to the proxy server.",
        "reference": "http://www.squid-cache.org/Doc/config/acl/",
        "points": 1,
        "answers": [
            {"text": "access_rule", "is_correct": False},
            {"text": "acl", "is_correct": True},
            {"text": "auth_param", "is_correct": False},
            {"text": "http_access", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Squid cache replacement policies?",
        "explanation": "Cache replacement policies in Squid determine which cached objects to remove when cache storage becomes full.",
        "reference": "http://www.squid-cache.org/Doc/config/cache_replacement_policy/",
        "points": 1,
        "answers": [
            {"text": "User authentication", "is_correct": False},
            {"text": "Cache object eviction strategy", "is_correct": True},
            {"text": "Network routing", "is_correct": False},
            {"text": "Content filtering", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays Squid cache statistics?",
        "explanation": "squidclient mgr:info command displays comprehensive Squid cache statistics and management information.",
        "reference": "http://www.squid-cache.org/Doc/config/cachemgr_passwd/",
        "points": 1,
        "answers": [
            {"text": "squid -stats", "is_correct": False},
            {"text": "squidclient mgr:info", "is_correct": True},
            {"text": "squid-status", "is_correct": False},
            {"text": "cache-stats", "is_correct": False},
        ],
    },
    {
        "text": "What is transparent proxying in Squid?",
        "explanation": "Transparent proxying intercepts network traffic without requiring client configuration, automatically redirecting web requests through the proxy.",
        "reference": "http://www.squid-cache.org/Doc/config/http_port/",
        "points": 1,
        "answers": [
            {"text": "Visible proxy configuration", "is_correct": False},
            {"text": "Automatic traffic interception", "is_correct": True},
            {"text": "Authentication bypass", "is_correct": False},
            {"text": "Cache transparency", "is_correct": False},
        ],
    },
    {
        "text": "Which DNS record type defines mail servers for a domain?",
        "explanation": "MX (Mail Exchange) records specify the mail servers responsible for handling email for a particular domain.",
        "reference": "https://tools.ietf.org/rfc/rfc1035.txt",
        "points": 1,
        "answers": [
            {"text": "A", "is_correct": False},
            {"text": "MX", "is_correct": True},
            {"text": "CNAME", "is_correct": False},
            {"text": "PTR", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of DNS DNSSEC?",
        "explanation": "DNSSEC (DNS Security Extensions) provides authentication and data integrity for DNS responses, preventing DNS spoofing attacks.",
        "reference": "https://tools.ietf.org/rfc/rfc4033.txt",
        "points": 1,
        "answers": [
            {"text": "DNS encryption", "is_correct": False},
            {"text": "DNS authentication and integrity", "is_correct": True},
            {"text": "DNS compression", "is_correct": False},
            {"text": "DNS caching", "is_correct": False},
        ],
    },
    {
        "text": "Which BIND tool checks zone file syntax?",
        "explanation": "named-checkzone command validates DNS zone file syntax and reports any errors or inconsistencies.",
        "reference": "https://bind9.readthedocs.io/en/latest/manpages.html#named-checkzone-named-compilezone",
        "points": 1,
        "answers": [
            {"text": "zone-check", "is_correct": False},
            {"text": "named-checkzone", "is_correct": True},
            {"text": "bind-verify", "is_correct": False},
            {"text": "dns-validate", "is_correct": False},
        ],
    },
    {
        "text": "What is DNS zone transfer and why is it important?",
        "explanation": "DNS zone transfer replicates zone data from primary to secondary DNS servers, providing redundancy and load distribution for DNS services.",
        "reference": "https://tools.ietf.org/rfc/rfc1034.txt",
        "points": 1,
        "answers": [
            {"text": "Domain migration", "is_correct": False},
            {"text": "Zone data replication to secondary servers", "is_correct": True},
            {"text": "DNS caching", "is_correct": False},
            {"text": "Record updates", "is_correct": False},
        ],
    },
    {
        "text": "Which BIND configuration option restricts zone transfers?",
        "explanation": "allow-transfer option in BIND configuration restricts which servers are allowed to perform zone transfers from the primary server.",
        "reference": "https://bind9.readthedocs.io/en/latest/reference.html#zone-transfers",
        "points": 1,
        "answers": [
            {"text": "transfer-acl", "is_correct": False},
            {"text": "allow-transfer", "is_correct": True},
            {"text": "zone-security", "is_correct": False},
            {"text": "transfer-policy", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of HAProxy in enterprise environments?",
        "explanation": "HAProxy provides high-availability load balancing and proxying for web services, distributing traffic across multiple backend servers.",
        "reference": "http://www.haproxy.org/download/1.8/doc/configuration.txt",
        "points": 1,
        "answers": [
            {"text": "Web development", "is_correct": False},
            {"text": "Load balancing and high availability", "is_correct": True},
            {"text": "Database management", "is_correct": False},
            {"text": "Content management", "is_correct": False},
        ],
    },
    {
        "text": "Which HAProxy algorithm distributes requests round-robin?",
        "explanation": "The roundrobin algorithm in HAProxy distributes requests sequentially across all available backend servers.",
        "reference": "http://www.haproxy.org/download/1.8/doc/configuration.txt",
        "points": 1,
        "answers": [
            {"text": "leastconn", "is_correct": False},
            {"text": "roundrobin", "is_correct": True},
            {"text": "source", "is_correct": False},
            {"text": "random", "is_correct": False},
        ],
    },
    {
        "text": "What is HAProxy health checking?",
        "explanation": "HAProxy health checking monitors backend server availability and automatically removes failed servers from the load balancing pool.",
        "reference": "http://www.haproxy.org/download/1.8/doc/configuration.txt",
        "points": 1,
        "answers": [
            {"text": "System health monitoring", "is_correct": False},
            {"text": "Backend server availability monitoring", "is_correct": True},
            {"text": "Network health checking", "is_correct": False},
            {"text": "Application health scanning", "is_correct": False},
        ],
    },
    {
        "text": "Which command shows HAProxy statistics?",
        "explanation": "HAProxy provides statistics through a web interface or socket interface, accessible via the stats directive in configuration.",
        "reference": "http://www.haproxy.org/download/1.8/doc/configuration.txt",
        "points": 1,
        "answers": [
            {"text": "haproxy -stats", "is_correct": False},
            {"text": "stats interface", "is_correct": True},
            {"text": "haproxy-status", "is_correct": False},
            {"text": "proxy-info", "is_correct": False},
        ],
    },
    {
        "text": "What is SSL/TLS termination in HAProxy?",
        "explanation": "SSL/TLS termination in HAProxy decrypts SSL/TLS traffic at the load balancer and forwards unencrypted traffic to backend servers.",
        "reference": "http://www.haproxy.org/download/1.8/doc/configuration.txt",
        "points": 1,
        "answers": [
            {"text": "SSL connection ending", "is_correct": False},
            {"text": "SSL decryption at load balancer", "is_correct": True},
            {"text": "SSL certificate management", "is_correct": False},
            {"text": "SSL monitoring", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Keepalived in Linux clustering?",
        "explanation": "Keepalived provides high availability through VRRP (Virtual Router Redundancy Protocol) and health checking for services.",
        "reference": "https://keepalived.readthedocs.io/en/latest/",
        "points": 1,
        "answers": [
            {"text": "Process monitoring", "is_correct": False},
            {"text": "High availability and VRRP", "is_correct": True},
            {"text": "Service management", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which protocol does Keepalived use for failover?",
        "explanation": "Keepalived uses VRRP (Virtual Router Redundancy Protocol) to provide automatic failover between redundant systems.",
        "reference": "https://tools.ietf.org/rfc/rfc3768.txt",
        "points": 1,
        "answers": [
            {"text": "HSRP", "is_correct": False},
            {"text": "VRRP", "is_correct": True},
            {"text": "CARP", "is_correct": False},
            {"text": "BGP", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of virtual IP (VIP) in Keepalived?",
        "explanation": "Virtual IP (VIP) in Keepalived provides a floating IP address that moves between servers during failover, ensuring service continuity.",
        "reference": "https://keepalived.readthedocs.io/en/latest/configuration_synopsis.html",
        "points": 1,
        "answers": [
            {"text": "Network virtualization", "is_correct": False},
            {"text": "Floating IP for failover", "is_correct": True},
            {"text": "IP address pooling", "is_correct": False},
            {"text": "Virtual networking", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains Keepalived configuration?",
        "explanation": "The main Keepalived configuration file is /etc/keepalived/keepalived.conf, which defines VRRP instances and health checks.",
        "reference": "https://keepalived.readthedocs.io/en/latest/configuration_synopsis.html",
        "points": 1,
        "answers": [
            {"text": "/etc/keepalived.conf", "is_correct": False},
            {"text": "/etc/keepalived/keepalived.conf", "is_correct": True},
            {"text": "/etc/vrrp.conf", "is_correct": False},
            {"text": "/var/keepalived/config", "is_correct": False},
        ],
    },
    {
        "text": "What is Pacemaker in Linux clustering?",
        "explanation": "Pacemaker is a cluster resource manager that provides high availability by managing cluster resources and handling failover scenarios.",
        "reference": "https://clusterlabs.org/pacemaker/doc/",
        "points": 1,
        "answers": [
            {"text": "Performance monitoring", "is_correct": False},
            {"text": "Cluster resource management", "is_correct": True},
            {"text": "Process management", "is_correct": False},
            {"text": "Package management", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages Pacemaker cluster resources?",
        "explanation": "crm command-line tool (or pcs in newer versions) is used to configure and manage Pacemaker cluster resources and constraints.",
        "reference": "https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html/Clusters_from_Scratch/index.html",
        "points": 1,
        "answers": [
            {"text": "cluster", "is_correct": False},
            {"text": "crm", "is_correct": True},
            {"text": "pacemaker", "is_correct": False},
            {"text": "resource", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Corosync in clustering?",
        "explanation": "Corosync provides the messaging layer for cluster communication, enabling cluster membership and reliable message delivery between nodes.",
        "reference": "https://corosync.github.io/corosync/",
        "points": 1,
        "answers": [
            {"text": "Resource management", "is_correct": False},
            {"text": "Cluster communication and membership", "is_correct": True},
            {"text": "Service synchronization", "is_correct": False},
            {"text": "Configuration synchronization", "is_correct": False},
        ],
    },
    {
        "text": "Which file configures Corosync cluster communication?",
        "explanation": "The main Corosync configuration file is /etc/corosync/corosync.conf, which defines cluster membership and communication settings.",
        "reference": "https://man7.org/linux/man-pages/man5/corosync.conf.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/cluster.conf", "is_correct": False},
            {"text": "/etc/corosync/corosync.conf", "is_correct": True},
            {"text": "/etc/corosync.conf", "is_correct": False},
            {"text": "/var/corosync/config", "is_correct": False},
        ],
    },
]
