"""SUSE Certified Linux Administrator (CLA)"""

CERTIFICATION = {
    "name": "SUSE Certified Linux Administrator (CLA)",
    "description": "SUSE Linux Enterprise administration and management skills",
    "slug": "suse-cla",
    "level": "Professional",
    "duration": 171,
    "questions_count": 57,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which package manager is primarily used in SUSE Linux Enterprise?",
        "explanation": "SUSE Linux Enterprise uses zypper as its primary package manager for installing, updating, and removing software packages.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-sw-cl.html",
        "points": 1,
        "answers": [
            {"text": "yum", "is_correct": False},
            {"text": "apt", "is_correct": False},
            {"text": "zypper", "is_correct": True},
            {"text": "dnf", "is_correct": False},
        ],
    },
    {
        "text": "What is YaST in SUSE Linux?",
        "explanation": "YaST (Yet another Setup Tool) is SUSE's comprehensive system administration and configuration tool with both GUI and text-based interfaces.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-yast-text.html",
        "points": 1,
        "answers": [
            {"text": "A text editor", "is_correct": False},
            {"text": "System administration tool", "is_correct": True},
            {"text": "Package repository", "is_correct": False},
            {"text": "File manager", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to list all available repositories in SUSE?",
        "explanation": "The 'zypper lr' or 'zypper repos' command lists all configured software repositories in SUSE Linux systems.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/sec-zypper-softman.html",
        "points": 1,
        "answers": [
            {"text": "zypper list", "is_correct": False},
            {"text": "zypper lr", "is_correct": True},
            {"text": "zypper show", "is_correct": False},
            {"text": "zypper search", "is_correct": False},
        ],
    },
    {
        "text": "What is the default init system in modern SUSE Linux Enterprise?",
        "explanation": "Modern SUSE Linux Enterprise Server uses systemd as its init system for managing services and system processes.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-systemd.html",
        "points": 1,
        "answers": [
            {"text": "SysV init", "is_correct": False},
            {"text": "systemd", "is_correct": True},
            {"text": "Upstart", "is_correct": False},
            {"text": "OpenRC", "is_correct": False},
        ],
    },
    {
        "text": "Which tool is used for network configuration in SUSE Linux?",
        "explanation": "Wicked is SUSE's network configuration framework that replaced the traditional ifup/ifdown scripts for network interface management.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-network.html",
        "points": 1,
        "answers": [
            {"text": "NetworkManager", "is_correct": False},
            {"text": "Wicked", "is_correct": True},
            {"text": "netplan", "is_correct": False},
            {"text": "ifupdown", "is_correct": False},
        ],
    },
    {
        "text": "Which command updates all installed packages in SUSE Linux?",
        "explanation": "The 'zypper update' command updates all installed packages to their latest versions in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/sec-zypper-update.html",
        "points": 1,
        "answers": [
            {"text": "zypper refresh", "is_correct": False},
            {"text": "zypper update", "is_correct": True},
            {"text": "zypper upgrade", "is_correct": False},
            {"text": "zypper patch", "is_correct": False},
        ],
    },
    {
        "text": "What is the command to install a new package in SUSE Linux?",
        "explanation": "The 'zypper install' command is used to install new packages in SUSE Linux Enterprise.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/sec-zypper-softman.html",
        "points": 1,
        "answers": [
            {"text": "zypper add", "is_correct": False},
            {"text": "zypper install", "is_correct": True},
            {"text": "zypper get", "is_correct": False},
            {"text": "zypper fetch", "is_correct": False},
        ],
    },
    {
        "text": "Which command removes a package in SUSE Linux?",
        "explanation": "The 'zypper remove' command uninstalls a package from the system in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/sec-zypper-softman.html",
        "points": 1,
        "answers": [
            {"text": "zypper erase", "is_correct": False},
            {"text": "zypper remove", "is_correct": True},
            {"text": "zypper uninstall", "is_correct": False},
            {"text": "zypper delete", "is_correct": False},
        ],
    },
    {
        "text": "Which command refreshes repository metadata in SUSE Linux?",
        "explanation": "The 'zypper refresh' command updates repository metadata to ensure the latest package information is available.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/sec-zypper-softman.html",
        "points": 1,
        "answers": [
            {"text": "zypper update", "is_correct": False},
            {"text": "zypper refresh", "is_correct": True},
            {"text": "zypper reload", "is_correct": False},
            {"text": "zypper sync", "is_correct": False},
        ],
    },
    {
        "text": "What is the default file system for SUSE Linux Enterprise 15?",
        "explanation": "SUSE Linux Enterprise 15 uses XFS as the default file system for data partitions.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-storage.html",
        "points": 1,
        "answers": [
            {"text": "ext4", "is_correct": False},
            {"text": "XFS", "is_correct": True},
            {"text": "Btrfs", "is_correct": False},
            {"text": "ReiserFS", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays disk usage in SUSE Linux?",
        "explanation": "The 'df' command displays disk space usage for all mounted file systems.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-storage.html",
        "points": 1,
        "answers": [
            {"text": "du", "is_correct": False},
            {"text": "df", "is_correct": True},
            {"text": "lsblk", "is_correct": False},
            {"text": "lsfs", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create a new user in SUSE Linux?",
        "explanation": "The 'useradd' command creates a new user account in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-user.html",
        "points": 1,
        "answers": [
            {"text": "adduser", "is_correct": False},
            {"text": "useradd", "is_correct": True},
            {"text": "mkuser", "is_correct": False},
            {"text": "newuser", "is_correct": False},
        ],
    },
    {
        "text": "Which command changes a user's password in SUSE Linux?",
        "explanation": "The 'passwd' command changes the password for a user account in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-user.html",
        "points": 1,
        "answers": [
            {"text": "chpasswd", "is_correct": False},
            {"text": "passwd", "is_correct": True},
            {"text": "setpass", "is_correct": False},
            {"text": "userpass", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains user account information in SUSE Linux?",
        "explanation": "The /etc/passwd file contains user account information in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-user.html",
        "points": 1,
        "answers": [
            {"text": "/etc/shadow", "is_correct": False},
            {"text": "/etc/passwd", "is_correct": True},
            {"text": "/etc/group", "is_correct": False},
            {"text": "/etc/users", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to add a user to a group in SUSE Linux?",
        "explanation": "The 'usermod -aG' command adds a user to a supplementary group in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-user.html",
        "points": 1,
        "answers": [
            {"text": "adduser", "is_correct": False},
            {"text": "usermod -aG", "is_correct": True},
            {"text": "groupadd", "is_correct": False},
            {"text": "gpasswd", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays running processes in SUSE Linux?",
        "explanation": "The 'ps' command displays information about currently running processes.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-proc.html",
        "points": 1,
        "answers": [
            {"text": "top", "is_correct": False},
            {"text": "ps", "is_correct": True},
            {"text": "jobs", "is_correct": False},
            {"text": "proc", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to schedule tasks in SUSE Linux?",
        "explanation": "The 'crontab' command is used to schedule recurring tasks in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-cron.html",
        "points": 1,
        "answers": [
            {"text": "at", "is_correct": False},
            {"text": "crontab", "is_correct": True},
            {"text": "schedule", "is_correct": False},
            {"text": "cronjob", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display memory usage in SUSE Linux?",
        "explanation": "The 'free' command displays memory usage statistics in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-proc.html",
        "points": 1,
        "answers": [
            {"text": "meminfo", "is_correct": False},
            {"text": "free", "is_correct": True},
            {"text": "memory", "is_correct": False},
            {"text": "top", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change file permissions in SUSE Linux?",
        "explanation": "The 'chmod' command changes file and directory permissions in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-permissions.html",
        "points": 1,
        "answers": [
            {"text": "chown", "is_correct": False},
            {"text": "chmod", "is_correct": True},
            {"text": "chgrp", "is_correct": False},
            {"text": "perm", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change file ownership in SUSE Linux?",
        "explanation": "The 'chown' command changes the owner and group of files and directories in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-permissions.html",
        "points": 1,
        "answers": [
            {"text": "chmod", "is_correct": False},
            {"text": "chown", "is_correct": True},
            {"text": "owner", "is_correct": False},
            {"text": "own", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create a symbolic link in SUSE Linux?",
        "explanation": "The 'ln -s' command creates a symbolic (soft) link in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-files.html",
        "points": 1,
        "answers": [
            {"text": "link", "is_correct": False},
            {"text": "ln -s", "is_correct": True},
            {"text": "symlink", "is_correct": False},
            {"text": "softlink", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to find files by name in SUSE Linux?",
        "explanation": "The 'find' command searches for files and directories by name and other criteria in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-files.html",
        "points": 1,
        "answers": [
            {"text": "locate", "is_correct": False},
            {"text": "find", "is_correct": True},
            {"text": "search", "is_correct": False},
            {"text": "which", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to compress files in SUSE Linux?",
        "explanation": "The 'gzip' command compresses files using the gzip algorithm in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-archiving.html",
        "points": 1,
        "answers": [
            {"text": "compress", "is_correct": False},
            {"text": "gzip", "is_correct": True},
            {"text": "zip", "is_correct": False},
            {"text": "pack", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create compressed archives in SUSE Linux?",
        "explanation": "The 'tar' command with compression options (e.g., tar -czf) creates compressed archives in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-archiving.html",
        "points": 1,
        "answers": [
            {"text": "archive", "is_correct": False},
            {"text": "tar", "is_correct": True},
            {"text": "zip", "is_correct": False},
            {"text": "pack", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays system log messages in SUSE Linux?",
        "explanation": "The 'journalctl' command displays logs from the systemd journal in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-logs.html",
        "points": 1,
        "answers": [
            {"text": "syslog", "is_correct": False},
            {"text": "journalctl", "is_correct": True},
            {"text": "dmesg", "is_correct": False},
            {"text": "logview", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display network interfaces in SUSE Linux?",
        "explanation": "The 'ip addr' command displays network interface configuration in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-network.html",
        "points": 1,
        "answers": [
            {"text": "ifconfig", "is_correct": False},
            {"text": "ip addr", "is_correct": True},
            {"text": "netstat", "is_correct": False},
            {"text": "network", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to test network connectivity in SUSE Linux?",
        "explanation": "The 'ping' command tests network connectivity to a remote host in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-network.html",
        "points": 1,
        "answers": [
            {"text": "test", "is_correct": False},
            {"text": "ping", "is_correct": True},
            {"text": "connect", "is_correct": False},
            {"text": "trace", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains DNS resolver configuration in SUSE Linux?",
        "explanation": "The /etc/resolv.conf file contains DNS resolver configuration in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-network.html",
        "points": 1,
        "answers": [
            {"text": "/etc/hosts", "is_correct": False},
            {"text": "/etc/resolv.conf", "is_correct": True},
            {"text": "/etc/dns.conf", "is_correct": False},
            {"text": "/etc/nameserver", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to manage firewall rules in SUSE Linux?",
        "explanation": "The 'firewall-cmd' command is used to manage firewalld rules in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-firewall.html",
        "points": 1,
        "answers": [
            {"text": "iptables", "is_correct": False},
            {"text": "firewall-cmd", "is_correct": True},
            {"text": "ufw", "is_correct": False},
            {"text": "netfilter", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to set the system hostname in SUSE Linux?",
        "explanation": "The 'hostnamectl' command sets the system hostname in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-hostname.html",
        "points": 1,
        "answers": [
            {"text": "hostname", "is_correct": False},
            {"text": "hostnamectl", "is_correct": True},
            {"text": "sethostname", "is_correct": False},
            {"text": "name", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to synchronize system time in SUSE Linux?",
        "explanation": "The 'timedatectl' command manages system time and date settings in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-time.html",
        "points": 1,
        "answers": [
            {"text": "ntpdate", "is_correct": False},
            {"text": "timedatectl", "is_correct": True},
            {"text": "date", "is_correct": False},
            {"text": "time", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays hardware information in SUSE Linux?",
        "explanation": "The 'lshw' command displays detailed hardware information in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-hardware.html",
        "points": 1,
        "answers": [
            {"text": "hardware", "is_correct": False},
            {"text": "lshw", "is_correct": True},
            {"text": "hwinfo", "is_correct": False},
            {"text": "sysinfo", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create a logical volume in SUSE Linux?",
        "explanation": "The 'lvcreate' command creates logical volumes in LVM on SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-lvm.html",
        "points": 1,
        "answers": [
            {"text": "vgcreate", "is_correct": False},
            {"text": "lvcreate", "is_correct": True},
            {"text": "pvcreate", "is_correct": False},
            {"text": "lvmcreate", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to extend a logical volume in SUSE Linux?",
        "explanation": "The 'lvextend' command extends the size of logical volumes in LVM on SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-lvm.html",
        "points": 1,
        "answers": [
            {"text": "lvgrow", "is_correct": False},
            {"text": "lvextend", "is_correct": True},
            {"text": "lvexpand", "is_correct": False},
            {"text": "lvresize", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create a volume group in SUSE Linux?",
        "explanation": "The 'vgcreate' command creates volume groups in LVM on SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-lvm.html",
        "points": 1,
        "answers": [
            {"text": "lvcreate", "is_correct": False},
            {"text": "vgcreate", "is_correct": True},
            {"text": "pvcreate", "is_correct": False},
            {"text": "volgroup", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to initialize a disk for LVM in SUSE Linux?",
        "explanation": "The 'pvcreate' command initializes a disk or partition for use with LVM in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-lvm.html",
        "points": 1,
        "answers": [
            {"text": "lvcreate", "is_correct": False},
            {"text": "pvcreate", "is_correct": True},
            {"text": "vgcreate", "is_correct": False},
            {"text": "diskcreate", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to check the status of a systemd service in SUSE Linux?",
        "explanation": "The 'systemctl status' command displays the status of a systemd service in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-systemd.html",
        "points": 1,
        "answers": [
            {"text": "systemctl info", "is_correct": False},
            {"text": "systemctl status", "is_correct": True},
            {"text": "systemctl show", "is_correct": False},
            {"text": "systemctl check", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to enable a service at boot in SUSE Linux?",
        "explanation": "The 'systemctl enable' command enables a service to start at boot in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-systemd.html",
        "points": 1,
        "answers": [
            {"text": "systemctl start", "is_correct": False},
            {"text": "systemctl enable", "is_correct": True},
            {"text": "systemctl activate", "is_correct": False},
            {"text": "systemctl boot", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to start a service immediately in SUSE Linux?",
        "explanation": "The 'systemctl start' command starts a systemd service immediately in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-systemd.html",
        "points": 1,
        "answers": [
            {"text": "systemctl run", "is_correct": False},
            {"text": "systemctl start", "is_correct": True},
            {"text": "systemctl begin", "is_correct": False},
            {"text": "systemctl launch", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to reboot the system in SUSE Linux?",
        "explanation": "The 'reboot' command reboots the system in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-shutdown.html",
        "points": 1,
        "answers": [
            {"text": "shutdown -r", "is_correct": False},
            {"text": "reboot", "is_correct": True},
            {"text": "restart", "is_correct": False},
            {"text": "systemctl reboot", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to shut down the system in SUSE Linux?",
        "explanation": "The 'shutdown' command is used to halt or power off the system in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-shutdown.html",
        "points": 1,
        "answers": [
            {"text": "halt", "is_correct": False},
            {"text": "shutdown", "is_correct": True},
            {"text": "poweroff", "is_correct": False},
            {"text": "stop", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display the current kernel version in SUSE Linux?",
        "explanation": "The 'uname -r' command displays the current running kernel version in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-kernel.html",
        "points": 1,
        "answers": [
            {"text": "kernel", "is_correct": False},
            {"text": "uname -r", "is_correct": True},
            {"text": "version", "is_correct": False},
            {"text": "lsmod", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to list loaded kernel modules in SUSE Linux?",
        "explanation": "The 'lsmod' command lists all loaded kernel modules in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-kernel.html",
        "points": 1,
        "answers": [
            {"text": "modinfo", "is_correct": False},
            {"text": "lsmod", "is_correct": True},
            {"text": "insmod", "is_correct": False},
            {"text": "modprobe", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to load a kernel module in SUSE Linux?",
        "explanation": "The 'modprobe' command loads kernel modules in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-kernel.html",
        "points": 1,
        "answers": [
            {"text": "insmod", "is_correct": False},
            {"text": "modprobe", "is_correct": True},
            {"text": "lsmod", "is_correct": False},
            {"text": "modinfo", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display system uptime in SUSE Linux?",
        "explanation": "The 'uptime' command displays how long the system has been running and the current load averages in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-proc.html",
        "points": 1,
        "answers": [
            {"text": "runtime", "is_correct": False},
            {"text": "uptime", "is_correct": True},
            {"text": "load", "is_correct": False},
            {"text": "sysinfo", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display disk partitions in SUSE Linux?",
        "explanation": "The 'lsblk' command displays information about block devices and disk partitions in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-storage.html",
        "points": 1,
        "answers": [
            {"text": "fdisk", "is_correct": False},
            {"text": "lsblk", "is_correct": True},
            {"text": "blkid", "is_correct": False},
            {"text": "parted", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to partition disks in SUSE Linux?",
        "explanation": "The 'fdisk' command is used to create and modify disk partitions in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-storage.html",
        "points": 1,
        "answers": [
            {"text": "lsblk", "is_correct": False},
            {"text": "fdisk", "is_correct": True},
            {"text": "parted", "is_correct": False},
            {"text": "mkfs", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create a file system in SUSE Linux?",
        "explanation": "The 'mkfs' command creates a file system on a partition or disk in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-storage.html",
        "points": 1,
        "answers": [
            {"text": "format", "is_correct": False},
            {"text": "mkfs", "is_correct": True},
            {"text": "filesystem", "is_correct": False},
            {"text": "create-fs", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to mount a file system in SUSE Linux?",
        "explanation": "The 'mount' command attaches a file system to the directory tree in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-storage.html",
        "points": 1,
        "answers": [
            {"text": "attach", "is_correct": False},
            {"text": "mount", "is_correct": True},
            {"text": "connect", "is_correct": False},
            {"text": "link", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains file system mount information in SUSE Linux?",
        "explanation": "The /etc/fstab file contains file system mount information in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-storage.html",
        "points": 1,
        "answers": [
            {"text": "/etc/mtab", "is_correct": False},
            {"text": "/etc/fstab", "is_correct": True},
            {"text": "/etc/mounts", "is_correct": False},
            {"text": "/proc/mounts", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display file contents in SUSE Linux?",
        "explanation": "The 'cat' command displays the contents of files in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-files.html",
        "points": 1,
        "answers": [
            {"text": "less", "is_correct": False},
            {"text": "cat", "is_correct": True},
            {"text": "more", "is_correct": False},
            {"text": "view", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to search for text in files in SUSE Linux?",
        "explanation": "The 'grep' command searches for text patterns in files in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-files.html",
        "points": 1,
        "answers": [
            {"text": "find", "is_correct": False},
            {"text": "grep", "is_correct": True},
            {"text": "search", "is_correct": False},
            {"text": "awk", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display the current working directory in SUSE Linux?",
        "explanation": "The 'pwd' command prints the current working directory in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-files.html",
        "points": 1,
        "answers": [
            {"text": "cwd", "is_correct": False},
            {"text": "pwd", "is_correct": True},
            {"text": "dir", "is_correct": False},
            {"text": "whereami", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to copy files in SUSE Linux?",
        "explanation": "The 'cp' command copies files and directories in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-files.html",
        "points": 1,
        "answers": [
            {"text": "copy", "is_correct": False},
            {"text": "cp", "is_correct": True},
            {"text": "cpr", "is_correct": False},
            {"text": "duplicate", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to move files in SUSE Linux?",
        "explanation": "The 'mv' command moves or renames files and directories in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-files.html",
        "points": 1,
        "answers": [
            {"text": "move", "is_correct": False},
            {"text": "mv", "is_correct": True},
            {"text": "ren", "is_correct": False},
            {"text": "rename", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to remove files in SUSE Linux?",
        "explanation": "The 'rm' command removes files and directories in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-files.html",
        "points": 1,
        "answers": [
            {"text": "delete", "is_correct": False},
            {"text": "rm", "is_correct": True},
            {"text": "remove", "is_correct": False},
            {"text": "erase", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display the manual page for a command in SUSE Linux?",
        "explanation": "The 'man' command displays the manual page for a command in SUSE Linux.",
        "reference": "https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-manpages.html",
        "points": 1,
        "answers": [
            {"text": "help", "is_correct": False},
            {"text": "man", "is_correct": True},
            {"text": "info", "is_correct": False},
            {"text": "doc", "is_correct": False},
        ],
    },
]
