"""MySQL Database Administrator Certification"""

CERTIFICATION = {
    "name": "MySQL Database Administrator",
    "description": "MySQL database administration, optimization, and management skills",
    "slug": "mysql-database-administrator",
    "level": "Professional",
    "duration": 15,
    "questions_count": 5,
    "category_slug": "database",
    "is_active": True,
}

QUESTIONS = [{"text": "Which MySQL storage engine supports transactions?",
              "explanation": "InnoDB is MySQL's default storage engine that supports ACID transactions, foreign key constraints, and crash recovery, making it suitable for applications requiring data integrity.",
              "reference": "https://dev.mysql.com/doc/refman/8.0/en/innodb-storage-engine.html",
              "points": 1,
              "answers": [{"text": "InnoDB",
                           "is_correct": True},
                          {"text": "MyISAM",
                           "is_correct": False},
                          {"text": "MEMORY",
                           "is_correct": False},
                          {"text": "CSV",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of MySQL's binary log?",
              "explanation": "The binary log records all changes to the database and is used for replication and point-in-time recovery. It contains events that describe database changes such as table creation operations or changes to table data.",
              "reference": "https://dev.mysql.com/doc/refman/8.0/en/binary-log.html",
              "points": 1,
              "answers": [{"text": "Records database changes for replication and recovery",
                           "is_correct": True,
                           },
                          {"text": "Stores user authentication information",
                           "is_correct": False},
                          {"text": "Contains system configuration settings",
                           "is_correct": False},
                          {"text": "Logs error messages only",
                           "is_correct": False},
                          ],
              },
             {"text": "Which command is used to optimize a MySQL table?",
              "explanation": "OPTIMIZE TABLE reorganizes the physical storage of table data and associated index data to reduce storage space and improve I/O efficiency when accessing the table.",
              "reference": "https://dev.mysql.com/doc/refman/8.0/en/optimize-table.html",
              "points": 1,
              "answers": [{"text": "OPTIMIZE TABLE",
                           "is_correct": True},
                          {"text": "ANALYZE TABLE",
                           "is_correct": False},
                          {"text": "REPAIR TABLE",
                           "is_correct": False},
                          {"text": "CHECK TABLE",
                           "is_correct": False},
                          ],
              },
             {"text": "What is MySQL replication?",
              "explanation": "MySQL replication enables data from one MySQL database server (the master) to be copied to one or more MySQL database servers (the slaves), providing data redundancy, load distribution, and backup solutions.",
              "reference": "https://dev.mysql.com/doc/refman/8.0/en/replication.html",
              "points": 1,
              "answers": [{"text": "Copying data from master to one or more slave servers",
                           "is_correct": True,
                           },
                          {"text": "Creating database backups",
                           "is_correct": False},
                          {"text": "Encrypting database connections",
                           "is_correct": False},
                          {"text": "Compressing database files",
                           "is_correct": False},
                          ],
              },
             {"text": "Which MySQL configuration file parameter controls the maximum number of connections?",
              "explanation": "max_connections specifies the maximum permitted number of simultaneous client connections to the MySQL server. This is an important parameter for managing server resources and performance.",
              "reference": "https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_connections",
              "points": 1,
              "answers": [{"text": "max_connections",
                           "is_correct": True},
                          {"text": "max_users",
                           "is_correct": False},
                          {"text": "connection_limit",
                           "is_correct": False},
                          {"text": "max_sessions",
                           "is_correct": False},
                          ],
              },
             ]
