"""System Design Interview Preparation"""
from scripts.syllabus.syllabus.fundamentals.content import SYLLABUS_JSON

CERTIFICATION = {
    "name": "System Design Interview - Fundamentals",
    "description": "Fundamental concepts for system design interviews",
    "slug": "system-design-fundamentals",
    "level": "Intermediate",
    "duration": 6,
    "questions_count": 52,
    "category_slug": "system-design",
    "is_active": True,
    "benefits": "Master core system design principles\nLearn scalability patterns\nUnderstand distributed system concepts\nPrepare for technical interviews",
    "advantages": "Gain confidence in system design discussions and build a strong foundation for senior engineering roles.",
    "career_benefits": "Qualify for senior software engineer positions\nIncrease salary potential by 20-40%\nBuild expertise for system architect roles\nStand out in technical interviews",
    "teaching_eligibility": True,
    "min_score_for_teaching": 90,
    "min_score_for_certificate": 80,
    "syllabus": SYLLABUS_JSON,
}

QUESTIONS = [{"text": "What is horizontal scaling?",
              "explanation": "Horizontal scaling involves adding more servers to a system to handle increased load, rather than upgrading existing hardware.",
              "reference": "https://en.wikipedia.org/wiki/Scalability#Horizontal_(scale_out)_and_vertical_scaling_(scale_up)",
              "points": 1,
              "answers": [{"text": "Adding more powerful hardware to existing servers",
                           "is_correct": False,
                           },
                          {"text": "Adding more servers to the system",
                           "is_correct": True},
                          {"text": "Optimizing database queries",
                           "is_correct": False},
                          {"text": "Implementing caching mechanisms",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the CAP theorem?",
              "explanation": "The CAP theorem states that in a distributed system, you can only guarantee two of three properties: Consistency, Availability, and Partition tolerance.",
              "reference": "https://en.wikipedia.org/wiki/CAP_theorem",
              "points": 1,
              "answers": [{"text": "Consistency, Availability, Performance",
                           "is_correct": False},
                          {"text": "Consistency, Availability, Partition tolerance",
                           "is_correct": True,
                           },
                          {"text": "Caching, API design, Performance",
                           "is_correct": False},
                          {"text": "Concurrency, Algorithms, Protocols",
                           "is_correct": False},
                          ],
              },
             {"text": "What is vertical scaling?",
              "explanation": "Vertical scaling involves increasing the power of existing hardware by adding more CPU, RAM, or storage to handle increased load.",
              "reference": "https://en.wikipedia.org/wiki/Scalability#Horizontal_(scale_out)_and_vertical_scaling_(scale_up)",
              "points": 1,
              "answers": [{"text": "Adding more servers to the system",
                           "is_correct": False},
                          {"text": "Upgrading existing hardware with more resources",
                           "is_correct": True},
                          {"text": "Distributing load across multiple databases",
                           "is_correct": False},
                          {"text": "Implementing microservices architecture",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a load balancer?",
              "explanation": "A load balancer distributes incoming network traffic across multiple servers to ensure no single server becomes overwhelmed.",
              "reference": "https://en.wikipedia.org/wiki/Load_balancing_(computing)",
              "points": 1,
              "answers": [{"text": "A component that distributes traffic across multiple servers",
                           "is_correct": True},
                          {"text": "A database optimization tool",
                           "is_correct": False},
                          {"text": "A caching mechanism",
                           "is_correct": False},
                          {"text": "A monitoring system",
                           "is_correct": False},
                          ],
              },
             {"text": "What is database sharding?",
              "explanation": "Database sharding is a method of horizontally partitioning data across multiple databases to improve performance and scalability.",
              "reference": "https://en.wikipedia.org/wiki/Shard_(database_architecture)",
              "points": 1,
              "answers": [{"text": "Copying data to multiple databases for backup",
                           "is_correct": False},
                          {"text": "Horizontally partitioning data across multiple databases",
                           "is_correct": True},
                          {"text": "Compressing database files",
                           "is_correct": False},
                          {"text": "Indexing database tables",
                           "is_correct": False},
                          ],
              },
             {"text": "What is eventual consistency?",
              "explanation": "Eventual consistency guarantees that if no new updates are made to a distributed data store, eventually all replicas will converge to the same value.",
              "reference": "https://en.wikipedia.org/wiki/Eventual_consistency",
              "points": 1,
              "answers": [{"text": "Data is immediately consistent across all nodes",
                           "is_correct": False},
                          {"text": "Data becomes consistent across nodes over time",
                           "is_correct": True},
                          {"text": "Data is never consistent",
                           "is_correct": False},
                          {"text": "Data consistency is not guaranteed",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a CDN (Content Delivery Network)?",
              "explanation": "A CDN is a geographically distributed network of servers that deliver web content to users based on their location to improve performance.",
              "reference": "https://en.wikipedia.org/wiki/Content_delivery_network",
              "points": 1,
              "answers": [{"text": "A network of geographically distributed servers for content delivery",
                           "is_correct": True},
                          {"text": "A type of database cluster",
                           "is_correct": False},
                          {"text": "A load balancing algorithm",
                           "is_correct": False},
                          {"text": "A caching protocol",
                           "is_correct": False},
                          ],
              },
             {"text": "What is microservices architecture?",
              "explanation": "Microservices architecture structures an application as a collection of loosely coupled services that communicate over well-defined APIs.",
              "reference": "https://microservices.io/",
              "points": 1,
              "answers": [{"text": "A single large application deployed as one unit",
                           "is_correct": False},
                          {"text": "An application split into small, independent services",
                           "is_correct": True},
                          {"text": "A database design pattern",
                           "is_correct": False},
                          {"text": "A frontend framework",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of caching?",
              "explanation": "Caching stores frequently accessed data in a fast storage layer to reduce latency and improve system performance.",
              "reference": "https://en.wikipedia.org/wiki/Cache_(computing)",
              "points": 1,
              "answers": [{"text": "To permanently store data",
                           "is_correct": False},
                          {"text": "To improve performance by storing frequently accessed data",
                           "is_correct": True},
                          {"text": "To backup data",
                           "is_correct": False},
                          {"text": "To compress data",
                           "is_correct": False},
                          ],
              },
             {"text": "What is database replication?",
              "explanation": "Database replication involves copying and maintaining database objects in multiple databases to ensure availability and fault tolerance.",
              "reference": "https://en.wikipedia.org/wiki/Replication_(computing)",
              "points": 1,
              "answers": [{"text": "Creating a single backup copy",
                           "is_correct": False},
                          {"text": "Copying and maintaining data across multiple databases",
                           "is_correct": True},
                          {"text": "Compressing database files",
                           "is_correct": False},
                          {"text": "Optimizing query performance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is API rate limiting?",
              "explanation": "API rate limiting controls the number of requests a client can make to an API within a specific time period to prevent abuse and ensure fair usage.",
              "reference": "https://en.wikipedia.org/wiki/Rate_limiting",
              "points": 1,
              "answers": [{"text": "Controlling the number of API requests per time period",
                           "is_correct": True},
                          {"text": "Optimizing API response time",
                           "is_correct": False},
                          {"text": "Compressing API responses",
                           "is_correct": False},
                          {"text": "Encrypting API data",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a message queue?",
              "explanation": "A message queue is a communication method that allows applications to communicate asynchronously by storing messages in a queue until they are processed.",
              "reference": "https://en.wikipedia.org/wiki/Message_queue",
              "points": 1,
              "answers": [{"text": "A synchronous communication protocol",
                           "is_correct": False},
                          {"text": "An asynchronous communication mechanism using queues",
                           "is_correct": True},
                          {"text": "A type of database",
                           "is_correct": False},
                          {"text": "A caching system",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between SQL and NoSQL databases?",
              "explanation": "SQL databases are relational with structured schemas and ACID properties, while NoSQL databases are non-relational with flexible schemas and eventual consistency.",
              "reference": "https://en.wikipedia.org/wiki/NoSQL",
              "points": 1,
              "answers": [{"text": "SQL is faster than NoSQL",
                           "is_correct": False},
                          {"text": "SQL is relational with fixed schemas, NoSQL is non-relational with flexible schemas",
                           "is_correct": True},
                          {"text": "NoSQL doesn't support queries",
                           "is_correct": False},
                          {"text": "SQL is only for small applications",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a reverse proxy?",
              "explanation": "A reverse proxy acts as an intermediary for requests from clients seeking resources from servers, typically used for load balancing and SSL termination.",
              "reference": "https://en.wikipedia.org/wiki/Reverse_proxy",
              "points": 1,
              "answers": [{"text": "A server that forwards client requests to backend servers",
                           "is_correct": True},
                          {"text": "A client-side caching mechanism",
                           "is_correct": False},
                          {"text": "A database connection pool",
                           "is_correct": False},
                          {"text": "A monitoring tool",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of database indexing?",
              "explanation": "Database indexing creates data structures that improve the speed of data retrieval operations on a database table at the cost of additional storage space.",
              "reference": "https://en.wikipedia.org/wiki/Database_index",
              "points": 1,
              "answers": [{"text": "To compress database data",
                           "is_correct": False},
                          {"text": "To improve query performance",
                           "is_correct": True},
                          {"text": "To backup database data",
                           "is_correct": False},
                          {"text": "To encrypt sensitive data",
                           "is_correct": False},
                          ],
              },
             {"text": "What is session management?",
              "explanation": "Session management tracks user interactions across multiple requests, maintaining state information between HTTP requests in stateless protocols.",
              "reference": "https://en.wikipedia.org/wiki/Session_(computer_science)",
              "points": 1,
              "answers": [{"text": "Managing user authentication across requests",
                           "is_correct": True},
                          {"text": "Optimizing database connections",
                           "is_correct": False},
                          {"text": "Compressing network traffic",
                           "is_correct": False},
                          {"text": "Monitoring system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is data partitioning?",
              "explanation": "Data partitioning divides large datasets into smaller, more manageable segments to improve performance, scalability, and manageability.",
              "reference": "https://en.wikipedia.org/wiki/Partition_(database)",
              "points": 1,
              "answers": [{"text": "Dividing data into smaller, manageable segments",
                           "is_correct": True},
                          {"text": "Encrypting sensitive data",
                           "is_correct": False},
                          {"text": "Compressing large files",
                           "is_correct": False},
                          {"text": "Creating data backups",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of a circuit breaker pattern?",
              "explanation": "The circuit breaker pattern prevents a system from repeatedly trying to execute operations that are likely to fail, providing resilience in distributed systems.",
              "reference": "https://martinfowler.com/bliki/CircuitBreaker.html",
              "points": 1,
              "answers": [{"text": "To prevent repeated execution of likely-to-fail operations",
                           "is_correct": True},
                          {"text": "To optimize database queries",
                           "is_correct": False},
                          {"text": "To compress network traffic",
                           "is_correct": False},
                          {"text": "To encrypt data transmission",
                           "is_correct": False},
                          ],
              },
             {"text": "What is database normalization?",
              "explanation": "Database normalization is the process of organizing data to reduce redundancy and improve data integrity by dividing tables into smaller, related tables.",
              "reference": "https://en.wikipedia.org/wiki/Database_normalization",
              "points": 1,
              "answers": [{"text": "Organizing data to reduce redundancy",
                           "is_correct": True},
                          {"text": "Compressing database files",
                           "is_correct": False},
                          {"text": "Creating database backups",
                           "is_correct": False},
                          {"text": "Encrypting sensitive data",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between synchronous and asynchronous communication?",
              "explanation": "Synchronous communication requires the sender to wait for a response, while asynchronous communication allows the sender to continue without waiting.",
              "reference": "https://en.wikipedia.org/wiki/Asynchronous_communication",
              "points": 1,
              "answers": [{"text": "Synchronous waits for response, asynchronous doesn't",
                           "is_correct": True},
                          {"text": "Asynchronous is faster than synchronous",
                           "is_correct": False},
                          {"text": "Synchronous uses more bandwidth",
                           "is_correct": False},
                          {"text": "They are the same thing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is auto-scaling?",
              "explanation": "Auto-scaling automatically adjusts computing resources based on demand to maintain performance while optimizing costs.",
              "reference": "https://en.wikipedia.org/wiki/Autoscaling",
              "points": 1,
              "answers": [{"text": "Automatically adjusting resources based on demand",
                           "is_correct": True},
                          {"text": "Manual resource allocation",
                           "is_correct": False},
                          {"text": "Fixed resource allocation",
                           "is_correct": False},
                          {"text": "Resource deallocation only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a distributed hash table (DHT)?",
              "explanation": "A DHT is a decentralized distributed system that provides a lookup service similar to a hash table, where key-value pairs are stored across multiple nodes.",
              "reference": "https://en.wikipedia.org/wiki/Distributed_hash_table",
              "points": 1,
              "answers": [{"text": "A centralized hash table",
                           "is_correct": False},
                          {"text": "A decentralized system for storing key-value pairs across nodes",
                           "is_correct": True},
                          {"text": "A type of database index",
                           "is_correct": False},
                          {"text": "A caching mechanism",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of a health check?",
              "explanation": "Health checks monitor the status of services and infrastructure components to ensure they are functioning properly and available.",
              "reference": "https://en.wikipedia.org/wiki/Health_check",
              "points": 1,
              "answers": [{"text": "To monitor service status and availability",
                           "is_correct": True},
                          {"text": "To optimize database performance",
                           "is_correct": False},
                          {"text": "To compress network traffic",
                           "is_correct": False},
                          {"text": "To encrypt data transmission",
                           "is_correct": False},
                          ],
              },
             {"text": "What is database connection pooling?",
              "explanation": "Connection pooling maintains a cache of database connections that can be reused across multiple requests to improve performance and resource utilization.",
              "reference": "https://en.wikipedia.org/wiki/Connection_pool",
              "points": 1,
              "answers": [{"text": "Creating a new connection for each request",
                           "is_correct": False},
                          {"text": "Reusing database connections across multiple requests",
                           "is_correct": True},
                          {"text": "Compressing database queries",
                           "is_correct": False},
                          {"text": "Encrypting database connections",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between stateful and stateless services?",
              "explanation": "Stateful services retain client information between requests, while stateless services treat each request independently without storing client context.",
              "reference": "https://en.wikipedia.org/wiki/Stateless_protocol",
              "points": 1,
              "answers": [{"text": "Stateful retains client information, stateless doesn't",
                           "is_correct": True},
                          {"text": "Stateless is slower than stateful",
                           "is_correct": False},
                          {"text": "They are the same thing",
                           "is_correct": False},
                          {"text": "Stateful uses more memory always",
                           "is_correct": False},
                          ],
              },
             {"text": "What is data consistency?",
              "explanation": "Data consistency ensures that all nodes in a distributed system have the same data at the same time, maintaining data integrity across the system.",
              "reference": "https://en.wikipedia.org/wiki/Consistency_(database_systems)",
              "points": 1,
              "answers": [{"text": "All nodes have the same data at the same time",
                           "is_correct": True},
                          {"text": "Data is compressed efficiently",
                           "is_correct": False},
                          {"text": "Data is encrypted properly",
                           "is_correct": False},
                          {"text": "Data is backed up regularly",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a single point of failure?",
              "explanation": "A single point of failure is a component in a system whose failure would cause the entire system to stop working, representing a critical vulnerability.",
              "reference": "https://en.wikipedia.org/wiki/Single_point_of_failure",
              "points": 1,
              "answers": [{"text": "A component whose failure causes system failure",
                           "is_correct": True},
                          {"text": "A performance bottleneck",
                           "is_correct": False},
                          {"text": "A security vulnerability",
                           "is_correct": False},
                          {"text": "A slow database query",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of service discovery?",
              "explanation": "Service discovery allows services in a distributed system to find and communicate with each other without hardcoded network locations.",
              "reference": "https://en.wikipedia.org/wiki/Service_discovery",
              "points": 1,
              "answers": [{"text": "To find and communicate with services dynamically",
                           "is_correct": True},
                          {"text": "To monitor service performance",
                           "is_correct": False},
                          {"text": "To encrypt service communication",
                           "is_correct": False},
                          {"text": "To compress network traffic",
                           "is_correct": False},
                          ],
              },
             {"text": "What is database denormalization?",
              "explanation": "Database denormalization intentionally introduces redundancy to improve read performance by reducing the number of joins required in queries.",
              "reference": "https://en.wikipedia.org/wiki/Denormalization",
              "points": 1,
              "answers": [{"text": "Introducing redundancy to improve read performance",
                           "is_correct": True},
                          {"text": "Removing all redundancy from data",
                           "is_correct": False},
                          {"text": "Encrypting database tables",
                           "is_correct": False},
                          {"text": "Compressing database files",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of a proxy server?",
              "explanation": "A proxy server acts as an intermediary between clients and servers, often used for caching, security, load balancing, or anonymity.",
              "reference": "https://en.wikipedia.org/wiki/Proxy_server",
              "points": 1,
              "answers": [{"text": "Acts as an intermediary between clients and servers",
                           "is_correct": True},
                          {"text": "Stores data permanently",
                           "is_correct": False},
                          {"text": "Encrypts all network traffic",
                           "is_correct": False},
                          {"text": "Monitors system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is eventual consistency in distributed systems?",
              "explanation": "Eventual consistency guarantees that if no new updates are made, all replicas will eventually converge to the same state, allowing temporary inconsistencies.",
              "reference": "https://en.wikipedia.org/wiki/Eventual_consistency",
              "points": 1,
              "answers": [{"text": "Immediate consistency across all nodes",
                           "is_correct": False},
                          {"text": "Consistency achieved over time without new updates",
                           "is_correct": True},
                          {"text": "No consistency guarantees",
                           "is_correct": False},
                          {"text": "Manual consistency maintenance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of data compression?",
              "explanation": "Data compression reduces the size of data to save storage space and reduce transmission time while maintaining the essential information.",
              "reference": "https://en.wikipedia.org/wiki/Data_compression",
              "points": 1,
              "answers": [{"text": "To reduce data size and transmission time",
                           "is_correct": True},
                          {"text": "To encrypt sensitive data",
                           "is_correct": False},
                          {"text": "To improve data security",
                           "is_correct": False},
                          {"text": "To backup data automatically",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a distributed transaction?",
              "explanation": "A distributed transaction is a transaction that involves multiple databases or services and must maintain ACID properties across all participants.",
              "reference": "https://en.wikipedia.org/wiki/Distributed_transaction",
              "points": 1,
              "answers": [{"text": "A transaction involving multiple databases or services",
                           "is_correct": True},
                          {"text": "A single database transaction",
                           "is_correct": False},
                          {"text": "A read-only operation",
                           "is_correct": False},
                          {"text": "A caching mechanism",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of monitoring in distributed systems?",
              "explanation": "Monitoring tracks system performance, health, and behavior to detect issues, optimize performance, and ensure reliability in distributed systems.",
              "reference": "https://en.wikipedia.org/wiki/Application_performance_monitoring",
              "points": 1,
              "answers": [{"text": "To track system performance and detect issues",
                           "is_correct": True},
                          {"text": "To compress network traffic",
                           "is_correct": False},
                          {"text": "To encrypt data transmission",
                           "is_correct": False},
                          {"text": "To backup system data",
                           "is_correct": False},
                          ],
              },
             {"text": "What is idempotency in API design?",
              "explanation": "Idempotency ensures that making the same API request multiple times has the same effect as making it once, providing reliability in distributed systems.",
              "reference": "https://en.wikipedia.org/wiki/Idempotence",
              "points": 1,
              "answers": [{"text": "Making the same request multiple times has the same effect",
                           "is_correct": True},
                          {"text": "Each request must be unique",
                           "is_correct": False},
                          {"text": "Requests are processed in order",
                           "is_correct": False},
                          {"text": "Requests are encrypted automatically",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between ACID and BASE properties?",
              "explanation": "ACID (Atomicity, Consistency, Isolation, Durability) ensures strict consistency, while BASE (Basically Available, Soft state, Eventual consistency) allows for more flexibility.",
              "reference": "https://en.wikipedia.org/wiki/ACID",
              "points": 1,
              "answers": [{"text": "ACID ensures strict consistency, BASE allows flexibility",
                           "is_correct": True},
                          {"text": "BASE is faster than ACID",
                           "is_correct": False},
                          {"text": "ACID is only for NoSQL databases",
                           "is_correct": False},
                          {"text": "They are the same thing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a consensus algorithm?",
              "explanation": "A consensus algorithm ensures that multiple nodes in a distributed system agree on a single value or state, even in the presence of failures.",
              "reference": "https://en.wikipedia.org/wiki/Consensus_(computer_science)",
              "points": 1,
              "answers": [{"text": "An algorithm for nodes to agree on a single value",
                           "is_correct": True},
                          {"text": "A load balancing algorithm",
                           "is_correct": False},
                          {"text": "A caching strategy",
                           "is_correct": False},
                          {"text": "A compression algorithm",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of graceful degradation?",
              "explanation": "Graceful degradation allows a system to continue operating with reduced functionality when some components fail, maintaining core services.",
              "reference": "https://en.wikipedia.org/wiki/Graceful_degradation",
              "points": 1,
              "answers": [{"text": "Continuing operation with reduced functionality during failures",
                           "is_correct": True},
                          {"text": "Completely shutting down during failures",
                           "is_correct": False},
                          {"text": "Ignoring all errors",
                           "is_correct": False},
                          {"text": "Preventing all failures",
                           "is_correct": False},
                          ],
              },
             {"text": "What is data locality?",
              "explanation": "Data locality refers to keeping data close to where it's being processed to minimize latency and improve performance in distributed systems.",
              "reference": "https://en.wikipedia.org/wiki/Locality_of_reference",
              "points": 1,
              "answers": [{"text": "Keeping data close to where it's processed",
                           "is_correct": True},
                          {"text": "Distributing data randomly across nodes",
                           "is_correct": False},
                          {"text": "Centralizing all data in one location",
                           "is_correct": False},
                          {"text": "Encrypting data based on location",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of API versioning?",
              "explanation": "API versioning allows multiple versions of an API to coexist, enabling backward compatibility while introducing new features or changes.",
              "reference": "https://en.wikipedia.org/wiki/Software_versioning",
              "points": 1,
              "answers": [{"text": "Allowing multiple API versions to coexist for compatibility",
                           "is_correct": True},
                          {"text": "Encrypting API responses",
                           "is_correct": False},
                          {"text": "Compressing API data",
                           "is_correct": False},
                          {"text": "Monitoring API performance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is horizontal partitioning (sharding) vs vertical partitioning?",
              "explanation": "Horizontal partitioning splits rows across multiple tables/databases, while vertical partitioning splits columns, each optimizing for different access patterns.",
              "reference": "https://en.wikipedia.org/wiki/Partition_(database)",
              "points": 1,
              "answers": [{"text": "Horizontal splits rows, vertical splits columns",
                           "is_correct": True},
                          {"text": "Horizontal splits columns, vertical splits rows",
                           "is_correct": False},
                          {"text": "Both split rows the same way",
                           "is_correct": False},
                          {"text": "Both split columns the same way",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the role of a message broker?",
              "explanation": "A message broker facilitates communication between distributed applications by receiving, routing, and delivering messages between producers and consumers.",
              "reference": "https://en.wikipedia.org/wiki/Message_broker",
              "points": 1,
              "answers": [{"text": "Facilitating communication between distributed applications",
                           "is_correct": True},
                          {"text": "Storing data permanently",
                           "is_correct": False},
                          {"text": "Encrypting network traffic",
                           "is_correct": False},
                          {"text": "Monitoring system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between latency and throughput?",
              "explanation": "Latency is the time taken to process a single request, while throughput is the number of requests that can be processed in a given time period.",
              "reference": "https://en.wikipedia.org/wiki/Latency_(engineering)",
              "points": 1,
              "answers": [{"text": "Latency is time per request, throughput is requests per time",
                           "is_correct": True},
                          {"text": "They measure the same thing",
                           "is_correct": False},
                          {"text": "Latency is requests per time, throughput is time per request",
                           "is_correct": False},
                          {"text": "Both measure storage capacity",
                           "is_correct": False},
                          ],
              },
             {"text": "What is fault tolerance?",
              "explanation": "Fault tolerance is the ability of a system to continue operating properly in the event of failure of some of its components.",
              "reference": "https://en.wikipedia.org/wiki/Fault_tolerance",
              "points": 1,
              "answers": [{"text": "The ability to continue operating despite component failures",
                           "is_correct": True},
                          {"text": "Preventing all system failures",
                           "is_correct": False},
                          {"text": "Monitoring system performance",
                           "is_correct": False},
                          {"text": "Optimizing system speed",
                           "is_correct": False},
                          ],
              },
             {"text": "What is data replication lag?",
              "explanation": "Data replication lag is the time delay between when data is written to a primary database and when it appears in replica databases.",
              "reference": "https://en.wikipedia.org/wiki/Replication_lag",
              "points": 1,
              "answers": [{"text": "Time delay between primary write and replica availability",
                           "is_correct": True},
                          {"text": "Time to backup data",
                           "is_correct": False},
                          {"text": "Network latency between servers",
                           "is_correct": False},
                          {"text": "Database query execution time",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of containerization?",
              "explanation": "Containerization packages applications with their dependencies into lightweight, portable containers that can run consistently across different environments.",
              "reference": "https://en.wikipedia.org/wiki/Containerization_(computing)",
              "points": 1,
              "answers": [{"text": "Packaging applications with dependencies for portability",
                           "is_correct": True},
                          {"text": "Compressing application files",
                           "is_correct": False},
                          {"text": "Encrypting application data",
                           "is_correct": False},
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is blue-green deployment?",
              "explanation": "Blue-green deployment is a technique that reduces downtime by running two identical production environments and switching between them during deployment.",
              "reference": "https://martinfowler.com/bliki/BlueGreenDeployment.html",
              "points": 1,
              "answers": [{"text": "Running two identical environments and switching between them",
                           "is_correct": True},
                          {"text": "Using blue and green colors for UI themes",
                           "is_correct": False},
                          {"text": "A type of load balancing algorithm",
                           "is_correct": False},
                          {"text": "A database backup strategy",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between a monolith and microservices?",
              "explanation": "A monolith is a single deployable unit containing all functionality, while microservices split functionality into small, independent services that communicate over networks.",
              "reference": "https://microservices.io/patterns/monolithic.html",
              "points": 1,
              "answers": [{"text": "Monolith is one unit, microservices are multiple independent services",
                           "is_correct": True},
                          {"text": "Microservices are always faster than monoliths",
                           "is_correct": False},
                          {"text": "Monoliths can't scale horizontally",
                           "is_correct": False},
                          {"text": "They are the same architecture pattern",
                           "is_correct": False},
                          ],
              },
             ]
