"""High-Performance System Architecture Certification"""

CERTIFICATION = {
    "name": "High-Performance System Architecture",
    "description": "Designing and implementing high-performance, scalable systems",
    "slug": "high-performance-system-architecture",
    "level": "Expert",
    "duration": 3,
    "questions_count": 55,
    "category_slug": "system-design",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is the primary benefit of using a Content Delivery Network (CDN)?",
        "explanation": "CDNs reduce latency by serving content from geographically distributed edge locations closer to users.",
        "reference": "https://en.wikipedia.org/wiki/Content_delivery_network",
        "points": 1,
        "answers": [
            {"text": "Increased security", "is_correct": False},
            {"text": "Reduced latency and improved performance", "is_correct": True},
            {"text": "Better SEO rankings", "is_correct": False},
            {"text": "Lower storage costs", "is_correct": False},
        ],
    },
    {
        "text": "Which load balancing algorithm distributes requests evenly across all available servers?",
        "explanation": "Round-robin algorithm distributes requests sequentially to each server in the pool, ensuring even distribution of load.",
        "reference": "https://en.wikipedia.org/wiki/Round-robin_scheduling",
        "points": 1,
        "answers": [
            {"text": "Least connections", "is_correct": False},
            {"text": "Round-robin", "is_correct": True},
            {"text": "Weighted response time", "is_correct": False},
            {"text": "IP hash", "is_correct": False},
        ],
    },
    {
        "text": "What is horizontal scaling also known as?",
        "explanation": "Horizontal scaling involves adding more servers to the system, also called scaling out.",
        "reference": "https://en.wikipedia.org/wiki/Scalability#Horizontal_and_vertical_scaling",
        "points": 1,
        "answers": [
            {"text": "Scaling up", "is_correct": False},
            {"text": "Scaling out", "is_correct": True},
            {"text": "Vertical scaling", "is_correct": False},
            {"text": "Linear scaling", "is_correct": False},
        ],
    },
    {
        "text": "Which caching strategy writes to both cache and database simultaneously?",
        "explanation": "Write-through caching writes data to both the cache and the backing store simultaneously, ensuring data consistency.",
        "reference": "https://en.wikipedia.org/wiki/Cache_(computing)#Writing_policies",
        "points": 1,
        "answers": [
            {"text": "Write-behind", "is_correct": False},
            {"text": "Write-around", "is_correct": False},
            {"text": "Write-through", "is_correct": True},
            {"text": "Write-back", "is_correct": False},
        ],
    },
    {
        "text": "What is the CAP theorem in distributed systems?",
        "explanation": "CAP theorem states that distributed systems can guarantee at most two of: Consistency, Availability, and Partition tolerance.",
        "reference": "https://en.wikipedia.org/wiki/CAP_theorem",
        "points": 1,
        "answers": [
            {"text": "Capacity, Availability, Performance", "is_correct": False},
            {"text": "Consistency, Availability, Partition tolerance", "is_correct": True},
            {"text": "Concurrency, Authentication, Privacy", "is_correct": False},
            {"text": "Caching, API, Performance", "is_correct": False},
        ],
    },
    {
        "text": "Which database sharding technique distributes data based on a hash function?",
        "explanation": "Hash-based sharding uses a hash function on the shard key to determine which shard stores the data.",
        "reference": "https://en.wikipedia.org/wiki/Shard_(database_architecture)",
        "points": 1,
        "answers": [
            {"text": "Range-based sharding", "is_correct": False},
            {"text": "Directory-based sharding", "is_correct": False},
            {"text": "Hash-based sharding", "is_correct": True},
            {"text": "Geographic sharding", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of a circuit breaker pattern in microservices?",
        "explanation": "Circuit breaker prevents cascading failures by stopping calls to a failing service temporarily.",
        "reference": "https://martinfowler.com/bliki/CircuitBreaker.html",
        "points": 1,
        "answers": [
            {"text": "Load balancing", "is_correct": False},
            {"text": "Data encryption", "is_correct": False},
            {"text": "Preventing cascading failures", "is_correct": True},
            {"text": "Session management", "is_correct": False},
        ],
    },
    {
        "text": "Which NoSQL database type is optimized for key-value pairs?",
        "explanation": "Key-value stores like Redis and DynamoDB are optimized for simple key-value data access patterns.",
        "reference": "https://en.wikipedia.org/wiki/Key%E2%80%93value_database",
        "points": 1,
        "answers": [
            {"text": "Document database", "is_correct": False},
            {"text": "Column-family", "is_correct": False},
            {"text": "Graph database", "is_correct": False},
            {"text": "Key-value store", "is_correct": True},
        ],
    },
    {
        "text": "What is the main advantage of using async/non-blocking I/O?",
        "explanation": "Async I/O allows a single thread to handle multiple I/O operations concurrently, improving throughput.",
        "reference": "https://en.wikipedia.org/wiki/Asynchronous_I/O",
        "points": 1,
        "answers": [
            {"text": "Better security", "is_correct": False},
            {"text": "Higher throughput with fewer threads", "is_correct": True},
            {"text": "Simplified code structure", "is_correct": False},
            {"text": "Reduced memory usage", "is_correct": False},
        ],
    },
    {
        "text": "Which technique helps reduce database load by serving frequently accessed data from memory?",
        "explanation": "Caching stores frequently accessed data in memory for fast retrieval, reducing database load.",
        "reference": "https://en.wikipedia.org/wiki/Cache_(computing)",
        "points": 1,
        "answers": [
            {"text": "Indexing", "is_correct": False},
            {"text": "Partitioning", "is_correct": False},
            {"text": "Caching", "is_correct": True},
            {"text": "Replication", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of database connection pooling?",
        "explanation": "Connection pooling reuses database connections to reduce the overhead of creating new connections for each request.",
        "reference": "https://en.wikipedia.org/wiki/Connection_pool",
        "points": 1,
        "answers": [
            {"text": "Data encryption", "is_correct": False},
            {"text": "Reducing connection overhead", "is_correct": True},
            {"text": "Query optimization", "is_correct": False},
            {"text": "Schema validation", "is_correct": False},
        ],
    },
    {
        "text": "Which pattern allows services to communicate asynchronously through messages?",
        "explanation": "Message queues enable asynchronous communication between services by decoupling producers and consumers.",
        "reference": "https://en.wikipedia.org/wiki/Message_queue",
        "points": 1,
        "answers": [
            {"text": "Message queues", "is_correct": True},
            {"text": "REST APIs", "is_correct": False},
            {"text": "GraphQL", "is_correct": False},
            {"text": "RPC calls", "is_correct": False},
        ],
    },
    {
        "text": "What is eventual consistency in distributed systems?",
        "explanation": "Eventual consistency means the system will become consistent over time, but may be temporarily inconsistent.",
        "reference": "https://en.wikipedia.org/wiki/Eventual_consistency",
        "points": 1,
        "answers": [
            {"text": "Immediate consistency across all nodes", "is_correct": False},
            {"text": "Consistency achieved over time", "is_correct": True},
            {"text": "No consistency guarantees", "is_correct": False},
            {"text": "Consistency only during writes", "is_correct": False},
        ],
    },
    {
        "text": "Which technique improves read performance by maintaining multiple copies of data?",
        "explanation": "Database replication creates multiple copies of data across different servers to improve read performance and availability.",
        "reference": "https://en.wikipedia.org/wiki/Replication_(computing)",
        "points": 1,
        "answers": [
            {"text": "Sharding", "is_correct": False},
            {"text": "Indexing", "is_correct": False},
            {"text": "Replication", "is_correct": True},
            {"text": "Partitioning", "is_correct": False},
        ],
    },
    {
        "text": "What is the main benefit of using microservices architecture for high-performance systems?",
        "explanation": "Microservices allow independent scaling of different components based on their specific load requirements.",
        "reference": "https://martinfowler.com/articles/microservices.html",
        "points": 1,
        "answers": [
            {"text": "Simpler deployment", "is_correct": False},
            {"text": "Independent scaling", "is_correct": True},
            {"text": "Reduced code complexity", "is_correct": False},
            {"text": "Better security", "is_correct": False},
        ],
    },
    {
        "text": "Which HTTP method is idempotent and safe for caching?",
        "explanation": "GET requests are idempotent (multiple calls have the same effect) and safe (don't modify server state), making them ideal for caching.",
        "reference": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods",
        "points": 1,
        "answers": [
            {"text": "POST", "is_correct": False},
            {"text": "PUT", "is_correct": False},
            {"text": "DELETE", "is_correct": False},
            {"text": "GET", "is_correct": True},
        ],
    },
    {
        "text": "What is the purpose of a reverse proxy in high-performance architectures?",
        "explanation": "Reverse proxies act as intermediaries for requests, providing load balancing, SSL termination, and caching.",
        "reference": "https://en.wikipedia.org/wiki/Reverse_proxy",
        "points": 1,
        "answers": [
            {"text": "Client-side caching", "is_correct": False},
            {"text": "Load balancing and SSL termination", "is_correct": True},
            {"text": "Database optimization", "is_correct": False},
            {"text": "Code compilation", "is_correct": False},
        ],
    },
    {
        "text": "Which data structure is most efficient for implementing a cache with LRU eviction?",
        "explanation": "A combination of HashMap and Doubly Linked List provides O(1) access and O(1) LRU eviction.",
        "reference": "https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)",
        "points": 1,
        "answers": [
            {"text": "Array", "is_correct": False},
            {"text": "Binary tree", "is_correct": False},
            {"text": "HashMap + Doubly Linked List", "is_correct": True},
            {"text": "Stack", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between vertical and horizontal partitioning?",
        "explanation": "Vertical partitioning splits tables by columns, while horizontal partitioning splits by rows (sharding).",
        "reference": "https://en.wikipedia.org/wiki/Partition_(database)",
        "points": 1,
        "answers": [
            {"text": "Vertical splits by rows, horizontal by columns", "is_correct": False},
            {"text": "Vertical splits by columns, horizontal by rows", "is_correct": True},
            {"text": "Both split by rows", "is_correct": False},
            {"text": "Both split by columns", "is_correct": False},
        ],
    },
    {
        "text": "Which technique helps prevent the 'thundering herd' problem in caching?",
        "explanation": "Cache warming preloads frequently accessed data, preventing multiple simultaneous cache misses.",
        "reference": "https://en.wikipedia.org/wiki/Cache_stampede",
        "points": 1,
        "answers": [
            {"text": "Cache invalidation", "is_correct": False},
            {"text": "Cache warming", "is_correct": True},
            {"text": "Cache partitioning", "is_correct": False},
            {"text": "Cache compression", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of database indexing in performance optimization?",
        "explanation": "Indexes create data structures that allow faster query execution by avoiding full table scans.",
        "reference": "https://en.wikipedia.org/wiki/Database_index",
        "points": 1,
        "answers": [
            {"text": "Data compression", "is_correct": False},
            {"text": "Faster query execution", "is_correct": True},
            {"text": "Data encryption", "is_correct": False},
            {"text": "Storage reduction", "is_correct": False},
        ],
    },
    {
        "text": "Which protocol is most efficient for real-time communication?",
        "explanation": "WebSockets provide full-duplex communication over a single TCP connection, ideal for real-time applications.",
        "reference": "https://en.wikipedia.org/wiki/WebSocket",
        "points": 1,
        "answers": [
            {"text": "HTTP polling", "is_correct": False},
            {"text": "WebSockets", "is_correct": True},
            {"text": "FTP", "is_correct": False},
            {"text": "SMTP", "is_correct": False},
        ],
    },
    {
        "text": "What is the main advantage of using stateless services?",
        "explanation": "Stateless services can be easily scaled horizontally since they don't maintain server-side state between requests.",
        "reference": "https://en.wikipedia.org/wiki/Stateless_protocol",
        "points": 1,
        "answers": [
            {"text": "Better security", "is_correct": False},
            {"text": "Easier horizontal scaling", "is_correct": True},
            {"text": "Faster processing", "is_correct": False},
            {"text": "Lower memory usage", "is_correct": False},
        ],
    },
    {
        "text": "Which technique reduces latency by processing data closer to the source?",
        "explanation": "Edge computing processes data at edge locations closer to users, reducing latency and bandwidth usage.",
        "reference": "https://en.wikipedia.org/wiki/Edge_computing",
        "points": 1,
        "answers": [
            {"text": "Cloud computing", "is_correct": False},
            {"text": "Edge computing", "is_correct": True},
            {"text": "Grid computing", "is_correct": False},
            {"text": "Quantum computing", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of rate limiting in high-performance systems?",
        "explanation": "Rate limiting controls the number of requests to prevent system overload and ensure fair resource usage.",
        "reference": "https://en.wikipedia.org/wiki/Rate_limiting",
        "points": 1,
        "answers": [
            {"text": "Data compression", "is_correct": False},
            {"text": "Preventing system overload", "is_correct": True},
            {"text": "Improving security", "is_correct": False},
            {"text": "Reducing storage costs", "is_correct": False},
        ],
    },
    {
        "text": "Which pattern helps handle failures gracefully in distributed systems?",
        "explanation": "Bulkhead pattern isolates critical resources to prevent failures in one area from affecting others.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead",
        "points": 1,
        "answers": [
            {"text": "Singleton pattern", "is_correct": False},
            {"text": "Observer pattern", "is_correct": False},
            {"text": "Bulkhead pattern", "is_correct": True},
            {"text": "Factory pattern", "is_correct": False},
        ],
    },
    {
        "text": "What is the main benefit of using immutable data structures in concurrent systems?",
        "explanation": "Immutable data structures eliminate race conditions and reduce the need for locks in concurrent environments.",
        "reference": "https://en.wikipedia.org/wiki/Immutable_object",
        "points": 1,
        "answers": [
            {"text": "Reduced memory usage", "is_correct": False},
            {"text": "Thread safety without locks", "is_correct": True},
            {"text": "Faster processing", "is_correct": False},
            {"text": "Better compression", "is_correct": False},
        ],
    },
    {
        "text": "Which caching strategy is best for write-heavy workloads?",
        "explanation": "Write-behind (lazy write) caching improves write performance by batching writes to the backing store.",
        "reference": "https://en.wikipedia.org/wiki/Cache_(computing)#Writing_policies",
        "points": 1,
        "answers": [
            {"text": "Write-through", "is_correct": False},
            {"text": "Write-around", "is_correct": False},
            {"text": "Write-behind", "is_correct": True},
            {"text": "Read-through", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of connection multiplexing in HTTP/2?",
        "explanation": "Connection multiplexing allows multiple requests/responses to be sent concurrently over a single connection.",
        "reference": "https://en.wikipedia.org/wiki/HTTP/2",
        "points": 1,
        "answers": [
            {"text": "Data compression", "is_correct": False},
            {"text": "Multiple concurrent streams", "is_correct": True},
            {"text": "Better security", "is_correct": False},
            {"text": "Reduced bandwidth", "is_correct": False},
        ],
    },
    {
        "text": "Which technique helps reduce database query time by storing computed results?",
        "explanation": "Materialized views store precomputed query results, reducing query execution time for complex operations.",
        "reference": "https://en.wikipedia.org/wiki/Materialized_view",
        "points": 1,
        "answers": [
            {"text": "Normalization", "is_correct": False},
            {"text": "Materialized views", "is_correct": True},
            {"text": "Triggers", "is_correct": False},
            {"text": "Foreign keys", "is_correct": False},
        ],
    },
    {
        "text": "What is the main advantage of using a message broker like RabbitMQ or Kafka?",
        "explanation": "Message brokers provide reliable, asynchronous communication and decouple services for better scalability.",
        "reference": "https://en.wikipedia.org/wiki/Message_broker",
        "points": 1,
        "answers": [
            {"text": "Faster processing", "is_correct": False},
            {"text": "Service decoupling and reliability", "is_correct": True},
            {"text": "Data compression", "is_correct": False},
            {"text": "Better security", "is_correct": False},
        ],
    },
    {
        "text": "Which load balancing strategy considers server capacity and current load?",
        "explanation": "Weighted least connections algorithm considers both server weights (capacity) and current connections (load).",
        "reference": "https://kemptechnologies.com/load-balancer/weighted-least-connection-scheduling/",
        "points": 1,
        "answers": [
            {"text": "Round-robin", "is_correct": False},
            {"text": "Random", "is_correct": False},
            {"text": "Weighted least connections", "is_correct": True},
            {"text": "IP hash", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of database connection timeouts?",
        "explanation": "Connection timeouts prevent resource leaks by closing idle connections and freeing up connection pool resources.",
        "reference": "https://en.wikipedia.org/wiki/Connection_pool",
        "points": 1,
        "answers": [
            {"text": "Improving query performance", "is_correct": False},
            {"text": "Preventing resource leaks", "is_correct": True},
            {"text": "Data validation", "is_correct": False},
            {"text": "Schema synchronization", "is_correct": False},
        ],
    },
    {
        "text": "Which pattern helps maintain data consistency across multiple databases?",
        "explanation": "Two-phase commit (2PC) protocol ensures atomicity across multiple databases by coordinating transaction commits.",
        "reference": "https://en.wikipedia.org/wiki/Two-phase_commit_protocol",
        "points": 1,
        "answers": [
            {"text": "Saga pattern", "is_correct": False},
            {"text": "Two-phase commit", "is_correct": True},
            {"text": "Event sourcing", "is_correct": False},
            {"text": "CQRS", "is_correct": False},
        ],
    },
    {
        "text": "What is the main benefit of using compression in high-performance systems?",
        "explanation": "Compression reduces bandwidth usage and storage requirements, improving transfer speeds and reducing costs.",
        "reference": "https://en.wikipedia.org/wiki/Data_compression",
        "points": 1,
        "answers": [
            {"text": "Better security", "is_correct": False},
            {"text": "Reduced bandwidth and storage", "is_correct": True},
            {"text": "Faster processing", "is_correct": False},
            {"text": "Improved reliability", "is_correct": False},
        ],
    },
    {
        "text": "Which technique allows graceful degradation when external services are unavailable?",
        "explanation": "Fallback mechanisms provide alternative responses or cached data when primary services are unavailable.",
        "reference": "https://martinfowler.com/bliki/CircuitBreaker.html",
        "points": 1,
        "answers": [
            {"text": "Load balancing", "is_correct": False},
            {"text": "Fallback mechanisms", "is_correct": True},
            {"text": "Data replication", "is_correct": False},
            {"text": "Connection pooling", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of health checks in load balancers?",
        "explanation": "Health checks monitor server status and remove unhealthy servers from the load balancer pool.",
        "reference": "https://en.wikipedia.org/wiki/Load_balancing_(computing)",
        "points": 1,
        "answers": [
            {"text": "Performance monitoring", "is_correct": False},
            {"text": "Removing unhealthy servers", "is_correct": True},
            {"text": "Security scanning", "is_correct": False},
            {"text": "Configuration validation", "is_correct": False},
        ],
    },
    {
        "text": "Which technique helps reduce memory usage in high-throughput applications?",
        "explanation": "Object pooling reuses objects instead of creating new ones, reducing garbage collection pressure and memory allocation overhead.",
        "reference": "https://en.wikipedia.org/wiki/Object_pool_pattern",
        "points": 1,
        "answers": [
            {"text": "Data compression", "is_correct": False},
            {"text": "Object pooling", "is_correct": True},
            {"text": "Lazy loading", "is_correct": False},
            {"text": "Caching", "is_correct": False},
        ],
    },
    {
        "text": "What is the main advantage of using event-driven architecture?",
        "explanation": "Event-driven architecture provides loose coupling between components and enables reactive, scalable systems.",
        "reference": "https://en.wikipedia.org/wiki/Event-driven_architecture",
        "points": 1,
        "answers": [
            {"text": "Simpler debugging", "is_correct": False},
            {"text": "Loose coupling and scalability", "is_correct": True},
            {"text": "Better security", "is_correct": False},
            {"text": "Reduced complexity", "is_correct": False},
        ],
    },
    {
        "text": "Which technique optimizes database queries by reducing data transfer?",
        "explanation": "Query result pagination limits the amount of data returned per query, reducing network transfer and memory usage.",
        "reference": "https://en.wikipedia.org/wiki/Pagination",
        "points": 1,
        "answers": [
            {"text": "Indexing", "is_correct": False},
            {"text": "Pagination", "is_correct": True},
            {"text": "Normalization", "is_correct": False},
            {"text": "Partitioning", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of using CDN edge caching?",
        "explanation": "Edge caching stores content at CDN edge locations to serve users from the nearest geographic location, reducing latency.",
        "reference": "https://en.wikipedia.org/wiki/Content_delivery_network",
        "points": 1,
        "answers": [
            {"text": "Data compression", "is_correct": False},
            {"text": "Geographic proximity caching", "is_correct": True},
            {"text": "Load balancing", "is_correct": False},
            {"text": "Security filtering", "is_correct": False},
        ],
    },
    {
        "text": "Which pattern helps handle varying loads by automatically adjusting resources?",
        "explanation": "Auto-scaling automatically adjusts the number of running instances based on current load and predefined metrics.",
        "reference": "https://en.wikipedia.org/wiki/Autoscaling",
        "points": 1,
        "answers": [
            {"text": "Load balancing", "is_correct": False},
            {"text": "Auto-scaling", "is_correct": True},
            {"text": "Circuit breaker", "is_correct": False},
            {"text": "Bulkhead", "is_correct": False},
        ],
    },
    {
        "text": "What is the main benefit of using in-memory databases for high-performance applications?",
        "explanation": "In-memory databases store data in RAM, providing much faster access times compared to disk-based storage.",
        "reference": "https://en.wikipedia.org/wiki/In-memory_database",
        "points": 1,
        "answers": [
            {"text": "Lower storage costs", "is_correct": False},
            {"text": "Faster data access", "is_correct": True},
            {"text": "Better durability", "is_correct": False},
            {"text": "Easier backup", "is_correct": False},
        ],
    },
    {
        "text": "Which technique helps optimize API performance by fetching related data in a single request?",
        "explanation": "GraphQL allows clients to specify exactly what data they need and fetch related data in a single request, reducing over-fetching.",
        "reference": "https://graphql.org/learn/",
        "points": 1,
        "answers": [
            {"text": "REST APIs", "is_correct": False},
            {"text": "GraphQL", "is_correct": True},
            {"text": "SOAP", "is_correct": False},
            {"text": "RPC", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of using database read replicas?",
        "explanation": "Read replicas distribute read traffic across multiple database copies, improving read performance and reducing load on the primary database.",
        "reference": "https://en.wikipedia.org/wiki/Replication_(computing)",
        "points": 1,
        "answers": [
            {"text": "Write performance", "is_correct": False},
            {"text": "Read performance and load distribution", "is_correct": True},
            {"text": "Data compression", "is_correct": False},
            {"text": "Security enhancement", "is_correct": False},
        ],
    },
    {
        "text": "Which technique helps reduce response time by preprocessing and storing results?",
        "explanation": "Pre-computation calculates and stores results for common queries or operations beforehand, reducing response time.",
        "reference": "https://en.wikipedia.org/wiki/Precomputation",
        "points": 1,
        "answers": [
            {"text": "Lazy loading", "is_correct": False},
            {"text": "Pre-computation", "is_correct": True},
            {"text": "Just-in-time processing", "is_correct": False},
            {"text": "Dynamic compilation", "is_correct": False},
        ],
    },
    {
        "text": "What is the main advantage of using content compression (gzip) in web applications?",
        "explanation": "Content compression reduces the size of transmitted data, decreasing bandwidth usage and improving page load times.",
        "reference": "https://en.wikipedia.org/wiki/HTTP_compression",
        "points": 1,
        "answers": [
            {"text": "Better security", "is_correct": False},
            {"text": "Reduced bandwidth and faster loading", "is_correct": True},
            {"text": "Improved caching", "is_correct": False},
            {"text": "Enhanced SEO", "is_correct": False},
        ],
    },
    {
        "text": "Which pattern helps manage configuration changes without system restart?",
        "explanation": "Hot reloading allows configuration changes to be applied dynamically without requiring system restart or downtime.",
        "reference": "https://en.wikipedia.org/wiki/Hot_swapping",
        "points": 1,
        "answers": [
            {"text": "Blue-green deployment", "is_correct": False},
            {"text": "Hot reloading", "is_correct": True},
            {"text": "Rolling updates", "is_correct": False},
            {"text": "Canary deployment", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of using sticky sessions in load balancing?",
        "explanation": "Sticky sessions ensure that requests from the same client are always routed to the same server to maintain session state.",
        "reference": "https://en.wikipedia.org/wiki/Load_balancing_(computing)#Persistence",
        "points": 1,
        "answers": [
            {"text": "Better performance", "is_correct": False},
            {"text": "Session state maintenance", "is_correct": True},
            {"text": "Security enhancement", "is_correct": False},
            {"text": "Load distribution", "is_correct": False},
        ],
    },
    {
        "text": "Which technique optimizes memory usage by loading data only when needed?",
        "explanation": "Lazy loading defers the loading of data or objects until they are actually needed, optimizing memory usage.",
        "reference": "https://en.wikipedia.org/wiki/Lazy_loading",
        "points": 1,
        "answers": [
            {"text": "Eager loading", "is_correct": False},
            {"text": "Lazy loading", "is_correct": True},
            {"text": "Batch loading", "is_correct": False},
            {"text": "Parallel loading", "is_correct": False},
        ],
    },
    {
        "text": "What is the main benefit of using asynchronous message processing?",
        "explanation": "Asynchronous processing decouples producers from consumers, allowing better scalability and system resilience.",
        "reference": "https://en.wikipedia.org/wiki/Asynchronous_communication",
        "points": 1,
        "answers": [
            {"text": "Faster processing", "is_correct": False},
            {"text": "Decoupling and scalability", "is_correct": True},
            {"text": "Better security", "is_correct": False},
            {"text": "Simpler debugging", "is_correct": False},
        ],
    },
    {
        "text": "Which technique helps optimize database performance by storing frequently accessed data in faster storage?",
        "explanation": "Tiered storage places frequently accessed (hot) data on faster storage and less accessed (cold) data on slower, cheaper storage.",
        "reference": "https://en.wikipedia.org/wiki/Hierarchical_storage_management",
        "points": 1,
        "answers": [
            {"text": "Data archiving", "is_correct": False},
            {"text": "Tiered storage", "is_correct": True},
            {"text": "Data mirroring", "is_correct": False},
            {"text": "Data compression", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of using connection keep-alive in HTTP?",
        "explanation": "Keep-alive allows reusing the same TCP connection for multiple HTTP requests, reducing connection establishment overhead.",
        "reference": "https://en.wikipedia.org/wiki/HTTP_persistent_connection",
        "points": 1,
        "answers": [
            {"text": "Better security", "is_correct": False},
            {"text": "Reduced connection overhead", "is_correct": True},
            {"text": "Data compression", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which pattern helps handle high-volume data processing efficiently?",
        "explanation": "Stream processing handles continuous data streams in real-time, enabling efficient processing of high-volume data flows.",
        "reference": "https://en.wikipedia.org/wiki/Stream_processing",
        "points": 1,
        "answers": [
            {"text": "Batch processing", "is_correct": False},
            {"text": "Stream processing", "is_correct": True},
            {"text": "Manual processing", "is_correct": False},
            {"text": "Sequential processing", "is_correct": False},
        ],
    },
]
