"""Microservices Architecture Certification"""

CERTIFICATION = {
    "name": "Microservices Architecture Professional",
    "description": "Advanced microservices design patterns and implementation",
    "slug": "microservices-architecture-professional",
    "level": "Professional",
    "duration": 3,
    "questions_count": 65,
    "category_slug": "system-design",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is the Circuit Breaker pattern in microservices?",
        "explanation": "The Circuit Breaker pattern prevents cascading failures by monitoring service calls and failing fast when a service is unresponsive.",
        "reference": "https://martinfowler.com/bliki/CircuitBreaker.html",
        "points": 1,
        "answers": [
            {"text": "A pattern for load balancing", "is_correct": False},
            {"text": "A pattern to prevent cascading failures", "is_correct": True},
            {"text": "A pattern for data consistency", "is_correct": False},
            {"text": "A pattern for service discovery", "is_correct": False},
        ],
    },
    {
        "text": "What is the main benefit of the Saga pattern?",
        "explanation": (
            "The Saga pattern provides a way to maintain data consistency "
            "across multiple services without using distributed transactions."
        ),
        "reference": "https://microservices.io/patterns/data/saga.html",
        "points": 1,
        "answers": [
            {"text": "Improved performance", "is_correct": False},
            {"text": "Data consistency across services", "is_correct": True},
            {"text": "Better security", "is_correct": False},
            {"text": "Simplified deployment", "is_correct": False},
        ],
    },
    {
        "text": "Which communication pattern is asynchronous in microservices?",
        "explanation": "Message queues enable asynchronous communication where services don't need to wait for immediate responses.",
        "reference": "https://microservices.io/patterns/communication-style/messaging.html",
        "points": 1,
        "answers": [
            {"text": "REST API calls", "is_correct": False},
            {"text": "GraphQL queries", "is_correct": False},
            {"text": "Message queues", "is_correct": True},
            {"text": "RPC calls", "is_correct": False},
        ],
    },
    {
        "text": "What is the Database per Service pattern?",
        "explanation": "Each microservice should have its own database to maintain loose coupling and data independence.",
        "reference": "https://microservices.io/patterns/data/database-per-service.html",
        "points": 1,
        "answers": [
            {"text": "Multiple services sharing one database", "is_correct": False},
            {"text": "Each service has its own database", "is_correct": True},
            {"text": "Services without databases", "is_correct": False},
            {"text": "Centralized database management", "is_correct": False},
        ],
    },
    {
        "text": "What is service mesh in microservices architecture?",
        "explanation": "A service mesh is a dedicated infrastructure layer that handles service-to-service communication, providing features like load balancing, service discovery, and security.",
        "reference": "https://istio.io/latest/docs/concepts/what-is-istio/",
        "points": 1,
        "answers": [
            {"text": "A type of database", "is_correct": False},
            {"text": "Infrastructure layer for service communication", "is_correct": True},
            {"text": "A monitoring tool", "is_correct": False},
            {"text": "A deployment strategy", "is_correct": False},
        ],
    },
    {
        "text": "What is the Bulkhead pattern in microservices?",
        "explanation": "The Bulkhead pattern isolates resources to prevent failures in one service from affecting others, similar to compartments in a ship.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead",
        "points": 1,
        "answers": [
            {"text": "Resource isolation pattern", "is_correct": True},
            {"text": "Data replication pattern", "is_correct": False},
            {"text": "Load balancing pattern", "is_correct": False},
            {"text": "Security pattern", "is_correct": False},
        ],
    },
    {
        "text": "What is API Gateway in microservices architecture?",
        "explanation": "An API Gateway is a single entry point for all client requests, handling routing, authentication, and other cross-cutting concerns.",
        "reference": "https://microservices.io/patterns/apigateway.html",
        "points": 1,
        "answers": [
            {"text": "A database interface", "is_correct": False},
            {"text": "Single entry point for client requests", "is_correct": True},
            {"text": "A monitoring service", "is_correct": False},
            {"text": "A deployment tool", "is_correct": False},
        ],
    },
    {
        "text": "What is the Strangler Fig pattern used for?",
        "explanation": "The Strangler Fig pattern is used to gradually migrate from monolithic to microservices architecture by incrementally replacing functionality.",
        "reference": "https://martinfowler.com/bliki/StranglerFigApplication.html",
        "points": 1,
        "answers": [
            {"text": "Performance optimization", "is_correct": False},
            {"text": "Gradual migration from monolith", "is_correct": True},
            {"text": "Security enhancement", "is_correct": False},
            {"text": "Data backup strategy", "is_correct": False},
        ],
    },
    {
        "text": "What is eventual consistency in microservices?",
        "explanation": "Eventual consistency means that data will become consistent over time, but may be temporarily inconsistent across distributed services.",
        "reference": "https://en.wikipedia.org/wiki/Eventual_consistency",
        "points": 1,
        "answers": [
            {"text": "Immediate data consistency", "is_correct": False},
            {"text": "Data becomes consistent over time", "is_correct": True},
            {"text": "No data consistency", "is_correct": False},
            {"text": "Manual data synchronization", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of distributed tracing in microservices?",
        "explanation": "Distributed tracing tracks requests across multiple services to help debug and monitor complex microservices interactions.",
        "reference": "https://opentracing.io/docs/overview/what-is-tracing/",
        "points": 1,
        "answers": [
            {"text": "Load balancing", "is_correct": False},
            {"text": "Tracking requests across services", "is_correct": True},
            {"text": "Data encryption", "is_correct": False},
            {"text": "Service deployment", "is_correct": False},
        ],
    },
    {
        "text": "What is the CQRS pattern in microservices?",
        "explanation": "Command Query Responsibility Segregation (CQRS) separates read and write operations for better performance and scalability.",
        "reference": "https://martinfowler.com/bliki/CQRS.html",
        "points": 1,
        "answers": [
            {"text": "Separating read and write operations", "is_correct": True},
            {"text": "Combining all operations", "is_correct": False},
            {"text": "Security protocol", "is_correct": False},
            {"text": "Deployment strategy", "is_correct": False},
        ],
    },
    {
        "text": "What is service discovery in microservices?",
        "explanation": "Service discovery is the mechanism by which services can find and communicate with each other in a dynamic environment.",
        "reference": "https://microservices.io/patterns/service-registry.html",
        "points": 1,
        "answers": [
            {"text": "Finding available services dynamically", "is_correct": True},
            {"text": "Creating new services", "is_correct": False},
            {"text": "Deleting unused services", "is_correct": False},
            {"text": "Monitoring service health", "is_correct": False},
        ],
    },
    {
        "text": "What is the Event Sourcing pattern?",
        "explanation": "Event Sourcing stores all changes as a sequence of events, allowing reconstruction of current state and providing audit trails.",
        "reference": "https://martinfowler.com/eaaDev/EventSourcing.html",
        "points": 1,
        "answers": [
            {"text": "Storing current state only", "is_correct": False},
            {"text": "Storing all changes as events", "is_correct": True},
            {"text": "Caching frequently used data", "is_correct": False},
            {"text": "Compressing data storage", "is_correct": False},
        ],
    },
    {
        "text": "What is blue-green deployment in microservices?",
        "explanation": "Blue-green deployment maintains two identical production environments, switching traffic between them for zero-downtime deployments.",
        "reference": "https://martinfowler.com/bliki/BlueGreenDeployment.html",
        "points": 1,
        "answers": [
            {"text": "Two identical production environments", "is_correct": True},
            {"text": "Single production environment", "is_correct": False},
            {"text": "Testing environment only", "is_correct": False},
            {"text": "Development environment", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of a health check endpoint?",
        "explanation": "Health check endpoints allow monitoring systems to verify if a service is running and healthy.",
        "reference": "https://microservices.io/patterns/observability/health-check-api.html",
        "points": 1,
        "answers": [
            {"text": "Performance measurement", "is_correct": False},
            {"text": "Service health verification", "is_correct": True},
            {"text": "Data validation", "is_correct": False},
            {"text": "Security scanning", "is_correct": False},
        ],
    },
    {
        "text": "What is container orchestration in microservices?",
        "explanation": "Container orchestration automates deployment, scaling, and management of containerized applications across clusters.",
        "reference": "https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/",
        "points": 1,
        "answers": [
            {"text": "Manual container management", "is_correct": False},
            {"text": "Automated container management", "is_correct": True},
            {"text": "Container creation only", "is_correct": False},
            {"text": "Container deletion only", "is_correct": False},
        ],
    },
    {
        "text": "What is the Retry pattern in microservices?",
        "explanation": "The Retry pattern automatically retries failed operations with exponential backoff to handle transient failures.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/retry",
        "points": 1,
        "answers": [
            {"text": "Never retry failed operations", "is_correct": False},
            {"text": "Automatically retry failed operations", "is_correct": True},
            {"text": "Manual retry only", "is_correct": False},
            {"text": "Ignore failed operations", "is_correct": False},
        ],
    },
    {
        "text": "What is sidecar pattern in microservices?",
        "explanation": "The sidecar pattern deploys helper services alongside main services to provide cross-cutting functionality like logging or monitoring.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar",
        "points": 1,
        "answers": [
            {"text": "Helper services alongside main services", "is_correct": True},
            {"text": "Backup services only", "is_correct": False},
            {"text": "Primary services only", "is_correct": False},
            {"text": "Database services", "is_correct": False},
        ],
    },
    {
        "text": "What is API versioning in microservices?",
        "explanation": "API versioning allows services to evolve independently while maintaining backward compatibility with existing clients.",
        "reference": "https://microservices.io/patterns/communication-style/api-versioning.html",
        "points": 1,
        "answers": [
            {"text": "Managing different API versions", "is_correct": True},
            {"text": "Using only one API version", "is_correct": False},
            {"text": "Removing old APIs immediately", "is_correct": False},
            {"text": "API documentation", "is_correct": False},
        ],
    },
    {
        "text": "What is the Timeout pattern in microservices?",
        "explanation": "The Timeout pattern prevents services from waiting indefinitely by setting maximum wait times for operations.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/timeout",
        "points": 1,
        "answers": [
            {"text": "Waiting indefinitely", "is_correct": False},
            {"text": "Setting maximum wait times", "is_correct": True},
            {"text": "No time limits", "is_correct": False},
            {"text": "Random wait times", "is_correct": False},
        ],
    },
    {
        "text": "What is service decomposition in microservices?",
        "explanation": "Service decomposition is the process of breaking down a monolithic application into smaller, independent microservices.",
        "reference": "https://microservices.io/patterns/decomposition/decompose-by-business-capability.html",
        "points": 1,
        "answers": [
            {"text": "Combining services into monolith", "is_correct": False},
            {"text": "Breaking monolith into microservices", "is_correct": True},
            {"text": "Service optimization", "is_correct": False},
            {"text": "Service documentation", "is_correct": False},
        ],
    },
    {
        "text": "What is the Ambassador pattern in microservices?",
        "explanation": "The Ambassador pattern uses a proxy to handle network communication on behalf of a service, providing features like retry, circuit breaking, and routing.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/ambassador",
        "points": 1,
        "answers": [
            {"text": "Direct service communication", "is_correct": False},
            {"text": "Proxy for network communication", "is_correct": True},
            {"text": "Service registration", "is_correct": False},
            {"text": "Data storage pattern", "is_correct": False},
        ],
    },
    {
        "text": "What is distributed caching in microservices?",
        "explanation": "Distributed caching stores frequently accessed data across multiple nodes to improve performance and reduce database load.",
        "reference": "https://redis.io/topics/partitioning",
        "points": 1,
        "answers": [
            {"text": "Local caching only", "is_correct": False},
            {"text": "Caching across multiple nodes", "is_correct": True},
            {"text": "No caching strategy", "is_correct": False},
            {"text": "Database-only storage", "is_correct": False},
        ],
    },
    {
        "text": "What is the Backends for Frontends (BFF) pattern?",
        "explanation": "BFF creates separate backend services tailored for specific frontend clients (mobile, web, etc.) to optimize data delivery.",
        "reference": "https://samnewman.io/patterns/architectural/bff/",
        "points": 1,
        "answers": [
            {"text": "Single backend for all frontends", "is_correct": False},
            {"text": "Separate backends for different frontends", "is_correct": True},
            {"text": "No backend services", "is_correct": False},
            {"text": "Frontend-only architecture", "is_correct": False},
        ],
    },
    {
        "text": "What is canary deployment in microservices?",
        "explanation": "Canary deployment gradually rolls out new versions to a small subset of users before full deployment to minimize risk.",
        "reference": "https://martinfowler.com/bliki/CanaryRelease.html",
        "points": 1,
        "answers": [
            {"text": "Deploy to all users at once", "is_correct": False},
            {"text": "Gradual rollout to subset of users", "is_correct": True},
            {"text": "Deploy only to developers", "is_correct": False},
            {"text": "Never deploy new versions", "is_correct": False},
        ],
    },
    {
        "text": "What is the Transactional Outbox pattern?",
        "explanation": "The Transactional Outbox pattern ensures reliable event publishing by storing events in the same database transaction as business data.",
        "reference": "https://microservices.io/patterns/data/transactional-outbox.html",
        "points": 1,
        "answers": [
            {"text": "Unreliable event publishing", "is_correct": False},
            {"text": "Reliable event publishing with database", "is_correct": True},
            {"text": "No event publishing", "is_correct": False},
            {"text": "External event storage", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of correlation IDs in microservices?",
        "explanation": "Correlation IDs track requests across multiple services, enabling end-to-end tracing and debugging of distributed transactions.",
        "reference": "https://blog.rapid7.com/2016/12/23/the-value-of-correlation-ids/",
        "points": 1,
        "answers": [
            {"text": "Service identification", "is_correct": False},
            {"text": "Tracking requests across services", "is_correct": True},
            {"text": "Performance optimization", "is_correct": False},
            {"text": "Security authentication", "is_correct": False},
        ],
    },
    {
        "text": "What is the Database Sharding pattern?",
        "explanation": "Database sharding horizontally partitions data across multiple databases to improve performance and scalability.",
        "reference": "https://en.wikipedia.org/wiki/Shard_(database_architecture)",
        "points": 1,
        "answers": [
            {"text": "Vertical data partitioning", "is_correct": False},
            {"text": "Horizontal data partitioning", "is_correct": True},
            {"text": "No data partitioning", "is_correct": False},
            {"text": "Data replication only", "is_correct": False},
        ],
    },
    {
        "text": "What is the Anti-Corruption Layer pattern?",
        "explanation": "The Anti-Corruption Layer pattern creates a translation layer between new microservices and legacy systems to prevent pollution of the new design.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer",
        "points": 1,
        "answers": [
            {"text": "Direct integration with legacy systems", "is_correct": False},
            {"text": "Translation layer for legacy systems", "is_correct": True},
            {"text": "Removing all legacy systems", "is_correct": False},
            {"text": "Copying legacy system design", "is_correct": False},
        ],
    },
    {
        "text": "What is service mesh security in microservices?",
        "explanation": "Service mesh security provides mutual TLS, authentication, and authorization between services automatically at the infrastructure level.",
        "reference": "https://istio.io/latest/docs/concepts/security/",
        "points": 1,
        "answers": [
            {"text": "No security between services", "is_correct": False},
            {"text": "Automatic service-to-service security", "is_correct": True},
            {"text": "Manual security configuration", "is_correct": False},
            {"text": "Client-side security only", "is_correct": False},
        ],
    },
    {
        "text": "What is the Scatter-Gather pattern in microservices?",
        "explanation": "The Scatter-Gather pattern sends requests to multiple services simultaneously and aggregates the responses.",
        "reference": "https://www.enterpriseintegrationpatterns.com/patterns/messaging/BroadcastAggregate.html",
        "points": 1,
        "answers": [
            {"text": "Sequential service calls", "is_correct": False},
            {"text": "Simultaneous calls with response aggregation", "is_correct": True},
            {"text": "Single service calls only", "is_correct": False},
            {"text": "No service communication", "is_correct": False},
        ],
    },
    {
        "text": "What is polyglot persistence in microservices?",
        "explanation": "Polyglot persistence allows different microservices to use different database technologies best suited for their specific data needs.",
        "reference": "https://martinfowler.com/bliki/PolyglotPersistence.html",
        "points": 1,
        "answers": [
            {"text": "Using same database for all services", "is_correct": False},
            {"text": "Different databases for different services", "is_correct": True},
            {"text": "No databases", "is_correct": False},
            {"text": "Only relational databases", "is_correct": False},
        ],
    },
    {
        "text": "What is the Command pattern in microservices architecture?",
        "explanation": "The Command pattern encapsulates requests as objects, allowing for parameterization, queuing, and logging of operations.",
        "reference": "https://en.wikipedia.org/wiki/Command_pattern",
        "points": 1,
        "answers": [
            {"text": "Direct method calls", "is_correct": False},
            {"text": "Encapsulating requests as objects", "is_correct": True},
            {"text": "Database queries", "is_correct": False},
            {"text": "UI components", "is_correct": False},
        ],
    },
    {
        "text": "What is immutable infrastructure in microservices?",
        "explanation": "Immutable infrastructure treats servers as disposable resources that are never modified after deployment, only replaced.",
        "reference": "https://martinfowler.com/bliki/ImmutableServer.html",
        "points": 1,
        "answers": [
            {"text": "Modifying servers after deployment", "is_correct": False},
            {"text": "Never modifying servers after deployment", "is_correct": True},
            {"text": "Manual server management", "is_correct": False},
            {"text": "Permanent server installation", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of feature flags in microservices?",
        "explanation": "Feature flags enable toggling functionality on/off without code deployment, allowing gradual rollouts and easy rollbacks.",
        "reference": "https://martinfowler.com/articles/feature-toggles.html",
        "points": 1,
        "answers": [
            {"text": "Permanent feature activation", "is_correct": False},
            {"text": "Toggle functionality without deployment", "is_correct": True},
            {"text": "Feature documentation", "is_correct": False},
            {"text": "Performance monitoring", "is_correct": False},
        ],
    },
    {
        "text": "What is the Bulkhead pattern's main benefit?",
        "explanation": "The Bulkhead pattern prevents resource exhaustion in one part of the system from affecting other parts, improving overall system resilience.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead",
        "points": 1,
        "answers": [
            {"text": "Faster processing", "is_correct": False},
            {"text": "Fault isolation and resilience", "is_correct": True},
            {"text": "Lower costs", "is_correct": False},
            {"text": "Simplified architecture", "is_correct": False},
        ],
    },
    {
        "text": "What is API composition in microservices?",
        "explanation": "API composition aggregates data from multiple microservices to fulfill a single client request, often implemented in API gateways.",
        "reference": "https://microservices.io/patterns/data/api-composition.html",
        "points": 1,
        "answers": [
            {"text": "Single service data retrieval", "is_correct": False},
            {"text": "Aggregating data from multiple services", "is_correct": True},
            {"text": "Creating new APIs", "is_correct": False},
            {"text": "API documentation", "is_correct": False},
        ],
    },
    {
        "text": "What is the Shared Data Anti-pattern?",
        "explanation": "The Shared Data Anti-pattern occurs when multiple microservices directly access the same database, violating service independence.",
        "reference": "https://microservices.io/patterns/data/shared-database.html",
        "points": 1,
        "answers": [
            {"text": "Good practice for data sharing", "is_correct": False},
            {"text": "Violates service independence", "is_correct": True},
            {"text": "Improves performance", "is_correct": False},
            {"text": "Simplifies data management", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of dead letter queues in microservices?",
        "explanation": "Dead letter queues store messages that cannot be processed successfully, allowing for analysis and retry of failed operations.",
        "reference": "https://en.wikipedia.org/wiki/Dead_letter_queue",
        "points": 1,
        "answers": [
            {"text": "Storing successful messages", "is_correct": False},
            {"text": "Storing failed messages for analysis", "is_correct": True},
            {"text": "Deleting old messages", "is_correct": False},
            {"text": "Message routing", "is_correct": False},
        ],
    },
    {
        "text": "What is graceful degradation in microservices?",
        "explanation": "Graceful degradation ensures that system functionality is maintained at a reduced level when some services fail, rather than complete failure.",
        "reference": "https://en.wikipedia.org/wiki/Graceful_degradation",
        "points": 1,
        "answers": [
            {"text": "Complete system shutdown on failure", "is_correct": False},
            {"text": "Maintaining reduced functionality during failures", "is_correct": True},
            {"text": "Improving performance", "is_correct": False},
            {"text": "Adding new features", "is_correct": False},
        ],
    },
    {
        "text": "What is the Aggregator pattern in microservices?",
        "explanation": "The Aggregator pattern collects data from multiple microservices and presents a unified response to the client.",
        "reference": "https://microservices.io/patterns/data/api-composition.html",
        "points": 1,
        "answers": [
            {"text": "Splitting data across services", "is_correct": False},
            {"text": "Collecting data from multiple services", "is_correct": True},
            {"text": "Caching service data", "is_correct": False},
            {"text": "Encrypting service data", "is_correct": False},
        ],
    },
    {
        "text": "What is the main challenge of distributed logging?",
        "explanation": "Distributed logging must correlate logs from multiple services to provide coherent views of system behavior and troubleshooting.",
        "reference": "https://microservices.io/patterns/observability/application-logging.html",
        "points": 1,
        "answers": [
            {"text": "Log storage space", "is_correct": False},
            {"text": "Correlating logs across services", "is_correct": True},
            {"text": "Log formatting", "is_correct": False},
            {"text": "Log compression", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of chaos engineering in microservices?",
        "explanation": "Chaos engineering deliberately introduces failures to test system resilience and identify weaknesses before they cause real problems.",
        "reference": "https://principlesofchaos.org/",
        "points": 1,
        "answers": [
            {"text": "Preventing all failures", "is_correct": False},
            {"text": "Testing system resilience through deliberate failures", "is_correct": True},
            {"text": "Optimizing performance", "is_correct": False},
            {"text": "Reducing costs", "is_correct": False},
        ],
    },
    {
        "text": "What is service choreography in microservices?",
        "explanation": "Service choreography is a decentralized approach where services coordinate through events without a central orchestrator.",
        "reference": "https://microservices.io/patterns/data/saga.html",
        "points": 1,
        "answers": [
            {"text": "Centralized service coordination", "is_correct": False},
            {"text": "Decentralized service coordination through events", "is_correct": True},
            {"text": "Manual service coordination", "is_correct": False},
            {"text": "No service coordination", "is_correct": False},
        ],
    },
    {
        "text": "What is the Repository pattern in microservices?",
        "explanation": "The Repository pattern provides an abstraction layer over data access, allowing services to interact with data without knowing implementation details.",
        "reference": "https://martinfowler.com/eaaCatalog/repository.html",
        "points": 1,
        "answers": [
            {"text": "Direct database access", "is_correct": False},
            {"text": "Abstraction layer over data access", "is_correct": True},
            {"text": "Data visualization", "is_correct": False},
            {"text": "Data backup strategy", "is_correct": False},
        ],
    },
    {
        "text": "What is the main advantage of containerization for microservices?",
        "explanation": "Containerization provides consistent deployment environments and resource isolation, making microservices portable and easier to manage.",
        "reference": "https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/",
        "points": 1,
        "answers": [
            {"text": "Larger resource usage", "is_correct": False},
            {"text": "Consistent environments and isolation", "is_correct": True},
            {"text": "Slower deployment", "is_correct": False},
            {"text": "More complex management", "is_correct": False},
        ],
    },
    {
        "text": "What is the Throttling pattern in microservices?",
        "explanation": "The Throttling pattern controls the rate of resource consumption to prevent system overload and ensure fair resource allocation.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/throttling",
        "points": 1,
        "answers": [
            {"text": "Unlimited resource usage", "is_correct": False},
            {"text": "Controlling resource consumption rate", "is_correct": True},
            {"text": "Increasing system speed", "is_correct": False},
            {"text": "Reducing system costs", "is_correct": False},
        ],
    },
    {
        "text": "What is event-driven architecture in microservices?",
        "explanation": "Event-driven architecture uses events to trigger and communicate between microservices, enabling loose coupling and asynchronous processing.",
        "reference": "https://microservices.io/patterns/data/event-driven-architecture.html",
        "points": 1,
        "answers": [
            {"text": "Synchronous communication only", "is_correct": False},
            {"text": "Communication through events", "is_correct": True},
            {"text": "Direct method calls", "is_correct": False},
            {"text": "Database-driven communication", "is_correct": False},
        ],
    },
    {
        "text": "What is the Cache-Aside pattern?",
        "explanation": "The Cache-Aside pattern loads data into cache on demand when a cache miss occurs, with the application managing the cache directly.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/cache-aside",
        "points": 1,
        "answers": [
            {"text": "Pre-loading all data into cache", "is_correct": False},
            {"text": "Loading data into cache on demand", "is_correct": True},
            {"text": "Never using cache", "is_correct": False},
            {"text": "Automatic cache management", "is_correct": False},
        ],
    },
    {
        "text": "What is the main goal of microservices decomposition by business capability?",
        "explanation": "Decomposing by business capability creates services that align with business functions, ensuring each service has a clear business purpose.",
        "reference": "https://microservices.io/patterns/decomposition/decompose-by-business-capability.html",
        "points": 1,
        "answers": [
            {"text": "Technical convenience", "is_correct": False},
            {"text": "Aligning services with business functions", "is_correct": True},
            {"text": "Reducing code complexity", "is_correct": False},
            {"text": "Improving performance", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of service contracts in microservices?",
        "explanation": "Service contracts define the interface and expected behavior of services, enabling independent development and testing.",
        "reference": "https://martinfowler.com/articles/consumerDrivenContracts.html",
        "points": 1,
        "answers": [
            {"text": "Legal agreements", "is_correct": False},
            {"text": "Defining service interfaces and behavior", "is_correct": True},
            {"text": "Performance metrics", "is_correct": False},
            {"text": "Security policies", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between orchestration and choreography in microservices?",
        "explanation": "Orchestration uses a central coordinator to manage service interactions, while choreography allows services to interact directly through events.",
        "reference": "https://microservices.io/patterns/data/saga.html",
        "points": 1,
        "answers": [
            {"text": "No difference", "is_correct": False},
            {"text": "Central coordinator vs. direct service interaction", "is_correct": True},
            {"text": "Both use central coordinators", "is_correct": False},
            {"text": "Both avoid service interaction", "is_correct": False},
        ],
    },
    {
        "text": "What is the Materialized View pattern in microservices?",
        "explanation": "The Materialized View pattern creates read-only views of data from multiple services for optimized query performance.",
        "reference": "https://microservices.io/patterns/data/cqrs.html",
        "points": 1,
        "answers": [
            {"text": "Real-time data processing", "is_correct": False},
            {"text": "Pre-computed read-only data views", "is_correct": True},
            {"text": "Data backup strategy", "is_correct": False},
            {"text": "Service registration method", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of idempotency in microservices?",
        "explanation": "Idempotency ensures that performing the same operation multiple times has the same effect as performing it once, crucial for reliable distributed systems.",
        "reference": "https://en.wikipedia.org/wiki/Idempotence",
        "points": 1,
        "answers": [
            {"text": "Faster operation execution", "is_correct": False},
            {"text": "Same effect regardless of repetition", "is_correct": True},
            {"text": "Automatic error recovery", "is_correct": False},
            {"text": "Reduced memory usage", "is_correct": False},
        ],
    },
    {
        "text": "What is the Database Sharding strategy based on range partitioning?",
        "explanation": "Range partitioning divides data based on ranges of key values, such as alphabetical or numerical ranges.",
        "reference": "https://en.wikipedia.org/wiki/Partition_(database)",
        "points": 1,
        "answers": [
            {"text": "Random data distribution", "is_correct": False},
            {"text": "Data divided by key value ranges", "is_correct": True},
            {"text": "Hash-based distribution", "is_correct": False},
            {"text": "Round-robin distribution", "is_correct": False},
        ],
    },
    {
        "text": "What is the Two-Phase Commit (2PC) protocol?",
        "explanation": "Two-Phase Commit is a distributed transaction protocol that ensures atomicity across multiple databases, though it can cause blocking.",
        "reference": "https://en.wikipedia.org/wiki/Two-phase_commit_protocol",
        "points": 1,
        "answers": [
            {"text": "Single-phase transaction protocol", "is_correct": False},
            {"text": "Distributed transaction atomicity protocol", "is_correct": True},
            {"text": "Load balancing algorithm", "is_correct": False},
            {"text": "Service discovery mechanism", "is_correct": False},
        ],
    },
    {
        "text": "What is the Competing Consumers pattern?",
        "explanation": "The Competing Consumers pattern allows multiple service instances to process messages from the same queue concurrently for scalability.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/competing-consumers",
        "points": 1,
        "answers": [
            {"text": "Single consumer per queue", "is_correct": False},
            {"text": "Multiple consumers processing same queue", "is_correct": True},
            {"text": "Consumer priority system", "is_correct": False},
            {"text": "Sequential message processing", "is_correct": False},
        ],
    },
    {
        "text": "What is the Gateway Aggregation pattern?",
        "explanation": "Gateway Aggregation combines multiple service calls into a single request to reduce client complexity and network calls.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/gateway-aggregation",
        "points": 1,
        "answers": [
            {"text": "Single service per request", "is_correct": False},
            {"text": "Combining multiple service calls", "is_correct": True},
            {"text": "Service separation strategy", "is_correct": False},
            {"text": "Database aggregation method", "is_correct": False},
        ],
    },
    {
        "text": "What is the External Configuration Store pattern?",
        "explanation": "External Configuration Store centralizes configuration information outside of application deployment packages for dynamic updates.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/external-configuration-store",
        "points": 1,
        "answers": [
            {"text": "Configuration within application code", "is_correct": False},
            {"text": "Centralized external configuration management", "is_correct": True},
            {"text": "Local file-based configuration", "is_correct": False},
            {"text": "Database-stored application code", "is_correct": False},
        ],
    },
    {
        "text": "What is the Leader Election pattern in distributed systems?",
        "explanation": "Leader Election ensures only one instance acts as coordinator in a distributed system, preventing split-brain scenarios.",
        "reference": "https://en.wikipedia.org/wiki/Leader_election",
        "points": 1,
        "answers": [
            {"text": "Multiple simultaneous leaders", "is_correct": False},
            {"text": "Single coordinator selection", "is_correct": True},
            {"text": "No coordination needed", "is_correct": False},
            {"text": "Manual leader assignment", "is_correct": False},
        ],
    },
    {
        "text": "What is the Database-per-Tenant pattern in multi-tenant systems?",
        "explanation": "Database-per-Tenant provides complete data isolation by giving each tenant their own database instance.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/sharding",
        "points": 1,
        "answers": [
            {"text": "Shared database for all tenants", "is_correct": False},
            {"text": "Separate database per tenant", "is_correct": True},
            {"text": "Schema-based tenant separation", "is_correct": False},
            {"text": "Row-level tenant isolation", "is_correct": False},
        ],
    },
    {
        "text": "What is the Claim Check pattern?",
        "explanation": "The Claim Check pattern stores large message payloads externally and passes only a reference through the messaging system.",
        "reference": "https://www.enterpriseintegrationpatterns.com/patterns/messaging/StoreInLibrary.html",
        "points": 1,
        "answers": [
            {"text": "Storing all data in messages", "is_correct": False},
            {"text": "External storage with message references", "is_correct": True},
            {"text": "Message compression technique", "is_correct": False},
            {"text": "Message encryption method", "is_correct": False},
        ],
    },
    {
        "text": "What is the Pipes and Filters pattern in microservices?",
        "explanation": "Pipes and Filters breaks down complex processing into a series of discrete processing steps connected by channels.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/pipes-and-filters",
        "points": 1,
        "answers": [
            {"text": "Monolithic processing approach", "is_correct": False},
            {"text": "Sequential discrete processing steps", "is_correct": True},
            {"text": "Parallel unstructured processing", "is_correct": False},
            {"text": "Single-step data transformation", "is_correct": False},
        ],
    },
    {
        "text": "What is the Valet Key pattern?",
        "explanation": "The Valet Key pattern provides clients with restricted access tokens to directly access specific resources without going through the service.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/valet-key",
        "points": 1,
        "answers": [
            {"text": "Full administrative access", "is_correct": False},
            {"text": "Restricted direct resource access", "is_correct": True},
            {"text": "No access control", "is_correct": False},
            {"text": "Service-mediated access only", "is_correct": False},
        ],
    },
    {
        "text": "What is the Publisher-Subscriber pattern in microservices?",
        "explanation": "Publisher-Subscriber decouples message producers from consumers, allowing asynchronous communication through message brokers.",
        "reference": "https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern",
        "points": 1,
        "answers": [
            {"text": "Direct synchronous communication", "is_correct": False},
            {"text": "Decoupled asynchronous messaging", "is_correct": True},
            {"text": "Database-based communication", "is_correct": False},
            {"text": "File-based message exchange", "is_correct": False},
        ],
    },
    {
        "text": "What is the Compensating Transaction pattern?",
        "explanation": "Compensating Transaction undoes work performed by a series of steps in case of failure, since traditional rollback isn't possible in distributed systems.",
        "reference": "https://docs.microsoft.com/en-us/azure/architecture/patterns/compensating-transaction",
        "points": 1,
        "answers": [
            {"text": "Traditional database rollback", "is_correct": False},
            {"text": "Undoing distributed operations on failure", "is_correct": True},
            {"text": "Preventing all failures", "is_correct": False},
            {"text": "Ignoring failed operations", "is_correct": False},
        ],
    }
]
