"""Linux Professional Institute Certification Level 1 (LPIC-1)"""

CERTIFICATION = {
    "name": "Linux Professional Institute Certification Level 1 (LPIC-1)",
    "description": "Fundamental Linux administration skills and knowledge",
    "slug": "lpic-1",
    "level": "Associate",
    "duration": 147,
    "questions_count": 49,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which file contains the system's hostname in most Linux distributions?",
        "explanation": "/etc/hostname contains the system's hostname in most modern Linux distributions.",
        "reference": "https://www.lpi.org/our-certifications/lpic-1-overview",
        "points": 1,
        "answers": [
            {"text": "/etc/hosts", "is_correct": False},
            {"text": "/etc/hostname", "is_correct": True},
            {"text": "/etc/resolv.conf", "is_correct": False},
            {"text": "/etc/network", "is_correct": False},
        ],
    },
    {
        "text": "What is the default runlevel for graphical mode in System V init?",
        "explanation": "Runlevel 5 is traditionally used for graphical multi-user mode with X11 display manager in System V init systems.",
        "reference": "https://www.lpi.org/our-certifications/exam-101-objectives",
        "points": 1,
        "answers": [
            {"text": "3", "is_correct": False},
            {"text": "5", "is_correct": True},
            {"text": "1", "is_correct": False},
            {"text": "0", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to view the kernel ring buffer?",
        "explanation": "dmesg displays the kernel ring buffer which contains kernel messages including boot messages and hardware detection.",
        "reference": "https://man7.org/linux/man-pages/man1/dmesg.1.html",
        "points": 1,
        "answers": [
            {"text": "kmesg", "is_correct": False},
            {"text": "dmesg", "is_correct": True},
            {"text": "kernel", "is_correct": False},
            {"text": "syslog", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /proc filesystem?",
        "explanation": "The /proc filesystem is a virtual filesystem that provides an interface to kernel data structures and system information.",
        "reference": "https://man7.org/linux/man-pages/man5/proc.5.html",
        "points": 1,
        "answers": [
            {"text": "Store user processes", "is_correct": False},
            {"text": "Virtual filesystem for kernel data", "is_correct": True},
            {"text": "Process execution directory", "is_correct": False},
            {"text": "Program installation location", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display and manipulate routing tables?",
        "explanation": "The route command (traditional) or ip route (modern) is used to display and manipulate the IP routing table.",
        "reference": "https://man7.org/linux/man-pages/man8/route.8.html",
        "points": 1,
        "answers": [
            {"text": "netstat", "is_correct": False},
            {"text": "route", "is_correct": True},
            {"text": "ifconfig", "is_correct": False},
            {"text": "ping", "is_correct": False},
        ],
    },
    {
        "text": "What does the command 'chmod 755 file' do?",
        "explanation": "chmod 755 sets permissions to rwxr-xr-x: owner has read/write/execute, group and others have read/execute.",
        "reference": "https://man7.org/linux/man-pages/man1/chmod.1.html",
        "points": 1,
        "answers": [
            {"text": "Sets full permissions for all", "is_correct": False},
            {"text": "Sets rwxr-xr-x permissions", "is_correct": True},
            {"text": "Sets read-only permissions", "is_correct": False},
            {"text": "Removes all permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains the list of filesystems to be mounted at boot?",
        "explanation": "The /etc/fstab file contains filesystem table information used for automatic mounting at boot time.",
        "reference": "https://man7.org/linux/man-pages/man5/fstab.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/mtab", "is_correct": False},
            {"text": "/etc/fstab", "is_correct": True},
            {"text": "/etc/mounts", "is_correct": False},
            {"text": "/proc/mounts", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to display currently mounted filesystems?",
        "explanation": "The mount command without arguments displays currently mounted filesystems and their mount points.",
        "reference": "https://man7.org/linux/man-pages/man8/mount.8.html",
        "points": 1,
        "answers": [
            {"text": "df", "is_correct": False},
            {"text": "mount", "is_correct": True},
            {"text": "lsblk", "is_correct": False},
            {"text": "fdisk", "is_correct": False},
        ],
    },
    {
        "text": "Which signal does 'kill -9' send to a process?",
        "explanation": "Signal 9 (SIGKILL) is an unconditional kill signal that cannot be caught, blocked, or ignored by the process.",
        "reference": "https://man7.org/linux/man-pages/man7/signal.7.html",
        "points": 1,
        "answers": [
            {"text": "SIGTERM", "is_correct": False},
            {"text": "SIGKILL", "is_correct": True},
            {"text": "SIGHUP", "is_correct": False},
            {"text": "SIGINT", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /etc/shadow file?",
        "explanation": "The /etc/shadow file stores encrypted password information and password aging data for user accounts.",
        "reference": "https://man7.org/linux/man-pages/man5/shadow.5.html",
        "points": 1,
        "answers": [
            {"text": "Store user account information", "is_correct": False},
            {"text": "Store encrypted passwords", "is_correct": True},
            {"text": "Store group information", "is_correct": False},
            {"text": "Store system configuration", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to create a filesystem on a partition?",
        "explanation": "The mkfs command (make filesystem) creates a filesystem on a device or partition.",
        "reference": "https://man7.org/linux/man-pages/man8/mkfs.8.html",
        "points": 1,
        "answers": [
            {"text": "fdisk", "is_correct": False},
            {"text": "mkfs", "is_correct": True},
            {"text": "format", "is_correct": False},
            {"text": "partition", "is_correct": False},
        ],
    },
    {
        "text": "What does the command 'umask 022' set?",
        "explanation": "umask 022 sets the default permissions for new files to 644 (rw-r--r--) and directories to 755 (rwxr-xr-x).",
        "reference": "https://man7.org/linux/man-pages/man2/umask.2.html",
        "points": 1,
        "answers": [
            {"text": "Full permissions for all", "is_correct": False},
            {"text": "Default creation permissions", "is_correct": True},
            {"text": "Read-only permissions", "is_correct": False},
            {"text": "No permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which directory contains device files in Linux?",
        "explanation": "The /dev directory contains device files that represent hardware devices and virtual devices.",
        "reference": "https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s06.html",
        "points": 1,
        "answers": [
            {"text": "/sys", "is_correct": False},
            {"text": "/dev", "is_correct": True},
            {"text": "/proc", "is_correct": False},
            {"text": "/var", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to display block device information?",
        "explanation": "The lsblk command lists all block devices in a tree format showing the relationship between devices and mount points.",
        "reference": "https://man7.org/linux/man-pages/man8/lsblk.8.html",
        "points": 1,
        "answers": [
            {"text": "blkid", "is_correct": False},
            {"text": "lsblk", "is_correct": True},
            {"text": "fdisk", "is_correct": False},
            {"text": "lsdev", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains kernel boot parameters?",
        "explanation": "/proc/cmdline contains the kernel command line parameters that were passed to the kernel at boot time.",
        "reference": "https://man7.org/linux/man-pages/man5/proc.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/kernel", "is_correct": False},
            {"text": "/proc/cmdline", "is_correct": True},
            {"text": "/boot/grub.conf", "is_correct": False},
            {"text": "/etc/bootparams", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the swap space in Linux?",
        "explanation": "Swap space is used as virtual memory when physical RAM is fully utilized, allowing the system to continue operating.",
        "reference": "https://www.kernel.org/doc/Documentation/vm/swapfile.txt",
        "points": 1,
        "answers": [
            {"text": "Store temporary files", "is_correct": False},
            {"text": "Virtual memory extension", "is_correct": True},
            {"text": "Boot loader storage", "is_correct": False},
            {"text": "System backup space", "is_correct": False},
        ],
    },
    {
        "text": "Which command enables a swap file or partition?",
        "explanation": "The swapon command activates swap space on a device or file for use as virtual memory.",
        "reference": "https://man7.org/linux/man-pages/man8/swapon.8.html",
        "points": 1,
        "answers": [
            {"text": "mkswap", "is_correct": False},
            {"text": "swapon", "is_correct": True},
            {"text": "swapoff", "is_correct": False},
            {"text": "enableswap", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'ps aux' command display?",
        "explanation": "ps aux displays all running processes with detailed information including user, PID, CPU usage, memory usage, and command.",
        "reference": "https://man7.org/linux/man-pages/man1/ps.1.html",
        "points": 1,
        "answers": [
            {"text": "Only current user processes", "is_correct": False},
            {"text": "All processes with details", "is_correct": True},
            {"text": "System services only", "is_correct": False},
            {"text": "Memory usage only", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains system startup scripts in System V?",
        "explanation": "System V init scripts are typically located in /etc/init.d/ directory for service management.",
        "reference": "https://refspecs.linuxfoundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html",
        "points": 1,
        "answers": [
            {"text": "/etc/rc.d/", "is_correct": False},
            {"text": "/etc/init.d/", "is_correct": True},
            {"text": "/etc/startup/", "is_correct": False},
            {"text": "/etc/services/", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to display system resource usage?",
        "explanation": "The sar command (System Activity Reporter) displays system resource usage including CPU, memory, and I/O statistics.",
        "reference": "https://man7.org/linux/man-pages/man1/sar.1.html",
        "points": 1,
        "answers": [
            {"text": "iostat", "is_correct": False},
            {"text": "sar", "is_correct": True},
            {"text": "vmstat", "is_correct": False},
            {"text": "top", "is_correct": False},
        ],
    },
    {
        "text": "Which environment variable contains the user's home directory path?",
        "explanation": "The HOME environment variable contains the full path to the current user's home directory.",
        "reference": "https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html",
        "points": 1,
        "answers": [
            {"text": "PATH", "is_correct": False},
            {"text": "HOME", "is_correct": True},
            {"text": "USER", "is_correct": False},
            {"text": "PWD", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the /etc/passwd file?",
        "explanation": "The /etc/passwd file contains user account information including username, UID, GID, home directory, and shell.",
        "reference": "https://man7.org/linux/man-pages/man5/passwd.5.html",
        "points": 1,
        "answers": [
            {"text": "Store user passwords", "is_correct": False},
            {"text": "Store user account information", "is_correct": True},
            {"text": "Store system passwords", "is_correct": False},
            {"text": "Store group information", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to change group ownership of files?",
        "explanation": "The chgrp command changes the group ownership of files and directories.",
        "reference": "https://man7.org/linux/man-pages/man1/chgrp.1.html",
        "points": 1,
        "answers": [
            {"text": "chown", "is_correct": False},
            {"text": "chgrp", "is_correct": True},
            {"text": "chmod", "is_correct": False},
            {"text": "groups", "is_correct": False},
        ],
    },
    {
        "text": "What does the command 'ln -s target link' create?",
        "explanation": "The ln -s command creates a symbolic link (symlink) that points to the target file or directory.",
        "reference": "https://man7.org/linux/man-pages/man1/ln.1.html",
        "points": 1,
        "answers": [
            {"text": "Hard link", "is_correct": False},
            {"text": "Symbolic link", "is_correct": True},
            {"text": "Copy of file", "is_correct": False},
            {"text": "Shortcut", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays information about PCI devices?",
        "explanation": "The lspci command lists all PCI devices connected to the system with detailed information.",
        "reference": "https://man7.org/linux/man-pages/man8/lspci.8.html",
        "points": 1,
        "answers": [
            {"text": "lsdev", "is_correct": False},
            {"text": "lspci", "is_correct": True},
            {"text": "hwinfo", "is_correct": False},
            {"text": "pciinfo", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the PATH environment variable?",
        "explanation": "The PATH environment variable contains a list of directories where the shell searches for executable commands.",
        "reference": "https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html",
        "points": 1,
        "answers": [
            {"text": "Current directory path", "is_correct": False},
            {"text": "Executable search paths", "is_correct": True},
            {"text": "File system paths", "is_correct": False},
            {"text": "Library paths", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display USB device information?",
        "explanation": "The lsusb command lists USB devices connected to the system and their details.",
        "reference": "https://man7.org/linux/man-pages/man8/lsusb.8.html",
        "points": 1,
        "answers": [
            {"text": "usbinfo", "is_correct": False},
            {"text": "lsusb", "is_correct": True},
            {"text": "usb-devices", "is_correct": False},
            {"text": "lsdev", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'wc' command do?",
        "explanation": "The wc (word count) command counts lines, words, and characters in files or input streams.",
        "reference": "https://man7.org/linux/man-pages/man1/wc.1.html",
        "points": 1,
        "answers": [
            {"text": "Word processor", "is_correct": False},
            {"text": "Count lines, words, characters", "is_correct": True},
            {"text": "Write to console", "is_correct": False},
            {"text": "Watch files", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to sort lines in a file?",
        "explanation": "The sort command sorts lines of text files alphabetically or numerically according to specified criteria.",
        "reference": "https://man7.org/linux/man-pages/man1/sort.1.html",
        "points": 1,
        "answers": [
            {"text": "order", "is_correct": False},
            {"text": "sort", "is_correct": True},
            {"text": "arrange", "is_correct": False},
            {"text": "organize", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'cut' command?",
        "explanation": "The cut command extracts specific columns or fields from lines of text files or input streams.",
        "reference": "https://man7.org/linux/man-pages/man1/cut.1.html",
        "points": 1,
        "answers": [
            {"text": "Delete files", "is_correct": False},
            {"text": "Extract columns from text", "is_correct": True},
            {"text": "Split files", "is_correct": False},
            {"text": "Trim whitespace", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays the last modification time of files?",
        "explanation": "The stat command displays detailed file statistics including modification, access, and change times.",
        "reference": "https://man7.org/linux/man-pages/man1/stat.1.html",
        "points": 1,
        "answers": [
            {"text": "time", "is_correct": False},
            {"text": "stat", "is_correct": True},
            {"text": "date", "is_correct": False},
            {"text": "mtime", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'tr' command do?",
        "explanation": "The tr (translate) command translates or deletes characters from input streams, useful for character substitution.",
        "reference": "https://man7.org/linux/man-pages/man1/tr.1.html",
        "points": 1,
        "answers": [
            {"text": "Transfer files", "is_correct": False},
            {"text": "Translate characters", "is_correct": True},
            {"text": "Tree view", "is_correct": False},
            {"text": "Track processes", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to merge lines from multiple files?",
        "explanation": "The paste command merges corresponding lines from multiple files side by side.",
        "reference": "https://man7.org/linux/man-pages/man1/paste.1.html",
        "points": 1,
        "answers": [
            {"text": "merge", "is_correct": False},
            {"text": "paste", "is_correct": True},
            {"text": "join", "is_correct": False},
            {"text": "combine", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'uniq' command?",
        "explanation": "The uniq command removes duplicate adjacent lines from sorted files or input streams.",
        "reference": "https://man7.org/linux/man-pages/man1/uniq.1.html",
        "points": 1,
        "answers": [
            {"text": "Make files unique", "is_correct": False},
            {"text": "Remove duplicate lines", "is_correct": True},
            {"text": "Count unique files", "is_correct": False},
            {"text": "Generate unique IDs", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays network interface configuration?",
        "explanation": "The ip addr or ifconfig command displays network interface configuration including IP addresses and status.",
        "reference": "https://man7.org/linux/man-pages/man8/ip.8.html",
        "points": 1,
        "answers": [
            {"text": "netconfig", "is_correct": False},
            {"text": "ip addr", "is_correct": True},
            {"text": "network", "is_correct": False},
            {"text": "ifstat", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'sed' command do?",
        "explanation": "The sed (stream editor) command performs text transformations on input streams including search, replace, insert, and delete operations.",
        "reference": "https://man7.org/linux/man-pages/man1/sed.1.html",
        "points": 1,
        "answers": [
            {"text": "Secure delete", "is_correct": False},
            {"text": "Stream editor for text", "is_correct": True},
            {"text": "System editor", "is_correct": False},
            {"text": "Send data", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display or set system date?",
        "explanation": "The date command displays the current date and time, and can be used to set the system date (with appropriate privileges).",
        "reference": "https://man7.org/linux/man-pages/man1/date.1.html",
        "points": 1,
        "answers": [
            {"text": "time", "is_correct": False},
            {"text": "date", "is_correct": True},
            {"text": "clock", "is_correct": False},
            {"text": "calendar", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'awk' command?",
        "explanation": "AWK is a pattern scanning and processing language used for text processing and data extraction from structured files.",
        "reference": "https://man7.org/linux/man-pages/man1/awk.1p.html",
        "points": 1,
        "answers": [
            {"text": "Archive files", "is_correct": False},
            {"text": "Text processing and pattern scanning", "is_correct": True},
            {"text": "Audio processing", "is_correct": False},
            {"text": "Automated tasks", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays information about loaded kernel modules?",
        "explanation": "The lsmod command displays information about currently loaded kernel modules and their dependencies.",
        "reference": "https://man7.org/linux/man-pages/man8/lsmod.8.html",
        "points": 1,
        "answers": [
            {"text": "modinfo", "is_correct": False},
            {"text": "lsmod", "is_correct": True},
            {"text": "modules", "is_correct": False},
            {"text": "kernmod", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'modprobe' command do?",
        "explanation": "The modprobe command loads or unloads kernel modules along with their dependencies automatically.",
        "reference": "https://man7.org/linux/man-pages/man8/modprobe.8.html",
        "points": 1,
        "answers": [
            {"text": "Probe hardware", "is_correct": False},
            {"text": "Load/unload kernel modules", "is_correct": True},
            {"text": "Test modules", "is_correct": False},
            {"text": "Module information", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains module loading configuration?",
        "explanation": "Files in /etc/modprobe.d/ directory contain module loading configuration including aliases and options.",
        "reference": "https://man7.org/linux/man-pages/man5/modprobe.d.5.html",
        "points": 1,
        "answers": [
            {"text": "/etc/modules", "is_correct": False},
            {"text": "/etc/modprobe.d/", "is_correct": True},
            {"text": "/etc/module.conf", "is_correct": False},
            {"text": "/proc/modules", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'cpio' command?",
        "explanation": "The cpio command creates and extracts archives, commonly used for backing up files and creating initramfs images.",
        "reference": "https://man7.org/linux/man-pages/man1/cpio.1.html",
        "points": 1,
        "answers": [
            {"text": "Copy files", "is_correct": False},
            {"text": "Create and extract archives", "is_correct": True},
            {"text": "CPU information", "is_correct": False},
            {"text": "Character processing", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display file type information?",
        "explanation": "The file command determines and displays the type of files based on their content and magic numbers.",
        "reference": "https://man7.org/linux/man-pages/man1/file.1.html",
        "points": 1,
        "answers": [
            {"text": "type", "is_correct": False},
            {"text": "file", "is_correct": True},
            {"text": "filetype", "is_correct": False},
            {"text": "info", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'dd' command do?",
        "explanation": "The dd command copies and converts files with options for block size, count, and format conversion.",
        "reference": "https://man7.org/linux/man-pages/man1/dd.1.html",
        "points": 1,
        "answers": [
            {"text": "Delete directory", "is_correct": False},
            {"text": "Copy and convert files", "is_correct": True},
            {"text": "Disk defragmentation", "is_correct": False},
            {"text": "Data dump", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays information about CPU architecture?",
        "explanation": "The lscpu command displays detailed information about CPU architecture including cores, threads, and cache sizes.",
        "reference": "https://man7.org/linux/man-pages/man1/lscpu.1.html",
        "points": 1,
        "answers": [
            {"text": "cpuinfo", "is_correct": False},
            {"text": "lscpu", "is_correct": True},
            {"text": "procinfo", "is_correct": False},
            {"text": "cpu", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'at' command?",
        "explanation": "The at command schedules commands to be executed once at a specified time in the future.",
        "reference": "https://man7.org/linux/man-pages/man1/at.1.html",
        "points": 1,
        "answers": [
            {"text": "Attach processes", "is_correct": False},
            {"text": "Schedule one-time tasks", "is_correct": True},
            {"text": "Automatic tasks", "is_correct": False},
            {"text": "Access time", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to display system load averages?",
        "explanation": "The uptime command displays system load averages for 1, 5, and 15 minute intervals along with system uptime.",
        "reference": "https://man7.org/linux/man-pages/man1/uptime.1.html",
        "points": 1,
        "answers": [
            {"text": "load", "is_correct": False},
            {"text": "uptime", "is_correct": True},
            {"text": "sysload", "is_correct": False},
            {"text": "loadavg", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'nohup' command do?",
        "explanation": "The nohup command runs programs immune to hangup signals, allowing them to continue running after logout.",
        "reference": "https://man7.org/linux/man-pages/man1/nohup.1.html",
        "points": 1,
        "answers": [
            {"text": "No output", "is_correct": False},
            {"text": "Run immune to hangups", "is_correct": True},
            {"text": "No interrupts", "is_correct": False},
            {"text": "Non-blocking", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays memory and swap usage?",
        "explanation": "The free command displays memory usage information including total, used, free, and swap space statistics.",
        "reference": "https://man7.org/linux/man-pages/man1/free.1.html",
        "points": 1,
        "answers": [
            {"text": "memory", "is_correct": False},
            {"text": "free", "is_correct": True},
            {"text": "meminfo", "is_correct": False},
            {"text": "ram", "is_correct": False},
        ],
    },
]
