"""Red Hat Certified Engineer (RHCE) Certification"""

CERTIFICATION = {
    "name": "Red Hat Certified Engineer (RHCE)",
    "description": "Advanced Red Hat Enterprise Linux administration and automation",
    "slug": "rhce",
    "level": "Expert",
    "duration": 144,
    "questions_count": 48,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which tool is primarily used for automation in RHCE certification?",
        "explanation": "Ansible is the primary automation tool covered in RHCE certification for automating deployment and configuration management.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/administration_guide/",
        "points": 1,
        "answers": [
            {"text": "Puppet", "is_correct": False},
            {"text": "Ansible", "is_correct": True},
            {"text": "Chef", "is_correct": False},
            {"text": "SaltStack", "is_correct": False},
        ],
    },
    {
        "text": "What is an Ansible playbook?",
        "explanation": "An Ansible playbook is a YAML file that contains a series of tasks and configurations to be executed on managed hosts for automation.",
        "reference": "https://docs.ansible.com/ansible/latest/user_guide/playbooks.html",
        "points": 1,
        "answers": [
            {"text": "Configuration file", "is_correct": False},
            {"text": "YAML automation script", "is_correct": True},
            {"text": "Inventory file", "is_correct": False},
            {"text": "Module collection", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains the Ansible inventory?",
        "explanation": "The Ansible inventory file (default: /etc/ansible/hosts) contains the list of managed hosts and groups for automation tasks.",
        "reference": "https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html",
        "points": 1,
        "answers": [
            {"text": "/etc/ansible/ansible.cfg", "is_correct": False},
            {"text": "/etc/ansible/hosts", "is_correct": True},
            {"text": "/etc/ansible/playbooks", "is_correct": False},
            {"text": "/etc/ansible/modules", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Ansible roles?",
        "explanation": "Ansible roles provide a structured way to organize playbooks, tasks, variables, and handlers for reusable automation components.",
        "reference": "https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html",
        "points": 1,
        "answers": [
            {"text": "User permissions", "is_correct": False},
            {"text": "Reusable automation components", "is_correct": True},
            {"text": "System roles", "is_correct": False},
            {"text": "Security roles", "is_correct": False},
        ],
    },
    {
        "text": "Which command executes an Ansible playbook?",
        "explanation": "ansible-playbook command executes Ansible playbooks against the specified inventory hosts.",
        "reference": "https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html",
        "points": 1,
        "answers": [
            {"text": "ansible-run", "is_correct": False},
            {"text": "ansible-playbook", "is_correct": True},
            {"text": "ansible-exec", "is_correct": False},
            {"text": "ansible-play", "is_correct": False},
        ],
    },
    {
        "text": "What is Ansible Vault used for?",
        "explanation": "Ansible Vault encrypts sensitive data like passwords and keys within Ansible files to maintain security in automation scripts.",
        "reference": "https://docs.ansible.com/ansible/latest/user_guide/vault.html",
        "points": 1,
        "answers": [
            {"text": "File storage", "is_correct": False},
            {"text": "Sensitive data encryption", "is_correct": True},
            {"text": "Version control", "is_correct": False},
            {"text": "Backup storage", "is_correct": False},
        ],
    },
    {
        "text": "Which Ansible module manages system services?",
        "explanation": "The systemd module (or service module) in Ansible manages systemd services, enabling, disabling, starting, and stopping services.",
        "reference": "https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html",
        "points": 1,
        "answers": [
            {"text": "command", "is_correct": False},
            {"text": "systemd", "is_correct": True},
            {"text": "shell", "is_correct": False},
            {"text": "script", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of firewalld in RHEL?",
        "explanation": "firewalld is a dynamic firewall management tool in RHEL that provides network security through zones and services configuration.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/using-and-configuring-firewalls_securing-networks",
        "points": 1,
        "answers": [
            {"text": "System monitoring", "is_correct": False},
            {"text": "Dynamic firewall management", "is_correct": True},
            {"text": "Log management", "is_correct": False},
            {"text": "Service management", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages firewalld rules?",
        "explanation": "firewall-cmd is the command-line interface for managing firewalld zones, services, and rules in RHEL systems.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/using-and-configuring-firewalls_securing-networks",
        "points": 1,
        "answers": [
            {"text": "iptables", "is_correct": False},
            {"text": "firewall-cmd", "is_correct": True},
            {"text": "ufw", "is_correct": False},
            {"text": "netfilter", "is_correct": False},
        ],
    },
    {
        "text": "What are firewalld zones?",
        "explanation": "Firewalld zones define different levels of network trust and security policies, allowing different firewall rules for different network environments.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/using-and-configuring-firewalls_securing-networks",
        "points": 1,
        "answers": [
            {"text": "Network segments", "is_correct": False},
            {"text": "Trust levels with security policies", "is_correct": True},
            {"text": "Geographic regions", "is_correct": False},
            {"text": "Time zones", "is_correct": False},
        ],
    },
    {
        "text": "Which command makes firewalld rules permanent?",
        "explanation": "firewall-cmd --permanent flag makes firewall rules persistent across reboots in firewalld configuration.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/using-and-configuring-firewalls_securing-networks",
        "points": 1,
        "answers": [
            {"text": "firewall-cmd --save", "is_correct": False},
            {"text": "firewall-cmd --permanent", "is_correct": True},
            {"text": "firewall-cmd --persist", "is_correct": False},
            {"text": "firewall-cmd --store", "is_correct": False},
        ],
    },
    {
        "text": "What is SELinux in Red Hat Enterprise Linux?",
        "explanation": "SELinux (Security-Enhanced Linux) provides mandatory access control security policies to enhance system security beyond traditional permissions.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/index",
        "points": 1,
        "answers": [
            {"text": "File system encryption", "is_correct": False},
            {"text": "Mandatory access control security", "is_correct": True},
            {"text": "Network security", "is_correct": False},
            {"text": "User authentication", "is_correct": False},
        ],
    },
    {
        "text": "Which command shows SELinux status?",
        "explanation": "sestatus command displays the current SELinux status including mode, policy, and enforcement status.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/changing-selinux-states-and-modes_using-selinux",
        "points": 1,
        "answers": [
            {"text": "selinux-status", "is_correct": False},
            {"text": "sestatus", "is_correct": True},
            {"text": "getenforce", "is_correct": False},
            {"text": "seinfo", "is_correct": False},
        ],
    },
    {
        "text": "What are SELinux contexts?",
        "explanation": "SELinux contexts are security labels assigned to files, processes, and resources that define access permissions in the SELinux security model.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/getting-started-with-selinux_using-selinux",
        "points": 1,
        "answers": [
            {"text": "File permissions", "is_correct": False},
            {"text": "Security labels for access control", "is_correct": True},
            {"text": "System contexts", "is_correct": False},
            {"text": "Configuration contexts", "is_correct": False},
        ],
    },
    {
        "text": "Which command changes SELinux file contexts?",
        "explanation": "chcon command changes SELinux security contexts of files and directories, while restorecon restores default contexts.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/changing-selinux-states-and-modes_using-selinux",
        "points": 1,
        "answers": [
            {"text": "semanage", "is_correct": False},
            {"text": "chcon", "is_correct": True},
            {"text": "setsebool", "is_correct": False},
            {"text": "semodule", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of LVM in RHEL?",
        "explanation": "LVM (Logical Volume Manager) provides flexible disk space management by creating logical volumes that can be easily resized and managed.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/index",
        "points": 1,
        "answers": [
            {"text": "File system encryption", "is_correct": False},
            {"text": "Flexible volume management", "is_correct": True},
            {"text": "Network management", "is_correct": False},
            {"text": "Process management", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates a logical volume in LVM?",
        "explanation": "lvcreate command creates logical volumes within a volume group in LVM, specifying size and name parameters.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/managing-lvm-logical-volumes_configuring-and-managing-logical-volumes",
        "points": 1,
        "answers": [
            {"text": "vgcreate", "is_correct": False},
            {"text": "lvcreate", "is_correct": True},
            {"text": "pvcreate", "is_correct": False},
            {"text": "lvextend", "is_correct": False},
        ],
    },
    {
        "text": "What is Stratis in RHEL 8?",
        "explanation": "Stratis is a volume management solution in RHEL 8 that provides advanced storage features like snapshots and thin provisioning.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/setting-up-stratis-file-systems_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "File system checker", "is_correct": False},
            {"text": "Advanced volume management", "is_correct": True},
            {"text": "Network storage", "is_correct": False},
            {"text": "Backup tool", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages Stratis pools?",
        "explanation": "stratis command-line tool manages Stratis pools, filesystems, and storage configuration in RHEL 8.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/setting-up-stratis-file-systems_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "lvm", "is_correct": False},
            {"text": "stratis", "is_correct": True},
            {"text": "pool", "is_correct": False},
            {"text": "storage", "is_correct": False},
        ],
    },
    {
        "text": "What is VDO in Red Hat Enterprise Linux?",
        "explanation": "VDO (Virtual Data Optimizer) provides data reduction through deduplication and compression to optimize storage utilization.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/deploying-vdo_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "Video display optimization", "is_correct": False},
            {"text": "Data deduplication and compression", "is_correct": True},
            {"text": "Virtual disk optimization", "is_correct": False},
            {"text": "Volume disk organization", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates VDO volumes?",
        "explanation": "vdo command creates and manages VDO volumes for data deduplication and compression in RHEL.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/deploying-vdo_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "vdo-create", "is_correct": False},
            {"text": "vdo", "is_correct": True},
            {"text": "vdocreate", "is_correct": False},
            {"text": "volume", "is_correct": False},
        ],
    },
    {
        "text": "What is Podman in RHEL 8?",
        "explanation": "Podman is a daemonless container engine that manages OCI containers and pods, providing Docker-compatible functionality without requiring a daemon.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/index",
        "points": 1,
        "answers": [
            {"text": "Package manager", "is_correct": False},
            {"text": "Daemonless container engine", "is_correct": True},
            {"text": "Process manager", "is_correct": False},
            {"text": "Pod manager", "is_correct": False},
        ],
    },
    {
        "text": "Which command runs containers with Podman?",
        "explanation": "podman run command creates and runs containers from images, similar to docker run but without requiring a daemon.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/working-with-containers_building-running-and-managing-containers",
        "points": 1,
        "answers": [
            {"text": "container run", "is_correct": False},
            {"text": "podman run", "is_correct": True},
            {"text": "pod run", "is_correct": False},
            {"text": "run-container", "is_correct": False},
        ],
    },
    {
        "text": "What are Podman pods?",
        "explanation": "Podman pods are groups of containers that share the same network, PID, and IPC namespaces, similar to Kubernetes pods.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/working-with-pods_building-running-and-managing-containers",
        "points": 1,
        "answers": [
            {"text": "Container storage", "is_correct": False},
            {"text": "Groups of containers sharing namespaces", "is_correct": True},
            {"text": "Container networks", "is_correct": False},
            {"text": "Container images", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates systemd services for containers?",
        "explanation": "podman generate systemd creates systemd unit files for containers and pods, enabling container management through systemd.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/working-with-containers_building-running-and-managing-containers",
        "points": 1,
        "answers": [
            {"text": "systemctl generate", "is_correct": False},
            {"text": "podman generate systemd", "is_correct": True},
            {"text": "container-systemd", "is_correct": False},
            {"text": "podman systemd", "is_correct": False},
        ],
    },
    {
        "text": "What is dnf in RHEL 8?",
        "explanation": "dnf is the package manager in RHEL 8 that replaces yum, providing dependency resolution and package management capabilities.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_and_managing_software_packages/index",
        "points": 1,
        "answers": [
            {"text": "File manager", "is_correct": False},
            {"text": "Package manager", "is_correct": True},
            {"text": "Network manager", "is_correct": False},
            {"text": "Service manager", "is_correct": False},
        ],
    },
    {
        "text": "Which command installs packages with dnf?",
        "explanation": "dnf install command installs packages and their dependencies from configured repositories in RHEL 8.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_and_managing_software_packages/installing-software-packages_installing-and-managing-software-packages",
        "points": 1,
        "answers": [
            {"text": "dnf add", "is_correct": False},
            {"text": "dnf install", "is_correct": True},
            {"text": "dnf get", "is_correct": False},
            {"text": "dnf download", "is_correct": False},
        ],
    },
    {
        "text": "What are dnf modules in RHEL 8?",
        "explanation": "dnf modules provide multiple versions of software packages, allowing users to choose specific versions and profiles for applications.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_and_managing_software_packages/introduction-to-modules_installing-and-managing-software-packages",
        "points": 1,
        "answers": [
            {"text": "Package groups", "is_correct": False},
            {"text": "Multiple software versions and profiles", "is_correct": True},
            {"text": "System modules", "is_correct": False},
            {"text": "Kernel modules", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages dnf modules?",
        "explanation": "dnf module command manages application streams and modules, including enable, disable, install, and reset operations.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_and_managing_software_packages/introduction-to-modules_installing-and-managing-software-packages",
        "points": 1,
        "answers": [
            {"text": "dnf stream", "is_correct": False},
            {"text": "dnf module", "is_correct": True},
            {"text": "dnf version", "is_correct": False},
            {"text": "dnf profile", "is_correct": False},
        ],
    },
    {
        "text": "What is NetworkManager in RHEL?",
        "explanation": "NetworkManager provides dynamic network configuration and management, handling network connections, WiFi, VPNs, and network profiles.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/getting-started-with-networkmanager_configuring-and-managing-networking",
        "points": 1,
        "answers": [
            {"text": "Static network configuration", "is_correct": False},
            {"text": "Dynamic network management", "is_correct": True},
            {"text": "Network monitoring", "is_correct": False},
            {"text": "Network security", "is_correct": False},
        ],
    },
    {
        "text": "Which command configures NetworkManager connections?",
        "explanation": "nmcli (NetworkManager command line interface) configures and manages NetworkManager connections and settings.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/getting-started-with-networkmanager_configuring-and-managing-networking",
        "points": 1,
        "answers": [
            {"text": "netctl", "is_correct": False},
            {"text": "nmcli", "is_correct": True},
            {"text": "netconfig", "is_correct": False},
            {"text": "ifconfig", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Cockpit in RHEL?",
        "explanation": "Cockpit provides a web-based management interface for Linux servers, offering system administration through a browser.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/index",
        "points": 1,
        "answers": [
            {"text": "Command-line tool", "is_correct": False},
            {"text": "Web-based system management", "is_correct": True},
            {"text": "Container management", "is_correct": False},
            {"text": "Package management", "is_correct": False},
        ],
    },
    {
        "text": "Which service enables Cockpit web console?",
        "explanation": "cockpit.socket service enables the Cockpit web console, allowing web-based system administration access.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/getting-started-with-the-rhel-8-web-console_system-management-using-the-rhel-8-web-console",
        "points": 1,
        "answers": [
            {"text": "cockpit.service", "is_correct": False},
            {"text": "cockpit.socket", "is_correct": True},
            {"text": "cockpit-web.service", "is_correct": False},
            {"text": "web-console.service", "is_correct": False},
        ],
    },
    {
        "text": "What is Tuned in RHEL?",
        "explanation": "Tuned is a system tuning service that optimizes system performance by applying predefined or custom tuning profiles.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/monitoring_and_managing_system_status_and_performance/getting-started-with-tuned_monitoring-and-managing-system-status-and-performance",
        "points": 1,
        "answers": [
            {"text": "Network tuning", "is_correct": False},
            {"text": "System performance optimization", "is_correct": True},
            {"text": "Audio tuning", "is_correct": False},
            {"text": "Display tuning", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages Tuned profiles?",
        "explanation": "tuned-adm command manages Tuned profiles, including listing available profiles and setting active profiles for system optimization.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/monitoring_and_managing_system_status_and_performance/getting-started-with-tuned_monitoring-and-managing-system-status-and-performance",
        "points": 1,
        "answers": [
            {"text": "tuned", "is_correct": False},
            {"text": "tuned-adm", "is_correct": True},
            {"text": "tune", "is_correct": False},
            {"text": "profile", "is_correct": False},
        ],
    },
    {
        "text": "What is chronyd in RHEL 8?",
        "explanation": "chronyd is the NTP daemon in RHEL 8 that synchronizes system time with remote time servers for accurate timekeeping.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony-to-configure-ntp",
        "points": 1,
        "answers": [
            {"text": "Log daemon", "is_correct": False},
            {"text": "NTP time synchronization daemon", "is_correct": True},
            {"text": "Cron daemon", "is_correct": False},
            {"text": "System daemon", "is_correct": False},
        ],
    },
    {
        "text": "Which command configures chronyd?",
        "explanation": "chrony configuration is managed through /etc/chrony.conf file and chronyc command for runtime management.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony-to-configure-ntp",
        "points": 1,
        "answers": [
            {"text": "ntpconfig", "is_correct": False},
            {"text": "chronyc", "is_correct": True},
            {"text": "timeconfig", "is_correct": False},
            {"text": "ntpdate", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of rsyslog in RHEL?",
        "explanation": "rsyslog provides system logging services, collecting, processing, and forwarding log messages from various system components.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/viewing-and-managing-log-files_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "System monitoring", "is_correct": False},
            {"text": "System logging and log management", "is_correct": True},
            {"text": "Remote access", "is_correct": False},
            {"text": "System backup", "is_correct": False},
        ],
    },
    {
        "text": "Which file configures rsyslog?",
        "explanation": "The main rsyslog configuration file is /etc/rsyslog.conf, with additional configuration files in /etc/rsyslog.d/.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/viewing-and-managing-log-files_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "/etc/syslog.conf", "is_correct": False},
            {"text": "/etc/rsyslog.conf", "is_correct": True},
            {"text": "/etc/log.conf", "is_correct": False},
            {"text": "/var/log/rsyslog.conf", "is_correct": False},
        ],
    },
    {
        "text": "What is journald in RHEL 8?",
        "explanation": "journald is the systemd logging service that collects and stores log data in a structured, indexed format for efficient querying.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/viewing-and-managing-log-files_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "Journal manager", "is_correct": False},
            {"text": "systemd logging service", "is_correct": True},
            {"text": "Database daemon", "is_correct": False},
            {"text": "File system daemon", "is_correct": False},
        ],
    },
    {
        "text": "Which command queries systemd journal logs?",
        "explanation": "journalctl command queries and displays logs from the systemd journal, with various filtering and formatting options.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/viewing-and-managing-log-files_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "systemctl logs", "is_correct": False},
            {"text": "journalctl", "is_correct": True},
            {"text": "journal", "is_correct": False},
            {"text": "logctl", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of systemd timers?",
        "explanation": "systemd timers provide scheduling functionality similar to cron, with better integration with systemd services and more precise timing.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/scheduling-system-tasks_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "Time synchronization", "is_correct": False},
            {"text": "Task scheduling with systemd", "is_correct": True},
            {"text": "System timing", "is_correct": False},
            {"text": "Timer display", "is_correct": False},
        ],
    },
    {
        "text": "Which command lists systemd timers?",
        "explanation": "systemctl list-timers displays all systemd timers with their next run times and associated services.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/scheduling-system-tasks_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "systemctl timers", "is_correct": False},
            {"text": "systemctl list-timers", "is_correct": True},
            {"text": "timer list", "is_correct": False},
            {"text": "systemctl show-timers", "is_correct": False},
        ],
    },
    {
        "text": "What is Kerberos in enterprise authentication?",
        "explanation": "Kerberos is a network authentication protocol that provides secure authentication using tickets and encryption for enterprise environments.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_authentication_and_authorization_in_rhel/configuring-sssd-to-use-ldap-and-require-tls-authentication_configuring-authentication-and-authorization-in-rhel",
        "points": 1,
        "answers": [
            {"text": "Database system", "is_correct": False},
            {"text": "Network authentication protocol", "is_correct": True},
            {"text": "File system", "is_correct": False},
            {"text": "Monitoring system", "is_correct": False},
        ],
    },
    {
        "text": "What is SSSD in RHEL?",
        "explanation": "SSSD (System Security Services Daemon) provides centralized authentication and identity services, integrating with LDAP, Active Directory, and Kerberos.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_authentication_and_authorization_in_rhel/understanding-sssd-and-its-benefits_configuring-authentication-and-authorization-in-rhel",
        "points": 1,
        "answers": [
            {"text": "SSH daemon", "is_correct": False},
            {"text": "Centralized authentication service", "is_correct": True},
            {"text": "System service daemon", "is_correct": False},
            {"text": "Security scanning daemon", "is_correct": False},
        ],
    },
    {
        "text": "Which file configures SSSD?",
        "explanation": "The main SSSD configuration file is /etc/sssd/sssd.conf, which defines domains, providers, and authentication settings.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_authentication_and_authorization_in_rhel/understanding-sssd-and-its-benefits_configuring-authentication-and-authorization-in-rhel",
        "points": 1,
        "answers": [
            {"text": "/etc/sssd.conf", "is_correct": False},
            {"text": "/etc/sssd/sssd.conf", "is_correct": True},
            {"text": "/etc/sss.conf", "is_correct": False},
            {"text": "/var/sssd/config", "is_correct": False},
        ],
    },
    {
        "text": "What is IdM (Identity Management) in Red Hat?",
        "explanation": "Red Hat Identity Management provides centralized authentication, authorization, and identity services for Linux environments using LDAP, Kerberos, and DNS.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_identity_management/index",
        "points": 1,
        "answers": [
            {"text": "File management", "is_correct": False},
            {"text": "Centralized identity and authentication", "is_correct": True},
            {"text": "Image management", "is_correct": False},
            {"text": "Infrastructure management", "is_correct": False},
        ],
    },
    {
        "text": "Which command joins a system to IdM domain?",
        "explanation": "ipa-client-install command enrolls a system as a client to Red Hat Identity Management domain.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_identity_management/installing-an-ipa-client_installing-identity-management",
        "points": 1,
        "answers": [
            {"text": "idm-join", "is_correct": False},
            {"text": "ipa-client-install", "is_correct": True},
            {"text": "ipa-join", "is_correct": False},
            {"text": "realm join", "is_correct": False},
        ],
    },
]
