"""Red Hat Certified System Administrator (RHCSA) Certification"""

CERTIFICATION = {
    "name": "Red Hat Certified System Administrator (RHCSA)",
    "description": "Red Hat Enterprise Linux system administration skills",
    "slug": "rhcsa",
    "level": "Professional",
    "duration": 150,
    "questions_count": 50,
    "category_slug": "linux",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which command is used to manage systemd services in RHEL?",
        "explanation": "The systemctl command is the primary tool for managing systemd services in Red Hat Enterprise Linux and other systemd-based distributions.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-services-with-systemd_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "service", "is_correct": False},
            {"text": "systemctl", "is_correct": True},
            {"text": "chkconfig", "is_correct": False},
            {"text": "init", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates a new user account in RHEL?",
        "explanation": "The useradd command creates new user accounts in Red Hat Enterprise Linux, setting up home directories and default settings.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-users-and-groups_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "adduser", "is_correct": False},
            {"text": "useradd", "is_correct": True},
            {"text": "newuser", "is_correct": False},
            {"text": "mkuser", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to change user password in RHEL?",
        "explanation": "The passwd command is used to change user passwords in Red Hat Enterprise Linux systems.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-users-and-groups_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "password", "is_correct": False},
            {"text": "passwd", "is_correct": True},
            {"text": "chpasswd", "is_correct": False},
            {"text": "setpass", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains user account information in RHEL?",
        "explanation": "The /etc/passwd file contains user account information including usernames, UIDs, GIDs, home directories, and default shells.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-users-and-groups_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "/etc/shadow", "is_correct": False},
            {"text": "/etc/passwd", "is_correct": True},
            {"text": "/etc/group", "is_correct": False},
            {"text": "/etc/users", "is_correct": False},
        ],
    },
    {
        "text": "What command creates a new group in RHEL?",
        "explanation": "The groupadd command creates new groups in Red Hat Enterprise Linux systems.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-users-and-groups_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "addgroup", "is_correct": False},
            {"text": "groupadd", "is_correct": True},
            {"text": "newgroup", "is_correct": False},
            {"text": "mkgroup", "is_correct": False},
        ],
    },
    {
        "text": "Which command adds a user to a group?",
        "explanation": "The usermod -aG command adds a user to additional groups without removing them from existing groups.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-users-and-groups_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "adduser", "is_correct": False},
            {"text": "usermod -aG", "is_correct": True},
            {"text": "groupmod", "is_correct": False},
            {"text": "gpasswd", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of sudo in RHEL?",
        "explanation": "sudo allows users to execute commands with the privileges of another user, typically root, for administrative tasks.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-sudo-access_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "Switch user", "is_correct": False},
            {"text": "Execute commands as another user", "is_correct": True},
            {"text": "Super user", "is_correct": False},
            {"text": "System update", "is_correct": False},
        ],
    },
    {
        "text": "Which file configures sudo permissions?",
        "explanation": "The /etc/sudoers file configures sudo permissions and rules for users and groups in Red Hat Enterprise Linux.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-sudo-access_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "/etc/sudo.conf", "is_correct": False},
            {"text": "/etc/sudoers", "is_correct": True},
            {"text": "/etc/sudo/config", "is_correct": False},
            {"text": "/var/sudo/sudoers", "is_correct": False},
        ],
    },
    {
        "text": "What command is used to edit the sudoers file safely?",
        "explanation": "The visudo command safely edits the sudoers file with syntax checking to prevent configuration errors.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-sudo-access_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "vi /etc/sudoers", "is_correct": False},
            {"text": "visudo", "is_correct": True},
            {"text": "sudo-edit", "is_correct": False},
            {"text": "sudoedit", "is_correct": False},
        ],
    },
    {
        "text": "Which command is used to install packages in RHEL 8?",
        "explanation": "The dnf command is the package manager in RHEL 8 that replaces yum for installing, updating, and removing packages.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_and_managing_software_packages/index",
        "points": 1,
        "answers": [
            {"text": "yum", "is_correct": False},
            {"text": "dnf", "is_correct": True},
            {"text": "rpm", "is_correct": False},
            {"text": "apt", "is_correct": False},
        ],
    },
    {
        "text": "What command searches for available packages in RHEL?",
        "explanation": "The dnf search command searches for packages in the configured repositories based on package names and descriptions.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_and_managing_software_packages/searching-for-software-packages_installing-and-managing-software-packages",
        "points": 1,
        "answers": [
            {"text": "dnf find", "is_correct": False},
            {"text": "dnf search", "is_correct": True},
            {"text": "dnf list", "is_correct": False},
            {"text": "dnf query", "is_correct": False},
        ],
    },
    {
        "text": "Which command removes packages in RHEL?",
        "explanation": "The dnf remove command uninstalls packages and their dependencies from Red Hat Enterprise Linux systems.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_and_managing_software_packages/removing-software-packages_installing-and-managing-software-packages",
        "points": 1,
        "answers": [
            {"text": "dnf delete", "is_correct": False},
            {"text": "dnf remove", "is_correct": True},
            {"text": "dnf uninstall", "is_correct": False},
            {"text": "dnf erase", "is_correct": False},
        ],
    },
    {
        "text": "What command updates all packages in RHEL?",
        "explanation": "The dnf update command updates all installed packages to their latest available versions in RHEL.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_and_managing_software_packages/updating-software-packages_installing-and-managing-software-packages",
        "points": 1,
        "answers": [
            {"text": "dnf upgrade", "is_correct": False},
            {"text": "dnf update", "is_correct": True},
            {"text": "dnf refresh", "is_correct": False},
            {"text": "dnf sync", "is_correct": False},
        ],
    },
    {
        "text": "Which command enables a systemd service to start at boot?",
        "explanation": "The systemctl enable command creates symbolic links to enable a service to start automatically during the boot process.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-services-with-systemd_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "systemctl start", "is_correct": False},
            {"text": "systemctl enable", "is_correct": True},
            {"text": "systemctl activate", "is_correct": False},
            {"text": "systemctl boot", "is_correct": False},
        ],
    },
    {
        "text": "What command starts a systemd service immediately?",
        "explanation": "The systemctl start command starts a systemd service immediately without enabling it for boot.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-services-with-systemd_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "systemctl run", "is_correct": False},
            {"text": "systemctl start", "is_correct": True},
            {"text": "systemctl begin", "is_correct": False},
            {"text": "systemctl launch", "is_correct": False},
        ],
    },
    {
        "text": "Which command checks the status of a systemd service?",
        "explanation": "The systemctl status command displays the current status, recent log entries, and runtime information for a systemd service.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-services-with-systemd_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "systemctl info", "is_correct": False},
            {"text": "systemctl status", "is_correct": True},
            {"text": "systemctl show", "is_correct": False},
            {"text": "systemctl check", "is_correct": False},
        ],
    },
    {
        "text": "What command creates a filesystem on a partition in RHEL?",
        "explanation": "The mkfs command creates filesystems on partitions or devices, with options for different filesystem types like ext4, xfs, etc.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/index",
        "points": 1,
        "answers": [
            {"text": "format", "is_correct": False},
            {"text": "mkfs", "is_correct": True},
            {"text": "filesystem", "is_correct": False},
            {"text": "create-fs", "is_correct": False},
        ],
    },
    {
        "text": "Which command mounts a filesystem in RHEL?",
        "explanation": "The mount command attaches filesystems to the directory tree at specified mount points in Red Hat Enterprise Linux.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/mounting-file-systems_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "attach", "is_correct": False},
            {"text": "mount", "is_correct": True},
            {"text": "connect", "is_correct": False},
            {"text": "link", "is_correct": False},
        ],
    },
    {
        "text": "What file contains filesystem mount information in RHEL?",
        "explanation": "The /etc/fstab file contains filesystem table information used for automatic mounting at boot time.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/mounting-file-systems_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "/etc/mtab", "is_correct": False},
            {"text": "/etc/fstab", "is_correct": True},
            {"text": "/etc/mounts", "is_correct": False},
            {"text": "/proc/mounts", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays disk usage by filesystem?",
        "explanation": "The df command displays disk space usage for mounted filesystems, showing available and used space.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/monitoring-file-systems_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "du", "is_correct": False},
            {"text": "df", "is_correct": True},
            {"text": "disk", "is_correct": False},
            {"text": "space", "is_correct": False},
        ],
    },
    {
        "text": "What command shows directory size in RHEL?",
        "explanation": "The du command displays disk usage for directories and files, showing how much space they consume.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/monitoring-file-systems_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "df", "is_correct": False},
            {"text": "du", "is_correct": True},
            {"text": "size", "is_correct": False},
            {"text": "ls -s", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates partitions in RHEL?",
        "explanation": "The fdisk command is used to create, modify, and manage disk partitions in Red Hat Enterprise Linux.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/partitioning-disks_managing-file-systems",
        "points": 1,
        "answers": [
            {"text": "partition", "is_correct": False},
            {"text": "fdisk", "is_correct": True},
            {"text": "parted", "is_correct": False},
            {"text": "disk", "is_correct": False},
        ],
    },
    {
        "text": "What command changes file permissions in RHEL?",
        "explanation": "The chmod command changes file and directory permissions using numeric or symbolic notation in Red Hat Enterprise Linux.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-file-permissions_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "chown", "is_correct": False},
            {"text": "chmod", "is_correct": True},
            {"text": "chgrp", "is_correct": False},
            {"text": "permission", "is_correct": False},
        ],
    },
    {
        "text": "Which command changes file ownership in RHEL?",
        "explanation": "The chown command changes the owner and group ownership of files and directories in Red Hat Enterprise Linux.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-file-permissions_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "chmod", "is_correct": False},
            {"text": "chown", "is_correct": True},
            {"text": "owner", "is_correct": False},
            {"text": "own", "is_correct": False},
        ],
    },
    {
        "text": "What are the standard RHEL file permission values for rwx?",
        "explanation": "In RHEL, file permissions are represented as: read (4), write (2), execute (1). Full permissions (rwx) = 4+2+1 = 7.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-file-permissions_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "rwx = 6", "is_correct": False},
            {"text": "rwx = 7", "is_correct": True},
            {"text": "rwx = 8", "is_correct": False},
            {"text": "rwx = 9", "is_correct": False},
        ],
    },
    {
        "text": "Which command creates a symbolic link in RHEL?",
        "explanation": "The ln -s command creates symbolic links (symlinks) that point to other files or directories.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-files-and-directories_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "link", "is_correct": False},
            {"text": "ln -s", "is_correct": True},
            {"text": "symlink", "is_correct": False},
            {"text": "soft-link", "is_correct": False},
        ],
    },
    {
        "text": "What command finds files by name in RHEL?",
        "explanation": "The find command searches for files and directories based on various criteria including name, size, permissions, and modification time.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/finding-files-and-directories_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "locate", "is_correct": False},
            {"text": "find", "is_correct": True},
            {"text": "search", "is_correct": False},
            {"text": "which", "is_correct": False},
        ],
    },
    {
        "text": "Which command compresses files in RHEL?",
        "explanation": "The gzip command compresses files using the gzip compression algorithm, creating .gz files for space efficiency.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/archiving-and-compressing-files_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "compress", "is_correct": False},
            {"text": "gzip", "is_correct": True},
            {"text": "zip", "is_correct": False},
            {"text": "pack", "is_correct": False},
        ],
    },
    {
        "text": "What command creates compressed archives in RHEL?",
        "explanation": "The tar command with compression options (like tar -czf) creates compressed archives combining multiple files into a single archive file.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/archiving-and-compressing-files_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "archive", "is_correct": False},
            {"text": "tar", "is_correct": True},
            {"text": "zip", "is_correct": False},
            {"text": "pack", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays running processes in RHEL?",
        "explanation": "The ps command displays information about currently running processes on the system with various formatting options.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/monitoring-and-managing-processes_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "top", "is_correct": False},
            {"text": "ps", "is_correct": True},
            {"text": "jobs", "is_correct": False},
            {"text": "process", "is_correct": False},
        ],
    },
    {
        "text": "What command kills processes by PID in RHEL?",
        "explanation": "The kill command terminates processes by sending signals to them using their process ID (PID).",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/monitoring-and-managing-processes_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "stop", "is_correct": False},
            {"text": "kill", "is_correct": True},
            {"text": "terminate", "is_correct": False},
            {"text": "end", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays real-time process information?",
        "explanation": "The top command displays real-time information about running processes, including CPU and memory usage statistics.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/monitoring-and-managing-processes_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "ps", "is_correct": False},
            {"text": "top", "is_correct": True},
            {"text": "htop", "is_correct": False},
            {"text": "monitor", "is_correct": False},
        ],
    },
    {
        "text": "What command schedules tasks in RHEL?",
        "explanation": "The crontab command is used to schedule and manage cron jobs for automated task execution in Red Hat Enterprise Linux.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/scheduling-system-tasks_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "schedule", "is_correct": False},
            {"text": "crontab", "is_correct": True},
            {"text": "cron", "is_correct": False},
            {"text": "at", "is_correct": False},
        ],
    },
    {
        "text": "Which command configures network interfaces in RHEL 8?",
        "explanation": "The nmcli command (NetworkManager command line interface) is used to configure network connections in RHEL 8.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/getting-started-with-networkmanager_configuring-and-managing-networking",
        "points": 1,
        "answers": [
            {"text": "ifconfig", "is_correct": False},
            {"text": "nmcli", "is_correct": True},
            {"text": "netconfig", "is_correct": False},
            {"text": "ip", "is_correct": False},
        ],
    },
    {
        "text": "What command tests network connectivity in RHEL?",
        "explanation": "The ping command sends ICMP echo request packets to test network connectivity and measure round-trip time to a destination.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/testing-network-connectivity_configuring-and-managing-networking",
        "points": 1,
        "answers": [
            {"text": "test", "is_correct": False},
            {"text": "ping", "is_correct": True},
            {"text": "connect", "is_correct": False},
            {"text": "trace", "is_correct": False},
        ],
    },
    {
        "text": "Which file contains DNS server configuration in RHEL?",
        "explanation": "The /etc/resolv.conf file contains DNS resolver configuration including nameserver entries for domain name resolution.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/configuring-hostname-resolution_configuring-and-managing-networking",
        "points": 1,
        "answers": [
            {"text": "/etc/hosts", "is_correct": False},
            {"text": "/etc/resolv.conf", "is_correct": True},
            {"text": "/etc/dns.conf", "is_correct": False},
            {"text": "/etc/nameserver", "is_correct": False},
        ],
    },
    {
        "text": "What command displays network interface configuration?",
        "explanation": "The ip addr command displays network interface configuration including IP addresses, netmasks, and interface status.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/viewing-and-configuring-network-interfaces_configuring-and-managing-networking",
        "points": 1,
        "answers": [
            {"text": "ifconfig", "is_correct": False},
            {"text": "ip addr", "is_correct": True},
            {"text": "netstat", "is_correct": False},
            {"text": "network", "is_correct": False},
        ],
    },
    {
        "text": "Which command manages firewall rules in RHEL 8?",
        "explanation": "The firewall-cmd command is the command-line interface for managing firewalld zones, services, and rules in RHEL 8.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/using-and-configuring-firewalls_securing-networks",
        "points": 1,
        "answers": [
            {"text": "iptables", "is_correct": False},
            {"text": "firewall-cmd", "is_correct": True},
            {"text": "ufw", "is_correct": False},
            {"text": "netfilter", "is_correct": False},
        ],
    },
    {
        "text": "What command displays system log messages in RHEL 8?",
        "explanation": "The journalctl command queries and displays logs from the systemd journal in RHEL 8 systems.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/viewing-and-managing-log-files_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "syslog", "is_correct": False},
            {"text": "journalctl", "is_correct": True},
            {"text": "dmesg", "is_correct": False},
            {"text": "logview", "is_correct": False},
        ],
    },
    {
        "text": "Which command shows system uptime and load in RHEL?",
        "explanation": "The uptime command displays how long the system has been running and the current load averages.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/monitoring_and_managing_system_status_and_performance/monitoring-performance-with-performance-analysis-tools_monitoring-and-managing-system-status-and-performance",
        "points": 1,
        "answers": [
            {"text": "runtime", "is_correct": False},
            {"text": "uptime", "is_correct": True},
            {"text": "load", "is_correct": False},
            {"text": "sysinfo", "is_correct": False},
        ],
    },
    {
        "text": "What command displays memory usage in RHEL?",
        "explanation": "The free command displays memory usage information including total, used, free, and swap space statistics.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/monitoring_and_managing_system_status_and_performance/monitoring-performance-with-performance-analysis-tools_monitoring-and-managing-system-status-and-performance",
        "points": 1,
        "answers": [
            {"text": "memory", "is_correct": False},
            {"text": "free", "is_correct": True},
            {"text": "ram", "is_correct": False},
            {"text": "meminfo", "is_correct": False},
        ],
    },
    {
        "text": "Which command sets the system hostname in RHEL?",
        "explanation": "The hostnamectl command manages the system hostname and related metadata in RHEL systems using systemd.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/changing-the-hostname_configuring-basic-system-settings",
        "points": 1,
        "answers": [
            {"text": "hostname", "is_correct": False},
            {"text": "hostnamectl", "is_correct": True},
            {"text": "sethostname", "is_correct": False},
            {"text": "name", "is_correct": False},
        ],
    },
    {
        "text": "What command synchronizes system time in RHEL 8?",
        "explanation": "The timedatectl command manages system time and date settings, including NTP synchronization in RHEL 8.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony-to-configure-ntp",
        "points": 1,
        "answers": [
            {"text": "ntpdate", "is_correct": False},
            {"text": "timedatectl", "is_correct": True},
            {"text": "date", "is_correct": False},
            {"text": "time", "is_correct": False},
        ],
    },
    {
        "text": "Which command displays system hardware information?",
        "explanation": "The lshw command displays detailed hardware information about the system including CPU, memory, and devices.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/monitoring_and_managing_system_status_and_performance/viewing-hardware-information_monitoring-and-managing-system-status-and-performance",
        "points": 1,
        "answers": [
            {"text": "hardware", "is_correct": False},
            {"text": "lshw", "is_correct": True},
            {"text": "hwinfo", "is_correct": False},
            {"text": "sysinfo", "is_correct": False},
        ],
    },
    {
        "text": "What command creates a logical volume in LVM?",
        "explanation": "The lvcreate command creates logical volumes within a volume group in LVM (Logical Volume Manager).",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/managing-lvm-logical-volumes_configuring-and-managing-logical-volumes",
        "points": 1,
        "answers": [
            {"text": "vgcreate", "is_correct": False},
            {"text": "lvcreate", "is_correct": True},
            {"text": "pvcreate", "is_correct": False},
            {"text": "lvmcreate", "is_correct": False},
        ],
    },
    {
        "text": "Which command extends a logical volume in LVM?",
        "explanation": "The lvextend command extends the size of logical volumes in LVM, allowing dynamic expansion of storage.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/modifying-lvm-logical-volumes_configuring-and-managing-logical-volumes",
        "points": 1,
        "answers": [
            {"text": "lvgrow", "is_correct": False},
            {"text": "lvextend", "is_correct": True},
            {"text": "lvexpand", "is_correct": False},
            {"text": "lvresize", "is_correct": False},
        ],
    },
    {
        "text": "What command creates a volume group in LVM?",
        "explanation": "The vgcreate command creates volume groups from physical volumes in LVM systems.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/managing-lvm-volume-groups_configuring-and-managing-logical-volumes",
        "points": 1,
        "answers": [
            {"text": "lvcreat", "is_correct": False},
            {"text": "vgcreate", "is_correct": True},
            {"text": "pvcreate", "is_correct": False},
            {"text": "volgroup", "is_correct": False},
        ],
    },
    {
        "text": "Which command makes a disk available for LVM?",
        "explanation": "The pvcreate command initializes physical volumes (disks or partitions) for use with LVM.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/managing-lvm-physical-volumes_configuring-and-managing-logical-volumes",
        "points": 1,
        "answers": [
            {"text": "lvcreate", "is_correct": False},
            {"text": "pvcreate", "is_correct": True},
            {"text": "vgcreate", "is_correct": False},
            {"text": "diskcreate", "is_correct": False},
        ],
    },
    {
        "text": "What is SELinux enforcement mode in RHEL?",
        "explanation": "SELinux enforcement mode actively enforces security policies and blocks actions that violate the configured security rules.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/changing-selinux-states-and-modes_using-selinux",
        "points": 1,
        "answers": [
            {"text": "Permissive mode", "is_correct": False},
            {"text": "Enforcing mode actively blocks violations", "is_correct": True},
            {"text": "Disabled mode", "is_correct": False},
            {"text": "Monitor mode", "is_correct": False},
        ],
    },
    {
        "text": "Which command shows SELinux status in RHEL?",
        "explanation": "The sestatus command displays the current SELinux status including mode, policy, and enforcement status.",
        "reference": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/changing-selinux-states-and-modes_using-selinux",
        "points": 1,
        "answers": [
            {"text": "selinux-status", "is_correct": False},
            {"text": "sestatus", "is_correct": True},
            {"text": "getenforce", "is_correct": False},
            {"text": "seinfo", "is_correct": False},
        ],
    },
]
