"""Certified Information Systems Auditor (CISA) Certification"""

CERTIFICATION = {
    "name": "Certified Information Systems Auditor (CISA)",
    "description": "Information systems auditing and control",
    "slug": "cisa",
    "level": "Professional",
    "duration": 270,
    "questions_count": 90,
    "category_slug": "cybersecurity",
    "is_active": True,
}

QUESTIONS = [{"text": "What is the primary objective of information systems auditing?",
              "explanation": "The primary objective of IS auditing is to evaluate the adequacy and effectiveness of controls within an IT environment to ensure confidentiality, integrity, and availability of information.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "To evaluate adequacy and effectiveness of IT controls",
                           "is_correct": True,
                           },
                          {"text": "To implement new technology systems",
                           "is_correct": False},
                          {"text": "To manage IT operations",
                           "is_correct": False},
                          {"text": "To develop software applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which audit approach provides the most comprehensive evaluation of IT controls?",
              "explanation": "Risk-based auditing focuses audit efforts on areas of highest risk, providing the most effective and comprehensive evaluation of IT controls.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "Compliance-based auditing",
                           "is_correct": False},
                          {"text": "Risk-based auditing",
                           "is_correct": True},
                          {"text": "Process-based auditing",
                           "is_correct": False},
                          {"text": "Technology-based auditing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of audit evidence in information systems auditing?",
              "explanation": "Audit evidence provides the factual basis to support audit findings, conclusions, and recommendations regarding the effectiveness of IT controls.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "To support audit findings and conclusions",
                           "is_correct": True},
                          {"text": "To train new auditors",
                           "is_correct": False},
                          {"text": "To document system requirements",
                           "is_correct": False},
                          {"text": "To create user manuals",
                           "is_correct": False},
                          ],
              },
             {"text": "Which sampling technique is most appropriate for testing IT controls?",
              "explanation": "Statistical sampling provides a scientific basis for drawing conclusions about the population and is most appropriate for testing IT controls.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "Judgmental sampling",
                           "is_correct": False},
                          {"text": "Statistical sampling",
                           "is_correct": True},
                          {"text": "Random sampling",
                           "is_correct": False},
                          {"text": "Convenience sampling",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary focus of a substantive test in IS auditing?",
              "explanation": "Substantive tests focus on detecting material misstatements in data and transactions, examining the actual content and accuracy of information.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "Testing the effectiveness of controls",
                           "is_correct": False},
                          {"text": "Detecting material misstatements in data",
                           "is_correct": True},
                          {"text": "Evaluating system performance",
                           "is_correct": False},
                          {"text": "Assessing user satisfaction",
                           "is_correct": False},
                          ],
              },
             {"text": "Which type of audit provides an independent assessment of service organization controls?",
              "explanation": "SOC (Service Organization Control) audits, particularly SOC 2 Type II, provide independent assessments of service organization controls over security, availability, processing integrity, confidentiality, and privacy.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "Internal audit",
                           "is_correct": False},
                          {"text": "SOC audit",
                           "is_correct": True},
                          {"text": "Compliance audit",
                           "is_correct": False},
                          {"text": "Operational audit",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of walk-through testing in IS auditing?",
              "explanation": "Walk-through testing traces a transaction from initiation to completion to understand the process flow and identify control points.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "To understand process flow and control points",
                           "is_correct": True,
                           },
                          {"text": "To test system performance",
                           "is_correct": False},
                          {"text": "To validate user access rights",
                           "is_correct": False},
                          {"text": "To check data accuracy",
                           "is_correct": False},
                          ],
              },
             {"text": "Which audit technique is most effective for continuous monitoring?",
              "explanation": "Computer-Assisted Audit Techniques (CAATs) are most effective for continuous monitoring as they can automatically analyze large volumes of data in real-time.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "Manual review",
                           "is_correct": False},
                          {"text": "Computer-Assisted Audit Techniques (CAATs)",
                           "is_correct": True},
                          {"text": "Interview techniques",
                           "is_correct": False},
                          {"text": "Observation methods",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary characteristic of preventive controls?",
              "explanation": "Preventive controls are designed to prevent errors or irregularities from occurring in the first place, rather than detecting them after they occur.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "They prevent errors from occurring",
                           "is_correct": True},
                          {"text": "They detect errors after occurrence",
                           "is_correct": False},
                          {"text": "They correct errors automatically",
                           "is_correct": False},
                          {"text": "They monitor system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which documentation standard is essential for audit trail requirements?",
              "explanation": "Audit trails must provide a complete, accurate, and tamper-evident record of all transactions and system activities to support accountability and forensic analysis.",
              "reference": "https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/the-fundamentals-of-information-systems-auditing",
              "points": 1,
              "answers": [{"text": "Complete and tamper-evident transaction records",
                           "is_correct": True,
                           },
                          {"text": "Summary reports only",
                           "is_correct": False},
                          {"text": "User activity logs only",
                           "is_correct": False},
                          {"text": "System error logs only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of IT governance?",
              "explanation": "IT governance ensures that IT investments support business objectives, manage IT-related risks, and deliver value to stakeholders through proper oversight and control.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Align IT investments with business objectives",
                           "is_correct": True,
                           },
                          {"text": "Reduce IT operational costs",
                           "is_correct": False},
                          {"text": "Implement new technologies",
                           "is_correct": False},
                          {"text": "Manage IT staff performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which framework is most commonly used for IT governance?",
              "explanation": "COBIT (Control Objectives for Information and Related Technologies) is the most widely adopted framework for IT governance and management.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "ITIL",
                           "is_correct": False},
                          {"text": "COBIT",
                           "is_correct": True},
                          {"text": "ISO 27001",
                           "is_correct": False},
                          {"text": "NIST",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the role of an IT steering committee?",
              "explanation": "An IT steering committee provides strategic direction, prioritizes IT investments, and ensures alignment between IT initiatives and business strategy.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Provide strategic IT direction and oversight",
                           "is_correct": True,
                           },
                          {"text": "Manage daily IT operations",
                           "is_correct": False},
                          {"text": "Develop software applications",
                           "is_correct": False},
                          {"text": "Maintain IT infrastructure",
                           "is_correct": False},
                          ],
              },
             {"text": "Which metric is most important for measuring IT governance effectiveness?",
              "explanation": "Business-IT alignment measures how well IT initiatives support and enable business objectives, which is the primary goal of IT governance.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "IT budget utilization",
                           "is_correct": False},
                          {"text": "Business-IT alignment",
                           "is_correct": True},
                          {"text": "System uptime",
                           "is_correct": False},
                          {"text": "User satisfaction",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary focus of IT portfolio management?",
              "explanation": "IT portfolio management focuses on optimizing the mix of IT investments to maximize business value while managing risk and resource constraints.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Optimizing IT investments for maximum business value",
                           "is_correct": True,
                           },
                          {"text": "Managing IT project schedules",
                           "is_correct": False},
                          {"text": "Reducing IT operational costs",
                           "is_correct": False},
                          {"text": "Implementing new technologies",
                           "is_correct": False},
                          ],
              },
             {"text": "Which principle is fundamental to effective IT governance?",
              "explanation": "Accountability ensures that roles, responsibilities, and decision rights are clearly defined and that individuals are held responsible for IT-related decisions and outcomes.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Cost reduction",
                           "is_correct": False},
                          {"text": "Accountability",
                           "is_correct": True},
                          {"text": "Technology innovation",
                           "is_correct": False},
                          {"text": "Process automation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of IT performance measurement in governance?",
              "explanation": "IT performance measurement provides objective data to assess whether IT is delivering expected value and meeting strategic objectives.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Assess IT value delivery and strategic achievement",
                           "is_correct": True,
                           },
                          {"text": "Compare IT costs with competitors",
                           "is_correct": False},
                          {"text": "Evaluate individual employee performance",
                           "is_correct": False},
                          {"text": "Measure system technical performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which governance structure ensures proper segregation of duties?",
              "explanation": "A three lines of defense model provides proper segregation by separating operational management, risk management, and independent assurance functions.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Centralized IT management",
                           "is_correct": False},
                          {"text": "Three lines of defense model",
                           "is_correct": True},
                          {"text": "Matrix organizational structure",
                           "is_correct": False},
                          {"text": "Flat organizational structure",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary objective of IT risk governance?",
              "explanation": "IT risk governance ensures that IT-related risks are identified, assessed, and managed in alignment with the organization's risk appetite and business objectives.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Manage IT risks aligned with business objectives",
                           "is_correct": True,
                           },
                          {"text": "Eliminate all IT risks",
                           "is_correct": False},
                          {"text": "Reduce IT operational costs",
                           "is_correct": False},
                          {"text": "Implement security controls",
                           "is_correct": False},
                          ],
              },
             {"text": "Which factor is most critical for successful IT governance implementation?",
              "explanation": "Executive leadership commitment is essential for successful IT governance as it provides the authority, resources, and organizational support needed for effective implementation.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Advanced technology tools",
                           "is_correct": False},
                          {"text": "Executive leadership commitment",
                           "is_correct": True},
                          {"text": "Large IT budget",
                           "is_correct": False},
                          {"text": "Detailed policies and procedures",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of a business case in IT project initiation?",
              "explanation": "A business case justifies the IT investment by demonstrating expected benefits, costs, risks, and alignment with business objectives.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Justify IT investment and demonstrate business value",
                           "is_correct": True,
                           },
                          {"text": "Define technical specifications",
                           "is_correct": False},
                          {"text": "Allocate project resources",
                           "is_correct": False},
                          {"text": "Create project timeline",
                           "is_correct": False},
                          ],
              },
             {"text": "Which development methodology emphasizes iterative development and customer collaboration?",
              "explanation": "Agile methodology emphasizes iterative development, customer collaboration, responding to change, and delivering working software frequently.",
              "reference": "https://agilemanifesto.org/",
              "points": 1,
              "answers": [{"text": "Waterfall",
                           "is_correct": False},
                          {"text": "Agile",
                           "is_correct": True},
                          {"text": "Spiral",
                           "is_correct": False},
                          {"text": "V-Model",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary objective of requirements management?",
              "explanation": "Requirements management ensures that stakeholder needs are accurately captured, documented, and maintained throughout the project lifecycle.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Capture and maintain stakeholder requirements",
                           "is_correct": True,
                           },
                          {"text": "Reduce project costs",
                           "is_correct": False},
                          {"text": "Accelerate development timeline",
                           "is_correct": False},
                          {"text": "Minimize technical complexity",
                           "is_correct": False},
                          ],
              },
             {"text": "Which testing approach provides the highest level of assurance?",
              "explanation": "Independent testing by third parties provides the highest level of assurance as it eliminates potential conflicts of interest and bias.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Developer self-testing",
                           "is_correct": False},
                          {"text": "Peer review testing",
                           "is_correct": False},
                          {"text": "Independent third-party testing",
                           "is_correct": True},
                          {"text": "Automated testing only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of configuration management in system development?",
              "explanation": "Configuration management controls changes to system components and maintains the integrity of the system throughout its lifecycle.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Control changes and maintain system integrity",
                           "is_correct": True,
                           },
                          {"text": "Optimize system performance",
                           "is_correct": False},
                          {"text": "Reduce development costs",
                           "is_correct": False},
                          {"text": "Accelerate deployment",
                           "is_correct": False},
                          ],
              },
             {"text": "Which phase gate review is most critical for project success?",
              "explanation": "The requirements review gate is most critical as it ensures stakeholder needs are properly understood before significant resources are invested.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Design review",
                           "is_correct": False},
                          {"text": "Requirements review",
                           "is_correct": True},
                          {"text": "Testing review",
                           "is_correct": False},
                          {"text": "Deployment review",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of using a formal change control process?",
              "explanation": "Formal change control ensures all changes are evaluated for impact, approved by appropriate authorities, and properly documented.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Ensure changes are evaluated and approved",
                           "is_correct": True},
                          {"text": "Reduce development time",
                           "is_correct": False},
                          {"text": "Lower project costs",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which approach best ensures security is built into systems from the beginning?",
              "explanation": "Security by design integrates security considerations into every phase of the development lifecycle from initial planning to deployment.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Security testing at the end",
                           "is_correct": False},
                          {"text": "Security by design",
                           "is_correct": True},
                          {"text": "Post-implementation security review",
                           "is_correct": False},
                          {"text": "Third-party security assessment",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of user acceptance testing (UAT)?",
              "explanation": "UAT validates that the system meets business requirements and is acceptable to end users before final deployment.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Validate system meets business requirements",
                           "is_correct": True},
                          {"text": "Test system performance",
                           "is_correct": False},
                          {"text": "Verify technical functionality",
                           "is_correct": False},
                          {"text": "Check code quality",
                           "is_correct": False},
                          ],
              },
             {"text": "Which factor is most important for successful system implementation?",
              "explanation": "Change management is crucial for successful implementation as it helps users adapt to new systems and processes.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Advanced technology",
                           "is_correct": False},
                          {"text": "Change management",
                           "is_correct": True},
                          {"text": "Large budget",
                           "is_correct": False},
                          {"text": "Detailed documentation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary objective of IT service management?",
              "explanation": "IT service management ensures that IT services are delivered efficiently and effectively to meet business requirements and user expectations.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Deliver IT services to meet business requirements",
                           "is_correct": True,
                           },
                          {"text": "Reduce IT operational costs",
                           "is_correct": False},
                          {"text": "Implement new technologies",
                           "is_correct": False},
                          {"text": "Manage IT staff performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which ITIL process is responsible for restoring normal service operation as quickly as possible?",
              "explanation": "Incident Management is responsible for restoring normal service operation as quickly as possible and minimizing business impact.",
              "reference": "https://www.axelos.com/best-practice-solutions/itil",
              "points": 1,
              "answers": [{"text": "Problem Management",
                           "is_correct": False},
                          {"text": "Incident Management",
                           "is_correct": True},
                          {"text": "Change Management",
                           "is_correct": False},
                          {"text": "Configuration Management",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of a service level agreement (SLA)?",
              "explanation": "An SLA defines the expected level of service between a service provider and customer, including performance metrics and responsibilities.",
              "reference": "https://www.axelos.com/best-practice-solutions/itil",
              "points": 1,
              "answers": [{"text": "Define expected service levels and responsibilities",
                           "is_correct": True,
                           },
                          {"text": "Document technical specifications",
                           "is_correct": False},
                          {"text": "Establish pricing for services",
                           "is_correct": False},
                          {"text": "Create operational procedures",
                           "is_correct": False},
                          ],
              },
             {"text": "Which backup strategy provides the fastest recovery time?",
              "explanation": "Real-time replication (mirroring) provides the fastest recovery time as data is continuously synchronized to a backup system.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Full backup",
                           "is_correct": False},
                          {"text": "Incremental backup",
                           "is_correct": False},
                          {"text": "Real-time replication",
                           "is_correct": True},
                          {"text": "Differential backup",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of capacity management?",
              "explanation": "Capacity management ensures that IT resources have sufficient capacity to meet current and future business requirements in a cost-effective manner.",
              "reference": "https://www.axelos.com/best-practice-solutions/itil",
              "points": 1,
              "answers": [{"text": "Ensure sufficient IT capacity for business needs",
                           "is_correct": True,
                           },
                          {"text": "Reduce hardware costs",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          {"text": "Manage user access",
                           "is_correct": False},
                          ],
              },
             {"text": "Which monitoring approach provides the most comprehensive view of system health?",
              "explanation": "End-to-end monitoring tracks the complete user experience across all system components, providing the most comprehensive view of system health.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Infrastructure monitoring",
                           "is_correct": False},
                          {"text": "Application monitoring",
                           "is_correct": False},
                          {"text": "End-to-end monitoring",
                           "is_correct": True},
                          {"text": "Network monitoring",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of business continuity planning?",
              "explanation": "Business continuity planning ensures that critical business functions can continue during and after a disruptive incident.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Ensure critical business functions continue during disruption",
                           "is_correct": True,
                           },
                          {"text": "Reduce operational costs",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          {"text": "Manage IT projects",
                           "is_correct": False},
                          ],
              },
             {"text": "Which metric is most important for measuring operational efficiency?",
              "explanation": "System availability directly impacts business operations and is the most important metric for measuring operational efficiency.",
              "reference": "https://www.axelos.com/best-practice-solutions/itil",
              "points": 1,
              "answers": [{"text": "Cost per transaction",
                           "is_correct": False},
                          {"text": "System availability",
                           "is_correct": True},
                          {"text": "User satisfaction",
                           "is_correct": False},
                          {"text": "Response time",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of implementing automated operations?",
              "explanation": "Automated operations reduce human error, improve consistency, and increase operational efficiency by eliminating manual processes.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Reduce human error and improve efficiency",
                           "is_correct": True},
                          {"text": "Lower hardware costs",
                           "is_correct": False},
                          {"text": "Improve user interface",
                           "is_correct": False},
                          {"text": "Increase system complexity",
                           "is_correct": False},
                          ],
              },
             {"text": "Which factor is most critical for successful vendor management?",
              "explanation": "Clear contract terms and SLAs are most critical for successful vendor management as they define expectations, responsibilities, and performance measures.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Lowest cost proposal",
                           "is_correct": False},
                          {"text": "Clear contract terms and SLAs",
                           "is_correct": True},
                          {"text": "Vendor reputation only",
                           "is_correct": False},
                          {"text": "Geographic proximity",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of information asset protection?",
              "explanation": "Information asset protection ensures the confidentiality, integrity, and availability of information assets throughout their lifecycle.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Ensure confidentiality, integrity, and availability",
                           "is_correct": True,
                           },
                          {"text": "Reduce storage costs",
                           "is_correct": False},
                          {"text": "Improve data processing speed",
                           "is_correct": False},
                          {"text": "Increase data accessibility",
                           "is_correct": False},
                          ],
              },
             {"text": "Which access control model is most suitable for organizations with strict hierarchical structures?",
              "explanation": "Mandatory Access Control (MAC) is most suitable for hierarchical organizations as it enforces strict access based on security classifications and clearances.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Discretionary Access Control (DAC)",
                           "is_correct": False},
                          {"text": "Mandatory Access Control (MAC)",
                           "is_correct": True},
                          {"text": "Role-Based Access Control (RBAC)",
                           "is_correct": False},
                          {"text": "Attribute-Based Access Control (ABAC)",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of data classification?",
              "explanation": "Data classification categorizes data based on its sensitivity and criticality to determine appropriate protection measures and handling requirements.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Categorize data to determine protection requirements",
                           "is_correct": True,
                           },
                          {"text": "Organize data for better performance",
                           "is_correct": False},
                          {"text": "Reduce data storage costs",
                           "is_correct": False},
                          {"text": "Improve data search capabilities",
                           "is_correct": False},
                          ],
              },
             {"text": "Which encryption type provides the best performance for large data volumes?",
              "explanation": "Symmetric encryption provides better performance for large data volumes as it uses the same key for encryption and decryption, requiring less computational overhead.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Asymmetric encryption",
                           "is_correct": False},
                          {"text": "Symmetric encryption",
                           "is_correct": True},
                          {"text": "Hash functions",
                           "is_correct": False},
                          {"text": "Digital signatures",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of implementing data loss prevention (DLP)?",
              "explanation": "DLP prevents unauthorized disclosure of sensitive information by monitoring, detecting, and blocking data in motion, at rest, and in use.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Prevent unauthorized disclosure of sensitive data",
                           "is_correct": True,
                           },
                          {"text": "Improve data processing speed",
                           "is_correct": False},
                          {"text": "Reduce data storage requirements",
                           "is_correct": False},
                          {"text": "Enhance data visualization",
                           "is_correct": False},
                          ],
              },
             {"text": "Which principle should guide the retention of personal data?",
              "explanation": "Data minimization principle requires that personal data should only be retained for as long as necessary for the specific purposes for which it was collected.",
              "reference": "https://gdpr-info.eu/",
              "points": 1,
              "answers": [{"text": "Retain all data indefinitely",
                           "is_correct": False},
                          {"text": "Data minimization principle",
                           "is_correct": True},
                          {"text": "Maximum retention period",
                           "is_correct": False},
                          {"text": "Business convenience",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of identity and access management (IAM)?",
              "explanation": "IAM ensures that the right individuals have appropriate access to technology resources at the right time for the right reasons.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Ensure appropriate access for authorized individuals",
                           "is_correct": True,
                           },
                          {"text": "Manage user passwords only",
                           "is_correct": False},
                          {"text": "Control network traffic",
                           "is_correct": False},
                          {"text": "Monitor system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which security control type prevents unauthorized access most effectively?",
              "explanation": "Preventive controls are designed to prevent security incidents from occurring, making them most effective at preventing unauthorized access.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Detective controls",
                           "is_correct": False},
                          {"text": "Preventive controls",
                           "is_correct": True},
                          {"text": "Corrective controls",
                           "is_correct": False},
                          {"text": "Compensating controls",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of vulnerability management?",
              "explanation": "Vulnerability management identifies, evaluates, and mitigates security vulnerabilities in systems and applications to reduce security risks.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Identify and mitigate security vulnerabilities",
                           "is_correct": True,
                           },
                          {"text": "Improve system performance",
                           "is_correct": False},
                          {"text": "Reduce operational costs",
                           "is_correct": False},
                          {"text": "Enhance user experience",
                           "is_correct": False},
                          ],
              },
             {"text": "Which approach provides the most comprehensive data protection?",
              "explanation": "Defense in depth uses multiple layers of security controls to provide comprehensive protection against various types of threats.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Single strong security control",
                           "is_correct": False},
                          {"text": "Defense in depth",
                           "is_correct": True},
                          {"text": "Perimeter security only",
                           "is_correct": False},
                          {"text": "Encryption only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary objective of enterprise risk management?",
              "explanation": "Enterprise risk management identifies, assesses, and manages risks across the organization to achieve strategic objectives while staying within risk appetite.",
              "reference": "https://www.coso.org/Pages/erm.aspx",
              "points": 1,
              "answers": [{"text": "Identify and manage organizational risks",
                           "is_correct": True},
                          {"text": "Eliminate all business risks",
                           "is_correct": False},
                          {"text": "Reduce operational costs",
                           "is_correct": False},
                          {"text": "Improve employee satisfaction",
                           "is_correct": False},
                          ],
              },
             {"text": "Which risk assessment methodology provides the most quantitative analysis?",
              "explanation": "Quantitative risk assessment uses numerical values and statistical methods to calculate risk levels, providing the most quantitative analysis.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Qualitative risk assessment",
                           "is_correct": False},
                          {"text": "Quantitative risk assessment",
                           "is_correct": True},
                          {"text": "Semi-quantitative assessment",
                           "is_correct": False},
                          {"text": "Subjective assessment",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of a risk register?",
              "explanation": "A risk register documents identified risks, their assessments, treatment plans, and ownership to facilitate risk management and monitoring.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Document and track identified risks",
                           "is_correct": True},
                          {"text": "Store financial data",
                           "is_correct": False},
                          {"text": "Manage user accounts",
                           "is_correct": False},
                          {"text": "Track project schedules",
                           "is_correct": False},
                          ],
              },
             {"text": "Which compliance framework is most relevant for financial institutions?",
              "explanation": "SOX (Sarbanes-Oxley Act) is most relevant for financial institutions as it mandates strict financial reporting and internal control requirements.",
              "reference": "https://www.sec.gov/about/laws/soa2002.pdf",
              "points": 1,
              "answers": [{"text": "HIPAA",
                           "is_correct": False},
                          {"text": "SOX",
                           "is_correct": True},
                          {"text": "GDPR",
                           "is_correct": False},
                          {"text": "PCI DSS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of risk mitigation strategies?",
              "explanation": "Risk mitigation strategies reduce the likelihood or impact of risks to acceptable levels while balancing cost and benefit considerations.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Reduce risk to acceptable levels",
                           "is_correct": True},
                          {"text": "Eliminate all risks",
                           "is_correct": False},
                          {"text": "Increase business profits",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which factor is most important when determining risk appetite?",
              "explanation": "Business objectives and strategy are most important when determining risk appetite as they define what the organization wants to achieve and how much risk it's willing to accept.",
              "reference": "https://www.coso.org/Pages/erm.aspx",
              "points": 1,
              "answers": [{"text": "Current market conditions",
                           "is_correct": False},
                          {"text": "Business objectives and strategy",
                           "is_correct": True},
                          {"text": "Available technology",
                           "is_correct": False},
                          {"text": "Competitor analysis",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of continuous risk monitoring?",
              "explanation": "Continuous risk monitoring identifies changes in risk levels and ensures that risk management strategies remain effective and appropriate.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Identify changes in risk levels",
                           "is_correct": True},
                          {"text": "Reduce monitoring costs",
                           "is_correct": False},
                          {"text": "Improve system uptime",
                           "is_correct": False},
                          {"text": "Enhance user experience",
                           "is_correct": False},
                          ],
              },
             {"text": "Which approach best ensures regulatory compliance?",
              "explanation": "Regular compliance assessments ensure ongoing adherence to regulatory requirements and identify gaps that need to be addressed.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "One-time compliance check",
                           "is_correct": False},
                          {"text": "Regular compliance assessments",
                           "is_correct": True},
                          {"text": "Informal monitoring",
                           "is_correct": False},
                          {"text": "Self-certification only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary focus of third-party risk management?",
              "explanation": "Third-party risk management assesses and manages risks introduced by vendors, suppliers, and other external parties to the organization.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Manage risks from external parties",
                           "is_correct": True},
                          {"text": "Reduce vendor costs",
                           "is_correct": False},
                          {"text": "Improve vendor performance",
                           "is_correct": False},
                          {"text": "Streamline procurement",
                           "is_correct": False},
                          ],
              },
             {"text": "Which risk response strategy accepts the risk without further action?",
              "explanation": "Risk acceptance acknowledges the risk and decides to accept it without implementing additional controls, often when the cost of mitigation exceeds the benefit.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Risk mitigation",
                           "is_correct": False},
                          {"text": "Risk acceptance",
                           "is_correct": True},
                          {"text": "Risk transfer",
                           "is_correct": False},
                          {"text": "Risk avoidance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of business process evaluation?",
              "explanation": "Business process evaluation assesses the effectiveness and efficiency of business processes to identify improvement opportunities and ensure objectives are met.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Assess process effectiveness and efficiency",
                           "is_correct": True},
                          {"text": "Reduce operational costs only",
                           "is_correct": False},
                          {"text": "Automate all processes",
                           "is_correct": False},
                          {"text": "Eliminate manual activities",
                           "is_correct": False},
                          ],
              },
             {"text": "Which framework is most suitable for IT control evaluation?",
              "explanation": "COBIT provides a comprehensive framework specifically designed for IT governance and control evaluation.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "COSO",
                           "is_correct": False},
                          {"text": "COBIT",
                           "is_correct": True},
                          {"text": "ISO 9001",
                           "is_correct": False},
                          {"text": "Six Sigma",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of internal controls?",
              "explanation": "Internal controls provide reasonable assurance that organizational objectives are achieved, risks are managed, and financial reporting is reliable.",
              "reference": "https://www.coso.org/Pages/ic.aspx",
              "points": 1,
              "answers": [{"text": "Provide assurance for achieving objectives",
                           "is_correct": True},
                          {"text": "Eliminate all business risks",
                           "is_correct": False},
                          {"text": "Guarantee financial success",
                           "is_correct": False},
                          {"text": "Replace management oversight",
                           "is_correct": False},
                          ],
              },
             {"text": "Which testing method provides the most reliable evidence of control effectiveness?",
              "explanation": "Reperformance testing provides the most reliable evidence as the auditor independently executes the control to verify its effectiveness.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Inquiry",
                           "is_correct": False},
                          {"text": "Observation",
                           "is_correct": False},
                          {"text": "Reperformance",
                           "is_correct": True},
                          {"text": "Inspection",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary characteristic of compensating controls?",
              "explanation": "Compensating controls provide alternative protection when primary controls are not feasible or cost-effective to implement.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Provide alternative protection methods",
                           "is_correct": True},
                          {"text": "Replace all other controls",
                           "is_correct": False},
                          {"text": "Are always more effective",
                           "is_correct": False},
                          {"text": "Cost less than primary controls",
                           "is_correct": False},
                          ],
              },
             {"text": "Which approach ensures comprehensive security management?",
              "explanation": "Security governance provides strategic direction and ensures security is aligned with business objectives across the organization.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Technical controls only",
                           "is_correct": False},
                          {"text": "Security governance",
                           "is_correct": True},
                          {"text": "Incident response",
                           "is_correct": False},
                          {"text": "Penetration testing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary objective of security awareness training?",
              "explanation": "Security awareness training educates users about security threats and their role in protecting organizational information assets.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Educate users about security threats and responsibilities",
                           "is_correct": True,
                           },
                          {"text": "Reduce training costs",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          {"text": "Eliminate security incidents",
                           "is_correct": False},
                          ],
              },
             {"text": "Which testing approach simulates real-world attack scenarios?",
              "explanation": "Penetration testing simulates real-world attacks to identify vulnerabilities and assess the effectiveness of security controls.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Vulnerability scanning",
                           "is_correct": False},
                          {"text": "Penetration testing",
                           "is_correct": True},
                          {"text": "Code review",
                           "is_correct": False},
                          {"text": "Configuration review",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of security metrics?",
              "explanation": "Security metrics measure the effectiveness of security controls and programs, providing data for decision-making and improvement.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Measure security control effectiveness",
                           "is_correct": True},
                          {"text": "Reduce security costs",
                           "is_correct": False},
                          {"text": "Eliminate security threats",
                           "is_correct": False},
                          {"text": "Automate security processes",
                           "is_correct": False},
                          ],
              },
             {"text": "Which factor is most critical for effective incident response?",
              "explanation": "Preparation and planning are most critical for effective incident response, including procedures, roles, and communication plans.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Advanced technology tools",
                           "is_correct": False},
                          {"text": "Preparation and planning",
                           "is_correct": True},
                          {"text": "Large security team",
                           "is_correct": False},
                          {"text": "Expensive security software",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary goal of disaster recovery planning?",
              "explanation": "Disaster recovery planning aims to restore critical IT systems and operations within defined timeframes after a disaster.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Restore IT systems within defined timeframes",
                           "is_correct": True,
                           },
                          {"text": "Prevent all disasters",
                           "is_correct": False},
                          {"text": "Reduce operational costs",
                           "is_correct": False},
                          {"text": "Improve system performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which metric is most important for measuring RTO compliance?",
              "explanation": "Actual recovery time compared to RTO target is the most important metric for measuring Recovery Time Objective compliance.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "System uptime percentage",
                           "is_correct": False},
                          {"text": "Actual recovery time vs. RTO target",
                           "is_correct": True},
                          {"text": "Number of incidents",
                           "is_correct": False},
                          {"text": "Cost of recovery",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of business impact analysis (BIA)?",
              "explanation": "BIA identifies critical business processes and assesses the impact of disruptions to prioritize recovery efforts and resource allocation.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Identify critical processes and assess disruption impact",
                           "is_correct": True,
                           },
                          {"text": "Calculate financial profits",
                           "is_correct": False},
                          {"text": "Evaluate employee performance",
                           "is_correct": False},
                          {"text": "Assess market competition",
                           "is_correct": False},
                          ],
              },
             {"text": "Which backup strategy provides the best balance of speed and storage efficiency?",
              "explanation": "Incremental backup provides a good balance by backing up only changed data, offering reasonable recovery speed with efficient storage use.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Full backup",
                           "is_correct": False},
                          {"text": "Incremental backup",
                           "is_correct": True},
                          {"text": "Differential backup",
                           "is_correct": False},
                          {"text": "Mirror backup",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary difference between hot, warm, and cold sites?",
              "explanation": "The difference lies in recovery time and cost - hot sites provide immediate recovery, warm sites require some setup time, and cold sites need significant time and effort.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Recovery time and cost considerations",
                           "is_correct": True},
                          {"text": "Geographic location only",
                           "is_correct": False},
                          {"text": "Equipment manufacturer",
                           "is_correct": False},
                          {"text": "Power consumption levels",
                           "is_correct": False},
                          ],
              },
             {"text": "Which factor is most important when testing disaster recovery plans?",
              "explanation": "Realistic scenarios that simulate actual disaster conditions are most important for effective DR plan testing.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Low cost testing",
                           "is_correct": False},
                          {"text": "Realistic disaster scenarios",
                           "is_correct": True},
                          {"text": "Minimal business disruption",
                           "is_correct": False},
                          {"text": "Quick completion time",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of recovery point objective (RPO)?",
              "explanation": "RPO defines the maximum acceptable amount of data loss measured in time, determining backup frequency and strategy requirements.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Define maximum acceptable data loss",
                           "is_correct": True},
                          {"text": "Set recovery time targets",
                           "is_correct": False},
                          {"text": "Determine staff requirements",
                           "is_correct": False},
                          {"text": "Calculate recovery costs",
                           "is_correct": False},
                          ],
              },
             {"text": "Which approach ensures effective crisis communication?",
              "explanation": "Pre-defined communication plans with clear roles and procedures ensure effective crisis communication when disasters occur.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Ad-hoc communication",
                           "is_correct": False},
                          {"text": "Pre-defined communication plans",
                           "is_correct": True},
                          {"text": "Social media only",
                           "is_correct": False},
                          {"text": "Email notifications only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of conducting post-incident reviews?",
              "explanation": "Post-incident reviews identify lessons learned and improvement opportunities to enhance future disaster response and recovery capabilities.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Identify lessons learned and improvements",
                           "is_correct": True},
                          {"text": "Assign blame for incidents",
                           "is_correct": False},
                          {"text": "Reduce insurance premiums",
                           "is_correct": False},
                          {"text": "Satisfy regulatory requirements only",
                           "is_correct": False},
                          ],
              },
             {"text": "Which principle should guide alternating backup site selection?",
              "explanation": "Geographic diversity ensures that backup sites are not affected by the same disasters that impact primary sites.",
              "reference": "https://www.isaca.org/resources/cobit",
              "points": 1,
              "answers": [{"text": "Cost minimization",
                           "is_correct": False},
                          {"text": "Geographic diversity",
                           "is_correct": True},
                          {"text": "Vendor preference",
                           "is_correct": False},
                          {"text": "Technology compatibility only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the most important characteristic of professional skepticism in auditing?",
              "explanation": "Professional skepticism requires auditors to maintain a questioning mind and critically assess audit evidence rather than simply accepting information at face value.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Questioning mind and critical assessment",
                           "is_correct": True},
                          {"text": "Accepting all information provided",
                           "is_correct": False},
                          {"text": "Focusing only on negative findings",
                           "is_correct": False},
                          {"text": "Avoiding difficult questions",
                           "is_correct": False},
                          ],
              },
             {"text": "Which approach best ensures auditor independence?",
              "explanation": "Organizational independence and objectivity ensure that auditors can perform their duties without conflicts of interest or undue influence.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Auditing only familiar systems",
                           "is_correct": False},
                          {"text": "Organizational independence and objectivity",
                           "is_correct": True},
                          {"text": "Working closely with auditees",
                           "is_correct": False},
                          {"text": "Focusing on cost savings",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of continuing professional education for IS auditors?",
              "explanation": "CPE ensures auditors maintain current knowledge of evolving technologies, regulations, and audit methodologies to perform effective audits.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Maintain current knowledge and competency",
                           "is_correct": True},
                          {"text": "Meet minimum hour requirements",
                           "is_correct": False},
                          {"text": "Obtain salary increases",
                           "is_correct": False},
                          {"text": "Network with other professionals",
                           "is_correct": False},
                          ],
              },
             {"text": "Which factor is most important for effective audit communication?",
              "explanation": "Clear, concise, and actionable audit reports ensure that findings and recommendations are understood and can be implemented by management.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Technical complexity",
                           "is_correct": False},
                          {"text": "Clear and actionable reporting",
                           "is_correct": True},
                          {"text": "Lengthy detailed descriptions",
                           "is_correct": False},
                          {"text": "Use of audit jargon",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the most effective way to ensure audit quality?",
              "explanation": "Quality assurance programs with peer reviews and continuous monitoring ensure that audits meet professional standards and effectiveness requirements.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Reducing audit time",
                           "is_correct": False},
                          {"text": "Quality assurance programs",
                           "is_correct": True},
                          {"text": "Using only senior auditors",
                           "is_correct": False},
                          {"text": "Avoiding complex audits",
                           "is_correct": False},
                          ],
              },
             {"text": "Which principle guides ethical behavior for IS auditors?",
              "explanation": "Professional integrity requires auditors to be honest, objective, and fair in all professional relationships and audit activities.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Profit maximization",
                           "is_correct": False},
                          {"text": "Professional integrity",
                           "is_correct": True},
                          {"text": "Client satisfaction only",
                           "is_correct": False},
                          {"text": "Personal advancement",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of audit follow-up procedures?",
              "explanation": "Audit follow-up ensures that management has implemented agreed-upon corrective actions and that identified risks have been properly addressed.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Ensure corrective actions are implemented",
                           "is_correct": True},
                          {"text": "Generate additional audit fees",
                           "is_correct": False},
                          {"text": "Identify new audit opportunities",
                           "is_correct": False},
                          {"text": "Satisfy regulatory requirements only",
                           "is_correct": False},
                          ],
              },
             {"text": "Which approach best demonstrates audit value to the organization?",
              "explanation": "Risk-based auditing focusing on critical business areas demonstrates audit value by addressing the most significant risks to organizational objectives.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Auditing all systems equally",
                           "is_correct": False},
                          {"text": "Risk-based audit focus",
                           "is_correct": True},
                          {"text": "Compliance-only auditing",
                           "is_correct": False},
                          {"text": "Technology-focused auditing",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the most important factor in audit planning?",
              "explanation": "Understanding business objectives and risks is essential for effective audit planning to ensure audit efforts focus on areas of greatest concern.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Available audit time",
                           "is_correct": False},
                          {"text": "Understanding business objectives and risks",
                           "is_correct": True},
                          {"text": "Audit tool availability",
                           "is_correct": False},
                          {"text": "Previous audit findings",
                           "is_correct": False},
                          ],
              },
             {"text": "Which competency is most critical for modern IS auditors?",
              "explanation": "Technology knowledge combined with business acumen allows auditors to understand both technical risks and their business impact in today's digital environment.",
              "reference": "https://www.isaca.org/resources/isaca-journal",
              "points": 1,
              "answers": [{"text": "Accounting skills only",
                           "is_correct": False},
                          {"text": "Technology and business knowledge",
                           "is_correct": True},
                          {"text": "Legal expertise only",
                           "is_correct": False},
                          {"text": "Project management only",
                           "is_correct": False},
                          ],
              },
             ]
