"""Categories data for seeding the database with hierarchical structure"""

CATEGORIES = [
    # Top-level categories
    {
        "name": "IT & Technology",
        "description": "Information Technology and Technical Certifications",
        "slug": "it",
        "icon": "computer",
        "color": "blue",
        "parent_id": None,
    },
    {
        "name": "Languages",
        "description": "Language proficiency certifications",
        "slug": "languages",
        "icon": "language",
        "color": "rose",
        "parent_id": None,
    },
    {
        "name": "Academic",
        "description": "Academic subjects and grade-level certifications",
        "slug": "academic",
        "icon": "academic",
        "color": "amber",
        "parent_id": None,
    },

    # IT & Technology subcategories
    {
        "name": "AWS",
        "description": "Amazon Web Services Cloud Computing Certifications",
        "slug": "aws",
        "icon": "aws",
        "color": "orange",
        "parent_slug": "it",
    },
    {
        "name": "Azure",
        "description": "Microsoft Azure Cloud Computing Certifications",
        "slug": "azure",
        "icon": "azure",
        "color": "blue",
        "parent_slug": "it",
    },
    {
        "name": "Google Cloud",
        "description": "Google Cloud Platform Certifications",
        "slug": "google-cloud",
        "icon": "gcp",
        "color": "green",
        "parent_slug": "it",
    },
    {
        "name": "DevOps",
        "description": "DevOps, Infrastructure, and Automation Certifications",
        "slug": "devops",
        "icon": "devops",
        "color": "purple",
        "parent_slug": "it",
    },
    {
        "name": "Programming",
        "description": "Programming Languages and Software Development",
        "slug": "programming",
        "icon": "code",
        "color": "teal",
        "parent_slug": "it",
    },
    {
        "name": "Cybersecurity",
        "description": "Information Security and Cybersecurity Certifications",
        "slug": "cybersecurity",
        "icon": "shield",
        "color": "red",
        "parent_slug": "it",
    },
    {
        "name": "Data & Analytics",
        "description": "Data Science, Analytics, and Machine Learning",
        "slug": "data-analytics",
        "icon": "chart",
        "color": "indigo",
        "parent_slug": "it",
    },
    {
        "name": "Project Management",
        "description": "Project Management and Agile Methodologies",
        "slug": "project-management",
        "icon": "project",
        "color": "yellow",
        "parent_slug": "it",
    },
    {
        "name": "Networking",
        "description": "Computer Networking and Infrastructure",
        "slug": "networking",
        "icon": "network",
        "color": "cyan",
        "parent_slug": "it",
    },
    {
        "name": "Database",
        "description": "Database Management and Administration",
        "slug": "database",
        "icon": "database",
        "color": "pink",
        "parent_slug": "it",
    },
    {
        "name": "Linux & System Administration",
        "description": "Linux, Unix, and System Administration Certifications",
        "slug": "linux",
        "icon": "linux",
        "color": "gray",
        "parent_slug": "it",
    },
    {
        "name": "System Design & Architecture",
        "description": "Software Architecture and System Design",
        "slug": "system-design",
        "icon": "architecture",
        "color": "emerald",
        "parent_slug": "it",
    },
    {
        "name": "Data Structures & Algorithms",
        "description": "Data Structures, Algorithms, and Competitive Programming",
        "slug": "data-structures-algorithms",
        "icon": "algorithm",
        "color": "violet",
        "parent_slug": "it",
    },

    # Language subcategories
    {
        "name": "German",
        "description": "German language proficiency levels",
        "slug": "german",
        "icon": "flag-de",
        "color": "red",
        "parent_slug": "languages",
    },
    {
        "name": "French",
        "description": "French language proficiency levels",
        "slug": "french",
        "icon": "flag-fr",
        "color": "blue",
        "parent_slug": "languages",
    },
    {
        "name": "Spanish",
        "description": "Spanish language proficiency levels",
        "slug": "spanish",
        "icon": "flag-es",
        "color": "yellow",
        "parent_slug": "languages",
    },
    {
        "name": "English",
        "description": "English language proficiency levels",
        "slug": "english",
        "icon": "flag-us",
        "color": "blue",
        "parent_slug": "languages",
    },

    # Academic subcategories
    {
        "name": "Science",
        "description": "General Science subjects by grade level",
        "slug": "science",
        "icon": "flask",
        "color": "green",
        "parent_slug": "academic",
    },
    {
        "name": "Physics",
        "description": "Physics subjects by grade level",
        "slug": "physics",
        "icon": "atom",
        "color": "blue",
        "parent_slug": "academic",
    },
    {
        "name": "Mathematics",
        "description": "Mathematics subjects by grade level",
        "slug": "mathematics",
        "icon": "calculator",
        "color": "purple",
        "parent_slug": "academic",
    },
    {
        "name": "Chemistry",
        "description": "Chemistry subjects by grade level",
        "slug": "chemistry",
        "icon": "test-tube",
        "color": "orange",
        "parent_slug": "academic",
    },
    {
        "name": "Biology",
        "description": "Biology subjects by grade level",
        "slug": "biology",
        "icon": "dna",
        "color": "emerald",
        "parent_slug": "academic",
    },
]