"""AWS Advanced Networking Specialty Certification"""

CERTIFICATION = {
    "name": "AWS Certified Advanced Networking - Specialty",
    "description": "Design and maintain network architecture for all AWS services",
    "slug": "aws-advanced-networking-specialty",
    "level": "Specialty",
    "duration": 228,
    "questions_count": 76,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is AWS Direct Connect used for?",
        "explanation": "AWS Direct Connect is a cloud service solution that makes it easy to establish a dedicated network connection from your premises to AWS. Using AWS Direct Connect, you can establish private connectivity between AWS and your datacenter, office, or colocation environment.",
        "reference": "https://docs.aws.amazon.com/directconnect/",
        "points": 1,
        "answers": [
            {"text": "Dedicated network connection to AWS", "is_correct": True},
            {"text": "Content delivery network", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
            {"text": "DNS management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides DNS management?",
        "explanation": "Amazon Route 53 is a highly available and scalable cloud Domain Name System (DNS) web service. It is designed to give developers and businesses an extremely reliable and cost effective way to route end users to Internet applications.",
        "reference": "https://docs.aws.amazon.com/route53/",
        "points": 1,
        "answers": [
            {"text": "Amazon Route 53", "is_correct": True},
            {"text": "AWS CloudFront", "is_correct": False},
            {"text": "Elastic Load Balancing", "is_correct": False},
            {"text": "AWS Direct Connect", "is_correct": False},
        ],
    },
    {
        "text": "What is a VPC endpoint used for?",
        "explanation": "A VPC endpoint enables you to privately connect your VPC to supported AWS services and VPC endpoint services powered by AWS PrivateLink without requiring an internet gateway, NAT device, VPN connection, or AWS Direct Connect connection.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html",
        "points": 1,
        "answers": [
            {
                "text": "Private connection to AWS services without internet gateway",
                "is_correct": True,
            },
            {"text": "Public internet access", "is_correct": False},
            {"text": "Cross-region connectivity", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides distributed denial of service (DDoS) protection?",
        "explanation": "AWS Shield is a managed Distributed Denial of Service (DDoS) protection service that safeguards applications running on AWS. AWS Shield provides always-on detection and automatic inline mitigations that minimize application downtime and latency.",
        "reference": "https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html",
        "points": 1,
        "answers": [
            {"text": "AWS Shield", "is_correct": True},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "Amazon CloudFront", "is_correct": False},
            {"text": "AWS Security Groups", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Transit Gateway used for?",
        "explanation": "AWS Transit Gateway is a service that enables customers to connect their Amazon Virtual Private Clouds (VPCs) and their on-premises networks to a single gateway.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/tgw/",
        "points": 1,
        "answers": [
            {
                "text": "Connecting multiple VPCs and on-premises networks",
                "is_correct": True,
            },
            {"text": "Internet access management", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
            {"text": "DNS resolution", "is_correct": False},
        ],
    },
    {
        "text": "Which Direct Connect virtual interface type provides dedicated bandwidth?",
        "explanation": "A Dedicated Virtual Interface (VIF) provides dedicated bandwidth to a single customer. It's hosted on a dedicated port and provides predictable performance for critical workloads.",
        "reference": "https://docs.aws.amazon.com/directconnect/latest/userguide/WorkingWithVirtualInterfaces.html",
        "points": 1,
        "answers": [
            {"text": "Dedicated Virtual Interface", "is_correct": True},
            {"text": "Hosted Virtual Interface", "is_correct": False},
            {"text": "Transit Virtual Interface", "is_correct": False},
            {"text": "Gateway Virtual Interface", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum bandwidth for AWS Direct Connect?",
        "explanation": "AWS Direct Connect supports bandwidths from 50 Mbps to 100 Gbps. The highest bandwidth option is 100 Gbps for dedicated connections.",
        "reference": "https://docs.aws.amazon.com/directconnect/latest/userguide/getting_started.html",
        "points": 1,
        "answers": [
            {"text": "100 Gbps", "is_correct": True},
            {"text": "50 Gbps", "is_correct": False},
            {"text": "25 Gbps", "is_correct": False},
            {"text": "10 Gbps", "is_correct": False},
        ],
    },
    {
        "text": "Which Route 53 routing policy routes traffic based on the location of your users?",
        "explanation": "Geolocation routing lets you choose the resources that serve your traffic based on the geographic location of your users, meaning the location that DNS queries originate from.",
        "reference": "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html",
        "points": 1,
        "answers": [
            {"text": "Geolocation routing", "is_correct": True},
            {"text": "Latency-based routing", "is_correct": False},
            {"text": "Weighted routing", "is_correct": False},
            {"text": "Failover routing", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS PrivateLink used for?",
        "explanation": "AWS PrivateLink provides private connectivity between VPCs, AWS services, and on-premises applications, securely on the Amazon network. It simplifies the security of data shared with cloud-based applications by eliminating the exposure of data to the public Internet.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/privatelink/",
        "points": 1,
        "answers": [
            {
                "text": "Private connectivity between VPCs and AWS services",
                "is_correct": True,
            },
            {"text": "Public internet access", "is_correct": False},
            {"text": "Cross-region replication", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides Web Application Firewall capabilities?",
        "explanation": "AWS WAF is a web application firewall that helps protect your web applications or APIs against common web exploits and bots that may affect availability, compromise security, or consume excessive resources.",
        "reference": "https://docs.aws.amazon.com/waf/",
        "points": 1,
        "answers": [
            {"text": "AWS WAF", "is_correct": True},
            {"text": "AWS Shield", "is_correct": False},
            {"text": "AWS CloudFront", "is_correct": False},
            {"text": "AWS Security Groups", "is_correct": False},
        ],
    },
    {
        "text": "What is the minimum BGP AS number for customer gateways in AWS?",
        "explanation": "For customer gateways, you can use BGP AS numbers from 1 to 2147483647. However, AWS reserves AS number 7224 for its own use.",
        "reference": "https://docs.aws.amazon.com/vpn/latest/s2svpn/cgw-options.html",
        "points": 1,
        "answers": [
            {"text": "1", "is_correct": True},
            {"text": "64512", "is_correct": False},
            {"text": "65000", "is_correct": False},
            {"text": "7224", "is_correct": False},
        ],
    },
    {
        "text": "Which type of VPC endpoint is used for AWS services like S3 and DynamoDB?",
        "explanation": "Gateway endpoints are used for Amazon S3 and Amazon DynamoDB. They are specified as a target for a route in your route table for traffic destined for the supported AWS services.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html",
        "points": 1,
        "answers": [
            {"text": "Gateway endpoint", "is_correct": True},
            {"text": "Interface endpoint", "is_correct": False},
            {"text": "Network endpoint", "is_correct": False},
            {"text": "Service endpoint", "is_correct": False},
        ],
    },
    {
        "text": "What is the default CIDR block size for a VPC?",
        "explanation": "AWS VPC supports CIDR blocks ranging from /16 (65,536 IP addresses) to /28 (16 IP addresses). There is no default size, but /16 is commonly used for maximum flexibility.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html",
        "points": 1,
        "answers": [
            {"text": "/16 to /28", "is_correct": True},
            {"text": "/8 to /24", "is_correct": False},
            {"text": "/12 to /28", "is_correct": False},
            {"text": "/16 to /24", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides network load balancing with ultra-low latency?",
        "explanation": "Network Load Balancer operates at the transport layer (Layer 4) and can handle millions of requests per second while maintaining ultra-low latencies.",
        "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/network/",
        "points": 1,
        "answers": [
            {"text": "Network Load Balancer", "is_correct": True},
            {"text": "Application Load Balancer", "is_correct": False},
            {"text": "Classic Load Balancer", "is_correct": False},
            {"text": "Gateway Load Balancer", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of VPCs you can create per AWS account per region by default?",
        "explanation": "By default, you can create up to 5 VPCs per AWS account per region. This limit can be increased by contacting AWS Support.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html",
        "points": 1,
        "answers": [
            {"text": "5", "is_correct": True},
            {"text": "10", "is_correct": False},
            {"text": "20", "is_correct": False},
            {"text": "Unlimited", "is_correct": False},
        ],
    },
    {
        "text": "Which protocol does AWS Direct Connect use for BGP routing?",
        "explanation": "AWS Direct Connect uses BGP (Border Gateway Protocol) for dynamic routing between your network and AWS. BGP is the standard routing protocol for the internet.",
        "reference": "https://docs.aws.amazon.com/directconnect/latest/userguide/routing-and-bgp.html",
        "points": 1,
        "answers": [
            {"text": "BGP", "is_correct": True},
            {"text": "OSPF", "is_correct": False},
            {"text": "RIP", "is_correct": False},
            {"text": "EIGRP", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Global Accelerator?",
        "explanation": "AWS Global Accelerator is a service that improves the availability and performance of your applications with local or global users by using AWS's global network infrastructure.",
        "reference": "https://docs.aws.amazon.com/global-accelerator/",
        "points": 1,
        "answers": [
            {
                "text": "Improve application performance using AWS global network",
                "is_correct": True,
            },
            {"text": "Provide DNS resolution", "is_correct": False},
            {"text": "Load balance traffic", "is_correct": False},
            {"text": "Cache content globally", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed NAT capabilities?",
        "explanation": "AWS NAT Gateway is a highly available, managed Network Address Translation (NAT) service that allows instances in a private subnet to connect to the internet or other AWS services.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html",
        "points": 1,
        "answers": [
            {"text": "NAT Gateway", "is_correct": True},
            {"text": "Internet Gateway", "is_correct": False},
            {"text": "VPC Endpoint", "is_correct": False},
            {"text": "Transit Gateway", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between Security Groups and NACLs?",
        "explanation": "Security Groups operate at the instance level and are stateful, while Network ACLs operate at the subnet level and are stateless. Security Groups only support allow rules, while NACLs support both allow and deny rules.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Security.html",
        "points": 1,
        "answers": [
            {
                "text": "Security Groups are stateful at instance level, NACLs are stateless at subnet level",
                "is_correct": True,
            },
            {
                "text": "Security Groups are stateless, NACLs are stateful",
                "is_correct": False,
            },
            {"text": "Both operate at the same level", "is_correct": False},
            {"text": "NACLs only support allow rules", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides DNS failover capabilities?",
        "explanation": "Amazon Route 53 provides DNS failover capabilities through health checks and failover routing policies, allowing automatic failover to healthy resources.",
        "reference": "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover.html",
        "points": 1,
        "answers": [
            {"text": "Amazon Route 53", "is_correct": True},
            {"text": "AWS CloudFront", "is_correct": False},
            {"text": "Elastic Load Balancer", "is_correct": False},
            {"text": "AWS Direct Connect", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Site-to-Site VPN?",
        "explanation": "AWS Site-to-Site VPN creates a secure connection between your data center or branch office and your AWS cloud resources. This connection goes over the public internet but is encrypted.",
        "reference": "https://docs.aws.amazon.com/vpn/latest/s2svpn/",
        "points": 1,
        "answers": [
            {
                "text": "Secure encrypted connection between on-premises and AWS",
                "is_correct": True,
            },
            {"text": "Private dedicated connection to AWS", "is_correct": False},
            {"text": "Content delivery network", "is_correct": False},
            {"text": "Load balancing service", "is_correct": False},
        ],
    },
    {
        "text": "Which type of AWS load balancer operates at Layer 7?",
        "explanation": "Application Load Balancer operates at Layer 7 (Application Layer) and can make routing decisions based on content type, such as HTTP headers, method, path, source IP, etc.",
        "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/application/",
        "points": 1,
        "answers": [
            {"text": "Application Load Balancer", "is_correct": True},
            {"text": "Network Load Balancer", "is_correct": False},
            {"text": "Classic Load Balancer", "is_correct": False},
            {"text": "Gateway Load Balancer", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CloudFront primarily used for?",
        "explanation": "Amazon CloudFront is a content delivery network (CDN) service that securely delivers data, videos, applications, and APIs to customers globally with low latency and high transfer speeds.",
        "reference": "https://docs.aws.amazon.com/cloudfront/",
        "points": 1,
        "answers": [
            {"text": "Content delivery network (CDN)", "is_correct": True},
            {"text": "DNS management", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
            {"text": "VPN connectivity", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service allows you to monitor network traffic in your VPC?",
        "explanation": "VPC Flow Logs capture information about the IP traffic going to and from network interfaces in your VPC. Flow log data can be published to Amazon CloudWatch Logs or Amazon S3.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html",
        "points": 1,
        "answers": [
            {"text": "VPC Flow Logs", "is_correct": True},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum size of a subnet in AWS?",
        "explanation": "The largest subnet you can create in a VPC uses a /16 netmask (65,536 IP addresses). AWS reserves the first 4 and last 1 IP addresses in each subnet.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html",
        "points": 1,
        "answers": [
            {"text": "/16 netmask", "is_correct": True},
            {"text": "/8 netmask", "is_correct": False},
            {"text": "/24 netmask", "is_correct": False},
            {"text": "/12 netmask", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed DDoS protection at no additional cost?",
        "explanation": "AWS Shield Standard provides protection against most common, frequently occurring network and transport layer DDoS attacks at no additional cost for all AWS customers.",
        "reference": "https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html",
        "points": 1,
        "answers": [
            {"text": "AWS Shield Standard", "is_correct": True},
            {"text": "AWS Shield Advanced", "is_correct": False},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "AWS CloudFront", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS PrivateLink endpoints?",
        "explanation": "AWS PrivateLink endpoints enable you to connect privately to services across different accounts and VPCs to significantly simplify your network architecture.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/privatelink/",
        "points": 1,
        "answers": [
            {
                "text": "Private connectivity across accounts and VPCs",
                "is_correct": True,
            },
            {"text": "Public internet access", "is_correct": False},
            {"text": "DNS resolution", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which routing protocol is commonly used with AWS Transit Gateway?",
        "explanation": "AWS Transit Gateway supports BGP (Border Gateway Protocol) for dynamic routing and static routing. BGP is the most commonly used for complex routing scenarios.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/tgw/tgw-routing.html",
        "points": 1,
        "answers": [
            {"text": "BGP", "is_correct": True},
            {"text": "OSPF", "is_correct": False},
            {"text": "RIP", "is_correct": False},
            {"text": "EIGRP", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum MTU size supported by AWS Direct Connect?",
        "explanation": "AWS Direct Connect supports jumbo frames with a maximum MTU size of 9001 bytes for Virtual Interfaces (VIFs).",
        "reference": "https://docs.aws.amazon.com/directconnect/latest/userguide/set-jumbo-frames-vif.html",
        "points": 1,
        "answers": [
            {"text": "9001 bytes", "is_correct": True},
            {"text": "1500 bytes", "is_correct": False},
            {"text": "9000 bytes", "is_correct": False},
            {"text": "1518 bytes", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides network packet inspection capabilities?",
        "explanation": "AWS Network Firewall provides fine-grained network traffic inspection and filtering capabilities for VPCs. It can inspect traffic at the packet level and apply rules based on various criteria.",
        "reference": "https://docs.aws.amazon.com/network-firewall/",
        "points": 1,
        "answers": [
            {"text": "AWS Network Firewall", "is_correct": True},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "AWS Shield", "is_correct": False},
            {"text": "Security Groups", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Client VPN?",
        "explanation": "AWS Client VPN is a managed client-based VPN service that enables you to securely access your AWS resources and resources in your on-premises network from any location.",
        "reference": "https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/",
        "points": 1,
        "answers": [
            {"text": "Managed client-based VPN service", "is_correct": True},
            {"text": "Site-to-site VPN connection", "is_correct": False},
            {"text": "Direct Connect alternative", "is_correct": False},
            {"text": "Load balancing service", "is_correct": False},
        ],
    },
    {
        "text": "Which feature of Route 53 allows you to route traffic based on the health of your resources?",
        "explanation": "Route 53 health checks monitor the health and performance of your web applications, web servers, and other resources. You can use health checks with failover routing to route traffic away from unhealthy resources.",
        "reference": "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover.html",
        "points": 1,
        "answers": [
            {"text": "Health checks with failover routing", "is_correct": True},
            {"text": "Weighted routing", "is_correct": False},
            {"text": "Geolocation routing", "is_correct": False},
            {"text": "Latency-based routing", "is_correct": False},
        ],
    },
    {
        "text": "What is the default behavior of a Network ACL?",
        "explanation": "The default Network ACL allows all inbound and outbound traffic. Custom Network ACLs start with deny all rules and you must explicitly add allow rules.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html",
        "points": 1,
        "answers": [
            {"text": "Allows all traffic", "is_correct": True},
            {"text": "Denies all traffic", "is_correct": False},
            {"text": "Allows only HTTPS traffic", "is_correct": False},
            {"text": "Allows only SSH traffic", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed DNS resolution for VPCs?",
        "explanation": "Amazon Route 53 Resolver provides DNS resolution for VPCs. It automatically provides DNS resolution for instances within a VPC and can be configured for hybrid cloud scenarios.",
        "reference": "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver.html",
        "points": 1,
        "answers": [
            {"text": "Route 53 Resolver", "is_correct": True},
            {"text": "AWS Directory Service", "is_correct": False},
            {"text": "AWS DNS", "is_correct": False},
            {"text": "VPC DNS", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of routes in a VPC route table?",
        "explanation": "By default, you can have up to 50 routes in a route table, but this limit can be increased to 1,000 routes per route table by contacting AWS Support.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html",
        "points": 1,
        "answers": [
            {"text": "50 (can be increased to 1,000)", "is_correct": True},
            {"text": "100", "is_correct": False},
            {"text": "200", "is_correct": False},
            {"text": "Unlimited", "is_correct": False},
        ],
    },
    {
        "text": "Which type of Direct Connect connection provides the highest bandwidth?",
        "explanation": "Dedicated Direct Connect connections provide the highest bandwidth, with options up to 100 Gbps. These are physical connections dedicated to a single customer.",
        "reference": "https://docs.aws.amazon.com/directconnect/latest/userguide/getting_started.html",
        "points": 1,
        "answers": [
            {"text": "Dedicated connection", "is_correct": True},
            {"text": "Hosted connection", "is_correct": False},
            {"text": "Virtual connection", "is_correct": False},
            {"text": "Shared connection", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS App Mesh used for?",
        "explanation": "AWS App Mesh is a service mesh that provides application-level networking to make it easy for your services to communicate with each other across multiple types of compute infrastructure.",
        "reference": "https://docs.aws.amazon.com/app-mesh/",
        "points": 1,
        "answers": [
            {
                "text": "Service mesh for application-level networking",
                "is_correct": True,
            },
            {"text": "Load balancing", "is_correct": False},
            {"text": "DNS management", "is_correct": False},
            {"text": "VPN connectivity", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides bandwidth throttling for APIs?",
        "explanation": "Amazon API Gateway provides request throttling to protect your backend services from traffic spikes and to control costs. You can set throttling rules at various levels.",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html",
        "points": 1,
        "answers": [
            {"text": "Amazon API Gateway", "is_correct": True},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "AWS Shield", "is_correct": False},
            {"text": "Elastic Load Balancer", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of VPC peering?",
        "explanation": "VPC peering allows you to connect two VPCs privately using AWS's network. Instances in either VPC can communicate with each other as if they are within the same network.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/peering/",
        "points": 1,
        "answers": [
            {"text": "Connect two VPCs privately", "is_correct": True},
            {"text": "Connect VPC to internet", "is_correct": False},
            {"text": "Load balance traffic", "is_correct": False},
            {"text": "Provide DNS resolution", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides network insights and troubleshooting?",
        "explanation": "VPC Reachability Analyzer is a configuration analysis tool that enables you to perform connectivity testing between a source and destination resource in your VPCs.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/reachability/",
        "points": 1,
        "answers": [
            {"text": "VPC Reachability Analyzer", "is_correct": True},
            {"text": "AWS X-Ray", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon Inspector", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between Internet Gateway and NAT Gateway?",
        "explanation": "Internet Gateway enables bidirectional internet access for public subnets, while NAT Gateway enables outbound internet access for private subnets without allowing inbound connections from the internet.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html",
        "points": 1,
        "answers": [
            {
                "text": "IGW provides bidirectional access, NAT Gateway provides outbound-only access",
                "is_correct": True,
            },
            {"text": "Both provide the same functionality", "is_correct": False},
            {
                "text": "IGW is for private subnets, NAT Gateway is for public subnets",
                "is_correct": False,
            },
            {"text": "NAT Gateway provides bidirectional access", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed certificate management for SSL/TLS?",
        "explanation": "AWS Certificate Manager (ACM) is a service that lets you easily provision, manage, and deploy public and private SSL/TLS certificates for use with AWS services.",
        "reference": "https://docs.aws.amazon.com/acm/",
        "points": 1,
        "answers": [
            {"text": "AWS Certificate Manager (ACM)", "is_correct": True},
            {"text": "AWS KMS", "is_correct": False},
            {"text": "AWS Secrets Manager", "is_correct": False},
            {"text": "AWS IAM", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of Availability Zones that a VPC can span?",
        "explanation": "A VPC can span all Availability Zones within a region. The number of AZs varies by region, but a VPC is not limited in how many AZs it can span within its region.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/how-it-works.html",
        "points": 1,
        "answers": [
            {"text": "All AZs within the region", "is_correct": True},
            {"text": "Maximum of 3 AZs", "is_correct": False},
            {"text": "Maximum of 5 AZs", "is_correct": False},
            {"text": "Only 1 AZ", "is_correct": False},
        ],
    },
    {
        "text": "Which feature of AWS Global Accelerator improves application performance?",
        "explanation": "AWS Global Accelerator uses AWS's global network infrastructure and anycast IP addresses to route traffic to the optimal endpoint based on health, geography, and routing policies.",
        "reference": "https://docs.aws.amazon.com/global-accelerator/latest/dg/what-is-global-accelerator.html",
        "points": 1,
        "answers": [
            {
                "text": "Global network infrastructure with anycast IPs",
                "is_correct": True,
            },
            {"text": "Content caching", "is_correct": False},
            {"text": "DNS optimization", "is_correct": False},
            {"text": "Load balancing only", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Cloud WAN used for?",
        "explanation": "AWS Cloud WAN is a managed wide area networking (WAN) service that makes it easy to build, manage, and monitor a global network that connects resources running across your cloud and on-premises environments.",
        "reference": "https://docs.aws.amazon.com/cloud-wan/",
        "points": 1,
        "answers": [
            {"text": "Managed wide area networking service", "is_correct": True},
            {"text": "Virtual private cloud", "is_correct": False},
            {"text": "Content delivery network", "is_correct": False},
            {"text": "DNS management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides network monitoring and observability?",
        "explanation": "Amazon CloudWatch provides monitoring and observability for AWS network resources. It collects and tracks metrics, collects and monitors log files, and sets alarms.",
        "reference": "https://docs.aws.amazon.com/cloudwatch/",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudWatch", "is_correct": True},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon Inspector", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Resource Access Manager (RAM) in networking?",
        "explanation": "AWS RAM enables you to share AWS resources with other AWS accounts or within your AWS Organizations. For networking, this includes sharing subnets, Transit Gateways, and other network resources.",
        "reference": "https://docs.aws.amazon.com/ram/",
        "points": 1,
        "answers": [
            {"text": "Share AWS resources across accounts", "is_correct": True},
            {"text": "Manage user access", "is_correct": False},
            {"text": "Monitor resource usage", "is_correct": False},
            {"text": "Encrypt network traffic", "is_correct": False},
        ],
    },
    {
        "text": "Which load balancer type is best for extreme performance and static IP requirements?",
        "explanation": "Network Load Balancer is designed for extreme performance, handling millions of requests per second with ultra-low latencies, and supports static IP addresses.",
        "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html",
        "points": 1,
        "answers": [
            {"text": "Network Load Balancer", "is_correct": True},
            {"text": "Application Load Balancer", "is_correct": False},
            {"text": "Classic Load Balancer", "is_correct": False},
            {"text": "Gateway Load Balancer", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Wavelength designed for?",
        "explanation": "AWS Wavelength embeds AWS compute and storage services within communications service providers' 5G networks, providing ultra-low latency applications for 5G devices.",
        "reference": "https://docs.aws.amazon.com/wavelength/",
        "points": 1,
        "answers": [
            {
                "text": "Ultra-low latency applications for 5G networks",
                "is_correct": True,
            },
            {"text": "Satellite communications", "is_correct": False},
            {"text": "Edge computing for IoT", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides centralized network firewall management?",
        "explanation": "AWS Firewall Manager is a security management service that allows you to centrally configure and manage firewall rules across your accounts and applications in AWS Organizations.",
        "reference": "https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html",
        "points": 1,
        "answers": [
            {"text": "AWS Firewall Manager", "is_correct": True},
            {"text": "AWS Network Firewall", "is_correct": False},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of elastic network interfaces (ENIs) per instance?",
        "explanation": "The maximum number of ENIs per instance depends on the instance type. It varies from 2 for small instances to 15 for large instances like c5n.18xlarge.",
        "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html",
        "points": 1,
        "answers": [
            {"text": "Depends on instance type (2-15)", "is_correct": True},
            {"text": "Always 5", "is_correct": False},
            {"text": "Always 10", "is_correct": False},
            {"text": "Unlimited", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides DNS query logging?",
        "explanation": "Route 53 Resolver query logging allows you to log DNS queries that originate from your VPCs, helping with security analysis and troubleshooting.",
        "reference": "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs.html",
        "points": 1,
        "answers": [
            {"text": "Route 53 Resolver query logging", "is_correct": True},
            {"text": "VPC Flow Logs", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Local Zones?",
        "explanation": "AWS Local Zones are a type of infrastructure deployment that places compute, storage, database, and other select AWS services close to large population and industry centers for ultra-low latency applications.",
        "reference": "https://docs.aws.amazon.com/local-zones/",
        "points": 1,
        "answers": [
            {
                "text": "Ultra-low latency infrastructure near population centers",
                "is_correct": True,
            },
            {"text": "Disaster recovery sites", "is_correct": False},
            {"text": "Edge caching locations", "is_correct": False},
            {"text": "Backup storage locations", "is_correct": False},
        ],
    },
    {
        "text": "Which feature helps optimize Route 53 DNS resolution performance?",
        "explanation": "Route 53 uses anycast networking and has a global network of DNS servers that automatically route queries to the nearest healthy server, optimizing resolution performance.",
        "reference": "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/route-53-concepts.html",
        "points": 1,
        "answers": [
            {"text": "Anycast networking with global DNS servers", "is_correct": True},
            {"text": "DNS caching only", "is_correct": False},
            {"text": "Single authoritative server", "is_correct": False},
            {"text": "Regional DNS servers only", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Snow Family's role in networking?",
        "explanation": "AWS Snow Family devices provide offline data transfer capabilities and edge computing. They can help with large-scale data migration when network bandwidth is limited or costly.",
        "reference": "https://docs.aws.amazon.com/snow/",
        "points": 1,
        "answers": [
            {
                "text": "Offline data transfer when network bandwidth is limited",
                "is_correct": True,
            },
            {"text": "Real-time network monitoring", "is_correct": False},
            {"text": "DNS resolution", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides network packet capture capabilities?",
        "explanation": "VPC Traffic Mirroring allows you to copy network traffic from an elastic network interface and send it to security and monitoring appliances for content inspection, threat monitoring, and troubleshooting.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/mirroring/",
        "points": 1,
        "answers": [
            {"text": "VPC Traffic Mirroring", "is_correct": True},
            {"text": "VPC Flow Logs", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between dedicated and default tenancy in VPC?",
        "explanation": "Default tenancy runs instances on shared hardware, while dedicated tenancy runs instances on single-tenant hardware dedicated to a single customer account for compliance and licensing requirements.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/dedicated-instance.html",
        "points": 1,
        "answers": [
            {
                "text": "Default uses shared hardware, dedicated uses single-tenant hardware",
                "is_correct": True,
            },
            {"text": "No difference in hardware", "is_correct": False},
            {"text": "Dedicated is faster", "is_correct": False},
            {"text": "Default is more secure", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides automated network vulnerability assessment?",
        "explanation": "Amazon Inspector is an automated security assessment service that helps improve the security and compliance of applications. It can assess network reachability and security group configurations.",
        "reference": "https://docs.aws.amazon.com/inspector/",
        "points": 1,
        "answers": [
            {"text": "Amazon Inspector", "is_correct": True},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Carrier IP in AWS Wavelength?",
        "explanation": "Carrier IP addresses are unique IP addresses provided by the telecommunications carrier in Wavelength Zones. They enable communication with resources in Wavelength Zones and mobile devices.",
        "reference": "https://docs.aws.amazon.com/wavelength/latest/developerguide/wavelength-quotas.html",
        "points": 1,
        "answers": [
            {
                "text": "Unique IPs from telecom carriers for Wavelength communication",
                "is_correct": True,
            },
            {"text": "Regular public IP addresses", "is_correct": False},
            {"text": "Private IP addresses only", "is_correct": False},
            {"text": "Elastic IP addresses", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service helps with network capacity planning?",
        "explanation": "AWS Trusted Advisor provides recommendations for optimizing AWS infrastructure, including network performance and capacity planning recommendations based on usage patterns.",
        "reference": "https://docs.aws.amazon.com/support/latest/user/trusted-advisor.html",
        "points": 1,
        "answers": [
            {"text": "AWS Trusted Advisor", "is_correct": True},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS Cost Explorer", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Outposts' networking model?",
        "explanation": "AWS Outposts extends AWS infrastructure to on-premises locations. It uses local gateways for local traffic and connects to the parent AWS Region for AWS services access.",
        "reference": "https://docs.aws.amazon.com/outposts/latest/userguide/outposts-networking-components.html",
        "points": 1,
        "answers": [
            {
                "text": "Local gateway for local traffic, connection to parent Region",
                "is_correct": True,
            },
            {"text": "Completely isolated from AWS", "is_correct": False},
            {"text": "Only connects through Direct Connect", "is_correct": False},
            {"text": "Uses only VPN connections", "is_correct": False},
        ],
    },
    {
        "text": "Which feature of Transit Gateway enables network segmentation?",
        "explanation": "Transit Gateway Route Tables enable network segmentation by controlling how traffic flows between connected VPCs and on-premises networks through the Transit Gateway.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/tgw/tgw-route-tables.html",
        "points": 1,
        "answers": [
            {"text": "Route Tables", "is_correct": True},
            {"text": "Security Groups", "is_correct": False},
            {"text": "Network ACLs", "is_correct": False},
            {"text": "VPC Endpoints", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum bandwidth for a single VIF in Direct Connect?",
        "explanation": "The maximum bandwidth for a single Virtual Interface (VIF) in Direct Connect is limited by the physical port capacity, which can be up to 100 Gbps for dedicated connections.",
        "reference": "https://docs.aws.amazon.com/directconnect/latest/userguide/limits.html",
        "points": 1,
        "answers": [
            {
                "text": "Up to the physical port capacity (max 100 Gbps)",
                "is_correct": True,
            },
            {"text": "Always 10 Gbps", "is_correct": False},
            {"text": "Maximum 50 Gbps", "is_correct": False},
            {"text": "No limit", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides network automation and orchestration?",
        "explanation": "AWS CloudFormation provides infrastructure as code capabilities, allowing you to automate and orchestrate the deployment of network resources using templates.",
        "reference": "https://docs.aws.amazon.com/cloudformation/",
        "points": 1,
        "answers": [
            {"text": "AWS CloudFormation", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "AWS Step Functions", "is_correct": False},
            {"text": "AWS CodeDeploy", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Route 53 Application Recovery Controller?",
        "explanation": "Route 53 Application Recovery Controller helps you prepare for and coordinate recovery across AWS Regions and Availability Zones using readiness checks and routing controls.",
        "reference": "https://docs.aws.amazon.com/r53recovery/latest/dg/what-is-route53-recovery.html",
        "points": 1,
        "answers": [
            {"text": "Coordinate recovery across regions and AZs", "is_correct": True},
            {"text": "DNS caching", "is_correct": False},
            {"text": "Load balancing only", "is_correct": False},
            {"text": "SSL certificate management", "is_correct": False},
        ],
    },
    {
        "text": "Which protocol does AWS VPN use for encryption?",
        "explanation": "AWS Site-to-Site VPN uses IPsec (Internet Protocol Security) for encrypting traffic between your network and AWS. It supports both IKEv1 and IKEv2.",
        "reference": "https://docs.aws.amazon.com/vpn/latest/s2svpn/VPC_VPN.html",
        "points": 1,
        "answers": [
            {"text": "IPsec", "is_correct": True},
            {"text": "SSL/TLS", "is_correct": False},
            {"text": "PPTP", "is_correct": False},
            {"text": "L2TP", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Direct Connect Gateway used for?",
        "explanation": "Direct Connect Gateway allows you to connect your AWS Direct Connect connection to VPCs in any AWS Region (except China), providing global reach for your Direct Connect connection.",
        "reference": "https://docs.aws.amazon.com/directconnect/latest/userguide/direct-connect-gateways.html",
        "points": 1,
        "answers": [
            {
                "text": "Connect Direct Connect to VPCs in any AWS Region",
                "is_correct": True,
            },
            {"text": "Provide internet access", "is_correct": False},
            {"text": "Load balance traffic", "is_correct": False},
            {"text": "Encrypt Direct Connect traffic", "is_correct": False},
        ],
    },
    {
        "text": "Which feature helps reduce latency for global applications?",
        "explanation": "AWS Global Accelerator improves global application performance by using AWS's global network infrastructure and anycast IP addresses to route traffic to the optimal endpoint.",
        "reference": "https://docs.aws.amazon.com/global-accelerator/latest/dg/what-is-global-accelerator.html",
        "points": 1,
        "answers": [
            {"text": "AWS Global Accelerator", "is_correct": True},
            {"text": "Amazon CloudFront only", "is_correct": False},
            {"text": "Route 53 only", "is_correct": False},
            {"text": "Elastic Load Balancer only", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Network Load Balancer's cross-zone load balancing?",
        "explanation": "Cross-zone load balancing distributes traffic evenly across all registered targets in all enabled Availability Zones, ensuring better load distribution even when targets are unevenly distributed across zones.",
        "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html",
        "points": 1,
        "answers": [
            {"text": "Distribute traffic evenly across all AZs", "is_correct": True},
            {"text": "Balance only within single AZ", "is_correct": False},
            {"text": "Provide SSL termination", "is_correct": False},
            {"text": "Enable health checks", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides centralized network access control?",
        "explanation": "AWS Network Access Analyzer helps you understand network access to your resources. It identifies unintended network access and helps you implement security best practices.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/network-access-analyzer/",
        "points": 1,
        "answers": [
            {"text": "AWS Network Access Analyzer", "is_correct": True},
            {"text": "AWS IAM", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of Direct Connect connections per AWS account per region?",
        "explanation": "By default, you can create up to 10 Direct Connect connections per AWS account per region. This limit can be increased by contacting AWS Support.",
        "reference": "https://docs.aws.amazon.com/directconnect/latest/userguide/limits.html",
        "points": 1,
        "answers": [
            {"text": "10 (can be increased)", "is_correct": True},
            {"text": "5", "is_correct": False},
            {"text": "20", "is_correct": False},
            {"text": "Unlimited", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service helps optimize network costs?",
        "explanation": "AWS Cost Explorer provides cost optimization recommendations for network resources, helping you understand and optimize data transfer costs across your AWS infrastructure.",
        "reference": "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html",
        "points": 1,
        "answers": [
            {"text": "AWS Cost Explorer", "is_correct": True},
            {"text": "AWS Trusted Advisor", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Gateway Load Balancer?",
        "explanation": "Gateway Load Balancer makes it easy to deploy, scale, and manage virtual appliances like firewalls, intrusion detection and prevention systems, and deep packet inspection systems.",
        "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/gateway/",
        "points": 1,
        "answers": [
            {"text": "Deploy and scale virtual network appliances", "is_correct": True},
            {"text": "HTTP/HTTPS load balancing", "is_correct": False},
            {"text": "TCP/UDP load balancing", "is_correct": False},
            {"text": "DNS load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which feature of CloudFront helps improve security?",
        "explanation": "AWS WAF integration with CloudFront helps protect web applications from common web exploits by filtering malicious traffic at the edge locations before it reaches your origin servers.",
        "reference": "https://docs.aws.amazon.com/cloudfront/latest/developerguide/distribution-web-awswaf.html",
        "points": 1,
        "answers": [
            {"text": "AWS WAF integration", "is_correct": True},
            {"text": "SSL certificates only", "is_correct": False},
            {"text": "Geographic restrictions only", "is_correct": False},
            {"text": "Origin access identity only", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Verified Access used for?",
        "explanation": "AWS Verified Access provides secure access to corporate applications without a VPN by validating each application request based on user identity and device security status.",
        "reference": "https://docs.aws.amazon.com/verified-access/",
        "points": 1,
        "answers": [
            {"text": "Secure application access without VPN", "is_correct": True},
            {"text": "DNS resolution", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides network path analysis?",
        "explanation": "VPC Reachability Analyzer performs connectivity testing between a source and destination resource in your VPCs and produces hop-by-hop details of the virtual network path.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/reachability/what-is-reachability-analyzer.html",
        "points": 1,
        "answers": [
            {"text": "VPC Reachability Analyzer", "is_correct": True},
            {"text": "AWS X-Ray", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "VPC Flow Logs", "is_correct": False},
        ],
    },
]
