"""AWS Database Specialty Certification"""

CERTIFICATION = {
    "name": "AWS Certified Database - Specialty",
    "description": "Design, deploy, and maintain AWS database solutions",
    "slug": "aws-database-specialty",
    "level": "Specialty",
    "duration": 168,
    "questions_count": 56,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which AWS service provides managed relational databases?",
        "explanation": "Amazon Relational Database Service (Amazon RDS) makes it easy to set up, operate, and scale a relational database in the cloud. It provides cost-efficient and resizable capacity while automating time-consuming administration tasks such as hardware provisioning, database setup, patching and backups.",
        "reference": "https://docs.aws.amazon.com/rds/",
        "points": 1,
        "answers": [
            {"text": "Amazon RDS", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon ElastiCache", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": False},
        ],
    },
    {
        "text": "What type of database is Amazon DynamoDB?",
        "explanation": "Amazon DynamoDB is a key-value and document database that delivers single-digit millisecond performance at any scale. It's a fully managed, multiregion, multimaster, durable database with built-in security, backup and restore, and in-memory caching for internet-scale applications.",
        "reference": "https://docs.aws.amazon.com/dynamodb/",
        "points": 1,
        "answers": [
            {"text": "NoSQL (key-value and document)", "is_correct": True},
            {"text": "Relational", "is_correct": False},
            {"text": "Graph", "is_correct": False},
            {"text": "Time-series", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides managed MongoDB-compatible database?",
        "explanation": "Amazon DocumentDB (with MongoDB compatibility) is a fast, scalable, highly available, and fully managed document database service that supports MongoDB workloads.",
        "reference": "https://docs.aws.amazon.com/documentdb/",
        "points": 1,
        "answers": [
            {"text": "Amazon DocumentDB", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon Neptune", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Aurora?",
        "explanation": "Amazon Aurora is a MySQL and PostgreSQL-compatible relational database built for the cloud, that combines the performance and availability of traditional enterprise databases with the simplicity and cost-effectiveness of open source databases.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/",
        "points": 1,
        "answers": [
            {
                "text": "MySQL and PostgreSQL-compatible cloud-native database",
                "is_correct": True,
            },
            {"text": "NoSQL database", "is_correct": False},
            {"text": "In-memory cache", "is_correct": False},
            {"text": "Graph database", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed graph database?",
        "explanation": "Amazon Neptune is a fast, reliable, fully-managed graph database service that makes it easy to build and run applications that work with highly connected datasets.",
        "reference": "https://docs.aws.amazon.com/neptune/",
        "points": 1,
        "answers": [
            {"text": "Amazon Neptune", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon ElastiCache", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum storage capacity for a single Aurora cluster?",
        "explanation": "Amazon Aurora can automatically scale storage from 10 GB up to 128 TiB (tebibytes) as your database grows, without any impact to database performance.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.html",
        "points": 1,
        "answers": [
            {"text": "128 TiB", "is_correct": True},
            {"text": "64 TiB", "is_correct": False},
            {"text": "32 TiB", "is_correct": False},
            {"text": "16 TiB", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB feature provides automatic scaling?",
        "explanation": "DynamoDB Auto Scaling automatically adjusts read and write throughput capacity in response to dynamically changing request volumes, helping you maintain steady, predictable performance at the lowest possible cost.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.html",
        "points": 1,
        "answers": [
            {"text": "DynamoDB Auto Scaling", "is_correct": True},
            {"text": "DynamoDB Streams", "is_correct": False},
            {"text": "DynamoDB Accelerator (DAX)", "is_correct": False},
            {"text": "DynamoDB Global Tables", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum item size in DynamoDB?",
        "explanation": "The maximum item size in DynamoDB is 400 KB. This includes both attribute names (binary length) and attribute values (lengths as stored).",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html",
        "points": 1,
        "answers": [
            {"text": "400 KB", "is_correct": True},
            {"text": "1 MB", "is_correct": False},
            {"text": "256 KB", "is_correct": False},
            {"text": "64 KB", "is_correct": False},
        ],
    },
    {
        "text": "Which RDS engine supports read replicas across regions?",
        "explanation": "Amazon RDS supports cross-region read replicas for MySQL, MariaDB, PostgreSQL, Oracle, and SQL Server engines, providing disaster recovery and read scaling capabilities.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html",
        "points": 1,
        "answers": [
            {
                "text": "All RDS engines support cross-region read replicas",
                "is_correct": True,
            },
            {"text": "Only MySQL and PostgreSQL", "is_correct": False},
            {"text": "Only MySQL", "is_correct": False},
            {"text": "None support cross-region read replicas", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon ElastiCache primarily used for?",
        "explanation": "Amazon ElastiCache is a web service that makes it easy to deploy, operate, and scale an in-memory cache in the cloud. It improves the performance of web applications by allowing you to retrieve information from fast, managed, in-memory caches.",
        "reference": "https://docs.aws.amazon.com/elasticache/",
        "points": 1,
        "answers": [
            {
                "text": "In-memory caching to improve application performance",
                "is_correct": True,
            },
            {"text": "Persistent data storage", "is_correct": False},
            {"text": "Data warehousing", "is_correct": False},
            {"text": "File storage", "is_correct": False},
        ],
    },
    {
        "text": "Which Aurora feature provides continuous backup?",
        "explanation": "Aurora automatic backup provides continuous, incremental backups of your cluster volume and enables point-in-time recovery. Backups are stored in Amazon S3 and are automatically encrypted.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html",
        "points": 1,
        "answers": [
            {"text": "Aurora automatic backup", "is_correct": True},
            {"text": "Aurora manual snapshots", "is_correct": False},
            {"text": "Aurora Parallel Query", "is_correct": False},
            {"text": "Aurora Global Database", "is_correct": False},
        ],
    },
    {
        "text": "What is DynamoDB Global Tables used for?",
        "explanation": "DynamoDB Global Tables provide a fully managed solution for deploying a multiregion, multi-master database, without having to build and maintain your own replication solution.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html",
        "points": 1,
        "answers": [
            {"text": "Multi-region, multi-master replication", "is_correct": True},
            {"text": "In-memory caching", "is_correct": False},
            {"text": "Batch processing", "is_correct": False},
            {"text": "Data archival", "is_correct": False},
        ],
    },
    {
        "text": "Which database engine is best for OLTP workloads requiring ACID transactions?",
        "explanation": "Amazon Aurora with MySQL or PostgreSQL compatibility provides full ACID transaction support and is optimized for OLTP (Online Transaction Processing) workloads with high concurrency and low latency requirements.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.AuroraMySQL.html",
        "points": 1,
        "answers": [
            {"text": "Amazon Aurora", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon ElastiCache", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of DynamoDB Accelerator (DAX)?",
        "explanation": "DAX is a fully managed, highly available, in-memory cache for DynamoDB that delivers up to 10x performance improvement – from milliseconds to microseconds – even at millions of requests per second.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.html",
        "points": 1,
        "answers": [
            {
                "text": "In-memory cache for DynamoDB to improve performance",
                "is_correct": True,
            },
            {"text": "Data encryption service", "is_correct": False},
            {"text": "Backup and restore service", "is_correct": False},
            {"text": "Query optimization tool", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides time-series database capabilities?",
        "explanation": "Amazon Timestream is a fast, scalable, and serverless time series database service for IoT and operational applications that makes it easy to store and analyze trillions of time series data points per day.",
        "reference": "https://docs.aws.amazon.com/timestream/",
        "points": 1,
        "answers": [
            {"text": "Amazon Timestream", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon Aurora", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of read replicas for an Aurora cluster?",
        "explanation": "An Aurora cluster can have up to 15 Aurora Replicas in addition to the primary DB instance. Aurora Replicas share the same underlying storage as the primary instance.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Replication.html",
        "points": 1,
        "answers": [
            {"text": "15 Aurora Replicas", "is_correct": True},
            {"text": "5 Aurora Replicas", "is_correct": False},
            {"text": "10 Aurora Replicas", "is_correct": False},
            {"text": "20 Aurora Replicas", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB consistency model provides the most up-to-date data?",
        "explanation": "Strongly consistent reads in DynamoDB return a result that reflects all writes that received a successful response prior to the read, ensuring you get the most up-to-date data.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html",
        "points": 1,
        "answers": [
            {"text": "Strongly consistent reads", "is_correct": True},
            {"text": "Eventually consistent reads", "is_correct": False},
            {"text": "Transactional reads", "is_correct": False},
            {"text": "Batch reads", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon MemoryDB for Redis?",
        "explanation": "Amazon MemoryDB for Redis is a durable, in-memory database service that delivers ultra-fast performance. It's compatible with Redis and provides data durability and Multi-AZ support.",
        "reference": "https://docs.aws.amazon.com/memorydb/",
        "points": 1,
        "answers": [
            {
                "text": "Durable, in-memory database compatible with Redis",
                "is_correct": True,
            },
            {"text": "Relational database service", "is_correct": False},
            {"text": "Document database service", "is_correct": False},
            {"text": "Graph database service", "is_correct": False},
        ],
    },
    {
        "text": "Which Aurora feature allows querying data without moving it to Aurora?",
        "explanation": "Aurora Parallel Query allows Aurora to push down and distribute query processing across thousands of CPUs in Aurora's storage layer, enabling faster analytical queries over current data.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-mysql-parallel-query.html",
        "points": 1,
        "answers": [
            {"text": "Aurora Parallel Query", "is_correct": True},
            {"text": "Aurora Global Database", "is_correct": False},
            {"text": "Aurora Serverless", "is_correct": False},
            {"text": "Aurora Multi-Master", "is_correct": False},
        ],
    },
    {
        "text": "What is the backup retention period for Aurora automatic backups?",
        "explanation": "Aurora automatic backups have a retention period that can be set from 1 to 35 days. The default retention period is 1 day if you create the cluster using the console, and 1 day if you create it using the AWS CLI or API.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html",
        "points": 1,
        "answers": [
            {"text": "1 to 35 days", "is_correct": True},
            {"text": "1 to 7 days", "is_correct": False},
            {"text": "1 to 14 days", "is_correct": False},
            {"text": "7 to 35 days", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB feature captures item-level changes?",
        "explanation": "DynamoDB Streams captures data modification events in DynamoDB tables. The stream records appear in the same sequence as the actual modifications to the DynamoDB table.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html",
        "points": 1,
        "answers": [
            {"text": "DynamoDB Streams", "is_correct": True},
            {"text": "DynamoDB Auto Scaling", "is_correct": False},
            {"text": "DynamoDB Accelerator (DAX)", "is_correct": False},
            {"text": "DynamoDB Global Tables", "is_correct": False},
        ],
    },
    {
        "text": "What is Aurora Serverless v2?",
        "explanation": "Aurora Serverless v2 scales instantly from fractions of a capacity unit to hundreds of capacity units, providing fine-grained scaling and supporting the full breadth of Aurora features.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html",
        "points": 1,
        "answers": [
            {
                "text": "Auto-scaling Aurora with fine-grained capacity adjustment",
                "is_correct": True,
            },
            {"text": "Serverless compute for analytics", "is_correct": False},
            {"text": "Serverless ETL processing", "is_correct": False},
            {"text": "Serverless backup service", "is_correct": False},
        ],
    },
    {
        "text": "Which encryption option is available for DynamoDB at rest?",
        "explanation": "DynamoDB encryption at rest provides an additional layer of data protection by securing your data in the underlying storage. It uses AWS Key Management Service (KMS) keys for encryption.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/EncryptionAtRest.html",
        "points": 1,
        "answers": [
            {"text": "AWS KMS encryption", "is_correct": True},
            {"text": "SSL/TLS only", "is_correct": False},
            {"text": "Client-side encryption only", "is_correct": False},
            {"text": "No encryption available", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of RDS Proxy?",
        "explanation": "Amazon RDS Proxy improves application performance and resilience by pooling and sharing database connections. It reduces connection overhead and provides failover capabilities.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html",
        "points": 1,
        "answers": [
            {
                "text": "Connection pooling and improved application resilience",
                "is_correct": True,
            },
            {"text": "Data encryption", "is_correct": False},
            {"text": "Backup management", "is_correct": False},
            {"text": "Query optimization", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Cassandra?",
        "explanation": "Amazon Keyspaces (for Apache Cassandra) is a scalable, highly available, and managed Apache Cassandra-compatible database service that helps you run Cassandra workloads more easily.",
        "reference": "https://docs.aws.amazon.com/keyspaces/",
        "points": 1,
        "answers": [
            {"text": "Amazon Keyspaces", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": False},
            {"text": "Amazon Neptune", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of Global Secondary Indexes (GSI) per DynamoDB table?",
        "explanation": "You can create up to 20 Global Secondary Indexes per DynamoDB table. Each GSI has its own provisioned throughput settings.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html",
        "points": 1,
        "answers": [
            {"text": "20 GSIs", "is_correct": True},
            {"text": "10 GSIs", "is_correct": False},
            {"text": "5 GSIs", "is_correct": False},
            {"text": "Unlimited GSIs", "is_correct": False},
        ],
    },
    {
        "text": "Which Aurora feature provides cross-region disaster recovery?",
        "explanation": "Aurora Global Database allows a single Aurora database to span multiple AWS regions, enabling fast local reads and disaster recovery from region-wide outages.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database.html",
        "points": 1,
        "answers": [
            {"text": "Aurora Global Database", "is_correct": True},
            {"text": "Aurora Parallel Query", "is_correct": False},
            {"text": "Aurora Serverless", "is_correct": False},
            {"text": "Aurora Multi-Master", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between ElastiCache Redis and Memcached?",
        "explanation": "Redis supports more advanced data structures, persistence, replication, and clustering. Memcached is simpler, multithreaded, and better for basic caching scenarios.",
        "reference": "https://docs.aws.amazon.com/elasticache/latest/red-ug/SelectEngine.html",
        "points": 1,
        "answers": [
            {
                "text": "Redis supports advanced features, Memcached is simpler",
                "is_correct": True,
            },
            {"text": "No significant differences", "is_correct": False},
            {
                "text": "Memcached supports clustering, Redis doesn't",
                "is_correct": False,
            },
            {"text": "Redis is only for session storage", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB operation is most cost-effective for reading multiple items?",
        "explanation": "BatchGetItem operation allows you to retrieve multiple items from one or more tables in a single request, making it more cost-effective than multiple individual GetItem operations.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.BatchOperations",
        "points": 1,
        "answers": [
            {"text": "BatchGetItem", "is_correct": True},
            {"text": "GetItem", "is_correct": False},
            {"text": "Query", "is_correct": False},
            {"text": "Scan", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon QLDB used for?",
        "explanation": "Amazon Quantum Ledger Database (QLDB) is a fully managed ledger database that provides a transparent, immutable, and cryptographically verifiable transaction log owned by a central trusted authority.",
        "reference": "https://docs.aws.amazon.com/qldb/",
        "points": 1,
        "answers": [
            {
                "text": "Immutable, cryptographically verifiable ledger database",
                "is_correct": True,
            },
            {"text": "Relational database", "is_correct": False},
            {"text": "Graph database", "is_correct": False},
            {"text": "Time-series database", "is_correct": False},
        ],
    },
    {
        "text": "Which Aurora storage feature provides high IOPS performance?",
        "explanation": "Aurora storage is designed for high performance with up to 64 TiB of storage that can scale automatically. It provides consistent performance with up to thousands of IOPS.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.StorageReliability.html",
        "points": 1,
        "answers": [
            {"text": "Aurora distributed storage architecture", "is_correct": True},
            {"text": "Aurora Parallel Query", "is_correct": False},
            {"text": "Aurora Serverless", "is_correct": False},
            {"text": "Aurora Global Database", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of DynamoDB Point-in-Time Recovery (PITR)?",
        "explanation": "Point-in-time recovery helps protect your DynamoDB tables from accidental write or delete operations by providing continuous backups for the last 35 days.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.html",
        "points": 1,
        "answers": [
            {
                "text": "Continuous backup and recovery for last 35 days",
                "is_correct": True,
            },
            {"text": "Real-time data replication", "is_correct": False},
            {"text": "Performance optimization", "is_correct": False},
            {"text": "Data compression", "is_correct": False},
        ],
    },
    {
        "text": "Which RDS Multi-AZ deployment provides the fastest failover?",
        "explanation": "RDS Multi-AZ with Aurora provides the fastest failover, typically completing in 30-120 seconds. Aurora's shared storage architecture enables faster failover than traditional Multi-AZ deployments.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html",
        "points": 1,
        "answers": [
            {"text": "Aurora Multi-AZ", "is_correct": True},
            {"text": "RDS Multi-AZ with standby", "is_correct": False},
            {"text": "RDS Multi-AZ with read replicas", "is_correct": False},
            {"text": "All provide the same failover speed", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon DocumentDB Global Clusters?",
        "explanation": "Amazon DocumentDB Global Clusters span multiple AWS Regions, enabling low-latency global reads and disaster recovery from region-wide outages.",
        "reference": "https://docs.aws.amazon.com/documentdb/latest/developerguide/global-clusters.html",
        "points": 1,
        "answers": [
            {
                "text": "Cross-region clusters for global reads and disaster recovery",
                "is_correct": True,
            },
            {"text": "High availability within a single region", "is_correct": False},
            {"text": "Data archival service", "is_correct": False},
            {"text": "Backup and restore service", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB capacity mode automatically scales based on demand?",
        "explanation": "DynamoDB On-Demand mode automatically scales up and down based on your application's traffic patterns, eliminating the need to plan for capacity.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html",
        "points": 1,
        "answers": [
            {"text": "On-Demand mode", "is_correct": True},
            {"text": "Provisioned mode", "is_correct": False},
            {"text": "Reserved mode", "is_correct": False},
            {"text": "Burst mode", "is_correct": False},
        ],
    },
    {
        "text": "What is Neptune Analytics used for?",
        "explanation": "Neptune Analytics is a graph analytics engine that can quickly analyze large amounts of graph data to get insights and find trends for use cases like fraud detection and recommendation engines.",
        "reference": "https://docs.aws.amazon.com/neptune/latest/userguide/neptune-analytics.html",
        "points": 1,
        "answers": [
            {
                "text": "Graph analytics and insights on large datasets",
                "is_correct": True,
            },
            {"text": "Relational data analytics", "is_correct": False},
            {"text": "Time-series analytics", "is_correct": False},
            {"text": "Document search analytics", "is_correct": False},
        ],
    },
    {
        "text": "Which Aurora feature enables write operations across multiple regions?",
        "explanation": "Aurora Global Database with Global Write Forwarding allows write operations to be performed in secondary regions, with writes being forwarded to the primary region.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-write-forwarding.html",
        "points": 1,
        "answers": [
            {"text": "Global Write Forwarding", "is_correct": True},
            {"text": "Aurora Multi-Master", "is_correct": False},
            {"text": "Aurora Parallel Query", "is_correct": False},
            {"text": "Aurora Serverless", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum throughput for a DynamoDB partition?",
        "explanation": "A single DynamoDB partition can handle up to 3,000 read capacity units or 1,000 write capacity units, and up to 10 GB of data.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.Partitions.html",
        "points": 1,
        "answers": [
            {"text": "3,000 RCUs or 1,000 WCUs", "is_correct": True},
            {"text": "5,000 RCUs or 2,000 WCUs", "is_correct": False},
            {"text": "1,000 RCUs or 500 WCUs", "is_correct": False},
            {"text": "Unlimited throughput", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Apache Kafka for streaming?",
        "explanation": "Amazon Managed Streaming for Apache Kafka (MSK) is a fully managed service that makes it easy to build and run applications that use Apache Kafka to process streaming data.",
        "reference": "https://docs.aws.amazon.com/msk/",
        "points": 1,
        "answers": [
            {"text": "Amazon MSK", "is_correct": True},
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon SNS", "is_correct": False},
        ],
    },
    {
        "text": "What is RDS Custom used for?",
        "explanation": "Amazon RDS Custom gives you access to the underlying operating system and database environment, allowing you to customize the database server host and operating system.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/custom.html",
        "points": 1,
        "answers": [
            {
                "text": "Customizable database environment with OS access",
                "is_correct": True,
            },
            {"text": "Serverless database option", "is_correct": False},
            {"text": "Multi-region replication", "is_correct": False},
            {"text": "Automated backup service", "is_correct": False},
        ],
    },
    {
        "text": "Which ElastiCache feature provides automatic failover?",
        "explanation": "ElastiCache Multi-AZ with automatic failover provides enhanced availability and fault tolerance for Redis clusters by maintaining multiple replicas across different Availability Zones.",
        "reference": "https://docs.aws.amazon.com/elasticache/latest/red-ug/AutoFailover.html",
        "points": 1,
        "answers": [
            {"text": "Multi-AZ with automatic failover", "is_correct": True},
            {"text": "Single-AZ deployment", "is_correct": False},
            {"text": "Read replicas only", "is_correct": False},
            {"text": "Manual failover only", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of DynamoDB Transactions?",
        "explanation": "DynamoDB Transactions provide ACID (Atomicity, Consistency, Isolation, Durability) properties across one or more items within a single AWS account and region.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html",
        "points": 1,
        "answers": [
            {"text": "ACID transactions across multiple items", "is_correct": True},
            {"text": "Batch processing operations", "is_correct": False},
            {"text": "Data compression", "is_correct": False},
            {"text": "Query optimization", "is_correct": False},
        ],
    },
    {
        "text": "Which database is best for real-time fraud detection applications?",
        "explanation": "Amazon Neptune is ideal for fraud detection as it can analyze complex relationships and patterns in data using graph algorithms to identify suspicious activities and connections.",
        "reference": "https://docs.aws.amazon.com/neptune/latest/userguide/feature-overview-use-cases.html",
        "points": 1,
        "answers": [
            {"text": "Amazon Neptune", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": False},
        ],
    },
    {
        "text": "What is Aurora Machine Learning?",
        "explanation": "Aurora Machine Learning enables you to add ML-based predictions to applications via SQL by integrating Aurora with AWS ML services like SageMaker and Comprehend.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-ml.html",
        "points": 1,
        "answers": [
            {"text": "ML integration with Aurora via SQL", "is_correct": True},
            {"text": "Automated query optimization", "is_correct": False},
            {"text": "Predictive scaling", "is_correct": False},
            {"text": "Automated backup optimization", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB feature helps optimize costs for infrequently accessed data?",
        "explanation": "DynamoDB Infrequent Access (IA) storage class reduces storage costs for tables or table data that is accessed infrequently, providing up to 60% cost reduction.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithTables.tableclasses.html",
        "points": 1,
        "answers": [
            {"text": "DynamoDB Infrequent Access (IA)", "is_correct": True},
            {"text": "DynamoDB Auto Scaling", "is_correct": False},
            {"text": "DynamoDB Streams", "is_correct": False},
            {"text": "DynamoDB Accelerator", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum backup retention period for RDS?",
        "explanation": "Amazon RDS supports backup retention periods from 0 to 35 days. Setting the retention period to 0 disables automated backups.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html",
        "points": 1,
        "answers": [
            {"text": "35 days", "is_correct": True},
            {"text": "7 days", "is_correct": False},
            {"text": "14 days", "is_correct": False},
            {"text": "90 days", "is_correct": False},
        ],
    },
    {
        "text": "Which Neptune query language is used for property graphs?",
        "explanation": "Gremlin is the query language used for property graphs in Amazon Neptune. It's part of the Apache TinkerPop project and provides a functional graph traversal language.",
        "reference": "https://docs.aws.amazon.com/neptune/latest/userguide/access-graph-gremlin.html",
        "points": 1,
        "answers": [
            {"text": "Gremlin", "is_correct": True},
            {"text": "SPARQL", "is_correct": False},
            {"text": "SQL", "is_correct": False},
            {"text": "Cypher", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon RDS Performance Insights?",
        "explanation": "Amazon RDS Performance Insights is a database performance tuning and monitoring feature that helps you quickly assess the load on your database and determine when and where to take action.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.html",
        "points": 1,
        "answers": [
            {
                "text": "Database performance monitoring and tuning tool",
                "is_correct": True,
            },
            {"text": "Automated backup service", "is_correct": False},
            {"text": "Connection pooling service", "is_correct": False},
            {"text": "Data migration tool", "is_correct": False},
        ],
    },
    {
        "text": "Which feature provides encryption in transit for DynamoDB?",
        "explanation": "DynamoDB uses HTTPS/TLS to encrypt data in transit between your application and DynamoDB. All requests to DynamoDB use SSL/TLS encryption.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/encryption-in-transit.html",
        "points": 1,
        "answers": [
            {"text": "HTTPS/TLS encryption", "is_correct": True},
            {"text": "AWS KMS only", "is_correct": False},
            {"text": "VPC endpoints only", "is_correct": False},
            {"text": "No encryption in transit available", "is_correct": False},
        ],
    },
    {
        "text": "What is Aurora I/O-Optimized?",
        "explanation": "Aurora I/O-Optimized is a cluster configuration that provides improved price performance for I/O-intensive applications by eliminating charges for Aurora I/O operations.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-io-optimized.html",
        "points": 1,
        "answers": [
            {
                "text": "Configuration that eliminates I/O operation charges",
                "is_correct": True,
            },
            {"text": "Automated I/O optimization", "is_correct": False},
            {"text": "In-memory I/O processing", "is_correct": False},
            {"text": "Compressed I/O operations", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed wide-column database?",
        "explanation": "Amazon Keyspaces (for Apache Cassandra) provides a managed wide-column NoSQL database service that's compatible with Apache Cassandra.",
        "reference": "https://docs.aws.amazon.com/keyspaces/latest/devguide/what-is-keyspaces.html",
        "points": 1,
        "answers": [
            {"text": "Amazon Keyspaces", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": False},
            {"text": "Amazon SimpleDB", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of DynamoDB Contributor Insights?",
        "explanation": "DynamoDB Contributor Insights helps you find the most accessed and throttled keys in your table or index, enabling you to optimize application performance and reduce costs.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/contributorinsights.html",
        "points": 1,
        "answers": [
            {"text": "Identify most accessed and throttled keys", "is_correct": True},
            {"text": "Monitor backup operations", "is_correct": False},
            {"text": "Track data encryption status", "is_correct": False},
            {"text": "Analyze query performance", "is_correct": False},
        ],
    },
    {
        "text": "Which Aurora edition provides the highest performance?",
        "explanation": "Aurora PostgreSQL and MySQL provide similar high performance, but the choice depends on your specific workload. Both offer up to 5x the performance of MySQL and 3x the performance of PostgreSQL respectively.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.html",
        "points": 1,
        "answers": [
            {
                "text": "Performance depends on workload, both are high-performance",
                "is_correct": True,
            },
            {"text": "Aurora PostgreSQL only", "is_correct": False},
            {"text": "Aurora MySQL only", "is_correct": False},
            {"text": "Aurora Serverless only", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon RDS Blue/Green Deployments?",
        "explanation": "Amazon RDS Blue/Green Deployments enable you to make safer, simpler, and faster database changes by creating a staging environment that mirrors the production environment.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/blue-green-deployments.html",
        "points": 1,
        "answers": [
            {
                "text": "Safer database changes with staging environment",
                "is_correct": True,
            },
            {"text": "Multi-region deployment strategy", "is_correct": False},
            {"text": "Backup and restore strategy", "is_correct": False},
            {"text": "Performance optimization technique", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB feature provides schema flexibility?",
        "explanation": "DynamoDB's schemaless design allows each item to have a different set of attributes, providing flexibility to add attributes as your application evolves without modifying the table structure.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html",
        "points": 1,
        "answers": [
            {"text": "Schemaless design with flexible attributes", "is_correct": True},
            {"text": "Global Secondary Indexes", "is_correct": False},
            {"text": "DynamoDB Streams", "is_correct": False},
            {"text": "Auto Scaling", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Neptune ML?",
        "explanation": "Neptune ML makes it easy to build and train machine learning models on large graphs using Graph Neural Networks (GNNs) without needing to learn new tools or ML techniques.",
        "reference": "https://docs.aws.amazon.com/neptune/latest/userguide/machine-learning.html",
        "points": 1,
        "answers": [
            {
                "text": "Machine learning on graphs using Graph Neural Networks",
                "is_correct": True,
            },
            {"text": "Query optimization", "is_correct": False},
            {"text": "Automated graph creation", "is_correct": False},
            {"text": "Graph visualization", "is_correct": False},
        ],
    },
]
