"""AWS DevOps Engineer Professional Certification"""

CERTIFICATION = {
    "name": "AWS Certified DevOps Engineer - Professional",
    "description": "Implement and manage continuous delivery systems and methodologies on AWS",
    "slug": "aws-devops-engineer-professional",
    "level": "Professional",
    "duration": 315,
    "questions_count": 105,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [{"text": "Which AWS service provides infrastructure as code?",
              "explanation": "AWS CloudFormation provides a common language for you to model and provision AWS and third party application resources in your cloud environment. CloudFormation allows you to use programming languages or a simple text file to model and provision, in an automated and secure manner, all the resources needed for your applications across all regions and accounts.",
              "reference": "https://docs.aws.amazon.com/cloudformation/",
              "points": 1,
              "answers": [{"text": "AWS CloudFormation",
                           "is_correct": True},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          {"text": "AWS S3",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CodePipeline used for?",
              "explanation": "AWS CodePipeline is a fully managed continuous delivery service that helps you automate your release pipelines for fast and reliable application and infrastructure updates.",
              "reference": "https://docs.aws.amazon.com/codepipeline/",
              "points": 1,
              "answers": [{"text": "Continuous integration and delivery",
                           "is_correct": True},
                          {"text": "Code storage",
                           "is_correct": False},
                          {"text": "Load balancing",
                           "is_correct": False},
                          {"text": "Database management",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides managed Git repositories?",
              "explanation": "AWS CodeCommit is a fully-managed source control service that hosts secure Git-based repositories. It makes it easy for teams to collaborate on code in a secure and highly scalable ecosystem.",
              "reference": "https://docs.aws.amazon.com/codecommit/",
              "points": 1,
              "answers": [{"text": "AWS CodeCommit",
                           "is_correct": True},
                          {"text": "AWS CodeBuild",
                           "is_correct": False},
                          {"text": "AWS CodeDeploy",
                           "is_correct": False},
                          {"text": "AWS CodePipeline",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CodeBuild primarily used for?",
              "explanation": "AWS CodeBuild is a fully managed continuous integration service that compiles source code, runs tests, and produces software packages that are ready to deploy.",
              "reference": "https://docs.aws.amazon.com/codebuild/",
              "points": 1,
              "answers": [{"text": "Building and testing code",
                           "is_correct": True},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          {"text": "Storing source code",
                           "is_correct": False},
                          {"text": "Monitoring applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service automates application deployments?",
              "explanation": "AWS CodeDeploy is a fully managed deployment service that automates software deployments to a variety of compute services such as Amazon EC2, AWS Fargate, AWS Lambda, and your on-premises servers.",
              "reference": "https://docs.aws.amazon.com/codedeploy/",
              "points": 1,
              "answers": [{"text": "AWS CodeDeploy",
                           "is_correct": True},
                          {"text": "AWS CodeCommit",
                           "is_correct": False},
                          {"text": "AWS CodeBuild",
                           "is_correct": False},
                          {"text": "AWS CloudFormation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of AWS CloudWatch?",
              "explanation": "Amazon CloudWatch is a monitoring and observability service that provides data and actionable insights to monitor applications, respond to system-wide performance changes, and optimize resource utilization.",
              "reference": "https://docs.aws.amazon.com/cloudwatch/",
              "points": 1,
              "answers": [{"text": "Monitoring and logging",
                           "is_correct": True},
                          {"text": "Code deployment",
                           "is_correct": False},
                          {"text": "Infrastructure provisioning",
                           "is_correct": False},
                          {"text": "Identity management",
                           "is_correct": False},
                          ],
              },
             {"text": "Which deployment strategy provides the fastest rollback capability?",
              "explanation": "Blue/Green deployment provides the fastest rollback capability because you can instantly switch traffic back to the previous environment if issues are detected.",
              "reference": "https://docs.aws.amazon.com/whitepapers/latest/introduction-devops-aws/deployment-strategies.html",
              "points": 1,
              "answers": [{"text": "Blue/Green deployment",
                           "is_correct": True},
                          {"text": "Rolling deployment",
                           "is_correct": False},
                          {"text": "Canary deployment",
                           "is_correct": False},
                          {"text": "In-place deployment",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Systems Manager Parameter Store used for?",
              "explanation": "AWS Systems Manager Parameter Store provides secure, hierarchical storage for configuration data management and secrets management. You can store data such as passwords, database strings, Amazon Machine Image (AMI) IDs, and license codes as parameter values.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html",
              "points": 1,
              "answers": [{"text": "Storing configuration data and secrets",
                           "is_correct": True},
                          {"text": "Building applications",
                           "is_correct": False},
                          {"text": "Monitoring metrics",
                           "is_correct": False},
                          {"text": "Managing EC2 instances",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service is best for container orchestration?",
              "explanation": "Amazon ECS (Elastic Container Service) and Amazon EKS (Elastic Kubernetes Service) are AWS's primary container orchestration services. ECS is AWS's native container orchestration service, while EKS runs Kubernetes.",
              "reference": "https://docs.aws.amazon.com/ecs/",
              "points": 1,
              "answers": [{"text": "Amazon ECS or EKS",
                           "is_correct": True},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          {"text": "AWS Fargate",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS CloudTrail?",
              "explanation": "AWS CloudTrail is a service that enables governance, compliance, operational auditing, and risk auditing of your AWS account. It logs, continuously monitors, and retains account activity related to actions across your AWS infrastructure.",
              "reference": "https://docs.aws.amazon.com/cloudtrail/",
              "points": 1,
              "answers": [{"text": "Auditing and logging API calls",
                           "is_correct": True},
                          {"text": "Application monitoring",
                           "is_correct": False},
                          {"text": "Code deployment",
                           "is_correct": False},
                          {"text": "Resource provisioning",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed relational databases?",
              "explanation": "Amazon RDS (Relational Database Service) makes it easy to set up, operate, and scale a relational database in the cloud. It provides cost-efficient and resizable capacity while automating time-consuming administration tasks.",
              "reference": "https://docs.aws.amazon.com/rds/",
              "points": 1,
              "answers": [{"text": "Amazon RDS",
                           "is_correct": True},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon S3",
                           "is_correct": False},
                          {"text": "Amazon ElastiCache",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Elastic Beanstalk primarily used for?",
              "explanation": "AWS Elastic Beanstalk is an easy-to-use service for deploying and scaling web applications and services. You simply upload your code and Elastic Beanstalk automatically handles the deployment details of capacity provisioning, load balancing, auto-scaling, and application health monitoring.",
              "reference": "https://docs.aws.amazon.com/elasticbeanstalk/",
              "points": 1,
              "answers": [{"text": "Deploying and scaling web applications",
                           "is_correct": True},
                          {"text": "Managing databases",
                           "is_correct": False},
                          {"text": "Monitoring applications",
                           "is_correct": False},
                          {"text": "Storing files",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service is used for DNS management in AWS?",
              "explanation": "Amazon Route 53 is a highly available and scalable cloud Domain Name System (DNS) web service. It is designed to give developers and businesses an extremely reliable and cost-effective way to route end users to Internet applications.",
              "reference": "https://docs.aws.amazon.com/route53/",
              "points": 1,
              "answers": [{"text": "Amazon Route 53",
                           "is_correct": True},
                          {"text": "AWS CloudFront",
                           "is_correct": False},
                          {"text": "Elastic Load Balancer",
                           "is_correct": False},
                          {"text": "AWS VPC",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of using AWS Auto Scaling?",
              "explanation": "AWS Auto Scaling monitors your applications and automatically adjusts capacity to maintain steady, predictable performance at the lowest possible cost. It helps ensure that you have the right number of EC2 instances available to handle the load for your application.",
              "reference": "https://docs.aws.amazon.com/autoscaling/",
              "points": 1,
              "answers": [{"text": "Automatically adjusting capacity based on demand",
                           "is_correct": True,
                           },
                          {"text": "Reducing security vulnerabilities",
                           "is_correct": False},
                          {"text": "Improving code quality",
                           "is_correct": False},
                          {"text": "Encrypting data",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides content delivery network (CDN) capabilities?",
              "explanation": "Amazon CloudFront is a fast content delivery network (CDN) service that securely delivers data, videos, applications, and APIs to customers globally with low latency and high transfer speeds.",
              "reference": "https://docs.aws.amazon.com/cloudfront/",
              "points": 1,
              "answers": [{"text": "Amazon CloudFront",
                           "is_correct": True},
                          {"text": "Amazon S3",
                           "is_correct": False},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Config used for?",
              "explanation": "AWS Config is a service that enables you to assess, audit, and evaluate the configurations of your AWS resources. It continuously monitors and records your AWS resource configurations and allows you to automate the evaluation of recorded configurations against desired configurations.",
              "reference": "https://docs.aws.amazon.com/config/",
              "points": 1,
              "answers": [{"text": "Configuration management and compliance",
                           "is_correct": True},
                          {"text": "Code compilation",
                           "is_correct": False},
                          {"text": "Application deployment",
                           "is_correct": False},
                          {"text": "Performance monitoring",
                           "is_correct": False},
                          ],
              },
             {"text": "Which deployment configuration in CodeDeploy stops and starts each instance one at a time?",
              "explanation": "OneAtATime deployment configuration deploys the application revision to only one instance at a time. This is the slowest deployment but provides the highest availability during deployment.",
              "reference": "https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html",
              "points": 1,
              "answers": [{"text": "OneAtATime",
                           "is_correct": True},
                          {"text": "HalfAtATime",
                           "is_correct": False},
                          {"text": "AllAtOnce",
                           "is_correct": False},
                          {"text": "BlueGreen",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of AWS CloudFormation StackSets?",
              "explanation": "AWS CloudFormation StackSets extends the functionality of stacks by enabling you to create, update, or delete stacks across multiple accounts and regions with a single operation.",
              "reference": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/what-is-cfnstacksets.html",
              "points": 1,
              "answers": [{"text": "Deploy stacks across multiple accounts and regions",
                           "is_correct": True,
                           },
                          {"text": "Monitor stack performance",
                           "is_correct": False},
                          {"text": "Backup stack configurations",
                           "is_correct": False},
                          {"text": "Optimize stack costs",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides serverless computing?",
              "explanation": "AWS Lambda is a serverless compute service that lets you run code without provisioning or managing servers. You pay only for the compute time you consume—there is no charge when your code is not running.",
              "reference": "https://docs.aws.amazon.com/lambda/",
              "points": 1,
              "answers": [{"text": "AWS Lambda",
                           "is_correct": True},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          {"text": "Amazon ECS",
                           "is_correct": False},
                          {"text": "AWS Batch",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CodeStar used for?",
              "explanation": "AWS CodeStar is a cloud-based service for creating, managing, and working with software development projects on AWS. You can quickly develop, build, and deploy applications on AWS with CodeStar.",
              "reference": "https://docs.aws.amazon.com/codestar/",
              "points": 1,
              "answers": [{"text": "Managing software development projects",
                           "is_correct": True},
                          {"text": "Monitoring applications",
                           "is_correct": False},
                          {"text": "Storing code repositories",
                           "is_correct": False},
                          {"text": "Deploying infrastructure",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed message queuing?",
              "explanation": "Amazon SQS (Simple Queue Service) is a fully managed message queuing service that enables you to decouple and scale microservices, distributed systems, and serverless applications.",
              "reference": "https://docs.aws.amazon.com/sqs/",
              "points": 1,
              "answers": [{"text": "Amazon SQS",
                           "is_correct": True},
                          {"text": "Amazon SNS",
                           "is_correct": False},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon Kinesis",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Secrets Manager?",
              "explanation": "AWS Secrets Manager helps you protect secrets needed to access your applications, services, and IT resources. The service enables you to easily rotate, manage, and retrieve database credentials, API keys, and other secrets throughout their lifecycle.",
              "reference": "https://docs.aws.amazon.com/secretsmanager/",
              "points": 1,
              "answers": [{"text": "Managing and rotating secrets securely",
                           "is_correct": True},
                          {"text": "Building applications",
                           "is_correct": False},
                          {"text": "Monitoring performance",
                           "is_correct": False},
                          {"text": "Managing user identities",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service is best for real-time data streaming?",
              "explanation": "Amazon Kinesis makes it easy to collect, process, and analyze real-time, streaming data so you can get timely insights and react quickly to new information.",
              "reference": "https://docs.aws.amazon.com/kinesis/",
              "points": 1,
              "answers": [{"text": "Amazon Kinesis",
                           "is_correct": True},
                          {"text": "Amazon SQS",
                           "is_correct": False},
                          {"text": "Amazon SNS",
                           "is_correct": False},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS X-Ray used for?",
              "explanation": "AWS X-Ray is a service that collects data about requests that your application serves, and provides tools you can use to view, filter, and gain insights into that data to identify issues and opportunities for optimization.",
              "reference": "https://docs.aws.amazon.com/xray/",
              "points": 1,
              "answers": [{"text": "Distributed application tracing and debugging",
                           "is_correct": True,
                           },
                          {"text": "Code compilation",
                           "is_correct": False},
                          {"text": "Resource provisioning",
                           "is_correct": False},
                          {"text": "User authentication",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides NoSQL database capabilities?",
              "explanation": "Amazon DynamoDB is a key-value and document database that delivers single-digit millisecond performance at any scale. It's a fully managed, multiregion, multimaster, durable database with built-in security, backup and restore, and in-memory caching for internet-scale applications.",
              "reference": "https://docs.aws.amazon.com/dynamodb/",
              "points": 1,
              "answers": [{"text": "Amazon DynamoDB",
                           "is_correct": True},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon S3",
                           "is_correct": False},
                          {"text": "Amazon Redshift",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Systems Manager Session Manager?",
              "explanation": "AWS Systems Manager Session Manager is a fully managed service that provides secure and auditable node management without the need to open inbound ports, maintain bastion hosts, or manage SSH keys.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html",
              "points": 1,
              "answers": [{"text": "Secure shell access to EC2 instances",
                           "is_correct": True},
                          {"text": "Managing application configurations",
                           "is_correct": False},
                          {"text": "Monitoring system performance",
                           "is_correct": False},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides elastic file system storage?",
              "explanation": "Amazon EFS (Elastic File System) provides a simple, scalable, fully managed elastic NFS file system for use with AWS Cloud services and on-premises resources.",
              "reference": "https://docs.aws.amazon.com/efs/",
              "points": 1,
              "answers": [{"text": "Amazon EFS",
                           "is_correct": True},
                          {"text": "Amazon EBS",
                           "is_correct": False},
                          {"text": "Amazon S3",
                           "is_correct": False},
                          {"text": "AWS Storage Gateway",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CodeArtifact used for?",
              "explanation": "AWS CodeArtifact is a fully managed artifact repository service that makes it easy for organizations to securely store, publish, and share software packages used in their software development process.",
              "reference": "https://docs.aws.amazon.com/codeartifact/",
              "points": 1,
              "answers": [{"text": "Managing software packages and dependencies",
                           "is_correct": True},
                          {"text": "Building applications",
                           "is_correct": False},
                          {"text": "Deploying code",
                           "is_correct": False},
                          {"text": "Monitoring applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which deployment strategy minimizes risk by gradually shifting traffic?",
              "explanation": "Canary deployment strategy releases the change to a small subset of servers first, then gradually increases the traffic to the new version while monitoring for issues.",
              "reference": "https://docs.aws.amazon.com/whitepapers/latest/introduction-devops-aws/deployment-strategies.html",
              "points": 1,
              "answers": [{"text": "Canary deployment",
                           "is_correct": True},
                          {"text": "Blue/Green deployment",
                           "is_correct": False},
                          {"text": "Rolling deployment",
                           "is_correct": False},
                          {"text": "All-at-once deployment",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS OpsWorks used for?",
              "explanation": "AWS OpsWorks is a configuration management service that provides managed instances of Chef and Puppet. OpsWorks lets you use Chef and Puppet to automate how servers are configured, deployed, and managed across your Amazon EC2 instances or on-premises compute environments.",
              "reference": "https://docs.aws.amazon.com/opsworks/",
              "points": 1,
              "answers": [{"text": "Configuration management with Chef and Puppet",
                           "is_correct": True,
                           },
                          {"text": "Code deployment",
                           "is_correct": False},
                          {"text": "Database management",
                           "is_correct": False},
                          {"text": "Network configuration",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Kafka?",
              "explanation": "Amazon MSK (Managed Streaming for Apache Kafka) is a fully managed service that makes it easy for you to build and run applications that use Apache Kafka to process streaming data.",
              "reference": "https://docs.aws.amazon.com/msk/",
              "points": 1,
              "answers": [{"text": "Amazon MSK",
                           "is_correct": True},
                          {"text": "Amazon Kinesis",
                           "is_correct": False},
                          {"text": "Amazon SQS",
                           "is_correct": False},
                          {"text": "Amazon SNS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of AWS CloudFormation drift detection?",
              "explanation": "CloudFormation drift detection enables you to detect whether a stack's actual configuration differs, or has drifted, from its expected configuration. You can use drift detection to identify resources that need to be updated.",
              "reference": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html",
              "points": 1,
              "answers": [{"text": "Detect configuration changes outside of CloudFormation",
                           "is_correct": True,
                           },
                          {"text": "Monitor stack performance",
                           "is_correct": False},
                          {"text": "Optimize stack costs",
                           "is_correct": False},
                          {"text": "Backup stack configurations",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides distributed caching?",
              "explanation": "Amazon ElastiCache is a web service that makes it easy to deploy, operate, and scale an in-memory cache in the cloud. It supports Redis and Memcached engines.",
              "reference": "https://docs.aws.amazon.com/elasticache/",
              "points": 1,
              "answers": [{"text": "Amazon ElastiCache",
                           "is_correct": True},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon S3",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CodeGuru used for?",
              "explanation": "Amazon CodeGuru is a developer tool that provides intelligent recommendations to improve code quality and identify the most expensive lines of code. It uses machine learning to provide automated code reviews and application performance recommendations.",
              "reference": "https://docs.aws.amazon.com/codeguru/",
              "points": 1,
              "answers": [{"text": "Code quality analysis and performance optimization",
                           "is_correct": True,
                           },
                          {"text": "Code compilation",
                           "is_correct": False},
                          {"text": "Code deployment",
                           "is_correct": False},
                          {"text": "Code storage",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides data warehouse capabilities?",
              "explanation": "Amazon Redshift is a fast, scalable data warehouse that makes it simple and cost-effective to analyze all your data across your data warehouse and data lake.",
              "reference": "https://docs.aws.amazon.com/redshift/",
              "points": 1,
              "answers": [{"text": "Amazon Redshift",
                           "is_correct": True},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon ElastiCache",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Service Catalog used for?",
              "explanation": "AWS Service Catalog allows organizations to create and manage catalogs of IT services that are approved for use on AWS. These IT services can include everything from virtual machine images, servers, software, and databases to complete multi-tier application architectures.",
              "reference": "https://docs.aws.amazon.com/servicecatalog/",
              "points": 1,
              "answers": [{"text": "Managing catalogs of approved IT services",
                           "is_correct": True},
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          {"text": "Managing user identities",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides API management?",
              "explanation": "Amazon API Gateway is a fully managed service that makes it easy for developers to create, publish, maintain, monitor, and secure APIs at any scale. APIs act as the 'front door' for applications to access data, business logic, or functionality from your backend services.",
              "reference": "https://docs.aws.amazon.com/apigateway/",
              "points": 1,
              "answers": [{"text": "Amazon API Gateway",
                           "is_correct": True},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon CloudFront",
                           "is_correct": False},
                          {"text": "Elastic Load Balancer",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Control Tower?",
              "explanation": "AWS Control Tower provides the easiest way to set up and govern a secure, multi-account AWS environment. It establishes a landing zone that is based on best-practices blueprints, and enables governance using guardrails you can choose from a pre-packaged list.",
              "reference": "https://docs.aws.amazon.com/controltower/",
              "points": 1,
              "answers": [{"text": "Setting up and governing multi-account AWS environments",
                           "is_correct": True,
                           },
                          {"text": "Managing single AWS accounts",
                           "is_correct": False},
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides hybrid cloud storage?",
              "explanation": "AWS Storage Gateway is a hybrid cloud storage service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between an organization's on-premises IT environment and AWS's storage infrastructure.",
              "reference": "https://docs.aws.amazon.com/storagegateway/",
              "points": 1,
              "answers": [{"text": "AWS Storage Gateway",
                           "is_correct": True},
                          {"text": "Amazon S3",
                           "is_correct": False},
                          {"text": "Amazon EBS",
                           "is_correct": False},
                          {"text": "Amazon EFS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS App Mesh used for?",
              "explanation": "AWS App Mesh is a service mesh that provides application-level networking to make it easy for your services to communicate with each other across multiple types of compute infrastructure.",
              "reference": "https://docs.aws.amazon.com/app-mesh/",
              "points": 1,
              "answers": [{"text": "Service mesh for microservices communication",
                           "is_correct": True,
                           },
                          {"text": "Application deployment",
                           "is_correct": False},
                          {"text": "Database management",
                           "is_correct": False},
                          {"text": "User authentication",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides container registry capabilities?",
              "explanation": "Amazon ECR (Elastic Container Registry) is a fully managed Docker container registry that makes it easy for developers to store, manage, and deploy Docker container images.",
              "reference": "https://docs.aws.amazon.com/ecr/",
              "points": 1,
              "answers": [{"text": "Amazon ECR",
                           "is_correct": True},
                          {"text": "Amazon ECS",
                           "is_correct": False},
                          {"text": "Amazon EKS",
                           "is_correct": False},
                          {"text": "AWS Fargate",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CodeWhisperer used for?",
              "explanation": "Amazon CodeWhisperer is an AI coding companion that generates whole line and full function code suggestions in your IDE to help you get more done faster.",
              "reference": "https://docs.aws.amazon.com/codewhisperer/",
              "points": 1,
              "answers": [{"text": "AI-powered code generation and suggestions",
                           "is_correct": True},
                          {"text": "Code compilation",
                           "is_correct": False},
                          {"text": "Code deployment",
                           "is_correct": False},
                          {"text": "Code testing",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed workflows?",
              "explanation": "AWS Step Functions is a visual workflow service that helps developers use AWS services to build distributed applications, automate processes, orchestrate microservices, and create data and machine learning pipelines.",
              "reference": "https://docs.aws.amazon.com/step-functions/",
              "points": 1,
              "answers": [{"text": "AWS Step Functions",
                           "is_correct": True},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon SQS",
                           "is_correct": False},
                          {"text": "AWS Batch",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of using Infrastructure as Code (IaC)?",
              "explanation": "Infrastructure as Code (IaC) provides consistency, repeatability, and version control for infrastructure deployments. It reduces manual errors, enables faster provisioning, and ensures environments are identical across deployments.",
              "reference": "https://docs.aws.amazon.com/whitepapers/latest/introduction-devops-aws/infrastructure-as-code.html",
              "points": 1,
              "answers": [{"text": "Consistent and repeatable infrastructure deployments",
                           "is_correct": True,
                           },
                          {"text": "Reduced infrastructure costs",
                           "is_correct": False},
                          {"text": "Improved application performance",
                           "is_correct": False},
                          {"text": "Enhanced security",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides batch processing capabilities?",
              "explanation": "AWS Batch enables you to run batch computing workloads on the AWS Cloud. It dynamically provisions the optimal quantity and type of compute resources based on the volume and specific resource requirements of the batch jobs submitted.",
              "reference": "https://docs.aws.amazon.com/batch/",
              "points": 1,
              "answers": [{"text": "AWS Batch",
                           "is_correct": True},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          {"text": "Amazon ECS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Organizations used for?",
              "explanation": "AWS Organizations is an account management service that enables you to centrally manage and govern your environment as you grow and scale your AWS resources. You can create accounts, group them into organizational units (OUs), and apply policies.",
              "reference": "https://docs.aws.amazon.com/organizations/",
              "points": 1,
              "answers": [{"text": "Centrally managing multiple AWS accounts",
                           "is_correct": True},
                          {"text": "Managing user identities",
                           "is_correct": False},
                          {"text": "Monitoring account usage",
                           "is_correct": False},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which deployment hook in CodeDeploy is executed before the application is stopped?",
              "explanation": "The BeforeStop hook is executed before the application is stopped during a CodeDeploy deployment. This is useful for tasks like graceful shutdown procedures or data backup.",
              "reference": "https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html",
              "points": 1,
              "answers": [{"text": "BeforeStop",
                           "is_correct": True},
                          {"text": "AfterStop",
                           "is_correct": False},
                          {"text": "BeforeInstall",
                           "is_correct": False},
                          {"text": "ApplicationStart",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CloudFormation Guard used for?",
              "explanation": "AWS CloudFormation Guard is an open-source general-purpose policy-as-code evaluation tool. It provides developers with a simple-to-use, yet powerful and expressive domain-specific language (DSL) to define policies and enables developers to validate JSON- or YAML-formatted structured data with those policies.",
              "reference": "https://docs.aws.amazon.com/cfn-guard/",
              "points": 1,
              "answers": [{"text": "Policy-as-code validation for CloudFormation templates",
                           "is_correct": True,
                           },
                          {"text": "Monitoring CloudFormation stacks",
                           "is_correct": False},
                          {"text": "Deploying CloudFormation templates",
                           "is_correct": False},
                          {"text": "Optimizing CloudFormation costs",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides network load balancing with ultra-low latency?",
              "explanation": "Network Load Balancer operates at the connection level (Layer 4), routing connections to targets within Amazon VPC based on IP protocol data. It can handle millions of requests per second while maintaining ultra-low latencies.",
              "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/network/",
              "points": 1,
              "answers": [{"text": "Network Load Balancer",
                           "is_correct": True},
                          {"text": "Application Load Balancer",
                           "is_correct": False},
                          {"text": "Classic Load Balancer",
                           "is_correct": False},
                          {"text": "Gateway Load Balancer",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Resource Groups?",
              "explanation": "AWS Resource Groups let you organize AWS resources that are in use in your account. You can group resources based on their tags, CloudFormation stacks, or other criteria, making it easier to manage and monitor related resources together.",
              "reference": "https://docs.aws.amazon.com/ARG/",
              "points": 1,
              "answers": [{"text": "Organizing and managing related AWS resources",
                           "is_correct": True,
                           },
                          {"text": "Monitoring resource performance",
                           "is_correct": False},
                          {"text": "Deploying resources",
                           "is_correct": False},
                          {"text": "Encrypting resources",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Airflow?",
              "explanation": "Amazon MWAA (Managed Workflows for Apache Airflow) is a managed orchestration service for Apache Airflow that makes it easier to set up and operate end-to-end data pipelines in the cloud at scale.",
              "reference": "https://docs.aws.amazon.com/mwaa/",
              "points": 1,
              "answers": [{"text": "Amazon MWAA",
                           "is_correct": True},
                          {"text": "AWS Step Functions",
                           "is_correct": False},
                          {"text": "AWS Batch",
                           "is_correct": False},
                          {"text": "AWS Glue",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS License Manager used for?",
              "explanation": "AWS License Manager makes it easier to manage licenses from software vendors like Microsoft, SAP, Oracle, and IBM across AWS and on-premises environments. It helps administrators control license usage and reduce over-provisioning.",
              "reference": "https://docs.aws.amazon.com/license-manager/",
              "points": 1,
              "answers": [{"text": "Managing software licenses across environments",
                           "is_correct": True,
                           },
                          {"text": "Managing AWS service licenses",
                           "is_correct": False},
                          {"text": "Monitoring license costs",
                           "is_correct": False},
                          {"text": "Deploying licensed software",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides change management and automation?",
              "explanation": "AWS Systems Manager Change Calendar lets you set up date and time ranges when actions you specify (for example, in Systems Manager Automation documents) may or may not be performed in your AWS account. Change Calendar integrates with other Systems Manager capabilities.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-change-calendar.html",
              "points": 1,
              "answers": [{"text": "AWS Systems Manager Change Calendar",
                           "is_correct": True},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS CloudTrail",
                           "is_correct": False},
                          {"text": "AWS Service Catalog",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Proton used for?",
              "explanation": "AWS Proton is the first fully managed application deployment service for container and serverless applications. Platform engineering teams can use Proton to connect and coordinate all the different tools needed for infrastructure provisioning, code deployments, monitoring, and updates.",
              "reference": "https://docs.aws.amazon.com/proton/",
              "points": 1,
              "answers": [{"text": "Managing application deployment infrastructure",
                           "is_correct": True,
                           },
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Building applications",
                           "is_correct": False},
                          {"text": "Testing applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides real-time application monitoring?",
              "explanation": "Amazon CloudWatch provides real-time monitoring of AWS resources and applications. It collects and tracks metrics, collects and monitors log files, and sets alarms. CloudWatch Application Insights provides automated setup of monitoring for applications.",
              "reference": "https://docs.aws.amazon.com/cloudwatch/",
              "points": 1,
              "answers": [{"text": "Amazon CloudWatch",
                           "is_correct": True},
                          {"text": "AWS X-Ray",
                           "is_correct": False},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS CloudTrail",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of AWS Well-Architected Framework?",
              "explanation": "The AWS Well-Architected Framework helps cloud architects build secure, high-performing, resilient, and efficient infrastructure for their applications and workloads. It's based on five pillars: operational excellence, security, reliability, performance efficiency, and cost optimization.",
              "reference": "https://docs.aws.amazon.com/wellarchitected/",
              "points": 1,
              "answers": [{"text": "Providing best practices for cloud architecture",
                           "is_correct": True,
                           },
                          {"text": "Monitoring architecture performance",
                           "is_correct": False},
                          {"text": "Deploying cloud resources",
                           "is_correct": False},
                          {"text": "Managing cloud costs",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Prometheus?",
              "explanation": "Amazon Managed Service for Prometheus is a serverless, Prometheus-compatible monitoring service for container metrics that makes it easier to securely monitor container environments at scale.",
              "reference": "https://docs.aws.amazon.com/prometheus/",
              "points": 1,
              "answers": [{"text": "Amazon Managed Service for Prometheus",
                           "is_correct": True},
                          {"text": "Amazon CloudWatch",
                           "is_correct": False},
                          {"text": "AWS X-Ray",
                           "is_correct": False},
                          {"text": "Amazon OpenSearch",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CodeCatalyst used for?",
              "explanation": "Amazon CodeCatalyst is a unified software development and delivery service. CodeCatalyst enables software development teams to quickly get started with developing, building, and deploying applications on AWS.",
              "reference": "https://docs.aws.amazon.com/codecatalyst/",
              "points": 1,
              "answers": [{"text": "Unified software development and delivery",
                           "is_correct": True},
                          {"text": "Code analysis and review",
                           "is_correct": False},
                          {"text": "Code storage and versioning",
                           "is_correct": False},
                          {"text": "Code compilation and testing",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Grafana?",
              "explanation": "Amazon Managed Grafana is a fully managed service for open source Grafana developed in collaboration with Grafana Labs. Grafana is a popular open source analytics platform that enables you to query, visualize, alert on and understand your metrics.",
              "reference": "https://docs.aws.amazon.com/grafana/",
              "points": 1,
              "answers": [{"text": "Amazon Managed Grafana",
                           "is_correct": True},
                          {"text": "Amazon CloudWatch",
                           "is_correct": False},
                          {"text": "Amazon QuickSight",
                           "is_correct": False},
                          {"text": "Amazon OpenSearch",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Application Composer used for?",
              "explanation": "AWS Application Composer is a visual builder that simplifies the process of building serverless applications by providing a drag-and-drop interface for AWS services and automatically generating Infrastructure as Code templates.",
              "reference": "https://docs.aws.amazon.com/application-composer/",
              "points": 1,
              "answers": [{"text": "Visual building of serverless applications",
                           "is_correct": True},
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Testing applications",
                           "is_correct": False},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Spark?",
              "explanation": "Amazon EMR (Elastic MapReduce) is a big data platform for processing vast amounts of data using open source tools such as Apache Spark, Apache Hive, Apache HBase, Apache Flink, Apache Hudi, and Presto.",
              "reference": "https://docs.aws.amazon.com/emr/",
              "points": 1,
              "answers": [{"text": "Amazon EMR",
                           "is_correct": True},
                          {"text": "AWS Glue",
                           "is_correct": False},
                          {"text": "Amazon Kinesis",
                           "is_correct": False},
                          {"text": "AWS Batch",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Resource Access Manager (RAM)?",
              "explanation": "AWS Resource Access Manager (RAM) is a service that enables you to easily and securely share AWS resources with any AWS account or within your AWS Organization. You can share AWS resources that you own with other AWS accounts.",
              "reference": "https://docs.aws.amazon.com/ram/",
              "points": 1,
              "answers": [{"text": "Sharing AWS resources across accounts",
                           "is_correct": True},
                          {"text": "Managing resource permissions",
                           "is_correct": False},
                          {"text": "Monitoring resource usage",
                           "is_correct": False},
                          {"text": "Optimizing resource costs",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides machine learning model management?",
              "explanation": "Amazon SageMaker is a fully managed service that provides every developer and data scientist with the ability to build, train, and deploy machine learning (ML) models quickly. SageMaker removes the heavy lifting from each step of the machine learning process.",
              "reference": "https://docs.aws.amazon.com/sagemaker/",
              "points": 1,
              "answers": [{"text": "Amazon SageMaker",
                           "is_correct": True},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          {"text": "AWS Batch",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Fault Injection Simulator used for?",
              "explanation": "AWS Fault Injection Simulator (FIS) is a fully managed service for running fault injection experiments on AWS that makes it easier to improve an application's performance, observability, and resiliency.",
              "reference": "https://docs.aws.amazon.com/fis/",
              "points": 1,
              "answers": [{"text": "Testing application resilience through controlled failures",
                           "is_correct": True,
                           },
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          {"text": "Building applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed ETL (Extract, Transform, Load)?",
              "explanation": "AWS Glue is a fully managed extract, transform, and load (ETL) service that makes it easy for customers to prepare and load their data for analytics. You can create and run an ETL job with a few clicks in the AWS Management Console.",
              "reference": "https://docs.aws.amazon.com/glue/",
              "points": 1,
              "answers": [{"text": "AWS Glue",
                           "is_correct": True},
                          {"text": "Amazon EMR",
                           "is_correct": False},
                          {"text": "AWS Data Pipeline",
                           "is_correct": False},
                          {"text": "Amazon Kinesis",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary benefit of using AWS Fargate?",
              "explanation": "AWS Fargate is a serverless compute engine for containers that works with both Amazon ECS and Amazon EKS. With Fargate, you no longer have to provision, configure, and scale clusters of virtual machines to run containers.",
              "reference": "https://docs.aws.amazon.com/fargate/",
              "points": 1,
              "answers": [{"text": "Serverless container execution without managing servers",
                           "is_correct": True,
                           },
                          {"text": "Improved container performance",
                           "is_correct": False},
                          {"text": "Reduced container costs",
                           "is_correct": False},
                          {"text": "Enhanced container security",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides search and analytics capabilities?",
              "explanation": "Amazon OpenSearch Service (successor to Amazon Elasticsearch Service) is a managed service that makes it easy for you to perform interactive log analytics, real-time application monitoring, website search, and more.",
              "reference": "https://docs.aws.amazon.com/opensearch-service/",
              "points": 1,
              "answers": [{"text": "Amazon OpenSearch Service",
                           "is_correct": True},
                          {"text": "Amazon CloudWatch",
                           "is_correct": False},
                          {"text": "Amazon S3",
                           "is_correct": False},
                          {"text": "Amazon Athena",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS PrivateLink used for?",
              "explanation": "AWS PrivateLink provides private connectivity between VPCs, AWS services, and on-premises applications, securely on the Amazon network. AWS PrivateLink makes it easy to connect services across different accounts and VPCs to significantly simplify the network architecture.",
              "reference": "https://docs.aws.amazon.com/privatelink/",
              "points": 1,
              "answers": [{"text": "Private connectivity between VPCs and AWS services",
                           "is_correct": True,
                           },
                          {"text": "Public internet connectivity",
                           "is_correct": False},
                          {"text": "VPN connections",
                           "is_correct": False},
                          {"text": "DNS resolution",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Cassandra?",
              "explanation": "Amazon Keyspaces (for Apache Cassandra) is a scalable, highly available, and managed Apache Cassandra-compatible database service. With Amazon Keyspaces, you can run your Cassandra workloads on AWS using the same Cassandra application code and developer tools that you use today.",
              "reference": "https://docs.aws.amazon.com/keyspaces/",
              "points": 1,
              "answers": [{"text": "Amazon Keyspaces",
                           "is_correct": True},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon DocumentDB",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS DataSync used for?",
              "explanation": "AWS DataSync is an online data transfer service that simplifies, automates, and accelerates copying large amounts of data between on-premises storage systems and AWS Storage services, as well as between AWS Storage services.",
              "reference": "https://docs.aws.amazon.com/datasync/",
              "points": 1,
              "answers": [{"text": "Automated data transfer between storage systems",
                           "is_correct": True,
                           },
                          {"text": "Real-time data streaming",
                           "is_correct": False},
                          {"text": "Data backup and archival",
                           "is_correct": False},
                          {"text": "Data analysis and processing",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides quantum computing capabilities?",
              "explanation": "Amazon Braket is a fully managed quantum computing service that helps researchers and developers get started with the technology to accelerate research and discovery. Braket provides a development environment for exploring and building quantum algorithms.",
              "reference": "https://docs.aws.amazon.com/braket/",
              "points": 1,
              "answers": [{"text": "Amazon Braket",
                           "is_correct": True},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          {"text": "AWS Batch",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Trusted Advisor?",
              "explanation": "AWS Trusted Advisor provides recommendations that help you follow AWS best practices. Trusted Advisor evaluates your account by using checks. These checks identify ways to optimize your AWS infrastructure, improve security and performance, reduce costs, and monitor service quotas.",
              "reference": "https://docs.aws.amazon.com/support/latest/user/trusted-advisor.html",
              "points": 1,
              "answers": [{"text": "Providing optimization recommendations for AWS resources",
                           "is_correct": True,
                           },
                          {"text": "Managing AWS support cases",
                           "is_correct": False},
                          {"text": "Monitoring AWS service health",
                           "is_correct": False},
                          {"text": "Billing and cost management",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed document database capabilities?",
              "explanation": "Amazon DocumentDB (with MongoDB compatibility) is a fast, scalable, highly available, and fully managed document database service that supports MongoDB workloads. You can use the same MongoDB application code, drivers, and tools with Amazon DocumentDB.",
              "reference": "https://docs.aws.amazon.com/documentdb/",
              "points": 1,
              "answers": [{"text": "Amazon DocumentDB",
                           "is_correct": True},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon Neptune",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Cost Explorer used for?",
              "explanation": "AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage. You can explore your usage and costs using the main graph, the Cost Explorer cost and usage reports, or the Cost Explorer RI reports.",
              "reference": "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html",
              "points": 1,
              "answers": [{"text": "Analyzing AWS costs and usage patterns",
                           "is_correct": True},
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Managing resource deployments",
                           "is_correct": False},
                          {"text": "Optimizing infrastructure",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed time series database?",
              "explanation": "Amazon Timestream is a fast, scalable, and serverless time series database service for IoT and operational applications that makes it easy to store and analyze trillions of events per day at 1/10th the cost of relational databases.",
              "reference": "https://docs.aws.amazon.com/timestream/",
              "points": 1,
              "answers": [{"text": "Amazon Timestream",
                           "is_correct": True},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon CloudWatch",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Transit Gateway used for?",
              "explanation": "AWS Transit Gateway is a service that enables customers to connect their Amazon Virtual Private Clouds (VPCs) and their on-premises networks to a single gateway. It acts as a cloud router that simplifies the network architecture.",
              "reference": "https://docs.aws.amazon.com/transit-gateway/",
              "points": 1,
              "answers": [{"text": "Connecting VPCs and on-premises networks",
                           "is_correct": True},
                          {"text": "Load balancing traffic",
                           "is_correct": False},
                          {"text": "Managing DNS routing",
                           "is_correct": False},
                          {"text": "Monitoring network performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed blockchain?",
              "explanation": "Amazon Managed Blockchain is a fully managed service that makes it easy to join public networks or create and manage scalable private networks using the popular open-source frameworks Hyperledger Fabric and Ethereum.",
              "reference": "https://docs.aws.amazon.com/managed-blockchain/",
              "points": 1,
              "answers": [{"text": "Amazon Managed Blockchain",
                           "is_correct": True},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          {"text": "Amazon ECS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Directory Service used for?",
              "explanation": "AWS Directory Service provides multiple ways to use Amazon Cloud Directory and Microsoft Active Directory (AD) with other AWS services. Directories store information about users, groups, and devices, and administrators use them to manage access to information and resources.",
              "reference": "https://docs.aws.amazon.com/directory-service/",
              "points": 1,
              "answers": [{"text": "Managing user directories and access",
                           "is_correct": True},
                          {"text": "Storing application data",
                           "is_correct": False},
                          {"text": "Managing file systems",
                           "is_correct": False},
                          {"text": "Monitoring user activity",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Flink?",
              "explanation": "Amazon Kinesis Data Analytics for Apache Flink is the easiest way to analyze streaming data, gain actionable insights, and respond to your business and customer needs in real time using Apache Flink.",
              "reference": "https://docs.aws.amazon.com/kinesisanalytics/latest/java/",
              "points": 1,
              "answers": [{"text": "Amazon Kinesis Data Analytics",
                           "is_correct": True},
                          {"text": "Amazon EMR",
                           "is_correct": False},
                          {"text": "AWS Glue",
                           "is_correct": False},
                          {"text": "Amazon Redshift",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Personal Health Dashboard used for?",
              "explanation": "AWS Personal Health Dashboard provides alerts and remediation guidance when AWS is experiencing events that might affect you. Personal Health Dashboard gives you a personalized view into the performance and availability of the AWS services underlying your AWS resources.",
              "reference": "https://docs.aws.amazon.com/health/",
              "points": 1,
              "answers": [{"text": "Monitoring AWS service health affecting your resources",
                           "is_correct": True,
                           },
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Managing user health data",
                           "is_correct": False},
                          {"text": "Tracking resource costs",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed graph database?",
              "explanation": "Amazon Neptune is a fast, reliable, fully managed graph database service that makes it easy to build and run applications that work with highly connected datasets. Neptune supports both Property Graph and RDF models.",
              "reference": "https://docs.aws.amazon.com/neptune/",
              "points": 1,
              "answers": [{"text": "Amazon Neptune",
                           "is_correct": True},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon DocumentDB",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Single Sign-On (SSO) used for?",
              "explanation": "AWS SSO is a cloud SSO service that makes it easy to centrally manage SSO access to multiple AWS accounts and business applications. You can use AWS SSO to manage SSO access and user permissions to all of your accounts in AWS Organizations centrally.",
              "reference": "https://docs.aws.amazon.com/singlesignon/",
              "points": 1,
              "answers": [{"text": "Centrally managing SSO access to AWS accounts and applications",
                           "is_correct": True,
                           },
                          {"text": "Managing user passwords",
                           "is_correct": False},
                          {"text": "Monitoring user activity",
                           "is_correct": False},
                          {"text": "Encrypting user data",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed in-memory data store?",
              "explanation": "Amazon MemoryDB for Redis is a Redis-compatible, durable, in-memory database service that delivers ultra-fast performance. It's purpose-built for modern applications with microservices architectures.",
              "reference": "https://docs.aws.amazon.com/memorydb/",
              "points": 1,
              "answers": [{"text": "Amazon MemoryDB for Redis",
                           "is_correct": True},
                          {"text": "Amazon ElastiCache",
                           "is_correct": False},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Global Accelerator used for?",
              "explanation": "AWS Global Accelerator is a service that improves the availability and performance of your applications with local or global users. It provides static IP addresses that act as a fixed entry point to your application endpoints in one or more AWS Regions.",
              "reference": "https://docs.aws.amazon.com/global-accelerator/",
              "points": 1,
              "answers": [{"text": "Improving application availability and performance globally",
                           "is_correct": True,
                           },
                          {"text": "Accelerating data processing",
                           "is_correct": False},
                          {"text": "Speeding up deployments",
                           "is_correct": False},
                          {"text": "Optimizing storage performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed ledger database?",
              "explanation": "Amazon QLDB (Quantum Ledger Database) is a fully managed ledger database that provides a transparent, immutable, and cryptographically verifiable transaction log owned by a central trusted authority.",
              "reference": "https://docs.aws.amazon.com/qldb/",
              "points": 1,
              "answers": [{"text": "Amazon QLDB",
                           "is_correct": True},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon DocumentDB",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Snowball used for?",
              "explanation": "AWS Snowball is a petabyte-scale data transport solution that uses secure appliances to transfer large amounts of data into and out of the AWS cloud. Using Snowball addresses common challenges with large-scale data transfers including high network costs, long transfer times, and security concerns.",
              "reference": "https://docs.aws.amazon.com/snowball/",
              "points": 1,
              "answers": [{"text": "Large-scale data transfer using physical appliances",
                           "is_correct": True,
                           },
                          {"text": "Real-time data streaming",
                           "is_correct": False},
                          {"text": "Data backup and archival",
                           "is_correct": False},
                          {"text": "Data processing and analytics",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides virtual desktop infrastructure?",
              "explanation": "Amazon WorkSpaces is a managed, secure Desktop-as-a-Service (DaaS) solution. You can use Amazon WorkSpaces to provision either Windows or Linux desktops in just a few minutes and quickly scale to provide thousands of desktops to workers across the globe.",
              "reference": "https://docs.aws.amazon.com/workspaces/",
              "points": 1,
              "answers": [{"text": "Amazon WorkSpaces",
                           "is_correct": True},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon ECS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS App Runner used for?",
              "explanation": "AWS App Runner is a fully managed service that makes it easy for developers to quickly deploy containerized web applications and APIs, at scale and with no prior infrastructure experience required. You provide your source code or container image, and App Runner builds and deploys the application automatically.",
              "reference": "https://docs.aws.amazon.com/apprunner/",
              "points": 1,
              "answers": [{"text": "Easily deploying containerized web applications",
                           "is_correct": True,
                           },
                          {"text": "Running batch processing jobs",
                           "is_correct": False},
                          {"text": "Managing databases",
                           "is_correct": False},
                          {"text": "Monitoring applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Kafka streaming?",
              "explanation": "Amazon Kinesis Data Streams is a massively scalable and durable real-time data streaming service. However, for Apache Kafka specifically, Amazon MSK (Managed Streaming for Apache Kafka) is the dedicated service.",
              "reference": "https://docs.aws.amazon.com/msk/",
              "points": 1,
              "answers": [{"text": "Amazon MSK (Managed Streaming for Apache Kafka)",
                           "is_correct": True,
                           },
                          {"text": "Amazon Kinesis Data Streams",
                           "is_correct": False},
                          {"text": "Amazon SQS",
                           "is_correct": False},
                          {"text": "Amazon SNS",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Amplify used for?",
              "explanation": "AWS Amplify is a set of tools and services that can be used together or on their own, to help front-end web and mobile developers build scalable full stack applications, powered by AWS. With Amplify, you can configure app backends and connect your app in minutes, deploy static web apps in a few clicks, and easily manage app content outside the AWS console.",
              "reference": "https://docs.aws.amazon.com/amplify/",
              "points": 1,
              "answers": [{"text": "Building and deploying full-stack web and mobile applications",
                           "is_correct": True,
                           },
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Managing databases",
                           "is_correct": False},
                          {"text": "Processing data streams",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides threat detection and security monitoring?",
              "explanation": "Amazon GuardDuty is a threat detection service that continuously monitors for malicious activity and unauthorized behavior to protect your AWS accounts, workloads, and data stored in Amazon S3.",
              "reference": "https://docs.aws.amazon.com/guardduty/",
              "points": 1,
              "answers": [{"text": "Amazon GuardDuty",
                           "is_correct": True},
                          {"text": "AWS Security Hub",
                           "is_correct": False},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS CloudTrail",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Macie used for?",
              "explanation": "Amazon Macie is a fully managed data security and data privacy service that uses machine learning and pattern matching to discover and protect your sensitive data in AWS.",
              "reference": "https://docs.aws.amazon.com/macie/",
              "points": 1,
              "answers": [{"text": "Discovering and protecting sensitive data",
                           "is_correct": True},
                          {"text": "Monitoring network traffic",
                           "is_correct": False},
                          {"text": "Managing user access",
                           "is_correct": False},
                          {"text": "Encrypting data",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Hive?",
              "explanation": "Amazon EMR (Elastic MapReduce) provides managed Apache Hive along with other big data frameworks. Hive is a data warehouse software that facilitates reading, writing, and managing large datasets residing in distributed storage.",
              "reference": "https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hive.html",
              "points": 1,
              "answers": [{"text": "Amazon EMR",
                           "is_correct": True},
                          {"text": "AWS Glue",
                           "is_correct": False},
                          {"text": "Amazon Redshift",
                           "is_correct": False},
                          {"text": "Amazon Athena",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Security Hub used for?",
              "explanation": "AWS Security Hub is a cloud security posture management service that performs security best practice checks, aggregates alerts, and enables automated remediation. It centrally manages security findings from multiple AWS security services and third-party tools.",
              "reference": "https://docs.aws.amazon.com/securityhub/",
              "points": 1,
              "answers": [{"text": "Centrally managing security findings and compliance",
                           "is_correct": True,
                           },
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Managing user identities",
                           "is_correct": False},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache HBase?",
              "explanation": "Amazon EMR provides managed Apache HBase. HBase is an open-source, non-relational, distributed database modeled after Google's Bigtable and written in Java. It runs on top of HDFS and provides BigTable-like capabilities.",
              "reference": "https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hbase.html",
              "points": 1,
              "answers": [{"text": "Amazon EMR",
                           "is_correct": True},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon Neptune",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS WAF used for?",
              "explanation": "AWS WAF is a web application firewall that helps protect your web applications or APIs against common web exploits and bots that may affect availability, compromise security, or consume excessive resources.",
              "reference": "https://docs.aws.amazon.com/waf/",
              "points": 1,
              "answers": [{"text": "Protecting web applications from common attacks",
                           "is_correct": True,
                           },
                          {"text": "Managing network firewalls",
                           "is_correct": False},
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Managing user access",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed relational database with Aurora engine?",
              "explanation": "Amazon Aurora is a MySQL and PostgreSQL-compatible relational database built for the cloud. It combines the performance and availability of traditional enterprise databases with the simplicity and cost-effectiveness of open source databases.",
              "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/",
              "points": 1,
              "answers": [{"text": "Amazon Aurora",
                           "is_correct": True},
                          {"text": "Amazon RDS",
                           "is_correct": False},
                          {"text": "Amazon DynamoDB",
                           "is_correct": False},
                          {"text": "Amazon Redshift",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Inspector used for?",
              "explanation": "Amazon Inspector is an automated security assessment service that helps improve the security and compliance of applications deployed on AWS. It automatically assesses applications for exposure, vulnerabilities, and deviations from best practices.",
              "reference": "https://docs.aws.amazon.com/inspector/",
              "points": 1,
              "answers": [{"text": "Automated security assessment of applications",
                           "is_correct": True,
                           },
                          {"text": "Monitoring application performance",
                           "is_correct": False},
                          {"text": "Managing user access",
                           "is_correct": False},
                          {"text": "Deploying applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Presto?",
              "explanation": "Amazon EMR provides managed Apache Presto (now called Trino). Presto is a distributed SQL query engine for running interactive analytic queries against data sources of all sizes ranging from gigabytes to petabytes.",
              "reference": "https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-presto.html",
              "points": 1,
              "answers": [{"text": "Amazon EMR",
                           "is_correct": True},
                          {"text": "Amazon Athena",
                           "is_correct": False},
                          {"text": "Amazon Redshift",
                           "is_correct": False},
                          {"text": "AWS Glue",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Shield used for?",
              "explanation": "AWS Shield is a managed Distributed Denial of Service (DDoS) protection service that safeguards applications running on AWS. AWS Shield provides always-on detection and automatic inline mitigations that minimize application downtime and latency.",
              "reference": "https://docs.aws.amazon.com/shield/",
              "points": 1,
              "answers": [{"text": "DDoS protection for applications",
                           "is_correct": True},
                          {"text": "Web application firewall",
                           "is_correct": False},
                          {"text": "Identity and access management",
                           "is_correct": False},
                          {"text": "Data encryption",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Zeppelin?",
              "explanation": "Amazon EMR provides managed Apache Zeppelin. Zeppelin is a web-based notebook that enables data-driven, interactive data analytics and collaborative documents with SQL, Scala and more.",
              "reference": "https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-zeppelin.html",
              "points": 1,
              "answers": [{"text": "Amazon EMR",
                           "is_correct": True},
                          {"text": "Amazon SageMaker",
                           "is_correct": False},
                          {"text": "AWS Glue",
                           "is_correct": False},
                          {"text": "Amazon Athena",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS Certificate Manager used for?",
              "explanation": "AWS Certificate Manager is a service that lets you easily provision, manage, and deploy public and private Secure Sockets Layer/Transport Layer Security (SSL/TLS) certificates for use with AWS services and your internal connected resources.",
              "reference": "https://docs.aws.amazon.com/acm/",
              "points": 1,
              "answers": [{"text": "Managing SSL/TLS certificates",
                           "is_correct": True},
                          {"text": "Managing user certificates",
                           "is_correct": False},
                          {"text": "Encrypting data",
                           "is_correct": False},
                          {"text": "Managing API keys",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides managed Apache Livy?",
              "explanation": "Amazon EMR provides managed Apache Livy. Livy is a service that enables easy interaction with a Spark cluster over a REST interface. It enables easy submission of Spark jobs or snippets of Spark code, synchronous or asynchronous result retrieval, as well as Spark Context management.",
              "reference": "https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-livy.html",
              "points": 1,
              "answers": [{"text": "Amazon EMR",
                           "is_correct": True},
                          {"text": "AWS Glue",
                           "is_correct": False},
                          {"text": "Amazon Kinesis",
                           "is_correct": False},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CloudHSM used for?",
              "explanation": "AWS CloudHSM provides hardware security modules in the AWS Cloud. A hardware security module (HSM) is a computing device that processes cryptographic operations and provides secure storage for cryptographic keys.",
              "reference": "https://docs.aws.amazon.com/cloudhsm/",
              "points": 1,
              "answers": [{"text": "Hardware-based cryptographic operations and key storage",
                           "is_correct": True,
                           },
                          {"text": "Software-based encryption",
                           "is_correct": False},
                          {"text": "Identity management",
                           "is_correct": False},
                          {"text": "Network security",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides infrastructure event management?",
              "explanation": "AWS Infrastructure Event Management (IEM) is a structured program available to Enterprise Support customers that helps you plan for large-scale events such as product or application launches, infrastructure migrations, and marketing events.",
              "reference": "https://docs.aws.amazon.com/support/latest/user/infrastructure-event-management.html",
              "points": 1,
              "answers": [{"text": "AWS Infrastructure Event Management",
                           "is_correct": True},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS CloudWatch Events",
                           "is_correct": False},
                          {"text": "AWS Systems Manager",
                           "is_correct": False},
                          ],
              },
             ]
