"""AWS Machine Learning Specialty Certification"""

CERTIFICATION = {
    "name": "AWS Certified Machine Learning - Specialty",
    "description": "Design, implement, deploy, and maintain machine learning solutions for given business problems",
    "slug": "aws-machine-learning-specialty",
    "level": "Specialty",
    "duration": 276,
    "questions_count": 92,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [{"text": "Which AWS service provides pre-built machine learning models via APIs?",
              "explanation": "Amazon Rekognition, Amazon Comprehend, Amazon Polly, Amazon Lex, and other AI services provide pre-built machine learning capabilities via simple APIs that don't require machine learning expertise.",
              "reference": "https://aws.amazon.com/machine-learning/ai-services/",
              "points": 1,
              "answers": [{"text": "Amazon AI Services (Rekognition, Comprehend, etc.)",
                           "is_correct": True,
                           },
                          {"text": "Amazon SageMaker",
                           "is_correct": False},
                          {"text": "AWS Lambda",
                           "is_correct": False},
                          {"text": "Amazon EC2",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Amazon SageMaker primarily used for?",
              "explanation": "Amazon SageMaker is a fully managed service that provides every developer and data scientist with the ability to build, train, and deploy machine learning (ML) models quickly.",
              "reference": "https://docs.aws.amazon.com/sagemaker/",
              "points": 1,
              "answers": [{"text": "Building, training, and deploying ML models",
                           "is_correct": True},
                          {"text": "Data storage only",
                           "is_correct": False},
                          {"text": "Web hosting",
                           "is_correct": False},
                          {"text": "Database management",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides automatic speech recognition?",
              "explanation": "Amazon Transcribe is an automatic speech recognition (ASR) service that makes it easy for developers to add speech-to-text capability to their applications.",
              "reference": "https://docs.aws.amazon.com/transcribe/",
              "points": 1,
              "answers": [{"text": "Amazon Transcribe",
                           "is_correct": True},
                          {"text": "Amazon Polly",
                           "is_correct": False},
                          {"text": "Amazon Lex",
                           "is_correct": False},
                          {"text": "Amazon Comprehend",
                           "is_correct": False},
                          ],
              },
             {"text": "What does Amazon Comprehend provide?",
              "explanation": "Amazon Comprehend is a natural language processing (NLP) service that uses machine learning to find insights and relationships in text.",
              "reference": "https://docs.aws.amazon.com/comprehend/",
              "points": 1,
              "answers": [{"text": "Natural language processing and text analytics",
                           "is_correct": True,
                           },
                          {"text": "Image recognition",
                           "is_correct": False},
                          {"text": "Speech synthesis",
                           "is_correct": False},
                          {"text": "Video analysis",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service is used for building conversational interfaces?",
              "explanation": "Amazon Lex is a service for building conversational interfaces into any application using voice and text. Amazon Lex provides the advanced deep learning functionalities of automatic speech recognition (ASR) for converting speech to text, and natural language understanding (NLU) to recognize the intent of the text.",
              "reference": "https://docs.aws.amazon.com/lex/",
              "points": 1,
              "answers": [{"text": "Amazon Lex",
                           "is_correct": True},
                          {"text": "Amazon Polly",
                           "is_correct": False},
                          {"text": "Amazon Transcribe",
                           "is_correct": False},
                          {"text": "Amazon Translate",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary purpose of Amazon SageMaker Studio?",
              "explanation": "Amazon SageMaker Studio is a web-based, integrated development environment (IDE) for machine learning that lets you build, train, debug, deploy, and monitor your machine learning models.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/studio.html",
              "points": 1,
              "answers": [{"text": "Integrated ML development environment",
                           "is_correct": True},
                          {"text": "Data storage service",
                           "is_correct": False},
                          {"text": "Model hosting only",
                           "is_correct": False},
                          {"text": "Data visualization tool",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker feature automatically scales ML models based on traffic?",
              "explanation": "Amazon SageMaker automatically scales your model endpoints up or down based on the traffic patterns of your application, ensuring optimal performance and cost efficiency.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/endpoint-auto-scaling.html",
              "points": 1,
              "answers": [{"text": "Auto Scaling",
                           "is_correct": True},
                          {"text": "Batch Transform",
                           "is_correct": False},
                          {"text": "Processing Jobs",
                           "is_correct": False},
                          {"text": "Ground Truth",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Amazon SageMaker Ground Truth used for?",
              "explanation": "Amazon SageMaker Ground Truth is a data labeling service that makes it easy to label training datasets for machine learning with high accuracy using human annotators.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/sms.html",
              "points": 1,
              "answers": [{"text": "Data labeling and annotation",
                           "is_correct": True},
                          {"text": "Model training",
                           "is_correct": False},
                          {"text": "Data storage",
                           "is_correct": False},
                          {"text": "Model deployment",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides real-time fraud detection capabilities?",
              "explanation": "Amazon Fraud Detector is a fully managed service that uses machine learning to identify potentially fraudulent activities in real-time.",
              "reference": "https://docs.aws.amazon.com/frauddetector/",
              "points": 1,
              "answers": [{"text": "Amazon Fraud Detector",
                           "is_correct": True},
                          {"text": "Amazon GuardDuty",
                           "is_correct": False},
                          {"text": "AWS WAF",
                           "is_correct": False},
                          {"text": "Amazon Inspector",
                           "is_correct": False},
                          ],
              },
             {"text": "What type of machine learning algorithm is Amazon Personalize based on?",
              "explanation": "Amazon Personalize uses collaborative filtering, content-based filtering, and deep learning algorithms to provide real-time personalized recommendations.",
              "reference": "https://docs.aws.amazon.com/personalize/",
              "points": 1,
              "answers": [{"text": "Recommendation algorithms (collaborative filtering)",
                           "is_correct": True,
                           },
                          {"text": "Computer vision algorithms",
                           "is_correct": False},
                          {"text": "Natural language processing",
                           "is_correct": False},
                          {"text": "Time series forecasting",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker feature helps with hyperparameter optimization?",
              "explanation": "Amazon SageMaker Automatic Model Tuning (also known as hyperparameter tuning) finds the best version of a model by running training jobs with different hyperparameter values.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning.html",
              "points": 1,
              "answers": [{"text": "Automatic Model Tuning",
                           "is_correct": True},
                          {"text": "SageMaker Debugger",
                           "is_correct": False},
                          {"text": "SageMaker Profiler",
                           "is_correct": False},
                          {"text": "SageMaker Clarify",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Amazon Forecast primarily used for?",
              "explanation": "Amazon Forecast is a fully managed service that uses machine learning to deliver highly accurate forecasts for time-series data.",
              "reference": "https://docs.aws.amazon.com/forecast/",
              "points": 1,
              "answers": [{"text": "Time series forecasting",
                           "is_correct": True},
                          {"text": "Image classification",
                           "is_correct": False},
                          {"text": "Text analysis",
                           "is_correct": False},
                          {"text": "Speech recognition",
                           "is_correct": False},
                          ],
              },
             {"text": "Which feature of Amazon Rekognition can identify inappropriate content?",
              "explanation": "Amazon Rekognition Content Moderation can automatically detect inappropriate, unwanted, or offensive content in images and videos.",
              "reference": "https://docs.aws.amazon.com/rekognition/latest/dg/moderation.html",
              "points": 1,
              "answers": [{"text": "Content Moderation",
                           "is_correct": True},
                          {"text": "Face Recognition",
                           "is_correct": False},
                          {"text": "Object Detection",
                           "is_correct": False},
                          {"text": "Text Detection",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the maximum size of a dataset that can be processed by SageMaker training jobs?",
              "explanation": "SageMaker training jobs can process datasets of virtually unlimited size by leveraging distributed training and multiple instances.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/train-model.html",
              "points": 1,
              "answers": [{"text": "No specific limit (scales based on instances)",
                           "is_correct": True,
                           },
                          {"text": "100 GB",
                           "is_correct": False},
                          {"text": "1 TB",
                           "is_correct": False},
                          {"text": "10 TB",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service can translate text in real-time?",
              "explanation": "Amazon Translate is a neural machine translation service that delivers fast, high-quality, and affordable language translation.",
              "reference": "https://docs.aws.amazon.com/translate/",
              "points": 1,
              "answers": [{"text": "Amazon Translate",
                           "is_correct": True},
                          {"text": "Amazon Comprehend",
                           "is_correct": False},
                          {"text": "Amazon Polly",
                           "is_correct": False},
                          {"text": "Amazon Transcribe",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of SageMaker Model Registry?",
              "explanation": "Amazon SageMaker Model Registry is a centralized model store to catalog, version, and manage the lifecycle of ML models in production.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry.html",
              "points": 1,
              "answers": [{"text": "Model versioning and lifecycle management",
                           "is_correct": True},
                          {"text": "Data preprocessing",
                           "is_correct": False},
                          {"text": "Model training",
                           "is_correct": False},
                          {"text": "Feature engineering",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker instance type is optimized for inference workloads?",
              "explanation": "Amazon SageMaker Inference instances are specifically optimized for hosting ML models and providing real-time predictions with low latency.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/inference.html",
              "points": 1,
              "answers": [{"text": "ml.inf1 instances",
                           "is_correct": True},
                          {"text": "ml.p3 instances",
                           "is_correct": False},
                          {"text": "ml.c5 instances",
                           "is_correct": False},
                          {"text": "ml.m5 instances",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Amazon Kendra's primary function?",
              "explanation": "Amazon Kendra is an intelligent search service powered by machine learning that helps users find information within their organization's content.",
              "reference": "https://docs.aws.amazon.com/kendra/",
              "points": 1,
              "answers": [{"text": "Intelligent enterprise search",
                           "is_correct": True},
                          {"text": "Database management",
                           "is_correct": False},
                          {"text": "File storage",
                           "is_correct": False},
                          {"text": "Web hosting",
                           "is_correct": False},
                          ],
              },
             {"text": "Which algorithm is commonly used for anomaly detection in AWS services?",
              "explanation": "AWS services like Amazon Lookout for Metrics use isolation forests, autoencoders, and other unsupervised learning algorithms for anomaly detection.",
              "reference": "https://docs.aws.amazon.com/lookoutmetrics/",
              "points": 1,
              "answers": [{"text": "Isolation Forest and Autoencoders",
                           "is_correct": True},
                          {"text": "Linear Regression",
                           "is_correct": False},
                          {"text": "Decision Trees",
                           "is_correct": False},
                          {"text": "K-Means Clustering",
                           "is_correct": False},
                          ],
              },
             {"text": "What is SageMaker Clarify used for?",
              "explanation": "Amazon SageMaker Clarify provides tools to help explain how machine learning models make predictions and detect potential bias in ML models and datasets.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-fairness-and-explainability.html",
              "points": 1,
              "answers": [{"text": "Model explainability and bias detection",
                           "is_correct": True},
                          {"text": "Data labeling",
                           "is_correct": False},
                          {"text": "Model training",
                           "is_correct": False},
                          {"text": "Data storage",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service is best for building custom computer vision models?",
              "explanation": "Amazon Rekognition Custom Labels allows you to build custom computer vision models to identify objects and scenes specific to your business needs.",
              "reference": "https://docs.aws.amazon.com/rekognition/latest/customlabels-dg/",
              "points": 1,
              "answers": [{"text": "Amazon Rekognition Custom Labels",
                           "is_correct": True},
                          {"text": "Amazon Textract",
                           "is_correct": False},
                          {"text": "Amazon Comprehend",
                           "is_correct": False},
                          {"text": "Amazon Polly",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of SageMaker Processing Jobs?",
              "explanation": "Amazon SageMaker Processing Jobs allow you to run data preprocessing and postprocessing workloads on the SageMaker platform.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/processing-job.html",
              "points": 1,
              "answers": [{"text": "Data preprocessing and postprocessing",
                           "is_correct": True},
                          {"text": "Model training only",
                           "is_correct": False},
                          {"text": "Model deployment only",
                           "is_correct": False},
                          {"text": "Data storage",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides sentiment analysis capabilities?",
              "explanation": "Amazon Comprehend provides sentiment analysis to determine whether text expresses positive, negative, neutral, or mixed sentiment.",
              "reference": "https://docs.aws.amazon.com/comprehend/latest/dg/how-sentiment.html",
              "points": 1,
              "answers": [{"text": "Amazon Comprehend",
                           "is_correct": True},
                          {"text": "Amazon Textract",
                           "is_correct": False},
                          {"text": "Amazon Translate",
                           "is_correct": False},
                          {"text": "Amazon Polly",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Amazon Textract primarily designed for?",
              "explanation": "Amazon Textract is a machine learning service that automatically extracts text, handwriting, and data from scanned documents.",
              "reference": "https://docs.aws.amazon.com/textract/",
              "points": 1,
              "answers": [{"text": "Document text and data extraction",
                           "is_correct": True},
                          {"text": "Image classification",
                           "is_correct": False},
                          {"text": "Speech synthesis",
                           "is_correct": False},
                          {"text": "Language translation",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker feature helps monitor model performance in production?",
              "explanation": "Amazon SageMaker Model Monitor automatically monitors machine learning models in production and alerts you when there are deviations in model quality.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor.html",
              "points": 1,
              "answers": [{"text": "SageMaker Model Monitor",
                           "is_correct": True},
                          {"text": "SageMaker Debugger",
                           "is_correct": False},
                          {"text": "SageMaker Profiler",
                           "is_correct": False},
                          {"text": "SageMaker Clarify",
                           "is_correct": False},
                          ],
              },
             {"text": "What type of machine learning is Amazon CodeGuru Reviewer based on?",
              "explanation": "Amazon CodeGuru Reviewer uses machine learning to automatically review code and provide intelligent recommendations to improve code quality.",
              "reference": "https://docs.aws.amazon.com/codeguru/",
              "points": 1,
              "answers": [{"text": "Code analysis and pattern recognition",
                           "is_correct": True},
                          {"text": "Natural language processing",
                           "is_correct": False},
                          {"text": "Computer vision",
                           "is_correct": False},
                          {"text": "Time series forecasting",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides medical text analysis?",
              "explanation": "Amazon Comprehend Medical is a HIPAA-eligible natural language processing service that uses machine learning to extract health data from medical text.",
              "reference": "https://docs.aws.amazon.com/comprehend/latest/dg/comprehend-medical.html",
              "points": 1,
              "answers": [{"text": "Amazon Comprehend Medical",
                           "is_correct": True},
                          {"text": "Amazon Textract",
                           "is_correct": False},
                          {"text": "Amazon Rekognition",
                           "is_correct": False},
                          {"text": "Amazon Translate",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of SageMaker Feature Store?",
              "explanation": "Amazon SageMaker Feature Store is a centralized repository for machine learning features that makes it easy to store, share, and manage features for ML models.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/feature-store.html",
              "points": 1,
              "answers": [{"text": "Centralized feature repository",
                           "is_correct": True},
                          {"text": "Model training",
                           "is_correct": False},
                          {"text": "Data visualization",
                           "is_correct": False},
                          {"text": "Model deployment",
                           "is_correct": False},
                          ],
              },
             {"text": "Which instance family is optimized for machine learning training workloads?",
              "explanation": "P3 instances with NVIDIA V100 GPUs are specifically designed for machine learning training workloads requiring high computational power.",
              "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/accelerated-computing-instances.html",
              "points": 1,
              "answers": [{"text": "P3 instances (GPU-optimized)",
                           "is_correct": True},
                          {"text": "T3 instances",
                           "is_correct": False},
                          {"text": "M5 instances",
                           "is_correct": False},
                          {"text": "C5 instances",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Amazon Polly's main functionality?",
              "explanation": "Amazon Polly is a text-to-speech service that uses advanced deep learning technologies to synthesize natural-sounding human speech.",
              "reference": "https://docs.aws.amazon.com/polly/",
              "points": 1,
              "answers": [{"text": "Text-to-speech synthesis",
                           "is_correct": True},
                          {"text": "Speech-to-text conversion",
                           "is_correct": False},
                          {"text": "Language translation",
                           "is_correct": False},
                          {"text": "Voice recognition",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker algorithm is best for recommendation systems?",
              "explanation": "Amazon SageMaker Factorization Machines algorithm is particularly well-suited for building recommendation systems and sparse data problems.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/fact-machines.html",
              "points": 1,
              "answers": [{"text": "Factorization Machines",
                           "is_correct": True},
                          {"text": "XGBoost",
                           "is_correct": False},
                          {"text": "Linear Learner",
                           "is_correct": False},
                          {"text": "K-Means",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Deep Learning AMIs?",
              "explanation": "AWS Deep Learning AMIs provide machine learning practitioners with the infrastructure and tools to accelerate deep learning in the cloud at any scale.",
              "reference": "https://docs.aws.amazon.com/dlami/",
              "points": 1,
              "answers": [{"text": "Pre-configured ML development environments",
                           "is_correct": True},
                          {"text": "Data storage solutions",
                           "is_correct": False},
                          {"text": "Web hosting platforms",
                           "is_correct": False},
                          {"text": "Database management systems",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service helps with document analysis and form processing?",
              "explanation": "Amazon Textract can analyze documents and forms, extracting text, tables, and form data automatically using machine learning.",
              "reference": "https://docs.aws.amazon.com/textract/latest/dg/analyzing-document-text.html",
              "points": 1,
              "answers": [{"text": "Amazon Textract",
                           "is_correct": True},
                          {"text": "Amazon Comprehend",
                           "is_correct": False},
                          {"text": "Amazon Rekognition",
                           "is_correct": False},
                          {"text": "Amazon Translate",
                           "is_correct": False},
                          ],
              },
             {"text": "What is SageMaker Pipelines used for?",
              "explanation": "Amazon SageMaker Pipelines is a purpose-built CI/CD service for machine learning that helps automate and manage ML workflows.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/pipelines.html",
              "points": 1,
              "answers": [{"text": "ML workflow automation and CI/CD",
                           "is_correct": True},
                          {"text": "Data storage",
                           "is_correct": False},
                          {"text": "Model hosting",
                           "is_correct": False},
                          {"text": "Data visualization",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides code recommendations based on ML?",
              "explanation": "Amazon CodeWhisperer uses machine learning to provide code recommendations and suggestions as you write code in your IDE.",
              "reference": "https://docs.aws.amazon.com/codewhisperer/",
              "points": 1,
              "answers": [{"text": "Amazon CodeWhisperer",
                           "is_correct": True},
                          {"text": "Amazon CodeGuru",
                           "is_correct": False},
                          {"text": "AWS CodeCommit",
                           "is_correct": False},
                          {"text": "AWS CodeDeploy",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary use case for Amazon Lookout for Vision?",
              "explanation": "Amazon Lookout for Vision is a machine learning service that spots defects and anomalies in visual representations using computer vision.",
              "reference": "https://docs.aws.amazon.com/lookout-for-vision/",
              "points": 1,
              "answers": [{"text": "Industrial defect detection",
                           "is_correct": True},
                          {"text": "Facial recognition",
                           "is_correct": False},
                          {"text": "Object classification",
                           "is_correct": False},
                          {"text": "Text recognition",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker feature provides distributed training capabilities?",
              "explanation": "SageMaker supports distributed training across multiple instances to speed up the training process for large datasets and complex models.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/distributed-training.html",
              "points": 1,
              "answers": [{"text": "Multi-instance training jobs",
                           "is_correct": True},
                          {"text": "SageMaker Debugger",
                           "is_correct": False},
                          {"text": "SageMaker Profiler",
                           "is_correct": False},
                          {"text": "SageMaker Clarify",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Amazon Lookout for Metrics designed to detect?",
              "explanation": "Amazon Lookout for Metrics uses machine learning to automatically detect and diagnose anomalies in business and operational metrics.",
              "reference": "https://docs.aws.amazon.com/lookoutmetrics/",
              "points": 1,
              "answers": [{"text": "Anomalies in business metrics",
                           "is_correct": True},
                          {"text": "Security threats",
                           "is_correct": False},
                          {"text": "Code quality issues",
                           "is_correct": False},
                          {"text": "Infrastructure problems",
                           "is_correct": False},
                          ],
              },
             {"text": "Which data format is commonly used for training data in SageMaker?",
              "explanation": "SageMaker algorithms commonly use CSV format for structured data, though many algorithms also support other formats like LibSVM, Parquet, and JSON.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/cdf-training.html",
              "points": 1,
              "answers": [{"text": "CSV and Parquet",
                           "is_correct": True},
                          {"text": "XML only",
                           "is_correct": False},
                          {"text": "PDF only",
                           "is_correct": False},
                          {"text": "Word documents",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of SageMaker Experiments?",
              "explanation": "Amazon SageMaker Experiments helps you organize, track, compare, and evaluate machine learning experiments and model iterations.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/experiments.html",
              "points": 1,
              "answers": [{"text": "Track and compare ML experiments",
                           "is_correct": True},
                          {"text": "Deploy models to production",
                           "is_correct": False},
                          {"text": "Store training data",
                           "is_correct": False},
                          {"text": "Monitor model performance",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides conversational AI for contact centers?",
              "explanation": "Amazon Connect with Lex integration provides conversational AI capabilities for contact centers, enabling voice and chat bots.",
              "reference": "https://docs.aws.amazon.com/connect/latest/adminguide/amazon-lex.html",
              "points": 1,
              "answers": [{"text": "Amazon Connect with Lex",
                           "is_correct": True},
                          {"text": "Amazon Chime",
                           "is_correct": False},
                          {"text": "Amazon WorkSpaces",
                           "is_correct": False},
                          {"text": "Amazon Pinpoint",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the main advantage of using SageMaker Spot Instances for training?",
              "explanation": "SageMaker Spot Instances can reduce the cost of training machine learning models by up to 90% compared to On-Demand instances.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-managed-spot-training.html",
              "points": 1,
              "answers": [{"text": "Significant cost reduction (up to 90%)",
                           "is_correct": True},
                          {"text": "Faster training speed",
                           "is_correct": False},
                          {"text": "Better model accuracy",
                           "is_correct": False},
                          {"text": "More storage capacity",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides real-time translation of streaming text?",
              "explanation": "Amazon Translate can process text in real-time, making it suitable for applications that need instant translation of streaming content.",
              "reference": "https://docs.aws.amazon.com/translate/latest/dg/real-time-translation.html",
              "points": 1,
              "answers": [{"text": "Amazon Translate",
                           "is_correct": True},
                          {"text": "Amazon Comprehend",
                           "is_correct": False},
                          {"text": "Amazon Transcribe",
                           "is_correct": False},
                          {"text": "Amazon Polly",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the primary function of AWS Panorama?",
              "explanation": "AWS Panorama is a machine learning appliance and software development kit that allows you to add computer vision to your existing cameras.",
              "reference": "https://docs.aws.amazon.com/panorama/",
              "points": 1,
              "answers": [{"text": "Edge computer vision deployment",
                           "is_correct": True},
                          {"text": "Cloud-based image processing",
                           "is_correct": False},
                          {"text": "Video streaming",
                           "is_correct": False},
                          {"text": "Camera management",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker algorithm is best for clustering tasks?",
              "explanation": "Amazon SageMaker K-Means algorithm is specifically designed for clustering tasks, grouping data points into k clusters.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/k-means.html",
              "points": 1,
              "answers": [{"text": "K-Means",
                           "is_correct": True},
                          {"text": "Linear Learner",
                           "is_correct": False},
                          {"text": "XGBoost",
                           "is_correct": False},
                          {"text": "Factorization Machines",
                           "is_correct": False},
                          ],
              },
             {"text": "What is Amazon HealthLake designed for?",
              "explanation": "Amazon HealthLake is a HIPAA-eligible service that enables healthcare organizations to store, transform, and analyze health data using machine learning.",
              "reference": "https://docs.aws.amazon.com/healthlake/",
              "points": 1,
              "answers": [{"text": "Healthcare data analytics with ML",
                           "is_correct": True},
                          {"text": "General data storage",
                           "is_correct": False},
                          {"text": "Image processing",
                           "is_correct": False},
                          {"text": "Financial analysis",
                           "is_correct": False},
                          ],
              },
             {"text": "Which feature helps debug SageMaker training jobs?",
              "explanation": "Amazon SageMaker Debugger automatically captures training metrics and provides insights to help debug and optimize machine learning models.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/train-debugger.html",
              "points": 1,
              "answers": [{"text": "SageMaker Debugger",
                           "is_correct": True},
                          {"text": "SageMaker Profiler",
                           "is_correct": False},
                          {"text": "SageMaker Clarify",
                           "is_correct": False},
                          {"text": "SageMaker Monitor",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of Amazon Augmented AI (A2I)?",
              "explanation": "Amazon Augmented AI (A2I) makes it easy to build workflows for human review of machine learning predictions when models need human oversight.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/a2i-use-augmented-ai.html",
              "points": 1,
              "answers": [{"text": "Human review workflows for ML predictions",
                           "is_correct": True},
                          {"text": "Automated model training",
                           "is_correct": False},
                          {"text": "Data preprocessing",
                           "is_correct": False},
                          {"text": "Model deployment",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides intelligent document processing?",
              "explanation": "Amazon Textract provides intelligent document processing capabilities, extracting text, tables, and form data from virtually any document.",
              "reference": "https://docs.aws.amazon.com/textract/latest/dg/what-is.html",
              "points": 1,
              "answers": [{"text": "Amazon Textract",
                           "is_correct": True},
                          {"text": "Amazon Comprehend",
                           "is_correct": False},
                          {"text": "Amazon Rekognition",
                           "is_correct": False},
                          {"text": "Amazon Translate",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the main benefit of using SageMaker Multi-Model Endpoints?",
              "explanation": "SageMaker Multi-Model Endpoints allow you to host multiple models on a single endpoint, reducing hosting costs and improving resource utilization.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/multi-model-endpoints.html",
              "points": 1,
              "answers": [{"text": "Cost-efficient hosting of multiple models",
                           "is_correct": True},
                          {"text": "Faster training speed",
                           "is_correct": False},
                          {"text": "Better model accuracy",
                           "is_correct": False},
                          {"text": "Larger model size support",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides machine learning-powered business intelligence?",
              "explanation": "Amazon QuickSight uses machine learning to provide business intelligence insights, including anomaly detection and forecasting.",
              "reference": "https://docs.aws.amazon.com/quicksight/latest/user/quicksight-machine-learning.html",
              "points": 1,
              "answers": [{"text": "Amazon QuickSight",
                           "is_correct": True},
                          {"text": "Amazon Redshift",
                           "is_correct": False},
                          {"text": "Amazon Athena",
                           "is_correct": False},
                          {"text": "Amazon EMR",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for handling imbalanced datasets in SageMaker?",
              "explanation": "For imbalanced datasets, you can use techniques like SMOTE, class weighting, or focal loss. SageMaker also supports custom sampling strategies during training.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/train-model.html",
              "points": 1,
              "answers": [{"text": "Use SMOTE, class weighting, or focal loss",
                           "is_correct": True},
                          {"text": "Only use more data",
                           "is_correct": False},
                          {"text": "Always use random sampling",
                           "is_correct": False},
                          {"text": "Remove minority class examples",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker algorithm is best suited for time series forecasting?",
              "explanation": "Amazon SageMaker DeepAR algorithm is specifically designed for forecasting scalar time series using recurrent neural networks.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html",
              "points": 1,
              "answers": [{"text": "DeepAR",
                           "is_correct": True},
                          {"text": "XGBoost",
                           "is_correct": False},
                          {"text": "K-Means",
                           "is_correct": False},
                          {"text": "Linear Learner",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of SageMaker Batch Transform?",
              "explanation": "SageMaker Batch Transform allows you to get predictions for entire datasets without needing to set up a persistent endpoint.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/batch-transform.html",
              "points": 1,
              "answers": [{"text": "Batch inference on large datasets",
                           "is_correct": True},
                          {"text": "Real-time inference only",
                           "is_correct": False},
                          {"text": "Model training",
                           "is_correct": False},
                          {"text": "Data preprocessing",
                           "is_correct": False},
                          ],
              },
             {"text": "Which activation function is commonly used in the output layer for binary classification?",
              "explanation": "The sigmoid activation function is commonly used in the output layer for binary classification as it outputs values between 0 and 1.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/neural-networks.html",
              "points": 1,
              "answers": [{"text": "Sigmoid",
                           "is_correct": True},
                          {"text": "ReLU",
                           "is_correct": False},
                          {"text": "Tanh",
                           "is_correct": False},
                          {"text": "Softmax",
                           "is_correct": False},
                          ],
              },
             {"text": "What is cross-validation primarily used for in machine learning?",
              "explanation": "Cross-validation is used to assess how well a model will generalize to unseen data and to tune hyperparameters.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-validation.html",
              "points": 1,
              "answers": [{"text": "Model validation and hyperparameter tuning",
                           "is_correct": True},
                          {"text": "Data cleaning",
                           "is_correct": False},
                          {"text": "Feature selection only",
                           "is_correct": False},
                          {"text": "Data visualization",
                           "is_correct": False},
                          ],
              },
             {"text": "Which metric is most appropriate for evaluating a highly imbalanced classification problem?",
              "explanation": "For imbalanced datasets, F1-score, precision, recall, and AUC-ROC are more meaningful than accuracy, as accuracy can be misleading.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-model-quality-metrics.html",
              "points": 1,
              "answers": [{"text": "F1-score or AUC-ROC",
                           "is_correct": True},
                          {"text": "Accuracy only",
                           "is_correct": False},
                          {"text": "Mean Squared Error",
                           "is_correct": False},
                          {"text": "R-squared",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between L1 and L2 regularization?",
              "explanation": "L1 regularization (Lasso) adds the sum of absolute values of parameters, promoting sparsity. L2 regularization (Ridge) adds the sum of squared parameters, preventing large weights.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/linear-learner.html",
              "points": 1,
              "answers": [{"text": "L1 promotes sparsity, L2 prevents large weights",
                           "is_correct": True,
                           },
                          {"text": "L1 is for classification, L2 for regression",
                           "is_correct": False,
                           },
                          {"text": "L1 is faster, L2 is more accurate",
                           "is_correct": False},
                          {"text": "No significant difference",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique helps prevent overfitting in neural networks?",
              "explanation": "Dropout randomly sets some neurons to zero during training, which helps prevent overfitting by reducing co-adaptation between neurons.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/neural-networks.html",
              "points": 1,
              "answers": [{"text": "Dropout",
                           "is_correct": True},
                          {"text": "Increasing learning rate",
                           "is_correct": False},
                          {"text": "Adding more layers",
                           "is_correct": False},
                          {"text": "Using smaller datasets",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of feature scaling in machine learning?",
              "explanation": "Feature scaling ensures that all features contribute equally to the distance calculations in algorithms like SVM, k-NN, and neural networks.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/data-prep.html",
              "points": 1,
              "answers": [{"text": "Normalize feature ranges for equal contribution",
                           "is_correct": True,
                           },
                          {"text": "Reduce the number of features",
                           "is_correct": False},
                          {"text": "Increase model accuracy always",
                           "is_correct": False},
                          {"text": "Speed up data loading",
                           "is_correct": False},
                          ],
              },
             {"text": "Which SageMaker algorithm is best for Principal Component Analysis (PCA)?",
              "explanation": "Amazon SageMaker provides a built-in PCA algorithm for dimensionality reduction and feature extraction.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/pca.html",
              "points": 1,
              "answers": [{"text": "PCA Algorithm",
                           "is_correct": True},
                          {"text": "K-Means",
                           "is_correct": False},
                          {"text": "XGBoost",
                           "is_correct": False},
                          {"text": "Linear Learner",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the curse of dimensionality?",
              "explanation": "The curse of dimensionality refers to various phenomena that arise when analyzing data in high-dimensional spaces, where the volume of space increases exponentially with dimensions.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/feature-selection.html",
              "points": 1,
              "answers": [{"text": "Problems arising from high-dimensional data",
                           "is_correct": True},
                          {"text": "Having too few features",
                           "is_correct": False},
                          {"text": "Computational complexity only",
                           "is_correct": False},
                          {"text": "Memory limitations",
                           "is_correct": False},
                          ],
              },
             {"text": "Which ensemble method combines multiple weak learners sequentially?",
              "explanation": "Boosting algorithms like AdaBoost and Gradient Boosting combine weak learners sequentially, where each learner corrects the errors of the previous ones.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost.html",
              "points": 1,
              "answers": [{"text": "Boosting",
                           "is_correct": True},
                          {"text": "Bagging",
                           "is_correct": False},
                          {"text": "Stacking",
                           "is_correct": False},
                          {"text": "Voting",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the main advantage of Random Forest over Decision Trees?",
              "explanation": "Random Forest reduces overfitting by averaging multiple decision trees trained on different subsets of data and features.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/randomcutforest.html",
              "points": 1,
              "answers": [{"text": "Reduces overfitting through ensemble averaging",
                           "is_correct": True,
                           },
                          {"text": "Faster training time",
                           "is_correct": False},
                          {"text": "Better interpretability",
                           "is_correct": False},
                          {"text": "Uses less memory",
                           "is_correct": False},
                          ],
              },
             {"text": "Which distance metric is commonly used in K-Means clustering?",
              "explanation": "K-Means clustering typically uses Euclidean distance to measure similarity between data points and cluster centroids.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/k-means.html",
              "points": 1,
              "answers": [{"text": "Euclidean distance",
                           "is_correct": True},
                          {"text": "Manhattan distance",
                           "is_correct": False},
                          {"text": "Cosine similarity",
                           "is_correct": False},
                          {"text": "Hamming distance",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of the learning rate in gradient descent?",
              "explanation": "The learning rate controls the size of steps taken during gradient descent optimization. Too high can cause overshooting, too low can cause slow convergence.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/training-parameters.html",
              "points": 1,
              "answers": [{"text": "Controls step size in optimization",
                           "is_correct": True},
                          {"text": "Determines number of epochs",
                           "is_correct": False},
                          {"text": "Sets batch size",
                           "is_correct": False},
                          {"text": "Defines model architecture",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique is used to handle missing values in datasets?",
              "explanation": "Common techniques for handling missing values include imputation (mean, median, mode), deletion, or using algorithms that handle missing values naturally.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/data-prep.html",
              "points": 1,
              "answers": [{"text": "Imputation, deletion, or specialized algorithms",
                           "is_correct": True,
                           },
                          {"text": "Always delete rows with missing values",
                           "is_correct": False},
                          {"text": "Replace with zeros only",
                           "is_correct": False},
                          {"text": "Ignore missing values",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of a confusion matrix?",
              "explanation": "A confusion matrix provides a detailed breakdown of correct and incorrect classifications for each class, helping evaluate model performance.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-model-quality-metrics.html",
              "points": 1,
              "answers": [{"text": "Detailed classification performance breakdown",
                           "is_correct": True,
                           },
                          {"text": "Feature importance ranking",
                           "is_correct": False},
                          {"text": "Training progress visualization",
                           "is_correct": False},
                          {"text": "Data distribution analysis",
                           "is_correct": False},
                          ],
              },
             {"text": "Which activation function is most commonly used in hidden layers of deep networks?",
              "explanation": "ReLU (Rectified Linear Unit) is widely used in hidden layers because it helps mitigate the vanishing gradient problem and is computationally efficient.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/neural-networks.html",
              "points": 1,
              "answers": [{"text": "ReLU",
                           "is_correct": True},
                          {"text": "Sigmoid",
                           "is_correct": False},
                          {"text": "Tanh",
                           "is_correct": False},
                          {"text": "Linear",
                           "is_correct": False},
                          ],
              },
             {"text": "What is transfer learning in deep learning?",
              "explanation": "Transfer learning involves using a pre-trained model on a new, related task, leveraging learned features to improve performance with less data and training time.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/transfer-learning.html",
              "points": 1,
              "answers": [{"text": "Using pre-trained models for new tasks",
                           "is_correct": True},
                          {"text": "Moving data between systems",
                           "is_correct": False},
                          {"text": "Converting model formats",
                           "is_correct": False},
                          {"text": "Sharing models between teams",
                           "is_correct": False},
                          ],
              },
             {"text": "Which optimization algorithm adapts learning rates for each parameter?",
              "explanation": "Adam optimizer adapts learning rates for each parameter individually, combining advantages of AdaGrad and RMSprop optimizers.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/training-parameters.html",
              "points": 1,
              "answers": [{"text": "Adam",
                           "is_correct": True},
                          {"text": "SGD",
                           "is_correct": False},
                          {"text": "Momentum",
                           "is_correct": False},
                          {"text": "Gradient Descent",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of batch normalization?",
              "explanation": "Batch normalization normalizes inputs to each layer, reducing internal covariate shift and allowing for higher learning rates and faster training.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/neural-networks.html",
              "points": 1,
              "answers": [{"text": "Normalizes layer inputs for stable training",
                           "is_correct": True},
                          {"text": "Reduces batch size",
                           "is_correct": False},
                          {"text": "Increases model capacity",
                           "is_correct": False},
                          {"text": "Saves memory",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique helps address the vanishing gradient problem?",
              "explanation": "Techniques like ReLU activations, skip connections (ResNet), and proper weight initialization help address vanishing gradients in deep networks.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/neural-networks.html",
              "points": 1,
              "answers": [{"text": "ReLU activations and skip connections",
                           "is_correct": True},
                          {"text": "Increasing learning rate",
                           "is_correct": False},
                          {"text": "Adding more layers",
                           "is_correct": False},
                          {"text": "Using larger datasets",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of early stopping in training?",
              "explanation": "Early stopping prevents overfitting by stopping training when validation performance stops improving, even if training loss continues to decrease.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning-early-stopping.html",
              "points": 1,
              "answers": [{"text": "Prevent overfitting by stopping at optimal point",
                           "is_correct": True,
                           },
                          {"text": "Speed up training only",
                           "is_correct": False},
                          {"text": "Reduce computational costs only",
                           "is_correct": False},
                          {"text": "Improve model interpretability",
                           "is_correct": False},
                          ],
              },
             {"text": "Which data augmentation technique is commonly used for image data?",
              "explanation": "Image data augmentation includes techniques like rotation, flipping, cropping, and color adjustments to increase dataset diversity.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/image-classification.html",
              "points": 1,
              "answers": [{"text": "Rotation, flipping, and cropping",
                           "is_correct": True},
                          {"text": "Adding noise to labels",
                           "is_correct": False},
                          {"text": "Removing random pixels",
                           "is_correct": False},
                          {"text": "Changing file formats",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of attention mechanisms in neural networks?",
              "explanation": "Attention mechanisms allow models to focus on relevant parts of input sequences, improving performance in tasks like machine translation and text summarization.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/seq2seq.html",
              "points": 1,
              "answers": [{"text": "Focus on relevant parts of input sequences",
                           "is_correct": True},
                          {"text": "Reduce model size",
                           "is_correct": False},
                          {"text": "Speed up training",
                           "is_correct": False},
                          {"text": "Simplify architecture",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique is used to reduce model complexity and prevent overfitting?",
              "explanation": "Regularization techniques like L1/L2 regularization, dropout, and early stopping help reduce model complexity and prevent overfitting.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/regularization.html",
              "points": 1,
              "answers": [{"text": "Regularization (L1/L2, dropout)",
                           "is_correct": True},
                          {"text": "Adding more features",
                           "is_correct": False},
                          {"text": "Increasing training data only",
                           "is_correct": False},
                          {"text": "Using more complex models",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between precision and recall?",
              "explanation": "Precision measures the proportion of positive predictions that are correct, while recall measures the proportion of actual positives that are correctly identified.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-model-quality-metrics.html",
              "points": 1,
              "answers": [{"text": "Precision: correct positives/predicted positives; Recall: correct positives/actual positives",
                           "is_correct": True,
                           },
                          {"text": "Precision and recall are the same metric",
                           "is_correct": False},
                          {"text": "Precision is for regression, recall for classification",
                           "is_correct": False,
                           },
                          {"text": "Precision measures speed, recall measures accuracy",
                           "is_correct": False,
                           },
                          ],
              },
             {"text": "Which technique is used for dimensionality reduction while preserving non-linear relationships?",
              "explanation": "t-SNE (t-Distributed Stochastic Neighbor Embedding) and autoencoders can preserve non-linear relationships during dimensionality reduction.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/pca.html",
              "points": 1,
              "answers": [{"text": "t-SNE or autoencoders",
                           "is_correct": True},
                          {"text": "PCA only",
                           "is_correct": False},
                          {"text": "Linear regression",
                           "is_correct": False},
                          {"text": "K-means clustering",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of feature engineering in machine learning?",
              "explanation": "Feature engineering involves creating, transforming, and selecting features to improve model performance and interpretability.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/feature-engineering.html",
              "points": 1,
              "answers": [{"text": "Create and transform features to improve model performance",
                           "is_correct": True,
                           },
                          {"text": "Only remove unnecessary features",
                           "is_correct": False},
                          {"text": "Visualize data distributions",
                           "is_correct": False},
                          {"text": "Speed up data loading",
                           "is_correct": False},
                          ],
              },
             {"text": "Which metric is appropriate for evaluating regression models?",
              "explanation": "Common regression metrics include Mean Squared Error (MSE), Root Mean Squared Error (RMSE), Mean Absolute Error (MAE), and R-squared.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-model-quality-metrics.html",
              "points": 1,
              "answers": [{"text": "MSE, RMSE, MAE, or R-squared",
                           "is_correct": True},
                          {"text": "Accuracy and F1-score",
                           "is_correct": False},
                          {"text": "Precision and recall",
                           "is_correct": False},
                          {"text": "AUC-ROC",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of word embeddings in NLP?",
              "explanation": "Word embeddings convert words into dense vector representations that capture semantic relationships and can be used as input to machine learning models.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/blazingtext.html",
              "points": 1,
              "answers": [{"text": "Convert words to dense vector representations",
                           "is_correct": True,
                           },
                          {"text": "Count word frequencies",
                           "is_correct": False},
                          {"text": "Remove stop words",
                           "is_correct": False},
                          {"text": "Translate between languages",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique is used to handle categorical variables in machine learning?",
              "explanation": "Common techniques include one-hot encoding, label encoding, target encoding, and embedding layers for high-cardinality categorical variables.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/data-prep.html",
              "points": 1,
              "answers": [{"text": "One-hot encoding, label encoding, or embeddings",
                           "is_correct": True,
                           },
                          {"text": "Only remove categorical variables",
                           "is_correct": False},
                          {"text": "Always use numerical conversion",
                           "is_correct": False},
                          {"text": "Ignore categorical variables",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of hyperparameter tuning?",
              "explanation": "Hyperparameter tuning involves finding the optimal values for model hyperparameters to maximize performance on validation data.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning.html",
              "points": 1,
              "answers": [{"text": "Find optimal hyperparameter values for best performance",
                           "is_correct": True,
                           },
                          {"text": "Adjust training data only",
                           "is_correct": False},
                          {"text": "Change model architecture",
                           "is_correct": False},
                          {"text": "Speed up training time",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique is used to evaluate model performance on unseen data?",
              "explanation": "Train/validation/test split or cross-validation techniques are used to evaluate how well a model generalizes to unseen data.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-validation.html",
              "points": 1,
              "answers": [{"text": "Train/validation/test split or cross-validation",
                           "is_correct": True,
                           },
                          {"text": "Training on full dataset",
                           "is_correct": False},
                          {"text": "Using training accuracy only",
                           "is_correct": False},
                          {"text": "Random predictions",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between supervised and unsupervised learning?",
              "explanation": "Supervised learning uses labeled data to train models for prediction, while unsupervised learning finds patterns in unlabeled data.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/algos.html",
              "points": 1,
              "answers": [{"text": "Supervised uses labeled data, unsupervised finds patterns in unlabeled data",
                           "is_correct": True,
                           },
                          {"text": "Supervised is faster than unsupervised",
                           "is_correct": False},
                          {"text": "Supervised is only for classification, unsupervised for regression",
                           "is_correct": False,
                           },
                          {"text": "No significant difference",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique is used to handle temporal dependencies in sequential data?",
              "explanation": "Recurrent Neural Networks (RNNs), LSTMs, and GRUs are designed to handle temporal dependencies in sequential data like time series or text.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/seq2seq.html",
              "points": 1,
              "answers": [{"text": "RNNs, LSTMs, or GRUs",
                           "is_correct": True},
                          {"text": "Convolutional Neural Networks",
                           "is_correct": False},
                          {"text": "Decision Trees",
                           "is_correct": False},
                          {"text": "K-Means clustering",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of data normalization in machine learning?",
              "explanation": "Data normalization scales features to similar ranges, preventing features with larger scales from dominating the learning process.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/data-prep.html",
              "points": 1,
              "answers": [{"text": "Scale features to similar ranges for equal importance",
                           "is_correct": True,
                           },
                          {"text": "Remove outliers from data",
                           "is_correct": False},
                          {"text": "Increase data size",
                           "is_correct": False},
                          {"text": "Improve data quality",
                           "is_correct": False},
                          ],
              },
             {"text": "Which algorithm is commonly used for collaborative filtering in recommendation systems?",
              "explanation": "Matrix factorization techniques, including Singular Value Decomposition (SVD) and Non-negative Matrix Factorization (NMF), are commonly used for collaborative filtering.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/fact-machines.html",
              "points": 1,
              "answers": [{"text": "Matrix factorization (SVD, NMF)",
                           "is_correct": True},
                          {"text": "K-Means clustering",
                           "is_correct": False},
                          {"text": "Decision Trees",
                           "is_correct": False},
                          {"text": "Linear Regression",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of gradient clipping in neural network training?",
              "explanation": "Gradient clipping prevents the exploding gradient problem by limiting the magnitude of gradients during backpropagation.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/training-parameters.html",
              "points": 1,
              "answers": [{"text": "Prevent exploding gradients by limiting magnitude",
                           "is_correct": True,
                           },
                          {"text": "Speed up training",
                           "is_correct": False},
                          {"text": "Reduce memory usage",
                           "is_correct": False},
                          {"text": "Improve model accuracy",
                           "is_correct": False},
                          ],
              },
             {"text": "Which technique is used to reduce the computational cost of neural networks?",
              "explanation": "Techniques like pruning, quantization, knowledge distillation, and using smaller architectures help reduce computational cost.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/model-compression.html",
              "points": 1,
              "answers": [{"text": "Pruning, quantization, or knowledge distillation",
                           "is_correct": True,
                           },
                          {"text": "Adding more layers",
                           "is_correct": False},
                          {"text": "Increasing batch size only",
                           "is_correct": False},
                          {"text": "Using higher learning rates",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of ensemble methods in machine learning?",
              "explanation": "Ensemble methods combine multiple models to achieve better performance than individual models by reducing bias, variance, or both.",
              "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/ensemble-methods.html",
              "points": 1,
              "answers": [{"text": "Combine multiple models for better performance",
                           "is_correct": True,
                           },
                          {"text": "Speed up training time",
                           "is_correct": False},
                          {"text": "Reduce data requirements",
                           "is_correct": False},
                          {"text": "Simplify model interpretation",
                           "is_correct": False},
                          ],
              },
             ]
