"""AWS Security Specialty Certification"""

CERTIFICATION = {
    "name": "AWS Certified Security - Specialty",
    "description": "Specialized knowledge in AWS security",
    "slug": "aws-security-specialty",
    "level": "Specialty",
    "duration": 198,
    "questions_count": 66,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which AWS service provides centralized logging for security analysis?",
        "explanation": "AWS CloudTrail provides event history of AWS API calls, which is essential for security analysis and compliance.",
        "reference": "https://docs.aws.amazon.com/cloudtrail/",
        "points": 1,
        "answers": [
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": True},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS Systems Manager", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary purpose of AWS Identity and Access Management (IAM)?",
        "explanation": "AWS IAM enables you to manage access to AWS services and resources securely by controlling authentication and authorization.",
        "reference": "https://docs.aws.amazon.com/iam/",
        "points": 1,
        "answers": [
            {
                "text": "Control access to AWS services and resources",
                "is_correct": True,
            },
            {"text": "Monitor network traffic", "is_correct": False},
            {"text": "Encrypt data at rest", "is_correct": False},
            {"text": "Manage DNS records", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides threat intelligence and malware detection?",
        "explanation": "Amazon GuardDuty is a threat detection service that uses machine learning to identify malicious activity and unauthorized behavior.",
        "reference": "https://docs.aws.amazon.com/guardduty/",
        "points": 1,
        "answers": [
            {"text": "Amazon GuardDuty", "is_correct": True},
            {"text": "AWS Shield", "is_correct": False},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "Amazon Inspector", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Key Management Service (KMS)?",
        "explanation": "AWS KMS is a managed service that makes it easy to create and control cryptographic keys used to encrypt data.",
        "reference": "https://docs.aws.amazon.com/kms/",
        "points": 1,
        "answers": [
            {"text": "Manage cryptographic keys for encryption", "is_correct": True},
            {"text": "Store passwords securely", "is_correct": False},
            {"text": "Monitor API calls", "is_correct": False},
            {"text": "Manage user identities", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides DDoS protection for AWS resources?",
        "explanation": "AWS Shield provides managed DDoS protection for applications running on AWS, with Standard and Advanced tiers available.",
        "reference": "https://docs.aws.amazon.com/shield/",
        "points": 1,
        "answers": [
            {"text": "AWS Shield", "is_correct": True},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Secrets Manager used for?",
        "explanation": "AWS Secrets Manager helps you protect secrets needed to access your applications, services, and IT resources by enabling rotation, management, and retrieval of database credentials, API keys, and other secrets.",
        "reference": "https://docs.aws.amazon.com/secretsmanager/",
        "points": 1,
        "answers": [
            {
                "text": "Store and manage secrets like API keys and passwords",
                "is_correct": True,
            },
            {"text": "Encrypt files", "is_correct": False},
            {"text": "Monitor network traffic", "is_correct": False},
            {"text": "Manage user permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides web application firewall capabilities?",
        "explanation": "AWS WAF is a web application firewall that helps protect web applications from common web exploits and bots.",
        "reference": "https://docs.aws.amazon.com/waf/",
        "points": 1,
        "answers": [
            {"text": "AWS WAF", "is_correct": True},
            {"text": "AWS Shield", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Security Groups", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Certificate Manager (ACM)?",
        "explanation": "AWS Certificate Manager is a service that lets you provision, manage, and deploy SSL/TLS certificates for use with AWS services.",
        "reference": "https://docs.aws.amazon.com/acm/",
        "points": 1,
        "answers": [
            {"text": "Provision and manage SSL/TLS certificates", "is_correct": True},
            {"text": "Store encryption keys", "is_correct": False},
            {"text": "Monitor certificate usage", "is_correct": False},
            {"text": "Validate user identities", "is_correct": False},
        ],
    },
    {
        "text": "Which service helps assess security vulnerabilities in EC2 instances?",
        "explanation": "Amazon Inspector is an automated security assessment service that helps improve the security and compliance of applications deployed on AWS.",
        "reference": "https://docs.aws.amazon.com/inspector/",
        "points": 1,
        "answers": [
            {"text": "Amazon Inspector", "is_correct": True},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CloudHSM used for?",
        "explanation": "AWS CloudHSM provides hardware security modules in the AWS Cloud, offering secure cryptographic key storage and operations.",
        "reference": "https://docs.aws.amazon.com/cloudhsm/",
        "points": 1,
        "answers": [
            {"text": "Hardware-based cryptographic key storage", "is_correct": True},
            {"text": "Software encryption", "is_correct": False},
            {"text": "Network monitoring", "is_correct": False},
            {"text": "Identity management", "is_correct": False},
        ],
    },
    {
        "text": "Which IAM policy type provides the most restrictive permissions?",
        "explanation": "When multiple policies apply, AWS uses a deny-by-default approach, and explicit deny statements in any applicable policy will override any allow statements.",
        "reference": "https://docs.aws.amazon.com/iam/latest/userguide/reference_policies_evaluation-logic.html",
        "points": 1,
        "answers": [
            {"text": "Policies with explicit deny statements", "is_correct": True},
            {"text": "Inline policies", "is_correct": False},
            {"text": "Managed policies", "is_correct": False},
            {"text": "Resource-based policies", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Organizations primarily used for in security contexts?",
        "explanation": "AWS Organizations helps centrally manage multiple AWS accounts and apply security policies across all accounts in an organization.",
        "reference": "https://docs.aws.amazon.com/organizations/",
        "points": 1,
        "answers": [
            {
                "text": "Centrally manage multiple AWS accounts and policies",
                "is_correct": True,
            },
            {"text": "Monitor API calls", "is_correct": False},
            {"text": "Encrypt data", "is_correct": False},
            {"text": "Manage DNS records", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides continuous monitoring of AWS resource configurations?",
        "explanation": "AWS Config provides a detailed view of resource configurations and tracks changes over time for compliance monitoring.",
        "reference": "https://docs.aws.amazon.com/config/",
        "points": 1,
        "answers": [
            {"text": "AWS Config", "is_correct": True},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS Systems Manager", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of VPC Flow Logs?",
        "explanation": "VPC Flow Logs capture information about the IP traffic going to and from network interfaces in your VPC, useful for security analysis and troubleshooting.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html",
        "points": 1,
        "answers": [
            {
                "text": "Capture IP traffic information for network interfaces",
                "is_correct": True,
            },
            {"text": "Monitor application performance", "is_correct": False},
            {"text": "Store database logs", "is_correct": False},
            {"text": "Track user activities", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides security orchestration and incident response?",
        "explanation": "AWS Security Hub provides a central place to view security alerts and findings from multiple AWS security services and third-party tools.",
        "reference": "https://docs.aws.amazon.com/securityhub/",
        "points": 1,
        "answers": [
            {"text": "AWS Security Hub", "is_correct": True},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
        ],
    },
    {
        "text": "What is the principle of least privilege in IAM?",
        "explanation": "The principle of least privilege means granting only the minimum permissions necessary for users to perform their required tasks.",
        "reference": "https://docs.aws.amazon.com/iam/latest/userguide/best-practices.html",
        "points": 1,
        "answers": [
            {
                "text": "Grant minimum permissions necessary for required tasks",
                "is_correct": True,
            },
            {
                "text": "Grant all permissions to simplify management",
                "is_correct": False,
            },
            {"text": "Grant permissions based on user seniority", "is_correct": False},
            {"text": "Grant permissions randomly", "is_correct": False},
        ],
    },
    {
        "text": "Which encryption method is used for data in transit in AWS?",
        "explanation": "TLS (Transport Layer Security) is the primary encryption method used for data in transit in AWS services.",
        "reference": "https://docs.aws.amazon.com/general/latest/gr/aws-sec-crypt-overview.html",
        "points": 1,
        "answers": [
            {"text": "TLS (Transport Layer Security)", "is_correct": True},
            {"text": "AES-256", "is_correct": False},
            {"text": "RSA", "is_correct": False},
            {"text": "MD5", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Trusted Advisor's role in security?",
        "explanation": "AWS Trusted Advisor provides real-time guidance to help provision resources following AWS best practices, including security recommendations.",
        "reference": "https://docs.aws.amazon.com/support/latest/user/trusted-advisor.html",
        "points": 1,
        "answers": [
            {
                "text": "Provides security best practice recommendations",
                "is_correct": True,
            },
            {"text": "Monitors network traffic", "is_correct": False},
            {"text": "Encrypts data automatically", "is_correct": False},
            {"text": "Manages user identities", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides centralized compliance reporting?",
        "explanation": "AWS Artifact provides on-demand access to AWS compliance documentation and agreements, serving as a central repository for compliance reports.",
        "reference": "https://docs.aws.amazon.com/artifact/",
        "points": 1,
        "answers": [
            {"text": "AWS Artifact", "is_correct": True},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "AWS Security Hub", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Security Groups in AWS?",
        "explanation": "Security Groups act as virtual firewalls that control inbound and outbound traffic for EC2 instances at the instance level.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html",
        "points": 1,
        "answers": [
            {
                "text": "Virtual firewall controlling instance-level traffic",
                "is_correct": True,
            },
            {"text": "User group management", "is_correct": False},
            {"text": "Resource organization", "is_correct": False},
            {"text": "Backup management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides data loss prevention capabilities?",
        "explanation": "Amazon Macie uses machine learning to automatically discover, classify, and protect sensitive data in AWS.",
        "reference": "https://docs.aws.amazon.com/macie/",
        "points": 1,
        "answers": [
            {"text": "Amazon Macie", "is_correct": True},
            {"text": "AWS KMS", "is_correct": False},
            {"text": "AWS Secrets Manager", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between Security Groups and NACLs?",
        "explanation": "Security Groups operate at the instance level and are stateful, while NACLs operate at the subnet level and are stateless.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Security.html",
        "points": 1,
        "answers": [
            {
                "text": "Security Groups are instance-level and stateful, NACLs are subnet-level and stateless",
                "is_correct": True,
            },
            {
                "text": "Security Groups are for users, NACLs are for resources",
                "is_correct": False,
            },
            {"text": "Security Groups are free, NACLs cost money", "is_correct": False},
            {"text": "No significant difference", "is_correct": False},
        ],
    },
    {
        "text": "Which service helps with privileged access management?",
        "explanation": "AWS IAM Identity Center (formerly AWS SSO) provides centralized access management for multiple AWS accounts and applications.",
        "reference": "https://docs.aws.amazon.com/singlesignon/",
        "points": 1,
        "answers": [
            {"text": "AWS IAM Identity Center", "is_correct": True},
            {"text": "AWS Secrets Manager", "is_correct": False},
            {"text": "AWS KMS", "is_correct": False},
            {"text": "Amazon Cognito", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS PrivateLink used for?",
        "explanation": "AWS PrivateLink provides private connectivity between VPCs, AWS services, and on-premises applications, without exposing traffic to the public internet.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/privatelink/",
        "points": 1,
        "answers": [
            {
                "text": "Private connectivity without internet exposure",
                "is_correct": True,
            },
            {"text": "Public DNS resolution", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides automated remediation for security issues?",
        "explanation": "AWS Systems Manager can automate remediation actions based on findings from AWS Config, Security Hub, or other security services.",
        "reference": "https://docs.aws.amazon.com/systems-manager/",
        "points": 1,
        "answers": [
            {"text": "AWS Systems Manager", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS Step Functions", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Resource Access Manager (RAM)?",
        "explanation": "AWS RAM enables you to securely share your resources across AWS accounts within your organization or organizational units.",
        "reference": "https://docs.aws.amazon.com/ram/",
        "points": 1,
        "answers": [
            {
                "text": "Securely share resources across AWS accounts",
                "is_correct": True,
            },
            {"text": "Manage user access to resources", "is_correct": False},
            {"text": "Monitor resource usage", "is_correct": False},
            {"text": "Backup resources", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides network segmentation at the subnet level?",
        "explanation": "Network Access Control Lists (NACLs) provide an additional layer of security at the subnet level, controlling traffic in and out of subnets.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html",
        "points": 1,
        "answers": [
            {"text": "Network Access Control Lists (NACLs)", "is_correct": True},
            {"text": "Security Groups", "is_correct": False},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "Route Tables", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Detective used for?",
        "explanation": "AWS Detective makes it easy to analyze, investigate, and quickly identify the root cause of security findings or suspicious activities.",
        "reference": "https://docs.aws.amazon.com/detective/",
        "points": 1,
        "answers": [
            {"text": "Investigate and analyze security findings", "is_correct": True},
            {"text": "Detect vulnerabilities", "is_correct": False},
            {"text": "Monitor network traffic", "is_correct": False},
            {"text": "Encrypt data", "is_correct": False},
        ],
    },
    {
        "text": "Which IAM feature allows temporary access to AWS resources?",
        "explanation": "IAM roles provide temporary access credentials to AWS resources and can be assumed by users, applications, or services.",
        "reference": "https://docs.aws.amazon.com/iam/latest/userguide/id_roles.html",
        "points": 1,
        "answers": [
            {"text": "IAM Roles", "is_correct": True},
            {"text": "IAM Users", "is_correct": False},
            {"text": "IAM Groups", "is_correct": False},
            {"text": "IAM Policies", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Control Tower?",
        "explanation": "AWS Control Tower provides a pre-configured, secure, multi-account AWS environment based on best practices established by working with thousands of enterprises.",
        "reference": "https://docs.aws.amazon.com/controltower/",
        "points": 1,
        "answers": [
            {
                "text": "Set up and govern secure multi-account AWS environment",
                "is_correct": True,
            },
            {"text": "Monitor API calls", "is_correct": False},
            {"text": "Manage encryption keys", "is_correct": False},
            {"text": "Provide threat detection", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides endpoint security for EC2 instances?",
        "explanation": "Amazon Inspector provides automated security assessments to help improve the security and compliance of applications deployed on AWS EC2 instances.",
        "reference": "https://docs.aws.amazon.com/inspector/",
        "points": 1,
        "answers": [
            {"text": "Amazon Inspector", "is_correct": True},
            {"text": "AWS Systems Manager", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Network Firewall used for?",
        "explanation": "AWS Network Firewall is a stateful, managed network firewall and intrusion detection and prevention service for VPCs.",
        "reference": "https://docs.aws.amazon.com/network-firewall/",
        "points": 1,
        "answers": [
            {
                "text": "Stateful network firewall and intrusion prevention",
                "is_correct": True,
            },
            {"text": "Web application firewall", "is_correct": False},
            {"text": "Database firewall", "is_correct": False},
            {"text": "API gateway security", "is_correct": False},
        ],
    },
    {
        "text": "Which service helps with data classification and discovery?",
        "explanation": "Amazon Macie uses machine learning and pattern matching to discover and classify sensitive data in AWS S3 buckets.",
        "reference": "https://docs.aws.amazon.com/macie/",
        "points": 1,
        "answers": [
            {"text": "Amazon Macie", "is_correct": True},
            {"text": "AWS Glue", "is_correct": False},
            {"text": "Amazon Athena", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS CloudFormation in security contexts?",
        "explanation": "AWS CloudFormation enables Infrastructure as Code, allowing consistent and repeatable deployment of secure infrastructure configurations.",
        "reference": "https://docs.aws.amazon.com/cloudformation/",
        "points": 1,
        "answers": [
            {
                "text": "Infrastructure as Code for consistent security configurations",
                "is_correct": True,
            },
            {"text": "Monitor security events", "is_correct": False},
            {"text": "Encrypt data automatically", "is_correct": False},
            {"text": "Manage user identities", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides DNS security?",
        "explanation": "Amazon Route 53 Resolver DNS Firewall helps protect against DNS exfiltration and provides visibility into DNS queries.",
        "reference": "https://docs.aws.amazon.com/route53/latest/developerguide/resolver-dns-firewall.html",
        "points": 1,
        "answers": [
            {"text": "Route 53 Resolver DNS Firewall", "is_correct": True},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Shield", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Well-Architected Framework's Security Pillar focused on?",
        "explanation": "The Security Pillar focuses on protecting information, systems, and assets while delivering business value through risk assessments and mitigation strategies.",
        "reference": "https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/",
        "points": 1,
        "answers": [
            {
                "text": "Protecting information and systems through risk mitigation",
                "is_correct": True,
            },
            {"text": "Optimizing costs", "is_correct": False},
            {"text": "Improving performance", "is_correct": False},
            {"text": "Ensuring reliability", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides container security scanning?",
        "explanation": "Amazon ECR provides image vulnerability scanning to identify software vulnerabilities in container images.",
        "reference": "https://docs.aws.amazon.com/ecr/latest/userguide/image-scanning.html",
        "points": 1,
        "answers": [
            {"text": "Amazon ECR", "is_correct": True},
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "Amazon EKS", "is_correct": False},
            {"text": "AWS Fargate", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Security Token Service (STS)?",
        "explanation": "AWS STS enables you to request temporary, limited-privilege credentials for IAM users or federated users.",
        "reference": "https://docs.aws.amazon.com/STS/",
        "points": 1,
        "answers": [
            {"text": "Provide temporary security credentials", "is_correct": True},
            {"text": "Manage permanent user accounts", "is_correct": False},
            {"text": "Store encryption keys", "is_correct": False},
            {"text": "Monitor API calls", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides application-layer DDoS protection?",
        "explanation": "AWS WAF provides protection against application-layer DDoS attacks and web exploits, while AWS Shield provides network-layer protection.",
        "reference": "https://docs.aws.amazon.com/waf/",
        "points": 1,
        "answers": [
            {"text": "AWS WAF", "is_correct": True},
            {"text": "AWS Shield Standard", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS IAM Access Analyzer used for?",
        "explanation": "IAM Access Analyzer helps identify resources in your organization that are shared with external entities and validates IAM policies.",
        "reference": "https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html",
        "points": 1,
        "answers": [
            {
                "text": "Identify resources shared externally and validate policies",
                "is_correct": True,
            },
            {"text": "Monitor user login activities", "is_correct": False},
            {"text": "Encrypt sensitive data", "is_correct": False},
            {"text": "Scan for vulnerabilities", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides serverless security scanning?",
        "explanation": "Amazon Inspector now provides automated security assessments for both EC2 instances and container images, including serverless containers.",
        "reference": "https://docs.aws.amazon.com/inspector/",
        "points": 1,
        "answers": [
            {"text": "Amazon Inspector", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS X-Ray", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Personal Health Dashboard?",
        "explanation": "AWS Personal Health Dashboard provides alerts and remediation guidance when AWS experiences events that might affect your resources.",
        "reference": "https://docs.aws.amazon.com/health/",
        "points": 1,
        "answers": [
            {
                "text": "Provide personalized alerts about AWS service events",
                "is_correct": True,
            },
            {"text": "Monitor application performance", "is_correct": False},
            {"text": "Manage user health records", "is_correct": False},
            {"text": "Track security incidents", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides secure file transfer?",
        "explanation": "AWS Transfer Family provides fully managed support for file transfers over SFTP, FTPS, and FTP directly into and out of Amazon S3 or Amazon EFS.",
        "reference": "https://docs.aws.amazon.com/transfer/",
        "points": 1,
        "answers": [
            {"text": "AWS Transfer Family", "is_correct": True},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "AWS DataSync", "is_correct": False},
            {"text": "AWS Storage Gateway", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Config Rules used for?",
        "explanation": "AWS Config Rules allow you to automatically evaluate whether your AWS resources comply with desired configurations and security standards.",
        "reference": "https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config.html",
        "points": 1,
        "answers": [
            {
                "text": "Evaluate resource compliance with security standards",
                "is_correct": True,
            },
            {"text": "Configure network settings", "is_correct": False},
            {"text": "Set up user permissions", "is_correct": False},
            {"text": "Monitor application logs", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides API security and throttling?",
        "explanation": "Amazon API Gateway provides features like API throttling, request/response transformation, and authentication/authorization for securing APIs.",
        "reference": "https://docs.aws.amazon.com/apigateway/",
        "points": 1,
        "answers": [
            {"text": "Amazon API Gateway", "is_correct": True},
            {"text": "AWS WAF", "is_correct": False},
            {"text": "Amazon CloudFront", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Backup Vault Lock used for?",
        "explanation": "AWS Backup Vault Lock helps you implement additional protection for your backup vaults by preventing changes to and deletion of backups in your vault.",
        "reference": "https://docs.aws.amazon.com/aws-backup/latest/devguide/vault-lock.html",
        "points": 1,
        "answers": [
            {"text": "Prevent changes and deletion of backups", "is_correct": True},
            {"text": "Encrypt backup data", "is_correct": False},
            {"text": "Schedule backup jobs", "is_correct": False},
            {"text": "Monitor backup status", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides identity federation?",
        "explanation": "AWS IAM Identity Center and AWS Cognito provide identity federation capabilities, allowing users to access AWS resources using existing identity providers.",
        "reference": "https://docs.aws.amazon.com/iam/latest/userguide/id_roles_providers.html",
        "points": 1,
        "answers": [
            {"text": "AWS IAM Identity Center and Amazon Cognito", "is_correct": True},
            {"text": "AWS Directory Service only", "is_correct": False},
            {"text": "AWS Secrets Manager", "is_correct": False},
            {"text": "AWS KMS", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Directory Service?",
        "explanation": "AWS Directory Service provides multiple ways to use Microsoft Active Directory with other AWS services, enabling secure authentication and authorization.",
        "reference": "https://docs.aws.amazon.com/directoryservice/",
        "points": 1,
        "answers": [
            {
                "text": "Integrate Microsoft Active Directory with AWS services",
                "is_correct": True,
            },
            {"text": "Store file directories", "is_correct": False},
            {"text": "Manage DNS records", "is_correct": False},
            {"text": "Organize AWS resources", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides automated security assessments for serverless applications?",
        "explanation": "Amazon Inspector can assess serverless applications by scanning container images used in AWS Lambda functions and Amazon ECR repositories.",
        "reference": "https://docs.aws.amazon.com/inspector/",
        "points": 1,
        "answers": [
            {"text": "Amazon Inspector", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "AWS CodeGuru", "is_correct": False},
            {"text": "AWS X-Ray", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Resource Groups used for in security contexts?",
        "explanation": "AWS Resource Groups help organize resources for security management, allowing you to apply security policies and monitor resources collectively.",
        "reference": "https://docs.aws.amazon.com/ARG/",
        "points": 1,
        "answers": [
            {
                "text": "Organize resources for collective security management",
                "is_correct": True,
            },
            {"text": "Create user groups", "is_correct": False},
            {"text": "Manage network groups", "is_correct": False},
            {"text": "Group API calls", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides distributed denial of service response team support?",
        "explanation": "AWS Shield Advanced provides access to the AWS DDoS Response Team (DRT) for attack mitigation and post-attack analysis.",
        "reference": "https://docs.aws.amazon.com/shield/latest/DeveloperGuide/ddos-response-team.html",
        "points": 1,
        "answers": [
            {"text": "AWS Shield Advanced", "is_correct": True},
            {"text": "AWS Shield Standard", "is_correct": False},
            {"text": "AWS Support", "is_correct": False},
            {"text": "Amazon GuardDuty", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Systems Manager Session Manager used for?",
        "explanation": "Session Manager provides secure and auditable instance management without needing to open inbound ports, maintain bastion hosts, or manage SSH keys.",
        "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html",
        "points": 1,
        "answers": [
            {
                "text": "Secure instance access without SSH keys or bastion hosts",
                "is_correct": True,
            },
            {"text": "Manage user sessions", "is_correct": False},
            {"text": "Store session data", "is_correct": False},
            {"text": "Monitor session activities", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides centralized security finding management?",
        "explanation": "AWS Security Hub aggregates security findings from multiple AWS security services and third-party tools into a centralized dashboard.",
        "reference": "https://docs.aws.amazon.com/securityhub/",
        "points": 1,
        "answers": [
            {"text": "AWS Security Hub", "is_correct": True},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
            {"text": "Amazon Inspector", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Parameter Store in security?",
        "explanation": "AWS Systems Manager Parameter Store provides secure, hierarchical storage for configuration data management and secrets management with encryption support.",
        "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html",
        "points": 1,
        "answers": [
            {
                "text": "Secure storage for configuration data and secrets",
                "is_correct": True,
            },
            {"text": "Store application parameters only", "is_correct": False},
            {"text": "Monitor system parameters", "is_correct": False},
            {"text": "Configure network parameters", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides network traffic analysis?",
        "explanation": "Amazon VPC Traffic Mirroring copies network traffic from EC2 instances and sends it to security and monitoring appliances for analysis.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/mirroring/",
        "points": 1,
        "answers": [
            {"text": "VPC Traffic Mirroring", "is_correct": True},
            {"text": "VPC Flow Logs", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Firewall Manager used for?",
        "explanation": "AWS Firewall Manager is a security management service that allows you to centrally configure and manage firewall rules across multiple AWS accounts and applications.",
        "reference": "https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html",
        "points": 1,
        "answers": [
            {
                "text": "Centrally manage firewall rules across multiple accounts",
                "is_correct": True,
            },
            {"text": "Monitor firewall performance", "is_correct": False},
            {"text": "Install firewall software", "is_correct": False},
            {"text": "Configure network routing", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides automated incident response capabilities?",
        "explanation": "AWS Systems Manager Incident Manager helps you prepare for, respond to, and recover from application incidents by automating response procedures.",
        "reference": "https://docs.aws.amazon.com/incident-manager/",
        "points": 1,
        "answers": [
            {"text": "AWS Systems Manager Incident Manager", "is_correct": True},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Security Hub", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Cost Anomaly Detection in security?",
        "explanation": "AWS Cost Anomaly Detection can help identify unusual spending patterns that might indicate security breaches, such as unauthorized resource usage or cryptocurrency mining.",
        "reference": "https://docs.aws.amazon.com/cost-management/latest/userguide/getting-started-ad.html",
        "points": 1,
        "answers": [
            {
                "text": "Detect unusual spending patterns indicating potential breaches",
                "is_correct": True,
            },
            {"text": "Reduce AWS costs automatically", "is_correct": False},
            {"text": "Optimize resource allocation", "is_correct": False},
            {"text": "Track budget compliance", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides secure multi-party computation?",
        "explanation": "AWS Clean Rooms enables multiple parties to collaborate and analyze their combined datasets without sharing or revealing underlying data to each other.",
        "reference": "https://docs.aws.amazon.com/clean-rooms/",
        "points": 1,
        "answers": [
            {"text": "AWS Clean Rooms", "is_correct": True},
            {"text": "AWS KMS", "is_correct": False},
            {"text": "AWS Secrets Manager", "is_correct": False},
            {"text": "Amazon Cognito", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CloudShell's security model?",
        "explanation": "AWS CloudShell provides a browser-based shell with temporary credentials and pre-configured AWS CLI access, with automatic session timeout for security.",
        "reference": "https://docs.aws.amazon.com/cloudshell/",
        "points": 1,
        "answers": [
            {
                "text": "Browser-based shell with temporary credentials and auto-timeout",
                "is_correct": True,
            },
            {
                "text": "Permanent shell access with persistent credentials",
                "is_correct": False,
            },
            {"text": "Local shell emulation", "is_correct": False},
            {"text": "SSH-based remote access", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides API key management and rotation?",
        "explanation": "AWS Secrets Manager can automatically rotate API keys, database credentials, and other secrets on a configurable schedule.",
        "reference": "https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html",
        "points": 1,
        "answers": [
            {"text": "AWS Secrets Manager", "is_correct": True},
            {"text": "AWS KMS", "is_correct": False},
            {"text": "AWS IAM", "is_correct": False},
            {"text": "Amazon API Gateway", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Nitro Enclaves?",
        "explanation": "AWS Nitro Enclaves enables customers to create isolated compute environments to further protect and securely process highly sensitive data.",
        "reference": "https://docs.aws.amazon.com/enclaves/",
        "points": 1,
        "answers": [
            {
                "text": "Create isolated compute environments for sensitive data",
                "is_correct": True,
            },
            {"text": "Encrypt network traffic", "is_correct": False},
            {"text": "Manage user identities", "is_correct": False},
            {"text": "Monitor system performance", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides database encryption key management?",
        "explanation": "AWS RDS integrates with AWS KMS to provide transparent data encryption for databases, with AWS managing the encryption keys.",
        "reference": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html",
        "points": 1,
        "answers": [
            {"text": "AWS KMS integrated with RDS", "is_correct": True},
            {"text": "AWS Secrets Manager", "is_correct": False},
            {"text": "AWS CloudHSM", "is_correct": False},
            {"text": "Amazon Aurora only", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS PrivateLink Endpoint security benefit?",
        "explanation": "AWS PrivateLink endpoints allow secure access to AWS services without traffic traversing the internet, reducing exposure to threats.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/privatelink/concepts.html",
        "points": 1,
        "answers": [
            {"text": "Secure access without internet exposure", "is_correct": True},
            {"text": "Faster data transfer speeds", "is_correct": False},
            {"text": "Lower costs", "is_correct": False},
            {"text": "Better monitoring capabilities", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides security compliance automation?",
        "explanation": "AWS Config Rules and AWS Security Hub provide automated compliance checking against security standards like CIS, PCI DSS, and AWS Foundational Security Standard.",
        "reference": "https://docs.aws.amazon.com/config/latest/developerguide/conformance-packs.html",
        "points": 1,
        "answers": [
            {"text": "AWS Config Rules and Security Hub", "is_correct": True},
            {"text": "AWS CloudTrail only", "is_correct": False},
            {"text": "Amazon Inspector only", "is_correct": False},
            {"text": "AWS Artifact only", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Security Lake?",
        "explanation": "AWS Security Lake automatically centralizes security data from AWS environments, SaaS providers, on-premises, and cloud sources into a purpose-built data lake.",
        "reference": "https://docs.aws.amazon.com/security-lake/",
        "points": 1,
        "answers": [
            {
                "text": "Centralize security data from multiple sources into a data lake",
                "is_correct": True,
            },
            {"text": "Store application logs only", "is_correct": False},
            {"text": "Backup security configurations", "is_correct": False},
            {"text": "Monitor lake performance", "is_correct": False},
        ],
    },
]
