"""AWS Solutions Architect Associate Certification"""

CERTIFICATION = {
    "name": "AWS Certified Solutions Architect - Associate",
    "description": "Design and deploy scalable, highly available systems on AWS",
    "slug": "aws-solutions-architect-associate",
    "level": "Associate",
    "duration": 186,
    "questions_count": 62,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which AWS service would you use to implement a serverless web application?",
        "explanation": "AWS Lambda, along with API Gateway and other serverless services, enables you to build serverless web applications without managing servers.",
        "reference": "https://docs.aws.amazon.com/lambda/",
        "points": 1,
        "answers": [
            {"text": "Amazon EC2", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": True},
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "AWS Elastic Beanstalk", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon VPC?",
        "explanation": "Amazon Virtual Private Cloud (VPC) lets you provision a logically isolated section of the AWS Cloud where you can launch AWS resources in a virtual network that you define.",
        "reference": "https://docs.aws.amazon.com/vpc/",
        "points": 1,
        "answers": [
            {
                "text": "To create isolated network environments in AWS",
                "is_correct": True,
            },
            {"text": "To manage user permissions", "is_correct": False},
            {"text": "To store files securely", "is_correct": False},
            {"text": "To monitor application performance", "is_correct": False},
        ],
    },
    {
        "text": "Which storage class in Amazon S3 is most cost-effective for long-term archival?",
        "explanation": "S3 Glacier Deep Archive is the lowest-cost storage class for long-term retention and digital preservation for data that may be accessed once or twice in a year.",
        "reference": "https://docs.aws.amazon.com/s3/latest/userguide/storage-class-intro.html",
        "points": 1,
        "answers": [
            {"text": "S3 Standard", "is_correct": False},
            {"text": "S3 Intelligent-Tiering", "is_correct": False},
            {"text": "S3 Glacier", "is_correct": False},
            {"text": "S3 Glacier Deep Archive", "is_correct": True},
        ],
    },
    {
        "text": "What is the maximum size of an object that can be uploaded to Amazon S3 in a single PUT operation?",
        "explanation": "The maximum object size for a single PUT operation is 5 GB. For larger objects, you must use multipart upload.",
        "reference": "https://docs.aws.amazon.com/s3/latest/userguide/object-keys.html",
        "points": 1,
        "answers": [
            {"text": "5 GB", "is_correct": True},
            {"text": "1 TB", "is_correct": False},
            {"text": "100 GB", "is_correct": False},
            {"text": "5 TB", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides a managed NoSQL database?",
        "explanation": "Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability.",
        "reference": "https://docs.aws.amazon.com/dynamodb/",
        "points": 1,
        "answers": [
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon DynamoDB", "is_correct": True},
            {"text": "Amazon Redshift", "is_correct": False},
            {"text": "Amazon ElastiCache", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of an Application Load Balancer (ALB)?",
        "explanation": "Application Load Balancer operates at Layer 7 and routes HTTP/HTTPS traffic to targets based on content of the request, supporting advanced routing features.",
        "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/application/",
        "points": 1,
        "answers": [
            {
                "text": "Route traffic based on application content at Layer 7",
                "is_correct": True,
            },
            {"text": "Route traffic at Layer 4 only", "is_correct": False},
            {"text": "Store application data", "is_correct": False},
            {"text": "Monitor application performance", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides content delivery network (CDN) capabilities?",
        "explanation": "Amazon CloudFront is a web service that speeds up distribution of static and dynamic web content through a worldwide network of edge locations.",
        "reference": "https://docs.aws.amazon.com/cloudfront/",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudFront", "is_correct": True},
            {"text": "Amazon Route 53", "is_correct": False},
            {"text": "AWS Direct Connect", "is_correct": False},
            {"text": "Amazon API Gateway", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between EBS and Instance Store volumes?",
        "explanation": "EBS volumes provide persistent block storage that persists independently from EC2 instances, while Instance Store provides temporary storage that's physically attached to the host computer.",
        "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Storage.html",
        "points": 1,
        "answers": [
            {
                "text": "EBS is persistent, Instance Store is temporary",
                "is_correct": True,
            },
            {
                "text": "EBS is temporary, Instance Store is persistent",
                "is_correct": False,
            },
            {"text": "Both are persistent", "is_correct": False},
            {"text": "Both are temporary", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service enables you to run containers without managing servers?",
        "explanation": "AWS Fargate is a serverless compute engine for containers that works with both Amazon ECS and Amazon EKS.",
        "reference": "https://docs.aws.amazon.com/fargate/",
        "points": 1,
        "answers": [
            {"text": "AWS Fargate", "is_correct": True},
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "Amazon EKS", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon Route 53?",
        "explanation": "Amazon Route 53 is a highly available and scalable Domain Name System (DNS) web service designed to route users to Internet applications.",
        "reference": "https://docs.aws.amazon.com/route53/",
        "points": 1,
        "answers": [
            {"text": "DNS service and domain registration", "is_correct": True},
            {"text": "Load balancing only", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
            {"text": "Database routing", "is_correct": False},
        ],
    },
    {
        "text": "Which database engine is NOT supported by Amazon RDS?",
        "explanation": "Amazon RDS supports PostgreSQL, MySQL, MariaDB, Oracle, SQL Server, and Amazon Aurora, but not MongoDB (which is a NoSQL database).",
        "reference": "https://docs.aws.amazon.com/rds/latest/userguide/Welcome.html",
        "points": 1,
        "answers": [
            {"text": "MySQL", "is_correct": False},
            {"text": "PostgreSQL", "is_correct": False},
            {"text": "MongoDB", "is_correct": True},
            {"text": "Oracle", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon ElastiCache?",
        "explanation": "Amazon ElastiCache is a web service that makes it easy to deploy, operate, and scale an in-memory cache in the cloud to improve application performance.",
        "reference": "https://docs.aws.amazon.com/elasticache/",
        "points": 1,
        "answers": [
            {
                "text": "In-memory caching to improve application performance",
                "is_correct": True,
            },
            {"text": "Long-term data storage", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
            {"text": "Database backups", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides a managed Kubernetes service?",
        "explanation": "Amazon Elastic Kubernetes Service (EKS) is a managed service that you can use to run Kubernetes on AWS without installing and operating your own Kubernetes clusters.",
        "reference": "https://docs.aws.amazon.com/eks/",
        "points": 1,
        "answers": [
            {"text": "Amazon EKS", "is_correct": True},
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "AWS Fargate", "is_correct": False},
            {"text": "AWS Batch", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of Availability Zones in a single VPC?",
        "explanation": "A VPC can span all Availability Zones in an AWS Region. Currently, AWS Regions can have up to 6 Availability Zones, and a VPC can use all of them.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/configure-your-vpc.html",
        "points": 1,
        "answers": [
            {"text": "All AZs in the region", "is_correct": True},
            {"text": "3", "is_correct": False},
            {"text": "5", "is_correct": False},
            {"text": "10", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides managed message queuing?",
        "explanation": "Amazon Simple Queue Service (SQS) is a fully managed message queuing service that enables you to decouple and scale microservices, distributed systems, and serverless applications.",
        "reference": "https://docs.aws.amazon.com/sqs/",
        "points": 1,
        "answers": [
            {"text": "Amazon SQS", "is_correct": True},
            {"text": "Amazon SNS", "is_correct": False},
            {"text": "Amazon SES", "is_correct": False},
            {"text": "AWS Step Functions", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon SNS?",
        "explanation": "Amazon Simple Notification Service (SNS) is a messaging service for application-to-application (A2A) and application-to-person (A2P) communication.",
        "reference": "https://docs.aws.amazon.com/sns/",
        "points": 1,
        "answers": [
            {"text": "Publish/subscribe messaging service", "is_correct": True},
            {"text": "Queue-based messaging only", "is_correct": False},
            {"text": "Email service only", "is_correct": False},
            {"text": "File transfer service", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS storage service provides file system access for EC2 instances?",
        "explanation": "Amazon Elastic File System (EFS) provides scalable file storage for use with Amazon EC2 instances and supports NFSv4 protocol.",
        "reference": "https://docs.aws.amazon.com/efs/",
        "points": 1,
        "answers": [
            {"text": "Amazon EFS", "is_correct": True},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon EBS", "is_correct": False},
            {"text": "AWS Storage Gateway", "is_correct": False},
        ],
    },
    {
        "text": "What is Auto Scaling in AWS?",
        "explanation": "Auto Scaling monitors applications and automatically adjusts capacity to maintain steady, predictable performance at the lowest possible cost.",
        "reference": "https://docs.aws.amazon.com/autoscaling/",
        "points": 1,
        "answers": [
            {
                "text": "Automatically adjust capacity based on demand",
                "is_correct": True,
            },
            {"text": "Manual scaling only", "is_correct": False},
            {"text": "Fixed capacity allocation", "is_correct": False},
            {"text": "Storage scaling only", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides a data warehouse solution?",
        "explanation": "Amazon Redshift is a fully managed, petabyte-scale data warehouse service in the cloud designed for large scale data set storage and analysis.",
        "reference": "https://docs.aws.amazon.com/redshift/",
        "points": 1,
        "answers": [
            {"text": "Amazon Redshift", "is_correct": True},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon S3", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS CloudFormation?",
        "explanation": "AWS CloudFormation gives developers and systems administrators an easy way to create and manage AWS resources using templates for Infrastructure as Code.",
        "reference": "https://docs.aws.amazon.com/cloudformation/",
        "points": 1,
        "answers": [
            {"text": "Infrastructure as Code using templates", "is_correct": True},
            {"text": "Application deployment only", "is_correct": False},
            {"text": "Monitoring and logging", "is_correct": False},
            {"text": "User management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides real-time analytics on streaming data?",
        "explanation": "Amazon Kinesis enables you to collect, process, and analyze real-time, streaming data so you can get timely insights and react quickly to new information.",
        "reference": "https://docs.aws.amazon.com/kinesis/",
        "points": 1,
        "answers": [
            {"text": "Amazon Kinesis", "is_correct": True},
            {"text": "Amazon Athena", "is_correct": False},
            {"text": "Amazon EMR", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of a NAT Gateway?",
        "explanation": "A NAT Gateway enables instances in private subnets to connect to the internet or other AWS services, but prevents the internet from initiating connections with the instances.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html",
        "points": 1,
        "answers": [
            {
                "text": "Allow outbound internet access from private subnets",
                "is_correct": True,
            },
            {
                "text": "Provide inbound internet access to private subnets",
                "is_correct": False,
            },
            {"text": "Load balance traffic", "is_correct": False},
            {"text": "Cache content", "is_correct": False},
        ],
    },
    {
        "text": "Which database service provides automated backups and point-in-time recovery?",
        "explanation": "Amazon RDS automatically backs up your database and transaction logs, enabling point-in-time recovery to any second during your backup retention period.",
        "reference": "https://docs.aws.amazon.com/rds/latest/userguide/CHAP_CommonTasks.BackupRestore.html",
        "points": 1,
        "answers": [
            {"text": "Amazon RDS", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon ElastiCache", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon API Gateway?",
        "explanation": "Amazon API Gateway is a fully managed service that makes it easy for developers to create, publish, maintain, monitor, and secure APIs at any scale.",
        "reference": "https://docs.aws.amazon.com/apigateway/",
        "points": 1,
        "answers": [
            {"text": "Create and manage APIs", "is_correct": True},
            {"text": "Store API documentation", "is_correct": False},
            {"text": "Compile application code", "is_correct": False},
            {"text": "Manage database connections", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides event-driven computing?",
        "explanation": "AWS Lambda runs code in response to events such as changes to data in S3 buckets, DynamoDB tables, or custom events from applications.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/lambda-invocation.html",
        "points": 1,
        "answers": [
            {"text": "AWS Lambda", "is_correct": True},
            {"text": "Amazon EC2", "is_correct": False},
            {"text": "AWS Batch", "is_correct": False},
            {"text": "Amazon ECS", "is_correct": False},
        ],
    },
    {
        "text": "What is the default VPC?",
        "explanation": "The default VPC is a ready-to-use VPC that includes a default subnet in each Availability Zone, an internet gateway, and settings to enable DNS resolution.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html",
        "points": 1,
        "answers": [
            {"text": "Pre-configured VPC ready for immediate use", "is_correct": True},
            {"text": "The largest VPC in your account", "is_correct": False},
            {"text": "A VPC template", "is_correct": False},
            {"text": "A backup VPC", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides Big Data processing capabilities?",
        "explanation": "Amazon EMR (Elastic MapReduce) provides a managed cluster platform that simplifies running big data frameworks such as Apache Hadoop and Apache Spark.",
        "reference": "https://docs.aws.amazon.com/emr/",
        "points": 1,
        "answers": [
            {"text": "Amazon EMR", "is_correct": True},
            {"text": "Amazon Redshift", "is_correct": False},
            {"text": "Amazon Athena", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon CloudWatch?",
        "explanation": "Amazon CloudWatch is a monitoring and management service that provides data and actionable insights to monitor applications, respond to system-wide performance changes, optimize resource utilization, and get a unified view of operational health.",
        "reference": "https://docs.aws.amazon.com/cloudwatch/",
        "points": 1,
        "answers": [
            {
                "text": "Monitor and collect metrics from AWS resources",
                "is_correct": True,
            },
            {"text": "Store application logs only", "is_correct": False},
            {"text": "Manage user access", "is_correct": False},
            {"text": "Deploy applications", "is_correct": False},
        ],
    },
    {
        "text": "Which instance family is optimized for compute-intensive workloads?",
        "explanation": "C-family instances (like C5, C6i) are optimized for compute-intensive applications that benefit from high-performance processors.",
        "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html",
        "points": 1,
        "answers": [
            {"text": "C instances (Compute Optimized)", "is_correct": True},
            {"text": "M instances (General Purpose)", "is_correct": False},
            {"text": "R instances (Memory Optimized)", "is_correct": False},
            {"text": "T instances (Burstable Performance)", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Direct Connect?",
        "explanation": "AWS Direct Connect establishes a dedicated network connection from your premises to AWS, which can reduce network costs, increase bandwidth throughput, and provide more consistent network experience.",
        "reference": "https://docs.aws.amazon.com/directconnect/",
        "points": 1,
        "answers": [
            {"text": "Dedicated network connection to AWS", "is_correct": True},
            {"text": "VPN connection to AWS", "is_correct": False},
            {"text": "Internet gateway for VPC", "is_correct": False},
            {"text": "Load balancer service", "is_correct": False},
        ],
    },
    {
        "text": "Which storage class automatically moves objects between access tiers?",
        "explanation": "S3 Intelligent-Tiering automatically moves objects between two access tiers based on changing access patterns, optimizing costs without performance impact.",
        "reference": "https://docs.aws.amazon.com/s3/latest/userguide/intelligent-tiering.html",
        "points": 1,
        "answers": [
            {"text": "S3 Intelligent-Tiering", "is_correct": True},
            {"text": "S3 Standard", "is_correct": False},
            {"text": "S3 One Zone-IA", "is_correct": False},
            {"text": "S3 Glacier", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of subnets in a VPC?",
        "explanation": "Subnets allow you to partition your VPC's IP address range and place AWS resources in different availability zones for high availability and fault tolerance.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/configure-subnets.html",
        "points": 1,
        "answers": [
            {
                "text": "Partition VPC IP range across availability zones",
                "is_correct": True,
            },
            {"text": "Store network configurations", "is_correct": False},
            {"text": "Manage user permissions", "is_correct": False},
            {"text": "Monitor network traffic", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides SQL query capabilities on data stored in S3?",
        "explanation": "Amazon Athena is an interactive query service that makes it easy to analyze data in Amazon S3 using standard SQL.",
        "reference": "https://docs.aws.amazon.com/athena/",
        "points": 1,
        "answers": [
            {"text": "Amazon Athena", "is_correct": True},
            {"text": "Amazon Redshift", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
            {"text": "Amazon EMR", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Security Groups?",
        "explanation": "Security Groups act as a virtual firewall for EC2 instances to control inbound and outbound traffic at the instance level.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html",
        "points": 1,
        "answers": [
            {"text": "Virtual firewall for EC2 instances", "is_correct": True},
            {"text": "Manage user groups", "is_correct": False},
            {"text": "Organize AWS resources", "is_correct": False},
            {"text": "Monitor security events", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides email sending capabilities?",
        "explanation": "Amazon Simple Email Service (SES) is a cloud-based email sending service designed to help digital marketers and application developers send marketing, notification, and transactional emails.",
        "reference": "https://docs.aws.amazon.com/ses/",
        "points": 1,
        "answers": [
            {"text": "Amazon SES", "is_correct": True},
            {"text": "Amazon SNS", "is_correct": False},
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon RDS Read Replicas?",
        "explanation": "Read Replicas allow you to create one or more read-only copies of your database to scale read capacity and improve performance for read-heavy applications.",
        "reference": "https://docs.aws.amazon.com/rds/latest/userguide/USER_ReadRepl.html",
        "points": 1,
        "answers": [
            {
                "text": "Scale read capacity with read-only database copies",
                "is_correct": True,
            },
            {"text": "Backup database automatically", "is_correct": False},
            {"text": "Encrypt database data", "is_correct": False},
            {"text": "Monitor database performance", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides hybrid cloud storage?",
        "explanation": "AWS Storage Gateway connects on-premises software appliances with cloud-based storage to provide seamless and secure integration between on-premises environments and AWS storage services.",
        "reference": "https://docs.aws.amazon.com/storagegateway/",
        "points": 1,
        "answers": [
            {"text": "AWS Storage Gateway", "is_correct": True},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon EFS", "is_correct": False},
            {"text": "AWS DataSync", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Aurora?",
        "explanation": "Amazon Aurora is a MySQL and PostgreSQL-compatible relational database built for the cloud that combines the performance and availability of traditional enterprise databases with the simplicity and cost-effectiveness of open source databases.",
        "reference": "https://docs.aws.amazon.com/aurora/",
        "points": 1,
        "answers": [
            {
                "text": "Cloud-native relational database compatible with MySQL and PostgreSQL",
                "is_correct": True,
            },
            {"text": "NoSQL database service", "is_correct": False},
            {"text": "Data warehouse service", "is_correct": False},
            {"text": "In-memory cache service", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides workflow orchestration?",
        "explanation": "AWS Step Functions is a serverless function orchestrator that makes it easy to sequence AWS Lambda functions and multiple AWS services into business-critical applications.",
        "reference": "https://docs.aws.amazon.com/step-functions/",
        "points": 1,
        "answers": [
            {"text": "AWS Step Functions", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "AWS Batch", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of an Internet Gateway?",
        "explanation": "An Internet Gateway enables communication between instances in your VPC and the internet. It's a horizontally scaled, redundant, and highly available VPC component.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html",
        "points": 1,
        "answers": [
            {
                "text": "Enable internet connectivity for VPC resources",
                "is_correct": True,
            },
            {"text": "Provide private connectivity between VPCs", "is_correct": False},
            {"text": "Load balance traffic", "is_correct": False},
            {"text": "Monitor network traffic", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides managed Apache Kafka?",
        "explanation": "Amazon Managed Streaming for Apache Kafka (MSK) is a fully managed service that makes it easy to build and run applications that use Apache Kafka to process streaming data.",
        "reference": "https://docs.aws.amazon.com/msk/",
        "points": 1,
        "answers": [
            {"text": "Amazon MSK", "is_correct": True},
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon SNS", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Elastic Beanstalk?",
        "explanation": "AWS Elastic Beanstalk is an easy-to-use service for deploying and scaling web applications and services. You upload your code and Elastic Beanstalk handles the deployment.",
        "reference": "https://docs.aws.amazon.com/elasticbeanstalk/",
        "points": 1,
        "answers": [
            {
                "text": "Platform service for deploying web applications",
                "is_correct": True,
            },
            {"text": "Container orchestration service", "is_correct": False},
            {"text": "Database management service", "is_correct": False},
            {"text": "Content delivery network", "is_correct": False},
        ],
    },
    {
        "text": "Which instance type provides burstable CPU performance?",
        "explanation": "T-family instances (like T3, T4g) provide burstable CPU performance with a baseline level of CPU utilization and the ability to burst above the baseline when needed.",
        "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances.html",
        "points": 1,
        "answers": [
            {"text": "T instances (Burstable Performance)", "is_correct": True},
            {"text": "M instances (General Purpose)", "is_correct": False},
            {"text": "C instances (Compute Optimized)", "is_correct": False},
            {"text": "R instances (Memory Optimized)", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon S3 Transfer Acceleration?",
        "explanation": "S3 Transfer Acceleration enables fast, easy, and secure transfers of files over long distances between your client and S3 bucket using CloudFront's globally distributed edge locations.",
        "reference": "https://docs.aws.amazon.com/s3/latest/userguide/transfer-acceleration.html",
        "points": 1,
        "answers": [
            {
                "text": "Faster uploads using CloudFront edge locations",
                "is_correct": True,
            },
            {"text": "Automatic data compression", "is_correct": False},
            {"text": "Parallel upload processing", "is_correct": False},
            {"text": "Increased storage capacity", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides DNS-based health checks and failover?",
        "explanation": "Amazon Route 53 health checks monitor the health and performance of your applications and can automatically route traffic away from unhealthy endpoints.",
        "reference": "https://docs.aws.amazon.com/route53/latest/developerguide/dns-failover.html",
        "points": 1,
        "answers": [
            {"text": "Amazon Route 53", "is_correct": True},
            {"text": "Application Load Balancer", "is_correct": False},
            {"text": "AWS Auto Scaling", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Systems Manager?",
        "explanation": "AWS Systems Manager gives you visibility and control of your infrastructure on AWS. It provides a unified user interface to view operational data from multiple AWS services.",
        "reference": "https://docs.aws.amazon.com/systems-manager/",
        "points": 1,
        "answers": [
            {
                "text": "Unified interface for infrastructure management",
                "is_correct": True,
            },
            {"text": "Application performance monitoring", "is_correct": False},
            {"text": "Database administration", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides data migration capabilities?",
        "explanation": "AWS DataSync is an online data transfer service that simplifies, automates, and accelerates moving data between on-premises storage systems and AWS storage services.",
        "reference": "https://docs.aws.amazon.com/datasync/",
        "points": 1,
        "answers": [
            {"text": "AWS DataSync", "is_correct": True},
            {"text": "AWS Storage Gateway", "is_correct": False},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "AWS Snowball", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon DocumentDB?",
        "explanation": "Amazon DocumentDB is a fast, scalable, highly available, and fully managed document database service that supports MongoDB workloads.",
        "reference": "https://docs.aws.amazon.com/documentdb/",
        "points": 1,
        "answers": [
            {
                "text": "Managed MongoDB-compatible document database",
                "is_correct": True,
            },
            {"text": "Relational database service", "is_correct": False},
            {"text": "Key-value database service", "is_correct": False},
            {"text": "Graph database service", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides petabyte-scale data transfer?",
        "explanation": "AWS Snowmobile is an exabyte-scale data transfer service used to move extremely large amounts of data to AWS using a secure semi-trailer truck.",
        "reference": "https://docs.aws.amazon.com/snowball/latest/developer-guide/snowmobile.html",
        "points": 1,
        "answers": [
            {"text": "AWS Snowmobile", "is_correct": True},
            {"text": "AWS Snowball", "is_correct": False},
            {"text": "AWS DataSync", "is_correct": False},
            {"text": "AWS Direct Connect", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon GuardDuty?",
        "explanation": "Amazon GuardDuty is a threat detection service that uses machine learning to continuously monitor for malicious activity and unauthorized behavior in your AWS accounts and workloads.",
        "reference": "https://docs.aws.amazon.com/guardduty/",
        "points": 1,
        "answers": [
            {
                "text": "Intelligent threat detection using machine learning",
                "is_correct": True,
            },
            {"text": "Network firewall service", "is_correct": False},
            {"text": "Identity and access management", "is_correct": False},
            {"text": "Data encryption service", "is_correct": False},
        ],
    },
    {
        "text": "Which Load Balancer type operates at Layer 4 (Transport Layer)?",
        "explanation": "Network Load Balancer operates at Layer 4 and is capable of handling millions of requests per second while maintaining ultra-low latencies.",
        "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/network/",
        "points": 1,
        "answers": [
            {"text": "Network Load Balancer", "is_correct": True},
            {"text": "Application Load Balancer", "is_correct": False},
            {"text": "Classic Load Balancer", "is_correct": False},
            {"text": "Gateway Load Balancer", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Transit Gateway?",
        "explanation": "AWS Transit Gateway connects VPCs and on-premises networks through a central hub, simplifying network architecture and reducing operational overhead.",
        "reference": "https://docs.aws.amazon.com/transit-gateway/",
        "points": 1,
        "answers": [
            {
                "text": "Central hub for connecting VPCs and on-premises networks",
                "is_correct": True,
            },
            {"text": "Internet gateway for multiple VPCs", "is_correct": False},
            {"text": "VPN connection service", "is_correct": False},
            {"text": "Load balancing service", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides Extract, Transform, Load (ETL) capabilities?",
        "explanation": "AWS Glue is a fully managed extract, transform, and load (ETL) service that makes it easy to prepare and transform data for analytics.",
        "reference": "https://docs.aws.amazon.com/glue/",
        "points": 1,
        "answers": [
            {"text": "AWS Glue", "is_correct": True},
            {"text": "Amazon EMR", "is_correct": False},
            {"text": "Amazon Athena", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Timestream?",
        "explanation": "Amazon Timestream is a fast, scalable, and serverless time series database service for IoT and operational applications that makes it easy to store and analyze trillions of events per day.",
        "reference": "https://docs.aws.amazon.com/timestream/",
        "points": 1,
        "answers": [
            {
                "text": "Serverless time series database for IoT applications",
                "is_correct": True,
            },
            {"text": "Relational database service", "is_correct": False},
            {"text": "Document database service", "is_correct": False},
            {"text": "In-memory database service", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides managed Apache Spark and Hadoop?",
        "explanation": "Amazon EMR (Elastic MapReduce) is a managed cluster platform that simplifies running big data frameworks such as Apache Hadoop and Apache Spark on AWS.",
        "reference": "https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-what-is-emr.html",
        "points": 1,
        "answers": [
            {"text": "Amazon EMR", "is_correct": True},
            {"text": "AWS Glue", "is_correct": False},
            {"text": "Amazon Athena", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of VPC Peering?",
        "explanation": "VPC Peering allows you to connect two VPCs privately using AWS's network infrastructure, enabling instances in either VPC to communicate as if they are within the same network.",
        "reference": "https://docs.aws.amazon.com/vpc/latest/peering/",
        "points": 1,
        "answers": [
            {
                "text": "Connect two VPCs privately using AWS network",
                "is_correct": True,
            },
            {"text": "Connect VPC to internet", "is_correct": False},
            {"text": "Load balance traffic between VPCs", "is_correct": False},
            {"text": "Monitor VPC traffic", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides graph database capabilities?",
        "explanation": "Amazon Neptune is a fast, reliable, fully-managed graph database service that makes it easy to build and run applications that work with highly connected datasets.",
        "reference": "https://docs.aws.amazon.com/neptune/",
        "points": 1,
        "answers": [
            {"text": "Amazon Neptune", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS App Runner?",
        "explanation": "AWS App Runner is a fully managed service that makes it easy to quickly deploy from source code or container image directly to a scalable and secure web application in AWS.",
        "reference": "https://docs.aws.amazon.com/apprunner/",
        "points": 1,
        "answers": [
            {
                "text": "Fully managed service for deploying web applications from source code",
                "is_correct": True,
            },
            {"text": "Container orchestration service", "is_correct": False},
            {"text": "Application performance monitoring", "is_correct": False},
            {"text": "API management service", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides real-time machine learning inference?",
        "explanation": "Amazon SageMaker provides real-time inference endpoints that can host machine learning models for real-time predictions with low latency.",
        "reference": "https://docs.aws.amazon.com/sagemaker/latest/dg/realtime-endpoints.html",
        "points": 1,
        "answers": [
            {"text": "Amazon SageMaker", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "Amazon Comprehend", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Cost Explorer?",
        "explanation": "AWS Cost Explorer has an easy-to-use interface that lets you visualize, understand, and manage your AWS costs and usage over time.",
        "reference": "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html",
        "points": 1,
        "answers": [
            {"text": "Visualize and analyze AWS costs and usage", "is_correct": True},
            {"text": "Optimize resource performance", "is_correct": False},
            {"text": "Monitor application health", "is_correct": False},
            {"text": "Manage user permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides in-memory data structure store?",
        "explanation": "Amazon ElastiCache for Redis provides a blazing fast in-memory data structure store, used as a database, cache, and message broker.",
        "reference": "https://docs.aws.amazon.com/elasticache/latest/red-ug/",
        "points": 1,
        "answers": [
            {"text": "Amazon ElastiCache for Redis", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon S3", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Batch?",
        "explanation": "AWS Batch enables you to run batch computing workloads on the AWS Cloud by dynamically provisioning the optimal quantity and type of compute resources.",
        "reference": "https://docs.aws.amazon.com/batch/",
        "points": 1,
        "answers": [
            {
                "text": "Managed service for running batch computing workloads",
                "is_correct": True,
            },
            {"text": "Real-time data processing service", "is_correct": False},
            {"text": "Container orchestration service", "is_correct": False},
            {"text": "File transfer service", "is_correct": False},
        ],
    },
]
