"""AWS SysOps Administrator Associate Certification"""

CERTIFICATION = {
    "name": "AWS Certified SysOps Administrator - Associate",
    "description": "Deploy, manage, and operate scalable, highly available, and fault tolerant systems on AWS",
    "slug": "aws-sysops-administrator-associate",
    "level": "Associate",
    "duration": 165,
    "questions_count": 55,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [{"text": "Which AWS service should you use to monitor and troubleshoot application performance?",
              "explanation": "AWS X-Ray is a service that collects data about requests that your application serves, and provides tools you can use to view, filter, and gain insights into that data to identify issues and opportunities for optimization.",
              "reference": "https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html",
              "points": 1,
              "answers": [{"text": "AWS X-Ray",
                           "is_correct": True},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS CloudTrail",
                           "is_correct": False},
                          {"text": "AWS Inspector",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Systems Manager?",
              "explanation": "AWS Systems Manager is a collection of capabilities that helps you automate management tasks such as collecting system inventory, applying OS patches, automating the creation of Amazon Machine Images (AMIs), and configuring operating systems (OSs) and applications at scale.",
              "reference": "https://docs.aws.amazon.com/systems-manager/",
              "points": 1,
              "answers": [{"text": "Automate management tasks for AWS resources",
                           "is_correct": True},
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Manage DNS records",
                           "is_correct": False},
                          {"text": "Create load balancers",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides automated backup for EC2 instances?",
              "explanation": "AWS Backup is a centralized backup service that makes it easy and cost-effective for you to backup your application data across AWS services in the AWS cloud, including Amazon EBS volumes, Amazon EC2 instances, Amazon RDS databases, Amazon DynamoDB tables, Amazon EFS file systems, Amazon FSx file systems, and AWS Storage Gateway volumes.",
              "reference": "https://docs.aws.amazon.com/aws-backup/",
              "points": 1,
              "answers": [{"text": "AWS Backup",
                           "is_correct": True},
                          {"text": "Amazon S3",
                           "is_correct": False},
                          {"text": "AWS CloudFormation",
                           "is_correct": False},
                          {"text": "Amazon EBS Snapshots only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is AWS CloudWatch used for?",
              "explanation": "Amazon CloudWatch is a monitoring and observability service built for DevOps engineers, developers, site reliability engineers (SREs), and IT managers. CloudWatch provides you with data and actionable insights to monitor your applications, respond to system-wide performance changes, optimize resource utilization, and get a unified view of operational health.",
              "reference": "https://docs.aws.amazon.com/cloudwatch/",
              "points": 1,
              "answers": [{"text": "Monitoring and observability of AWS resources",
                           "is_correct": True,
                           },
                          {"text": "Source code version control",
                           "is_correct": False},
                          {"text": "Database administration",
                           "is_correct": False},
                          {"text": "Network security",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service helps you analyze and optimize AWS costs?",
              "explanation": "AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage. You can explore your usage and costs using the main graph, the Cost Explorer cost and usage reports, or the Cost Explorer RI reports.",
              "reference": "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html",
              "points": 1,
              "answers": [{"text": "AWS Cost Explorer",
                           "is_correct": True},
                          {"text": "AWS CloudFormation",
                           "is_correct": False},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS CloudTrail",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the maximum retention period for CloudWatch Logs?",
              "explanation": "CloudWatch Logs can retain log data indefinitely. You can set retention periods from 1 day to 10 years, or choose never expire for indefinite retention.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html",
              "points": 1,
              "answers": [{"text": "Indefinite (never expire)",
                           "is_correct": True},
                          {"text": "1 year maximum",
                           "is_correct": False},
                          {"text": "5 years maximum",
                           "is_correct": False},
                          {"text": "90 days maximum",
                           "is_correct": False},
                          ],
              },
             {"text": "Which CloudWatch metric is NOT available by default for EC2 instances?",
              "explanation": "Memory utilization is not available by default in CloudWatch for EC2 instances. You need to install the CloudWatch agent to collect memory metrics.",
              "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html",
              "points": 1,
              "answers": [{"text": "Memory utilization",
                           "is_correct": True},
                          {"text": "CPU utilization",
                           "is_correct": False},
                          {"text": "Network In/Out",
                           "is_correct": False},
                          {"text": "Disk Read/Write Ops",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of Auto Scaling cooldown periods?",
              "explanation": "Cooldown periods help ensure that Auto Scaling doesn't launch or terminate additional instances before the previous scaling activity takes effect, preventing thrashing.",
              "reference": "https://docs.aws.amazon.com/autoscaling/ec2/userguide/Cooldown.html",
              "points": 1,
              "answers": [{"text": "Prevent rapid scaling actions before previous ones take effect",
                           "is_correct": True,
                           },
                          {"text": "Reduce costs by delaying scaling",
                           "is_correct": False},
                          {"text": "Improve instance performance",
                           "is_correct": False},
                          {"text": "Schedule maintenance windows",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service helps automate patch management for EC2 instances?",
              "explanation": "AWS Systems Manager Patch Manager automates the process of patching managed instances with both security related and other types of updates.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-patch.html",
              "points": 1,
              "answers": [{"text": "AWS Systems Manager Patch Manager",
                           "is_correct": True},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS Inspector",
                           "is_correct": False},
                          {"text": "AWS CloudFormation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the difference between CloudWatch Logs and CloudTrail?",
              "explanation": "CloudWatch Logs captures application and system logs, while CloudTrail captures API calls and management events for auditing purposes.",
              "reference": "https://docs.aws.amazon.com/cloudtrail/latest/userguide/cloudtrail-user-guide.html",
              "points": 1,
              "answers": [{"text": "CloudWatch Logs captures application logs, CloudTrail captures API calls",
                           "is_correct": True,
                           },
                          {"text": "They serve the same purpose",
                           "is_correct": False},
                          {"text": "CloudWatch Logs is for billing, CloudTrail for monitoring",
                           "is_correct": False,
                           },
                          {"text": "CloudWatch Logs is free, CloudTrail costs money",
                           "is_correct": False,
                           },
                          ],
              },
             {"text": "Which tool helps you estimate AWS costs before deployment?",
              "explanation": "AWS Pricing Calculator helps you estimate the cost of AWS services for your specific use case before you deploy resources.",
              "reference": "https://calculator.aws/",
              "points": 1,
              "answers": [{"text": "AWS Pricing Calculator",
                           "is_correct": True},
                          {"text": "AWS Cost Explorer",
                           "is_correct": False},
                          {"text": "AWS Budgets",
                           "is_correct": False},
                          {"text": "AWS Cost and Usage Report",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Config?",
              "explanation": "AWS Config is a service that enables you to assess, audit, and evaluate the configurations of your AWS resources for compliance and governance.",
              "reference": "https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html",
              "points": 1,
              "answers": [{"text": "Track resource configurations and compliance",
                           "is_correct": True,
                           },
                          {"text": "Monitor application performance",
                           "is_correct": False},
                          {"text": "Manage user access",
                           "is_correct": False},
                          {"text": "Deploy infrastructure",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides centralized management of EC2 instances without SSH access?",
              "explanation": "AWS Systems Manager Session Manager provides secure and auditable instance management without needing to open inbound ports, maintain bastion hosts, or manage SSH keys.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html",
              "points": 1,
              "answers": [{"text": "AWS Systems Manager Session Manager",
                           "is_correct": True},
                          {"text": "AWS Direct Connect",
                           "is_correct": False},
                          {"text": "AWS VPN",
                           "is_correct": False},
                          {"text": "AWS PrivateLink",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for storing sensitive configuration data?",
              "explanation": "AWS Systems Manager Parameter Store provides secure, hierarchical storage for configuration data and secrets management with encryption support.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html",
              "points": 1,
              "answers": [{"text": "AWS Systems Manager Parameter Store",
                           "is_correct": True},
                          {"text": "Environment variables",
                           "is_correct": False},
                          {"text": "Configuration files",
                           "is_correct": False},
                          {"text": "Database storage",
                           "is_correct": False},
                          ],
              },
             {"text": "Which CloudWatch feature allows you to take automated actions based on metrics?",
              "explanation": "CloudWatch Alarms can trigger automated actions such as Auto Scaling, EC2 actions, or SNS notifications when metric thresholds are breached.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html",
              "points": 1,
              "answers": [{"text": "CloudWatch Alarms",
                           "is_correct": True},
                          {"text": "CloudWatch Logs",
                           "is_correct": False},
                          {"text": "CloudWatch Metrics",
                           "is_correct": False},
                          {"text": "CloudWatch Events",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Trusted Advisor?",
              "explanation": "AWS Trusted Advisor provides real-time guidance to help you provision your resources following AWS best practices for cost optimization, security, fault tolerance, service limits, and performance.",
              "reference": "https://docs.aws.amazon.com/support/latest/user/trusted-advisor.html",
              "points": 1,
              "answers": [{"text": "Provide best practice recommendations for AWS resources",
                           "is_correct": True,
                           },
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Manage user permissions",
                           "is_correct": False},
                          {"text": "Deploy applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service helps you set up automated responses to security findings?",
              "explanation": "AWS Security Hub aggregates security findings and can trigger automated remediation responses through integration with other AWS services.",
              "reference": "https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cloudwatch-events.html",
              "points": 1,
              "answers": [{"text": "AWS Security Hub",
                           "is_correct": True},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS CloudTrail",
                           "is_correct": False},
                          {"text": "AWS Inspector",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the maximum size for a single CloudWatch Logs event?",
              "explanation": "The maximum size for a single log event in CloudWatch Logs is 256 KB. Events larger than this will be rejected.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html",
              "points": 1,
              "answers": [{"text": "256 KB",
                           "is_correct": True},
                          {"text": "1 MB",
                           "is_correct": False},
                          {"text": "512 KB",
                           "is_correct": False},
                          {"text": "128 KB",
                           "is_correct": False},
                          ],
              },
             {"text": "Which AWS service provides distributed tracing for microservices?",
              "explanation": "AWS X-Ray provides distributed tracing capabilities that help you analyze and debug distributed applications and microservices.",
              "reference": "https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html",
              "points": 1,
              "answers": [{"text": "AWS X-Ray",
                           "is_correct": True},
                          {"text": "CloudWatch Logs",
                           "is_correct": False},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "CloudWatch Metrics",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Personal Health Dashboard?",
              "explanation": "AWS Personal Health Dashboard provides alerts and remediation guidance when AWS is experiencing events that might affect your resources.",
              "reference": "https://docs.aws.amazon.com/health/latest/ug/what-is-aws-personal-health-dashboard.html",
              "points": 1,
              "answers": [{"text": "Provide personalized alerts about AWS service events affecting your resources",
                           "is_correct": True,
                           },
                          {"text": "Monitor application performance",
                           "is_correct": False},
                          {"text": "Manage billing information",
                           "is_correct": False},
                          {"text": "Track resource usage",
                           "is_correct": False},
                          ],
              },
             {"text": "Which Auto Scaling policy type provides the fastest scaling response?",
              "explanation": "Target tracking scaling policies automatically adjust capacity to maintain a target metric value, providing faster and more responsive scaling than simple scaling policies.",
              "reference": "https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html",
              "points": 1,
              "answers": [{"text": "Target tracking scaling",
                           "is_correct": True},
                          {"text": "Simple scaling",
                           "is_correct": False},
                          {"text": "Step scaling",
                           "is_correct": False},
                          {"text": "Scheduled scaling",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended method for installing software on EC2 instances at launch?",
              "explanation": "User Data scripts run during instance initialization and are the recommended method for installing software and configuring instances at launch.",
              "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html",
              "points": 1,
              "answers": [{"text": "User Data scripts",
                           "is_correct": True},
                          {"text": "SSH after launch",
                           "is_correct": False},
                          {"text": "Manual installation",
                           "is_correct": False},
                          {"text": "Remote desktop",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service helps automate AMI creation and management?",
              "explanation": "EC2 Image Builder provides a simplified way to build, test, and deploy OS images for use with Amazon EC2 and on-premises.",
              "reference": "https://docs.aws.amazon.com/imagebuilder/latest/userguide/what-is-image-builder.html",
              "points": 1,
              "answers": [{"text": "EC2 Image Builder",
                           "is_correct": True},
                          {"text": "AWS Systems Manager",
                           "is_correct": False},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS CloudFormation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of CloudWatch custom metrics?",
              "explanation": "CloudWatch custom metrics allow you to publish application-specific metrics that are not available by default, enabling comprehensive monitoring of your applications.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html",
              "points": 1,
              "answers": [{"text": "Publish application-specific metrics not available by default",
                           "is_correct": True,
                           },
                          {"text": "Replace default EC2 metrics",
                           "is_correct": False},
                          {"text": "Reduce monitoring costs",
                           "is_correct": False},
                          {"text": "Store log data",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides automated remediation for compliance violations?",
              "explanation": "AWS Config Rules can trigger AWS Systems Manager Automation documents for automated remediation when compliance violations are detected.",
              "reference": "https://docs.aws.amazon.com/config/latest/developerguide/remediation.html",
              "points": 1,
              "answers": [{"text": "AWS Config with Systems Manager Automation",
                           "is_correct": True},
                          {"text": "AWS CloudTrail",
                           "is_correct": False},
                          {"text": "AWS Inspector",
                           "is_correct": False},
                          {"text": "AWS GuardDuty",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for managing EC2 instance lifecycle?",
              "explanation": "Systems Manager Maintenance Windows provide a way to schedule and automate tasks like patching, updates, and other maintenance activities during defined maintenance windows.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-maintenance.html",
              "points": 1,
              "answers": [{"text": "Systems Manager Maintenance Windows",
                           "is_correct": True},
                          {"text": "Manual scheduling",
                           "is_correct": False},
                          {"text": "Auto Scaling only",
                           "is_correct": False},
                          {"text": "CloudFormation updates",
                           "is_correct": False},
                          ],
              },
             {"text": "Which CloudWatch Logs feature helps you analyze log patterns?",
              "explanation": "CloudWatch Logs Insights provides a fast, interactive log analytics service with powerful query capabilities for analyzing log patterns and trends.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html",
              "points": 1,
              "answers": [{"text": "CloudWatch Logs Insights",
                           "is_correct": True},
                          {"text": "CloudWatch Metrics",
                           "is_correct": False},
                          {"text": "CloudWatch Alarms",
                           "is_correct": False},
                          {"text": "CloudWatch Dashboards",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Budgets?",
              "explanation": "AWS Budgets allows you to set custom cost and usage budgets and receive alerts when you exceed or are forecasted to exceed your thresholds.",
              "reference": "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/budgets-managing-costs.html",
              "points": 1,
              "answers": [{"text": "Set cost and usage budgets with alerting",
                           "is_correct": True},
                          {"text": "Calculate pricing estimates",
                           "is_correct": False},
                          {"text": "Analyze historical costs",
                           "is_correct": False},
                          {"text": "Generate detailed billing reports",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides automated security assessments for EC2 instances and container images?",
              "explanation": "Amazon Inspector automatically assesses EC2 instances and container images for software vulnerabilities and unintended network exposure.",
              "reference": "https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html",
              "points": 1,
              "answers": [{"text": "Amazon Inspector",
                           "is_correct": True},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "AWS Security Hub",
                           "is_correct": False},
                          {"text": "AWS Systems Manager",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for handling sensitive data in Systems Manager Parameter Store?",
              "explanation": "SecureString parameters in Parameter Store encrypt sensitive data using AWS KMS keys, providing secure storage for sensitive configuration data.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-securestring.html",
              "points": 1,
              "answers": [{"text": "Use SecureString parameters with KMS encryption",
                           "is_correct": True,
                           },
                          {"text": "Use String parameters only",
                           "is_correct": False},
                          {"text": "Store in environment variables",
                           "is_correct": False},
                          {"text": "Use configuration files",
                           "is_correct": False},
                          ],
              },
             {"text": "Which CloudWatch feature allows you to create reusable visualizations?",
              "explanation": "CloudWatch Dashboards allow you to create reusable, customizable home pages in the CloudWatch console for monitoring your AWS resources and applications.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Dashboards.html",
              "points": 1,
              "answers": [{"text": "CloudWatch Dashboards",
                           "is_correct": True},
                          {"text": "CloudWatch Alarms",
                           "is_correct": False},
                          {"text": "CloudWatch Metrics",
                           "is_correct": False},
                          {"text": "CloudWatch Logs",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of Systems Manager Inventory?",
              "explanation": "Systems Manager Inventory collects information about your instances and the software installed on them, helping you understand your system configurations and installed applications.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-inventory.html",
              "points": 1,
              "answers": [{"text": "Collect information about instances and installed software",
                           "is_correct": True,
                           },
                          {"text": "Store application configuration",
                           "is_correct": False},
                          {"text": "Monitor network traffic",
                           "is_correct": False},
                          {"text": "Manage user access",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service helps you track API calls made in your AWS account?",
              "explanation": "AWS CloudTrail logs API calls made in your AWS account, providing a history of API activity for security analysis, resource change tracking, and compliance auditing.",
              "reference": "https://docs.aws.amazon.com/cloudtrail/latest/userguide/cloudtrail-user-guide.html",
              "points": 1,
              "answers": [{"text": "AWS CloudTrail",
                           "is_correct": True},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "CloudWatch Logs",
                           "is_correct": False},
                          {"text": "AWS X-Ray",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended method for deploying applications consistently across environments?",
              "explanation": "AWS CodeDeploy automates application deployments to compute services, ensuring consistent deployment processes across different environments.",
              "reference": "https://docs.aws.amazon.com/codedeploy/latest/userguide/welcome.html",
              "points": 1,
              "answers": [{"text": "AWS CodeDeploy",
                           "is_correct": True},
                          {"text": "Manual deployment",
                           "is_correct": False},
                          {"text": "SSH scripts",
                           "is_correct": False},
                          {"text": "Configuration management tools only",
                           "is_correct": False},
                          ],
              },
             {"text": "Which CloudWatch metric type provides the highest resolution?",
              "explanation": "High-resolution custom metrics can be published with timestamps as granular as one second, providing the highest resolution monitoring capabilities.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html",
              "points": 1,
              "answers": [{"text": "High-resolution custom metrics (1-second)",
                           "is_correct": True},
                          {"text": "Standard resolution metrics (1-minute)",
                           "is_correct": False},
                          {"text": "Basic monitoring (5-minute)",
                           "is_correct": False},
                          {"text": "Detailed monitoring (1-minute)",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Systems Manager Compliance?",
              "explanation": "Systems Manager Compliance scans your fleet of managed instances for patch compliance and configuration inconsistencies, helping maintain compliance standards.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-compliance.html",
              "points": 1,
              "answers": [{"text": "Scan managed instances for patch and configuration compliance",
                           "is_correct": True,
                           },
                          {"text": "Monitor network security",
                           "is_correct": False},
                          {"text": "Manage user permissions",
                           "is_correct": False},
                          {"text": "Deploy applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides cost allocation tracking for AWS resources?",
              "explanation": "Cost allocation tags allow you to organize and track your AWS costs on a detailed level. When you apply tags to your resources, AWS generates a cost allocation report with your usage and costs grouped by your tags.",
              "reference": "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html",
              "points": 1,
              "answers": [{"text": "Cost allocation tags",
                           "is_correct": True},
                          {"text": "AWS Budgets",
                           "is_correct": False},
                          {"text": "Cost Explorer",
                           "is_correct": False},
                          {"text": "AWS Organizations",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for automating operational tasks?",
              "explanation": "Systems Manager Automation documents allow you to define the steps and parameters for automating common operational tasks like patching, AMI creation, and configuration changes.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-automation.html",
              "points": 1,
              "answers": [{"text": "Systems Manager Automation documents",
                           "is_correct": True},
                          {"text": "Manual scripts",
                           "is_correct": False},
                          {"text": "Third-party tools only",
                           "is_correct": False},
                          {"text": "Custom applications",
                           "is_correct": False},
                          ],
              },
             {"text": "Which CloudWatch feature allows you to set up notifications for specific log patterns?",
              "explanation": "CloudWatch Logs metric filters allow you to extract metrics from log data and set up alarms on those metrics, enabling notifications for specific log patterns.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html",
              "points": 1,
              "answers": [{"text": "CloudWatch Logs metric filters",
                           "is_correct": True},
                          {"text": "CloudWatch Alarms only",
                           "is_correct": False},
                          {"text": "CloudWatch Events",
                           "is_correct": False},
                          {"text": "CloudWatch Insights",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Organizations Service Control Policies (SCPs)?",
              "explanation": "Service Control Policies (SCPs) help you manage permissions in your organization by defining the maximum permissions for member accounts, providing centralized access control.",
              "reference": "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html",
              "points": 1,
              "answers": [{"text": "Define maximum permissions for member accounts",
                           "is_correct": True,
                           },
                          {"text": "Set billing limits",
                           "is_correct": False},
                          {"text": "Monitor resource usage",
                           "is_correct": False},
                          {"text": "Deploy resources automatically",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service helps you manage and distribute software packages to EC2 instances?",
              "explanation": "Systems Manager Distributor helps you package and distribute software to Systems Manager managed instances, providing a centralized way to manage software distribution.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/distributor.html",
              "points": 1,
              "answers": [{"text": "Systems Manager Distributor",
                           "is_correct": True},
                          {"text": "AWS CodeDeploy",
                           "is_correct": False},
                          {"text": "EC2 User Data",
                           "is_correct": False},
                          {"text": "Manual installation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for handling Auto Scaling instance warm-up?",
              "explanation": "Instance warm-up periods allow newly launched instances time to start contributing to metrics before being considered for scaling actions, preventing premature scaling decisions.",
              "reference": "https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-add-availability-zone.html",
              "points": 1,
              "answers": [{"text": "Configure appropriate warm-up periods for new instances",
                           "is_correct": True,
                           },
                          {"text": "Disable warm-up to scale faster",
                           "is_correct": False},
                          {"text": "Use maximum warm-up time always",
                           "is_correct": False},
                          {"text": "Warm-up is not configurable",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides network performance monitoring for VPC resources?",
              "explanation": "VPC Flow Logs capture information about IP traffic going to and from network interfaces in your VPC, enabling network performance monitoring and troubleshooting.",
              "reference": "https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html",
              "points": 1,
              "answers": [{"text": "VPC Flow Logs",
                           "is_correct": True},
                          {"text": "CloudWatch Network Metrics",
                           "is_correct": False},
                          {"text": "AWS X-Ray",
                           "is_correct": False},
                          {"text": "AWS Config",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Cost and Usage Reports?",
              "explanation": "AWS Cost and Usage Reports provide the most comprehensive set of AWS cost and usage data available, including additional metadata about AWS services, pricing, and reservations.",
              "reference": "https://docs.aws.amazon.com/cur/latest/userguide/what-is-cur.html",
              "points": 1,
              "answers": [{"text": "Provide comprehensive cost and usage data with metadata",
                           "is_correct": True,
                           },
                          {"text": "Set billing alerts",
                           "is_correct": False},
                          {"text": "Estimate future costs",
                           "is_correct": False},
                          {"text": "Manage resource tags",
                           "is_correct": False},
                          ],
              },
             {"text": "Which Systems Manager feature helps you remotely execute commands on managed instances?",
              "explanation": "Systems Manager Run Command lets you remotely and securely execute commands on your managed instances without SSH or RDP access.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/execute-remote-commands.html",
              "points": 1,
              "answers": [{"text": "Systems Manager Run Command",
                           "is_correct": True},
                          {"text": "Systems Manager Session Manager",
                           "is_correct": False},
                          {"text": "Systems Manager Patch Manager",
                           "is_correct": False},
                          {"text": "Systems Manager Automation",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for monitoring application dependencies?",
              "explanation": "AWS X-Ray provides end-to-end tracing to help you analyze and debug distributed applications, showing how requests flow through your application and its dependencies.",
              "reference": "https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html",
              "points": 1,
              "answers": [{"text": "AWS X-Ray for distributed tracing",
                           "is_correct": True},
                          {"text": "CloudWatch Logs only",
                           "is_correct": False},
                          {"text": "Manual monitoring",
                           "is_correct": False},
                          {"text": "Application-level logging only",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service helps you automate responses to CloudWatch alarms?",
              "explanation": "Amazon SNS can be triggered by CloudWatch alarms to send notifications, and can integrate with other services like Lambda or Systems Manager for automated responses.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/US_SetupSNS.html",
              "points": 1,
              "answers": [{"text": "Amazon SNS with Lambda or Systems Manager",
                           "is_correct": True},
                          {"text": "CloudWatch Events only",
                           "is_correct": False},
                          {"text": "Manual intervention",
                           "is_correct": False},
                          {"text": "Auto Scaling only",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of CloudWatch anomaly detection?",
              "explanation": "CloudWatch anomaly detection uses machine learning algorithms to continuously analyze system and application metrics, determine normal baselines, and surface anomalies with minimal user intervention.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detector.html",
              "points": 1,
              "answers": [{"text": "Use ML to detect unusual patterns in metrics automatically",
                           "is_correct": True,
                           },
                          {"text": "Replace manual threshold setting",
                           "is_correct": False},
                          {"text": "Reduce monitoring costs",
                           "is_correct": False},
                          {"text": "Generate detailed reports",
                           "is_correct": False},
                          ],
              },
             {"text": "Which feature helps you troubleshoot Auto Scaling activities?",
              "explanation": "Auto Scaling Activity History provides detailed information about scaling activities, including the reason for each scaling action and any errors that occurred.",
              "reference": "https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-verify-scaling-activity.html",
              "points": 1,
              "answers": [{"text": "Auto Scaling Activity History",
                           "is_correct": True},
                          {"text": "CloudWatch Logs",
                           "is_correct": False},
                          {"text": "AWS Config",
                           "is_correct": False},
                          {"text": "CloudTrail events",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for managing infrastructure as code?",
              "explanation": "AWS CloudFormation provides a common language to describe and provision all infrastructure resources in your AWS environment, enabling infrastructure as code practices.",
              "reference": "https://docs.aws.amazon.com/cloudformation/latest/userguide/Welcome.html",
              "points": 1,
              "answers": [{"text": "AWS CloudFormation templates",
                           "is_correct": True},
                          {"text": "Manual resource creation",
                           "is_correct": False},
                          {"text": "Scripts with AWS CLI",
                           "is_correct": False},
                          {"text": "Third-party tools only",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service provides centralized logging for multiple AWS accounts?",
              "explanation": "CloudWatch Logs with cross-account access allows you to centralize log data from multiple AWS accounts into a central logging account for unified monitoring and analysis.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CrossAccountSubscriptions.html",
              "points": 1,
              "answers": [{"text": "CloudWatch Logs with cross-account access",
                           "is_correct": True},
                          {"text": "AWS Config aggregator",
                           "is_correct": False},
                          {"text": "AWS Organizations",
                           "is_correct": False},
                          {"text": "AWS CloudTrail",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of AWS Resource Groups?",
              "explanation": "AWS Resource Groups help you organize your AWS resources and automate tasks on large numbers of resources at one time using tags and resource queries.",
              "reference": "https://docs.aws.amazon.com/ARG/latest/userguide/welcome.html",
              "points": 1,
              "answers": [{"text": "Organize and automate tasks on groups of resources",
                           "is_correct": True,
                           },
                          {"text": "Monitor resource performance",
                           "is_correct": False},
                          {"text": "Control resource access",
                           "is_correct": False},
                          {"text": "Backup resources",
                           "is_correct": False},
                          ],
              },
             {"text": "Which Systems Manager feature helps you manage configuration drift?",
              "explanation": "Systems Manager State Manager helps you define and maintain consistent OS configurations by automating the process of keeping your instances in a defined state.",
              "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-state.html",
              "points": 1,
              "answers": [{"text": "Systems Manager State Manager",
                           "is_correct": True},
                          {"text": "Systems Manager Compliance",
                           "is_correct": False},
                          {"text": "Systems Manager Inventory",
                           "is_correct": False},
                          {"text": "AWS Config",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the recommended approach for monitoring containerized applications?",
              "explanation": "Container Insights provides a comprehensive monitoring solution for containerized applications, collecting metrics and logs from containers, pods, and clusters.",
              "reference": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html",
              "points": 1,
              "answers": [{"text": "CloudWatch Container Insights",
                           "is_correct": True},
                          {"text": "Application logs only",
                           "is_correct": False},
                          {"text": "Host-level monitoring only",
                           "is_correct": False},
                          {"text": "Manual monitoring",
                           "is_correct": False},
                          ],
              },
             {"text": "Which service helps you implement disaster recovery automation?",
              "explanation": "AWS Backup provides centralized backup across AWS services and can be integrated with Systems Manager for automated disaster recovery procedures.",
              "reference": "https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html",
              "points": 1,
              "answers": [{"text": "AWS Backup with Systems Manager automation",
                           "is_correct": True},
                          {"text": "Manual backup procedures",
                           "is_correct": False},
                          {"text": "Application-level backups only",
                           "is_correct": False},
                          {"text": "Third-party backup tools only",
                           "is_correct": False},
                          ],
              },
             ]
