"""FastAPI Developer Certification"""

CERTIFICATION = {
    "name": "FastAPI Developer",
    "description": "FastAPI Web Framework Developer Certification",
    "slug": "fastapi-developer",
    "level": "Intermediate",
    "duration": 8,
    "questions_count": 50,
    "category_slug": "programming",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is FastAPI?",
        "explanation": "FastAPI is a modern, fast web framework for building APIs with Python 3.7+ based on standard Python type hints.",
        "reference": "https://fastapi.tiangolo.com/",
        "points": 1,
        "answers": [
            {"text": "A database ORM", "is_correct": False},
            {"text": "A web framework for APIs", "is_correct": True},
            {"text": "A frontend framework", "is_correct": False},
            {"text": "A testing library", "is_correct": False},
        ],
    },
    {
        "text": "Which decorator is used to create a GET endpoint in FastAPI?",
        "explanation": "The @app.get() decorator is used to create HTTP GET endpoints in FastAPI.",
        "reference": "https://fastapi.tiangolo.com/tutorial/first-steps/",
        "points": 1,
        "answers": [
            {"text": "@app.route()", "is_correct": False},
            {"text": "@app.get()", "is_correct": True},
            {"text": "@get()", "is_correct": False},
            {"text": "@endpoint()", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Pydantic in FastAPI?",
        "explanation": "Pydantic is used for data validation, serialization, and documentation generation using Python type annotations.",
        "reference": "https://fastapi.tiangolo.com/tutorial/body/",
        "points": 1,
        "answers": [
            {"text": "Database connection", "is_correct": False},
            {"text": "Data validation and serialization", "is_correct": True},
            {"text": "Authentication", "is_correct": False},
            {"text": "File handling", "is_correct": False},
        ],
    },
    {
        "text": "Which class should you inherit from to create a Pydantic model?",
        "explanation": "Pydantic models inherit from BaseModel to get validation and serialization capabilities.",
        "reference": "https://fastapi.tiangolo.com/tutorial/body/#create-your-data-model",
        "points": 1,
        "answers": [
            {"text": "Model", "is_correct": False},
            {"text": "BaseModel", "is_correct": True},
            {"text": "DataModel", "is_correct": False},
            {"text": "Schema", "is_correct": False},
        ],
    },
    {
        "text": "How do you create a POST endpoint in FastAPI?",
        "explanation": "Use the @app.post() decorator to create HTTP POST endpoints in FastAPI.",
        "reference": "https://fastapi.tiangolo.com/tutorial/body/",
        "points": 1,
        "answers": [
            {"text": "@app.post()", "is_correct": True},
            {"text": "@app.create()", "is_correct": False},
            {"text": "@post()", "is_correct": False},
            {"text": "@app.add()", "is_correct": False},
        ],
    },
    {
        "text": "What does FastAPI automatically generate based on your code?",
        "explanation": "FastAPI automatically generates interactive API documentation using Swagger UI and ReDoc based on your code and type hints.",
        "reference": "https://fastapi.tiangolo.com/tutorial/first-steps/#interactive-api-docs",
        "points": 1,
        "answers": [
            {"text": "Database schemas", "is_correct": False},
            {"text": "Interactive API documentation", "is_correct": True},
            {"text": "Frontend code", "is_correct": False},
            {"text": "Test cases", "is_correct": False},
        ],
    },
    {
        "text": "Which parameter type is used for path parameters in FastAPI?",
        "explanation": "Path parameters are defined as function parameters with type annotations, automatically extracted from the URL path.",
        "reference": "https://fastapi.tiangolo.com/tutorial/path-params/",
        "points": 1,
        "answers": [
            {"text": "Query parameters", "is_correct": False},
            {"text": "Function parameters", "is_correct": True},
            {"text": "Header parameters", "is_correct": False},
            {"text": "Body parameters", "is_correct": False},
        ],
    },
    {
        "text": "How do you define query parameters in FastAPI?",
        "explanation": "Query parameters are function parameters that are not part of the path parameters, automatically treated as query parameters.",
        "reference": "https://fastapi.tiangolo.com/tutorial/query-params/",
        "points": 1,
        "answers": [
            {"text": "Using Query() function", "is_correct": False},
            {"text": "As function parameters not in path", "is_correct": True},
            {"text": "In the decorator", "is_correct": False},
            {"text": "Using @query decorator", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the uvicorn server?",
        "explanation": "Uvicorn is an ASGI server used to run FastAPI applications in production and development.",
        "reference": "https://fastapi.tiangolo.com/tutorial/first-steps/#run-it",
        "points": 1,
        "answers": [
            {"text": "Database server", "is_correct": False},
            {"text": "ASGI server for FastAPI", "is_correct": True},
            {"text": "Frontend server", "is_correct": False},
            {"text": "Message queue", "is_correct": False},
        ],
    },
    {
        "text": "How do you handle request body data in FastAPI?",
        "explanation": "Request body data is handled using Pydantic models as function parameters, which FastAPI automatically validates and parses.",
        "reference": "https://fastapi.tiangolo.com/tutorial/body/",
        "points": 1,
        "answers": [
            {"text": "Using request.json()", "is_correct": False},
            {"text": "Using Pydantic models", "is_correct": True},
            {"text": "Using form data", "is_correct": False},
            {"text": "Manual parsing", "is_correct": False},
        ],
    },
    {
        "text": "Which decorator is used for PUT endpoints in FastAPI?",
        "explanation": "The @app.put() decorator is used to create HTTP PUT endpoints in FastAPI.",
        "reference": "https://fastapi.tiangolo.com/tutorial/",
        "points": 1,
        "answers": [
            {"text": "@app.update()", "is_correct": False},
            {"text": "@app.put()", "is_correct": True},
            {"text": "@app.modify()", "is_correct": False},
            {"text": "@put()", "is_correct": False},
        ],
    },
    {
        "text": "What is dependency injection in FastAPI?",
        "explanation": "Dependency injection is a system that allows you to declare dependencies that your path operations need, which FastAPI will automatically provide.",
        "reference": "https://fastapi.tiangolo.com/tutorial/dependencies/",
        "points": 1,
        "answers": [
            {"text": "A testing framework", "is_correct": False},
            {"text": "A system to provide required dependencies", "is_correct": True},
            {"text": "A database feature", "is_correct": False},
            {"text": "An authentication method", "is_correct": False},
        ],
    },
    {
        "text": "How do you use the Depends() function in FastAPI?",
        "explanation": "Depends() is used to declare dependencies in path operation parameters, which FastAPI will resolve and inject.",
        "reference": "https://fastapi.tiangolo.com/tutorial/dependencies/#first-steps",
        "points": 1,
        "answers": [
            {"text": "For database connections", "is_correct": False},
            {"text": "To declare function dependencies", "is_correct": True},
            {"text": "For error handling", "is_correct": False},
            {"text": "For validation", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of response models in FastAPI?",
        "explanation": "Response models define the shape and validation of response data, and are used for documentation and serialization.",
        "reference": "https://fastapi.tiangolo.com/tutorial/response-model/",
        "points": 1,
        "answers": [
            {"text": "Input validation", "is_correct": False},
            {"text": "Response shape and documentation", "is_correct": True},
            {"text": "Error handling", "is_correct": False},
            {"text": "Authentication", "is_correct": False},
        ],
    },
    {
        "text": "How do you specify a response model in FastAPI?",
        "explanation": "Use the response_model parameter in the path operation decorator to specify the response model.",
        "reference": "https://fastapi.tiangolo.com/tutorial/response-model/#response_model-parameter",
        "points": 1,
        "answers": [
            {"text": "In the function return type", "is_correct": False},
            {"text": "Using response_model parameter", "is_correct": True},
            {"text": "With @response decorator", "is_correct": False},
            {"text": "In the function body", "is_correct": False},
        ],
    },
    {
        "text": "What is the HTTPException class used for?",
        "explanation": "HTTPException is used to return HTTP error responses with specific status codes and details.",
        "reference": "https://fastapi.tiangolo.com/tutorial/handling-errors/",
        "points": 1,
        "answers": [
            {"text": "Logging errors", "is_correct": False},
            {"text": "Returning HTTP error responses", "is_correct": True},
            {"text": "Validating input", "is_correct": False},
            {"text": "Database errors", "is_correct": False},
        ],
    },
    {
        "text": "How do you handle file uploads in FastAPI?",
        "explanation": "Use the File() and UploadFile parameters to handle file uploads in FastAPI endpoints.",
        "reference": "https://fastapi.tiangolo.com/tutorial/request-files/",
        "points": 1,
        "answers": [
            {"text": "Using request.files", "is_correct": False},
            {"text": "Using File() and UploadFile", "is_correct": True},
            {"text": "Using form data", "is_correct": False},
            {"text": "Using JSON body", "is_correct": False},
        ],
    },
    {
        "text": "What is middleware in FastAPI?",
        "explanation": "Middleware is a function that works with every request before it is processed by any specific path operation and with every response before returning it.",
        "reference": "https://fastapi.tiangolo.com/tutorial/middleware/",
        "points": 1,
        "answers": [
            {"text": "Database layer", "is_correct": False},
            {"text": "Request/response processing layer", "is_correct": True},
            {"text": "Authentication system", "is_correct": False},
            {"text": "Validation layer", "is_correct": False},
        ],
    },
    {
        "text": "How do you add CORS support in FastAPI?",
        "explanation": "Use CORSMiddleware from fastapi.middleware.cors to add CORS support to your FastAPI application.",
        "reference": "https://fastapi.tiangolo.com/tutorial/cors/",
        "points": 1,
        "answers": [
            {"text": "Using @cors decorator", "is_correct": False},
            {"text": "Using CORSMiddleware", "is_correct": True},
            {"text": "In the response headers", "is_correct": False},
            {"text": "Using CORS() function", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of tags in FastAPI path operations?",
        "explanation": "Tags are used to group related path operations in the documentation and organize the API structure.",
        "reference": "https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#tags",
        "points": 1,
        "answers": [
            {"text": "For validation", "is_correct": False},
            {"text": "For grouping operations in docs", "is_correct": True},
            {"text": "For authentication", "is_correct": False},
            {"text": "For caching", "is_correct": False},
        ],
    },
    {
        "text": "How do you create a DELETE endpoint in FastAPI?",
        "explanation": "Use the @app.delete() decorator to create HTTP DELETE endpoints in FastAPI.",
        "reference": "https://fastapi.tiangolo.com/tutorial/",
        "points": 1,
        "answers": [
            {"text": "@app.remove()", "is_correct": False},
            {"text": "@app.delete()", "is_correct": True},
            {"text": "@delete()", "is_correct": False},
            {"text": "@app.destroy()", "is_correct": False},
        ],
    },
    {
        "text": "What is the Query() function used for in FastAPI?",
        "explanation": "Query() is used to add additional validation, metadata, and documentation for query parameters.",
        "reference": "https://fastapi.tiangolo.com/tutorial/query-params-str-validations/",
        "points": 1,
        "answers": [
            {"text": "Database queries", "is_correct": False},
            {"text": "Query parameter validation and metadata", "is_correct": True},
            {"text": "Path parameters", "is_correct": False},
            {"text": "Request body", "is_correct": False},
        ],
    },
    {
        "text": "How do you make a query parameter optional in FastAPI?",
        "explanation": "Query parameters can be made optional by providing a default value or using Optional type annotation.",
        "reference": "https://fastapi.tiangolo.com/tutorial/query-params/#optional-parameters",
        "points": 1,
        "answers": [
            {"text": "Using @optional decorator", "is_correct": False},
            {"text": "Providing a default value", "is_correct": True},
            {"text": "Using required=False", "is_correct": False},
            {"text": "Using Optional() function", "is_correct": False},
        ],
    },
    {
        "text": "What is the Path() function used for in FastAPI?",
        "explanation": "Path() is used to add validation, metadata, and documentation for path parameters.",
        "reference": "https://fastapi.tiangolo.com/tutorial/path-params-numeric-validations/",
        "points": 1,
        "answers": [
            {"text": "URL routing", "is_correct": False},
            {"text": "Path parameter validation and metadata", "is_correct": True},
            {"text": "File paths", "is_correct": False},
            {"text": "Query parameters", "is_correct": False},
        ],
    },
    {
        "text": "How do you handle form data in FastAPI?",
        "explanation": "Use Form() parameters to handle HTML form data (application/x-www-form-urlencoded) in FastAPI.",
        "reference": "https://fastapi.tiangolo.com/tutorial/request-forms/",
        "points": 1,
        "answers": [
            {"text": "Using JSON body", "is_correct": False},
            {"text": "Using Form() parameters", "is_correct": True},
            {"text": "Using Query() parameters", "is_correct": False},
            {"text": "Using Path() parameters", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of status codes in FastAPI responses?",
        "explanation": "Status codes indicate the result of the HTTP request (success, error, etc.) and are important for API communication.",
        "reference": "https://fastapi.tiangolo.com/tutorial/response-status-code/",
        "points": 1,
        "answers": [
            {"text": "Response formatting", "is_correct": False},
            {"text": "Indicating request result", "is_correct": True},
            {"text": "Authentication", "is_correct": False},
            {"text": "Data validation", "is_correct": False},
        ],
    },
    {
        "text": "How do you set a custom status code in FastAPI?",
        "explanation": "Use the status_code parameter in the path operation decorator to set a custom status code.",
        "reference": "https://fastapi.tiangolo.com/tutorial/response-status-code/#response-status-code",
        "points": 1,
        "answers": [
            {"text": "In the function body", "is_correct": False},
            {"text": "Using status_code parameter", "is_correct": True},
            {"text": "In the response model", "is_correct": False},
            {"text": "Using @status decorator", "is_correct": False},
        ],
    },
    {
        "text": "What is OAuth2 in the context of FastAPI?",
        "explanation": "OAuth2 is a security specification that FastAPI supports for authentication and authorization in APIs.",
        "reference": "https://fastapi.tiangolo.com/tutorial/security/",
        "points": 1,
        "answers": [
            {"text": "A database system", "is_correct": False},
            {"text": "A security specification for authentication", "is_correct": True},
            {"text": "A web framework", "is_correct": False},
            {"text": "A testing tool", "is_correct": False},
        ],
    },
    {
        "text": "How do you enable automatic API documentation in FastAPI?",
        "explanation": "FastAPI automatically generates API documentation; it's enabled by default and accessible at /docs and /redoc endpoints.",
        "reference": "https://fastapi.tiangolo.com/tutorial/first-steps/#interactive-api-docs",
        "points": 1,
        "answers": [
            {"text": "Using @docs decorator", "is_correct": False},
            {"text": "It's enabled by default", "is_correct": True},
            {"text": "Installing docs package", "is_correct": False},
            {"text": "Adding docs=True parameter", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between synchronous and asynchronous functions in FastAPI?",
        "explanation": "Async functions can handle concurrent requests more efficiently using async/await, while sync functions block during execution.",
        "reference": "https://fastapi.tiangolo.com/async/",
        "points": 1,
        "answers": [
            {"text": "No difference in FastAPI", "is_correct": False},
            {"text": "Async allows concurrent request handling", "is_correct": True},
            {"text": "Sync is faster", "is_correct": False},
            {"text": "Async is only for databases", "is_correct": False},
        ],
    },
    {
        "text": "How do you create an async endpoint in FastAPI?",
        "explanation": "Use the async keyword before the function definition to create an asynchronous endpoint.",
        "reference": "https://fastapi.tiangolo.com/async/#path-operation-functions",
        "points": 1,
        "answers": [
            {"text": "Using @async decorator", "is_correct": False},
            {"text": "Using async def", "is_correct": True},
            {"text": "Using asyncio parameter", "is_correct": False},
            {"text": "Using await keyword", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the Header() function in FastAPI?",
        "explanation": "Header() is used to extract and validate HTTP headers from incoming requests.",
        "reference": "https://fastapi.tiangolo.com/tutorial/header-params/",
        "points": 1,
        "answers": [
            {"text": "Setting response headers", "is_correct": False},
            {"text": "Extracting request headers", "is_correct": True},
            {"text": "HTML headers", "is_correct": False},
            {"text": "File headers", "is_correct": False},
        ],
    },
    {
        "text": "How do you handle cookies in FastAPI?",
        "explanation": "Use the Cookie() function to extract cookies from requests and Response.set_cookie() to set cookies.",
        "reference": "https://fastapi.tiangolo.com/tutorial/cookie-params/",
        "points": 1,
        "answers": [
            {"text": "Using request.cookies", "is_correct": False},
            {"text": "Using Cookie() function", "is_correct": True},
            {"text": "Using @cookie decorator", "is_correct": False},
            {"text": "Using session storage", "is_correct": False},
        ],
    },
    {
        "text": "What is Starlette in relation to FastAPI?",
        "explanation": "Starlette is the ASGI framework that FastAPI is built on top of, providing the core web functionality.",
        "reference": "https://fastapi.tiangolo.com/",
        "points": 1,
        "answers": [
            {"text": "A database ORM", "is_correct": False},
            {"text": "The underlying ASGI framework", "is_correct": True},
            {"text": "A testing library", "is_correct": False},
            {"text": "A documentation tool", "is_correct": False},
        ],
    },
    {
        "text": "How do you create sub-applications in FastAPI?",
        "explanation": "Use app.mount() to mount sub-applications or APIRouter to organize your application into modules.",
        "reference": "https://fastapi.tiangolo.com/tutorial/bigger-applications/",
        "points": 1,
        "answers": [
            {"text": "Using @subapp decorator", "is_correct": False},
            {"text": "Using app.mount() or APIRouter", "is_correct": True},
            {"text": "Using include() function", "is_correct": False},
            {"text": "Creating new FastAPI instances", "is_correct": False},
        ],
    },
    {
        "text": "What is the APIRouter class used for?",
        "explanation": "APIRouter is used to organize path operations into separate modules and include them in the main application.",
        "reference": "https://fastapi.tiangolo.com/tutorial/bigger-applications/#apirouter",
        "points": 1,
        "answers": [
            {"text": "Database routing", "is_correct": False},
            {"text": "Organizing path operations into modules", "is_correct": True},
            {"text": "URL redirection", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "How do you include an APIRouter in your main FastAPI app?",
        "explanation": "Use app.include_router() to include an APIRouter instance in your main FastAPI application.",
        "reference": "https://fastapi.tiangolo.com/tutorial/bigger-applications/#include-the-apirouters-for-users-and-items",
        "points": 1,
        "answers": [
            {"text": "app.add_router()", "is_correct": False},
            {"text": "app.include_router()", "is_correct": True},
            {"text": "app.mount_router()", "is_correct": False},
            {"text": "app.use_router()", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the summary parameter in path operations?",
        "explanation": "The summary parameter provides a short description for the path operation that appears in the API documentation.",
        "reference": "https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#summary-and-description",
        "points": 1,
        "answers": [
            {"text": "For logging", "is_correct": False},
            {"text": "Short description in API docs", "is_correct": True},
            {"text": "Function naming", "is_correct": False},
            {"text": "Error messages", "is_correct": False},
        ],
    },
    {
        "text": "How do you add description to a path operation in FastAPI?",
        "explanation": "Use the description parameter in the path operation decorator or add a docstring to the function.",
        "reference": "https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#description-from-docstring",
        "points": 1,
        "answers": [
            {"text": "Using @description decorator", "is_correct": False},
            {"text": "Using description parameter or docstring", "is_correct": True},
            {"text": "In the response model", "is_correct": False},
            {"text": "Using comments", "is_correct": False},
        ],
    },
    {
        "text": "What is the background tasks feature in FastAPI?",
        "explanation": "Background tasks allow you to run functions in the background after returning a response, useful for non-blocking operations.",
        "reference": "https://fastapi.tiangolo.com/tutorial/background-tasks/",
        "points": 1,
        "answers": [
            {"text": "Scheduled cron jobs", "is_correct": False},
            {"text": "Functions that run after response", "is_correct": True},
            {"text": "Database background jobs", "is_correct": False},
            {"text": "UI background processes", "is_correct": False},
        ],
    },
    {
        "text": "How do you add a background task in FastAPI?",
        "explanation": "Use BackgroundTasks parameter in your path operation function and call background_tasks.add_task().",
        "reference": "https://fastapi.tiangolo.com/tutorial/background-tasks/#using-backgroundtasks",
        "points": 1,
        "answers": [
            {"text": "Using @background decorator", "is_correct": False},
            {"text": "Using BackgroundTasks parameter", "is_correct": True},
            {"text": "Using asyncio.create_task()", "is_correct": False},
            {"text": "Using threading module", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Field() in Pydantic models?",
        "explanation": "Field() is used to add validation, metadata, and documentation to Pydantic model fields.",
        "reference": "https://fastapi.tiangolo.com/tutorial/schema-extra-example/#using-field-additional-arguments",
        "points": 1,
        "answers": [
            {"text": "Database field mapping", "is_correct": False},
            {"text": "Field validation and metadata", "is_correct": True},
            {"text": "Form field handling", "is_correct": False},
            {"text": "Response field filtering", "is_correct": False},
        ],
    },
    {
        "text": "How do you exclude fields from Pydantic model serialization?",
        "explanation": "Use the exclude parameter when calling .dict() or .json() methods, or use Field(exclude=True).",
        "reference": "https://pydantic-docs.helpmanual.io/usage/exporting_models/",
        "points": 1,
        "answers": [
            {"text": "Using @exclude decorator", "is_correct": False},
            {"text": "Using exclude parameter or Field(exclude=True)", "is_correct": True},
            {"text": "Using private fields", "is_correct": False},
            {"text": "Using underscore prefix", "is_correct": False},
        ],
    },
    {
        "text": "What is the WebSocket support in FastAPI?",
        "explanation": "FastAPI has built-in WebSocket support for real-time, bidirectional communication between client and server.",
        "reference": "https://fastapi.tiangolo.com/tutorial/websockets/",
        "points": 1,
        "answers": [
            {"text": "A third-party extension", "is_correct": False},
            {"text": "Built-in real-time communication", "is_correct": True},
            {"text": "A database feature", "is_correct": False},
            {"text": "An authentication method", "is_correct": False},
        ],
    },
    {
        "text": "How do you create a WebSocket endpoint in FastAPI?",
        "explanation": "Use the @app.websocket() decorator to create WebSocket endpoints in FastAPI.",
        "reference": "https://fastapi.tiangolo.com/tutorial/websockets/#create-a-websocket",
        "points": 1,
        "answers": [
            {"text": "@app.socket()", "is_correct": False},
            {"text": "@app.websocket()", "is_correct": True},
            {"text": "@websocket()", "is_correct": False},
            {"text": "@app.ws()", "is_correct": False},
        ],
    },
    {
        "text": "What is the testing support like in FastAPI?",
        "explanation": "FastAPI provides excellent testing support through TestClient, which uses the requests library for easy testing.",
        "reference": "https://fastapi.tiangolo.com/tutorial/testing/",
        "points": 1,
        "answers": [
            {"text": "No built-in testing support", "is_correct": False},
            {"text": "TestClient for easy testing", "is_correct": True},
            {"text": "Only unit testing", "is_correct": False},
            {"text": "External testing required", "is_correct": False},
        ],
    },
    {
        "text": "How do you test a FastAPI application?",
        "explanation": "Use TestClient from fastapi.testclient to test your FastAPI application like a regular requests client.",
        "reference": "https://fastapi.tiangolo.com/tutorial/testing/#using-testclient",
        "points": 1,
        "answers": [
            {"text": "Using unittest only", "is_correct": False},
            {"text": "Using TestClient", "is_correct": True},
            {"text": "Manual HTTP requests", "is_correct": False},
            {"text": "Using curl commands", "is_correct": False},
        ],
    },
    {
        "text": "What are the main advantages of using FastAPI?",
        "explanation": "FastAPI offers high performance, automatic documentation, type checking, easy testing, and modern Python features.",
        "reference": "https://fastapi.tiangolo.com/features/",
        "points": 1,
        "answers": [
            {"text": "Only fast performance", "is_correct": False},
            {"text": "Performance, docs, types, and testing", "is_correct": True},
            {"text": "Just automatic documentation", "is_correct": False},
            {"text": "Only async support", "is_correct": False},
        ],
    },
]