"""Node.js Developer Certification"""

CERTIFICATION = {
    "name": "Node.js Developer Certification",
    "description": "Server-side JavaScript with Node.js",
    "slug": "nodejs-developer-certification",
    "level": "Associate",
    "duration": 15,
    "questions_count": 60,
    "category_slug": "programming",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is Node.js?",
        "explanation": "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine that allows you to run JavaScript on the server-side, enabling full-stack JavaScript development.",
        "reference": "https://nodejs.org/en/about/",
        "points": 1,
        "answers": [
            {"text": "A JavaScript framework", "is_correct": False},
            {"text": "A JavaScript runtime environment", "is_correct": True},
            {"text": "A database management system", "is_correct": False},
            {"text": "A CSS preprocessor", "is_correct": False},
        ],
    },
    {
        "text": "What is npm in the Node.js ecosystem?",
        "explanation": "npm (Node Package Manager) is the default package manager for Node.js that allows you to install, manage, and share JavaScript packages and dependencies.",
        "reference": "https://docs.npmjs.com/about-npm",
        "points": 1,
        "answers": [
            {"text": "A debugging tool", "is_correct": False},
            {"text": "A package manager for JavaScript", "is_correct": True},
            {"text": "A testing framework", "is_correct": False},
            {"text": "A web server", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the require() function in Node.js?",
        "explanation": "The require() function is used to import modules, JSON files, and local files in Node.js applications. It follows the CommonJS module system.",
        "reference": "https://nodejs.org/api/modules.html",
        "points": 1,
        "answers": [
            {"text": "To create HTTP servers", "is_correct": False},
            {"text": "To import modules and files", "is_correct": True},
            {"text": "To handle asynchronous operations", "is_correct": False},
            {"text": "To manage memory allocation", "is_correct": False},
        ],
    },
    {
        "text": "What is Express.js?",
        "explanation": "Express.js is a minimal and flexible Node.js web application framework that provides a robust set of features for building web and mobile applications and APIs.",
        "reference": "https://expressjs.com/",
        "points": 1,
        "answers": [
            {"text": "A database ORM", "is_correct": False},
            {"text": "A web application framework for Node.js", "is_correct": True},
            {"text": "A frontend JavaScript library", "is_correct": False},
            {"text": "A CSS framework", "is_correct": False},
        ],
    },
    {
        "text": "What is the event loop in Node.js?",
        "explanation": "The event loop is what allows Node.js to perform non-blocking I/O operations by offloading operations to the system kernel whenever possible, making Node.js single-threaded but highly concurrent.",
        "reference": "https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/",
        "points": 1,
        "answers": [
            {"text": "A debugging mechanism", "is_correct": False},
            {
                "text": "A mechanism for handling asynchronous operations",
                "is_correct": True,
            },
            {"text": "A security feature", "is_correct": False},
            {"text": "A package management system", "is_correct": False},
        ],
    },
    {
        "text": "What is middleware in Express.js?",
        "explanation": "Middleware functions are functions that have access to the request object (req), response object (res), and the next middleware function in the request-response cycle, allowing you to execute code, modify requests/responses, and call the next middleware.",
        "reference": "https://expressjs.com/en/guide/using-middleware.html",
        "points": 1,
        "answers": [
            {"text": "A database query language", "is_correct": False},
            {"text": "A function with access to req, res, and next", "is_correct": True},
            {"text": "A built-in Node.js module", "is_correct": False},
            {"text": "A security protocol", "is_correct": False},
        ],
    },
    {
        "text": "What does 'callback hell' or 'pyramid of doom' refer to?",
        "explanation": "Callback hell refers to deeply nested callbacks in asynchronous JavaScript code, making it hard to read and maintain. It occurs when multiple callbacks are nested within each other.",
        "reference": "http://callbackhell.com/",
        "points": 1,
        "answers": [
            {"text": "An error in Node.js", "is_correct": False},
            {"text": "Deeply nested asynchronous callbacks", "is_correct": True},
            {"text": "A type of memory leak", "is_correct": False},
            {"text": "A security vulnerability", "is_correct": False},
        ],
    },
    {
        "text": "What is a Promise in JavaScript?",
        "explanation": "A Promise is an object representing the eventual completion or failure of an asynchronous operation and its resulting value. Promises provide a cleaner alternative to callbacks.",
        "reference": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
        "points": 1,
        "answers": [
            {"text": "A variable type", "is_correct": False},
            {"text": "An object representing eventual async operation completion", "is_correct": True},
            {"text": "A built-in database", "is_correct": False},
            {"text": "A security token", "is_correct": False},
        ],
    },
    {
        "text": "What is async/await?",
        "explanation": "Async/await is syntactic sugar built on top of Promises that makes asynchronous code look and behave more like synchronous code, improving readability and error handling.",
        "reference": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function",
        "points": 1,
        "answers": [
            {"text": "A debugging tool", "is_correct": False},
            {"text": "Syntax for working with Promises more easily", "is_correct": True},
            {"text": "A network protocol", "is_correct": False},
            {"text": "A database query method", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'path' module in Node.js?",
        "explanation": "The path module provides utilities for working with file and directory paths, offering methods to resolve, normalize, and manipulate file paths across different operating systems.",
        "reference": "https://nodejs.org/api/path.html",
        "points": 1,
        "answers": [
            {"text": "To handle HTTP requests", "is_correct": False},
            {"text": "To work with file and directory paths", "is_correct": True},
            {"text": "To manage database connections", "is_correct": False},
            {"text": "To process JSON files", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'fs' module in Node.js used for?",
        "explanation": "The fs (file system) module allows you to work with the file system, providing functions to read, write, update, and delete files and directories.",
        "reference": "https://nodejs.org/api/fs.html",
        "points": 1,
        "answers": [
            {"text": "To manage network connections", "is_correct": False},
            {"text": "To interact with the file system", "is_correct": True},
            {"text": "To handle HTTP requests", "is_correct": False},
            {"text": "To compress data", "is_correct": False},
        ],
    },
    {
        "text": "What is a stream in Node.js?",
        "explanation": "Streams are objects that allow you to read data from a source or write data to a destination in chunks, rather than loading the entire data into memory at once, improving performance for large files.",
        "reference": "https://nodejs.org/api/stream.html",
        "points": 1,
        "answers": [
            {"text": "A type of database", "is_correct": False},
            {"text": "Objects for reading/writing data in chunks", "is_correct": True},
            {"text": "A web server type", "is_correct": False},
            {"text": "A security feature", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'events' module in Node.js?",
        "explanation": "The events module allows you to create and work with custom events using the EventEmitter class, enabling event-driven architecture in Node.js applications.",
        "reference": "https://nodejs.org/api/events.html",
        "points": 1,
        "answers": [
            {"text": "A scheduling module", "is_correct": False},
            {"text": "A module for working with custom events", "is_correct": True},
            {"text": "A database management system", "is_correct": False},
            {"text": "A network protocol", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of package.json?",
        "explanation": "package.json is a manifest file that contains metadata about a Node.js project including dependencies, scripts, version, and other project configurations.",
        "reference": "https://docs.npmjs.com/cli/v8/configuring-npm/package-json",
        "points": 1,
        "answers": [
            {"text": "To store sensitive information", "is_correct": False},
            {"text": "To define project metadata and dependencies", "is_correct": True},
            {"text": "To configure the database", "is_correct": False},
            {"text": "To store user data", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between npm install and npm update?",
        "explanation": "npm install installs packages listed in package.json with their exact versions, while npm update upgrades packages to newer versions that satisfy the version constraints in package.json.",
        "reference": "https://docs.npmjs.com/cli/v8/commands/npm-install",
        "points": 1,
        "answers": [
            {"text": "Both commands do the same thing", "is_correct": False},
            {"text": "install uses exact versions, update upgrades packages", "is_correct": True},
            {"text": "update is faster than install", "is_correct": False},
            {"text": "install is only for new projects", "is_correct": False},
        ],
    },
    {
        "text": "What is a REST API?",
        "explanation": "REST (Representational State Transfer) is an architectural style for APIs that uses HTTP methods (GET, POST, PUT, DELETE) to perform operations on resources identified by URLs.",
        "reference": "https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm",
        "points": 1,
        "answers": [
            {"text": "A database query language", "is_correct": False},
            {"text": "An API architectural style using HTTP methods", "is_correct": True},
            {"text": "A security protocol", "is_correct": False},
            {"text": "A frontend framework", "is_correct": False},
        ],
    },
    {
        "text": "What is CORS in web development?",
        "explanation": "CORS (Cross-Origin Resource Sharing) is a mechanism that allows web pages to access resources from a different domain/origin using HTTP headers to control access.",
        "reference": "https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS",
        "points": 1,
        "answers": [
            {"text": "A database management system", "is_correct": False},
            {"text": "A mechanism for cross-origin resource sharing", "is_correct": True},
            {"text": "A type of encryption", "is_correct": False},
            {"text": "A package manager", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'http' module in Node.js?",
        "explanation": "The http module is a core Node.js module that provides utilities for creating HTTP servers and making HTTP requests, enabling web server development.",
        "reference": "https://nodejs.org/api/http.html",
        "points": 1,
        "answers": [
            {"text": "A package for managing dependencies", "is_correct": False},
            {"text": "A core module for creating HTTP servers", "is_correct": True},
            {"text": "A database connection module", "is_correct": False},
            {"text": "A security framework", "is_correct": False},
        ],
    },
    {
        "text": "What is a callback function?",
        "explanation": "A callback function is a function passed as an argument to another function, which is then invoked inside the outer function to complete some kind of routine or action.",
        "reference": "https://developer.mozilla.org/en-US/docs/Glossary/Callback_function",
        "points": 1,
        "answers": [
            {"text": "A return statement in a function", "is_correct": False},
            {"text": "A function passed as an argument to another function", "is_correct": True},
            {"text": "A loop construct", "is_correct": False},
            {"text": "A type of error handling", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'url' module used for in Node.js?",
        "explanation": "The url module provides utilities for URL resolution and parsing, helping you work with URLs by breaking them into their component parts.",
        "reference": "https://nodejs.org/api/url.html",
        "points": 1,
        "answers": [
            {"text": "To create HTTP requests", "is_correct": False},
            {"text": "To parse and work with URLs", "is_correct": True},
            {"text": "To manage file paths", "is_correct": False},
            {"text": "To handle database queries", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of environment variables?",
        "explanation": "Environment variables are variables that are set in the operating system and can be accessed by applications to store configuration values, API keys, and sensitive information outside of code.",
        "reference": "https://nodejs.org/en/learn/how-to-read-environment-variables-from-nodejs",
        "points": 1,
        "answers": [
            {"text": "To declare variables in code", "is_correct": False},
            {"text": "To store configuration and sensitive data outside code", "is_correct": True},
            {"text": "To manage package versions", "is_correct": False},
            {"text": "To handle HTTP requests", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'dotenv' package used for?",
        "explanation": "dotenv is a popular npm package that loads environment variables from a .env file into process.env, making it easy to manage configuration in development environments.",
        "reference": "https://www.npmjs.com/package/dotenv",
        "points": 1,
        "answers": [
            {"text": "To compress files", "is_correct": False},
            {"text": "To load environment variables from .env files", "is_correct": True},
            {"text": "To test code", "is_correct": False},
            {"text": "To manage database migrations", "is_correct": False},
        ],
    },
    {
        "text": "What is body parsing in Express.js?",
        "explanation": "Body parsing is the process of extracting and parsing the request body data (JSON, form data, etc.) from incoming HTTP requests, typically using middleware like express.json().",
        "reference": "https://expressjs.com/en/api/express.json.html",
        "points": 1,
        "answers": [
            {"text": "A security feature", "is_correct": False},
            {"text": "Extracting and parsing request body data", "is_correct": True},
            {"text": "Compressing response data", "is_correct": False},
            {"text": "A routing mechanism", "is_correct": False},
        ],
    },
    {
        "text": "What is routing in Express.js?",
        "explanation": "Routing refers to how an application responds to client requests for specific URLs and HTTP methods. Express allows you to define routes using methods like app.get(), app.post(), etc.",
        "reference": "https://expressjs.com/en/guide/routing.html",
        "points": 1,
        "answers": [
            {"text": "A database feature", "is_correct": False},
            {"text": "Mapping URLs to handler functions", "is_correct": True},
            {"text": "A network protocol", "is_correct": False},
            {"text": "A caching mechanism", "is_correct": False},
        ],
    },
    {
        "text": "What is a status code in HTTP?",
        "explanation": "HTTP status codes are three-digit numbers returned by servers to indicate the result of an HTTP request. For example, 200 means OK, 404 means Not Found, and 500 means Internal Server Error.",
        "reference": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
        "points": 1,
        "answers": [
            {"text": "A unique identifier for variables", "is_correct": False},
            {"text": "A three-digit number indicating HTTP request results", "is_correct": True},
            {"text": "A type of encryption", "is_correct": False},
            {"text": "A database query code", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of error handling middleware in Express?",
        "explanation": "Error handling middleware is used to catch and handle errors that occur during request processing. It typically has four parameters (err, req, res, next) and is defined after other middleware.",
        "reference": "https://expressjs.com/en/guide/error-handling.html",
        "points": 1,
        "answers": [
            {"text": "To optimize performance", "is_correct": False},
            {"text": "To catch and handle errors in requests", "is_correct": True},
            {"text": "To authenticate users", "is_correct": False},
            {"text": "To compress responses", "is_correct": False},
        ],
    },
    {
        "text": "What is JSON?",
        "explanation": "JSON (JavaScript Object Notation) is a lightweight data interchange format that uses human-readable text to store and exchange data, making it ideal for APIs and configuration files.",
        "reference": "https://www.json.org/",
        "points": 1,
        "answers": [
            {"text": "A programming language", "is_correct": False},
            {"text": "A lightweight data interchange format", "is_correct": True},
            {"text": "A database system", "is_correct": False},
            {"text": "A security protocol", "is_correct": False},
        ],
    },
    {
        "text": "What is JWT (JSON Web Token)?",
        "explanation": "JWT is a compact, self-contained token format used for securely transmitting information between parties as JSON. It's commonly used for authentication and authorization in APIs.",
        "reference": "https://jwt.io/",
        "points": 1,
        "answers": [
            {"text": "A database query language", "is_correct": False},
            {"text": "A token format for secure information transmission", "is_correct": True},
            {"text": "A web server", "is_correct": False},
            {"text": "A CSS framework", "is_correct": False},
        ],
    },
    {
        "text": "What is authentication?",
        "explanation": "Authentication is the process of verifying that a user is who they claim to be, typically by checking credentials like username and password.",
        "reference": "https://en.wikipedia.org/wiki/Authentication",
        "points": 1,
        "answers": [
            {"text": "Granting users permission to resources", "is_correct": False},
            {"text": "Verifying a user's identity", "is_correct": True},
            {"text": "Encrypting user data", "is_correct": False},
            {"text": "A type of database", "is_correct": False},
        ],
    },
    {
        "text": "What is authorization?",
        "explanation": "Authorization is the process of determining what authenticated users are allowed to do, such as accessing specific resources or performing certain actions.",
        "reference": "https://en.wikipedia.org/wiki/Authorization",
        "points": 1,
        "answers": [
            {"text": "Verifying a user's identity", "is_correct": False},
            {"text": "Determining what users are allowed to do", "is_correct": True},
            {"text": "Encrypting passwords", "is_correct": False},
            {"text": "A networking protocol", "is_correct": False},
        ],
    },
    {
        "text": "What is bcrypt used for?",
        "explanation": "bcrypt is a password hashing library that uses a strong hashing algorithm with salt to securely hash passwords, making them resistant to rainbow table and brute force attacks.",
        "reference": "https://www.npmjs.com/package/bcrypt",
        "points": 1,
        "answers": [
            {"text": "To encrypt data", "is_correct": False},
            {"text": "To securely hash passwords", "is_correct": True},
            {"text": "To manage files", "is_correct": False},
            {"text": "To create HTTP servers", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'querystring' module in Node.js?",
        "explanation": "The querystring module provides utilities for parsing and formatting URL query strings, allowing you to extract query parameters from URLs.",
        "reference": "https://nodejs.org/api/querystring.html",
        "points": 1,
        "answers": [
            {"text": "To handle HTTP methods", "is_correct": False},
            {"text": "To parse and format URL query strings", "is_correct": True},
            {"text": "To manage database queries", "is_correct": False},
            {"text": "To handle file uploads", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'cluster' module in Node.js?",
        "explanation": "The cluster module allows you to create child processes that run simultaneously, enabling you to utilize multi-core systems and improve application performance.",
        "reference": "https://nodejs.org/api/cluster.html",
        "points": 1,
        "answers": [
            {"text": "To manage file systems", "is_correct": False},
            {"text": "To create child processes for multi-core systems", "is_correct": True},
            {"text": "To handle HTTP requests", "is_correct": False},
            {"text": "To manage database connections", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'child_process' module in Node.js?",
        "explanation": "The child_process module allows you to create and manage child processes in Node.js, enabling you to spawn new Node.js processes or execute external commands.",
        "reference": "https://nodejs.org/api/child_process.html",
        "points": 1,
        "answers": [
            {"text": "To manage threads", "is_correct": False},
            {"text": "To create and manage child processes", "is_correct": True},
            {"text": "To handle network requests", "is_correct": False},
            {"text": "To manage file permissions", "is_correct": False},
        ],
    },
    {
        "text": "What is logging in Node.js?",
        "explanation": "Logging is the practice of recording application events and information to help with debugging, monitoring, and understanding application behavior. Common libraries include winston and morgan.",
        "reference": "https://nodejs.org/en/learn/nodejs-logging/",
        "points": 1,
        "answers": [
            {"text": "A debugging tool", "is_correct": False},
            {"text": "Recording application events and information", "is_correct": True},
            {"text": "A database feature", "is_correct": False},
            {"text": "A security mechanism", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'os' module in Node.js?",
        "explanation": "The os module provides operating system-related utility methods and properties, allowing you to access information about the operating system and hardware.",
        "reference": "https://nodejs.org/api/os.html",
        "points": 1,
        "answers": [
            {"text": "To manage file systems", "is_correct": False},
            {"text": "To access OS information and utilities", "is_correct": True},
            {"text": "To handle HTTP requests", "is_correct": False},
            {"text": "To manage databases", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'buffer' in Node.js?",
        "explanation": "A buffer is a fixed-size chunk of memory allocated in Node.js to handle raw binary data. Buffers are useful when working with streams, file systems, and network operations.",
        "reference": "https://nodejs.org/api/buffer.html",
        "points": 1,
        "answers": [
            {"text": "A temporary variable", "is_correct": False},
            {"text": "A fixed-size memory chunk for binary data", "is_correct": True},
            {"text": "A caching mechanism", "is_correct": False},
            {"text": "A database connection pool", "is_correct": False},
        ],
    },
    {
        "text": "What is session management in Node.js?",
        "explanation": "Session management is the process of tracking user interactions and storing session data on the server, typically using session IDs stored in cookies to maintain user state across requests.",
        "reference": "https://expressjs.com/en/resources/middleware/session.html",
        "points": 1,
        "answers": [
            {"text": "A security protocol", "is_correct": False},
            {"text": "Tracking user interactions and storing session data", "is_correct": True},
            {"text": "A database feature", "is_correct": False},
            {"text": "A network protocol", "is_correct": False},
        ],
    },
    {
        "text": "What is a cookie?",
        "explanation": "A cookie is a small piece of data stored on the client's browser that is sent with every HTTP request to the server, commonly used for authentication, preferences, and tracking.",
        "reference": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies",
        "points": 1,
        "answers": [
            {"text": "A server-side storage mechanism", "is_correct": False},
            {"text": "A small piece of data stored on the client browser", "is_correct": True},
            {"text": "A type of encryption", "is_correct": False},
            {"text": "A database record", "is_correct": False},
        ],
    },
    {
        "text": "What is validation in web development?",
        "explanation": "Validation is the process of checking that data meets specific criteria or format requirements before processing it, important for security and data integrity.",
        "reference": "https://owasp.org/www-community/attacks/xss/",
        "points": 1,
        "answers": [
            {"text": "A testing framework", "is_correct": False},
            {"text": "Checking that data meets specific criteria", "is_correct": True},
            {"text": "A caching mechanism", "is_correct": False},
            {"text": "A compression technique", "is_correct": False},
        ],
    },
    {
        "text": "What is SQL injection?",
        "explanation": "SQL injection is a security vulnerability where attackers insert malicious SQL code into input fields to manipulate database queries and access unauthorized data.",
        "reference": "https://owasp.org/www-community/attacks/SQL_Injection",
        "points": 1,
        "answers": [
            {"text": "A database optimization technique", "is_correct": False},
            {"text": "A security vulnerability involving malicious SQL code", "is_correct": True},
            {"text": "A query optimization method", "is_correct": False},
            {"text": "A type of database connection", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'crypto' module in Node.js?",
        "explanation": "The crypto module provides cryptographic functionality including hashing, encryption, decryption, and HMAC operations for securing sensitive data.",
        "reference": "https://nodejs.org/api/crypto.html",
        "points": 1,
        "answers": [
            {"text": "To manage files", "is_correct": False},
            {"text": "To provide cryptographic functionality", "is_correct": True},
            {"text": "To handle HTTP requests", "is_correct": False},
            {"text": "To manage database connections", "is_correct": False},
        ],
    },
    {
        "text": "What is API rate limiting?",
        "explanation": "Rate limiting is a technique that restricts the number of API requests a client can make within a specific time period, protecting servers from abuse and ensuring fair resource usage.",
        "reference": "https://en.wikipedia.org/wiki/Rate_limiting",
        "points": 1,
        "answers": [
            {"text": "A caching technique", "is_correct": False},
            {"text": "Restricting requests per time period to prevent abuse", "is_correct": True},
            {"text": "A compression method", "is_correct": False},
            {"text": "A database indexing technique", "is_correct": False},
        ],
    },
    {
        "text": "Explain the difference between 'throw' and returning an error in Node.js asynchronous operations. When should each be used?",
        "explanation": "In synchronous code, 'throw' immediately stops execution and raises an error. In asynchronous operations, throwing inside a callback may not be caught by try-catch blocks, potentially crashing the process. Instead, you should pass errors to callback functions or reject Promises. For Promises and async/await, throwing or rejecting will properly propagate errors.",
        "reference": "https://nodejs.org/en/docs/guides/nodejs-error-handling/",
        "points": 2,
        "answers": [
            {"text": "'throw' works the same in synchronous and asynchronous code", "is_correct": False},
            {"text": "Use 'throw' in sync code, pass errors to callbacks/reject Promises in async code", "is_correct": True},
            {"text": "Always use 'throw' for consistency", "is_correct": False},
            {"text": "'throw' cannot be used in asynchronous operations", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of using libuv in Node.js and how does it relate to the event loop architecture?",
        "explanation": "libuv is a C library that provides asynchronous I/O and the event loop implementation for Node.js. It abstracts platform-specific details and provides a cross-platform API for handling non-blocking I/O, timers, DNS resolution, and other async operations. The event loop built on libuv polls for I/O events and executes callbacks when operations complete.",
        "reference": "http://docs.libuv.org/v1.x/",
        "points": 2,
        "answers": [
            {"text": "A package manager for Node.js", "is_correct": False},
            {"text": "A C library providing async I/O and event loop implementation", "is_correct": True},
            {"text": "A JavaScript framework for building UIs", "is_correct": False},
            {"text": "A database connection pooler", "is_correct": False},
        ],
    },
    {
        "text": "Describe the execution order of JavaScript execution phases in the Node.js event loop and how setImmediate(), setTimeout(), and process.nextTick() differ.",
        "explanation": "The Node.js event loop has phases: timers (setTimeout/setInterval), pending callbacks, idle/prepare, poll (I/O events), check (setImmediate), and close callbacks. process.nextTick() runs before each phase transition and has highest priority. setImmediate() runs in the check phase. setTimeout() runs in the timers phase if the delay has elapsed. Understanding this is crucial for predicting execution order.",
        "reference": "https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/",
        "points": 2,
        "answers": [
            {"text": "All three execute at the same time in the same order", "is_correct": False},
            {"text": "process.nextTick() > setImmediate() > setTimeout(), each in different event loop phases", "is_correct": True},
            {"text": "setTimeout() always executes before process.nextTick()", "is_correct": False},
            {"text": "setImmediate() and setTimeout() are identical", "is_correct": False},
        ],
    },
    {
        "text": "What are the advantages and disadvantages of using Promises compared to callbacks, and how does async/await improve upon Promises?",
        "explanation": "Promises provide better error handling with .catch() and eliminate callback hell through chaining. However, they add abstraction overhead. Async/await improves upon Promises by providing synchronous-like syntax, making code more readable and easier to debug. Errors can be caught with try-catch blocks, and the code flow is more intuitive, especially with sequential asynchronous operations.",
        "reference": "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises",
        "points": 2,
        "answers": [
            {"text": "Promises are always faster and have no downsides", "is_correct": False},
            {"text": "Promises solve callback hell; async/await adds cleaner syntax and error handling", "is_correct": True},
            {"text": "Callbacks are better than Promises and async/await", "is_correct": False},
            {"text": "Async/await cannot handle errors like Promises can", "is_correct": False},
        ],
    },
    {
        "text": "Explain memory leaks in Node.js applications and identify common causes such as unreleased event listeners and circular references.",
        "explanation": "Memory leaks occur when objects are no longer needed but remain in memory, preventing garbage collection. Common causes include: unreleased event listeners (use removeListener()), circular object references, large caches without expiration, and global variables. Always remove listeners with off() or removeListener(), use WeakMap/WeakSet for caches, and monitor memory usage with tools like clinic.js or memlab.",
        "reference": "https://nodejs.org/en/docs/guides/simple-profiling/",
        "points": 2,
        "answers": [
            {"text": "Memory leaks are impossible in Node.js", "is_correct": False},
            {"text": "They occur from unreleased listeners, circular refs, and unbounded caches", "is_correct": True},
            {"text": "Only caused by external libraries", "is_correct": False},
            {"text": "Garbage collection prevents all memory leaks automatically", "is_correct": False},
        ],
    },
    {
        "text": "How do you implement proper connection pooling for database connections in Node.js, and why is it important?",
        "explanation": "Connection pooling maintains a pool of reusable database connections instead of creating new ones per request. This reduces overhead, improves performance, and prevents connection exhaustion. Libraries like 'pg' for PostgreSQL and 'mysql2' support pooling through Pool objects. Set appropriate pool size based on workload, configure timeouts, and always release connections back to the pool using try-finally or async resource cleanup.",
        "reference": "https://node-postgres.com/api/pool",
        "points": 2,
        "answers": [
            {"text": "Create a new connection for each request", "is_correct": False},
            {"text": "Maintain a reusable pool of connections to reduce overhead", "is_correct": True},
            {"text": "Connection pooling only works with NoSQL databases", "is_correct": False},
            {"text": "Pooling decreases performance", "is_correct": False},
        ],
    },
    {
        "text": "Describe the difference between Stream.pipe() and manual stream handling with 'data' and 'end' events. When would you use each approach?",
        "explanation": "pipe() automatically handles backpressure, manages internal buffers, and prevents memory overflow when source reads faster than destination can write. Manual event handling gives more control but requires implementing backpressure manually by checking writable.write() return values and pausing the readable stream when needed. Use pipe() for simple operations; use manual handling for complex transformations or when you need custom flow control.",
        "reference": "https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options",
        "points": 2,
        "answers": [
            {"text": "pipe() and manual events work identically", "is_correct": False},
            {"text": "pipe() handles backpressure automatically; manual requires custom backpressure logic", "is_correct": True},
            {"text": "Manual events are always better than pipe()", "is_correct": False},
            {"text": "pipe() cannot be used with file streams", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'module.exports' pattern and how does it differ from 'exports' in Node.js? Explain potential pitfalls.",
        "explanation": "'exports' is a reference to 'module.exports'. You can add properties to either, but assigning directly to 'exports' breaks the reference to 'module.exports'. For example, 'exports = {}' won't work as intended because it reassigns the exports variable without affecting module.exports. Always use 'module.exports' for reassigning the entire export object to avoid confusion and bugs.",
        "reference": "https://nodejs.org/api/modules.html#modules_exports",
        "points": 2,
        "answers": [
            {"text": "exports and module.exports are completely independent", "is_correct": False},
            {"text": "exports references module.exports; assigning to exports breaks the link", "is_correct": True},
            {"text": "Both always export the same thing regardless of usage", "is_correct": False},
            {"text": "module.exports is deprecated", "is_correct": False},
        ],
    },
    {
        "text": "Explain how middleware chains work in Express.js and what happens when you don't call next() in a middleware function.",
        "explanation": "Middleware functions form a chain where each middleware receives (req, res, next). Calling next() passes control to the next middleware. If next() isn't called, the chain halts and subsequent middleware won't execute. This is useful for stopping processing early (e.g., authentication failure). If you don't send a response and don't call next(), the request hangs indefinitely.",
        "reference": "https://expressjs.com/en/guide/using-middleware.html",
        "points": 2,
        "answers": [
            {"text": "All middleware executes regardless of next() calls", "is_correct": False},
            {"text": "Not calling next() stops the chain; request hangs if no response is sent", "is_correct": True},
            {"text": "next() is optional and doesn't affect execution", "is_correct": False},
            {"text": "Express automatically calls next() if you don't", "is_correct": False},
        ],
    },
    {
        "text": "How do you handle errors in Express.js middleware, and why is error-handling middleware different from regular middleware?",
        "explanation": "Error-handling middleware has four parameters: (err, req, res, next). It must be defined after all other middleware and route handlers. Express recognizes the 4-parameter signature and only calls it when an error is passed to next(err). Regular middleware has three parameters and won't catch errors. Errors can originate from synchronous code (use try-catch), async code (use Promise rejection), or by explicitly calling next(err).",
        "reference": "https://expressjs.com/en/guide/error-handling.html",
        "points": 2,
        "answers": [
            {"text": "Error handling middleware uses three parameters like regular middleware", "is_correct": False},
            {"text": "Error-handling middleware has four parameters and must be defined last", "is_correct": True},
            {"text": "Express automatically handles all errors without middleware", "is_correct": False},
            {"text": "Error handling middleware is optional", "is_correct": False},
        ],
    },
    {
        "text": "Describe the concept of 'clustering' in Node.js. How does the cluster module enable multi-core utilization and what are the communication mechanisms between master and worker processes?",
        "explanation": "The cluster module allows spawning multiple child processes (workers) to utilize multi-core systems. The master process manages workers using cluster.fork(). Each worker runs the same Node.js code but is a separate process with its own event loop. Communication happens through IPC (Inter-Process Communication) using process.send() and process.on('message'). This enables load distribution across cores and better performance.",
        "reference": "https://nodejs.org/api/cluster.html",
        "points": 2,
        "answers": [
            {"text": "Clustering uses threads, not processes", "is_correct": False},
            {"text": "Cluster module spawns child processes and uses IPC for communication", "is_correct": True},
            {"text": "Clustering doesn't improve performance", "is_correct": False},
            {"text": "Node.js automatically clusters across all cores", "is_correct": False},
        ],
    },
    {
        "text": "Explain the differences between 'require()' and 'import/export' (ES6 modules). Why is Node.js moving towards ES6 modules and what are the compatibility considerations?",
        "explanation": "require() is CommonJS (synchronous) while import/export are ES6 modules (can be asynchronous). ES6 modules provide better tree-shaking, cleaner syntax, and static analysis. Node.js supports both: .js files use CommonJS by default, but .mjs files or 'type: module' in package.json enable ES6. Mixing them requires careful handling of top-level await and dual package publishing.",
        "reference": "https://nodejs.org/api/esm.html",
        "points": 2,
        "answers": [
            {"text": "require() and import are completely identical", "is_correct": False},
            {"text": "require() is CommonJS; import/export are ES6 modules with better features", "is_correct": True},
            {"text": "ES6 modules are deprecated in Node.js", "is_correct": False},
            {"text": "import/export are slower than require()", "is_correct": False},
        ],
    },
    {
        "text": "How do you implement graceful shutdown in a Node.js application? Why is this important and what resources must be properly closed?",
        "explanation": "Graceful shutdown involves listening for signals (SIGTERM, SIGINT) and stopping accepting new requests while completing in-flight ones. Close server with server.close(), terminate database connections, finish pending operations, and exit process. Important for zero-downtime deployments and preventing data corruption. Use libraries like 'lc' or implement manually with proper timeout handling.",
        "reference": "https://nodejs.org/en/docs/guides/nodejs-docker-webapp/",
        "points": 2,
        "answers": [
            {"text": "Immediate process termination is always fine", "is_correct": False},
            {"text": "Graceful shutdown completes in-flight requests and closes resources properly", "is_correct": True},
            {"text": "Shutdown is handled automatically by Node.js", "is_correct": False},
            {"text": "Graceful shutdown slows down application performance", "is_correct": False},
        ],
    },
    {
        "text": "Explain the concept of 'transpilation' in Node.js development. How does Babel enable using modern JavaScript features in older Node.js versions?",
        "explanation": "Transpilation converts modern JavaScript (ES2020+) into older, compatible JavaScript syntax. Babel is a transpiler that reads modern code and outputs ES5/ES6 compatible code that runs on older Node.js versions. It uses plugins and presets to target specific features. While Node.js now supports most modern features, Babel is useful for supporting older versions or using experimental features.",
        "reference": "https://babeljs.io/",
        "points": 2,
        "answers": [
            {"text": "Transpilation is only used in frontend development", "is_correct": False},
            {"text": "Babel converts modern JS to compatible syntax for older Node versions", "is_correct": True},
            {"text": "Transpilation makes code run slower", "is_correct": False},
            {"text": "Modern Node.js versions don't need transpilation", "is_correct": False},
        ],
    },
    {
        "text": "Describe the concept of 'dependency injection' in Node.js and how it improves testability and maintainability of code.",
        "explanation": "Dependency injection passes dependencies (objects, functions) to modules rather than having modules create them internally. This decouples components, improves testability by allowing mock dependencies, and simplifies configuration changes. In Node.js, you can implement DI manually by passing dependencies as parameters or use frameworks like 'inversify' for more complex setups.",
        "reference": "https://en.wikipedia.org/wiki/Dependency_injection",
        "points": 2,
        "answers": [
            {"text": "Dependency injection creates dependencies within modules", "is_correct": False},
            {"text": "DI passes dependencies to modules for loose coupling and better testability", "is_correct": True},
            {"text": "Dependency injection only works with TypeScript", "is_correct": False},
            {"text": "DI decreases code flexibility", "is_correct": False},
        ],
    },
    {
        "text": "How do you optimize Node.js application performance? Discuss caching strategies, profiling tools, and common bottlenecks.",
        "explanation": "Optimize with: caching (Redis, in-memory), lazy loading, code profiling (clinic.js, node --prof), database indexing, and connection pooling. Use load testing to identify bottlenecks. Monitor with tools like PM2, New Relic, or Datadog. Common bottlenecks are: blocking synchronous operations, N+1 queries, memory leaks, and inefficient loops. Use async patterns and streams for large data processing.",
        "reference": "https://nodejs.org/en/docs/guides/simple-profiling/",
        "points": 2,
        "answers": [
            {"text": "Node.js applications are always fast by default", "is_correct": False},
            {"text": "Optimize with caching, profiling, pooling, and monitoring tools", "is_correct": True},
            {"text": "Performance optimization is only for production", "is_correct": False},
            {"text": "Synchronous operations don't impact performance", "is_correct": False},
        ],
    },
    {
        "text": "Explain the differences between 'horizontal' and 'vertical' scaling in Node.js deployments and when to use each approach.",
        "explanation": "Vertical scaling adds resources to a single machine (more CPU, RAM). Horizontal scaling adds more machines/instances. Node.js is single-threaded, making horizontal scaling more effective. Vertical scaling is simpler but has hardware limits. Horizontal scaling requires load balancing, distributed caching, and session management. Modern deployments use both: vertical for single-instance optimization, horizontal for redundancy and handling traffic spikes.",
        "reference": "https://nodejs.org/en/docs/guides/nodejs-docker-webapp/",
        "points": 2,
        "answers": [
            {"text": "Vertical and horizontal scaling are the same thing", "is_correct": False},
            {"text": "Vertical adds resources to one machine; horizontal adds machines via load balancing", "is_correct": True},
            {"text": "Horizontal scaling is always better than vertical", "is_correct": False},
            {"text": "Node.js can only be scaled vertically", "is_correct": False},
        ],
    },
    {
        "text": "How do you implement authentication using JWT (JSON Web Tokens) in a Node.js application? Discuss token creation, validation, and refresh token mechanisms.",
        "explanation": "JWT consists of header.payload.signature. Create JWTs using jsonwebtoken library with a secret key. Validation involves verifying the signature and checking expiration. Access tokens are short-lived; refresh tokens are long-lived and used to get new access tokens without re-authenticating. Store refresh tokens securely (HttpOnly cookies or database) and access tokens in memory. Implement token rotation and blacklisting for security.",
        "reference": "https://tools.ietf.org/html/rfc7519",
        "points": 2,
        "answers": [
            {"text": "JWT tokens never expire", "is_correct": False},
            {"text": "Create short-lived access tokens and long-lived refresh tokens with rotation", "is_correct": True},
            {"text": "JWTs should always be stored in localStorage", "is_correct": False},
            {"text": "Token validation is optional", "is_correct": False},
        ],
    },
    {
        "text": "Describe the purpose and implementation of the 'observer pattern' in Node.js using EventEmitter. Provide use cases and potential pitfalls.",
        "explanation": "The observer pattern implements publish-subscribe behavior using EventEmitter. Objects emit events, and listeners subscribe to them. Useful for decoupling components and handling state changes. Create custom EventEmitter subclasses or use the built-in events module. Pitfalls: unbounded listeners cause memory leaks (remove with off()), listeners execute synchronously, and errors in listeners crash the program if not handled.",
        "reference": "https://nodejs.org/api/events.html",
        "points": 2,
        "answers": [
            {"text": "EventEmitter is only for framework development", "is_correct": False},
            {"text": "Observer pattern uses EventEmitter for publish-subscribe and state changes", "is_correct": True},
            {"text": "EventEmitter automatically cleans up listeners", "is_correct": False},
            {"text": "Observer pattern cannot be implemented in Node.js", "is_correct": False},
        ],
    },
    {
        "text": "How do you handle file uploads in a Node.js/Express application? Discuss multipart form data, streaming, and file validation.",
        "explanation": "Use middleware like 'multer' to parse multipart/form-data. Stream uploads directly to storage (disk, S3) to save memory. Validate file type, size, and content before processing. Implement virus scanning for security. Use destination and filename options in multer to control file placement. Handle errors properly (disk full, permission issues). For large files, use resumable upload libraries or cloud storage APIs.",
        "reference": "https://www.npmjs.com/package/multer",
        "points": 2,
        "answers": [
            {"text": "Load entire files into memory before processing", "is_correct": False},
            {"text": "Use multer middleware to stream uploads with proper validation", "is_correct": True},
            {"text": "File uploads don't need validation", "is_correct": False},
            {"text": "Express handles file uploads automatically", "is_correct": False},
        ],
    },
]
