"""SQL Advanced Certification"""

CERTIFICATION = {
    "name": "SQL Advanced",
    "description": "Advanced SQL Database Programming and Optimization",
    "slug": "sql-advanced",
    "level": "Advanced",
    "duration": 25,
    "questions_count": 70,
    "category_slug": "programming",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is a CTE (Common Table Expression)?",
        "explanation": """A CTE is a temporary named result set that exists within the scope of a single SQL statement. It improves readability and can be referenced multiple times.""",
        "reference": "https://www.postgresql.org/docs/current/queries-with.html",
        "points": 1,
        "answers": [
            {"text": "A temporary named result set defined using WITH clause", "is_correct": True},
            {"text": "A permanent table stored in database", "is_correct": False},
            {"text": "A type of index", "is_correct": False},
            {"text": "A database trigger", "is_correct": False},
        ],
    },
    {
        "text": "Which window function calculates a running total?",
        "explanation": """SUM() OVER (ORDER BY column) creates a running total. Window functions perform calculations across related rows without grouping them.""",
        "reference": "https://www.postgresql.org/docs/current/tutorial-window.html",
        "points": 1,
        "answers": [
            {"text": "SUM() OVER (ORDER BY column)", "is_correct": True},
            {"text": "RUNNING_SUM()", "is_correct": False},
            {"text": "CUMULATIVE_SUM()", "is_correct": False},
            {"text": "AGGREGATE(SUM)", "is_correct": False},
        ],
    },
    {
        "text": "What does PARTITION BY do in a window function?",
        "explanation": """PARTITION BY divides rows into partitions, applying the window function separately to each partition. It's like GROUP BY but doesn't collapse rows.""",
        "reference": "https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS",
        "points": 1,
        "answers": [
            {"text": "Divides rows into separate groups for window function calculations", "is_correct": True},
            {"text": "Creates table partitions", "is_correct": False},
            {"text": "Splits database into shards", "is_correct": False},
            {"text": "Filters rows by condition", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between RANK() and DENSE_RANK()?",
        "explanation": """RANK() leaves gaps after ties (1,2,2,4), while DENSE_RANK() doesn't leave gaps (1,2,2,3). Both assign ranks based on ORDER BY.""",
        "reference": "https://www.postgresql.org/docs/current/functions-window.html",
        "points": 1,
        "answers": [
            {"text": "RANK() leaves gaps after ties, DENSE_RANK() doesn't", "is_correct": True},
            {"text": "RANK() is faster than DENSE_RANK()", "is_correct": False},
            {"text": "DENSE_RANK() only works with numbers", "is_correct": False},
            {"text": "They are identical functions", "is_correct": False},
        ],
    },
    {
        "text": "What does ROW_NUMBER() window function do?",
        "explanation": """ROW_NUMBER() assigns a unique sequential integer to each row within a partition, starting from 1. Unlike RANK(), it doesn't handle ties.""",
        "reference": "https://www.postgresql.org/docs/current/functions-window.html",
        "points": 1,
        "answers": [
            {"text": "Assigns unique sequential numbers to rows", "is_correct": True},
            {"text": "Counts total rows in table", "is_correct": False},
            {"text": "Returns the primary key", "is_correct": False},
            {"text": "Generates random numbers", "is_correct": False},
        ],
    },
    {
        "text": "What is a recursive CTE used for?",
        "explanation": """Recursive CTEs reference themselves and are ideal for hierarchical data like org charts, file systems, or graphs. Uses UNION ALL with base and recursive cases.""",
        "reference": "https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE",
        "points": 1,
        "answers": [
            {"text": "Querying hierarchical or tree-structured data", "is_correct": True},
            {"text": "Creating infinite loops", "is_correct": False},
            {"text": "Optimizing simple SELECT queries", "is_correct": False},
            {"text": "Encrypting data", "is_correct": False},
        ],
    },
    {
        "text": "What does LEAD() window function do?",
        "explanation": """LEAD() accesses data from a subsequent row in the result set. LEAD(column, n) gets the value from n rows ahead. Useful for comparisons.""",
        "reference": "https://www.postgresql.org/docs/current/functions-window.html",
        "points": 1,
        "answers": [
            {"text": "Accesses data from the next row", "is_correct": True},
            {"text": "Accesses data from the previous row", "is_correct": False},
            {"text": "Calculates the first row value", "is_correct": False},
            {"text": "Sorts rows in descending order", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of EXPLAIN ANALYZE?",
        "explanation": """EXPLAIN ANALYZE executes the query and shows actual execution times and row counts, helping identify performance bottlenecks and optimization opportunities.""",
        "reference": "https://www.postgresql.org/docs/current/sql-explain.html",
        "points": 1,
        "answers": [
            {"text": "Shows query execution plan with actual runtime statistics", "is_correct": True},
            {"text": "Validates SQL syntax", "is_correct": False},
            {"text": "Creates database documentation", "is_correct": False},
            {"text": "Backs up query results", "is_correct": False},
        ],
    },
    {
        "text": "What is a materialized view?",
        "explanation": """A materialized view stores query results physically, unlike regular views. Must be refreshed to update data. Improves performance for complex queries.""",
        "reference": "https://www.postgresql.org/docs/current/sql-creatematerializedview.html",
        "points": 1,
        "answers": [
            {"text": "A view that stores query results physically", "is_correct": True},
            {"text": "A view that updates automatically", "is_correct": False},
            {"text": "A temporary table", "is_correct": False},
            {"text": "A read-only table", "is_correct": False},
        ],
    },
    {
        "text": "What does COALESCE() function do?",
        "explanation": """COALESCE() returns the first non-NULL value from its arguments. Useful for providing default values: COALESCE(column, 'default').""",
        "reference": "https://www.postgresql.org/docs/current/functions-conditional.html",
        "points": 1,
        "answers": [
            {"text": "Returns the first non-NULL value from arguments", "is_correct": True},
            {"text": "Combines multiple strings", "is_correct": False},
            {"text": "Removes NULL values from table", "is_correct": False},
            {"text": "Converts data types", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between UNION and UNION ALL?",
        "explanation": """UNION removes duplicate rows and sorts results, while UNION ALL keeps all rows including duplicates. UNION ALL is faster as it skips deduplication.""",
        "reference": "https://www.postgresql.org/docs/current/queries-union.html",
        "points": 1,
        "answers": [
            {"text": "UNION removes duplicates, UNION ALL keeps them", "is_correct": True},
            {"text": "UNION ALL removes duplicates, UNION keeps them", "is_correct": False},
            {"text": "They are identical", "is_correct": False},
            {"text": "UNION works only with numbers", "is_correct": False},
        ],
    },
    {
        "text": "What is a CROSS JOIN?",
        "explanation": """CROSS JOIN produces a Cartesian product of two tables - every row from first table paired with every row from second table. Can generate large result sets.""",
        "reference": "https://www.postgresql.org/docs/current/queries-table-expressions.html",
        "points": 1,
        "answers": [
            {"text": "Returns Cartesian product of two tables", "is_correct": True},
            {"text": "Returns only matching rows", "is_correct": False},
            {"text": "Returns rows with NULL values", "is_correct": False},
            {"text": "Returns first 10 rows", "is_correct": False},
        ],
    },
    {
        "text": "What does the HAVING clause do?",
        "explanation": """HAVING filters grouped results after GROUP BY, while WHERE filters before grouping. HAVING can use aggregate functions like COUNT, SUM.""",
        "reference": "https://www.postgresql.org/docs/current/tutorial-agg.html",
        "points": 1,
        "answers": [
            {"text": "Filters grouped results after aggregation", "is_correct": True},
            {"text": "Filters rows before grouping", "is_correct": False},
            {"text": "Sorts query results", "is_correct": False},
            {"text": "Creates table constraints", "is_correct": False},
        ],
    },
    {
        "text": "What is a self-join?",
        "explanation": """A self-join joins a table to itself, useful for comparing rows within the same table. Requires table aliases to distinguish between instances.""",
        "reference": "https://www.postgresql.org/docs/current/tutorial-join.html",
        "points": 1,
        "answers": [
            {"text": "A join where table is joined to itself", "is_correct": True},
            {"text": "A join that returns only unique values", "is_correct": False},
            {"text": "An automatic join created by database", "is_correct": False},
            {"text": "A join between primary and foreign keys", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of NULLIF() function?",
        "explanation": """NULLIF(value1, value2) returns NULL if both values are equal, otherwise returns value1. Useful for avoiding division by zero or handling special values.""",
        "reference": "https://www.postgresql.org/docs/current/functions-conditional.html",
        "points": 1,
        "answers": [
            {"text": "Returns NULL if two values are equal", "is_correct": True},
            {"text": "Removes NULL values", "is_correct": False},
            {"text": "Converts NULL to zero", "is_correct": False},
            {"text": "Checks if value is NULL", "is_correct": False},
        ],
    },
    {
        "text": "What does LATERAL join allow?",
        "explanation": """LATERAL allows subqueries to reference columns from preceding tables in the FROM clause. Enables row-by-row processing and dependent subqueries.""",
        "reference": "https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-LATERAL",
        "points": 1,
        "answers": [
            {"text": "Subqueries to reference columns from preceding tables", "is_correct": True},
            {"text": "Horizontal table partitioning", "is_correct": False},
            {"text": "Parallel query execution", "is_correct": False},
            {"text": "Automatic index creation", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between DELETE and TRUNCATE?",
        "explanation": """DELETE removes rows one by one and can be rolled back, while TRUNCATE is faster, removes all rows at once, resets identity counters, and uses less transaction log.""",
        "reference": "https://www.postgresql.org/docs/current/sql-truncate.html",
        "points": 1,
        "answers": [
            {"text": "DELETE is row-by-row, TRUNCATE removes all rows quickly", "is_correct": True},
            {"text": "They are identical operations", "is_correct": False},
            {"text": "TRUNCATE can be rolled back, DELETE cannot", "is_correct": False},
            {"text": "DELETE is faster than TRUNCATE", "is_correct": False},
        ],
    },
    {
        "text": "What does DISTINCT ON do in PostgreSQL?",
        "explanation": """DISTINCT ON(columns) returns only the first row for each unique combination of specified columns. Useful for getting unique records based on certain fields.""",
        "reference": "https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT",
        "points": 1,
        "answers": [
            {"text": "Returns first row for each unique value of specified columns", "is_correct": True},
            {"text": "Removes all duplicate rows", "is_correct": False},
            {"text": "Counts distinct values", "is_correct": False},
            {"text": "Creates unique constraint", "is_correct": False},
        ],
    },
    {
        "text": "What is a covering index?",
        "explanation": """A covering index includes all columns needed by a query, allowing the database to satisfy the query entirely from the index without accessing the table.""",
        "reference": "https://www.postgresql.org/docs/current/indexes-index-only-scans.html",
        "points": 1,
        "answers": [
            {"text": "An index containing all columns needed by a query", "is_correct": True},
            {"text": "An index on every column", "is_correct": False},
            {"text": "An index that hides data", "is_correct": False},
            {"text": "A primary key index", "is_correct": False},
        ],
    },
    {
        "text": "What does the USING clause do in joins?",
        "explanation": """USING(column) simplifies joins when both tables have identically named columns. Equivalent to ON table1.column = table2.column but cleaner.""",
        "reference": "https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-JOIN",
        "points": 1,
        "answers": [
            {"text": "Simplifies joins on columns with same name", "is_correct": True},
            {"text": "Specifies which table to use", "is_correct": False},
            {"text": "Defines table aliases", "is_correct": False},
            {"text": "Sets join order", "is_correct": False},
        ],
    },
    {
        "text": "What is a partial index?",
        "explanation": """A partial index is built on a subset of table rows matching a WHERE condition. Reduces index size and improves performance for queries on that subset.""",
        "reference": "https://www.postgresql.org/docs/current/indexes-partial.html",
        "points": 1,
        "answers": [
            {"text": "An index on a subset of rows matching a condition", "is_correct": True},
            {"text": "An incomplete or corrupted index", "is_correct": False},
            {"text": "An index on part of a column", "is_correct": False},
            {"text": "A temporary index", "is_correct": False},
        ],
    },
    {
        "text": "What does the OVER() clause define in window functions?",
        "explanation": """OVER() defines the window frame for window functions, including partitioning (PARTITION BY), ordering (ORDER BY), and frame bounds (ROWS/RANGE).""",
        "reference": "https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS",
        "points": 1,
        "answers": [
            {"text": "The window frame for calculations", "is_correct": True},
            {"text": "Query timeout limit", "is_correct": False},
            {"text": "Maximum result rows", "is_correct": False},
            {"text": "Transaction isolation level", "is_correct": False},
        ],
    },
    {
        "text": "What is UPSERT in PostgreSQL?",
        "explanation": """UPSERT (INSERT ... ON CONFLICT) inserts a row or updates it if a conflict occurs. Combines INSERT and UPDATE in one atomic operation.""",
        "reference": "https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT",
        "points": 1,
        "answers": [
            {"text": "INSERT with UPDATE on conflict (INSERT ... ON CONFLICT)", "is_correct": True},
            {"text": "UPDATE with INSERT fallback", "is_correct": False},
            {"text": "A stored procedure", "is_correct": False},
            {"text": "A type of trigger", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between INNER JOIN and OUTER JOIN?",
        "explanation": """INNER JOIN returns only matching rows from both tables. OUTER JOIN (LEFT/RIGHT/FULL) returns matching rows plus unmatched rows from one or both tables with NULLs.""",
        "reference": "https://www.postgresql.org/docs/current/tutorial-join.html",
        "points": 1,
        "answers": [
            {"text": "INNER returns matches only, OUTER includes unmatched rows", "is_correct": True},
            {"text": "They are the same", "is_correct": False},
            {"text": "OUTER JOIN is faster", "is_correct": False},
            {"text": "INNER JOIN includes NULL values", "is_correct": False},
        ],
    },
    {
        "text": "What does VACUUM do in PostgreSQL?",
        "explanation": """VACUUM reclaims storage by removing dead tuples from updates/deletes, prevents transaction ID wraparound, and updates statistics. VACUUM FULL rewrites entire table.""",
        "reference": "https://www.postgresql.org/docs/current/sql-vacuum.html",
        "points": 1,
        "answers": [
            {"text": "Reclaims storage and maintains database health", "is_correct": True},
            {"text": "Backs up the database", "is_correct": False},
            {"text": "Defragments hard drive", "is_correct": False},
            {"text": "Compresses data files", "is_correct": False},
        ],
    },
    {
        "text": "What is a composite index?",
        "explanation": """A composite index includes multiple columns. Query performance depends on column order - leftmost columns must be used for index to be effective.""",
        "reference": "https://www.postgresql.org/docs/current/indexes-multicolumn.html",
        "points": 1,
        "answers": [
            {"text": "An index on multiple columns", "is_correct": True},
            {"text": "Multiple indexes on one column", "is_correct": False},
            {"text": "An index combining multiple tables", "is_correct": False},
            {"text": "A virtual index", "is_correct": False},
        ],
    },
    {
        "text": "What does ANALYZE do?",
        "explanation": """ANALYZE collects statistics about table contents, helping the query planner choose optimal execution plans. Should run after significant data changes.""",
        "reference": "https://www.postgresql.org/docs/current/sql-analyze.html",
        "points": 1,
        "answers": [
            {"text": "Collects statistics for query optimization", "is_correct": True},
            {"text": "Checks for syntax errors", "is_correct": False},
            {"text": "Repairs corrupted indexes", "is_correct": False},
            {"text": "Monitors query performance", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of FETCH FIRST n ROWS ONLY?",
        "explanation": """FETCH FIRST n ROWS ONLY limits query results to n rows. Standard SQL alternative to LIMIT. Often used with ORDER BY for top-N queries.""",
        "reference": "https://www.postgresql.org/docs/current/sql-select.html#SQL-LIMIT",
        "points": 1,
        "answers": [
            {"text": "Limits query results to n rows", "is_correct": True},
            {"text": "Returns only first table rows", "is_correct": False},
            {"text": "Fetches data faster", "is_correct": False},
            {"text": "Creates a cursor", "is_correct": False},
        ],
    },
    {
        "text": "What does FILTER clause do in aggregate functions?",
        "explanation": """FILTER(WHERE condition) applies conditions to aggregate functions, allowing conditional aggregation within SELECT without subqueries. Example: COUNT(*) FILTER(WHERE status='active').""",
        "reference": "https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES",
        "points": 1,
        "answers": [
            {"text": "Applies conditions to aggregate functions", "is_correct": True},
            {"text": "Filters table rows", "is_correct": False},
            {"text": "Removes NULL values", "is_correct": False},
            {"text": "Optimizes query execution", "is_correct": False},
        ],
    },
    {
        "text": "What is a generated column?",
        "explanation": """A generated column's value is automatically computed from other columns. STORED physically saves the value, VIRTUAL computes on read (not in PostgreSQL yet).""",
        "reference": "https://www.postgresql.org/docs/current/ddl-generated-columns.html",
        "points": 1,
        "answers": [
            {"text": "A column automatically computed from other columns", "is_correct": True},
            {"text": "A column with auto-increment values", "is_correct": False},
            {"text": "A temporary column", "is_correct": False},
            {"text": "A column created by triggers", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between ROWS and RANGE in window frames?",
        "explanation": """ROWS counts a fixed number of rows relative to the current row, while RANGE groups rows with the same ORDER BY value into the frame. RANGE can include more rows than expected when there are ties.""",
        "reference": "https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS",
        "points": 1,
        "answers": [
            {"text": "ROWS counts rows; RANGE groups rows with equal ORDER BY values", "is_correct": True},
            {"text": "ROWS is for numbers only; RANGE is for dates only", "is_correct": False},
            {"text": "RANGE is always faster than ROWS", "is_correct": False},
            {"text": "They are identical", "is_correct": False},
        ],
    },
    {
        "text": "When can PostgreSQL perform an index-only scan?",
        "explanation": """An index-only scan is possible when all required columns are in the index and the visibility map shows the heap pages are all-visible. Otherwise PostgreSQL must visit the table heap.""",
        "reference": "https://www.postgresql.org/docs/current/indexes-index-only-scans.html",
        "points": 1,
        "answers": [
            {"text": "When all needed columns are in the index and visibility map allows it", "is_correct": True},
            {"text": "Whenever an index exists", "is_correct": False},
            {"text": "Only when the table has no NULLs", "is_correct": False},
            {"text": "Only for primary keys", "is_correct": False},
        ],
    },
    {
        "text": "What is a BRIN index most suitable for?",
        "explanation": """BRIN (Block Range INdex) works well for very large tables where values are naturally clustered, such as time-series data. It stores summaries per block range rather than per row.""",
        "reference": "https://www.postgresql.org/docs/current/brin.html",
        "points": 1,
        "answers": [
            {"text": "Large tables with data naturally ordered or clustered", "is_correct": True},
            {"text": "Small tables with random data", "is_correct": False},
            {"text": "Text search on short strings", "is_correct": False},
            {"text": "Unique constraints on primary keys", "is_correct": False},
        ],
    },
    {
        "text": "What does the SERIALIZABLE isolation level guarantee?",
        "explanation": """SERIALIZABLE provides the strictest isolation, ensuring transactions behave as if executed one at a time. PostgreSQL may abort transactions with serialization failures to preserve correctness.""",
        "reference": "https://www.postgresql.org/docs/current/transaction-iso.html",
        "points": 1,
        "answers": [
            {"text": "Transactions behave as if run one at a time", "is_correct": True},
            {"text": "No locks are ever taken", "is_correct": False},
            {"text": "Dirty reads are allowed", "is_correct": False},
            {"text": "Only read-only transactions are permitted", "is_correct": False},
        ],
    },
    {
        "text": "What does a DEFERRABLE constraint allow?",
        "explanation": """A DEFERRABLE constraint can be checked at transaction end rather than immediately. You can defer checking with SET CONSTRAINTS to enable multi-step updates.""",
        "reference": "https://www.postgresql.org/docs/current/sql-createtable.html",
        "points": 1,
        "answers": [
            {"text": "Constraint checking at transaction end", "is_correct": True},
            {"text": "Automatic index creation", "is_correct": False},
            {"text": "Temporary constraint suspension across sessions", "is_correct": False},
            {"text": "Constraint enforcement only on SELECT", "is_correct": False},
        ],
    },
    {
        "text": "What does ROLLUP provide in GROUP BY?",
        "explanation": """ROLLUP adds subtotals and a grand total to grouped results. It is useful for hierarchical aggregates like (year, month) totals.""",
        "reference": "https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUPING-SETS",
        "points": 1,
        "answers": [
            {"text": "Subtotals and grand totals for grouped data", "is_correct": True},
            {"text": "Removes duplicate rows", "is_correct": False},
            {"text": "Creates a materialized view", "is_correct": False},
            {"text": "Forces index usage", "is_correct": False},
        ],
    },
    {
        "text": "What does SELECT ... FOR UPDATE SKIP LOCKED do?",
        "explanation": """SKIP LOCKED causes rows already locked by other transactions to be skipped instead of waiting, enabling safe work queues and concurrent consumers.""",
        "reference": "https://www.postgresql.org/docs/current/explicit-locking.html",
        "points": 1,
        "answers": [
            {"text": "Skips rows locked by other transactions", "is_correct": True},
            {"text": "Ignores transaction isolation", "is_correct": False},
            {"text": "Unlocks rows automatically", "is_correct": False},
            {"text": "Locks rows only after commit", "is_correct": False},
        ],
    },
    {
        "text": "What is a GIN index commonly used for?",
        "explanation": """GIN (Generalized Inverted Index) is optimized for composite values like arrays, JSONB, and full-text search where a row contains many keys.""",
        "reference": "https://www.postgresql.org/docs/current/gin.html",
        "points": 1,
        "answers": [
            {"text": "Arrays, JSONB, and full-text search", "is_correct": True},
            {"text": "Single-column numeric ranges only", "is_correct": False},
            {"text": "Primary key lookups", "is_correct": False},
            {"text": "Row-level security policies", "is_correct": False},
        ],
    },
    {
        "text": "What does an EXCLUDE constraint enforce?",
        "explanation": """EXCLUDE constraints prevent rows from having conflicting values based on an operator class, commonly used to prevent overlapping ranges.""",
        "reference": "https://www.postgresql.org/docs/current/sql-createtable.html",
        "points": 1,
        "answers": [
            {"text": "Prevents conflicting values like overlapping ranges", "is_correct": True},
            {"text": "Excludes columns from SELECT *", "is_correct": False},
            {"text": "Disables foreign key checks", "is_correct": False},
            {"text": "Blocks inserts on weekends", "is_correct": False},
        ],
    },
    {
        "text": "What does the MERGE statement do?",
        "explanation": """MERGE conditionally inserts, updates, or deletes rows based on matches between a source and target. It is a single statement for sync-style operations.""",
        "reference": "https://www.postgresql.org/docs/current/sql-merge.html",
        "points": 1,
        "answers": [
            {"text": "Conditionally INSERT/UPDATE/DELETE based on matches", "is_correct": True},
            {"text": "Merges two databases into one", "is_correct": False},
            {"text": "Combines schemas without data", "is_correct": False},
            {"text": "Replaces VACUUM for cleanup", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of a CHECK constraint?",
        "explanation": """CHECK constraints enforce a boolean expression for each row, preventing invalid data from being inserted or updated.""",
        "reference": "https://www.postgresql.org/docs/current/ddl-constraints.html",
        "points": 1,
        "answers": [
            {"text": "Enforces a condition on row values", "is_correct": True},
            {"text": "Creates an index automatically", "is_correct": False},
            {"text": "Encrypts column data", "is_correct": False},
            {"text": "Schedules background jobs", "is_correct": False},
        ],
    },
    {
        "text": "What does the FILTER clause enable in aggregates?",
        "explanation": """FILTER allows conditional aggregation per aggregate function, avoiding CASE expressions or subqueries for multiple aggregates.""",
        "reference": "https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES",
        "points": 1,
        "answers": [
            {"text": "Conditional aggregation per aggregate function", "is_correct": True},
            {"text": "Filtering rows before GROUP BY", "is_correct": False},
            {"text": "Filtering columns from SELECT", "is_correct": False},
            {"text": "Making aggregates deterministic", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of a covering index with INCLUDE columns?",
        "explanation": """INCLUDE columns store extra non-key columns in the index, enabling index-only scans without affecting the index sort order.""",
        "reference": "https://www.postgresql.org/docs/current/sql-createindex.html",
        "points": 1,
        "answers": [
            {"text": "Add non-key columns for index-only scans", "is_correct": True},
            {"text": "Reduce index size by excluding columns", "is_correct": False},
            {"text": "Encrypt index contents", "is_correct": False},
            {"text": "Force table scans", "is_correct": False},
        ],
    },
    {
        "text": "What does a GiST index support well?",
        "explanation": """GiST (Generalized Search Tree) indexes are flexible and support geometric data, ranges, and similarity searches via operator classes.""",
        "reference": "https://www.postgresql.org/docs/current/gist.html",
        "points": 1,
        "answers": [
            {"text": "Geometric, range, and similarity searches", "is_correct": True},
            {"text": "Only equality lookups", "is_correct": False},
            {"text": "Only full-text search", "is_correct": False},
            {"text": "Primary key enforcement", "is_correct": False},
        ],
    },
    {
        "text": "What does a multicolumn index require for optimal use?",
        "explanation": """PostgreSQL can use a multicolumn index effectively when the query filters on the leftmost columns in the index definition.""",
        "reference": "https://www.postgresql.org/docs/current/indexes-multicolumn.html",
        "points": 1,
        "answers": [
            {"text": "Conditions on the leftmost indexed columns", "is_correct": True},
            {"text": "Conditions on any column in any order", "is_correct": False},
            {"text": "No WHERE clause is required", "is_correct": False},
            {"text": "Only ORDER BY uses it", "is_correct": False},
        ],
    },
    {
        "text": "What is the effect of SET LOCAL in a transaction?",
        "explanation": """SET LOCAL applies a parameter change only for the current transaction, reverting automatically at commit or rollback.""",
        "reference": "https://www.postgresql.org/docs/current/sql-set.html",
        "points": 1,
        "answers": [
            {"text": "Applies setting for the current transaction only", "is_correct": True},
            {"text": "Applies setting permanently to the database", "is_correct": False},
            {"text": "Applies setting to all sessions", "is_correct": False},
            {"text": "Forces a session restart", "is_correct": False},
        ],
    },
    {
        "text": "What does the REPEATABLE READ isolation level prevent?",
        "explanation": """REPEATABLE READ prevents non-repeatable reads by ensuring a transaction sees a consistent snapshot. It still allows serialization anomalies unless SERIALIZABLE is used.""",
        "reference": "https://www.postgresql.org/docs/current/transaction-iso.html",
        "points": 1,
        "answers": [
            {"text": "Non-repeatable reads", "is_correct": True},
            {"text": "All phantom reads", "is_correct": False},
            {"text": "All serialization anomalies", "is_correct": False},
            {"text": "Dirty writes only", "is_correct": False},
        ],
    },
    {
        "text": "What does JSONB provide over JSON in PostgreSQL?",
        "explanation": """JSONB stores data in a binary format that supports indexing and faster search operations, at the cost of slightly slower insert due to parsing.""",
        "reference": "https://www.postgresql.org/docs/current/datatype-json.html",
        "points": 1,
        "answers": [
            {"text": "Binary storage with better indexing and search", "is_correct": True},
            {"text": "Preserves exact input formatting", "is_correct": False},
            {"text": "Allows duplicate keys", "is_correct": False},
            {"text": "Requires no parsing", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of generated identity columns?",
        "explanation": """GENERATED {ALWAYS|BY DEFAULT} AS IDENTITY provides SQL-standard auto-increment behavior, replacing SERIAL with better semantics.""",
        "reference": "https://www.postgresql.org/docs/current/ddl-system-columns.html#DDL-SYSTEM-COLUMNS-IDENTITY",
        "points": 1,
        "answers": [
            {"text": "SQL-standard auto-increment behavior", "is_correct": True},
            {"text": "Automatic UUID generation only", "is_correct": False},
            {"text": "Computed columns from expressions", "is_correct": False},
            {"text": "Row-level security enforcement", "is_correct": False},
        ],
    },
    {
        "text": "What does the ON CONFLICT DO NOTHING clause do?",
        "explanation": """ON CONFLICT DO NOTHING silently skips inserts that violate a unique constraint, avoiding errors for duplicates.""",
        "reference": "https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT",
        "points": 1,
        "answers": [
            {"text": "Skips inserts that would violate uniqueness", "is_correct": True},
            {"text": "Deletes conflicting rows", "is_correct": False},
            {"text": "Updates the conflicting row", "is_correct": False},
            {"text": "Turns off constraints for the session", "is_correct": False},
        ],
    },
    {
        "text": "What does the RETURNING clause do?",
        "explanation": """RETURNING returns values from rows affected by INSERT, UPDATE, or DELETE, avoiding an extra SELECT.""",
        "reference": "https://www.postgresql.org/docs/current/dml-returning.html",
        "points": 1,
        "answers": [
            {"text": "Returns columns from affected rows", "is_correct": True},
            {"text": "Returns only the number of rows affected", "is_correct": False},
            {"text": "Rolls back the change", "is_correct": False},
            {"text": "Returns query plans", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of LISTEN/NOTIFY?",
        "explanation": """LISTEN/NOTIFY enables asynchronous notifications between sessions, often used to signal events without polling.""",
        "reference": "https://www.postgresql.org/docs/current/sql-notify.html",
        "points": 1,
        "answers": [
            {"text": "Asynchronous notifications between sessions", "is_correct": True},
            {"text": "Synchronous replication between nodes", "is_correct": False},
            {"text": "Materialized view refresh", "is_correct": False},
            {"text": "Lock escalation", "is_correct": False},
        ],
    },
    {
        "text": "What does CREATE INDEX CONCURRENTLY do?",
        "explanation": """It builds an index without locking writes, allowing reads and writes during creation. It takes longer and cannot run inside a transaction block.""",
        "reference": "https://www.postgresql.org/docs/current/sql-createindex.html",
        "points": 1,
        "answers": [
            {"text": "Builds an index without blocking writes", "is_correct": True},
            {"text": "Builds multiple indexes in parallel threads", "is_correct": False},
            {"text": "Requires exclusive table locks", "is_correct": False},
            {"text": "Forces a table rewrite", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of SET CONSTRAINTS ALL DEFERRED?",
        "explanation": """It defers checking of deferrable constraints until the end of the transaction, useful for batch updates that temporarily violate constraints.""",
        "reference": "https://www.postgresql.org/docs/current/sql-set-constraints.html",
        "points": 1,
        "answers": [
            {"text": "Defers checking deferrable constraints to commit", "is_correct": True},
            {"text": "Disables all constraints permanently", "is_correct": False},
            {"text": "Applies only to CHECK constraints", "is_correct": False},
            {"text": "Converts constraints to triggers", "is_correct": False},
        ],
    },
    {
        "text": "What does a UNIQUE constraint allow with NULL values?",
        "explanation": """In PostgreSQL, UNIQUE constraints allow multiple NULLs because NULL is not considered equal to NULL in uniqueness checks.""",
        "reference": "https://www.postgresql.org/docs/current/ddl-constraints.html",
        "points": 1,
        "answers": [
            {"text": "Multiple NULL values are allowed", "is_correct": True},
            {"text": "Only one NULL value is allowed", "is_correct": False},
            {"text": "NULL values are converted to zero", "is_correct": False},
            {"text": "NULL values are forbidden", "is_correct": False},
        ],
    },
    {
        "text": "What does the CLUSTER command do?",
        "explanation": """CLUSTER physically reorders a table based on an index, improving locality for index scans. It is a one-time operation unless repeated.""",
        "reference": "https://www.postgresql.org/docs/current/sql-cluster.html",
        "points": 1,
        "answers": [
            {"text": "Physically reorders table based on an index", "is_correct": True},
            {"text": "Creates a cluster of servers", "is_correct": False},
            {"text": "Enables partitioning", "is_correct": False},
            {"text": "Compacts WAL files", "is_correct": False},
        ],
    },
    {
        "text": "What is table partitioning used for?",
        "explanation": """Partitioning splits a large table into smaller pieces for manageability and performance, enabling pruning to scan only relevant partitions.""",
        "reference": "https://www.postgresql.org/docs/current/ddl-partitioning.html",
        "points": 1,
        "answers": [
            {"text": "Splitting a table into smaller pieces with pruning", "is_correct": True},
            {"text": "Splitting a database into separate servers", "is_correct": False},
            {"text": "Creating backups for each table", "is_correct": False},
            {"text": "Automatically sharding across nodes", "is_correct": False},
        ],
    },
    {
        "text": "What does partition pruning achieve?",
        "explanation": """Partition pruning skips scanning partitions that cannot match the query predicate, reducing I/O and improving performance.""",
        "reference": "https://www.postgresql.org/docs/current/ddl-partitioning.html",
        "points": 1,
        "answers": [
            {"text": "Skips irrelevant partitions during query execution", "is_correct": True},
            {"text": "Drops old partitions automatically", "is_correct": False},
            {"text": "Rebalances partition sizes", "is_correct": False},
            {"text": "Merges partitions into one", "is_correct": False},
        ],
    },
    {
        "text": "What does the SET ROLE command do?",
        "explanation": """SET ROLE switches the current session's role to another role you are a member of, affecting privileges for subsequent commands.""",
        "reference": "https://www.postgresql.org/docs/current/sql-set-role.html",
        "points": 1,
        "answers": [
            {"text": "Switches the active role and privileges", "is_correct": True},
            {"text": "Creates a new role", "is_correct": False},
            {"text": "Revokes privileges from all roles", "is_correct": False},
            {"text": "Resets password policies", "is_correct": False},
        ],
    },
    {
        "text": "What does REINDEX do?",
        "explanation": """REINDEX rebuilds indexes to recover from corruption or bloat, potentially improving performance and ensuring index validity.""",
        "reference": "https://www.postgresql.org/docs/current/sql-reindex.html",
        "points": 1,
        "answers": [
            {"text": "Rebuilds an index", "is_correct": True},
            {"text": "Deletes unused rows from a table", "is_correct": False},
            {"text": "Upgrades index format only", "is_correct": False},
            {"text": "Disables an index", "is_correct": False},
        ],
    },
    {
        "text": "What does the SEARCH BREADTH FIRST option do in recursive CTEs?",
        "explanation": """SEARCH BREADTH FIRST orders recursive CTE results in breadth-first order, useful for hierarchical traversal and predictable ordering.""",
        "reference": "https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE",
        "points": 1,
        "answers": [
            {"text": "Orders recursive results breadth-first", "is_correct": True},
            {"text": "Ensures depth-first ordering", "is_correct": False},
            {"text": "Prevents recursion loops", "is_correct": False},
            {"text": "Disables ordering entirely", "is_correct": False},
        ],
    },
    {
        "text": "What does the CYCLE clause do in recursive CTEs?",
        "explanation": """CYCLE detects cycles in recursive queries and marks or stops them, preventing infinite recursion in graph-like data.""",
        "reference": "https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE",
        "points": 1,
        "answers": [
            {"text": "Detects and marks cycles in recursive results", "is_correct": True},
            {"text": "Repeats the query until no rows remain", "is_correct": False},
            {"text": "Converts recursion to iteration", "is_correct": False},
            {"text": "Optimizes by materializing results", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of row-level security (RLS)?",
        "explanation": """RLS enforces access control policies per row, restricting which rows a role can see or modify.""",
        "reference": "https://www.postgresql.org/docs/current/ddl-rowsecurity.html",
        "points": 1,
        "answers": [
            {"text": "Restrict row visibility and modification by role", "is_correct": True},
            {"text": "Encrypt row data at rest", "is_correct": False},
            {"text": "Disable row locking", "is_correct": False},
            {"text": "Automatically partition tables", "is_correct": False},
        ],
    },
    {
        "text": "What does ALTER TABLE ... SET STATISTICS do?",
        "explanation": """It adjusts the statistics target for a column, influencing how much data ANALYZE samples to improve planner estimates.""",
        "reference": "https://www.postgresql.org/docs/current/sql-altertable.html",
        "points": 1,
        "answers": [
            {"text": "Adjusts statistics target for a column", "is_correct": True},
            {"text": "Rebuilds indexes for the table", "is_correct": False},
            {"text": "Changes column data type", "is_correct": False},
            {"text": "Adds a default value", "is_correct": False},
        ],
    },
    {
        "text": "What does VACUUM FREEZE help prevent?",
        "explanation": """VACUUM FREEZE marks tuples as frozen to prevent transaction ID wraparound, reducing the need for future vacuuming on those pages.""",
        "reference": "https://www.postgresql.org/docs/current/sql-vacuum.html",
        "points": 1,
        "answers": [
            {"text": "Transaction ID wraparound", "is_correct": True},
            {"text": "Deadlocks", "is_correct": False},
            {"text": "Index corruption", "is_correct": False},
            {"text": "WAL file growth", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of two-phase commit (PREPARE TRANSACTION)?",
        "explanation": """Two-phase commit allows a transaction to be prepared and later committed or rolled back, coordinating changes across multiple systems.""",
        "reference": "https://www.postgresql.org/docs/current/sql-prepare-transaction.html",
        "points": 1,
        "answers": [
            {"text": "Coordinate distributed commits across systems", "is_correct": True},
            {"text": "Speed up single-row inserts", "is_correct": False},
            {"text": "Automatically retry failed queries", "is_correct": False},
            {"text": "Prevent all deadlocks", "is_correct": False},
        ],
    },
    {
        "text": "What does a FOREIGN KEY ... ON DELETE CASCADE do?",
        "explanation": """It automatically deletes referencing rows when the referenced row is deleted, maintaining referential integrity.""",
        "reference": "https://www.postgresql.org/docs/current/ddl-constraints.html",
        "points": 1,
        "answers": [
            {"text": "Deletes dependent rows when parent row is deleted", "is_correct": True},
            {"text": "Prevents deletion of parent rows", "is_correct": False},
            {"text": "Sets foreign keys to NULL on delete", "is_correct": False},
            {"text": "Moves child rows to an archive table", "is_correct": False},
        ],
    },
    {
        "text": "What does a HASH index optimize?",
        "explanation": """HASH indexes are optimized for equality comparisons only. They are not used for range queries or ordering.""",
        "reference": "https://www.postgresql.org/docs/current/indexes-types.html",
        "points": 1,
        "answers": [
            {"text": "Equality comparisons", "is_correct": True},
            {"text": "Range queries", "is_correct": False},
            {"text": "Prefix matching", "is_correct": False},
            {"text": "Full-text search", "is_correct": False},
        ],
    },
    {
        "text": "What does the pg_stat_statements extension provide?",
        "explanation": """It tracks execution statistics for SQL statements, helping identify slow or frequently executed queries.""",
        "reference": "https://www.postgresql.org/docs/current/pgstatstatements.html",
        "points": 1,
        "answers": [
            {"text": "Query execution statistics", "is_correct": True},
            {"text": "Row-level security policies", "is_correct": False},
            {"text": "Automatic index creation", "is_correct": False},
            {"text": "WAL compression", "is_correct": False},
        ],
    },
    {
        "text": "What does the ANY operator do with an array?",
        "explanation": """ANY compares a value to each element of an array or subquery and returns true if any comparison is true.""",
        "reference": "https://www.postgresql.org/docs/current/functions-comparisons.html",
        "points": 1,
        "answers": [
            {"text": "Compares value to any element and returns true if any match", "is_correct": True},
            {"text": "Compares value to all elements and requires all match", "is_correct": False},
            {"text": "Flattens arrays into rows", "is_correct": False},
            {"text": "Creates arrays from rows", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the LAG() window function?",
        "explanation": """LAG() returns a value from a previous row in the window partition, enabling comparisons to prior rows.""",
        "reference": "https://www.postgresql.org/docs/current/functions-window.html",
        "points": 1,
        "answers": [
            {"text": "Accesses data from a previous row", "is_correct": True},
            {"text": "Accesses data from the next row", "is_correct": False},
            {"text": "Calculates cumulative totals", "is_correct": False},
            {"text": "Creates a random offset", "is_correct": False},
        ],
    },
    {
        "text": "What does the GROUPING() function indicate?",
        "explanation": """GROUPING() returns 1 when a column is aggregated by GROUPING SETS, ROLLUP, or CUBE and 0 when it is not.""",
        "reference": "https://www.postgresql.org/docs/current/functions-aggregate.html",
        "points": 1,
        "answers": [
            {"text": "Whether a column is aggregated in grouping sets", "is_correct": True},
            {"text": "Whether a column is indexed", "is_correct": False},
            {"text": "Whether a column allows NULLs", "is_correct": False},
            {"text": "Whether a column is sorted", "is_correct": False},
        ],
    },
    {
        "text": "What does the CUBE option add to GROUP BY?",
        "explanation": """CUBE produces all combinations of subtotals for the listed grouping columns, including the grand total.""",
        "reference": "https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUPING-SETS",
        "points": 1,
        "answers": [
            {"text": "All combinations of subtotals", "is_correct": True},
            {"text": "Only a grand total row", "is_correct": False},
            {"text": "Only pairwise combinations", "is_correct": False},
            {"text": "No subtotals", "is_correct": False},
        ],
    },
    {
        "text": "What does the OVERLAPS operator do?",
        "explanation": """OVERLAPS compares two time periods and returns true if they intersect, useful for scheduling and range overlap checks.""",
        "reference": "https://www.postgresql.org/docs/current/functions-datetime.html",
        "points": 1,
        "answers": [
            {"text": "Checks whether two time ranges overlap", "is_correct": True},
            {"text": "Merges two time ranges into one", "is_correct": False},
            {"text": "Subtracts one interval from another", "is_correct": False},
            {"text": "Rounds timestamps to nearest minute", "is_correct": False},
        ],
    },
    {
        "text": "What does the RANGE type enable in PostgreSQL?",
        "explanation": """Range types represent a range of values (e.g., int4range, tstzrange) and support overlap, containment, and adjacency operators.""",
        "reference": "https://www.postgresql.org/docs/current/rangetypes.html",
        "points": 1,
        "answers": [
            {"text": "Native range values with overlap and containment operators", "is_correct": True},
            {"text": "Only enumerated values", "is_correct": False},
            {"text": "Automatic sharding of tables", "is_correct": False},
            {"text": "Implicit unit conversions", "is_correct": False},
        ],
    },
    {
        "text": "What does the COALESCE function often help avoid?",
        "explanation": """COALESCE can prevent NULL propagation by substituting defaults, commonly used to avoid NULL results in expressions.""",
        "reference": "https://www.postgresql.org/docs/current/functions-conditional.html",
        "points": 1,
        "answers": [
            {"text": "NULL propagation in expressions", "is_correct": True},
            {"text": "Index bloat", "is_correct": False},
            {"text": "Deadlocks", "is_correct": False},
            {"text": "Race conditions", "is_correct": False},
        ],
    },
    {
        "text": "What does the NOT VALID option do for constraints?",
        "explanation": """NOT VALID creates the constraint without checking existing rows, allowing fast creation and later validation with VALIDATE CONSTRAINT.""",
        "reference": "https://www.postgresql.org/docs/current/sql-altertable.html",
        "points": 1,
        "answers": [
            {"text": "Creates constraint without checking existing rows", "is_correct": True},
            {"text": "Disables the constraint entirely", "is_correct": False},
            {"text": "Marks constraint as read-only", "is_correct": False},
            {"text": "Drops the constraint after commit", "is_correct": False},
        ],
    },
    {
        "text": "What does the LIKE pattern '%' match?",
        "explanation": """In LIKE patterns, '%' matches any sequence of characters (including an empty string).""",
        "reference": "https://www.postgresql.org/docs/current/functions-matching.html",
        "points": 1,
        "answers": [
            {"text": "Any sequence of characters", "is_correct": True},
            {"text": "A single character", "is_correct": False},
            {"text": "Only digits", "is_correct": False},
            {"text": "Only letters", "is_correct": False},
        ],
    },
    {
        "text": "What does the ESCAPE clause do in LIKE patterns?",
        "explanation": """ESCAPE defines a character that turns '%' and '_' into literals in a LIKE pattern, allowing you to match those characters.""",
        "reference": "https://www.postgresql.org/docs/current/functions-matching.html",
        "points": 1,
        "answers": [
            {"text": "Defines an escape character for '%' and '_' literals", "is_correct": True},
            {"text": "Escapes quotes in SQL strings", "is_correct": False},
            {"text": "Disables pattern matching", "is_correct": False},
            {"text": "Makes LIKE case-sensitive", "is_correct": False},
        ],
    },
    {
        "text": "What is the effect of SELECT DISTINCT?",
        "explanation": """SELECT DISTINCT removes duplicate rows from the result set, keeping one row per unique combination of selected columns.""",
        "reference": "https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT",
        "points": 1,
        "answers": [
            {"text": "Removes duplicate rows from the result set", "is_correct": True},
            {"text": "Sorts the result set by default", "is_correct": False},
            {"text": "Removes NULL values", "is_correct": False},
            {"text": "Requires a primary key", "is_correct": False},
        ],
    },
]
