"""TypeScript Developer Certification"""

CERTIFICATION = {
    "name": "TypeScript Developer Certification",
    "description": "TypeScript language features, type system, and advanced programming concepts",
    "slug": "typescript-developer-certification",
    "level": "Associate",
    "duration": 90,  # in minutes
    "questions_count": 60,
    "category_slug": "programming",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is the main benefit of using TypeScript over JavaScript?",
        "explanation": "TypeScript adds static type checking to JavaScript, helping catch errors at compile time rather than runtime.",
        "reference": "https://www.typescriptlang.org/docs/",
        "points": 1,
        "answers": [
            {"text": "Faster runtime performance", "is_correct": False},
            {"text": "Static type checking", "is_correct": True},
            {"text": "Smaller bundle size", "is_correct": False},
            {"text": "Built-in testing framework", "is_correct": False},
        ],
    },
    {
        "text": "Which TypeScript feature allows you to define optional properties in an interface?",
        "explanation": "The question mark (?) syntax allows you to define optional properties in TypeScript interfaces.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/objects.html",
        "points": 1,
        "answers": [
            {"text": "property?", "is_correct": True},
            {"text": "property | undefined", "is_correct": False},
            {"text": "optional property", "is_correct": False},
            {"text": "property: any", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'never' type represent in TypeScript?",
        "explanation": "The 'never' type represents values that never occur, such as functions that always throw errors or have infinite loops.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/narrowing.html#the-never-type",
        "points": 1,
        "answers": [
            {"text": "A type that can be anything", "is_correct": False},
            {"text": "A type that represents null or undefined", "is_correct": False},
            {"text": "A type for values that never occur", "is_correct": True},
            {"text": "A type for boolean values", "is_correct": False},
        ],
    },
    {
        "text": "How do you define a generic function in TypeScript?",
        "explanation": "Generic functions in TypeScript are defined using angle brackets with type parameters, like function<T>(param: T): T.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/generics.html",
        "points": 1,
        "answers": [
            {"text": "function<T>(param: T): T", "is_correct": True},
            {"text": "function(param: generic): generic", "is_correct": False},
            {"text": "generic function(param: T): T", "is_correct": False},
            {"text": "function[T](param: T): T", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'readonly' modifier in TypeScript?",
        "explanation": "The 'readonly' modifier prevents modification of a property after initialization, making it immutable.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/classes.html#readonly",
        "points": 1,
        "answers": [
            {"text": "Makes properties private", "is_correct": False},
            {"text": "Prevents modification after initialization", "is_correct": True},
            {"text": "Makes properties optional", "is_correct": False},
            {"text": "Allows null values", "is_correct": False},
        ],
    },
    {
        "text": "What is a union type in TypeScript?",
        "explanation": "A union type allows a variable to be one of several types, expressed using the pipe (|) operator.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types",
        "points": 1,
        "answers": [
            {"text": "A type that combines multiple interfaces", "is_correct": False},
            {"text": "A type that can be one of several types", "is_correct": True},
            {"text": "A type for merging arrays", "is_correct": False},
            {"text": "A type for database operations", "is_correct": False},
        ],
    },
    {
        "text": "What keyword is used to create a type alias in TypeScript?",
        "explanation": "The 'type' keyword is used to create type aliases in TypeScript.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-aliases",
        "points": 1,
        "answers": [
            {"text": "alias", "is_correct": False},
            {"text": "type", "is_correct": True},
            {"text": "typedef", "is_correct": False},
            {"text": "interface", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between 'interface' and 'type' in TypeScript?",
        "explanation": "Interfaces can be extended and merged, while type aliases cannot be reopened to add new properties. Interfaces are better for object shapes, types are more flexible for unions and primitives.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces",
        "points": 1,
        "answers": [
            {"text": "No difference, they are identical", "is_correct": False},
            {"text": "Interfaces can be extended and merged, types cannot", "is_correct": True},
            {"text": "Types are faster at runtime", "is_correct": False},
            {"text": "Interfaces are only for classes", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'keyof' operator do in TypeScript?",
        "explanation": "The 'keyof' operator produces a union of string or numeric literal types representing the keys of an object type.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/keyof-types.html",
        "points": 1,
        "answers": [
            {"text": "Creates a new key in an object", "is_correct": False},
            {"text": "Returns the keys of an object type as a union", "is_correct": True},
            {"text": "Checks if a key exists in an object", "is_correct": False},
            {"text": "Deletes a key from an object", "is_correct": False},
        ],
    },
    {
        "text": "What is a tuple type in TypeScript?",
        "explanation": "A tuple type allows you to express an array with a fixed number of elements whose types are known but need not be the same.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types",
        "points": 1,
        "answers": [
            {"text": "An array with unlimited elements", "is_correct": False},
            {"text": "An array with fixed number and types of elements", "is_correct": True},
            {"text": "A type for database tuples", "is_correct": False},
            {"text": "A special string type", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of 'as const' assertion in TypeScript?",
        "explanation": "'as const' makes all properties readonly and narrows types to their literal values, useful for creating immutable objects and literal type unions.",
        "reference": "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions",
        "points": 1,
        "answers": [
            {"text": "Converts variable to a constant", "is_correct": False},
            {"text": "Makes all properties readonly and narrows to literals", "is_correct": True},
            {"text": "Checks if value is constant", "is_correct": False},
            {"text": "Creates a constant class", "is_correct": False},
        ],
    },
    {
        "text": "What is type narrowing in TypeScript?",
        "explanation": "Type narrowing is the process of refining types to more specific types through control flow analysis and type guards.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/narrowing.html",
        "points": 1,
        "answers": [
            {"text": "Reducing file size of types", "is_correct": False},
            {"text": "Refining types to more specific types", "is_correct": True},
            {"text": "Making types more generic", "is_correct": False},
            {"text": "Converting types to strings", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'unknown' type in TypeScript?",
        "explanation": "The 'unknown' type is a type-safe counterpart of 'any'. You cannot do anything with an unknown value without narrowing its type first.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/functions.html#unknown",
        "points": 1,
        "answers": [
            {"text": "Same as 'any' type", "is_correct": False},
            {"text": "A type-safe counterpart of 'any' requiring type checking", "is_correct": True},
            {"text": "A type for unknown variables", "is_correct": False},
            {"text": "A type for undefined values", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'satisfies' operator do in TypeScript?",
        "explanation": "The 'satisfies' operator validates that a value satisfies a type without changing the inferred type of the expression.",
        "reference": "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator",
        "points": 1,
        "answers": [
            {"text": "Changes the type of a variable", "is_correct": False},
            {"text": "Validates type without changing inferred type", "is_correct": True},
            {"text": "Checks for null values", "is_correct": False},
            {"text": "Creates a new type", "is_correct": False},
        ],
    },
    {
        "text": "What are mapped types in TypeScript?",
        "explanation": "Mapped types allow you to create new types by transforming properties of existing types, using the 'in keyof' syntax.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/mapped-types.html",
        "points": 1,
        "answers": [
            {"text": "Types for Map data structures", "is_correct": False},
            {"text": "Types that transform properties of existing types", "is_correct": True},
            {"text": "Types for geographic mapping", "is_correct": False},
            {"text": "Types for function mapping", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'infer' keyword in TypeScript?",
        "explanation": "The 'infer' keyword is used in conditional types to infer a type variable within the condition that can be referenced in the true branch.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types",
        "points": 1,
        "answers": [
            {"text": "To automatically detect types", "is_correct": False},
            {"text": "To infer type variables in conditional types", "is_correct": True},
            {"text": "To infer function return types", "is_correct": False},
            {"text": "To guess unknown types", "is_correct": False},
        ],
    },
    {
        "text": "What is a discriminated union in TypeScript?",
        "explanation": "A discriminated union uses a common property (discriminant) to distinguish between union members, enabling type narrowing.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions",
        "points": 1,
        "answers": [
            {"text": "A union that discriminates against certain types", "is_correct": False},
            {"text": "A union with a common property for type narrowing", "is_correct": True},
            {"text": "A union of different classes", "is_correct": False},
            {"text": "A type for database queries", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Partial<T>' utility type do?",
        "explanation": "Partial<T> constructs a type with all properties of T set to optional.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype",
        "points": 1,
        "answers": [
            {"text": "Makes all properties required", "is_correct": False},
            {"text": "Makes all properties optional", "is_correct": True},
            {"text": "Removes half of the properties", "is_correct": False},
            {"text": "Creates a partial class", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Required<T>' utility type do?",
        "explanation": "Required<T> constructs a type with all properties of T set to required, removing optional modifiers.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype",
        "points": 1,
        "answers": [
            {"text": "Makes all properties optional", "is_correct": False},
            {"text": "Makes all properties required", "is_correct": True},
            {"text": "Checks if properties are required", "is_correct": False},
            {"text": "Creates required imports", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Pick<T, K>' utility type do?",
        "explanation": "Pick<T, K> constructs a type by picking the set of properties K from type T.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys",
        "points": 1,
        "answers": [
            {"text": "Randomly selects properties", "is_correct": False},
            {"text": "Creates a type with selected properties from T", "is_correct": True},
            {"text": "Removes properties from a type", "is_correct": False},
            {"text": "Picks the best type", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Omit<T, K>' utility type do?",
        "explanation": "Omit<T, K> constructs a type by picking all properties from T and then removing K.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys",
        "points": 1,
        "answers": [
            {"text": "Creates a type excluding specified properties", "is_correct": True},
            {"text": "Includes only specified properties", "is_correct": False},
            {"text": "Omits types from compilation", "is_correct": False},
            {"text": "Removes all properties", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Record<K, T>' utility type do?",
        "explanation": "Record<K, T> constructs an object type whose property keys are K and whose property values are T.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type",
        "points": 1,
        "answers": [
            {"text": "Records all types in a project", "is_correct": False},
            {"text": "Creates an object type with keys K and values T", "is_correct": True},
            {"text": "Records runtime type information", "is_correct": False},
            {"text": "Creates a database record type", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of 'strictNullChecks' in TypeScript?",
        "explanation": "strictNullChecks makes null and undefined distinct types, preventing accidental null/undefined errors by requiring explicit handling.",
        "reference": "https://www.typescriptlang.org/tsconfig#strictNullChecks",
        "points": 1,
        "answers": [
            {"text": "Removes all null checks", "is_correct": False},
            {"text": "Makes null and undefined distinct types requiring explicit handling", "is_correct": True},
            {"text": "Automatically fixes null errors", "is_correct": False},
            {"text": "Disables null values", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'this' parameter in TypeScript functions?",
        "explanation": "A fake parameter that comes first in the parameter list to specify the type of 'this' in the function body.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function",
        "points": 1,
        "answers": [
            {"text": "A reference to the current object", "is_correct": False},
            {"text": "A fake parameter to specify the type of 'this'", "is_correct": True},
            {"text": "A parameter passed by the caller", "is_correct": False},
            {"text": "The first real parameter", "is_correct": False},
        ],
    },
    {
        "text": "What are conditional types in TypeScript?",
        "explanation": "Conditional types select one of two possible types based on a condition expressed as a type relationship test, using 'extends ? :' syntax.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/conditional-types.html",
        "points": 1,
        "answers": [
            {"text": "Types that depend on runtime conditions", "is_correct": False},
            {"text": "Types that select based on type relationship tests", "is_correct": True},
            {"text": "Types for if-else statements", "is_correct": False},
            {"text": "Types that are conditionally compiled", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Exclude<T, U>' utility type do?",
        "explanation": "Exclude<T, U> constructs a type by excluding from T all union members that are assignable to U.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#excludetype-excludedunion",
        "points": 1,
        "answers": [
            {"text": "Includes only specified types", "is_correct": False},
            {"text": "Excludes types assignable to U from T", "is_correct": True},
            {"text": "Excludes types from compilation", "is_correct": False},
            {"text": "Creates an exclusion list", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'abstract' keyword in TypeScript classes?",
        "explanation": "The 'abstract' keyword defines classes that cannot be instantiated directly and methods that must be implemented by derived classes.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/classes.html#abstract-classes-and-members",
        "points": 1,
        "answers": [
            {"text": "Makes classes private", "is_correct": False},
            {"text": "Defines base classes and methods requiring implementation", "is_correct": True},
            {"text": "Makes classes more abstract", "is_correct": False},
            {"text": "Removes implementation details", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'ReturnType<T>' utility type used for?",
        "explanation": "ReturnType<T> constructs a type consisting of the return type of function type T.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype",
        "points": 1,
        "answers": [
            {"text": "Returns the type of a variable", "is_correct": False},
            {"text": "Extracts the return type of a function type", "is_correct": True},
            {"text": "Returns a type to its original form", "is_correct": False},
            {"text": "Checks what type a function returns", "is_correct": False},
        ],
    },
    {
        "text": "What are index signatures in TypeScript?",
        "explanation": "Index signatures allow you to describe types that can be indexed with a key of a certain type, like objects with dynamic keys.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures",
        "points": 1,
        "answers": [
            {"text": "Signatures for array indices", "is_correct": False},
            {"text": "Types describing objects with dynamic keys", "is_correct": True},
            {"text": "Digital signatures for security", "is_correct": False},
            {"text": "Function signatures with indices", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of 'declare' keyword in TypeScript?",
        "explanation": "The 'declare' keyword is used to tell TypeScript that a variable, function, or class exists, typically for ambient declarations in .d.ts files.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/type-declarations.html",
        "points": 1,
        "answers": [
            {"text": "Declares new variables", "is_correct": False},
            {"text": "Declares existence of entities for ambient declarations", "is_correct": True},
            {"text": "Makes declarations public", "is_correct": False},
            {"text": "Declares types at runtime", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the 'typeof' operator in TypeScript?",
        "explanation": "In TypeScript, 'typeof' can be used in type contexts to get the type of a variable or property.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/typeof-types.html",
        "points": 1,
        "answers": [
            {"text": "Only checks runtime types", "is_correct": False},
            {"text": "Gets the type of a variable in type contexts", "is_correct": True},
            {"text": "Creates new types", "is_correct": False},
            {"text": "Checks if type exists", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Extract<T, U>' utility type do?",
        "explanation": "Extract<T, U> constructs a type by extracting from T all union members that are assignable to U.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union",
        "points": 1,
        "answers": [
            {"text": "Extracts properties from objects", "is_correct": False},
            {"text": "Extracts union members assignable to U from T", "is_correct": True},
            {"text": "Removes types from a union", "is_correct": False},
            {"text": "Extracts values from arrays", "is_correct": False},
        ],
    },
    {
        "text": "What is a type guard in TypeScript?",
        "explanation": "A type guard is a function or expression that performs a runtime check to narrow types within a conditional block.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates",
        "points": 1,
        "answers": [
            {"text": "A security feature for types", "is_correct": False},
            {"text": "A runtime check that narrows types", "is_correct": True},
            {"text": "A guard clause in functions", "is_correct": False},
            {"text": "A type protection mechanism", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'NonNullable<T>' utility type do?",
        "explanation": "NonNullable<T> constructs a type by excluding null and undefined from T.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#nonnullabletype",
        "points": 1,
        "answers": [
            {"text": "Allows null and undefined", "is_correct": False},
            {"text": "Excludes null and undefined from T", "is_correct": True},
            {"text": "Makes all values non-null", "is_correct": False},
            {"text": "Checks for nullable values", "is_correct": False},
        ],
    },
    {
        "text": "What is an intersection type in TypeScript?",
        "explanation": "An intersection type combines multiple types into one using the & operator, requiring the value to satisfy all types.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/objects.html#intersection-types",
        "points": 1,
        "answers": [
            {"text": "A type for array intersections", "is_correct": False},
            {"text": "Combines multiple types with & operator", "is_correct": True},
            {"text": "Finds common properties of types", "is_correct": False},
            {"text": "A type for set operations", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'Parameters<T>' utility type used for?",
        "explanation": "Parameters<T> constructs a tuple type from the types used in the parameters of a function type T.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype",
        "points": 1,
        "answers": [
            {"text": "Gets function parameters as values", "is_correct": False},
            {"text": "Extracts parameter types as a tuple", "is_correct": True},
            {"text": "Counts function parameters", "is_correct": False},
            {"text": "Validates function parameters", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the '!' (non-null assertion) operator?",
        "explanation": "The ! operator asserts that a value is not null or undefined, bypassing TypeScript's null checking.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-",
        "points": 1,
        "answers": [
            {"text": "Negates boolean values", "is_correct": False},
            {"text": "Asserts value is not null or undefined", "is_correct": True},
            {"text": "Makes values required", "is_correct": False},
            {"text": "Throws an error if null", "is_correct": False},
        ],
    },
    {
        "text": "What is a template literal type in TypeScript?",
        "explanation": "Template literal types build on string literal types and can expand into many strings via unions, using the same syntax as template literals.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html",
        "points": 1,
        "answers": [
            {"text": "Regular template strings", "is_correct": False},
            {"text": "Types that expand strings via unions", "is_correct": True},
            {"text": "HTML templates in types", "is_correct": False},
            {"text": "String formatting types", "is_correct": False},
        ],
    },
    {
        "text": "What does 'noImplicitAny' compiler option do?",
        "explanation": "noImplicitAny raises errors when variables have an implicit 'any' type, enforcing explicit type annotations.",
        "reference": "https://www.typescriptlang.org/tsconfig#noImplicitAny",
        "points": 1,
        "answers": [
            {"text": "Disables all 'any' types", "is_correct": False},
            {"text": "Raises errors for implicit 'any' types", "is_correct": True},
            {"text": "Automatically infers types", "is_correct": False},
            {"text": "Allows any type without errors", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'Awaited<T>' utility type used for?",
        "explanation": "Awaited<T> recursively unwraps the 'awaited' type of a Promise-like type, useful for getting the resolved value type.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#awaitedtype",
        "points": 1,
        "answers": [
            {"text": "Waits for async operations", "is_correct": False},
            {"text": "Unwraps the resolved type of Promises", "is_correct": True},
            {"text": "Creates awaitable types", "is_correct": False},
            {"text": "Checks if type is async", "is_correct": False},
        ],
    },
    {
        "text": "What is variance in TypeScript generics?",
        "explanation": "Variance refers to how subtyping between complex types relates to subtyping of their components, including covariance and contravariance.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/generics.html",
        "points": 1,
        "answers": [
            {"text": "Type variation in functions", "is_correct": False},
            {"text": "How subtyping relates between generic types", "is_correct": True},
            {"text": "Variable differences in code", "is_correct": False},
            {"text": "Generic type errors", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'in' operator used for in TypeScript?",
        "explanation": "The 'in' operator checks if a property exists in an object and can act as a type guard to narrow types.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/narrowing.html#the-in-operator-narrowing",
        "points": 1,
        "answers": [
            {"text": "Checks array membership", "is_correct": False},
            {"text": "Checks property existence and narrows types", "is_correct": True},
            {"text": "Imports modules", "is_correct": False},
            {"text": "Loops through objects", "is_correct": False},
        ],
    },
    {
        "text": "What is a branded type (nominal typing) in TypeScript?",
        "explanation": "Branded types add a unique symbol or property to create nominal-like typing in TypeScript's structural type system.",
        "reference": "https://www.typescriptlang.org/play#example/nominal-typing",
        "points": 1,
        "answers": [
            {"text": "Types with brand names", "is_correct": False},
            {"text": "Types with unique symbols for nominal typing", "is_correct": True},
            {"text": "Trademarked type names", "is_correct": False},
            {"text": "Types from specific libraries", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'strictFunctionTypes' option do?",
        "explanation": "strictFunctionTypes enables stricter checking of function type parameter contravariance, making function type checking more sound.",
        "reference": "https://www.typescriptlang.org/tsconfig#strictFunctionTypes",
        "points": 1,
        "answers": [
            {"text": "Makes all functions strict mode", "is_correct": False},
            {"text": "Enables stricter function parameter checking", "is_correct": True},
            {"text": "Requires type annotations on functions", "is_correct": False},
            {"text": "Disallows function types", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'ConstructorParameters<T>' utility type?",
        "explanation": "ConstructorParameters<T> constructs a tuple type from the types of a constructor function's parameters.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#constructorparameterstype",
        "points": 1,
        "answers": [
            {"text": "Gets constructor settings", "is_correct": False},
            {"text": "Extracts constructor parameter types as tuple", "is_correct": True},
            {"text": "Creates constructor functions", "is_correct": False},
            {"text": "Validates constructor calls", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'InstanceType<T>' utility type?",
        "explanation": "InstanceType<T> constructs a type consisting of the instance type of a constructor function type T.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#instancetypetype",
        "points": 1,
        "answers": [
            {"text": "Checks instance types at runtime", "is_correct": False},
            {"text": "Gets the instance type of a constructor", "is_correct": True},
            {"text": "Creates new instances", "is_correct": False},
            {"text": "Type for instanceof operator", "is_correct": False},
        ],
    },
    {
        "text": "What are string literal types in TypeScript?",
        "explanation": "String literal types allow you to specify the exact value a string must have, creating types from specific string values.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types",
        "points": 1,
        "answers": [
            {"text": "Types for string variables", "is_correct": False},
            {"text": "Types that specify exact string values", "is_correct": True},
            {"text": "String templates", "is_correct": False},
            {"text": "Literal string values", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'asserts' keyword used for in type predicates?",
        "explanation": "The 'asserts' keyword in type predicates tells TypeScript that if the function returns, the asserted condition is true.",
        "reference": "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions",
        "points": 1,
        "answers": [
            {"text": "Makes assertions in tests", "is_correct": False},
            {"text": "Declares assertion in type predicates", "is_correct": True},
            {"text": "Throws assertion errors", "is_correct": False},
            {"text": "Validates function inputs", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between 'enum' and 'const enum' in TypeScript?",
        "explanation": "const enums are completely removed during compilation and inlined at use sites, while regular enums generate runtime code.",
        "reference": "https://www.typescriptlang.org/docs/handbook/enums.html#const-enums",
        "points": 1,
        "answers": [
            {"text": "No difference", "is_correct": False},
            {"text": "const enums are inlined, regular enums generate code", "is_correct": True},
            {"text": "const enums are immutable", "is_correct": False},
            {"text": "const enums are faster", "is_correct": False},
        ],
    },
    {
        "text": "What is the 'ThisType<T>' utility type?",
        "explanation": "ThisType<T> is a marker for contextual 'this' type and doesn't return a transformed type, it's used to specify the type of 'this' in object literals.",
        "reference": "https://www.typescriptlang.org/docs/handbook/utility-types.html#thistypetype",
        "points": 1,
        "answers": [
            {"text": "Gets the type of 'this'", "is_correct": False},
            {"text": "Marker for contextual 'this' type", "is_correct": True},
            {"text": "Checks 'this' binding", "is_correct": False},
            {"text": "Creates 'this' references", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of the '--strictPropertyInitialization' flag?",
        "explanation": "This flag ensures that class properties are initialized in the constructor or have definite assignment assertions.",
        "reference": "https://www.typescriptlang.org/tsconfig#strictPropertyInitialization",
        "points": 1,
        "answers": [
            {"text": "Initializes all properties automatically", "is_correct": False},
            {"text": "Ensures class properties are initialized", "is_correct": True},
            {"text": "Makes properties strict", "is_correct": False},
            {"text": "Validates property types", "is_correct": False},
        ],
    },
    {
        "text": "What are numeric literal types in TypeScript?",
        "explanation": "Numeric literal types allow you to specify exact numeric values a number can have, similar to string literal types.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types",
        "points": 1,
        "answers": [
            {"text": "Types for numbers only", "is_correct": False},
            {"text": "Types with exact numeric values", "is_correct": True},
            {"text": "Literal number values", "is_correct": False},
            {"text": "Numeric string types", "is_correct": False},
        ],
    },
    {
        "text": "What is covariance in TypeScript?",
        "explanation": "Covariance means that a type relationship is preserved in the same direction, commonly seen in return types and readonly properties.",
        "reference": "https://www.typescriptlang.org/docs/handbook/type-compatibility.html",
        "points": 1,
        "answers": [
            {"text": "Variable type changes", "is_correct": False},
            {"text": "Type relationship preserved in same direction", "is_correct": True},
            {"text": "Opposite type relationships", "is_correct": False},
            {"text": "Type conversion rules", "is_correct": False},
        ],
    },
    {
        "text": "What is contravariance in TypeScript?",
        "explanation": "Contravariance means that a type relationship is reversed, commonly seen in function parameter positions.",
        "reference": "https://www.typescriptlang.org/docs/handbook/type-compatibility.html",
        "points": 1,
        "answers": [
            {"text": "Same direction type relationships", "is_correct": False},
            {"text": "Reversed type relationship in parameters", "is_correct": True},
            {"text": "Type contradiction checking", "is_correct": False},
            {"text": "Opposite variance types", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of 'namespace' in TypeScript?",
        "explanation": "Namespaces provide a way to organize code by grouping related code, though modules are now preferred for code organization.",
        "reference": "https://www.typescriptlang.org/docs/handbook/namespaces.html",
        "points": 1,
        "answers": [
            {"text": "Creates global variables", "is_correct": False},
            {"text": "Groups related code for organization", "is_correct": True},
            {"text": "Defines name spaces in strings", "is_correct": False},
            {"text": "Names functions", "is_correct": False},
        ],
    },
    {
        "text": "What is type assertion in TypeScript?",
        "explanation": "Type assertion is a way to tell the compiler to treat a value as a specific type, using 'as Type' or '<Type>' syntax.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions",
        "points": 1,
        "answers": [
            {"text": "Validates types at runtime", "is_correct": False},
            {"text": "Tells compiler to treat value as specific type", "is_correct": True},
            {"text": "Asserts type correctness", "is_correct": False},
            {"text": "Creates type assertions", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Uppercase<T>' utility type do?",
        "explanation": "Uppercase<T> transforms each character in a string literal type to uppercase.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#uppercasestringtype",
        "points": 1,
        "answers": [
            {"text": "Converts strings to uppercase", "is_correct": False},
            {"text": "Transforms string literal type to uppercase", "is_correct": True},
            {"text": "Makes text uppercase", "is_correct": False},
            {"text": "Checks for uppercase", "is_correct": False},
        ],
    },
    {
        "text": "What does the 'Lowercase<T>' utility type do?",
        "explanation": "Lowercase<T> transforms each character in a string literal type to lowercase.",
        "reference": "https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#lowercasestringtype",
        "points": 1,
        "answers": [
            {"text": "Converts strings to lowercase", "is_correct": False},
            {"text": "Transforms string literal type to lowercase", "is_correct": True},
            {"text": "Makes text lowercase", "is_correct": False},
            {"text": "Validates lowercase strings", "is_correct": False},
        ],
    },
]
