"""Tableau Desktop Specialist Certification"""

CERTIFICATION = {
    "name": "Tableau Desktop Specialist",
    "description": "Foundational skills in Tableau Desktop for data visualization and analysis",
    "slug": "tableau-desktop-specialist",
    "level": "Entry",
    "duration": 15,
    "questions_count": 5,
    "category_slug": "data-analytics",
    "is_active": True,
}

QUESTIONS = [{"text": "What is the difference between dimensions and measures in Tableau?",
              "explanation": "Dimensions are qualitative categorical fields that typically contain discrete values and are used to slice and filter data. Measures are quantitative numerical fields that can be aggregated and are used for calculations.",
              "reference": "https://help.tableau.com/current/pro/desktop/en-us/datafields_typesandroles.htm",
              "points": 1,
              "answers": [{"text": "Dimensions are categorical; measures are numerical and aggregatable",
                           "is_correct": True,
                           },
                          {"text": "Dimensions are numerical; measures are categorical",
                           "is_correct": False,
                           },
                          {"text": "They are the same thing",
                           "is_correct": False},
                          {"text": "Dimensions are always dates",
                           "is_correct": False},
                          ],
              },
             {"text": "Which chart type is best for showing parts of a whole?",
              "explanation": "Pie charts and treemaps are effective for showing how individual parts contribute to a whole, with pie charts being most common for simple part-to-whole relationships.",
              "reference": "https://help.tableau.com/current/pro/desktop/en-us/buildexamples_piechart.htm",
              "points": 1,
              "answers": [{"text": "Pie chart",
                           "is_correct": True},
                          {"text": "Line chart",
                           "is_correct": False},
                          {"text": "Scatter plot",
                           "is_correct": False},
                          {"text": "Histogram",
                           "is_correct": False},
                          ],
              },
             {"text": "What is a calculated field in Tableau?",
              "explanation": "A calculated field is a new field created by performing calculations on existing fields in your data source using Tableau's calculation language and functions.",
              "reference": "https://help.tableau.com/current/pro/desktop/en-us/calculations_calculatedfields.htm",
              "points": 1,
              "answers": [{"text": "A new field created by performing calculations on existing fields",
                           "is_correct": True,
                           },
                          {"text": "A field imported from the data source",
                           "is_correct": False},
                          {"text": "A field used only for filtering",
                           "is_correct": False},
                          {"text": "A field that stores metadata",
                           "is_correct": False},
                          ],
              },
             {"text": "What does the Marks card control in Tableau?",
              "explanation": "The Marks card controls the visual properties of marks in a view, including color, size, shape, label, detail, and tooltip, allowing you to encode additional dimensions of data.",
              "reference": "https://help.tableau.com/current/pro/desktop/en-us/buildmanual_marks.htm",
              "points": 1,
              "answers": [{"text": "Visual properties of marks like color, size, and shape",
                           "is_correct": True,
                           },
                          {"text": "Data source connections",
                           "is_correct": False},
                          {"text": "Dashboard layout",
                           "is_correct": False},
                          {"text": "User permissions",
                           "is_correct": False},
                          ],
              },
             {"text": "What is the purpose of data blending in Tableau?",
              "explanation": "Data blending allows you to combine data from multiple data sources in a single view by establishing relationships between common dimensions across the sources.",
              "reference": "https://help.tableau.com/current/pro/desktop/en-us/multiple_connections.htm",
              "points": 1,
              "answers": [{"text": "Combine data from multiple data sources in a single view",
                           "is_correct": True,
                           },
                          {"text": "Clean and transform data",
                           "is_correct": False},
                          {"text": "Create calculated fields",
                           "is_correct": False},
                          {"text": "Export data to external systems",
                           "is_correct": False},
                          ],
              },
             ]
