"""AWS Cloud Practitioner Certification"""

CERTIFICATION = {
    "name": "AWS Certified Cloud Practitioner",
    "description": "Foundational understanding of AWS Cloud",
    "slug": "aws-cloud-practitioner",
    "level": "Foundational",
    "duration": 300,
    "questions_count": 100,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "What is the AWS Well-Architected Framework?",
        "explanation": "The AWS Well-Architected Framework provides guidance to help customers build secure, high-performing, resilient, and efficient infrastructure for their applications.",
        "reference": "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html",
        "points": 1,
        "answers": [
            {"text": "A set of best practices for building on AWS", "is_correct": True},
            {"text": "A billing calculation tool", "is_correct": False},
            {"text": "A monitoring service", "is_correct": False},
            {"text": "A deployment automation tool", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides a fully managed NoSQL database?",
        "explanation": "Amazon DynamoDB is AWS's fully managed NoSQL database service that provides fast and predictable performance with seamless scalability.",
        "reference": "https://docs.aws.amazon.com/dynamodb/",
        "points": 1,
        "answers": [
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon DynamoDB", "is_correct": True},
            {"text": "Amazon Redshift", "is_correct": False},
            {"text": "Amazon Aurora", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum size of a single object that can be stored in Amazon S3?",
        "explanation": "The maximum size of a single S3 object is 5 TB (terabytes).",
        "reference": "https://docs.aws.amazon.com/s3/",
        "points": 1,
        "answers": [
            {"text": "5 GB", "is_correct": False},
            {"text": "5 TB", "is_correct": True},
            {"text": "1 TB", "is_correct": False},
            {"text": "100 GB", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for content delivery and caching?",
        "explanation": "Amazon CloudFront is a fast content delivery network (CDN) service that securely delivers data, videos, applications, and APIs to customers globally.",
        "reference": "https://docs.aws.amazon.com/cloudfront/",
        "points": 1,
        "answers": [
            {"text": "Amazon Route 53", "is_correct": False},
            {"text": "Amazon CloudFront", "is_correct": True},
            {"text": "AWS Global Accelerator", "is_correct": False},
            {"text": "Amazon API Gateway", "is_correct": False},
        ],
    },
    {
        "text": "What does AWS IAM stand for?",
        "explanation": "AWS IAM stands for Identity and Access Management, which enables you to manage access to AWS services and resources securely.",
        "reference": "https://docs.aws.amazon.com/iam/",
        "points": 1,
        "answers": [
            {"text": "Internet Access Management", "is_correct": False},
            {"text": "Identity and Access Management", "is_correct": True},
            {"text": "Infrastructure Application Management", "is_correct": False},
            {"text": "Internal Account Management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides virtual servers in the cloud?",
        "explanation": "Amazon EC2 (Elastic Compute Cloud) provides secure, resizable compute capacity in the cloud. It is designed to make web-scale cloud computing easier for developers.",
        "reference": "https://docs.aws.amazon.com/ec2/",
        "points": 1,
        "answers": [
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon EC2", "is_correct": True},
            {"text": "Amazon VPC", "is_correct": False},
            {"text": "Amazon Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is the AWS Free Tier?",
        "explanation": "The AWS Free Tier provides customers the ability to explore and try out AWS services free of charge up to specified limits for each service.",
        "reference": "https://aws.amazon.com/free/",
        "points": 1,
        "answers": [
            {"text": "A premium support plan", "is_correct": False},
            {
                "text": "A way to try AWS services for free within certain limits",
                "is_correct": True,
            },
            {"text": "A discount program for enterprises", "is_correct": False},
            {"text": "A certification training program", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for serverless computing?",
        "explanation": "AWS Lambda lets you run code without provisioning or managing servers. You pay only for the compute time you consume.",
        "reference": "https://docs.aws.amazon.com/lambda/",
        "points": 1,
        "answers": [
            {"text": "Amazon EC2", "is_correct": False},
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": True},
            {"text": "Amazon Lightsail", "is_correct": False},
        ],
    },
    {
        "text": "What are the three main cloud service models?",
        "explanation": "The three main cloud service models are Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS).",
        "reference": "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/types-of-cloud-computing.html",
        "points": 1,
        "answers": [
            {"text": "Public, Private, Hybrid", "is_correct": False},
            {"text": "IaaS, PaaS, SaaS", "is_correct": True},
            {"text": "Compute, Storage, Network", "is_correct": False},
            {"text": "Basic, Standard, Premium", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for DNS management?",
        "explanation": "Amazon Route 53 is a highly available and scalable cloud Domain Name System (DNS) web service.",
        "reference": "https://docs.aws.amazon.com/route53/",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudFront", "is_correct": False},
            {"text": "Amazon Route 53", "is_correct": True},
            {"text": "AWS Direct Connect", "is_correct": False},
            {"text": "Amazon VPC", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon RDS?",
        "explanation": "Amazon Relational Database Service (RDS) makes it easy to set up, operate, and scale a relational database in the cloud.",
        "reference": "https://docs.aws.amazon.com/rds/",
        "points": 1,
        "answers": [
            {"text": "A NoSQL database service", "is_correct": False},
            {"text": "A managed relational database service", "is_correct": True},
            {"text": "A data warehousing service", "is_correct": False},
            {"text": "A file storage service", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS support plan provides 24/7 technical support via phone, email, and chat?",
        "explanation": "AWS Business Support provides 24/7 technical support via phone, email, and chat, along with architectural guidance and best practices.",
        "reference": "https://aws.amazon.com/support/plans/",
        "points": 1,
        "answers": [
            {"text": "Basic Support", "is_correct": False},
            {"text": "Developer Support", "is_correct": False},
            {"text": "Business Support", "is_correct": True},
            {"text": "Enterprise Support", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary benefit of using AWS Availability Zones?",
        "explanation": "Availability Zones provide high availability and fault tolerance by allowing you to distribute your applications across multiple isolated data centers.",
        "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html",
        "points": 1,
        "answers": [
            {"text": "Lower costs", "is_correct": False},
            {"text": "High availability and fault tolerance", "is_correct": True},
            {"text": "Faster performance", "is_correct": False},
            {"text": "Easier management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides object storage?",
        "explanation": "Amazon S3 (Simple Storage Service) provides object storage through a web service interface, designed to store and retrieve any amount of data from anywhere on the web.",
        "reference": "https://docs.aws.amazon.com/s3/",
        "points": 1,
        "answers": [
            {"text": "Amazon EBS", "is_correct": False},
            {"text": "Amazon EFS", "is_correct": False},
            {"text": "Amazon S3", "is_correct": True},
            {"text": "Amazon Glacier", "is_correct": False},
        ],
    },
    {
        "text": "What is the AWS Shared Responsibility Model?",
        "explanation": "The AWS Shared Responsibility Model defines what security responsibilities AWS handles and what responsibilities belong to the customer.",
        "reference": "https://aws.amazon.com/compliance/shared-responsibility-model/",
        "points": 1,
        "answers": [
            {"text": "A pricing model for shared resources", "is_correct": False},
            {
                "text": "A security model defining AWS and customer responsibilities",
                "is_correct": True,
            },
            {"text": "A collaboration tool for teams", "is_correct": False},
            {"text": "A data sharing agreement", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for monitoring and observability?",
        "explanation": "Amazon CloudWatch is a monitoring and observability service that provides data and actionable insights to monitor applications, respond to performance changes, and optimize resource utilization.",
        "reference": "https://docs.aws.amazon.com/cloudwatch/",
        "points": 1,
        "answers": [
            {"text": "AWS Config", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": True},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon Inspector", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between horizontal and vertical scaling?",
        "explanation": "Horizontal scaling (scale out) means adding more instances to handle increased load, while vertical scaling (scale up) means increasing the capacity of existing instances.",
        "reference": "https://docs.aws.amazon.com/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html",
        "points": 1,
        "answers": [
            {
                "text": "Horizontal scaling adds more instances, vertical scaling increases instance capacity",
                "is_correct": True,
            },
            {
                "text": "Horizontal scaling increases instance capacity, vertical scaling adds more instances",
                "is_correct": False,
            },
            {"text": "Both are the same thing", "is_correct": False},
            {
                "text": "Horizontal scaling is for storage, vertical scaling is for compute",
                "is_correct": False,
            },
        ],
    },
    {
        "text": "Which AWS service provides a virtual private cloud?",
        "explanation": "Amazon VPC (Virtual Private Cloud) lets you provision a logically isolated section of the AWS Cloud where you can launch AWS resources in a virtual network.",
        "reference": "https://docs.aws.amazon.com/vpc/",
        "points": 1,
        "answers": [
            {"text": "Amazon EC2", "is_correct": False},
            {"text": "Amazon VPC", "is_correct": True},
            {"text": "AWS Direct Connect", "is_correct": False},
            {"text": "Amazon Route 53", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CloudFormation used for?",
        "explanation": "AWS CloudFormation gives you an easy way to model and set up your AWS resources using templates, so you can spend less time managing resources and more time focusing on your applications.",
        "reference": "https://docs.aws.amazon.com/cloudformation/",
        "points": 1,
        "answers": [
            {"text": "Monitoring applications", "is_correct": False},
            {
                "text": "Infrastructure as Code - managing resources with templates",
                "is_correct": True,
            },
            {"text": "Content delivery", "is_correct": False},
            {"text": "Database management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides block storage for EC2 instances?",
        "explanation": "Amazon EBS (Elastic Block Store) provides high-performance block storage service designed for use with Amazon EC2 instances.",
        "reference": "https://docs.aws.amazon.com/ebs/",
        "points": 1,
        "answers": [
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon EBS", "is_correct": True},
            {"text": "Amazon EFS", "is_correct": False},
            {"text": "Amazon Glacier", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Auto Scaling?",
        "explanation": "AWS Auto Scaling monitors your applications and automatically adjusts capacity to maintain steady, predictable performance at the lowest possible cost.",
        "reference": "https://docs.aws.amazon.com/autoscaling/",
        "points": 1,
        "answers": [
            {
                "text": "To automatically adjust capacity based on demand",
                "is_correct": True,
            },
            {"text": "To backup data automatically", "is_correct": False},
            {"text": "To encrypt data at rest", "is_correct": False},
            {"text": "To manage user permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for data warehousing?",
        "explanation": "Amazon Redshift is a fast, scalable data warehouse that makes it simple and cost-effective to analyze all your data using standard SQL.",
        "reference": "https://docs.aws.amazon.com/redshift/",
        "points": 1,
        "answers": [
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": True},
            {"text": "Amazon ElastiCache", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon ElastiCache used for?",
        "explanation": "Amazon ElastiCache is a web service that makes it easy to deploy, operate, and scale an in-memory cache in the cloud.",
        "reference": "https://docs.aws.amazon.com/elasticache/",
        "points": 1,
        "answers": [
            {"text": "File storage", "is_correct": False},
            {"text": "In-memory caching", "is_correct": True},
            {"text": "Data archiving", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides file storage that can be mounted on multiple EC2 instances?",
        "explanation": "Amazon EFS (Elastic File System) provides a simple, scalable, fully managed elastic NFS file system for use with AWS services and on-premises resources.",
        "reference": "https://docs.aws.amazon.com/efs/",
        "points": 1,
        "answers": [
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon EBS", "is_correct": False},
            {"text": "Amazon EFS", "is_correct": True},
            {"text": "Amazon Glacier", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CloudTrail used for?",
        "explanation": "AWS CloudTrail is a service that enables governance, compliance, operational auditing, and risk auditing of your AWS account by logging API calls.",
        "reference": "https://docs.aws.amazon.com/cloudtrail/",
        "points": 1,
        "answers": [
            {"text": "Monitoring application performance", "is_correct": False},
            {"text": "Logging API calls and user activities", "is_correct": True},
            {"text": "Content delivery", "is_correct": False},
            {"text": "Database management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides a managed Kubernetes service?",
        "explanation": "Amazon EKS (Elastic Kubernetes Service) is a managed service that makes it easy for you to run Kubernetes on AWS without needing to install and operate your own Kubernetes clusters.",
        "reference": "https://docs.aws.amazon.com/eks/",
        "points": 1,
        "answers": [
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "Amazon EKS", "is_correct": True},
            {"text": "AWS Batch", "is_correct": False},
            {"text": "AWS Fargate", "is_correct": False},
        ],
    },
    {
        "text": "What is the AWS pricing model based on?",
        "explanation": "AWS uses a pay-as-you-go pricing model, meaning you only pay for the resources you actually use with no upfront costs or long-term commitments.",
        "reference": "https://aws.amazon.com/pricing/",
        "points": 1,
        "answers": [
            {"text": "Fixed monthly fees", "is_correct": False},
            {"text": "Pay-as-you-go for resources used", "is_correct": True},
            {"text": "Annual subscription only", "is_correct": False},
            {"text": "Per-user licensing", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides machine learning capabilities without requiring ML expertise?",
        "explanation": "Amazon SageMaker is a fully managed service that provides every developer and data scientist with the ability to build, train, and deploy machine learning models quickly.",
        "reference": "https://docs.aws.amazon.com/sagemaker/",
        "points": 1,
        "answers": [
            {"text": "Amazon Rekognition", "is_correct": False},
            {"text": "Amazon SageMaker", "is_correct": True},
            {"text": "Amazon Comprehend", "is_correct": False},
            {"text": "Amazon Polly", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Glacier used for?",
        "explanation": "Amazon S3 Glacier is a storage class for data archiving and long-term backup that provides secure, durable, and extremely low-cost storage.",
        "reference": "https://docs.aws.amazon.com/glacier/",
        "points": 1,
        "answers": [
            {"text": "Real-time data processing", "is_correct": False},
            {"text": "Data archiving and long-term backup", "is_correct": True},
            {"text": "Content delivery", "is_correct": False},
            {"text": "Database caching", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for API management?",
        "explanation": "Amazon API Gateway is a fully managed service that makes it easy for developers to create, publish, maintain, monitor, and secure APIs at any scale.",
        "reference": "https://docs.aws.amazon.com/apigateway/",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudFront", "is_correct": False},
            {"text": "Amazon API Gateway", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon Route 53", "is_correct": False},
        ],
    },
    {
        "text": "What is the benefit of using Reserved Instances?",
        "explanation": "Reserved Instances provide significant discounts (up to 75%) compared to On-Demand pricing in exchange for a commitment to use EC2 instances for a 1 or 3-year term.",
        "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-reserved-instances.html",
        "points": 1,
        "answers": [
            {"text": "Better performance", "is_correct": False},
            {
                "text": "Significant cost savings for committed usage",
                "is_correct": True,
            },
            {"text": "Higher availability", "is_correct": False},
            {"text": "More storage space", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides email sending capabilities?",
        "explanation": "Amazon SES (Simple Email Service) is a cloud-based email sending service designed to help digital marketers and application developers send marketing, notification, and transactional emails.",
        "reference": "https://docs.aws.amazon.com/ses/",
        "points": 1,
        "answers": [
            {"text": "Amazon SNS", "is_correct": False},
            {"text": "Amazon SES", "is_correct": True},
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon WorkMail", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Organizations used for?",
        "explanation": "AWS Organizations helps you centrally govern your environment as you grow and scale your workloads on AWS by managing multiple AWS accounts.",
        "reference": "https://docs.aws.amazon.com/organizations/",
        "points": 1,
        "answers": [
            {"text": "Managing multiple AWS accounts", "is_correct": True},
            {"text": "Monitoring applications", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
            {"text": "Database replication", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed message queuing?",
        "explanation": "Amazon SQS (Simple Queue Service) is a fully managed message queuing service that enables you to decouple and scale microservices, distributed systems, and serverless applications.",
        "reference": "https://docs.aws.amazon.com/sqs/",
        "points": 1,
        "answers": [
            {"text": "Amazon SNS", "is_correct": False},
            {"text": "Amazon SQS", "is_correct": True},
            {"text": "Amazon SES", "is_correct": False},
            {"text": "Amazon Kinesis", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Config?",
        "explanation": "AWS Config is a service that enables you to assess, audit, and evaluate the configurations of your AWS resources for compliance and governance.",
        "reference": "https://docs.aws.amazon.com/config/",
        "points": 1,
        "answers": [
            {"text": "Performance monitoring", "is_correct": False},
            {"text": "Configuration assessment and compliance", "is_correct": True},
            {"text": "Cost optimization", "is_correct": False},
            {"text": "User authentication", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides container orchestration without managing servers?",
        "explanation": "AWS Fargate is a serverless compute engine for containers that works with both Amazon ECS and Amazon EKS, allowing you to run containers without managing servers.",
        "reference": "https://docs.aws.amazon.com/fargate/",
        "points": 1,
        "answers": [
            {"text": "Amazon EC2", "is_correct": False},
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "AWS Fargate", "is_correct": True},
            {"text": "AWS Batch", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Rekognition used for?",
        "explanation": "Amazon Rekognition makes it easy to add image and video analysis to your applications using proven, highly scalable, deep learning technology.",
        "reference": "https://docs.aws.amazon.com/rekognition/",
        "points": 1,
        "answers": [
            {"text": "Text analysis", "is_correct": False},
            {"text": "Image and video analysis", "is_correct": True},
            {"text": "Voice recognition", "is_correct": False},
            {"text": "Database optimization", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides publish/subscribe messaging?",
        "explanation": "Amazon SNS (Simple Notification Service) is a fully managed messaging service for both application-to-application (A2A) and application-to-person (A2P) communication.",
        "reference": "https://docs.aws.amazon.com/sns/",
        "points": 1,
        "answers": [
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon SNS", "is_correct": True},
            {"text": "Amazon SES", "is_correct": False},
            {"text": "Amazon Kinesis", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between a Region and an Availability Zone?",
        "explanation": "A Region is a physical location with multiple Availability Zones. An Availability Zone is one or more discrete data centers with redundant power, networking, and connectivity.",
        "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html",
        "points": 1,
        "answers": [
            {"text": "Regions contain multiple Availability Zones", "is_correct": True},
            {
                "text": "Availability Zones contain multiple Regions",
                "is_correct": False,
            },
            {"text": "They are the same thing", "is_correct": False},
            {"text": "Regions are virtual, AZs are physical", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides real-time data streaming?",
        "explanation": "Amazon Kinesis makes it easy to collect, process, and analyze real-time, streaming data so you can get timely insights and react quickly to new information.",
        "reference": "https://docs.aws.amazon.com/kinesis/",
        "points": 1,
        "answers": [
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon SNS", "is_correct": False},
            {"text": "Amazon Kinesis", "is_correct": True},
            {"text": "AWS Batch", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Direct Connect?",
        "explanation": "AWS Direct Connect is a cloud service solution that makes it easy to establish a dedicated network connection from your premises to AWS.",
        "reference": "https://docs.aws.amazon.com/directconnect/",
        "points": 1,
        "answers": [
            {"text": "A VPN service", "is_correct": False},
            {"text": "A dedicated network connection to AWS", "is_correct": True},
            {"text": "A content delivery network", "is_correct": False},
            {"text": "A database connection service", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for text-to-speech conversion?",
        "explanation": "Amazon Polly is a service that turns text into lifelike speech, allowing you to create applications that talk and build entirely new categories of speech-enabled products.",
        "reference": "https://docs.aws.amazon.com/polly/",
        "points": 1,
        "answers": [
            {"text": "Amazon Transcribe", "is_correct": False},
            {"text": "Amazon Polly", "is_correct": True},
            {"text": "Amazon Comprehend", "is_correct": False},
            {"text": "Amazon Rekognition", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS CloudShell?",
        "explanation": "AWS CloudShell is a browser-based shell that makes it easy to securely manage, explore, and interact with your AWS resources using a pre-authenticated shell.",
        "reference": "https://docs.aws.amazon.com/cloudshell/",
        "points": 1,
        "answers": [
            {"text": "Virtual desktop service", "is_correct": False},
            {"text": "Browser-based shell for AWS management", "is_correct": True},
            {"text": "Container orchestration", "is_correct": False},
            {"text": "File sharing service", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides speech-to-text capabilities?",
        "explanation": "Amazon Transcribe is an automatic speech recognition (ASR) service that makes it easy for developers to add speech-to-text capability to their applications.",
        "reference": "https://docs.aws.amazon.com/transcribe/",
        "points": 1,
        "answers": [
            {"text": "Amazon Polly", "is_correct": False},
            {"text": "Amazon Transcribe", "is_correct": True},
            {"text": "Amazon Comprehend", "is_correct": False},
            {"text": "Amazon Translate", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Systems Manager used for?",
        "explanation": "AWS Systems Manager gives you visibility and control of your infrastructure on AWS, helping you manage your applications and infrastructure running on AWS.",
        "reference": "https://docs.aws.amazon.com/systems-manager/",
        "points": 1,
        "answers": [
            {"text": "Database management", "is_correct": False},
            {"text": "Infrastructure management and control", "is_correct": True},
            {"text": "User authentication", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides natural language processing?",
        "explanation": "Amazon Comprehend is a natural language processing (NLP) service that uses machine learning to find insights and relationships in text.",
        "reference": "https://docs.aws.amazon.com/comprehend/",
        "points": 1,
        "answers": [
            {"text": "Amazon Polly", "is_correct": False},
            {"text": "Amazon Transcribe", "is_correct": False},
            {"text": "Amazon Comprehend", "is_correct": True},
            {"text": "Amazon Translate", "is_correct": False},
        ],
    },
    {
        "text": "What is the benefit of using Spot Instances?",
        "explanation": "Spot Instances let you take advantage of unused EC2 capacity in the AWS cloud at up to 90% discount compared to On-Demand prices.",
        "reference": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html",
        "points": 1,
        "answers": [
            {"text": "Guaranteed availability", "is_correct": False},
            {"text": "Up to 90% cost savings", "is_correct": True},
            {"text": "Better performance", "is_correct": False},
            {"text": "More storage", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides language translation?",
        "explanation": "Amazon Translate is a neural machine translation service that delivers fast, high-quality, and affordable language translation.",
        "reference": "https://docs.aws.amazon.com/translate/",
        "points": 1,
        "answers": [
            {"text": "Amazon Polly", "is_correct": False},
            {"text": "Amazon Comprehend", "is_correct": False},
            {"text": "Amazon Transcribe", "is_correct": False},
            {"text": "Amazon Translate", "is_correct": True},
        ],
    },
    {
        "text": "What is AWS CodeCommit used for?",
        "explanation": "AWS CodeCommit is a fully-managed source control service that hosts secure Git-based repositories, making it easy for teams to collaborate on code.",
        "reference": "https://docs.aws.amazon.com/codecommit/",
        "points": 1,
        "answers": [
            {"text": "Code deployment", "is_correct": False},
            {"text": "Source control and Git repositories", "is_correct": True},
            {"text": "Code testing", "is_correct": False},
            {"text": "Performance monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides continuous integration and deployment?",
        "explanation": "AWS CodePipeline is a fully managed continuous delivery service that helps you automate your release pipelines for fast and reliable application and infrastructure updates.",
        "reference": "https://docs.aws.amazon.com/codepipeline/",
        "points": 1,
        "answers": [
            {"text": "AWS CodeCommit", "is_correct": False},
            {"text": "AWS CodePipeline", "is_correct": True},
            {"text": "AWS CodeDeploy", "is_correct": False},
            {"text": "AWS CodeBuild", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Lightsail?",
        "explanation": "Amazon Lightsail is designed to be the easiest way to launch and manage a virtual private server with AWS, offering easy-to-use cloud platform for simple workloads.",
        "reference": "https://docs.aws.amazon.com/lightsail/",
        "points": 1,
        "answers": [
            {"text": "A database service", "is_correct": False},
            {"text": "A simple virtual private server platform", "is_correct": True},
            {"text": "A content delivery network", "is_correct": False},
            {"text": "A monitoring service", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides disaster recovery solutions?",
        "explanation": "AWS Backup is a centralized backup service that makes it easy and cost-effective to back up your application data across AWS services in the AWS Cloud and on premises.",
        "reference": "https://docs.aws.amazon.com/backup/",
        "points": 1,
        "answers": [
            {"text": "AWS CloudFormation", "is_correct": False},
            {"text": "AWS Backup", "is_correct": True},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
        ],
    },
    {
        "text": "What is the AWS CLI?",
        "explanation": "The AWS Command Line Interface (CLI) is a unified tool to manage your AWS services from the command line and automate them through scripts.",
        "reference": "https://docs.aws.amazon.com/cli/",
        "points": 1,
        "answers": [
            {"text": "A web-based management console", "is_correct": False},
            {
                "text": "A command-line tool for managing AWS services",
                "is_correct": True,
            },
            {"text": "A mobile application", "is_correct": False},
            {"text": "A desktop software", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides workforce identity federation?",
        "explanation": "AWS Single Sign-On (SSO) makes it easy to centrally manage access to multiple AWS accounts and business applications and provide users with single sign-on access.",
        "reference": "https://docs.aws.amazon.com/singlesignon/",
        "points": 1,
        "answers": [
            {"text": "AWS IAM", "is_correct": False},
            {"text": "AWS SSO", "is_correct": True},
            {"text": "AWS Cognito", "is_correct": False},
            {"text": "AWS Directory Service", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Aurora?",
        "explanation": "Amazon Aurora is a MySQL and PostgreSQL-compatible relational database built for the cloud that combines the performance and availability of traditional enterprise databases with the simplicity and cost-effectiveness of open source databases.",
        "reference": "https://docs.aws.amazon.com/aurora/",
        "points": 1,
        "answers": [
            {"text": "A NoSQL database", "is_correct": False},
            {
                "text": "A MySQL and PostgreSQL-compatible relational database",
                "is_correct": True,
            },
            {"text": "A data warehouse service", "is_correct": False},
            {"text": "A caching service", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides user authentication for web and mobile apps?",
        "explanation": "Amazon Cognito lets you add user sign-up, sign-in, and access control to your web and mobile apps quickly and easily.",
        "reference": "https://docs.aws.amazon.com/cognito/",
        "points": 1,
        "answers": [
            {"text": "AWS IAM", "is_correct": False},
            {"text": "Amazon Cognito", "is_correct": True},
            {"text": "AWS SSO", "is_correct": False},
            {"text": "AWS Directory Service", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Trusted Advisor?",
        "explanation": "AWS Trusted Advisor provides recommendations that help you follow AWS best practices by analyzing your AWS environment and providing guidance on cost optimization, performance, security, and fault tolerance.",
        "reference": "https://docs.aws.amazon.com/support/latest/user/trusted-advisor.html",
        "points": 1,
        "answers": [
            {"text": "A monitoring service", "is_correct": False},
            {
                "text": "A service that provides best practice recommendations",
                "is_correct": True,
            },
            {"text": "A backup service", "is_correct": False},
            {"text": "A deployment service", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides batch computing?",
        "explanation": "AWS Batch enables developers, scientists, and engineers to easily and efficiently run hundreds of thousands of batch computing jobs on AWS.",
        "reference": "https://docs.aws.amazon.com/batch/",
        "points": 1,
        "answers": [
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "AWS Batch", "is_correct": True},
            {"text": "Amazon EC2", "is_correct": False},
            {"text": "AWS Fargate", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Resource Access Manager (RAM)?",
        "explanation": "AWS Resource Access Manager (RAM) helps you securely share your resources across AWS accounts, organizational units (OUs), and with IAM users and roles.",
        "reference": "https://docs.aws.amazon.com/ram/",
        "points": 1,
        "answers": [
            {"text": "Managing user permissions", "is_correct": False},
            {"text": "Sharing resources across AWS accounts", "is_correct": True},
            {"text": "Monitoring resource usage", "is_correct": False},
            {"text": "Backing up resources", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed blockchain networks?",
        "explanation": "Amazon Managed Blockchain is a fully managed service that makes it easy to create and manage scalable blockchain networks using popular open source frameworks.",
        "reference": "https://docs.aws.amazon.com/managed-blockchain/",
        "points": 1,
        "answers": [
            {"text": "Amazon QLDB", "is_correct": False},
            {"text": "Amazon Managed Blockchain", "is_correct": True},
            {"text": "AWS Database Migration Service", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon WorkSpaces?",
        "explanation": "Amazon WorkSpaces is a managed, secure Desktop-as-a-Service (DaaS) solution that runs on AWS and provides users with access to documents, applications, and resources from any supported device.",
        "reference": "https://docs.aws.amazon.com/workspaces/",
        "points": 1,
        "answers": [
            {"text": "A file sharing service", "is_correct": False},
            {"text": "A managed desktop-as-a-service solution", "is_correct": True},
            {"text": "A collaborative workspace", "is_correct": False},
            {"text": "A development environment", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides quantum computing capabilities?",
        "explanation": "Amazon Braket is a fully managed quantum computing service that helps researchers and developers get started with quantum computing.",
        "reference": "https://docs.aws.amazon.com/braket/",
        "points": 1,
        "answers": [
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon Braket", "is_correct": True},
            {"text": "Amazon SageMaker", "is_correct": False},
            {"text": "AWS Batch", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Cost Explorer used for?",
        "explanation": "AWS Cost Explorer has an easy-to-use interface that lets you visualize, understand, and manage your AWS costs and usage over time.",
        "reference": "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html",
        "points": 1,
        "answers": [
            {"text": "Monitoring application performance", "is_correct": False},
            {"text": "Visualizing and managing AWS costs", "is_correct": True},
            {"text": "Exploring AWS services", "is_correct": False},
            {"text": "Managing user access", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides distributed tracing for applications?",
        "explanation": "AWS X-Ray helps developers analyze and debug production, distributed applications, such as those built using a microservices architecture.",
        "reference": "https://docs.aws.amazon.com/xray/",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS X-Ray", "is_correct": True},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon Inspector", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Secrets Manager used for?",
        "explanation": "AWS Secrets Manager helps you protect secrets needed to access your applications, services, and IT resources by enabling you to easily rotate, manage, and retrieve database credentials, API keys, and other secrets.",
        "reference": "https://docs.aws.amazon.com/secretsmanager/",
        "points": 1,
        "answers": [
            {"text": "Managing user passwords", "is_correct": False},
            {"text": "Storing and managing application secrets", "is_correct": True},
            {"text": "Encrypting data", "is_correct": False},
            {"text": "Managing SSL certificates", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Apache Kafka?",
        "explanation": "Amazon MSK (Managed Streaming for Apache Kafka) is a fully managed service that makes it easy for you to build and run applications that use Apache Kafka to process streaming data.",
        "reference": "https://docs.aws.amazon.com/msk/",
        "points": 1,
        "answers": [
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "Amazon MSK", "is_correct": True},
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon SNS", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Personal Health Dashboard?",
        "explanation": "AWS Personal Health Dashboard provides alerts and remediation guidance when AWS is experiencing events that may impact you, giving you personalized view into the performance and availability of AWS services.",
        "reference": "https://docs.aws.amazon.com/health/",
        "points": 1,
        "answers": [
            {"text": "Monitoring application health", "is_correct": False},
            {
                "text": "Providing personalized AWS service health information",
                "is_correct": True,
            },
            {"text": "Managing user health records", "is_correct": False},
            {"text": "Tracking fitness data", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Elasticsearch?",
        "explanation": "Amazon OpenSearch Service (successor to Amazon Elasticsearch Service) makes it easy to deploy, secure, and run Elasticsearch cost effectively at scale.",
        "reference": "https://docs.aws.amazon.com/opensearch-service/",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudSearch", "is_correct": False},
            {"text": "Amazon OpenSearch Service", "is_correct": True},
            {"text": "Amazon Kendra", "is_correct": False},
            {"text": "AWS CloudFormation", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Application Load Balancer used for?",
        "explanation": "Application Load Balancer operates at the request level (layer 7), routing traffic to targets based on the content of the request, ideal for advanced load balancing of HTTP and HTTPS traffic.",
        "reference": "https://docs.aws.amazon.com/elasticloadbalancing/latest/application/",
        "points": 1,
        "answers": [
            {"text": "Balancing network traffic at layer 4", "is_correct": False},
            {"text": "Balancing HTTP/HTTPS traffic at layer 7", "is_correct": True},
            {"text": "Managing DNS routing", "is_correct": False},
            {"text": "Caching content", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides intelligent document processing?",
        "explanation": "Amazon Textract is a service that automatically extracts text and data from scanned documents and goes beyond simple optical character recognition (OCR) to also identify the contents of fields in forms and information stored in tables.",
        "reference": "https://docs.aws.amazon.com/textract/",
        "points": 1,
        "answers": [
            {"text": "Amazon Comprehend", "is_correct": False},
            {"text": "Amazon Textract", "is_correct": True},
            {"text": "Amazon Rekognition", "is_correct": False},
            {"text": "Amazon Transcribe", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS DataSync used for?",
        "explanation": "AWS DataSync is a data transfer service that makes it easy for you to automate moving data between on-premises storage and Amazon S3, Amazon EFS, or Amazon FSx.",
        "reference": "https://docs.aws.amazon.com/datasync/",
        "points": 1,
        "answers": [
            {"text": "Database synchronization", "is_correct": False},
            {"text": "Data transfer between on-premises and AWS", "is_correct": True},
            {"text": "Real-time data streaming", "is_correct": False},
            {"text": "Data encryption", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed time series database?",
        "explanation": "Amazon Timestream is a fast, scalable, and serverless time series database service for IoT and operational applications that makes it easy to store and analyze trillions of events per day.",
        "reference": "https://docs.aws.amazon.com/timestream/",
        "points": 1,
        "answers": [
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon Timestream", "is_correct": True},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": False},
        ],
    },
    {
        "text": "What is the AWS Snow Family used for?",
        "explanation": "The AWS Snow Family is a collection of physical devices that help migrate data into and out of AWS when transferring data over the internet would be too slow, difficult, or costly.",
        "reference": "https://docs.aws.amazon.com/snow/",
        "points": 1,
        "answers": [
            {"text": "Weather monitoring", "is_correct": False},
            {"text": "Physical data migration devices", "is_correct": True},
            {"text": "Cold storage solutions", "is_correct": False},
            {"text": "Network security appliances", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides edge computing capabilities?",
        "explanation": "AWS IoT Greengrass extends AWS to edge devices so they can act locally on the data they generate, while still using the cloud for management, analytics, and durable storage.",
        "reference": "https://docs.aws.amazon.com/greengrass/",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudFront", "is_correct": False},
            {"text": "AWS IoT Greengrass", "is_correct": True},
            {"text": "AWS Lambda@Edge", "is_correct": False},
            {"text": "Amazon EC2", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon EventBridge used for?",
        "explanation": "Amazon EventBridge is a serverless event bus that makes it easy to connect applications together using data from your own applications, integrated Software-as-a-Service (SaaS) applications, and AWS services.",
        "reference": "https://docs.aws.amazon.com/eventbridge/",
        "points": 1,
        "answers": [
            {"text": "Network bridging", "is_correct": False},
            {"text": "Serverless event routing", "is_correct": True},
            {"text": "Database connections", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Apache Airflow?",
        "explanation": "Amazon Managed Workflows for Apache Airflow (MWAA) is a managed orchestration service for Apache Airflow that makes it easier to set up and operate end-to-end data pipelines in the cloud.",
        "reference": "https://docs.aws.amazon.com/mwaa/",
        "points": 1,
        "answers": [
            {"text": "AWS Step Functions", "is_correct": False},
            {"text": "Amazon MWAA", "is_correct": True},
            {"text": "AWS Batch", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Control Tower used for?",
        "explanation": "AWS Control Tower provides the easiest way to set up and govern a secure, multi-account AWS environment based on best practices established through AWS's experience working with thousands of enterprises.",
        "reference": "https://docs.aws.amazon.com/controltower/",
        "points": 1,
        "answers": [
            {"text": "Application monitoring", "is_correct": False},
            {"text": "Multi-account governance and setup", "is_correct": True},
            {"text": "Network traffic control", "is_correct": False},
            {"text": "Database administration", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides contact center solutions?",
        "explanation": "Amazon Connect is an easy to use omnichannel cloud contact center that helps companies provide superior customer service at a lower cost.",
        "reference": "https://docs.aws.amazon.com/connect/",
        "points": 1,
        "answers": [
            {"text": "Amazon Chime", "is_correct": False},
            {"text": "Amazon Connect", "is_correct": True},
            {"text": "Amazon WorkSpaces", "is_correct": False},
            {"text": "Amazon SES", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Lake Formation used for?",
        "explanation": "AWS Lake Formation makes it easy to set up a secure data lake in days, allowing you to collect and catalog data from databases and object storage, move it into your data lake, and clean and classify it using machine learning algorithms.",
        "reference": "https://docs.aws.amazon.com/lake-formation/",
        "points": 1,
        "answers": [
            {"text": "Creating virtual lakes", "is_correct": False},
            {"text": "Setting up and managing secure data lakes", "is_correct": True},
            {"text": "Water resource management", "is_correct": False},
            {"text": "Geographic mapping", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS pricing model offers the highest discount for EC2 instances?",
        "explanation": "Savings Plans offer significant savings over On-Demand pricing in exchange for a commitment to use a specific amount of compute power for a 1 or 3-year period, providing up to 72% savings.",
        "reference": "https://docs.aws.amazon.com/savingsplans/",
        "points": 1,
        "answers": [
            {"text": "On-Demand", "is_correct": False},
            {"text": "Reserved Instances", "is_correct": False},
            {"text": "Spot Instances", "is_correct": False},
            {"text": "Savings Plans", "is_correct": True},
        ],
    },
    {
        "text": "What is the primary purpose of AWS Global Accelerator?",
        "explanation": "AWS Global Accelerator is a networking service that improves the availability and performance of the applications that you offer to your global users by using the AWS global network infrastructure.",
        "reference": "https://docs.aws.amazon.com/global-accelerator/",
        "points": 1,
        "answers": [
            {"text": "Content caching", "is_correct": False},
            {"text": "Improving global application performance", "is_correct": True},
            {"text": "Database acceleration", "is_correct": False},
            {"text": "CPU performance enhancement", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for hybrid cloud storage?",
        "explanation": "AWS Storage Gateway connects an on-premises environment to AWS cloud storage services like S3, providing seamless integration between on-premises and cloud storage.",
        "reference": "https://docs.aws.amazon.com/storagegateway/",
        "points": 1,
        "answers": [
            {"text": "AWS Direct Connect", "is_correct": False},
            {"text": "AWS Storage Gateway", "is_correct": True},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "AWS DataSync", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Neptune used for?",
        "explanation": "Amazon Neptune is a fast, reliable, fully-managed graph database service that makes it easy to build and run applications that work with highly connected datasets.",
        "reference": "https://docs.aws.amazon.com/neptune/",
        "points": 1,
        "answers": [
            {"text": "Time series data", "is_correct": False},
            {"text": "Graph databases", "is_correct": True},
            {"text": "Document databases", "is_correct": False},
            {"text": "Key-value storage", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Apache Spark?",
        "explanation": "Amazon EMR (Elastic MapReduce) is a managed cluster platform that simplifies running big data frameworks, such as Apache Hadoop and Apache Spark, on AWS.",
        "reference": "https://docs.aws.amazon.com/emr/",
        "points": 1,
        "answers": [
            {"text": "AWS Glue", "is_correct": False},
            {"text": "Amazon EMR", "is_correct": True},
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "AWS Batch", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Certificate Manager used for?",
        "explanation": "AWS Certificate Manager is a service that lets you easily provision, manage, and deploy public and private Secure Sockets Layer/Transport Layer Security (SSL/TLS) certificates.",
        "reference": "https://docs.aws.amazon.com/acm/",
        "points": 1,
        "answers": [
            {"text": "Managing user certificates", "is_correct": False},
            {
                "text": "Provisioning and managing SSL/TLS certificates",
                "is_correct": True,
            },
            {"text": "Certifying applications", "is_correct": False},
            {"text": "Academic certification management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed MongoDB?",
        "explanation": "Amazon DocumentDB is a fast, scalable, highly available, and fully managed document database service that supports MongoDB workloads.",
        "reference": "https://docs.aws.amazon.com/documentdb/",
        "points": 1,
        "answers": [
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": True},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon ElastiCache", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Key Management Service (KMS) used for?",
        "explanation": "AWS KMS makes it easy for you to create and manage cryptographic keys and control their use across a wide range of AWS services and in your applications.",
        "reference": "https://docs.aws.amazon.com/kms/",
        "points": 1,
        "answers": [
            {"text": "Managing API keys", "is_correct": False},
            {"text": "Creating and managing encryption keys", "is_correct": True},
            {"text": "Password management", "is_correct": False},
            {"text": "SSH key management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides intelligent search capabilities?",
        "explanation": "Amazon Kendra is an intelligent search service powered by machine learning that enables users to search unstructured data using natural language.",
        "reference": "https://docs.aws.amazon.com/kendra/",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudSearch", "is_correct": False},
            {"text": "Amazon Kendra", "is_correct": True},
            {"text": "Amazon OpenSearch", "is_correct": False},
            {"text": "Amazon Comprehend", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Ground Station used for?",
        "explanation": "AWS Ground Station is a fully managed service that lets you control satellite communications, process data, and scale your operations without having to worry about building or managing your own ground station infrastructure.",
        "reference": "https://docs.aws.amazon.com/ground-station/",
        "points": 1,
        "answers": [
            {"text": "Weather monitoring", "is_correct": False},
            {"text": "Satellite communications", "is_correct": True},
            {"text": "Ground network connectivity", "is_correct": False},
            {"text": "Geographic mapping", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides ledger database capabilities?",
        "explanation": "Amazon QLDB (Quantum Ledger Database) is a fully managed ledger database that provides a transparent, immutable, and cryptographically verifiable transaction log.",
        "reference": "https://docs.aws.amazon.com/qldb/",
        "points": 1,
        "answers": [
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon QLDB", "is_correct": True},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon Managed Blockchain", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Macie used for?",
        "explanation": "Amazon Macie is a fully managed data security and data privacy service that uses machine learning and pattern matching to discover and protect your sensitive data in AWS.",
        "reference": "https://docs.aws.amazon.com/macie/",
        "points": 1,
        "answers": [
            {"text": "Network security", "is_correct": False},
            {"text": "Data security and privacy protection", "is_correct": True},
            {"text": "Application security", "is_correct": False},
            {"text": "Infrastructure security", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides distributed denial of service (DDoS) protection?",
        "explanation": "AWS Shield is a managed Distributed Denial of Service (DDoS) protection service that safeguards applications running on AWS.",
        "reference": "https://docs.aws.amazon.com/shield/",
        "points": 1,
        "answers": [
            {"text": "AWS WAF", "is_correct": False},
            {"text": "AWS Shield", "is_correct": True},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Security Hub", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Step Functions used for?",
        "explanation": "AWS Step Functions lets you coordinate multiple AWS services into serverless workflows so you can build and update apps quickly.",
        "reference": "https://docs.aws.amazon.com/step-functions/",
        "points": 1,
        "answers": [
            {"text": "Function deployment", "is_correct": False},
            {"text": "Serverless workflow orchestration", "is_correct": True},
            {"text": "Step-by-step tutorials", "is_correct": False},
            {"text": "Function monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides web application firewall capabilities?",
        "explanation": "AWS WAF is a web application firewall that helps protect your web applications or APIs against common web exploits that may affect availability, compromise security, or consume excessive resources.",
        "reference": "https://docs.aws.amazon.com/waf/",
        "points": 1,
        "answers": [
            {"text": "AWS Shield", "is_correct": False},
            {"text": "AWS WAF", "is_correct": True},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Security Hub", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon GuardDuty used for?",
        "explanation": "Amazon GuardDuty is a threat detection service that continuously monitors for malicious activity and unauthorized behavior to protect your AWS accounts and workloads.",
        "reference": "https://docs.aws.amazon.com/guardduty/",
        "points": 1,
        "answers": [
            {"text": "Performance monitoring", "is_correct": False},
            {"text": "Threat detection and security monitoring", "is_correct": True},
            {"text": "Cost monitoring", "is_correct": False},
            {"text": "Compliance monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides centralized security findings management?",
        "explanation": "AWS Security Hub gives you a comprehensive view of your security alerts and security posture across your AWS accounts by aggregating, organizing, and prioritizing security findings from multiple AWS security services.",
        "reference": "https://docs.aws.amazon.com/securityhub/",
        "points": 1,
        "answers": [
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Security Hub", "is_correct": True},
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Outposts used for?",
        "explanation": "AWS Outposts is a fully managed service that offers the same AWS infrastructure, AWS services, APIs, and tools to virtually any datacenter, co-location space, or on-premises facility.",
        "reference": "https://docs.aws.amazon.com/outposts/",
        "points": 1,
        "answers": [
            {"text": "Remote monitoring", "is_correct": False},
            {"text": "Bringing AWS infrastructure on-premises", "is_correct": True},
            {"text": "External storage", "is_correct": False},
            {"text": "Outdoor computing", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides container registry capabilities?",
        "explanation": "Amazon ECR (Elastic Container Registry) is a fully-managed Docker container registry that makes it easy for developers to store, manage, and deploy Docker container images.",
        "reference": "https://docs.aws.amazon.com/ecr/",
        "points": 1,
        "answers": [
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "Amazon ECR", "is_correct": True},
            {"text": "Amazon EKS", "is_correct": False},
            {"text": "AWS Fargate", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Data Pipeline used for?",
        "explanation": "AWS Data Pipeline is a web service that helps you reliably process and move data between different AWS compute and storage services, as well as on-premises data sources, at specified intervals.",
        "reference": "https://docs.aws.amazon.com/datapipeline/",
        "points": 1,
        "answers": [
            {"text": "Real-time streaming", "is_correct": False},
            {"text": "Data processing and movement workflows", "is_correct": True},
            {"text": "Network pipelines", "is_correct": False},
            {"text": "Application deployment", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides infrastructure security assessment?",
        "explanation": "Amazon Inspector is an automated security assessment service that helps improve the security and compliance of applications deployed on AWS by automatically assessing applications for exposure, vulnerabilities, and deviations from best practices.",
        "reference": "https://docs.aws.amazon.com/inspector/",
        "points": 1,
        "answers": [
            {"text": "AWS Config", "is_correct": False},
            {"text": "Amazon Inspector", "is_correct": True},
            {"text": "Amazon GuardDuty", "is_correct": False},
            {"text": "AWS Security Hub", "is_correct": False},
        ],
    },
]
