"""AWS Data Analytics Specialty Certification"""

CERTIFICATION = {
    "name": "AWS Certified Data Analytics - Specialty",
    "description": "Design and implement AWS data analytics services to derive value from data",
    "slug": "aws-data-analytics-specialty",
    "level": "Specialty",
    "duration": 186,
    "questions_count": 62,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which AWS service is best for real-time data streaming?",
        "explanation": "Amazon Kinesis is a platform for streaming data on AWS, offering powerful services to make it easy to load and analyze streaming data, and also providing the ability for you to build custom streaming data applications for specialized needs.",
        "reference": "https://docs.aws.amazon.com/kinesis/",
        "points": 1,
        "answers": [
            {"text": "Amazon Kinesis", "is_correct": True},
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Redshift primarily used for?",
        "explanation": "Amazon Redshift is a fast, scalable data warehouse that makes it simple and cost-effective to analyze all your data across your data warehouse and data lake.",
        "reference": "https://docs.aws.amazon.com/redshift/",
        "points": 1,
        "answers": [
            {"text": "Data warehousing and analytics", "is_correct": True},
            {"text": "Real-time streaming", "is_correct": False},
            {"text": "Object storage", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which service provides serverless interactive query service for S3?",
        "explanation": "Amazon Athena is an interactive query service that makes it easy to analyze data in Amazon S3 using standard SQL. Athena is serverless, so there is no infrastructure to manage, and you pay only for the queries that you run.",
        "reference": "https://docs.aws.amazon.com/athena/",
        "points": 1,
        "answers": [
            {"text": "Amazon Athena", "is_correct": True},
            {"text": "Amazon EMR", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Glue used for?",
        "explanation": "AWS Glue is a fully managed extract, transform, and load (ETL) service that makes it easy for customers to prepare and load their data for analytics.",
        "reference": "https://docs.aws.amazon.com/glue/",
        "points": 1,
        "answers": [
            {"text": "ETL (Extract, Transform, Load) operations", "is_correct": True},
            {"text": "Data visualization", "is_correct": False},
            {"text": "Real-time streaming", "is_correct": False},
            {"text": "Machine learning model training", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Apache Spark?",
        "explanation": "Amazon EMR is the industry-leading cloud big data platform for petabyte-scale data processing, interactive analytics, and machine learning using open-source frameworks such as Apache Spark, Apache Hive, and Presto.",
        "reference": "https://docs.aws.amazon.com/emr/",
        "points": 1,
        "answers": [
            {"text": "Amazon EMR", "is_correct": True},
            {"text": "AWS Glue", "is_correct": False},
            {"text": "Amazon Athena", "is_correct": False},
            {"text": "Amazon Kinesis", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum record size for Kinesis Data Streams?",
        "explanation": "The maximum size of a data record (including partition key and data blob) in Kinesis Data Streams is 1 MB. This includes the partition key and the data payload.",
        "reference": "https://docs.aws.amazon.com/kinesis/latest/dev/service-sizes-and-limits.html",
        "points": 1,
        "answers": [
            {"text": "1 MB", "is_correct": True},
            {"text": "256 KB", "is_correct": False},
            {"text": "5 MB", "is_correct": False},
            {"text": "10 MB", "is_correct": False},
        ],
    },
    {
        "text": "Which Kinesis service is best for loading streaming data into data stores?",
        "explanation": "Amazon Kinesis Data Firehose is the easiest way to reliably load streaming data into data lakes, data stores, and analytics services. It can capture, transform, and deliver streaming data to Amazon S3, Amazon Redshift, Amazon Elasticsearch Service, and Splunk.",
        "reference": "https://docs.aws.amazon.com/firehose/",
        "points": 1,
        "answers": [
            {"text": "Kinesis Data Firehose", "is_correct": True},
            {"text": "Kinesis Data Streams", "is_correct": False},
            {"text": "Kinesis Data Analytics", "is_correct": False},
            {"text": "Kinesis Video Streams", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon QuickSight primarily used for?",
        "explanation": "Amazon QuickSight is a fast, cloud-powered business intelligence (BI) service that makes it easy to deliver insights to everyone in your organization. It allows you to create and publish interactive dashboards.",
        "reference": "https://docs.aws.amazon.com/quicksight/",
        "points": 1,
        "answers": [
            {
                "text": "Business intelligence and data visualization",
                "is_correct": True,
            },
            {"text": "Data storage", "is_correct": False},
            {"text": "ETL processing", "is_correct": False},
            {"text": "Real-time streaming", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Elasticsearch?",
        "explanation": "Amazon OpenSearch Service (formerly Amazon Elasticsearch Service) is a managed service that makes it easy to deploy, operate, and scale OpenSearch clusters in the AWS Cloud.",
        "reference": "https://docs.aws.amazon.com/opensearch-service/",
        "points": 1,
        "answers": [
            {"text": "Amazon OpenSearch Service", "is_correct": True},
            {"text": "Amazon EMR", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary use case for AWS Lake Formation?",
        "explanation": "AWS Lake Formation makes it easy to set up a secure data lake in days. A data lake is a centralized, curated, and secured repository that stores all your data, both in its original form and prepared for analysis.",
        "reference": "https://docs.aws.amazon.com/lake-formation/",
        "points": 1,
        "answers": [
            {"text": "Setting up and managing data lakes", "is_correct": True},
            {"text": "Real-time data processing", "is_correct": False},
            {"text": "Data visualization", "is_correct": False},
            {"text": "Machine learning model training", "is_correct": False},
        ],
    },
    {
        "text": "Which compression format is most efficient for Redshift columnar storage?",
        "explanation": "LZO compression is generally most efficient for Redshift columnar storage, providing good compression ratios with fast decompression. However, the best compression depends on data characteristics.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/dg/c_Compression_encodings.html",
        "points": 1,
        "answers": [
            {"text": "LZO", "is_correct": True},
            {"text": "GZIP", "is_correct": False},
            {"text": "BZIP2", "is_correct": False},
            {"text": "RAW (no compression)", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum cluster size for Amazon Redshift?",
        "explanation": "Amazon Redshift supports clusters with up to 128 compute nodes for the largest instance types (ra3.16xlarge), providing petabyte-scale data warehouse capabilities.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html",
        "points": 1,
        "answers": [
            {"text": "128 nodes", "is_correct": True},
            {"text": "64 nodes", "is_correct": False},
            {"text": "256 nodes", "is_correct": False},
            {"text": "32 nodes", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides real-time analytics on streaming data?",
        "explanation": "Amazon Kinesis Data Analytics enables you to process and analyze streaming data in real-time using standard SQL or Apache Flink applications.",
        "reference": "https://docs.aws.amazon.com/kinesisanalytics/",
        "points": 1,
        "answers": [
            {"text": "Kinesis Data Analytics", "is_correct": True},
            {"text": "Amazon Athena", "is_correct": False},
            {"text": "Amazon EMR", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Glue DataBrew used for?",
        "explanation": "AWS Glue DataBrew is a visual data preparation tool that makes it easy for data analysts and data scientists to clean and normalize data to prepare it for analytics and machine learning.",
        "reference": "https://docs.aws.amazon.com/databrew/",
        "points": 1,
        "answers": [
            {"text": "Visual data preparation and cleaning", "is_correct": True},
            {"text": "ETL job orchestration", "is_correct": False},
            {"text": "Data cataloging", "is_correct": False},
            {"text": "Real-time streaming", "is_correct": False},
        ],
    },
    {
        "text": "Which service is best for ad-hoc queries on data stored in S3?",
        "explanation": "Amazon Athena is ideal for ad-hoc queries on data stored in S3. It's serverless and allows you to analyze data using standard SQL without needing to set up infrastructure.",
        "reference": "https://docs.aws.amazon.com/athena/latest/ug/what-is.html",
        "points": 1,
        "answers": [
            {"text": "Amazon Athena", "is_correct": True},
            {"text": "Amazon Redshift", "is_correct": False},
            {"text": "Amazon EMR", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
        ],
    },
    {
        "text": "What is the retention period for Kinesis Data Streams by default?",
        "explanation": "By default, Kinesis Data Streams stores records for 24 hours. You can extend this retention period up to 365 days for long-term data retention.",
        "reference": "https://docs.aws.amazon.com/kinesis/latest/dev/kinesis-extended-retention.html",
        "points": 1,
        "answers": [
            {"text": "24 hours", "is_correct": True},
            {"text": "7 days", "is_correct": False},
            {"text": "1 hour", "is_correct": False},
            {"text": "30 days", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Apache Kafka?",
        "explanation": "Amazon Managed Streaming for Apache Kafka (MSK) is a fully managed service that makes it easy to build and run applications that use Apache Kafka to process streaming data.",
        "reference": "https://docs.aws.amazon.com/msk/",
        "points": 1,
        "answers": [
            {"text": "Amazon MSK", "is_correct": True},
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "Amazon EMR", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Redshift Spectrum used for?",
        "explanation": "Amazon Redshift Spectrum allows you to run queries against exabytes of data in Amazon S3 without having to load or transform any data. It extends the analytic power of Amazon Redshift beyond the data stored on local disks in your data warehouse.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/dg/c-using-spectrum.html",
        "points": 1,
        "answers": [
            {"text": "Query data in S3 directly from Redshift", "is_correct": True},
            {"text": "Backup Redshift data to S3", "is_correct": False},
            {"text": "Migrate data from S3 to Redshift", "is_correct": False},
            {"text": "Encrypt data in Redshift", "is_correct": False},
        ],
    },
    {
        "text": "Which partitioning strategy is most effective for time-series data in S3?",
        "explanation": "For time-series data, partitioning by date (year/month/day) is most effective as it allows for efficient query pruning and reduces the amount of data scanned during time-based queries.",
        "reference": "https://docs.aws.amazon.com/athena/latest/ug/partitions.html",
        "points": 1,
        "answers": [
            {"text": "Date-based partitioning (year/month/day)", "is_correct": True},
            {"text": "Hash-based partitioning", "is_correct": False},
            {"text": "Random partitioning", "is_correct": False},
            {"text": "No partitioning", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Data Pipeline used for?",
        "explanation": "AWS Data Pipeline is a web service that helps you reliably process and move data between different AWS compute and storage services, as well as on-premises data sources, at specified intervals.",
        "reference": "https://docs.aws.amazon.com/datapipeline/",
        "points": 1,
        "answers": [
            {"text": "Orchestrating data workflows and movement", "is_correct": True},
            {"text": "Real-time data streaming", "is_correct": False},
            {"text": "Data visualization", "is_correct": False},
            {"text": "Machine learning", "is_correct": False},
        ],
    },
    {
        "text": "Which file format provides the best performance for analytical queries in Athena?",
        "explanation": "Parquet is a columnar storage format that provides excellent compression and performance for analytical queries. It's optimized for OLAP workloads and reduces both query time and costs.",
        "reference": "https://docs.aws.amazon.com/athena/latest/ug/columnar-storage.html",
        "points": 1,
        "answers": [
            {"text": "Parquet", "is_correct": True},
            {"text": "CSV", "is_correct": False},
            {"text": "JSON", "is_correct": False},
            {"text": "Avro", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of shards in a Kinesis Data Stream?",
        "explanation": "There is no hard limit on the number of shards in a Kinesis Data Stream, but there are default limits that can be increased. The default limit is typically 500 shards per stream per region.",
        "reference": "https://docs.aws.amazon.com/kinesis/latest/dev/service-sizes-and-limits.html",
        "points": 1,
        "answers": [
            {
                "text": "No hard limit (500 default, can be increased)",
                "is_correct": True,
            },
            {"text": "100 shards", "is_correct": False},
            {"text": "1000 shards", "is_correct": False},
            {"text": "50 shards", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides data catalog capabilities?",
        "explanation": "AWS Glue Data Catalog is a central metadata repository that stores information about data sources, transformations, and targets. It serves as a unified metadata repository for analytics services.",
        "reference": "https://docs.aws.amazon.com/glue/latest/dg/catalog-and-crawler.html",
        "points": 1,
        "answers": [
            {"text": "AWS Glue Data Catalog", "is_correct": True},
            {"text": "Amazon Athena", "is_correct": False},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon EMR Notebooks used for?",
        "explanation": "Amazon EMR Notebooks provide a managed environment based on Jupyter Notebooks for data scientists and analysts to develop, visualize, and collaborate on analytics applications.",
        "reference": "https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-managed-notebooks.html",
        "points": 1,
        "answers": [
            {"text": "Managed Jupyter notebooks for data science", "is_correct": True},
            {"text": "Cluster management", "is_correct": False},
            {"text": "Data storage", "is_correct": False},
            {"text": "Real-time streaming", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides time-series database capabilities?",
        "explanation": "Amazon Timestream is a fast, scalable, and serverless time series database service for IoT and operational applications that makes it easy to store and analyze trillions of time series data points per day.",
        "reference": "https://docs.aws.amazon.com/timestream/",
        "points": 1,
        "answers": [
            {"text": "Amazon Timestream", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Redshift VACUUM operation?",
        "explanation": "VACUUM operation in Redshift reclaims space and resorts rows in either a specified table or all tables in the current database. It's essential for maintaining optimal query performance after DELETE and UPDATE operations.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/dg/r_VACUUM_command.html",
        "points": 1,
        "answers": [
            {
                "text": "Reclaim space and resort rows for optimal performance",
                "is_correct": True,
            },
            {"text": "Create table backups", "is_correct": False},
            {"text": "Compress data", "is_correct": False},
            {"text": "Update statistics", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is best for processing large-scale batch analytics?",
        "explanation": "Amazon EMR is ideal for large-scale batch analytics using frameworks like Apache Spark, Hadoop, and Hive. It provides managed clusters for big data processing workloads.",
        "reference": "https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-what-is-emr.html",
        "points": 1,
        "answers": [
            {"text": "Amazon EMR", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "Amazon Athena", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Glue Elastic Views used for?",
        "explanation": "AWS Glue Elastic Views makes it easy to build materialized views that combine and replicate data across multiple data stores, automatically updating them when the source data changes.",
        "reference": "https://docs.aws.amazon.com/glue/latest/dg/elastic-views.html",
        "points": 1,
        "answers": [
            {
                "text": "Building materialized views across multiple data stores",
                "is_correct": True,
            },
            {"text": "Data cataloging", "is_correct": False},
            {"text": "ETL processing", "is_correct": False},
            {"text": "Real-time streaming", "is_correct": False},
        ],
    },
    {
        "text": "Which storage class in S3 is most cost-effective for data archival in analytics?",
        "explanation": "S3 Glacier Deep Archive is the most cost-effective storage class for long-term data archival, though it has longer retrieval times (12+ hours). It's ideal for compliance and backup data that's rarely accessed.",
        "reference": "https://docs.aws.amazon.com/s3/latest/userguide/storage-class-intro.html",
        "points": 1,
        "answers": [
            {"text": "S3 Glacier Deep Archive", "is_correct": True},
            {"text": "S3 Standard", "is_correct": False},
            {"text": "S3 Standard-IA", "is_correct": False},
            {"text": "S3 Intelligent-Tiering", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Redshift RA3 instance family optimized for?",
        "explanation": "RA3 instance family is optimized for performance and flexibility, using managed storage that automatically scales and provides high performance. It separates compute and storage for independent scaling.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html#rs-ra3-node-types",
        "points": 1,
        "answers": [
            {
                "text": "Performance with managed storage and independent scaling",
                "is_correct": True,
            },
            {"text": "Memory-intensive workloads only", "is_correct": False},
            {"text": "Dense storage only", "is_correct": False},
            {"text": "Real-time processing", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Apache Airflow?",
        "explanation": "Amazon Managed Workflows for Apache Airflow (MWAA) is a managed orchestration service for Apache Airflow that makes it easier to set up and operate end-to-end data pipelines.",
        "reference": "https://docs.aws.amazon.com/mwaa/",
        "points": 1,
        "answers": [
            {"text": "Amazon MWAA", "is_correct": True},
            {"text": "AWS Step Functions", "is_correct": False},
            {"text": "AWS Data Pipeline", "is_correct": False},
            {"text": "AWS Glue", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary benefit of using columnar storage in analytics?",
        "explanation": "Columnar storage improves query performance by allowing queries to read only the columns they need, reducing I/O and enabling better compression ratios for similar data types stored together.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/dg/c_columnar_storage_disk_mem_mgmnt.html",
        "points": 1,
        "answers": [
            {"text": "Improved query performance and compression", "is_correct": True},
            {"text": "Faster inserts", "is_correct": False},
            {"text": "Better security", "is_correct": False},
            {"text": "Simplified schema design", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides graph database capabilities for analytics?",
        "explanation": "Amazon Neptune is a fast, reliable, fully managed graph database service that makes it easy to build and run applications that work with highly connected datasets using graph query languages like SPARQL and Gremlin.",
        "reference": "https://docs.aws.amazon.com/neptune/",
        "points": 1,
        "answers": [
            {"text": "Amazon Neptune", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon DocumentDB", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Kinesis Video Streams used for?",
        "explanation": "Amazon Kinesis Video Streams makes it easy to securely stream video from connected devices to AWS for analytics, machine learning, and other processing applications.",
        "reference": "https://docs.aws.amazon.com/kinesis/latest/video/",
        "points": 1,
        "answers": [
            {"text": "Streaming video data for analytics and ML", "is_correct": True},
            {"text": "Text data streaming", "is_correct": False},
            {"text": "Audio streaming only", "is_correct": False},
            {"text": "File transfers", "is_correct": False},
        ],
    },
    {
        "text": "Which feature in Redshift helps optimize query performance automatically?",
        "explanation": "Automatic WLM (Workload Management) in Redshift automatically manages memory allocation and concurrency for queries, optimizing performance without manual configuration.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/dg/automatic-wlm.html",
        "points": 1,
        "answers": [
            {"text": "Automatic Workload Management (WLM)", "is_correct": True},
            {"text": "Manual query optimization", "is_correct": False},
            {"text": "Sort keys only", "is_correct": False},
            {"text": "Distribution keys only", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS DataSync used for in analytics workflows?",
        "explanation": "AWS DataSync is a data transfer service that simplifies, automates, and accelerates moving large amounts of data between on-premises storage and AWS storage services for analytics.",
        "reference": "https://docs.aws.amazon.com/datasync/",
        "points": 1,
        "answers": [
            {
                "text": "Transfer large datasets between on-premises and AWS",
                "is_correct": True,
            },
            {"text": "Real-time data streaming", "is_correct": False},
            {"text": "Data transformation", "is_correct": False},
            {"text": "Data visualization", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Redis for analytics caching?",
        "explanation": "Amazon ElastiCache for Redis provides a high-performance, scalable, and cost-effective caching solution that can significantly improve application performance for analytics workloads.",
        "reference": "https://docs.aws.amazon.com/elasticache/redis/",
        "points": 1,
        "answers": [
            {"text": "Amazon ElastiCache for Redis", "is_correct": True},
            {"text": "Amazon DynamoDB", "is_correct": False},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon S3", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Glue Studio?",
        "explanation": "AWS Glue Studio is a visual interface for creating, running, and monitoring AWS Glue ETL jobs. It makes it easier to create data transformation jobs without writing code.",
        "reference": "https://docs.aws.amazon.com/glue/latest/ug/what-is-glue-studio.html",
        "points": 1,
        "answers": [
            {"text": "Visual interface for creating ETL jobs", "is_correct": True},
            {"text": "Data visualization dashboard", "is_correct": False},
            {"text": "Machine learning model training", "is_correct": False},
            {"text": "Real-time analytics", "is_correct": False},
        ],
    },
    {
        "text": "Which compression algorithm is best for real-time analytics in Kinesis?",
        "explanation": "GZIP compression provides a good balance between compression ratio and processing speed for real-time analytics in Kinesis, though the choice depends on specific requirements for latency vs. compression ratio.",
        "reference": "https://docs.aws.amazon.com/kinesis/latest/dev/kinesis-kpl-config.html",
        "points": 1,
        "answers": [
            {"text": "GZIP", "is_correct": True},
            {"text": "LZO", "is_correct": False},
            {"text": "BZIP2", "is_correct": False},
            {"text": "No compression", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Redshift Serverless?",
        "explanation": "Amazon Redshift Serverless makes it easy to run and scale analytics without having to provision and manage data warehouse clusters. You pay for the compute capacity your workloads use rather than for a dedicated cluster.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-serverless.html",
        "points": 1,
        "answers": [
            {
                "text": "Serverless data warehouse without cluster management",
                "is_correct": True,
            },
            {"text": "Managed Redis cache", "is_correct": False},
            {"text": "Serverless compute for EMR", "is_correct": False},
            {"text": "Serverless ETL processing", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides data quality and profiling capabilities?",
        "explanation": "AWS Glue Data Quality provides capabilities to measure, monitor, and manage the quality of your data. It can profile data and create data quality rules to ensure data meets your requirements.",
        "reference": "https://docs.aws.amazon.com/glue/latest/dg/glue-data-quality.html",
        "points": 1,
        "answers": [
            {"text": "AWS Glue Data Quality", "is_correct": True},
            {"text": "Amazon Inspector", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
            {"text": "Amazon Macie", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of concurrent connections for Redshift?",
        "explanation": "Amazon Redshift supports a maximum of 500 concurrent connections by default. This limit includes connections from all sources including applications, BI tools, and query tools.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/mgmt/amazon-redshift-limits.html",
        "points": 1,
        "answers": [
            {"text": "500 connections", "is_correct": True},
            {"text": "1000 connections", "is_correct": False},
            {"text": "100 connections", "is_correct": False},
            {"text": "Unlimited connections", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides log analytics capabilities?",
        "explanation": "Amazon OpenSearch Service provides powerful log analytics capabilities, allowing you to search, analyze, and visualize log data in real-time. It's commonly used for application monitoring and security analytics.",
        "reference": "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html",
        "points": 1,
        "answers": [
            {"text": "Amazon OpenSearch Service", "is_correct": True},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon S3", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Clean Rooms used for?",
        "explanation": "AWS Clean Rooms helps customers and their partners more easily and securely analyze and collaborate on their collective datasets without sharing or revealing underlying data.",
        "reference": "https://docs.aws.amazon.com/clean-rooms/",
        "points": 1,
        "answers": [
            {
                "text": "Secure data collaboration without sharing raw data",
                "is_correct": True,
            },
            {"text": "Data cleaning and preparation", "is_correct": False},
            {"text": "Secure data storage", "is_correct": False},
            {"text": "Data visualization", "is_correct": False},
        ],
    },
    {
        "text": "Which feature in EMR helps reduce costs for fault-tolerant workloads?",
        "explanation": "EMR Spot Instances allow you to use spare EC2 capacity at significant cost savings. They're ideal for fault-tolerant workloads that can handle interruptions.",
        "reference": "https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-instance-purchasing-options.html",
        "points": 1,
        "answers": [
            {"text": "Spot Instances", "is_correct": True},
            {"text": "Reserved Instances", "is_correct": False},
            {"text": "Dedicated Hosts", "is_correct": False},
            {"text": "On-Demand Instances", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon EMR on EKS used for?",
        "explanation": "Amazon EMR on EKS allows you to run Apache Spark applications on Amazon Elastic Kubernetes Service (EKS), providing the flexibility of containerized environments for big data workloads.",
        "reference": "https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-eks.html",
        "points": 1,
        "answers": [
            {"text": "Run Spark applications on Kubernetes", "is_correct": True},
            {"text": "Container orchestration only", "is_correct": False},
            {"text": "Serverless computing", "is_correct": False},
            {"text": "Database management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides data lineage tracking?",
        "explanation": "AWS Glue provides data lineage capabilities that help track the flow of data through your ETL processes, showing how data moves and transforms from source to destination.",
        "reference": "https://docs.aws.amazon.com/glue/latest/dg/monitor-data-lineage.html",
        "points": 1,
        "answers": [
            {"text": "AWS Glue", "is_correct": True},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Redshift ANALYZE operation?",
        "explanation": "ANALYZE operation updates the statistics metadata that the query planner uses to build and choose optimal query execution plans. It should be run after significant data changes for optimal performance.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/dg/r_ANALYZE.html",
        "points": 1,
        "answers": [
            {"text": "Update statistics for query optimization", "is_correct": True},
            {"text": "Compress table data", "is_correct": False},
            {"text": "Create table backups", "is_correct": False},
            {"text": "Defragment storage", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed ClickHouse?",
        "explanation": "As of 2024, AWS does not provide a managed ClickHouse service. ClickHouse can be deployed on EC2 instances or through third-party solutions on AWS Marketplace.",
        "reference": "https://aws.amazon.com/marketplace/search/results?searchTerms=clickhouse",
        "points": 1,
        "answers": [
            {"text": "AWS does not provide managed ClickHouse", "is_correct": True},
            {"text": "Amazon RDS", "is_correct": False},
            {"text": "Amazon Redshift", "is_correct": False},
            {"text": "Amazon EMR", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Glue Workflow used for?",
        "explanation": "AWS Glue Workflows allow you to orchestrate complex ETL activities involving multiple crawlers, jobs, and triggers. They provide visual representation and management of dependencies between ETL components.",
        "reference": "https://docs.aws.amazon.com/glue/latest/dg/workflows_overview.html",
        "points": 1,
        "answers": [
            {
                "text": "Orchestrate complex ETL activities with dependencies",
                "is_correct": True,
            },
            {"text": "Single job execution", "is_correct": False},
            {"text": "Data visualization", "is_correct": False},
            {"text": "Real-time processing", "is_correct": False},
        ],
    },
    {
        "text": "Which partitioning strategy is best for evenly distributed data access patterns?",
        "explanation": "Hash-based partitioning distributes data evenly across partitions and is ideal when data access patterns are uniform and you want to avoid hotspots.",
        "reference": "https://docs.aws.amazon.com/athena/latest/ug/partitions.html",
        "points": 1,
        "answers": [
            {"text": "Hash-based partitioning", "is_correct": True},
            {"text": "Range-based partitioning", "is_correct": False},
            {"text": "List-based partitioning", "is_correct": False},
            {"text": "No partitioning", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Kinesis Data Firehose's error record handling?",
        "explanation": "Kinesis Data Firehose can send failed records to a separate S3 bucket or prefix, allowing you to investigate and reprocess records that failed transformation or delivery.",
        "reference": "https://docs.aws.amazon.com/firehose/latest/dev/error-handling.html",
        "points": 1,
        "answers": [
            {"text": "Send failed records to S3 for investigation", "is_correct": True},
            {"text": "Automatically retry indefinitely", "is_correct": False},
            {"text": "Drop failed records silently", "is_correct": False},
            {"text": "Stop processing on any error", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Prometheus for monitoring?",
        "explanation": "Amazon Managed Service for Prometheus provides a Prometheus-compatible monitoring service that makes it easy to securely monitor containerized applications at scale.",
        "reference": "https://docs.aws.amazon.com/prometheus/",
        "points": 1,
        "answers": [
            {"text": "Amazon Managed Service for Prometheus", "is_correct": True},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS X-Ray", "is_correct": False},
            {"text": "Amazon OpenSearch", "is_correct": False},
        ],
    },
    {
        "text": "What is the primary advantage of using ORC format over Parquet?",
        "explanation": "ORC (Optimized Row Columnar) format provides excellent compression and is optimized for Hive workloads, while Parquet is more universal. ORC typically provides better compression ratios for Hive-based analytics.",
        "reference": "https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hive-columnar-formats.html",
        "points": 1,
        "answers": [
            {
                "text": "Better compression ratios for Hive workloads",
                "is_correct": True,
            },
            {"text": "Faster write performance", "is_correct": False},
            {"text": "Better cross-platform compatibility", "is_correct": False},
            {"text": "Simpler schema evolution", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides real-time machine learning inference on streaming data?",
        "explanation": "Amazon Kinesis Data Analytics can be used with machine learning models for real-time inference on streaming data, enabling real-time anomaly detection and prediction.",
        "reference": "https://docs.aws.amazon.com/kinesisanalytics/latest/dev/how-it-works.html",
        "points": 1,
        "answers": [
            {"text": "Kinesis Data Analytics", "is_correct": True},
            {"text": "Amazon SageMaker", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon EMR", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS IoT Analytics used for?",
        "explanation": "AWS IoT Analytics is a managed service that makes it easy to run sophisticated analytics on massive volumes of IoT data without having to worry about the cost and complexity of building an IoT analytics platform.",
        "reference": "https://docs.aws.amazon.com/iotanalytics/",
        "points": 1,
        "answers": [
            {"text": "Analytics on IoT device data", "is_correct": True},
            {"text": "General purpose analytics", "is_correct": False},
            {"text": "Social media analytics", "is_correct": False},
            {"text": "Financial data analytics", "is_correct": False},
        ],
    },
    {
        "text": "Which feature in Athena helps reduce query costs?",
        "explanation": "Query result caching in Athena can significantly reduce costs by reusing results from previous identical queries, eliminating the need to re-scan data and reducing data processing charges.",
        "reference": "https://docs.aws.amazon.com/athena/latest/ug/querying-with-query-result-caching.html",
        "points": 1,
        "answers": [
            {"text": "Query result caching", "is_correct": True},
            {"text": "Parallel processing", "is_correct": False},
            {"text": "Automatic scaling", "is_correct": False},
            {"text": "Data compression", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon EMR Serverless?",
        "explanation": "Amazon EMR Serverless is a serverless option for Amazon EMR that makes it easy to run open-source big data analytics frameworks without configuring, managing, and scaling clusters or servers.",
        "reference": "https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/emr-serverless.html",
        "points": 1,
        "answers": [
            {
                "text": "Serverless big data analytics without cluster management",
                "is_correct": True,
            },
            {"text": "Managed Kubernetes for analytics", "is_correct": False},
            {"text": "Serverless data warehouse", "is_correct": False},
            {"text": "Serverless data lake", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides data mesh capabilities?",
        "explanation": "AWS Lake Formation combined with other AWS services helps implement data mesh architectures by providing decentralized data ownership with centralized governance and discovery capabilities.",
        "reference": "https://docs.aws.amazon.com/lake-formation/latest/dg/what-is-lake-formation.html",
        "points": 1,
        "answers": [
            {"text": "AWS Lake Formation (with other services)", "is_correct": True},
            {"text": "Amazon S3 only", "is_correct": False},
            {"text": "AWS Glue only", "is_correct": False},
            {"text": "Amazon Redshift only", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Redshift sort keys?",
        "explanation": "Sort keys determine the order in which rows in a table are stored. When data is sorted, query performance is improved when queries include restrictions on sort key columns, as Redshift can skip blocks that don't contain relevant data.",
        "reference": "https://docs.aws.amazon.com/redshift/latest/dg/t_Sorting_data.html",
        "points": 1,
        "answers": [
            {
                "text": "Improve query performance by ordering data storage",
                "is_correct": True,
            },
            {"text": "Encrypt sensitive data", "is_correct": False},
            {"text": "Distribute data across nodes", "is_correct": False},
            {"text": "Compress data", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides change data capture (CDC) capabilities?",
        "explanation": "AWS Database Migration Service (DMS) provides change data capture capabilities, allowing you to replicate ongoing changes from source databases to target data stores for analytics.",
        "reference": "https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Task.CDC.html",
        "points": 1,
        "answers": [
            {"text": "AWS Database Migration Service (DMS)", "is_correct": True},
            {"text": "AWS Glue", "is_correct": False},
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "AWS DataSync", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon FinSpace used for?",
        "explanation": "Amazon FinSpace is a data management and analytics service purpose-built for the financial services industry that helps customers store, catalog, prepare, and analyze financial data.",
        "reference": "https://docs.aws.amazon.com/finspace/",
        "points": 1,
        "answers": [
            {
                "text": "Financial services data management and analytics",
                "is_correct": True,
            },
            {"text": "General purpose data analytics", "is_correct": False},
            {"text": "Real-time streaming", "is_correct": False},
            {"text": "Machine learning", "is_correct": False},
        ],
    },
]
