"""AWS Developer Associate Certification"""

CERTIFICATION = {
    "name": "AWS Certified Developer - Associate",
    "description": "Develop and maintain applications on AWS",
    "slug": "aws-developer-associate",
    "level": "Associate",
    "duration": 204,
    "questions_count": 68,
    "category_slug": "aws",
    "is_active": True,
}

QUESTIONS = [
    {
        "text": "Which AWS service is best suited for implementing a message queue?",
        "explanation": "Amazon SQS (Simple Queue Service) is a fully managed message queuing service that enables you to decouple and scale microservices.",
        "reference": "https://docs.aws.amazon.com/sqs/",
        "points": 1,
        "answers": [
            {"text": "Amazon SNS", "is_correct": False},
            {"text": "Amazon SQS", "is_correct": True},
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon EventBridge", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum execution time for an AWS Lambda function?",
        "explanation": "AWS Lambda functions have a maximum execution timeout of 15 minutes (900 seconds). This limit cannot be increased.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html",
        "points": 1,
        "answers": [
            {"text": "5 minutes", "is_correct": False},
            {"text": "10 minutes", "is_correct": False},
            {"text": "15 minutes", "is_correct": True},
            {"text": "30 minutes", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides application-level auto scaling?",
        "explanation": "AWS Application Auto Scaling provides automatic scaling for various AWS resources including ECS services, DynamoDB tables, and Lambda provisioned concurrency.",
        "reference": "https://docs.aws.amazon.com/autoscaling/application/userguide/what-is-application-auto-scaling.html",
        "points": 1,
        "answers": [
            {"text": "Amazon EC2 Auto Scaling", "is_correct": False},
            {"text": "AWS Application Auto Scaling", "is_correct": True},
            {"text": "Elastic Load Balancing", "is_correct": False},
            {"text": "Amazon CloudWatch", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Amazon API Gateway?",
        "explanation": "Amazon API Gateway is a fully managed service that makes it easy to create, publish, maintain, monitor, and secure APIs at any scale. It acts as a front door for applications to access backend services.",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "Create and manage APIs", "is_correct": True},
            {"text": "Store application data", "is_correct": False},
            {"text": "Monitor application performance", "is_correct": False},
            {"text": "Deploy applications", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB operation should you use to retrieve multiple items efficiently?",
        "explanation": "BatchGetItem allows you to retrieve multiple items from one or more tables in a single request, making it more efficient than multiple GetItem operations.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.BatchOperations",
        "points": 1,
        "answers": [
            {"text": "GetItem", "is_correct": False},
            {"text": "BatchGetItem", "is_correct": True},
            {"text": "Query", "is_correct": False},
            {"text": "Scan", "is_correct": False},
        ],
    },
    {
        "text": "What is the default visibility timeout for Amazon SQS messages?",
        "explanation": "The default visibility timeout for Amazon SQS messages is 30 seconds. During this time, the message is hidden from other consumers.",
        "reference": "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html",
        "points": 1,
        "answers": [
            {"text": "10 seconds", "is_correct": False},
            {"text": "30 seconds", "is_correct": True},
            {"text": "60 seconds", "is_correct": False},
            {"text": "300 seconds", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for deploying and managing containerized applications?",
        "explanation": "Amazon ECS (Elastic Container Service) is a fully managed container orchestration service that helps you easily deploy, manage, and scale containerized applications.",
        "reference": "https://docs.aws.amazon.com/ecs/latest/developerguide/Welcome.html",
        "points": 1,
        "answers": [
            {"text": "AWS Lambda", "is_correct": False},
            {"text": "Amazon ECS", "is_correct": True},
            {"text": "AWS Elastic Beanstalk", "is_correct": False},
            {"text": "Amazon EC2", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum payload size for an Amazon SNS message?",
        "explanation": "Amazon SNS supports message payloads up to 256 KB for HTTP/HTTPS/SQS endpoints and 160 KB for SMS.",
        "reference": "https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html",
        "points": 1,
        "answers": [
            {"text": "64 KB", "is_correct": False},
            {"text": "128 KB", "is_correct": False},
            {"text": "256 KB", "is_correct": True},
            {"text": "1 MB", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides version control for your Lambda functions?",
        "explanation": "AWS Lambda automatically provides versioning. You can create versions of your Lambda function code and use aliases to point to specific versions.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html",
        "points": 1,
        "answers": [
            {"text": "AWS CodeCommit", "is_correct": False},
            {"text": "AWS Lambda versioning", "is_correct": True},
            {"text": "Amazon S3", "is_correct": False},
            {"text": "AWS Systems Manager", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS X-Ray used for?",
        "explanation": "AWS X-Ray is a service that helps developers analyze and debug distributed applications by providing request tracing and performance insights.",
        "reference": "https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html",
        "points": 1,
        "answers": [
            {"text": "Application monitoring and tracing", "is_correct": True},
            {"text": "Code deployment", "is_correct": False},
            {"text": "Data storage", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
        ],
    },
    {
        "text": "Which environment variable contains the AWS region in Lambda?",
        "explanation": "The AWS_REGION environment variable contains the AWS region where the Lambda function is executed.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html",
        "points": 1,
        "answers": [
            {"text": "AWS_DEFAULT_REGION", "is_correct": False},
            {"text": "AWS_REGION", "is_correct": True},
            {"text": "LAMBDA_REGION", "is_correct": False},
            {"text": "REGION", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS CodeDeploy?",
        "explanation": "AWS CodeDeploy is a deployment service that automates application deployments to Amazon EC2 instances, on-premises servers, Lambda functions, or Amazon ECS services.",
        "reference": "https://docs.aws.amazon.com/codedeploy/latest/userguide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "Automated application deployment", "is_correct": True},
            {"text": "Source code storage", "is_correct": False},
            {"text": "Application building", "is_correct": False},
            {"text": "Performance monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB attribute serves as the partition key?",
        "explanation": "The hash attribute (also called partition key) determines which partition the item will be stored in. It's used for distributing data across multiple partitions.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html",
        "points": 1,
        "answers": [
            {"text": "Sort key", "is_correct": False},
            {"text": "Hash attribute (partition key)", "is_correct": True},
            {"text": "Range key", "is_correct": False},
            {"text": "Secondary index", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum size of an SQS message?",
        "explanation": "Amazon SQS supports message payloads up to 256 KB. For larger payloads, you can use the SQS Extended Client Library with S3.",
        "reference": "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html",
        "points": 1,
        "answers": [
            {"text": "64 KB", "is_correct": False},
            {"text": "128 KB", "is_correct": False},
            {"text": "256 KB", "is_correct": True},
            {"text": "1 MB", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for building CI/CD pipelines?",
        "explanation": "AWS CodePipeline is a continuous integration and continuous delivery service that helps you automate your build, test, and deployment pipelines.",
        "reference": "https://docs.aws.amazon.com/codepipeline/latest/userguide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "AWS CodeCommit", "is_correct": False},
            {"text": "AWS CodeBuild", "is_correct": False},
            {"text": "AWS CodePipeline", "is_correct": True},
            {"text": "AWS CodeDeploy", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Elastic Beanstalk used for?",
        "explanation": "AWS Elastic Beanstalk is a service for deploying and scaling web applications and services. You upload your code and Beanstalk handles deployment, capacity provisioning, load balancing, and monitoring.",
        "reference": "https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/Welcome.html",
        "points": 1,
        "answers": [
            {
                "text": "Easy deployment and scaling of web applications",
                "is_correct": True,
            },
            {"text": "Container orchestration", "is_correct": False},
            {"text": "Database management", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides temporary AWS credentials?",
        "explanation": "AWS Security Token Service (STS) provides temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users or federated users.",
        "reference": "https://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html",
        "points": 1,
        "answers": [
            {"text": "AWS IAM", "is_correct": False},
            {"text": "AWS STS", "is_correct": True},
            {"text": "AWS Cognito", "is_correct": False},
            {"text": "AWS KMS", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between SQS Standard and FIFO queues?",
        "explanation": "Standard queues offer maximum throughput with at-least-once delivery and best-effort ordering. FIFO queues guarantee exactly-once processing and first-in-first-out delivery order.",
        "reference": "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html",
        "points": 1,
        "answers": [
            {
                "text": "FIFO guarantees order and exactly-once processing",
                "is_correct": True,
            },
            {"text": "Standard queues are faster", "is_correct": False},
            {"text": "FIFO queues are cheaper", "is_correct": False},
            {"text": "No significant difference", "is_correct": False},
        ],
    },
    {
        "text": "Which Lambda runtime environment variable specifies the handler function?",
        "explanation": "The _HANDLER environment variable specifies the Lambda function handler that Lambda calls to start execution of your function.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html",
        "points": 1,
        "answers": [
            {"text": "_HANDLER", "is_correct": True},
            {"text": "LAMBDA_HANDLER", "is_correct": False},
            {"text": "AWS_LAMBDA_FUNCTION_HANDLER", "is_correct": False},
            {"text": "HANDLER_NAME", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CodeCommit used for?",
        "explanation": "AWS CodeCommit is a fully managed source control service that hosts secure Git-based repositories, making it easy to collaborate on code.",
        "reference": "https://docs.aws.amazon.com/codecommit/latest/userguide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "Git-based source control repositories", "is_correct": True},
            {"text": "Application deployment", "is_correct": False},
            {"text": "Code building and testing", "is_correct": False},
            {"text": "Performance monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which API Gateway integration type provides the lowest latency?",
        "explanation": "AWS_PROXY integration type provides the lowest latency as it passes the entire request to the backend service without transformation.",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html",
        "points": 1,
        "answers": [
            {"text": "AWS_PROXY", "is_correct": True},
            {"text": "HTTP", "is_correct": False},
            {"text": "MOCK", "is_correct": False},
            {"text": "AWS", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of DynamoDB Global Secondary Index (GSI)?",
        "explanation": "A Global Secondary Index enables querying on non-key attributes by creating an alternative partition and sort key for the table.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html",
        "points": 1,
        "answers": [
            {"text": "Query on non-key attributes", "is_correct": True},
            {"text": "Improve read performance", "is_correct": False},
            {"text": "Enable cross-region replication", "is_correct": False},
            {"text": "Backup table data", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service is used for managing application secrets?",
        "explanation": "AWS Secrets Manager helps you protect secrets needed to access your applications, services, and IT resources. It enables you to easily rotate, manage, and retrieve credentials.",
        "reference": "https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html",
        "points": 1,
        "answers": [
            {"text": "AWS Systems Manager Parameter Store", "is_correct": False},
            {"text": "AWS Secrets Manager", "is_correct": True},
            {"text": "AWS KMS", "is_correct": False},
            {"text": "AWS IAM", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum memory allocation for AWS Lambda?",
        "explanation": "AWS Lambda supports memory allocation from 128 MB to 10,240 MB (10 GB) in 1 MB increments.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html",
        "points": 1,
        "answers": [
            {"text": "3 GB", "is_correct": False},
            {"text": "5 GB", "is_correct": False},
            {"text": "10 GB", "is_correct": True},
            {"text": "15 GB", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides user authentication and authorization?",
        "explanation": "Amazon Cognito provides authentication, authorization, and user management for web and mobile applications. Users can sign in directly or through identity providers.",
        "reference": "https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html",
        "points": 1,
        "answers": [
            {"text": "AWS IAM", "is_correct": False},
            {"text": "Amazon Cognito", "is_correct": True},
            {"text": "AWS STS", "is_correct": False},
            {"text": "AWS Directory Service", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CloudFormation used for?",
        "explanation": "AWS CloudFormation provides infrastructure as code capabilities, allowing you to model and provision AWS resources using templates.",
        "reference": "https://docs.aws.amazon.com/cloudformation/latest/userguide/Welcome.html",
        "points": 1,
        "answers": [
            {
                "text": "Infrastructure as code and resource provisioning",
                "is_correct": True,
            },
            {"text": "Application monitoring", "is_correct": False},
            {"text": "Code deployment", "is_correct": False},
            {"text": "Data storage", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB feature automatically scales read and write capacity?",
        "explanation": "DynamoDB Auto Scaling automatically adjusts read and write throughput capacity in response to changing request volumes.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.html",
        "points": 1,
        "answers": [
            {"text": "DynamoDB Auto Scaling", "is_correct": True},
            {"text": "DynamoDB Streams", "is_correct": False},
            {"text": "DynamoDB Accelerator", "is_correct": False},
            {"text": "Global Tables", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of AWS Step Functions?",
        "explanation": "AWS Step Functions is a serverless orchestration service that lets you coordinate multiple AWS services into serverless workflows using visual workflows.",
        "reference": "https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html",
        "points": 1,
        "answers": [
            {"text": "Serverless workflow orchestration", "is_correct": True},
            {"text": "Function deployment", "is_correct": False},
            {"text": "API management", "is_correct": False},
            {"text": "Database operations", "is_correct": False},
        ],
    },
    {
        "text": "Which CloudWatch metric indicates Lambda function errors?",
        "explanation": "The Errors metric in CloudWatch shows the number of invocations that resulted in a function error, including those handled by your function code.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics.html",
        "points": 1,
        "answers": [
            {"text": "Duration", "is_correct": False},
            {"text": "Errors", "is_correct": True},
            {"text": "Invocations", "is_correct": False},
            {"text": "Throttles", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS EventBridge used for?",
        "explanation": "Amazon EventBridge is a serverless event bus that makes it easy to connect applications together using data from your own applications, integrated SaaS applications, and AWS services.",
        "reference": "https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-what-is.html",
        "points": 1,
        "answers": [
            {"text": "Serverless event routing and processing", "is_correct": True},
            {"text": "Message queuing", "is_correct": False},
            {"text": "File storage", "is_correct": False},
            {"text": "Database management", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides configuration management for applications?",
        "explanation": "AWS Systems Manager Parameter Store provides secure, hierarchical storage for configuration data and secrets management.",
        "reference": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html",
        "points": 1,
        "answers": [
            {"text": "AWS Config", "is_correct": False},
            {"text": "AWS Systems Manager Parameter Store", "is_correct": True},
            {"text": "AWS CloudFormation", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is the default timeout for API Gateway requests?",
        "explanation": "Amazon API Gateway has a default timeout of 29 seconds for HTTP APIs and REST APIs. This timeout cannot be increased.",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html",
        "points": 1,
        "answers": [
            {"text": "10 seconds", "is_correct": False},
            {"text": "29 seconds", "is_correct": True},
            {"text": "60 seconds", "is_correct": False},
            {"text": "300 seconds", "is_correct": False},
        ],
    },
    {
        "text": "Which Lambda feature allows processing of DynamoDB changes?",
        "explanation": "DynamoDB Streams can trigger Lambda functions to process changes to items in a DynamoDB table, enabling real-time data processing.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html",
        "points": 1,
        "answers": [
            {"text": "DynamoDB Triggers", "is_correct": False},
            {"text": "DynamoDB Streams with Lambda", "is_correct": True},
            {"text": "DynamoDB Events", "is_correct": False},
            {"text": "DynamoDB Functions", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CodeBuild used for?",
        "explanation": "AWS CodeBuild is a fully managed continuous integration service that compiles source code, runs tests, and produces software packages.",
        "reference": "https://docs.aws.amazon.com/codebuild/latest/userguide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "Continuous integration and build automation", "is_correct": True},
            {"text": "Source code storage", "is_correct": False},
            {"text": "Application deployment", "is_correct": False},
            {"text": "Performance monitoring", "is_correct": False},
        ],
    },
    {
        "text": "Which S3 storage class is most cost-effective for long-term archival?",
        "explanation": "S3 Glacier Deep Archive is the most cost-effective storage class for long-term archival, designed for data that is accessed once or twice per year.",
        "reference": "https://docs.aws.amazon.com/s3/latest/userguide/storage-class-intro.html",
        "points": 1,
        "answers": [
            {"text": "S3 Standard", "is_correct": False},
            {"text": "S3 Glacier", "is_correct": False},
            {"text": "S3 Glacier Deep Archive", "is_correct": True},
            {"text": "S3 Intelligent-Tiering", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Lambda layers?",
        "explanation": "Lambda layers allow you to package libraries, custom runtimes, and dependencies separately from your function code, enabling code sharing across multiple functions.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html",
        "points": 1,
        "answers": [
            {
                "text": "Share code and dependencies across functions",
                "is_correct": True,
            },
            {"text": "Improve function performance", "is_correct": False},
            {"text": "Enable cross-region deployment", "is_correct": False},
            {"text": "Provide additional memory", "is_correct": False},
        ],
    },
    {
        "text": "Which IAM feature allows cross-account access?",
        "explanation": "IAM roles can be assumed by users, applications, or services from different AWS accounts, enabling secure cross-account access.",
        "reference": "https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html",
        "points": 1,
        "answers": [
            {"text": "IAM Users", "is_correct": False},
            {"text": "IAM Roles", "is_correct": True},
            {"text": "IAM Groups", "is_correct": False},
            {"text": "IAM Policies", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon Kinesis Data Streams used for?",
        "explanation": "Amazon Kinesis Data Streams is used for real-time streaming data ingestion and processing, enabling real-time analytics and data processing applications.",
        "reference": "https://docs.aws.amazon.com/kinesis/latest/dev/introduction.html",
        "points": 1,
        "answers": [
            {"text": "Real-time data streaming and processing", "is_correct": True},
            {"text": "Batch data processing", "is_correct": False},
            {"text": "Data storage", "is_correct": False},
            {"text": "Data backup", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides distributed tracing for microservices?",
        "explanation": "AWS X-Ray provides distributed tracing capabilities that help developers trace requests through distributed applications and microservices architectures.",
        "reference": "https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html",
        "points": 1,
        "answers": [
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "AWS X-Ray", "is_correct": True},
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of API Gateway stages?",
        "explanation": "API Gateway stages allow you to manage different versions of your API (development, staging, production) with different configurations and endpoints.",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-stages.html",
        "points": 1,
        "answers": [
            {
                "text": "Manage different API versions and environments",
                "is_correct": True,
            },
            {"text": "Improve API performance", "is_correct": False},
            {"text": "Secure API endpoints", "is_correct": False},
            {"text": "Monitor API usage", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB operation is most efficient for reading a single item?",
        "explanation": "GetItem is the most efficient operation for reading a single item from DynamoDB when you know the primary key, as it provides direct access.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html",
        "points": 1,
        "answers": [
            {"text": "Query", "is_correct": False},
            {"text": "Scan", "is_correct": False},
            {"text": "GetItem", "is_correct": True},
            {"text": "BatchGetItem", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CloudWatch used for?",
        "explanation": "Amazon CloudWatch is a monitoring and observability service that provides data and actionable insights for AWS resources and applications.",
        "reference": "https://docs.aws.amazon.com/cloudwatch/latest/monitoring/WhatIsCloudWatch.html",
        "points": 1,
        "answers": [
            {"text": "Monitoring and observability", "is_correct": True},
            {"text": "Code deployment", "is_correct": False},
            {"text": "Data storage", "is_correct": False},
            {"text": "User authentication", "is_correct": False},
        ],
    },
    {
        "text": "Which feature allows Lambda functions to process multiple records in parallel?",
        "explanation": "Lambda concurrent executions allow processing multiple records or events in parallel by creating multiple instances of your function.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/invocation-scaling.html",
        "points": 1,
        "answers": [
            {"text": "Reserved concurrency", "is_correct": False},
            {"text": "Concurrent executions", "is_correct": True},
            {"text": "Async invocations", "is_correct": False},
            {"text": "Event batching", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum number of attributes in a DynamoDB item?",
        "explanation": "A DynamoDB item can have up to 400 KB of data, which includes all attribute names and values. There's no specific limit on the number of attributes.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html",
        "points": 1,
        "answers": [
            {"text": "No specific limit (400 KB total)", "is_correct": True},
            {"text": "100 attributes", "is_correct": False},
            {"text": "255 attributes", "is_correct": False},
            {"text": "1000 attributes", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides blue/green deployments?",
        "explanation": "AWS CodeDeploy provides blue/green deployment capabilities, allowing you to reduce downtime and risk by running two identical production environments.",
        "reference": "https://docs.aws.amazon.com/codedeploy/latest/userguide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "AWS CodeCommit", "is_correct": False},
            {"text": "AWS CodeDeploy", "is_correct": True},
            {"text": "AWS CodeBuild", "is_correct": False},
            {"text": "AWS CodePipeline", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of SQS Dead Letter Queues?",
        "explanation": "Dead Letter Queues capture messages that can't be processed successfully after a specified number of attempts, allowing for troubleshooting and reprocessing.",
        "reference": "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html",
        "points": 1,
        "answers": [
            {"text": "Handle failed message processing", "is_correct": True},
            {"text": "Store large messages", "is_correct": False},
            {"text": "Improve message throughput", "is_correct": False},
            {"text": "Enable message encryption", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides container image storage?",
        "explanation": "Amazon Elastic Container Registry (ECR) is a fully managed Docker container registry that stores, manages, and deploys Docker container images.",
        "reference": "https://docs.aws.amazon.com/ecr/latest/userguide/what-is-ecr.html",
        "points": 1,
        "answers": [
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon ECR", "is_correct": True},
            {"text": "Amazon ECS", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS SAM used for?",
        "explanation": "AWS Serverless Application Model (SAM) is a framework for building serverless applications that provides shorthand syntax to define functions, APIs, databases, and event source mappings.",
        "reference": "https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html",
        "points": 1,
        "answers": [
            {"text": "Building serverless applications", "is_correct": True},
            {"text": "Managing EC2 instances", "is_correct": False},
            {"text": "Monitoring applications", "is_correct": False},
            {"text": "Storing application data", "is_correct": False},
        ],
    },
    {
        "text": "Which Lambda feature helps reduce cold starts?",
        "explanation": "Provisioned Concurrency keeps Lambda functions initialized and ready to respond immediately to invocations, reducing cold start latency.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html",
        "points": 1,
        "answers": [
            {"text": "Reserved concurrency", "is_correct": False},
            {"text": "Provisioned concurrency", "is_correct": True},
            {"text": "Lambda layers", "is_correct": False},
            {"text": "Environment variables", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum batch size for SQS with Lambda?",
        "explanation": "Lambda can receive up to 10 messages in a single batch from an SQS queue. This helps improve throughput and reduce costs.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html",
        "points": 1,
        "answers": [
            {"text": "5 messages", "is_correct": False},
            {"text": "10 messages", "is_correct": True},
            {"text": "25 messages", "is_correct": False},
            {"text": "100 messages", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides API rate limiting?",
        "explanation": "Amazon API Gateway provides built-in throttling and rate limiting capabilities to control the number of requests per second that your APIs can handle.",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html",
        "points": 1,
        "answers": [
            {"text": "AWS WAF", "is_correct": False},
            {"text": "Amazon API Gateway", "is_correct": True},
            {"text": "Amazon CloudFront", "is_correct": False},
            {"text": "AWS Lambda", "is_correct": False},
        ],
    },
    {
        "text": "What is Amazon ElastiCache used for in web applications?",
        "explanation": "Amazon ElastiCache is used as an in-memory caching layer to improve application performance by reducing database load and latency.",
        "reference": "https://docs.aws.amazon.com/elasticache/latest/red-ug/WhatIs.html",
        "points": 1,
        "answers": [
            {"text": "In-memory caching to improve performance", "is_correct": True},
            {"text": "Persistent data storage", "is_correct": False},
            {"text": "Load balancing", "is_correct": False},
            {"text": "Content delivery", "is_correct": False},
        ],
    },
    {
        "text": "Which feature allows API Gateway to transform requests and responses?",
        "explanation": "API Gateway mapping templates allow you to transform request and response payloads between your client and backend services using Apache Velocity Template Language (VTL).",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html",
        "points": 1,
        "answers": [
            {"text": "Mapping templates", "is_correct": True},
            {"text": "Lambda authorizers", "is_correct": False},
            {"text": "Request validators", "is_correct": False},
            {"text": "API stages", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CloudTrail used for?",
        "explanation": "AWS CloudTrail provides governance, compliance, and audit capabilities by recording API calls and user activity across your AWS infrastructure.",
        "reference": "https://docs.aws.amazon.com/cloudtrail/latest/userguide/cloudtrail-user-guide.html",
        "points": 1,
        "answers": [
            {"text": "API auditing and compliance", "is_correct": True},
            {"text": "Application monitoring", "is_correct": False},
            {"text": "Code deployment", "is_correct": False},
            {"text": "Data backup", "is_correct": False},
        ],
    },
    {
        "text": "Which DynamoDB feature provides real-time change tracking?",
        "explanation": "DynamoDB Streams captures a time-ordered sequence of item-level changes in a DynamoDB table, enabling real-time processing of changes.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html",
        "points": 1,
        "answers": [
            {"text": "DynamoDB Streams", "is_correct": True},
            {"text": "Global Tables", "is_correct": False},
            {"text": "Auto Scaling", "is_correct": False},
            {"text": "Point-in-time Recovery", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of Lambda environment variables?",
        "explanation": "Lambda environment variables allow you to pass configuration settings to your function code without hardcoding values, making functions more flexible and secure.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html",
        "points": 1,
        "answers": [
            {
                "text": "Pass configuration settings to function code",
                "is_correct": True,
            },
            {"text": "Store function logs", "is_correct": False},
            {"text": "Manage function versions", "is_correct": False},
            {"text": "Control function permissions", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed message brokers?",
        "explanation": "Amazon MQ is a managed message broker service for Apache ActiveMQ and RabbitMQ that makes it easy to migrate message brokers to the cloud.",
        "reference": "https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon MQ", "is_correct": True},
            {"text": "Amazon SNS", "is_correct": False},
            {"text": "Amazon Kinesis", "is_correct": False},
        ],
    },
    {
        "text": "What is the difference between PUT and POST methods in REST APIs?",
        "explanation": "PUT is used to create or update a resource at a specific URI (idempotent), while POST is used to create resources or perform operations (not idempotent).",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-settings.html",
        "points": 1,
        "answers": [
            {
                "text": "PUT is idempotent for create/update, POST is for creation/operations",
                "is_correct": True,
            },
            {"text": "PUT is faster than POST", "is_correct": False},
            {"text": "POST is more secure than PUT", "is_correct": False},
            {"text": "No significant difference", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides content delivery with edge caching?",
        "explanation": "Amazon CloudFront is a content delivery network (CDN) that caches content at edge locations worldwide to reduce latency and improve performance.",
        "reference": "https://docs.aws.amazon.com/cloudfront/latest/developerguide/Introduction.html",
        "points": 1,
        "answers": [
            {"text": "Amazon S3", "is_correct": False},
            {"text": "Amazon CloudFront", "is_correct": True},
            {"text": "Elastic Load Balancing", "is_correct": False},
            {"text": "Amazon Route 53", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS CodeStar used for?",
        "explanation": "AWS CodeStar provides a unified interface to quickly develop, build, and deploy applications on AWS with pre-configured development toolchains.",
        "reference": "https://docs.aws.amazon.com/codestar/latest/userguide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "Unified development project management", "is_correct": True},
            {"text": "Code versioning only", "is_correct": False},
            {"text": "Application monitoring", "is_correct": False},
            {"text": "Database management", "is_correct": False},
        ],
    },
    {
        "text": "Which Lambda pricing model charges based on request duration?",
        "explanation": "Lambda pricing is based on the number of requests and the duration your code executes, measured in GB-seconds (memory allocated × execution time).",
        "reference": "https://aws.amazon.com/lambda/pricing/",
        "points": 1,
        "answers": [
            {"text": "Per-request and duration-based pricing", "is_correct": True},
            {"text": "Fixed monthly pricing", "is_correct": False},
            {"text": "Storage-based pricing", "is_correct": False},
            {"text": "Bandwidth-based pricing", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of API Gateway authorizers?",
        "explanation": "API Gateway authorizers control access to your APIs by validating incoming requests using Lambda functions or Amazon Cognito user pools.",
        "reference": "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access.html",
        "points": 1,
        "answers": [
            {"text": "Control API access and authentication", "is_correct": True},
            {"text": "Transform API requests", "is_correct": False},
            {"text": "Monitor API performance", "is_correct": False},
            {"text": "Cache API responses", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides application performance monitoring?",
        "explanation": "AWS X-Ray provides application performance monitoring and debugging capabilities for distributed applications by tracing requests across services.",
        "reference": "https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html",
        "points": 1,
        "answers": [
            {"text": "Amazon CloudWatch", "is_correct": False},
            {"text": "AWS X-Ray", "is_correct": True},
            {"text": "AWS CloudTrail", "is_correct": False},
            {"text": "AWS Config", "is_correct": False},
        ],
    },
    {
        "text": "What is the purpose of DynamoDB Local Secondary Index (LSI)?",
        "explanation": "A Local Secondary Index enables querying on different sort key attributes while maintaining the same partition key, providing alternative query patterns.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LSI.html",
        "points": 1,
        "answers": [
            {
                "text": "Query with alternative sort key on same partition",
                "is_correct": True,
            },
            {"text": "Improve read performance", "is_correct": False},
            {"text": "Enable cross-region access", "is_correct": False},
            {"text": "Reduce storage costs", "is_correct": False},
        ],
    },
    {
        "text": "Which AWS service provides managed Apache Kafka?",
        "explanation": "Amazon Managed Streaming for Apache Kafka (MSK) is a fully managed service that makes it easy to build and run applications that use Apache Kafka.",
        "reference": "https://docs.aws.amazon.com/msk/latest/developerguide/what-is-msk.html",
        "points": 1,
        "answers": [
            {"text": "Amazon Kinesis", "is_correct": False},
            {"text": "Amazon MSK", "is_correct": True},
            {"text": "Amazon SQS", "is_correct": False},
            {"text": "Amazon EventBridge", "is_correct": False},
        ],
    },
    {
        "text": "What is the maximum payload size for Lambda synchronous invocations?",
        "explanation": "Lambda synchronous invocations support a maximum payload size of 6 MB for both request and response.",
        "reference": "https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html",
        "points": 1,
        "answers": [
            {"text": "1 MB", "is_correct": False},
            {"text": "6 MB", "is_correct": True},
            {"text": "10 MB", "is_correct": False},
            {"text": "256 KB", "is_correct": False},
        ],
    },
    {
        "text": "Which feature allows DynamoDB to automatically handle traffic spikes?",
        "explanation": "DynamoDB On-Demand mode automatically scales up and down based on application traffic, handling sudden traffic spikes without capacity planning.",
        "reference": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html",
        "points": 1,
        "answers": [
            {"text": "Auto Scaling", "is_correct": False},
            {"text": "On-Demand mode", "is_correct": True},
            {"text": "Provisioned mode", "is_correct": False},
            {"text": "Global Tables", "is_correct": False},
        ],
    },
    {
        "text": "What is AWS Amplify used for?",
        "explanation": "AWS Amplify is a set of tools and services for building scalable full-stack applications, with features for frontend deployment, backend services, and CI/CD.",
        "reference": "https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html",
        "points": 1,
        "answers": [
            {"text": "Building full-stack applications", "is_correct": True},
            {"text": "Database management only", "is_correct": False},
            {"text": "API monitoring", "is_correct": False},
            {"text": "File storage", "is_correct": False},
        ],
    },
]
